Repository numpy/numpy, pull requests merged in 2020-02, with the labels that each got.

#14867 ENH: Use AVX-512F for np.maximum and np.minimum
  benchmarks/benchmarks/bench_avx.py
  numpy/core/code_generators/generate_umath.py
  numpy/core/src/umath/loops.c.src
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/simd.inc.src
  numpy/core/tests/test_umath.py
Labels: 01 - Enhancement, Triaged, component: numpy.core

#15427 DEP: Schedule unused C-API functions for removal/disabling
  doc/release/upcoming_changes/15427.deprecation.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/ufunc.rst
  numpy/core/src/multiarray/arrayobject.c
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/ctors.h
  numpy/core/src/umath/ufunc_object.c
Labels: 07 - Deprecation, 63 - C API

#15483 [DOC] Mention behaviour of np.squeeze with one element
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#15484 ENH: fixing generic error messages to be more specific in multiarray/descriptor.c
  numpy/core/src/multiarray/descriptor.c
Labels: 01 - Enhancement

#15491 TST: mark the top 3 slowest tests to save ~10 seconds
  numpy/core/tests/test_mem_overlap.py
  numpy/core/tests/test_multiarray.py
  numpy/linalg/tests/test_linalg.py
Labels: 05 - Testing

#15500 MAINT: Use True/False instead of 1/0 in np.dtype.__reduce__
  numpy/core/src/multiarray/descriptor.c
Labels: 03 - Maintenance

#15430 MAINT: Use contextmanager in _run_doctests
  tools/refguide_check.py
Labels: 03 - Maintenance, component: Other

#15503 MAINT: Do not allow `copyswap` and friends to fail silently
  numpy/core/src/multiarray/arraytypes.c.src
Labels: 03 - Maintenance, component: numpy.dtype

#15510 DOC: Update unique docstring example
  numpy/lib/arraysetops.py
Labels: 04 - Documentation, component: numpy.lib

#15408 ENH: Use AVX-512F for complex number arithmetic, absolute, square and conjugate
  benchmarks/benchmarks/bench_avx.py
  numpy/core/code_generators/generate_umath.py
  numpy/core/src/umath/loops.c.src
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/simd.inc.src
  numpy/core/tests/test_umath_complex.py
Labels: 01 - Enhancement, component: numpy.core

#15522 MAINT: Fix internal misuses of `NPY_TITLE_KEY`
  numpy/core/src/multiarray/arrayobject.c
  numpy/core/src/multiarray/descriptor.c
  numpy/core/src/multiarray/methods.c
  numpy/core/src/multiarray/refcount.c
  numpy/core/src/multiarray/shape.c
Labels: 03 - Maintenance

#15521 MAINT: Simplify arraydescr_richcompare
  numpy/core/src/multiarray/descriptor.c
Labels: 03 - Maintenance, component: numpy.dtype

#15468 BUG: Fix for SVD not always sorted with hermitian=True
  numpy/linalg/linalg.py
  numpy/linalg/tests/test_linalg.py
Labels: 00 - Bug, component: numpy.linalg

#15511 MAINT: Large overhead in some random functions
  numpy/random/_bounded_integers.pyx.in
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
Labels: 03 - Maintenance, 06 - Regression, 09 - Backport-Candidate

#15465 MAINT: cleanup unused imports; avoid redefinition of imports
  benchmarks/benchmarks/bench_random.py
  benchmarks/benchmarks/bench_records.py
  doc/neps/tools/build_index.py
  doc/postprocess.py
  doc/source/conf.py
  doc/source/user/plots/matplotlib3.py
  numpy/core/_type_aliases.py
  numpy/core/code_generators/generate_ufunc_api.py
  numpy/core/function_base.py
  numpy/core/setup.py
  numpy/core/umath.py
  numpy/distutils/command/build_clib.py
  numpy/distutils/command/build_ext.py
  numpy/distutils/core.py
  numpy/distutils/extension.py
  numpy/distutils/fcompiler/__init__.py
  numpy/distutils/fcompiler/environment.py
  numpy/distutils/fcompiler/gnu.py
  numpy/distutils/fcompiler/pg.py
  numpy/distutils/mingw32ccompiler.py
  numpy/distutils/npy_pkg_config.py
  numpy/distutils/system_info.py
  numpy/distutils/tests/test_fcompiler.py
  numpy/distutils/tests/test_shell_utils.py
  numpy/f2py/__init__.py
  numpy/f2py/capi_maps.py
  numpy/f2py/tests/test_crackfortran.py
  numpy/f2py/tests/test_quoted_character.py
  numpy/fft/tests/test_helper.py
  numpy/fft/tests/test_pocketfft.py
  numpy/lib/_datasource.py
  numpy/ma/mrecords.py
  numpy/random/tests/test_extending.py
  numpy/testing/_private/parameterized.py
  numpy/testing/tests/test_utils.py
  numpy/tests/test_reloading.py
  numpy/tests/test_scripts.py
  numpy/tests/test_warnings.py
  pavement.py
  runtests.py
  setup.py
  tools/openblas_support.py
  tools/refguide_check.py
  tools/swig/test/setup.py
  tools/swig/test/testArray.py
  tools/swig/test/testFlat.py
  tools/swig/test/testFortran.py
  tools/swig/test/testMatrix.py
  tools/swig/test/testSuperTensor.py
  tools/swig/test/testTensor.py
  tools/swig/test/testVector.py
Labels: 03 - Maintenance

#15550 DOC: Improve the `numpy.linalg.eig` docstring.
  numpy/linalg/linalg.py
Labels: 04 - Documentation, component: numpy.linalg

#15189 ENH: Add property-based tests using Hypothesis
  INSTALL.rst.txt
  doc/TESTS.rst.txt
  numpy/conftest.py
  numpy/core/tests/test_arrayprint.py
  numpy/core/tests/test_numeric.py
  test_requirements.txt
Labels: 05 - Testing, component: Documentation, component: numpy.core

#15560 BUG, DOC: restore missing import
  numpy/core/multiarray.py
  numpy/core/umath.py
Labels: 00 - Bug, 04 - Documentation

#15553 BUG: Added missing error check in `ndarray.__contains__`
  numpy/core/src/multiarray/sequence.c
Labels: 00 - Bug, 09 - Backport-Candidate, component: numpy.core

#15385 BUG, MAINT: Stop using the error-prone deprecated Py_UNICODE apis
  doc/release/upcoming_changes/15385.new_feature.rst
  numpy/core/defchararray.py
  numpy/core/include/numpy/arrayscalars.h
  numpy/core/src/common/ucsnarrow.c
  numpy/core/src/common/ucsnarrow.h
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/buffer.c
  numpy/core/src/multiarray/common.c
  numpy/core/src/multiarray/scalarapi.c
  numpy/core/src/multiarray/scalartypes.c.src
  numpy/core/tests/test_multiarray.py
  numpy/core/tests/test_scalarbuffer.py
Labels: 00 - Bug, Triage-review

#15574 TST: Do not create symbolic link named gfortran.
  azure-pipelines.yml
Labels: 05 - Testing, component: CI, component: build

#15575 DOC: Document caveat in random.uniform
  numpy/random/mtrand.pyx
Labels: 04 - Documentation

#15566 DOC: Removing bad practices from quick start + some PEP8
  doc/source/user/quickstart.rst
Labels: 04 - Documentation, component: Documentation

#15549 TST: Accuracy test float32 sin/cos/exp/log for AVX platforms
  benchmarks/benchmarks/bench_avx.py
  numpy/core/tests/test_umath_accuracy.py
Labels: 05 - Testing, component: numpy.core

#15585 BLD: manylinux2010 docker reports machine=i686
  tools/openblas_support.py
Labels: component: build

#15543 NEP: edit and move NEP 38 to accepted status
  doc/neps/Makefile
  doc/neps/nep-0038-SIMD-optimizations.rst
Labels: component: NEP

#15554 NEP 44 - Restructuring the NumPy Documentation
  doc/neps/nep-0044-restructuring-numpy-docs.rst
Labels: 04 - Documentation, component: NEP

#15598 BUG: Ignore differences in NAN for computing ULP differences
  numpy/core/tests/data/umath-validation-set-cos
  numpy/core/tests/data/umath-validation-set-sin
  numpy/core/tests/test_umath_accuracy.py
  numpy/testing/_private/utils.py
Labels: 00 - Bug, component: numpy.testing

#15600 TST: use manylinux2010 docker instead of ubuntu
  azure-pipelines.yml
Labels: 03 - Maintenance, 05 - Testing, component: CI

#15619 DOC: Fix documentation for apply_along_axis
  numpy/lib/shape_base.py
Labels: 03 - Maintenance, 04 - Documentation, component: numpy.lib

#15615 BUG: Remove check requiring natural alignment of float/double to run AVX code
  numpy/core/src/umath/simd.inc.src
Labels: 00 - Bug, 05 - Testing, component: numpy.core

#15633 DOC: remove broken link in f2py tutorial
  doc/source/f2py/getting-started.rst
Labels: 04 - Documentation, component: Documentation, component: numpy.f2py

#15579 DOC: numpy.clip is equivalent to minimum(..., maximum(...))
  numpy/core/fromnumeric.py
Labels: 04 - Documentation, component: numpy.core

#15612 BUG: Fix bug in AVX-512F np.maximum and np.minimum
  numpy/core/src/umath/simd.inc.src
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, component: numpy.core

#15610 TST: mask DeprecationWarning in xfailed test
  numpy/core/tests/test_numeric.py
Labels: 05 - Testing

#15624 DOC: fix printing, np., deprecation for refguide
  doc/source/reference/arrays.dtypes.rst
Labels: 04 - Documentation, component: Documentation

#15639 BLD: update openblas download to new location, use manylinux2010-base
  azure-pipelines.yml
  azure-steps-windows.yml
  shippable.yml
  tools/openblas_support.py
  tools/pypy-test.sh
  tools/travis-before-install.sh
Labels: component: build

#15547 MAINT: Refresh Doxyfile and modernize numpyfilter.py
  doc/cdoc/Doxyfile
  doc/cdoc/Makefile
  doc/cdoc/numpyfilter.py
Labels: component: Documentation

#14995 BUG: Use ``__array__`` during dimension discovery
  doc/release/upcoming_changes/14995.compatibility.rst
  numpy/core/src/multiarray/ctors.c
  numpy/core/tests/test_regression.py
Labels: 00 - Bug, 58 - Ready for review, Triaged

#15577 TST: Test division by zero both with scalar and with array
  numpy/core/tests/test_errstate.py
Labels: 05 - Testing, component: numpy.core

#15504 DOC: Remove duplicated code in true_divide docstring
  numpy/core/code_generators/ufunc_docstrings.py
Labels: 04 - Documentation, component: numpy.core

#12646 TST: check exception details in refguide_check.py
  numpy/core/multiarray.py
  tools/refguide_check.py
Labels: 04 - Documentation, 05 - Testing

#15665 BUG: fix doctest exception messages
  numpy/lib/function_base.py
  numpy/random/_generator.pyx
  numpy/testing/_private/utils.py
Labels: 00 - Bug, component: Documentation

#15295 DOC: Added tutorial about linear algebra on multidimensional arrays
  doc/source/conf.py
  doc/source/user/index.rst
  doc/source/user/plot_approx.py
  doc/source/user/plot_face.py
  doc/source/user/plot_final.py
  doc/source/user/plot_gray.py
  doc/source/user/plot_gray_svd.py
  doc/source/user/plot_reconstructed.py
  doc/source/user/tutorial-svd.rst
Labels: 04 - Documentation, component: numpy.linalg

#15644 DOC: Update to clarify actual behavior real_if_(all elements)_close
  numpy/lib/type_check.py
Labels: 04 - Documentation, component: numpy.lib
