Repository numpy/numpy, pull requests merged in 2020-12, with the labels that each got.

#17893 DOC: Prepare for 1.20.0 release
  doc/changelog/1.20.0-changelog.rst
  doc/release/upcoming_changes/13516.performance.rst
  doc/release/upcoming_changes/14882.deprecation.rst
  doc/release/upcoming_changes/15121.new_function.rst
  doc/release/upcoming_changes/15666.improvement.rst
  doc/release/upcoming_changes/15759.improvement.rst
  doc/release/upcoming_changes/15852.new_feature.rst
  doc/release/upcoming_changes/15886.deprecation.rst
  doc/release/upcoming_changes/15900.deprecation.rst
  doc/release/upcoming_changes/15997.improvement.rst
  doc/release/upcoming_changes/16056.deprecation.rst
  doc/release/upcoming_changes/16134.compatibility.rst
  doc/release/upcoming_changes/16134.improvement.rst
  doc/release/upcoming_changes/16156.deprecation.rst
  doc/release/upcoming_changes/16161.change.rst
  doc/release/upcoming_changes/16200.compatibility.rst
  doc/release/upcoming_changes/16232.deprecation.rst
  doc/release/upcoming_changes/16350.compatibility.rst
  doc/release/upcoming_changes/16476.new_feature.rst
  doc/release/upcoming_changes/16515.new_feature.rst
  doc/release/upcoming_changes/16519.improvement.rst
  doc/release/upcoming_changes/16554.compatibility.rst
  doc/release/upcoming_changes/16554.deprecation.rst
  doc/release/upcoming_changes/16554.expired.rst
  doc/release/upcoming_changes/16558.new_feature.rst
  doc/release/upcoming_changes/16570.compatibility.rst
  doc/release/upcoming_changes/16589.compatibility.rst
  doc/release/upcoming_changes/16592.compatibility.rst
  doc/release/upcoming_changes/16594.new_feature.rst
  doc/release/upcoming_changes/16650.compatibility.rst
  doc/release/upcoming_changes/16675.improvement.rst
  doc/release/upcoming_changes/16710.improvement.rst
  doc/release/upcoming_changes/16730.improvement.rst
  doc/release/upcoming_changes/16815.compatibility.rst
  doc/release/upcoming_changes/16841.change.rst
  doc/release/upcoming_changes/16938.c_api.rst
  doc/release/upcoming_changes/16986.improvement.rst
  doc/release/upcoming_changes/17010.compatibility.rst
  doc/release/upcoming_changes/17029.compatibility.rst
  doc/release/upcoming_changes/17067.expired.rst
  doc/release/upcoming_changes/17068.compatibility.rst
  doc/release/upcoming_changes/17116.expired.rst
  doc/release/upcoming_changes/17123.new_feature.rst
  doc/release/upcoming_changes/17195.improvement.rst
  doc/release/upcoming_changes/17219.new_feature.rst
  doc/release/upcoming_changes/17233.deprecation.rst
  doc/release/upcoming_changes/17241.compatibility.rst
  doc/release/upcoming_changes/17284.new_feature.rst
  doc/release/upcoming_changes/17344.new_feature.rst
  doc/release/upcoming_changes/17394.new_function.rst
  doc/release/upcoming_changes/17456.new_feature.rst
  doc/release/upcoming_changes/17535.new_function.rst
  doc/release/upcoming_changes/17577.compatibility.rst
  doc/release/upcoming_changes/17580.compatibility.rst
  doc/release/upcoming_changes/17596.future.rst
  doc/release/upcoming_changes/17706.compatibility.rst
  doc/source/release/1.20.0-notes.rst
Labels: 04 - Documentation, 14 - Release, component: Documentation

#17791 BLD: Enable Werror=undef in travis
  numpy/core/include/numpy/npy_common.h
  numpy/core/include/numpy/npy_math.h
  numpy/core/src/umath/loops.c.src
  numpy/core/src/umath/simd.inc.src
  numpy/core/src/umath/ufunc_type_resolution.c
  numpy/random/src/pcg64/pcg64.h
  tools/travis-test.sh
Labels: 36 - Build

#17727 ENH: Added libdivide for floor divide
  .gitattributes
  LICENSES_bundled.txt
  benchmarks/benchmarks/bench_ufunc.py
  doc/release/upcoming_changes/17727.performance.rst
  numpy/core/include/numpy/libdivide/LICENSE.txt
  numpy/core/include/numpy/libdivide/libdivide.h
  numpy/core/src/umath/fast_loop_macros.h
  numpy/core/src/umath/loops.c.src
  numpy/core/tests/test_umath.py
Labels: 01 - Enhancement, component: numpy.core

#17876 DOC: fixed typo in np-indexing.png explaining [-2:] slice in user guide
  doc/source/user/images/np_indexing.png
Labels: 04 - Documentation

#17895 MAINT: Remove remaining uses of Python 3.6.
  INSTALL.rst.txt
  setup.py
  test_requirements.txt
  tox.ini
Labels: 03 - Maintenance, 09 - Backport-Candidate

#17899 TST: use latest pypy37 not pypy36
  .github/workflows/build_test.yml
  numpy/core/src/multiarray/compiled_base.c
  test_requirements.txt
Labels: 05 - Testing, 08 - Backport, component: CI

#17874 MAINT: clean up a spurious warning in numpy/typing/setup.py
  numpy/typing/setup.py
Labels: 03 - Maintenance, 09 - Backport-Candidate, component: numpy.typing

#17901 MAINT: clean up a spurious warning in numpy/typing/setup.py
  numpy/typing/setup.py
Labels: 03 - Maintenance, 08 - Backport, component: numpy.typing

#17898 MAINT: Remove remaining uses of Python 3.6.
  INSTALL.rst.txt
  doc/changelog/1.20.0-changelog.rst
  doc/source/release/1.20.0-notes.rst
  setup.py
  test_requirements.txt
  tox.ini
Labels: 03 - Maintenance, 08 - Backport, 36 - Build

#17897 BUG: merging PR to use -Werror=undef broke another PR
  numpy/core/include/numpy/npy_common.h
Labels: 00 - Bug

#17896 ENH: Speed up default `where` in the reduce-like method
  numpy/core/_add_newdocs.py
  numpy/core/_methods.py
Labels: 01 - Enhancement, 09 - Backport-Candidate

#17792 ENH: add support for fujitsu compiler to numpy.
  numpy/distutils/fcompiler/__init__.py
  numpy/distutils/fcompiler/fujitsu.py
  numpy/tests/test_public_api.py
Labels: 01 - Enhancement, component: numpy.distutils

#17904 ENH: Speed up default `where` in the reduce-like method
  doc/changelog/1.20.0-changelog.rst
  doc/source/release/1.20.0-notes.rst
  numpy/core/_add_newdocs.py
  numpy/core/_methods.py
Labels: 01 - Enhancement, 08 - Backport

#17900 DEP: Finalize unravel_index `dims` alias for `shape` keyword
  doc/release/upcoming_changes/17900.expired.rst
  numpy/core/multiarray.py
  numpy/core/src/multiarray/compiled_base.c
  numpy/lib/tests/test_index_tricks.py
Labels: 07 - Deprecation

#17912 BUG: remove stray '+' from f-string upgrade in numba/extending.py
  numpy/random/_examples/numba/extending.py
Labels: 00 - Bug

#17878 BUG: np.arange: Allow `stop` not `start` as sole kwargs.
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug

#17914 DOC: Update release notes to mention `type(dtype) is not np.dtype`
  doc/source/release/1.20.0-notes.rst
Labels: 04 - Documentation, 09 - Backport-Candidate

#17907 BUG: 'bool' object has no attribute 'ndim'
  numpy/testing/_private/utils.py
Labels: 00 - Bug, 09 - Backport-Candidate, component: numpy.testing

#17916 ENH: add support for fujitsu compiler to numpy.
  numpy/distutils/fcompiler/__init__.py
  numpy/distutils/fcompiler/fujitsu.py
  numpy/tests/test_public_api.py
Labels: 01 - Enhancement, 08 - Backport, component: numpy.distutils

#17915 TST: remove stray '+' from f-string upgrade
  numpy/random/_examples/numba/extending.py
Labels: 00 - Bug, 05 - Testing, 08 - Backport, component: numpy.random

#17917 BUG: Fix subarray dtype used with too large count in fromfile
  numpy/core/src/multiarray/ctors.c
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug, 08 - Backport

#17918 Fix AttributeError: 'bool' object has no attribute 'ndim'
  numpy/testing/_private/utils.py
Labels: 00 - Bug, 08 - Backport, component: numpy.testing

#17919 BUG: ensure _UFuncNoLoopError can be pickled
  doc/source/user/quickstart.rst
  numpy/core/_exceptions.py
  numpy/core/tests/test__exceptions.py
Labels: 00 - Bug, 08 - Backport

#17922 BUG: 'bool' object has no attribute 'ndim'
  numpy/testing/_private/utils.py
Labels: 00 - Bug, 08 - Backport

#17924 BLD: use BUFFERSIZE=20 in OpenBLAS
  tools/openblas_support.py
Labels: 08 - Backport, 36 - Build, component: build

#17931 DOC: Update release notes to mention `type(dtype) is not np.dtype`
  doc/source/release/1.20.0-notes.rst
Labels: 04 - Documentation, 08 - Backport, component: Documentation

#17929 MAINT: Replace `contextlib_nullcontext` with `contextlib.nullcontext`
  numpy/compat/py3k.py
  numpy/core/_methods.py
  numpy/core/memmap.py
  numpy/core/records.py
  numpy/lib/npyio.py
Labels: 03 - Maintenance

#17719 ENH: Make `ndarray` generic w.r.t. its shape and dtype
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/array_constructors.py
  numpy/typing/tests/data/reveal/fromnumeric.py
  numpy/typing/tests/data/reveal/ndarray_misc.py
  numpy/typing/tests/data/reveal/numeric.py
Labels: 01 - Enhancement, component: numpy.typing, static typing

#17936 TST: Fixed an issue where the typing tests would fail for comparison operations
  numpy/typing/tests/data/reveal/comparisons.py
Labels: 00 - Bug, 05 - Testing, static typing

#17934 DOC: Add information about leak checking and valgrind
  doc/source/dev/development_advanced_debugging.rst
  doc/source/dev/development_environment.rst
  doc/source/dev/index.rst
Labels: 04 - Documentation

#17884 BUG: numpy.putmask not respecting writeable flag
  numpy/core/src/multiarray/item_selection.c
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug

#17957 TST: Fix crosstalk issues with polynomial str tests.
  numpy/polynomial/tests/test_printing.py
Labels: 05 - Testing, 09 - Backport-Candidate

#17962 TST: Ensure tests are not sensitive to execution order
  numpy/core/tests/test_overrides.py
  numpy/ma/timer_comparison.py
Labels: 00 - Bug, 05 - Testing, 09 - Backport-Candidate

#17950 BUG: Removed empty String from Nag Compiler's Flags
  numpy/distutils/fcompiler/nag.py
Labels: 00 - Bug

#17789 ENH, SIMD: Add new NPYV intrinsics pack(0)
  numpy/core/src/_simd/_simd.dispatch.c.src
  numpy/core/src/common/simd/avx2/conversion.h
  numpy/core/src/common/simd/avx2/reorder.h
  numpy/core/src/common/simd/avx512/conversion.h
  numpy/core/src/common/simd/avx512/reorder.h
  numpy/core/src/common/simd/neon/conversion.h
  numpy/core/src/common/simd/neon/reorder.h
  numpy/core/src/common/simd/sse/conversion.h
  numpy/core/src/common/simd/sse/reorder.h
  numpy/core/src/common/simd/vsx/conversion.h
  numpy/core/src/common/simd/vsx/reorder.h
  numpy/core/tests/test_simd.py
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/checks/extra_vsx_asm.c
Labels: 01 - Enhancement

#17956 ENH: Use versioneer to manage numpy versions.
  .gitattributes
  .gitignore
  MANIFEST.in
  doc/Makefile
  numpy/__init__.py
  numpy/_version.py
  numpy/core/setup_common.py
  numpy/distutils/misc_util.py
  numpy/tests/test_numpy_version.py
  numpy/version.py
  setup.cfg
  setup.py
  versioneer.py
Labels: 01 - Enhancement, 36 - Build

#17960 TST, BUILD: Add a native x86 baseline build running on ubuntu-20.04
  azure-pipelines.yml
  runtests.py
Labels: 05 - Testing

#17795 ENH: Add two new `_<X>Like` unions
  numpy/__init__.pyi
  numpy/typing/__init__.py
  numpy/typing/_callable.py
  numpy/typing/_scalars.py
Labels: 01 - Enhancement, component: numpy.typing, static typing

#17966 BUG: Add missing decref to arange
  numpy/core/src/multiarray/multiarraymodule.c
Labels: 00 - Bug

#17971 BUG, SIMD: Fix direactive check for AVX512BW of intrinsics npyv_tobits_*
  numpy/core/src/common/simd/avx512/conversion.h
Labels: 00 - Bug

#17978 MAINT: Update test_requirements and release_requirements.
  release_requirements.txt
  test_requirements.txt
Labels: 03 - Maintenance, 05 - Testing, 14 - Release

#17968 ENH: Use more typevars in `np.dtype`
  numpy/__init__.pyi
  numpy/typing/tests/data/pass/dtype.py
  numpy/typing/tests/data/reveal/dtype.py
Labels: 01 - Enhancement, static typing

#17981 ENH: Add proper dtype-support to `np.flatiter`
  numpy/__init__.pyi
  numpy/typing/_array_like.py
  numpy/typing/tests/data/fail/array_like.py
  numpy/typing/tests/data/pass/array_like.py
  numpy/typing/tests/data/pass/flatiter.py
  numpy/typing/tests/data/reveal/flatiter.py
Labels: 01 - Enhancement, static typing

#17955 DOC: Replace {var} in docstrings type annotation with `scalar or None`.
  numpy/ma/core.py
Labels: 04 - Documentation, component: numpy.ma

#17990 BUG: Replace f-string in setup.py
  setup.py
Labels: 00 - Bug, 36 - Build, component: build

#17906 BUG: Fix a MacOS build failure
  numpy/distutils/fcompiler/gnu.py
Labels: 00 - Bug, component: numpy.distutils

#17888 DOC: Correct sentence/statement composition
  doc/source/user/theory.broadcasting.rst
Labels: 04 - Documentation, component: Documentation

#17974 BLD: Fixes for versioneer and setup.py sdist.
  numpy/_version.py
  setup.py
  versioneer.py
Labels: 36 - Build, component: build

#17992 DOC: Replace verbatim with reference to local parameter
  numpy/core/function_base.py
Labels: 04 - Documentation, component: numpy.core

#17998 TST: ignore pytest warning
  pytest.ini
Labels: 05 - Testing

#17942 DOC: Clarify savez documentation of naming arrays in output file
  numpy/lib/npyio.py
Labels: 04 - Documentation, component: numpy.lib

#17921 BUG: Enforce high >= low on uniform number generators
  doc/release/upcoming_changes/17921.compatibility.rst
  numpy/random/_generator.pyx
  numpy/random/tests/test_generator_mt19937.py
Labels: 00 - Bug, 56 - Needs Release Note.

#16164 DOC: Add more information about poly1d -> polynomial to reference guide
  doc/source/reference/routines.polynomials.rst
Labels: 04 - Documentation, component: numpy.polynomial

#16855 DOC: Fix Typo (Wrong argument name)
  numpy/core/_add_newdocs.py
Labels: 03 - Maintenance, 04 - Documentation, component: numpy.core

#16241 DOC: Warn when reloading numpy or using numpy in sub-interpreter
  numpy/__init__.py
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/tests/test_reloading.py
Labels: 04 - Documentation, component: numpy.core

#16818 DOC: added examples section for rfft2 and irfft2 docstring
  numpy/fft/_pocketfft.py
Labels: 04 - Documentation, component: numpy.fft

#17637 DOC: Add module template
  doc/source/_templates/autosummary/module.rst
Labels: 04 - Documentation, component: Documentation

#16370 DOC: Fix for building with sphinx 3
  doc/source/conf.py
  doc/source/reference/arrays.scalars.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/coremath.rst
  doc/source/reference/c-api/dtype.rst
  doc/source/reference/c-api/iterator.rst
  doc/source/reference/c-api/types-and-structures.rst
  doc/source/reference/random/bit_generators/mt19937.rst
  doc/source/reference/random/bit_generators/pcg64.rst
  doc/source/reference/random/bit_generators/philox.rst
  doc/source/reference/random/bit_generators/sfc64.rst
  doc/source/reference/random/generator.rst
  doc/source/reference/random/legacy.rst
  doc/source/user/c-info.beyond-basics.rst
  doc/source/user/c-info.how-to-extend.rst
  doc_requirements.txt
Labels: 03 - Maintenance, 04 - Documentation, component: Documentation

#18002 DOC: Fix and extend the docstring for np.inner
  numpy/core/multiarray.py
Labels: 04 - Documentation

#17976 DOC: Add/remove spaces in snippets and re-format here and there
  doc/source/user/quickstart.rst
Labels: 04 - Documentation, component: Documentation

#18008 DOC: fix for doctests
  doc/source/user/quickstart.rst
Labels: 04 - Documentation, component: Documentation

#17817 BUG: Ignore fewer errors during array-coercion
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/tests/test_array_coercion.py
Labels: 00 - Bug

#17736 BUG, Benchmark: fix passing optimization build options to asv
  benchmarks/asv_compare.conf.json.tpl
  benchmarks/asv_pip_nopep517.py
  runtests.py
Labels: 00 - Bug, 01 - Enhancement, Triage-review

#18011 BLD: update to OpenBLAS 0.3.13
  tools/openblas_support.py
Labels: 36 - Build

#17852 DOC: Doc for deprecate_with_doc
  numpy/lib/tests/test_utils.py
  numpy/lib/utils.py
  numpy/tests/test_public_api.py
Labels: 04 - Documentation, component: numpy.lib

#18019 BLD: update to OpenBLAS 0.3.13
  tools/openblas_support.py
Labels: 08 - Backport, 36 - Build

#18018 TST: Ensure tests are not sensitive to execution order
  numpy/core/tests/test_overrides.py
  numpy/ma/timer_comparison.py
Labels: 00 - Bug, 05 - Testing, 08 - Backport

#18017 TST: Fix crosstalk issues with polynomial str tests.
  numpy/polynomial/tests/test_printing.py
Labels: 05 - Testing, 08 - Backport

#18016 BUG: Fix a MacOS build failure
  numpy/distutils/fcompiler/gnu.py
Labels: 00 - Bug, 08 - Backport, component: numpy.distutils

#18015 BUG: Ignore fewer errors during array-coercion
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/tests/test_array_coercion.py
Labels: 00 - Bug, 08 - Backport, component: numpy.core

#17973 DEP: Futurewarn on requiring __len__ on array-likes
  doc/source/release/1.20.0-notes.rst
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/tests/test_array_coercion.py
  numpy/core/tests/test_deprecations.py
Labels: 07 - Deprecation, 09 - Backport-Candidate

#18024 DEP: Futurewarn on requiring __len__ on array-likes
  doc/source/release/1.20.0-notes.rst
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/tests/test_array_coercion.py
  numpy/core/tests/test_deprecations.py
Labels: 07 - Deprecation, 08 - Backport

#18026 BLD: update to OpenBLAS 0.3.13
  tools/openblas_support.py
Labels: 08 - Backport, 36 - Build

#18031 DOC: Parameter name typo axes -> axis in numpy.fft._pocketfft.
  numpy/fft/_pocketfft.py
Labels: 04 - Documentation

#18027 DOC, MAINT: Minor fixes to refguide_check.py documentation.
  tools/refguide_check.py
Labels: 03 - Maintenance, 04 - Documentation

#18034 DOC: Fix a couple of reference to verbatim and vice versa
  numpy/core/code_generators/ufunc_docstrings.py
  numpy/lib/polynomial.py
  numpy/lib/scimath.py
  numpy/polynomial/polynomial.py
  numpy/testing/_private/utils.py
Labels: 04 - Documentation

#18030 BUG: make a variable volatile to work around clang compiler bug
  numpy/core/src/umath/simd.inc.src
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, 09 - Backport-Candidate

#18032 ENH: Add annotations for `np.core.arrayprint`
  numpy/__init__.pyi
  numpy/core/arrayprint.py
  numpy/core/arrayprint.pyi
  numpy/typing/tests/data/fail/arrayprint.py
  numpy/typing/tests/data/pass/arrayprint.py
  numpy/typing/tests/data/reveal/arrayprint.py
Labels: 01 - Enhancement, static typing

#17102 SIMD: Optimize the performance of np.packbits in AVX2/AVX512F/VSX.
  benchmarks/benchmarks/bench_core.py
  numpy/core/include/numpy/npy_common.h
  numpy/core/src/common/simd/avx2/avx2.h
  numpy/core/src/multiarray/compiled_base.c
Labels: 01 - Enhancement, Triaged, component: SIMD, component: numpy.core

#18014 DOC: random: add some examples for SeedSequence
  doc/source/reference/random/bit_generators/index.rst
Labels: 04 - Documentation

#18035 BUG: make a variable volatile to work around clang compiler bug
  numpy/core/src/umath/simd.inc.src
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, 08 - Backport

#18036 BUG: make a variable volatile to work around clang compiler bug
  numpy/core/src/umath/simd.inc.src
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, 08 - Backport, component: build

#17985 ENH, SIMD: Ditching the old CPU dispatcher(Arithmetic)
  .gitignore
  numpy/core/code_generators/generate_umath.py
  numpy/core/setup.py
  numpy/core/src/umath/fast_loop_macros.h
  numpy/core/src/umath/loops.c.src
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/loops_arithm_fp.dispatch.c.src
  numpy/core/src/umath/loops_utils.h
  numpy/core/src/umath/loops_utils.h.src
  numpy/core/src/umath/simd.inc.src
Labels: 01 - Enhancement

#18047 BLD,DOC: pin sphinx to 3.3.1
  doc_requirements.txt
Labels: 36 - Build

#18046 TST: add back sdist test run
  .github/workflows/build_test.yml
Labels: 05 - Testing, 09 - Backport-Candidate, component: CI

#18049 TST: add back sdist test run
  .github/workflows/build_test.yml
Labels: 05 - Testing, 08 - Backport, component: CI

#18054 DOC: Update stack docstrings
  numpy/core/shape_base.py
Labels: 04 - Documentation

#18048 DOC: Update TESTS.rst.txt
  doc/TESTS.rst.txt
Labels: 04 - Documentation

#18050 MAINT: Add aliases for commonly used `ArrayLike` objects
  numpy/typing/__init__.py
  numpy/typing/_array_like.py
Labels: 03 - Maintenance, static typing

#17843 ENH: Add a mypy plugin for inferring platform-specific `np.number` precisions
  doc/release/upcoming_changes/17843.new_feature.rst
  numpy/__init__.pyi
  numpy/core/fromnumeric.pyi
  numpy/tests/test_public_api.py
  numpy/typing/__init__.py
  numpy/typing/_callable.py
  numpy/typing/_char_codes.py
  numpy/typing/_nbit.py
  numpy/typing/mypy_plugin.py
  numpy/typing/tests/data/mypy.ini
  numpy/typing/tests/data/pass/scalars.py
  numpy/typing/tests/data/reveal/arithmetic.py
  numpy/typing/tests/data/reveal/bitwise_ops.py
  numpy/typing/tests/data/reveal/dtype.py
  numpy/typing/tests/data/reveal/fromnumeric.py
  numpy/typing/tests/data/reveal/mod.py
  numpy/typing/tests/data/reveal/ndarray_misc.py
  numpy/typing/tests/data/reveal/scalars.py
Labels: 01 - Enhancement, static typing

#18057 BLD: ensure we give the right error message for old Python versions
  setup.py
Labels: 36 - Build

#17958 MAINT: Optimize the performance of count_nonzero by using universal intrinsics
  numpy/core/src/_simd/_simd.dispatch.c.src
  numpy/core/src/common/simd/avx2/arithmetic.h
  numpy/core/src/common/simd/avx2/conversion.h
  numpy/core/src/common/simd/avx512/arithmetic.h
  numpy/core/src/common/simd/avx512/conversion.h
  numpy/core/src/common/simd/neon/arithmetic.h
  numpy/core/src/common/simd/neon/conversion.h
  numpy/core/src/common/simd/sse/arithmetic.h
  numpy/core/src/common/simd/sse/conversion.h
  numpy/core/src/common/simd/vsx/arithmetic.h
  numpy/core/src/common/simd/vsx/conversion.h
  numpy/core/src/multiarray/item_selection.c
  numpy/core/tests/test_simd.py
Labels: 03 - Maintenance, component: numpy.core

#18052 BUG: Fix concatenation when the output is "S" or "U"
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/convert_datatype.h
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/tests/test_shape_base.py
Labels: 00 - Bug, 09 - Backport-Candidate

#18063 BUG: Fix concatenation when the output is "S" or "U"
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/convert_datatype.h
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/tests/test_shape_base.py
Labels: 00 - Bug, 08 - Backport

#18001 BLD, BUG: Fix detecting aarch64 on macOS
  doc/source/reference/simd/simd-optimizations.py
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/tests/test_ccompiler_opt.py
  numpy/distutils/tests/test_ccompiler_opt_conf.py
Labels: 09 - Backport-Candidate, 36 - Build

#18064 BLD, BUG: Fix detecting aarch64 on macOS
  doc/source/reference/simd/simd-optimizations.py
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/tests/test_ccompiler_opt.py
  numpy/distutils/tests/test_ccompiler_opt_conf.py
Labels: 00 - Bug, 08 - Backport, 36 - Build

#18067 MAINT: Remove obsolete workaround to set ndarray.__hash__ = None
  numpy/core/src/multiarray/arrayobject.c
  numpy/core/src/multiarray/multiarraymodule.c
Labels: 03 - Maintenance

#18068 REL: Prepare for 1.20.0rc2 release.
  .mailmap
  doc/changelog/1.20.0-changelog.rst
  doc/source/release/1.20.0-notes.rst
Labels: 04 - Documentation, 14 - Release

#18066 TST: Allow mypy output types to be specified via aliases
  numpy/typing/tests/data/reveal/arithmetic.py
  numpy/typing/tests/data/reveal/bitwise_ops.py
  numpy/typing/tests/data/reveal/dtype.py
  numpy/typing/tests/data/reveal/fromnumeric.py
  numpy/typing/tests/data/reveal/mod.py
  numpy/typing/tests/data/reveal/nbit_base_example.py
  numpy/typing/tests/data/reveal/ndarray_misc.py
  numpy/typing/tests/data/reveal/scalars.py
  numpy/typing/tests/test_typing.py
Labels: 01 - Enhancement, 05 - Testing, static typing

#17587 SIMD: Replace raw SIMD of sin/cos with NPYV(universal intrinsics)
  .gitignore
  benchmarks/benchmarks/bench_ufunc_strides.py
  numpy/core/code_generators/generate_umath.py
  numpy/core/include/numpy/npy_math.h
  numpy/core/setup.py
  numpy/core/src/common/simd/vsx/vsx.h
  numpy/core/src/umath/loops.c.src
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/loops_trigonometric.dispatch.c.src
  numpy/core/src/umath/loops_utils.h.src
  numpy/core/src/umath/npy_simd_data.h
  numpy/core/src/umath/simd.inc.src
Labels: 01 - Enhancement, component: SIMD

#18072 MAINT: crackfortran regex simplify
  numpy/f2py/crackfortran.py
Labels: 03 - Maintenance, component: numpy.f2py

#18074 MAINT: exprtype regex simplify
  numpy/f2py/crackfortran.py
Labels: 03 - Maintenance, component: numpy.f2py

#18077 NEP: mark NEP 28 on website redesign as final
  doc/neps/nep-0028-website-redesign.rst
Labels: component: NEP

#18042 MAINT: Add dist_info to "other" setup.py commands.
  setup.py
Labels: 03 - Maintenance, 36 - Build

#18078 Fix build warnings in NEPs
  doc/neps/nep-0010-new-iterator-ufunc.rst
  doc/neps/nep-0035-array-creation-dispatch-with-array-function.rst
  doc/neps/nep-0036-fair-play.rst
Labels: 03 - Maintenance, 04 - Documentation

#18007 DOC: Add a brief explanation of float printing
  doc/source/reference/arrays.scalars.rst
  doc/source/user/basics.types.rst
Labels: 04 - Documentation

#18083 MAINT: regex char class improve
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/command/build_src.py
  numpy/distutils/conv_template.py
  numpy/distutils/extension.py
  numpy/distutils/fcompiler/__init__.py
  numpy/distutils/fcompiler/ibm.py
  numpy/distutils/from_template.py
  numpy/distutils/misc_util.py
  numpy/f2py/crackfortran.py
  numpy/f2py/f2py2e.py
  numpy/lib/polynomial.py
  tools/commitstats.py
Labels: 03 - Maintenance

#18088 DOC: Update reference to verbatim in a few location.
  numpy/polynomial/_polybase.py
  numpy/polynomial/chebyshev.py
  numpy/polynomial/hermite.py
  numpy/polynomial/hermite_e.py
  numpy/polynomial/laguerre.py
  numpy/polynomial/legendre.py
  numpy/polynomial/polynomial.py
Labels: 04 - Documentation

#18051 DEP: deprecate np.testing.dec
  numpy/core/tests/test_deprecations.py
  numpy/testing/_private/decorators.py
  numpy/testing/tests/test_decorators.py
Labels: 07 - Deprecation

#18090 MAINT: multiline regex class simplify
  numpy/core/code_generators/genapi.py
  numpy/f2py/capi_maps.py
  numpy/f2py/crackfortran.py
  numpy/f2py/f2py2e.py
  numpy/lib/_version.py
  numpy/linalg/lapack_lite/clapack_scrub.py
Labels: 03 - Maintenance

#18091 DOC: Avoid using "set of" when talking about an ordered list.
  benchmarks/benchmarks/bench_app.py
  benchmarks/benchmarks/common.py
  numpy/core/fromnumeric.py
  numpy/core/src/multiarray/methods.c
  numpy/lib/function_base.py
  numpy/lib/histograms.py
  numpy/ma/core.py
  numpy/ma/extras.py
  numpy/polynomial/_polybase.py
  numpy/testing/_private/parameterized.py
  tools/npy_tempita/__init__.py
  tools/refguide_check.py
Labels: 04 - Documentation

#18062 DOC: add missing details to linalg.lstsq docstring
  numpy/linalg/linalg.py
Labels: 04 - Documentation
