Repository numpy/numpy, pull requests merged in 2020-10, with the labels that each got.

#17406 ENH: Replace the module-level `__getattr__` with explicit type annotations #17367
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/modules.py
Labels: 01 - Enhancement, static typing

#17411 TST: Mark the typing tests as slow
  numpy/typing/tests/test_typing.py
Labels: 05 - Testing, static typing

#17405 MAINT: Replace PyUString_ConcatAndDel in mapping.c.
  numpy/core/src/multiarray/mapping.c
Labels: 03 - Maintenance, 27 - Py3K, component: numpy.core

#17326 ENH: Add annotations for five array construction functions
  numpy/__init__.pyi
  numpy/core/_asarray.pyi
  numpy/typing/tests/data/fail/array_constructors.py
  numpy/typing/tests/data/fail/simple.py
  numpy/typing/tests/data/pass/array_constructors.py
  numpy/typing/tests/data/pass/linspace.py
  numpy/typing/tests/data/pass/literal.py
  numpy/typing/tests/data/pass/simple.py
  numpy/typing/tests/data/reveal/array_constructors.py
  numpy/typing/tests/data/reveal/linspace.py
Labels: 01 - Enhancement, static typing

#17412 DOC: Fix a parameter type in the `putmask` docs
  numpy/core/multiarray.py
Labels: 03 - Maintenance, 04 - Documentation, component: numpy.core

#17423 DOC: Remove bogus reference to _a_
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation

#17424 DOC: Fix formatting issues in description of .c.src files
  doc/DISTUTILS.rst.txt
Labels: 04 - Documentation, component: Documentation

#17422 MAINT: chains nested try-except in numpy/ma/core.py
  numpy/ma/core.py
Labels: 03 - Maintenance

#17409 MAINT: Cleanup remaining PyUString_ConcatAndDel use.
  numpy/core/src/common/array_assign.c
  numpy/core/src/multiarray/common.c
  numpy/core/src/multiarray/descriptor.c
  numpy/core/src/multiarray/scalartypes.c.src
  numpy/core/src/multiarray/shape.c
  numpy/core/src/multiarray/shape.h
  numpy/core/src/umath/ufunc_object.c
Labels: 03 - Maintenance, 27 - Py3K, component: numpy.core

#17404 MAINT: Replace PyUString_ConcatAndDel in nditer_constr.c.
  numpy/core/src/multiarray/nditer_constr.c
Labels: 03 - Maintenance, 27 - Py3K, component: numpy.core

#17273 ENH: Annotate the arithmetic operations of `ndarray` and `generic`
  numpy/__init__.pyi
  numpy/typing/_callable.py
  numpy/typing/tests/data/fail/arithmetic.py
  numpy/typing/tests/data/fail/scalars.py
  numpy/typing/tests/data/pass/arithmetic.py
  numpy/typing/tests/data/pass/scalars.py
  numpy/typing/tests/data/pass/ufuncs.py
  numpy/typing/tests/data/reveal/arithmetic.py
  numpy/typing/tests/data/reveal/scalars.py
Labels: 01 - Enhancement, static typing

#17430 BUG: Fix memoryleaks related to NEP 37 function overrides
  numpy/core/src/multiarray/arrayfunction_override.c
  numpy/core/src/multiarray/multiarraymodule.c
Labels: 00 - Bug

#17431 DOC: Fix the links for ``Ellipsis``
  doc/source/reference/arrays.indexing.rst
Labels: 04 - Documentation

#17427 NEP: nep-0029 typo correction
  doc/neps/nep-0029-deprecation_policy.rst
Labels: 03 - Maintenance, component: NEP

#17421 BUG: Fix memory leak in array-coercion error paths
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/tests/test_array_coercion.py
Labels: 00 - Bug, component: numpy.core

#17433 MAINT : Disable 32 bit PyPy CI testing on Windows.
  azure-pipelines.yml
Labels: 03 - Maintenance, 24 - PyPy, component: CI

#17435 DOC: Security warning for issues template
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: 04 - Documentation

#17436 DOC: Fix "Feature request" spelling in issue templates
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: 04 - Documentation

#17443 ENH: Warn on unsupported Python 3.10+
  setup.py
Labels: 01 - Enhancement, 09 - Backport-Candidate

#17444 ENH: Add `Typing :: Typed` to the PyPi classifier
  setup.py
Labels: 01 - Enhancement, static typing

#17446 ENH: Warn on unsupported Python 3.10+
  setup.py
Labels: 03 - Maintenance, 08 - Backport, component: build

#17440 DOC: Cleaner template for PRs
  .github/PULL_REQUEST_TEMPLATE.md
  doc/source/dev/development_workflow.rst
Labels: 03 - Maintenance, 04 - Documentation

#17432 DOC: add references to einops and opt_einsum
  numpy/core/einsumfunc.py
Labels: 04 - Documentation

#17448 DOC: Remove CoC pages from Sphinx
  doc/source/dev/conduct/code_of_conduct.rst
  doc/source/dev/conduct/report_handling_manual.rst
  doc/source/dev/index.rst
Labels: 04 - Documentation

#17450 MAINT: Update test_requirements.txt.
  test_requirements.txt
Labels: 05 - Testing, 25 - WIP

#17445 DOC: Fix the references for macros
  doc/source/reference/arrays.interface.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/config.rst
  doc/source/reference/c-api/dtype.rst
  doc/source/reference/c-api/iterator.rst
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#17372 ENH: Add annotations for remaining `ndarray` / `generic` non-magic methods
  numpy/__init__.pyi
  numpy/core/fromnumeric.pyi
  numpy/typing/tests/data/fail/ndarray_misc.py
  numpy/typing/tests/data/pass/ndarray_misc.py
  numpy/typing/tests/data/reveal/ndarray_misc.py
Labels: 01 - Enhancement, static typing

#17459 DOC: update code of conduct URL
  .github/CODE_OF_CONDUCT.md
Labels: 04 - Documentation

#17457 BUG: Fixes incorrect error message in numpy.ediff1d
  numpy/lib/arraysetops.py
  numpy/lib/tests/test_arraysetops.py
Labels: 00 - Bug

#17391 DOC: Replace "About NumPy" with "Document conventions"
  doc/source/_templates/indexcontent.html
  doc/source/about.rst
  doc/source/doc_conventions.rst
  doc/source/docs/howto_document.rst
  doc/source/user/index.rst
Labels: 04 - Documentation

#17353 DOC: How-to guide for I/O
  doc/source/conf.py
  doc/source/user/how-to-io.rst
  doc/source/user/howtos_index.rst
  doc/source/user/ionumpy.rst
Labels: 04 - Documentation, component: Documentation

#17331 DOC: Remove the tables of scalar types, and use `..autoclass` to create link targets instead
  doc/source/conf.py
  doc/source/reference/arrays.scalars.rst
  numpy/core/__init__.py
  numpy/core/_add_newdocs.py
  numpy/core/_add_newdocs_scalars.py
Labels: 04 - Documentation, component: numpy.dtype

#17464 DOC: Add some entries for C types and macros
  doc/source/reference/c-api/types-and-structures.rst
  doc/source/reference/c-api/ufunc.rst
Labels: 04 - Documentation

#17447 NEP: update NEP 42 with discussion of type hinting applications
  doc/neps/nep-0042-new-dtypes.rst
Labels: component: NEP, static typing

#17472 TST: Fix doctest for full_like
  numpy/core/numeric.py
Labels: 05 - Testing

#17453 MAINT: Chain exceptions in "_polybase.py"
  numpy/polynomial/_polybase.py
Labels: 03 - Maintenance

#17474 MAINT: Move the `np.core.numeric` annotations to their own stub file
  numpy/__init__.pyi
  numpy/core/__init__.pyi
  numpy/core/numeric.pyi
Labels: 03 - Maintenance, static typing

#17468 DOC: add some missing scalar aliases
  doc/source/reference/arrays.scalars.rst
  doc/source/user/basics.types.rst
Labels: 04 - Documentation

#17442 MAINT: fix exception chaining in format.py
  numpy/lib/format.py
Labels: 03 - Maintenance

#17438 MAINT: Chaining exception in numpy\numpy\ma\mrecords.py
  numpy/ma/mrecords.py
Labels: 03 - Maintenance

#17481 DOC: Fix the entries for members of structures
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#17429 MAINT: Move aliases for common scalar unions to `numpy.typing`
  numpy/__init__.pyi
  numpy/core/fromnumeric.pyi
  numpy/core/function_base.pyi
  numpy/typing/__init__.py
  numpy/typing/_array_like.py
  numpy/typing/_callable.py
  numpy/typing/_scalars.py
Labels: 03 - Maintenance, static typing

#16300 DOC: Fix bad reference in ``numpy.ma``
  doc/source/reference/routines.ma.rst
  numpy/ma/core.py
  numpy/ma/extras.py
Labels: 03 - Maintenance, 04 - Documentation, component: numpy.ma

#17320 BUG: allow registration of hard-coded structured dtypes
  numpy/core/src/multiarray/_multiarray_tests.c.src
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/src/multiarray/usertypes.c
  numpy/core/tests/test_dtype.py
Labels: 00 - Bug, 06 - Regression, component: numpy.core

#17410 API: Special case how numpy scalars are coerced to signed integer
  doc/release/upcoming_changes/16200.compatibility.rst
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/tests/test_array_coercion.py
Labels: 06 - Regression, 30 - API, 62 - Python API, component: numpy.core

#17419 DEP: Deprecate coercion to subarray dtypes
  doc/release/upcoming_changes/17419.deprecation.rst
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/methods.c
  numpy/core/tests/test_deprecations.py
Labels: 07 - Deprecation, 62 - Python API, component: numpy.dtype

#17493 DOC: New round of NEP 42 edits
  doc/neps/nep-0042-new-dtypes.rst
Labels: 04 - Documentation

#17501 BUG: Fix failures in master related to userdtype registeration
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/src/multiarray/usertypes.c
  numpy/core/tests/test_dtype.py
Labels: 00 - Bug

#17497 DOC: Use consistent lowercase on docs landing page
  doc/source/_templates/indexcontent.html
Labels: 04 - Documentation

#17502 BUG: remove `sys` from the type stubs
  numpy/__init__.pyi
Labels: 00 - Bug, static typing

#17510 DOC: Fewer blank lines in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 04 - Documentation

#17483 DOC: Fix the references for `random.*`
  doc/source/release/1.17.0-notes.rst
Labels: 04 - Documentation

#17487 MAINT: Remove duplicate placeholder annotations
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/modules.py
  tools/functions_missing_types.py
Labels: 03 - Maintenance, static typing

#17485 BLD: circleCI- merge before build, add -n to sphinx
  .circleci/config.yml
Labels: component: build

#17465 ENH: Add annotations for bitwise operations
  numpy/__init__.pyi
  numpy/typing/_callable.py
  numpy/typing/tests/data/fail/bitwise_ops.py
  numpy/typing/tests/data/pass/bitwise_ops.py
  numpy/typing/tests/data/reveal/bitwise_ops.py
Labels: 01 - Enhancement, static typing

#17479 ENH: type np.unicode_ as np.str_
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/scalars.py
Labels: 01 - Enhancement, static typing

#17508 ENH: Added the Final feature for all constants
  numpy/__init__.pyi
Labels: 01 - Enhancement, static typing

#17344 ENH: Support for the NVIDIA HPC SDK nvfortran compiler
  numpy/distutils/fcompiler/__init__.py
  numpy/distutils/fcompiler/nv.py
  numpy/tests/test_public_api.py
Labels: 01 - Enhancement, 09 - Backport-Candidate, component: numpy.distutils

#17503 DOC: Fix empty 'C style guide' page
  doc/source/dev/index.rst
  doc/source/dev/style_guide.rst
Labels: 04 - Documentation

#17456 ENH: add dtype option to numpy.lib.function_base.cov and corrcoef
  doc/release/upcoming_changes/17456.new_feature.rst
  numpy/lib/function_base.py
  numpy/lib/tests/test_function_base.py
Labels: 01 - Enhancement

#17525 CI: Make merge ref grabbing conditional on the PR being active
  .circleci/config.yml
Labels: 00 - Bug, component: CI

#17520 DOC: Display real license on license page
  doc/source/license.rst
Labels: 04 - Documentation

#17522 ENH: Support for the NVIDIA HPC SDK nvfortran compiler
  numpy/distutils/fcompiler/__init__.py
  numpy/distutils/fcompiler/nv.py
  numpy/tests/test_public_api.py
Labels: 01 - Enhancement, 08 - Backport, component: numpy.distutils

#17498 MAINT: fix incompatible type comparison in numpy.lib.utils.info
  numpy/lib/tests/test_utils.py
  numpy/lib/utils.py
Labels: 03 - Maintenance

#17473 MAINT: py3k: remove os.fspath and os.PathLike backports
  numpy/compat/py3k.py
Labels: 03 - Maintenance

#17529 MAINT: Cleanup compatibility code for pathlib
  numpy/compat/py3k.py
Labels: 03 - Maintenance, 27 - Py3K

#17527 DOC: Fix Boolean types in C functions
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#17186 MAINT: Use utf8 strings in more of datetime
  numpy/core/src/multiarray/datetime_busday.c
  numpy/core/src/multiarray/datetime_busdaycal.c
  numpy/core/src/multiarray/datetime_strings.c
  numpy/core/tests/test_datetime.py
Labels: 03 - Maintenance, 27 - Py3K, component: numpy.datetime64

#17284 ENH: Pass optimizations arguments to asv build
  .gitignore
  benchmarks/asv_compare.conf.json.tpl
  runtests.py
Labels: 01 - Enhancement, component: benchmarks

#17534 DOC: Fix a typo
  doc/source/user/numpy-for-matlab-users.rst
Labels: 04 - Documentation

#17521 DOC: Add docstrings for some scalar types
  numpy/core/_add_newdocs_scalars.py
Labels: 04 - Documentation, component: Documentation

#17549 DOC: Fix the entries of C functions
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/config.rst
  doc/source/reference/c-api/types-and-structures.rst
  doc/source/reference/c-api/ufunc.rst
Labels: 04 - Documentation

#17523 DOC: Update top links in landing page
  doc/source/_templates/indexcontent.html
  doc/source/user/index.rst
  doc/source/user/install.rst
  doc/source/user/setting-up.rst
  doc/source/user/troubleshooting-importerror.rst
Labels: 04 - Documentation, component: Documentation

#16723 NEP: Initial draft for NEP 43 for extensible ufuncs
  doc/neps/_static/nep43-sketch-with-text.svg
  doc/neps/_static/nep43-sketch.svg
  doc/neps/nep-0043-extensible-ufuncs.rst
Labels: 04 - Documentation, component: NEP

#17541 CI: fix conditional for PR merge command
  .circleci/config.yml
Labels: 00 - Bug, component: CI

#17548 BUG: Workaround for #14787 on affected platforms
  numpy/core/setup.py
  numpy/distutils/command/autodist.py
  numpy/distutils/command/config.py
Labels: 00 - Bug

#17555 DOC: Fix wrong blockquotes
  doc/source/reference/arrays.interface.rst
  doc/source/user/c-info.how-to-extend.rst
Labels: 04 - Documentation

#17559 DOC: Remove directives for some constants
  doc/source/reference/c-api/dtype.rst
  doc/source/reference/c-api/ufunc.rst
Labels: 04 - Documentation

#17558 DOC: MAINT: Add NEP 43 links to NEP 42
  doc/neps/nep-0042-new-dtypes.rst
Labels: 04 - Documentation

#17568 BUG: Cygwin Workaround for #14787 on affected platforms
  numpy/core/setup.py
  numpy/distutils/command/autodist.py
  numpy/distutils/command/config.py
Labels: 00 - Bug, 08 - Backport, component: build, component: numpy.distutils

#17546 MAINT: explicit disabling `CCompilerOpt` in F2PY
  numpy/distutils/command/build_clib.py
  numpy/distutils/command/build_ext.py
  numpy/f2py/f2py2e.py
Labels: 03 - Maintenance

#17571 DOC: Fix typos
  doc/source/reference/c-api/array.rst
  doc/source/reference/routines.io.rst
  doc/source/user/c-info.beyond-basics.rst
Labels: 04 - Documentation

#17576 DOC: Fix Boolean array indexing typo
  doc/source/reference/arrays.indexing.rst
Labels: 04 - Documentation

#16759 ENH: make dtype generic over scalar type
  numpy/__init__.pyi
  numpy/typing/__init__.py
  numpy/typing/_dtype_like.py
  numpy/typing/tests/data/fail/dtype.py
  numpy/typing/tests/data/reveal/dtype.py
Labels: 01 - Enhancement, static typing

#17572 ENH: Add annotations for three new constants
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/constants.py
  numpy/typing/tests/data/reveal/constants.py
Labels: 01 - Enhancement, static typing

#14779 NEP 36 (fair play)
  doc/neps/nep-0036-fair-play.rst
Labels: 25 - WIP, component: NEP

#17535 ENH: add function to get broadcast shape from a given set of shapes.
  doc/release/upcoming_changes/17535.new_function.rst
  doc/source/reference/routines.other.rst
  numpy/__init__.pyi
  numpy/core/_add_newdocs.py
  numpy/lib/stride_tricks.py
  numpy/lib/tests/test_stride_tricks.py
Labels: 01 - Enhancement, 56 - Needs Release Note., 62 - Python API, component: numpy.lib

#17536 BUG: Fixed crash on self-referential dtypes
  numpy/core/src/multiarray/descriptor.c
  numpy/core/tests/test_dtype.py
Labels: 00 - Bug

#17581 MAINT: Move the `np.core.numerictypes` annotations to their own stub file
  numpy/__init__.pyi
  numpy/core/numerictypes.pyi
Labels: 03 - Maintenance, static typing

#17584 ENH: Add annotations for `np.core._type_aliases`
  numpy/__init__.pyi
  numpy/core/_type_aliases.pyi
  numpy/typing/tests/data/reveal/constants.py
Labels: 01 - Enhancement, static typing

#17252 DOC: Added a PR "Reviewer guidelines" document.
  doc/source/dev/development_environment.rst
  doc/source/dev/index.rst
  doc/source/dev/reviewer_guidelines.rst
Labels: 04 - Documentation

#17418 DOC: adding operational form documentation for array ops
  numpy/core/code_generators/ufunc_docstrings.py
Labels: 04 - Documentation

#17594 DOC: Typo in lexsort docstring
  numpy/core/multiarray.py
Labels: 04 - Documentation

#17540 ENH: Make `np.number` generic with respect to its precision
  numpy/__init__.pyi
  numpy/typing/__init__.py
  numpy/typing/_callable.py
  numpy/typing/tests/data/fail/bitwise_ops.py
  numpy/typing/tests/data/fail/numerictypes.py
  numpy/typing/tests/data/fail/scalars.py
  numpy/typing/tests/data/reveal/arithmetic.py
  numpy/typing/tests/data/reveal/array_constructors.py
  numpy/typing/tests/data/reveal/bitwise_ops.py
  numpy/typing/tests/data/reveal/dtype.py
  numpy/typing/tests/data/reveal/fromnumeric.py
  numpy/typing/tests/data/reveal/nbit_base_example.py
  numpy/typing/tests/data/reveal/ndarray_misc.py
  numpy/typing/tests/data/reveal/scalars.py
  numpy/typing/tests/test_typing.py
Labels: 01 - Enhancement, 30 - API, component: numpy.typing, static typing

#17564 MAINT: Update the annotations in `np.core.numeric`
  numpy/core/numeric.pyi
  numpy/typing/tests/data/pass/array_constructors.py
  numpy/typing/tests/data/pass/numeric.py
  numpy/typing/tests/data/pass/simple.py
  numpy/typing/tests/data/reveal/array_constructors.py
  numpy/typing/tests/data/reveal/numeric.py
Labels: 03 - Maintenance, static typing

#17597 TST: Clean up the errors of the typing tests
  numpy/typing/tests/test_typing.py
Labels: 05 - Testing, static typing

#17601 TST: Fix a broken `np.core.numeric` test
  numpy/core/numeric.pyi
  numpy/typing/tests/data/reveal/numeric.py
Labels: 00 - Bug, 05 - Testing, static typing

#17603 MAINT: Mark dead code as intentional for clang.
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/src/npysort/selection.c.src
  numpy/core/src/umath/loops.c.src
Labels: 03 - Maintenance, component: numpy.core

#17608 DOC: Fix typos (general documentation)
  doc/source/dev/development_workflow.rst
  doc/source/user/basics.subclassing.rst
Labels: 04 - Documentation

#16936 BUG: Fix memory leak of buffer-info cache due to relaxed strides
  numpy/core/src/multiarray/buffer.c
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug, 09 - Backport-Candidate, 58 - Ready for review, component: numpy.core

#17570 DOC: Add the entry for ``NPY_FEATURE_VERSION``
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#17607 DOC: removed old references to submodule licenses (closes #17606)
  LICENSES_bundled.txt
Labels: 04 - Documentation

#17614 DOC: Fix the document for arrays interface
  doc/source/reference/arrays.interface.rst
Labels: 04 - Documentation

#17619 DOC: Fix some references
  doc/source/f2py/distutils.rst
  doc/source/reference/arrays.interface.rst
  doc/source/reference/arrays.ndarray.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/types-and-structures.rst
  doc/source/reference/internals.code-explanations.rst
  doc/source/reference/maskedarray.generic.rst
  doc/source/reference/random/c-api.rst
  doc/source/reference/routines.array-manipulation.rst
  doc/source/reference/ufuncs.rst
  doc/source/release/1.16.0-notes.rst
  doc/source/user/basics.rec.rst
  doc/source/user/quickstart.rst
Labels: 04 - Documentation

#17624 DOC: Tidy up references to str_ / bytes_
  doc/source/reference/arrays.classes.rst
  doc/source/reference/arrays.dtypes.rst
  doc/source/reference/arrays.scalars.rst
  doc/source/reference/routines.char.rst
Labels: 04 - Documentation

#17580 MAINT: Cleanup swig for Python 3.
  doc/release/upcoming_changes/17580.compatibility.rst
  tools/swig/numpy.i
  tools/swig/pyfragments.swg
Labels: 03 - Maintenance, component: swig

#17628 DOC: Add entries for macros
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#17629 DOC: Add ``identity_value`` to ``PyUFuncObject``
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#17630 DOC: Replace ``PyCObject`` with ``PyCapsule``
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#17627 DOC: Fix the references for ``__array_*__``
  doc/source/reference/arrays.dtypes.rst
  doc/source/reference/arrays.interface.rst
  doc/source/reference/arrays.ndarray.rst
  doc/source/reference/arrays.scalars.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#17633 DOC: Don't use Python highlighting for non-python code
  doc/neps/nep-0000.rst
  doc/neps/nep-0002-warnfix.rst
  doc/neps/nep-0010-new-iterator-ufunc.rst
  doc/neps/nep-0011-deferred-ufunc-evaluation.rst
  doc/neps/nep-0012-missing-data.rst
  doc/neps/nep-0013-ufunc-overrides.rst
  doc/neps/nep-0025-missing-data-3.rst
  doc/neps/nep-0043-extensible-ufuncs.rst
  doc/neps/nep-0045-c_style_guide.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/deprecations.rst
Labels: 04 - Documentation, component: NEP

#17625 MAINT: Conversion of some strings to fstrings, part iv
  numpy/linalg/lapack_lite/make_lite.py
  numpy/linalg/linalg.py
  numpy/linalg/tests/test_build.py
  numpy/linalg/tests/test_linalg.py
Labels: 03 - Maintenance

#17623 MAINT: Conversion of some strings to fstrings, part III
  numpy/ma/bench.py
  numpy/ma/mrecords.py
  numpy/ma/tests/test_core.py
  numpy/ma/tests/test_old_ma.py
  numpy/ma/tests/test_subclassing.py
  numpy/ma/testutils.py
  numpy/ma/timer_comparison.py
Labels: 03 - Maintenance

#17622 MAINT: Conversion of some strings to fstrings, part II
  numpy/random/_examples/numba/extending.py
  numpy/random/tests/test_direct.py
  numpy/random/tests/test_generator_mt19937_regressions.py
  numpy/random/tests/test_randomstate_regression.py
  numpy/random/tests/test_regression.py
  numpy/random/tests/test_smoke.py
Labels: 03 - Maintenance

#17618 MAINT: Conversion of some strings to f-strings
  numpy/testing/_private/decorators.py
  numpy/testing/_private/noseclasses.py
  numpy/testing/_private/nosetester.py
  numpy/testing/_private/parameterized.py
  numpy/testing/_private/utils.py
  numpy/tests/test_public_api.py
Labels: 03 - Maintenance

#17340 SIMD: Add partial/non-contig load and store intrinsics for 32/64-bit
  numpy/core/src/common/simd/avx2/avx2.h
  numpy/core/src/common/simd/avx2/memory.h
  numpy/core/src/common/simd/avx512/avx512.h
  numpy/core/src/common/simd/avx512/memory.h
  numpy/core/src/common/simd/neon/memory.h
  numpy/core/src/common/simd/simd.h
  numpy/core/src/common/simd/sse/memory.h
  numpy/core/src/common/simd/vsx/memory.h
Labels: 01 - Enhancement, component: SIMD

#17642 DOC: Fix reference to atleast_1d
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#17621 TST: Valid docstring for config_py function show()
  numpy/distutils/misc_util.py
Labels: 05 - Testing

#17641 MAINT, BLD: update to OpenBLAS v0.3.12
  tools/openblas_support.py
Labels: 03 - Maintenance

#17638 DOC: Fix some references
  doc/source/reference/arrays.ndarray.rst
  doc/source/reference/arrays.nditer.cython.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/types-and-structures.rst
  doc/source/reference/maskedarray.baseclass.rst
  doc/source/user/basics.rec.rst
Labels: 04 - Documentation

#17647 BUG: Fix memory leak of buffer-info cache due to relaxed strides
  numpy/core/src/multiarray/buffer.c
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug, 08 - Backport, component: numpy.core

#17652 MAINT: Backport openblas_support from master.
  azure-steps-windows.yml
  tools/openblas_support.py
Labels: 03 - Maintenance, 08 - Backport, component: build

#17653 TST: Add Python 3.9 to the CI testing on Windows, Mac.
  .travis.yml
  azure-pipelines.yml
  numpy/random/tests/test_extending.py
Labels: 03 - Maintenance, 05 - Testing, component: CI

#17658 TST: simplify source path names in compilation test
  azure-pipelines.yml
  numpy/core/tests/examples/setup.py
  numpy/core/tests/test_cython.py
  numpy/random/_examples/cython/setup.py
Labels: 03 - Maintenance, 05 - Testing, 09 - Backport-Candidate

#17660 TST: Simplify source path names in test_extending.
  numpy/random/_examples/cython/setup.py
  numpy/random/tests/test_extending.py
Labels: 03 - Maintenance, 05 - Testing, 08 - Backport, component: numpy.random

#17654 BUG: f2py incorrectly translates dimension declarations.
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/test_crackfortran.py
Labels: 00 - Bug

#17577 BUG: Respect dtype of all-zero argument to poly1d
  doc/release/upcoming_changes/17577.compatibility.rst
  numpy/lib/polynomial.py
  numpy/lib/tests/test_polynomial.py
Labels: 00 - Bug, 01 - Enhancement, component: numpy.lib

#17666 REL: Update master after 1.19.3 release.
  doc/changelog/1.19.3-changelog.rst
  doc/source/release.rst
  doc/source/release/1.19.3-notes.rst
Labels: 04 - Documentation, 14 - Release, component: Documentation

#17662 TST: f2py: Add a doctest for `getlincoef`
  numpy/f2py/crackfortran.py
Labels: 05 - Testing, component: numpy.f2py

#17613 ENH: Add annotations for 9 `ndarray`/`generic` magic methods
  numpy/__init__.pyi
  numpy/typing/_callable.py
  numpy/typing/tests/data/fail/arithmetic.py
  numpy/typing/tests/data/fail/scalars.py
  numpy/typing/tests/data/pass/arithmetic.py
  numpy/typing/tests/data/pass/mod.py
  numpy/typing/tests/data/pass/scalars.py
  numpy/typing/tests/data/reveal/arithmetic.py
  numpy/typing/tests/data/reveal/mod.py
  numpy/typing/tests/test_typing.py
Labels: 01 - Enhancement, static typing

#17596 DEP,BUG: Coercion/cast of array to a subarray dtype will be fixed
  doc/release/upcoming_changes/17419.deprecation.rst
  doc/release/upcoming_changes/17596.future.rst
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/methods.c
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_dtype.py
Labels: 07 - Deprecation

#17668 TST: Make test suite work in FIPS (140-2) Mode
  numpy/core/tests/test_regression.py
  numpy/f2py/tests/util.py
  numpy/random/tests/test_generator_mt19937.py
  numpy/random/tests/test_random.py
  numpy/random/tests/test_randomstate.py
Labels: 05 - Testing

#17672 DOC: Update README badge for travis-ci.com
  README.md
Labels: 04 - Documentation

#16782 ENH, TST: Bring the NumPy C SIMD vectorization interface "NPYV" to Python
  .gitattributes
  numpy/core/setup.py
  numpy/core/src/_simd/_simd.c
  numpy/core/src/_simd/_simd.dispatch.c.src
  numpy/core/src/_simd/_simd.h
  numpy/core/src/_simd/_simd_arg.inc
  numpy/core/src/_simd/_simd_convert.inc
  numpy/core/src/_simd/_simd_data.inc.src
  numpy/core/src/_simd/_simd_easyintrin.inc
  numpy/core/src/_simd/_simd_inc.h.src
  numpy/core/src/_simd/_simd_vector.inc
  numpy/core/tests/test_simd.py
  numpy/core/tests/test_simd_module.py
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/command/build.py
  numpy/distutils/command/build_ext.py
  runtests.py
Labels: 01 - Enhancement, component: SIMD, component: numpy.core

#17680 REV: Revert OpenBLAS to 1.19.2 version for 1.19.4
  tools/openblas_support.py
Labels: 34 - Reversion, component: build

#17679 MAINT: Add check for Windows 10 version 2004 bug.
  numpy/__init__.py
Labels: 03 - Maintenance

#17683 REL: Prepare for the NumPy 1.19.4 release.
  doc/changelog/1.19.4-changelog.rst
  doc/source/release/1.19.3-notes.rst
  doc/source/release/1.19.4-notes.rst
Labels: 04 - Documentation, 14 - Release, component: Documentation

#17682 BUG: (nditer_impl.h) Use `intp` instead of `char *` for offset calculation
  numpy/core/src/multiarray/nditer_impl.h
Labels: 00 - Bug
