Repository numpy/numpy, pull requests merged in 2021-02, with the labels that each got.

#18272 DOC: Numpydoc warning incorrect underline length.
  numpy/ctypeslib.py
Labels: 04 - Documentation

#18278 ENH: defer the import of shutil
  numpy/lib/_datasource.py
Labels: 01 - Enhancement

#18263 ENH: Added sanity check to printoptions
  numpy/core/arrayprint.py
  numpy/core/arrayprint.pyi
  numpy/core/tests/test_arrayprint.py
Labels: 01 - Enhancement

#18228 ENH: Add dtype-support to the ufunc-based `ndarray` magic methods 2/4
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/arithmetic.py
  numpy/typing/tests/data/pass/arithmetic.py
  numpy/typing/tests/data/reveal/arithmetic.py
  numpy/typing/tests/data/reveal/mod.py
Labels: 01 - Enhancement, static typing

#18285 TST: Pin `typing_extensions` to the latest version
  numpy/__init__.pyi
  numpy/core/function_base.pyi
  numpy/core/shape_base.pyi
  test_requirements.txt
Labels: 05 - Testing, static typing

#18284 ENH: Add annotations for the remaining `np.generic` aliases
  numpy/__init__.pyi
  numpy/typing/tests/data/pass/scalars.py
  numpy/typing/tests/data/reveal/scalars.py
Labels: 01 - Enhancement, static typing

#18293 BUG: Fix typo in ``numpy.__init__.py``
  numpy/__init__.py
  numpy/core/tests/test_deprecations.py
Labels: 00 - Bug, 09 - Backport-Candidate

#18301 MAINT: avoid chaining exceptions in conv_template.py
  numpy/distutils/conv_template.py
Labels: 03 - Maintenance

#18303 MAINT: Fix typo in PyArray_RegisterDataType error
  numpy/core/src/multiarray/usertypes.c
Labels: 03 - Maintenance

#18161 MAINT: Make keyword arrays static
  numpy/core/src/multiarray/compiled_base.c
  numpy/core/src/multiarray/datetime_busday.c
  numpy/core/src/multiarray/methods.c
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/multiarray/scalartypes.c.src
Labels: 03 - Maintenance

#18264 BUG: Use C linkage for random distributions
  numpy/core/include/numpy/random/distributions.h
  numpy/random/_examples/cffi/parse.py
Labels: 00 - Bug, 09 - Backport-Candidate, component: numpy.random

#18302 MAINT: Add missing placeholder annotations
  numpy/char.pyi
  numpy/core/__init__.py
  numpy/core/records.py
  numpy/ctypeslib.py
  numpy/ctypeslib.pyi
  numpy/emath.pyi
  numpy/f2py/__init__.pyi
  numpy/lib/__init__.pyi
  numpy/ma/__init__.pyi
  numpy/matrixlib/__init__.pyi
  numpy/random/__init__.pyi
  numpy/rec.pyi
  numpy/testing/__init__.pyi
  numpy/typing/tests/data/pass/modules.py
  numpy/typing/tests/data/reveal/modules.py
Labels: 03 - Maintenance, static typing

#18200 ENH: Add new intrinsics sum_u8/u16/u64.
  numpy/core/src/_simd/_simd.dispatch.c.src
  numpy/core/src/common/simd/avx2/arithmetic.h
  numpy/core/src/common/simd/avx512/arithmetic.h
  numpy/core/src/common/simd/neon/arithmetic.h
  numpy/core/src/common/simd/sse/arithmetic.h
  numpy/core/src/common/simd/sse/sse.h
  numpy/core/src/common/simd/sse/utils.h
  numpy/core/src/common/simd/vsx/arithmetic.h
  numpy/core/tests/test_simd.py
Labels: 01 - Enhancement, component: SIMD

#18307 DOC: Corrected numpy.power example.
  doc/source/user/basics.types.rst
Labels: 04 - Documentation

#18313 Numpy logo fix on README
  README.md
Labels: 04 - Documentation

#18315 BLD: rearrange Azure build jobs
  azure-pipelines.yml
Labels: 36 - Build

#18310 BUG: Fix typo in ``numpy.__init__.py``
  numpy/__init__.py
  numpy/core/tests/test_deprecations.py
Labels: 00 - Bug, 08 - Backport

#18282 MAINT: gracefully shuffle memoryviews
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
  numpy/random/tests/test_random.py
Labels: 03 - Maintenance, 09 - Backport-Candidate, component: numpy.random

#18295 BUG: don't mutate list of fake libraries while iterating over it
  numpy/distutils/command/build_ext.py
  numpy/distutils/tests/test_build_ext.py
Labels: 00 - Bug, 06 - Regression, 09 - Backport-Candidate

#18326 BUG: don't mutate list of fake libraries while iterating over it.
  numpy/distutils/command/build_ext.py
  numpy/distutils/tests/test_build_ext.py
Labels: 00 - Bug, 06 - Regression, 08 - Backport, component: numpy.distutils

#18327 MAINT: gracefully shuffle memoryviews
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
  numpy/random/tests/test_random.py
Labels: 03 - Maintenance, 08 - Backport, component: numpy.random

#18328 BUG: Use C linkage for random distributions
  numpy/core/include/numpy/random/distributions.h
  numpy/random/_examples/cffi/parse.py
Labels: 00 - Bug, 08 - Backport, component: numpy.random

#18331 MAINT: Update openblas_support for macosx-arm64
  tools/openblas_support.py
Labels: 03 - Maintenance, component: build

#18333 CI: fix when GitHub Actions builds trigger, and allow ci skips
  .github/workflows/build_test.yml
Labels: 03 - Maintenance, component: CI

#18334 TST: use setup-python action for pypy, disable win64 pypy
  .github/workflows/build_test.yml
  azure-pipelines.yml
Labels: 05 - Testing

#18329 BUG: Allow unmodified use of isclose, allclose, etc. with timedelta
  numpy/core/numeric.py
  numpy/core/tests/test_numeric.py
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
  numpy/testing/tests/test_utils.py
Labels: 00 - Bug, 06 - Regression, 09 - Backport-Candidate

#18336 CI: fix when GitHub Actions builds trigger, and allow ci skips
  .github/workflows/build_test.yml
Labels: 03 - Maintenance, 08 - Backport, component: CI

#18337 BUG: Allow unmodified use of isclose, allclose, etc. with timedelta
  numpy/core/numeric.py
  numpy/core/tests/test_numeric.py
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
  numpy/testing/tests/test_utils.py
Labels: 00 - Bug, 06 - Regression, 08 - Backport

#18323 ENH: Add dtype-support to the ufunc-based `ndarray` magic methods 3/4
  numpy/__init__.pyi
  numpy/typing/_callable.py
  numpy/typing/tests/data/fail/arithmetic.py
  numpy/typing/tests/data/pass/arithmetic.py
  numpy/typing/tests/data/reveal/arithmetic.py
  numpy/typing/tests/test_typing.py
Labels: 01 - Enhancement, static typing

#18338 DOC: Fix whitespace before "last updated" on overview page
  doc/source/_templates/indexcontent.html
Labels: 04 - Documentation

#18340 DOC: remove pygments_style from conf.py
  doc/source/conf.py
Labels: 04 - Documentation

#18342 DOC: Specified all possible return types for trapz function #18140
  numpy/lib/function_base.py
Labels: 04 - Documentation

#18332 BUG: Allow pickling all relevant DType types/classes
  numpy/core/__init__.py
  numpy/core/tests/test_dtype.py
Labels: 00 - Bug, 06 - Regression, 09 - Backport-Candidate, component: numpy.core

#18289 MAINT: Move transferdata into buffer-wise struct
  numpy/core/src/multiarray/nditer_api.c
  numpy/core/src/multiarray/nditer_constr.c
  numpy/core/src/multiarray/nditer_impl.h
  numpy/core/src/multiarray/nditer_pywrap.c
  numpy/core/tests/test_nditer.py
Labels: 03 - Maintenance

#18345 BUG: Allow pickling all relevant DType types/classes
  numpy/core/__init__.py
  numpy/core/tests/test_dtype.py
Labels: 00 - Bug, 06 - Regression, 08 - Backport, component: numpy.core

#18346 DOC: Change license date 2020 -> 2021
  LICENSE.txt
  doc/source/conf.py
Labels: 03 - Maintenance, 04 - Documentation, 09 - Backport-Candidate

#18348 DEP: doc-deprecate BLAS_SRC/LAPACK_SRC
  numpy/distutils/system_info.py
  site.cfg.example
Labels: 07 - Deprecation, component: numpy.distutils

#18350 BUG: Fix missing signed_char dependency.
  numpy/f2py/cb_rules.py
  numpy/f2py/tests/test_callback.py
Labels: 00 - Bug, 09 - Backport-Candidate, component: numpy.f2py

#18349 CI: CircleCI seems to occasionally time out, increase the limit
  .circleci/config.yml
Labels: 03 - Maintenance, 09 - Backport-Candidate, component: CI

#18352 DOC: Change license date 2020 -> 2021
  LICENSE.txt
  doc/source/conf.py
Labels: 03 - Maintenance, 04 - Documentation, 08 - Backport

#18353 CI: CircleCI seems to occasionally time out, increase the limit
  .circleci/config.yml
Labels: 03 - Maintenance, 08 - Backport, component: CI

#18354 BUG: Fix f2py bugs when wrapping F90 subroutines.
  numpy/distutils/fcompiler/__init__.py
  numpy/f2py/auxfuncs.py
  numpy/f2py/crackfortran.py
  numpy/f2py/func2subr.py
  numpy/f2py/rules.py
  numpy/f2py/tests/test_callback.py
Labels: 00 - Bug, 08 - Backport, component: numpy.f2py

#18357 BUG: threads.h existence test requires GLIBC > 2.12.
  numpy/f2py/cfuncs.py
Labels: 00 - Bug, 08 - Backport, component: numpy.f2py

#18356 MAINT: crackfortran regex simplify
  numpy/f2py/crackfortran.py
Labels: 00 - Bug, 03 - Maintenance, 08 - Backport, component: numpy.f2py

#18351 BUG: Fix missing signed_char dependency. Closes #18335.
  numpy/f2py/cb_rules.py
  numpy/f2py/tests/test_callback.py
Labels: 00 - Bug, 08 - Backport, component: numpy.f2py

#18366 MAINT: Disable TravisCI git clone depth.
  .travis.yml
Labels: 03 - Maintenance, component: CI

#18362 REL: Update master after 1.20.1 release.
  .mailmap
  doc/changelog/1.20.1-changelog.rst
  doc/source/release.rst
  doc/source/release/1.20.1-notes.rst
Labels: 04 - Documentation, 14 - Release

#18361 ENH: Share memory of read-only intent(in) arrays.
  numpy/f2py/rules.py
  numpy/f2py/src/fortranobject.c
  numpy/f2py/tests/test_array_from_pyobj.py
Labels: 01 - Enhancement, component: numpy.f2py

#18322 ENH: Add a mypy plugin for exposing platform-specific extended-precision types
  doc/release/upcoming_changes/18322.new_feature.rst
  numpy/__init__.pyi
  numpy/typing/__init__.py
  numpy/typing/_callable.py
  numpy/typing/_extended_precision.py
  numpy/typing/mypy_plugin.py
  numpy/typing/tests/data/misc/extended_precision.py
  numpy/typing/tests/data/reveal/arithmetic.py
  numpy/typing/tests/test_typing.py
Labels: 01 - Enhancement, static typing

#18364 DOC: Update landing page to match table of contents
  doc/source/_templates/indexcontent.html
Labels: 04 - Documentation

#18374 TST: Add a test for nditer write masked with references
  numpy/core/src/multiarray/dtype_transfer.c
  numpy/core/tests/test_nditer.py
Labels: 05 - Testing

#18375 BUG: fix regression in a hidden callback use case
  numpy/distutils/command/config.py
  numpy/f2py/cb_rules.py
  numpy/f2py/tests/test_callback.py
Labels: 00 - Bug, 03 - Maintenance, 06 - Regression, 09 - Backport-Candidate, component: numpy.f2py

#18324 MAINT: Avoid moveaxis overhead in median.
  benchmarks/benchmarks/bench_function_base.py
  numpy/lib/utils.py
Labels: 03 - Maintenance

#18379 DOC: Fix docstring of _median_nancheck.
  numpy/lib/utils.py
Labels: 04 - Documentation

#18377 ENH: Add annotations for `np.lib.ufunclike`
  numpy/__init__.pyi
  numpy/lib/__init__.pyi
  numpy/lib/ufunclike.py
  numpy/lib/ufunclike.pyi
  numpy/typing/tests/data/fail/ufunclike.py
  numpy/typing/tests/data/pass/ufunclike.py
  numpy/typing/tests/data/reveal/ufunclike.py
Labels: 01 - Enhancement, static typing

#18382 MAINT: Update f2py from master.
  numpy/f2py/__version__.py
  numpy/f2py/capi_maps.py
  numpy/f2py/cb_rules.py
  numpy/f2py/common_rules.py
  numpy/f2py/crackfortran.py
  numpy/f2py/f2py2e.py
  numpy/f2py/rules.py
  numpy/f2py/src/fortranobject.c
  numpy/f2py/tests/test_array_from_pyobj.py
  numpy/f2py/tests/test_callback.py
  numpy/f2py/tests/test_crackfortran.py
  numpy/tests/test_scripts.py
Labels: 03 - Maintenance, component: numpy.f2py

#18384 BUG: improve the interface of `tofile` method
  numpy/__init__.pyi
Labels: 00 - Bug, static typing

#18389 MAINT: Fix version of wheel to support Python 3.10
  pyproject.toml
Labels: 03 - Maintenance, component: build

#18369 BUG: np.in1d bug on the object array (issue 17923)
  numpy/lib/arraysetops.py
  numpy/lib/tests/test_arraysetops.py
Labels: 00 - Bug

#18344 DOC: Added sentence to docstring of histogram_bin_edges to explain bin width
  numpy/lib/histograms.py
Labels: 04 - Documentation

#18274 MAINT: Chain exceptions in linalg
  numpy/linalg/lapack_lite/make_lite.py
  numpy/linalg/tests/test_build.py
  numpy/linalg/tests/test_linalg.py
Labels: 03 - Maintenance, component: numpy.linalg

#18317 MAINT: Fixed chain exception for array_split func
  numpy/lib/shape_base.py
Labels: 03 - Maintenance

#18392 BUG: Remove check in shuffle for non-ndarrays
  numpy/random/_generator.pyx
  numpy/random/tests/test_generator_mt19937.py
Labels: 00 - Bug

#18396 MAINT: Threading and Unicode strings
  numpy/distutils/ccompiler.py
  numpy/distutils/misc_util.py
  numpy/random/_common.pyx
  numpy/random/_generator.pyx
  numpy/random/_philox.pyx
  numpy/random/bit_generator.pyx
Labels: 03 - Maintenance

#18347 MAINT: Delete unused "dst" clearing functions
  numpy/core/src/common/lowlevel_strided_loops.h
  numpy/core/src/multiarray/dtype_transfer.c
Labels: 03 - Maintenance

#18402 BUG: Fix typo in char_codes
  numpy/typing/_char_codes.py
Labels: 00 - Bug, static typing

#18339 DOC: Discussion on the @ operator and the matrix class
  doc/source/reference/arrays.classes.rst
  doc/source/reference/arrays.ndarray.rst
  doc/source/reference/routines.linalg.rst
  numpy/core/code_generators/ufunc_docstrings.py
Labels: 04 - Documentation

#18390 ENH: Add annotations for `np.core.einsumfunc`
  numpy/__init__.pyi
  numpy/core/einsumfunc.pyi
  numpy/typing/__init__.py
  numpy/typing/_dtype_like.py
  numpy/typing/tests/data/fail/einsumfunc.py
  numpy/typing/tests/data/pass/einsumfunc.py
  numpy/typing/tests/data/reveal/einsumfunc.py
  numpy/typing/tests/test_typing.py
Labels: 01 - Enhancement, static typing

#18070 BUG: Fix unique handling of nan entries.
  benchmarks/benchmarks/bench_lib.py
  doc/release/upcoming_changes/18070.improvement.rst
  numpy/lib/arraysetops.py
  numpy/lib/tests/test_arraysetops.py
Labels: 00 - Bug, component: numpy.lib

#17887 DOC: Update arraycreation
  doc/source/user/basics.creation.rst
Labels: 04 - Documentation, component: Documentation

#18183 MAINT: Optimize numpy.count_nonzero for int types using SIMD operations
  benchmarks/benchmarks/bench_core.py
  numpy/core/src/multiarray/item_selection.c
  numpy/core/tests/test_numeric.py
Labels: 03 - Maintenance, component: benchmarks, component: numpy.core

#18416 BUG: Fix f2py parsing continued lines that follow comment lines.
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/test_crackfortran.py
Labels: 00 - Bug, component: numpy.f2py

#18405 DOC: Mention `scipy.signal.correlate` and FFT method in `np.correlate`closes gh-17721
  numpy/core/numeric.py
Labels: 04 - Documentation

#18415 MAINT: Update END statements parsing for recent Fortran standards.
  numpy/f2py/crackfortran.py
Labels: 03 - Maintenance, component: numpy.f2py

#18420 BUG: Fix tiny memory leaks when `like=` overrides are used
  numpy/core/src/multiarray/multiarraymodule.c
Labels: 00 - Bug, 09 - Backport-Candidate

#18429 DOC: point intersphinx to matplotlib/stable...
  doc/source/conf.py
Labels: 04 - Documentation

#18395 ENH: Initial typing of random
  numpy/random/__init__.pyi
  numpy/random/_generator.pyi
  numpy/random/_generator.pyx
  numpy/random/_mt19937.pyi
  numpy/random/_pcg64.pyi
  numpy/random/_philox.pyi
  numpy/random/_sfc64.pyi
  numpy/random/bit_generator.pyi
Labels: 01 - Enhancement, static typing

#16588 DOC: unify the docs for np.transpose and ndarray.transpose
  numpy/core/_add_newdocs.py
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#18436 BUG: Fix refcount leak in f2py `complex_double_from_pyobj`
  numpy/f2py/cfuncs.py
Labels: 00 - Bug, 09 - Backport-Candidate, component: numpy.f2py

#18432 MAINT: Correct code producing warnings
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/umath/fast_loop_macros.h
  numpy/random/src/distributions/distributions.c
Labels: 03 - Maintenance

#18428 DOC: remove explanations.rst
  doc/source/user/explanations_index.rst
  doc/source/user/index.rst
Labels: 04 - Documentation

#15392 BUG: Remove temporary change of descr/flags in VOID functions
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/tests/test_indexing.py
  numpy/core/tests/test_numeric.py
Labels: 00 - Bug, component: numpy.core

#18455 BUG: Fixed an issue where `diagflat` could overflow on windows or 32-bit platforms
  numpy/lib/twodim_base.py
Labels: 00 - Bug

#18448 DOC: Remove unfinished Linear Algebra section from Quickstart tutorial
  doc/source/user/quickstart.rst
Labels: 04 - Documentation

#18459 BUG: ``diagflat`` could overflow on windows or 32-bit platforms
  numpy/lib/twodim_base.py
Labels: 00 - Bug, 08 - Backport, component: numpy.lib

#18460 BUG: Fix refcount leak in f2py ``complex_double_from_pyobj``.
  numpy/f2py/cfuncs.py
Labels: 00 - Bug, 08 - Backport, component: numpy.f2py

#18461 BUG: Fix tiny memory leaks when ``like=`` overrides are used
  numpy/core/src/multiarray/multiarraymodule.c
Labels: 00 - Bug, 08 - Backport, component: numpy.core

#18462 BUG: Remove temporary change of descr/flags in VOID functions
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/tests/test_indexing.py
  numpy/core/tests/test_numeric.py
Labels: 00 - Bug, 08 - Backport, component: numpy.core

#18443 BUG: fix stacklevel in warning within random.shuffle
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
  numpy/random/tests/test_random.py
Labels: 00 - Bug, component: numpy.random

#18404 BUG: Fix iterator shape in advanced index assignment broadcast error
  numpy/core/src/multiarray/mapping.c
  numpy/core/tests/test_indexing.py
Labels: 00 - Bug

#18450 BUG: Segfault in nditer buffer dealloc for Object arrays
  numpy/core/src/multiarray/einsum.c.src
  numpy/core/src/multiarray/nditer_api.c
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_nditer.py
Labels: 00 - Bug, 06 - Regression, 09 - Backport-Candidate, component: numpy.core

#18110 API: make piecewise subclass safe using use zeros_like.
  doc/release/upcoming_changes/18110.change.rst
  numpy/lib/function_base.py
  numpy/lib/tests/test_function_base.py
Labels: 03 - Maintenance, 30 - API, 56 - Needs Release Note., 62 - Python API, component: numpy.lib

#18469 BUG: Segfault in nditer buffer dealloc for Object arrays
  numpy/core/src/multiarray/einsum.c.src
  numpy/core/src/multiarray/nditer_api.c
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_nditer.py
Labels: 00 - Bug, 06 - Regression, 08 - Backport, component: numpy.core

#18458 DOC: update NEP status for accepted/finished NEPs
  doc/neps/nep-0014-dropping-python2.7-proposal.rst
  doc/neps/nep-0023-backwards-compatibility.rst
  doc/neps/nep-0032-remove-financial-functions.rst
  doc/neps/nep-0035-array-creation-dispatch-with-array-function.rst
  doc/neps/nep-0040-legacy-datatype-impl.rst
Labels: component: NEP

#18372 DOC: improve standard_t example in numpy.random.
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
Labels: 04 - Documentation

#18477 BUG: remove nonsensical comparison of pointer < 0
  numpy/core/src/multiarray/ctors.c
Labels: 00 - Bug, 09 - Backport-Candidate, component: numpy.core

#18478 BUG: verify pointer against NULL before using it
  numpy/core/src/multiarray/dtype_transfer.c
Labels: 00 - Bug, 09 - Backport-Candidate, component: numpy.core

#18481 DOC: Generator and RandomState doc improvements
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
Labels: 04 - Documentation

#18476 BUG: Remove suspicious type casting
  numpy/core/src/multiarray/dtypemeta.c
Labels: 00 - Bug, 09 - Backport-Candidate, component: numpy.core

#18479 BUG: check if PyArray_malloc succeeded
  numpy/core/src/umath/ufunc_object.c
Labels: 00 - Bug, 09 - Backport-Candidate, component: numpy.core

#18485 BUG: Remove suspicious type casting
  numpy/core/src/multiarray/dtypemeta.c
Labels: 00 - Bug, 08 - Backport, component: numpy.core

#18486 BUG: remove nonsensical comparison of pointer < 0
  numpy/core/src/multiarray/ctors.c
Labels: 00 - Bug, 08 - Backport, component: numpy.core

#18487 BUG: verify pointer against NULL before using it
  numpy/core/src/multiarray/dtype_transfer.c
Labels: 00 - Bug, 08 - Backport, component: numpy.core

#18488 BUG: check if PyArray_malloc succeeded
  numpy/core/src/umath/ufunc_object.c
Labels: 00 - Bug, 08 - Backport, component: numpy.core

#18475 ENH: Added type annotations to eye() function
  numpy/__init__.pyi
Labels: 01 - Enhancement, static typing

#18489 DOC: Closes issue #7408
  doc/source/reference/routines.array-creation.rst
Labels: 04 - Documentation

#18493 BUG: Fix non-versioneer uses of numpy.distutils
  numpy/distutils/misc_util.py
Labels: 00 - Bug

#18456 NEP: array API standard adoption (NEP 47)
  doc/neps/_static/nep-0047-casting-rules-lattice.png
  doc/neps/_static/nep-0047-library-dependencies.png
  doc/neps/_static/nep-0047-scope-of-array-API.png
  doc/neps/nep-0047-array-api-standard.rst
Labels: component: NEP

#18498 BUG: Fixed Von Mises distribution for big values of kappa
  numpy/random/include/legacy-distributions.h
  numpy/random/mtrand.pyx
  numpy/random/src/distributions/distributions.c
  numpy/random/src/legacy/legacy-distributions.c
  numpy/random/tests/test_generator_mt19937.py
  numpy/random/tests/test_generator_mt19937_regressions.py
  numpy/random/tests/test_randomstate.py
Labels: 00 - Bug

#18482 ENH: Improve error message in multinomial
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
  numpy/random/tests/test_generator_mt19937.py
  numpy/random/tests/test_randomstate.py
Labels: 01 - Enhancement

#18502 DOC: Fix links to landing page
  doc/source/conf.py
  doc/source/index.rst
Labels: 04 - Documentation

#18497 TST: Remove the `einsum` typing tests reliance on issuing a `ComplexWarning`
  numpy/typing/tests/data/pass/einsumfunc.py
Labels: 05 - Testing, static typing

#18397 ENH: Add annotations for `np.lib.index_tricks`
  numpy/__init__.pyi
  numpy/lib/__init__.pyi
  numpy/lib/index_tricks.pyi
  numpy/typing/__init__.py
  numpy/typing/_array_like.py
  numpy/typing/tests/data/fail/index_tricks.py
  numpy/typing/tests/data/pass/index_tricks.py
  numpy/typing/tests/data/reveal/index_tricks.py
Labels: 01 - Enhancement, static typing

#18499 TST: Branch coverage improvement for `np.polynomial`
  numpy/polynomial/tests/test_legendre.py
  numpy/polynomial/tests/test_polynomial.py
  numpy/polynomial/tests/test_polyutils.py
Labels: 05 - Testing

#18513 BLD: add _2_24 to valid manylinux names
  tools/openblas_support.py
Labels: 36 - Build

#18505 DOC: add guide for downstream package authors
  doc/source/user/depending_on_numpy.rst
  doc/source/user/index.rst
Labels: 04 - Documentation
