Repository numpy/numpy, pull requests merged in 2021-09, with the labels that each got.

#19781 MAINT: refactor "for ... in range(len(" statements
  numpy/core/records.py
  numpy/core/tests/test_umath_complex.py
  numpy/f2py/f2py2e.py
  numpy/lib/index_tricks.py
  numpy/lib/polynomial.py
  numpy/lib/tests/test_function_base.py
  numpy/lib/tests/test_shape_base.py
  numpy/lib/utils.py
Labels: 03 - Maintenance

#19811 DEP: Deprecate quote_args (from numpy.distutils.misc_util)
  numpy/distutils/misc_util.py
Labels: 07 - Deprecation

#19817 ENH: Use custom file-like protocols instead of `typing.IO`
  numpy/__init__.pyi
  numpy/core/multiarray.pyi
  numpy/lib/npyio.pyi
  numpy/typing/tests/data/fail/npyio.py
  numpy/typing/tests/data/reveal/npyio.py
Labels: 01 - Enhancement, static typing

#19815 MAINT: revise OSError aliases (IOError, EnvironmentError)
  numpy/core/records.py
  numpy/core/setup.py
  numpy/core/src/multiarray/convert.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/tests/test_multiarray.py
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/cpuinfo.py
  numpy/distutils/exec_command.py
  numpy/distutils/fcompiler/compaq.py
  numpy/distutils/npy_pkg_config.py
  numpy/distutils/unixccompiler.py
  numpy/f2py/crackfortran.py
  numpy/f2py/f2py2e.py
  numpy/f2py/tests/util.py
  numpy/lib/_datasource.py
  numpy/lib/format.py
  numpy/lib/npyio.py
  numpy/lib/tests/test__datasource.py
  numpy/ma/mrecords.py
  runtests.py
  tools/cythonize.py
Labels: 03 - Maintenance

#19803 ENH: Add `is_integer` to `np.floating` & `np.integer`
  doc/release/upcoming_changes/19803.new_feature.rst
  numpy/__init__.pyi
  numpy/core/_add_newdocs_scalars.py
  numpy/core/src/multiarray/scalartypes.c.src
  numpy/core/tests/test_scalar_methods.py
  numpy/typing/tests/data/fail/scalars.py
  numpy/typing/tests/data/reveal/scalars.py
Labels: 01 - Enhancement, 62 - Python API

#19819 MAINT: mark _version.py as generated
  .gitattributes
  .lgtm.yml
Labels: 03 - Maintenance

#19809 MAINT: Fix compiler warnings generated by convert_datatype.h.
  numpy/core/src/multiarray/convert_datatype.h
Labels: 03 - Maintenance

#19818 MAINT: fix unhashable instance and potential exception identified by LGTM.
  numpy/array_api/_typing.py
  numpy/linalg/lapack_lite/clapack_scrub.py
Labels: 03 - Maintenance

#19754 ENH: Add clang-format file
  .clang-format
  doc/release/upcoming_changes/19754.new_feature.rst
Labels: 01 - Enhancement

#18884 DOC: Add support for documenting C/C++ via Doxygen & Breathe
  .circleci/config.yml
  doc/Makefile
  doc/preprocess.py
  doc/release/upcoming_changes/18884.new_feature.rst
  doc/source/conf.py
  doc/source/dev/examples/.doxyfile
  doc/source/dev/examples/doxy_class.hpp
  doc/source/dev/examples/doxy_func.h
  doc/source/dev/examples/doxy_rst.h
  doc/source/dev/howto-docs.rst
  doc/source/dev/howto_build_docs.rst
  doc/source/doxyfile
  doc_requirements.txt
  numpy/core/include/numpy/.doxyfile
  numpy/core/src/common/.doxyfile
Labels: 04 - Documentation, 56 - Needs Release Note.

#19821 BUG: Fixed an issue wherein certain `nan<x>` functions could fail for object arrays
  numpy/lib/nanfunctions.py
  numpy/lib/tests/test_nanfunctions.py
Labels: 00 - Bug

#19845 TST: Make nanfunc test ignore overflow instead of xfailing test
  numpy/lib/tests/test_nanfunctions.py
Labels: 05 - Testing

#19846 MAINT: Update testing to 3.10rc2
  .github/workflows/build_test.yml
  .travis.yml
Labels: 03 - Maintenance

#19829 MAINT: Standardize guards in numpy/core/src/multiarray.
  .clang-format
  numpy/core/src/multiarray/_datetime.h
  numpy/core/src/multiarray/abstractdtypes.h
  numpy/core/src/multiarray/alloc.h
  numpy/core/src/multiarray/array_coercion.h
  numpy/core/src/multiarray/array_method.h
  numpy/core/src/multiarray/arrayfunction_override.h
  numpy/core/src/multiarray/arrayobject.h
  numpy/core/src/multiarray/arraytypes.h
  numpy/core/src/multiarray/calculation.h
  numpy/core/src/multiarray/common.h
  numpy/core/src/multiarray/common_dtype.h
  numpy/core/src/multiarray/compiled_base.h
  numpy/core/src/multiarray/conversion_utils.h
  numpy/core/src/multiarray/convert.h
  numpy/core/src/multiarray/convert_datatype.h
  numpy/core/src/multiarray/ctors.h
  numpy/core/src/multiarray/datetime_busday.h
  numpy/core/src/multiarray/datetime_busdaycal.h
  numpy/core/src/multiarray/datetime_strings.h
  numpy/core/src/multiarray/descriptor.h
  numpy/core/src/multiarray/dragon4.h
  numpy/core/src/multiarray/dtype_transfer.h
  numpy/core/src/multiarray/dtypemeta.h
  numpy/core/src/multiarray/einsum_debug.h
  numpy/core/src/multiarray/einsum_sumprod.h
  numpy/core/src/multiarray/getset.h
  numpy/core/src/multiarray/hashdescr.h
  numpy/core/src/multiarray/item_selection.h
  numpy/core/src/multiarray/iterators.h
  numpy/core/src/multiarray/legacy_dtype_implementation.h
  numpy/core/src/multiarray/mapping.h
  numpy/core/src/multiarray/methods.h
  numpy/core/src/multiarray/multiarraymodule.h
  numpy/core/src/multiarray/nditer_impl.h
  numpy/core/src/multiarray/nditer_pywrap.h
  numpy/core/src/multiarray/npy_buffer.h
  numpy/core/src/multiarray/number.h
  numpy/core/src/multiarray/refcount.h
  numpy/core/src/multiarray/scalartypes.h
  numpy/core/src/multiarray/sequence.h
  numpy/core/src/multiarray/shape.h
  numpy/core/src/multiarray/strfuncs.h
  numpy/core/src/multiarray/temp_elide.h
  numpy/core/src/multiarray/typeinfo.h
  numpy/core/src/multiarray/usertypes.h
  numpy/core/src/multiarray/vdot.h
Labels: 03 - Maintenance

#19826 MAINT: Standardize guards in numpy/core/include
  numpy/core/include/numpy/_neighborhood_iterator_imp.h
  numpy/core/include/numpy/arrayobject.h
  numpy/core/include/numpy/arrayscalars.h
  numpy/core/include/numpy/halffloat.h
  numpy/core/include/numpy/libdivide/libdivide.h
  numpy/core/include/numpy/ndarrayobject.h
  numpy/core/include/numpy/ndarraytypes.h
  numpy/core/include/numpy/noprefix.h
  numpy/core/include/numpy/npy_1_7_deprecated_api.h
  numpy/core/include/numpy/npy_3kcompat.h
  numpy/core/include/numpy/npy_common.h
  numpy/core/include/numpy/npy_cpu.h
  numpy/core/include/numpy/npy_endian.h
  numpy/core/include/numpy/npy_interrupt.h
  numpy/core/include/numpy/npy_math.h
  numpy/core/include/numpy/npy_no_deprecated_api.h
  numpy/core/include/numpy/npy_os.h
  numpy/core/include/numpy/numpyconfig.h
  numpy/core/include/numpy/old_defines.h
  numpy/core/include/numpy/oldnumeric.h
  numpy/core/include/numpy/random/bitgen.h
  numpy/core/include/numpy/random/distributions.h
  numpy/core/include/numpy/ufuncobject.h
  numpy/core/include/numpy/utils.h
Labels: 03 - Maintenance

#19827 MAINT: Standardize guards in numpy/core/src/common.
  numpy/core/setup.py
  numpy/core/src/common/array_assign.h
  numpy/core/src/common/binop_override.h
  numpy/core/src/common/cblasfuncs.h
  numpy/core/src/common/get_attr_string.h
  numpy/core/src/common/lowlevel_strided_loops.h
  numpy/core/src/common/mem_overlap.h
  numpy/core/src/common/npy_argparse.h
  numpy/core/src/common/npy_cblas.h
  numpy/core/src/common/npy_cblas_base.h
  numpy/core/src/common/npy_config.h
  numpy/core/src/common/npy_cpu_dispatch.h
  numpy/core/src/common/npy_cpu_features.h
  numpy/core/src/common/npy_cpuinfo_parser.h
  numpy/core/src/common/npy_ctypes.h
  numpy/core/src/common/npy_extint128.h
  numpy/core/src/common/npy_fpmath.h
  numpy/core/src/common/npy_hashtable.h
  numpy/core/src/common/npy_import.h
  numpy/core/src/common/npy_longdouble.h
  numpy/core/src/common/npy_pycompat.h
  numpy/core/src/common/numpyos.h
  numpy/core/src/common/ucsnarrow.h
  numpy/core/src/common/ufunc_override.h
  numpy/core/src/common/umathmodule.h
Labels: 03 - Maintenance

#19856 MAINT: Mark type-check-only ufunc subclasses as ufunc aliases during runtime
  numpy/typing/__init__.py
Labels: 03 - Maintenance, 09 - Backport-Candidate, static typing

#19854 BUG: Fixed an issue wherein `var` would raise for 0d object arrays
  numpy/core/_methods.py
  numpy/lib/tests/test_nanfunctions.py
Labels: 00 - Bug

#19864 DOC: Update RELEASE_WALKTHROUGH
  doc/RELEASE_WALKTHROUGH.rst.txt
Labels: 04 - Documentation

#19862 DOC: Add BRANCH_WALKTHROUGH
  doc/BRANCH_WALKTHROUGH.rst
Labels: 04 - Documentation

#19870 DOC: Small fixups for the release walkthrough
  doc/RELEASE_WALKTHROUGH.rst.txt
Labels: 04 - Documentation

#19863 BUG: Fix `nanpercentile` ignoring the dtype of all-nan arrays
  numpy/lib/nanfunctions.py
  numpy/lib/tests/test_nanfunctions.py
Labels: 00 - Bug, 05 - Testing

#19874 DOC: Fix typo in upcoming changes filename
  doc/release/upcoming_changes/19665.change.rst
Labels: 04 - Documentation

#19869 BUG: ensure np.median does not drop subclass for NaN result.
  numpy/lib/function_base.py
  numpy/lib/tests/test_function_base.py
  numpy/lib/utils.py
  numpy/ma/extras.py
Labels: 00 - Bug, component: numpy.lib

#19883 DOC: Fix the reported module names of objects in the `numpy.typing` API
  numpy/typing/__init__.py
Labels: 04 - Documentation, static typing

#19882 MAINT: Use SHA-256 instead of SHA-1
  tools/cythonize.py
Labels: 03 - Maintenance

#19865 DOC: Moved NumPy Internals to Under-the-hood documentation for developers
  doc/source/dev/alignment.rst
  doc/source/dev/internals.code-explanations.rst
  doc/source/dev/internals.rst
  doc/source/dev/underthehood.rst
  doc/source/reference/alignment.rst
  doc/source/reference/index.rst
  doc/source/reference/internals.code-explanations.rst
  doc/source/reference/internals.rst
Labels: 04 - Documentation

#19844 DOC: Added missing C-API functions
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#19884 TST: Make this sysconfig handling a bit more portable
  runtests.py
Labels: 05 - Testing

#19887 ENH: Add annotations for `np.linalg`
  numpy/linalg/__init__.pyi
  numpy/linalg/linalg.pyi
  numpy/typing/tests/data/fail/linalg.py
  numpy/typing/tests/data/reveal/linalg.py
Labels: 01 - Enhancement, static typing

#19888 BUG: core: Fix *_like strides for str and bytes dtype.
  numpy/core/src/multiarray/ctors.c
  numpy/core/tests/test_numeric.py
Labels: 00 - Bug, component: numpy.core

#19902 BUG,DOC: Ignore upcoming_changes from refguide
  tools/refguide_check.py
Labels: 00 - Bug

#19894 ENH: Add a typing protocol for representing nested sequences
  numpy/__init__.pyi
  numpy/core/multiarray.pyi
  numpy/core/shape_base.pyi
  numpy/lib/arraypad.pyi
  numpy/lib/index_tricks.pyi
  numpy/lib/shape_base.pyi
  numpy/lib/stride_tricks.pyi
  numpy/lib/twodim_base.pyi
  numpy/lib/type_check.pyi
  numpy/typing/__init__.py
  numpy/typing/_array_like.py
  numpy/typing/_nested_sequence.py
  numpy/typing/tests/data/fail/comparisons.py
  numpy/typing/tests/data/fail/multiarray.py
  numpy/typing/tests/data/fail/nested_sequence.py
  numpy/typing/tests/data/reveal/nested_sequence.py
Labels: 01 - Enhancement, static typing

#19900 DOC:Fixed refguide errors for basics.creation.rst
  doc/source/user/basics.creation.rst
  tools/refguide_check.py
Labels: 04 - Documentation

#19893 MAINT,DOC: f2py restructring
  doc/source/f2py/advanced.rst
  doc/source/f2py/code/allocarr.f90
  doc/source/f2py/code/array.f
  doc/source/f2py/code/calculate.f
  doc/source/f2py/code/callback.f
  doc/source/f2py/code/callback2.pyf
  doc/source/f2py/code/common.f
  doc/source/f2py/code/extcallback.f
  doc/source/f2py/code/fib1.f
  doc/source/f2py/code/fib1.pyf
  doc/source/f2py/code/fib2.pyf
  doc/source/f2py/code/fib3.f
  doc/source/f2py/code/ftype.f
  doc/source/f2py/code/moddata.f90
  doc/source/f2py/code/results/allocarr_session.dat
  doc/source/f2py/code/results/array_session.dat
  doc/source/f2py/code/results/calculate_session.dat
  doc/source/f2py/code/results/callback_session.dat
  doc/source/f2py/code/results/common_session.dat
  doc/source/f2py/code/results/compile_session.dat
  doc/source/f2py/code/results/extcallback_session.dat
  doc/source/f2py/code/results/ftype_session.dat
  doc/source/f2py/code/results/moddata_session.dat
  doc/source/f2py/code/results/run_main_session.dat
  doc/source/f2py/code/results/scalar_session.dat
  doc/source/f2py/code/results/spam_session.dat
  doc/source/f2py/code/results/string_session.dat
  doc/source/f2py/code/results/var_session.dat
  doc/source/f2py/code/scalar.f
  doc/source/f2py/code/setup_example.py
  doc/source/f2py/code/spam.pyf
  doc/source/f2py/code/string.f
  doc/source/f2py/code/var.pyf
  doc/source/f2py/distutils.rst
  doc/source/f2py/f2py.getting-started.rst
  doc/source/f2py/index.rst
  doc/source/f2py/python-usage.rst
  doc/source/f2py/signature-file.rst
  doc/source/f2py/usage.rst
  numpy/f2py/__init__.py
  numpy/f2py/f2py2e.py
Labels: 04 - Documentation, component: numpy.f2py, 03 - Maintenance

#19908 BUG: Check whether an error is already set for invalid casting
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_ufunc.py
Labels: 00 - Bug

#19915 ENH: Add annotations for `np.char`
  numpy/__init__.pyi
  numpy/char.pyi
  numpy/core/defchararray.pyi
  numpy/typing/tests/data/fail/char.py
  numpy/typing/tests/data/reveal/char.py
  numpy/typing/tests/test_isfile.py
Labels: 01 - Enhancement, static typing

#19914 MAINT: Fix LGTM.com warning in nditer_imp.h
  numpy/core/src/multiarray/nditer_impl.h
Labels: 03 - Maintenance

#19775 MAINT,DOC: Readability improvements and cleanup for f2py
  doc/source/f2py/distutils.rst
  numpy/f2py/__main__.py
  numpy/f2py/auxfuncs.py
  numpy/f2py/capi_maps.py
  numpy/f2py/crackfortran.py
  numpy/f2py/f2py2e.py
  numpy/f2py/setup.py
  numpy/f2py/src/test/Makefile
  numpy/f2py/src/test/bar.f
  numpy/f2py/src/test/foo.f
  numpy/f2py/src/test/foo90.f90
  numpy/f2py/src/test/foomodule.c
  numpy/f2py/src/test/wrap.f
  tools/linter.py
Labels: 03 - Maintenance

#19920 DOC: Fix typos in NEPs, found by codespell
  doc/neps/nep-0010-new-iterator-ufunc.rst
  doc/neps/nep-0012-missing-data.rst
  doc/neps/nep-0018-array-function-protocol.rst
  doc/neps/nep-0020-gufunc-signature-enhancement.rst
  doc/neps/nep-0031-uarray.rst
  doc/neps/nep-0035-array-creation-dispatch-with-array-function.rst
  doc/neps/nep-0036-fair-play.rst
  doc/neps/nep-0038-SIMD-optimizations.rst
  doc/neps/nep-0040-legacy-datatype-impl.rst
  doc/neps/nep-0041-improved-dtype-support.rst
  doc/neps/nep-0042-new-dtypes.rst
  doc/neps/nep-0043-extensible-ufuncs.rst
  doc/neps/nep-0049.rst
  setup.cfg
Labels: 04 - Documentation

#19776 DOC: Add explanation of a sparse mesh grid
  numpy/lib/function_base.py
Labels: 04 - Documentation

#19918 MAINT: Override the modules of `np.char` and `np.rec` functions
  numpy/core/defchararray.py
  numpy/core/records.py
Labels: 03 - Maintenance

#19917 ENH: Add annotations for `np.lib.arraysetops`
  numpy/lib/arraysetops.pyi
  numpy/typing/tests/data/reveal/arraysetops.py
Labels: 01 - Enhancement, static typing

#19905 DOC: fix docstring formatting of polynomial fit method return values.
  numpy/lib/polynomial.py
  numpy/polynomial/_polybase.py
  numpy/polynomial/chebyshev.py
  numpy/polynomial/hermite.py
  numpy/polynomial/hermite_e.py
  numpy/polynomial/laguerre.py
  numpy/polynomial/legendre.py
  numpy/polynomial/polynomial.py
Labels: 04 - Documentation

#19903 DOC: Fixed refguide errors for basics.broadcasting.rst
  doc/source/user/basics.broadcasting.rst
  tools/refguide_check.py
Labels: 04 - Documentation

#19925 BUG: ufunc: Fix potential memory leak.
  numpy/core/src/umath/ufunc_object.c
Labels: 00 - Bug, component: numpy.ufunc

#19927 BUG: Only call the get_versions() function once on import
  numpy/__init__.py
  numpy/version.py
Labels: 00 - Bug

#19934 BUG: core: Fix memory leak in the C function boundarraymethod_repr.
  numpy/core/src/multiarray/array_method.c
Labels: 00 - Bug, component: numpy.core

#19936 BUG: Make sure __version__ is defined in setup mode
  numpy/__init__.py
Labels: 00 - Bug

#19933 MAINT: random: Use expm1 where appropriate.
  numpy/random/src/distributions/distributions.c
Labels: component: numpy.random, 03 - Maintenance

#19928 MAINT: lib: Check that the dtype given to fromregex is structured.
  numpy/lib/npyio.py
  numpy/lib/tests/test_io.py
Labels: component: numpy.lib, 03 - Maintenance

#19948 MAINT: Add annotations for three missing `ndarray` methods
  numpy/__init__.pyi
Labels: 03 - Maintenance, static typing

#19939 MAINT: Fix LGTM.com warning: Constant in conditional expression or statement
  numpy/f2py/f2py2e.py
Labels: 03 - Maintenance

#19940 MAINT: Fix LGTM.com warning: Variable `isrec` defined multiple times
  numpy/f2py/crackfortran.py
Labels: 03 - Maintenance

#19943 MAINT: Fix LGTM.com warning: Variable `f` defined multiple times
  numpy/distutils/system_info.py
Labels: 03 - Maintenance

#19946 MAINT: Fix LGTM.com warning: Comparison result is always the same (`p`)
  numpy/core/src/multiarray/nditer_api.c
Labels: 03 - Maintenance

#19942 MAINT: Fix LGTM.com warning: Unreachable code
  numpy/distutils/fcompiler/gnu.py
Labels: 03 - Maintenance

#19944 MAINT: Fix LGTM.com warning: Comparison result is always the same (`res`)
  numpy/core/src/multiarray/ctors.c
Labels: 03 - Maintenance

#19949 ENH: Add annotations for `np.rec`
  numpy/__init__.pyi
  numpy/core/records.pyi
  numpy/lib/npyio.pyi
  numpy/rec.pyi
  numpy/typing/__init__.py
  numpy/typing/tests/data/fail/rec.py
  numpy/typing/tests/data/reveal/npyio.py
  numpy/typing/tests/data/reveal/rec.py
  numpy/typing/tests/data/reveal/scalars.py
  numpy/typing/tests/test_isfile.py
Labels: 01 - Enhancement, static typing

#19951 MAINT: Fix LGTM.com warning: Comparison is always false because `bufferSize` >= 16384
  numpy/core/src/multiarray/dragon4.c
Labels: 03 - Maintenance

#19879 ENH: Add `__class_getitem__` to `ndarray`, `dtype` and `number`
  doc/release/upcoming_changes/19879.new_feature.rst
  doc/source/reference/arrays.dtypes.rst
  doc/source/reference/arrays.ndarray.rst
  doc/source/reference/arrays.scalars.rst
  numpy/__init__.pyi
  numpy/core/_add_newdocs.py
  numpy/core/src/multiarray/descriptor.c
  numpy/core/src/multiarray/methods.c
  numpy/core/src/multiarray/scalartypes.c.src
  numpy/core/tests/test_arraymethod.py
  numpy/core/tests/test_dtype.py
  numpy/core/tests/test_scalar_methods.py
  numpy/typing/_generic_alias.py
  tools/refguide_check.py
Labels: 01 - Enhancement, 62 - Python API

#19937 ENH: Updates to numpy.array_api
  numpy/array_api/__init__.py
  numpy/array_api/_array_object.py
  numpy/array_api/_creation_functions.py
  numpy/array_api/_linear_algebra_functions.py
  numpy/array_api/_manipulation_functions.py
  numpy/array_api/_statistical_functions.py
  numpy/array_api/_typing.py
  numpy/array_api/tests/test_array_object.py
Labels: 01 - Enhancement

#19926 BUG: Resolve Divide by Zero on Apple silicon + test failures
  numpy/core/src/umath/loops_unary_fp.dispatch.c.src
Labels: 00 - Bug, 09 - Backport-Candidate, component: SIMD

#19955 BUG: Resolve Divide by Zero on Apple silicon + test failures (#19926)
  numpy/core/src/umath/loops_unary_fp.dispatch.c.src
Labels: 00 - Bug, 08 - Backport, component: SIMD

#19958 MAINT: Mark type-check-only ufunc subclasses as ufunc aliases during runtime
  numpy/typing/__init__.py
Labels: 03 - Maintenance, 08 - Backport, static typing

#19953 ENH: Add annotations to `np.core.multiarray` part 4/4
  numpy/__init__.pyi
  numpy/core/_add_newdocs.py
  numpy/core/multiarray.pyi
  numpy/typing/tests/data/fail/multiarray.py
  numpy/typing/tests/data/fail/nditer.py
  numpy/typing/tests/data/reveal/multiarray.py
  numpy/typing/tests/data/reveal/nditer.py
Labels: 01 - Enhancement, static typing

#19805 ENH: Symbolic solver for dimension specifications.
  numpy/f2py/crackfortran.py
  numpy/f2py/symbolic.py
  numpy/f2py/tests/test_crackfortran.py
  numpy/f2py/tests/test_symbolic.py
  numpy/tests/test_public_api.py
Labels: 01 - Enhancement, component: numpy.f2py

#19960 DOC: Minor syntax fix for numpydoc warnings
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation

#19962 DOC: Remove overstated TDD evangelism.
  doc/TESTS.rst.txt
Labels: 04 - Documentation

#19968 ENH: nagfor from NAG is available on Darwin
  numpy/distutils/fcompiler/__init__.py
Labels: 01 - Enhancement

#19963 DOC: rename `np.lib.scimath` to `np.emath`
  numpy/lib/scimath.py
Labels: 04 - Documentation

#19967 DOC: Update basics.io.genfromtxt.rst
  doc/source/user/basics.io.genfromtxt.rst
Labels: 04 - Documentation

#19965 MAINT: Update funding link in FUNDING.yml
  .github/FUNDING.yml
Labels: 03 - Maintenance

#19913 MAINT: Fix LGTM.com error: Unmatchable caret in regular expression
  numpy/linalg/lapack_lite/clapack_scrub.py
Labels: 03 - Maintenance

#19983 DOC: Specifically mention the C99 requirement in 'Building from source'
  doc/source/user/building.rst
Labels: 04 - Documentation

#19979 ENH: Add annotations for `np.memmap`
  numpy/__init__.pyi
  numpy/core/memmap.pyi
  numpy/typing/tests/data/fail/memmap.py
  numpy/typing/tests/data/reveal/memmap.py
Labels: 01 - Enhancement, static typing

#19974 BUG: np.tan(np.inf) test failure in Apple silicon
  numpy/core/src/npymath/npy_math_internal.h.src
Labels: 00 - Bug

#19961 MAINT: Minor cleanups after merging gh-19805
  doc/release/upcoming_changes/19805.new_feature.rst
  numpy/f2py/tests/test_crackfortran.py
Labels: 03 - Maintenance

#19987 BUG: Remove double cast to char in favor of PyArray_BYTES
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
Labels: 00 - Bug

#19921 DEP: Use `delimiter` rather than `delimitor` as kwarg in mrecords
  doc/release/upcoming_changes/19921.deprecation.rst
  numpy/ma/mrecords.py
  numpy/ma/mrecords.pyi
  numpy/ma/tests/test_deprecations.py
Labels: 03 - Maintenance, 07 - Deprecation, 56 - Needs Release Note.

#19984 MAINT: Configure pytest to ignore array_api warnings.
  pytest.ini
Labels: 03 - Maintenance

#19988 DOC: Update links to online copy of Abramowitz and Stegun.
  numpy/core/code_generators/ufunc_docstrings.py
  numpy/lib/function_base.py
Labels: 04 - Documentation

#19992 ENH: nagfor - get_flags_linker_so() on darwin
  numpy/distutils/fcompiler/nag.py
Labels: 01 - Enhancement, component: numpy.distutils

#19977 MAINT: clang-format for f2py
  numpy/f2py/src/fortranobject.c
  numpy/f2py/src/fortranobject.h
Labels: component: numpy.f2py, 03 - Maintenance

#19994 BUG: np.tan(np.inf) test failure
  numpy/core/src/npymath/npy_math_internal.h.src
Labels: 00 - Bug, 08 - Backport

#19978 MAINT: Reduce DepreciationWarnings, use more data API types for f2py
  numpy/f2py/cfuncs.py
  numpy/f2py/rules.py
  numpy/f2py/src/fortranobject.c
Labels: 03 - Maintenance

#19999 DOC: Copy-edit and fix typos.
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#19986 MAINT: Fix LGTM.com warning: Comparison result is always the same (`denom`)
  numpy/core/src/multiarray/datetime.c
Labels: 03 - Maintenance

#19686 ENH: Add spaces after punctuation in dtype repr/str.
  doc/release/upcoming_changes/19687.change.rst
  doc/source/user/basics.rec.rst
  numpy/core/_dtype.py
  numpy/core/arrayprint.py
  numpy/core/arrayprint.pyi
  numpy/core/records.py
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/multiarray/scalartypes.c.src
  numpy/core/tests/test_dtype.py
  numpy/lib/recfunctions.py
  numpy/ma/core.py
Labels: 01 - Enhancement, 03 - Maintenance

#19814 ENH: Replaced markdown issue templates with issue forms
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/post-install.md
  .github/ISSUE_TEMPLATE/post-install.yml
Labels: 01 - Enhancement

#19843 TST: Fix/Improve cast nonstandard bool to numeric test
  numpy/core/tests/test_casting_unittests.py
Labels: 00 - Bug, 05 - Testing

#20003 BLD: updated mypy version from 0.902 to 0.910
  environment.yml
Labels: 36 - Build

#19969 MAINT: Misc `np.array_api` annotation fixes
  numpy/array_api/_creation_functions.py
  numpy/array_api/_data_type_functions.py
  numpy/array_api/_typing.py
Labels: 03 - Maintenance, static typing
