Repository numpy/numpy, pull requests merged in 2021-05, with the labels that each got.

#18882 ENH: Add min values comparison for floating point
  numpy/core/src/_simd/_simd.dispatch.c.src
  numpy/core/src/common/simd/avx2/math.h
  numpy/core/src/common/simd/avx512/math.h
  numpy/core/src/common/simd/neon/math.h
  numpy/core/src/common/simd/sse/math.h
  numpy/core/src/common/simd/vsx/math.h
  numpy/core/tests/test_simd.py
Labels: 01 - Enhancement, component: SIMD

#18887 MAINT: Relax certain integer-type constraints
  numpy/__init__.pyi
  numpy/typing/_shape.py
  numpy/typing/tests/data/pass/array_constructors.py
Labels: 03 - Maintenance, 08 - Backport, static typing

#18805 NEP: propose new nep for allocator policies
  doc/neps/nep-0049.rst
Labels: component: NEP

#18897 MAINT: Add ".csv" some data file names.
  numpy/core/tests/data/umath-validation-set-README.txt
  numpy/core/tests/data/umath-validation-set-cos.csv
  numpy/core/tests/data/umath-validation-set-exp.csv
  numpy/core/tests/data/umath-validation-set-log.csv
  numpy/core/tests/data/umath-validation-set-sin.csv
  numpy/core/tests/test_umath_accuracy.py
Labels: 03 - Maintenance, 05 - Testing, component: numpy.core

#18890 MAINT: ssize_t -> Py_ssize_t and other fixes for Python v3.10.0
  numpy/core/include/numpy/npy_3kcompat.h
  numpy/core/src/common/npy_argparse.c
  numpy/core/src/multiarray/array_method.c
  numpy/core/src/multiarray/common.h
  numpy/core/src/multiarray/dtype_transfer.c
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/tests/test_multiarray.py
Labels: 03 - Maintenance

#18899 BLD, BUG: Fix compiler optimization log AttributeError
  numpy/distutils/command/build_clib.py
  numpy/distutils/command/build_ext.py
Labels: 00 - Bug, 36 - Build, component: numpy.distutils

#18900 BLD: remove unnecessary flag `-faltivec` on macOS
  numpy/distutils/system_info.py
Labels: 09 - Backport-Candidate, 36 - Build

#18896 MAINT: Explicitly mark text files in .gitattributes.
  .gitattributes
Labels: 03 - Maintenance

#18903 MAINT, CI: treats _SIMD module build warnings as errors through CI only
  numpy/core/src/_simd/_simd.dispatch.c.src
  tools/travis-test.sh
Labels: 03 - Maintenance

#18885 MAINT: Remove unsafe unions and ABCs from return-annotations
  numpy/__init__.pyi
  numpy/core/einsumfunc.pyi
  numpy/core/fromnumeric.pyi
  numpy/core/function_base.pyi
  numpy/core/numeric.pyi
  numpy/lib/index_tricks.pyi
  numpy/lib/ufunclike.pyi
  numpy/typing/__init__.py
  numpy/typing/_array_like.py
  numpy/typing/_callable.py
  numpy/typing/tests/data/fail/fromnumeric.py
  numpy/typing/tests/data/fail/index_tricks.py
  numpy/typing/tests/data/reveal/arithmetic.py
  numpy/typing/tests/data/reveal/array_constructors.py
  numpy/typing/tests/data/reveal/comparisons.py
  numpy/typing/tests/data/reveal/einsumfunc.py
  numpy/typing/tests/data/reveal/fromnumeric.py
  numpy/typing/tests/data/reveal/index_tricks.py
  numpy/typing/tests/data/reveal/mod.py
  numpy/typing/tests/data/reveal/ndarray_misc.py
  numpy/typing/tests/data/reveal/numeric.py
  numpy/typing/tests/data/reveal/ufunclike.py
  tools/lint_diff.ini
Labels: 03 - Maintenance, 09 - Backport-Candidate, static typing

#18874 BLD, ENH: Enable Accelerate Framework
  doc/release/upcoming_changes/18874.change.rst
  numpy/core/setup.py
  numpy/core/tests/test_multiarray.py
  numpy/distutils/system_info.py
  numpy/linalg/setup.py
Labels: 01 - Enhancement, 36 - Build

#18908 MAINT: Adjust NumPy float hashing to Python's slightly changed hash
  numpy/core/src/common/npy_pycompat.h
  numpy/core/src/multiarray/scalartypes.c.src
  numpy/core/tests/test_scalarmath.py
Labels: 03 - Maintenance

#18912 CI: fix the GitHub Actions trigger in docker.yml
  .github/workflows/docker.yml
  environment.yml
Labels: component: CI

#18906 ENH: Add PCG64DXSM BitGenerator
  doc/release/upcoming_changes/18906.new_function.rst
  doc/source/reference/random/bit_generators/index.rst
  doc/source/reference/random/bit_generators/pcg64dxsm.rst
  doc/source/reference/random/index.rst
  doc/source/reference/random/parallel.rst
  doc/source/reference/random/performance.py
  doc/source/reference/random/performance.rst
  doc/source/reference/random/upgrading-pcg64.rst
  numpy/random/__init__.py
  numpy/random/__init__.pyi
  numpy/random/_pcg64.pyi
  numpy/random/_pcg64.pyx
  numpy/random/_pickle.py
  numpy/random/src/pcg64/pcg64.c
  numpy/random/src/pcg64/pcg64.h
  numpy/random/tests/data/pcg64dxsm-testset-1.csv
  numpy/random/tests/data/pcg64dxsm-testset-2.csv
  numpy/random/tests/test_direct.py
  numpy/random/tests/test_smoke.py
Labels: 01 - Enhancement, component: numpy.random

#18911 BLD, BUG: Fix bdist_wheel duplicate building
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/command/build_clib.py
  numpy/distutils/command/build_ext.py
Labels: 00 - Bug, 36 - Build, component: numpy.distutils

#18919 ENH: Add placeholder annotations for two missing `np.testing` objects
  numpy/testing/__init__.pyi
Labels: 01 - Enhancement, static typing

#18920 BUG: Report underflow condition in AVX implementation of np.exp
  numpy/core/src/umath/loops_exponent_log.dispatch.c.src
  numpy/core/tests/test_umath.py
Labels: 00 - Bug

#18915 MAINT: Remove unsafe unions and ABCs from return-annotations
  numpy/__init__.pyi
  numpy/core/fromnumeric.pyi
  numpy/core/function_base.pyi
  numpy/core/numeric.pyi
  numpy/typing/_callable.py
  numpy/typing/tests/data/fail/fromnumeric.py
  numpy/typing/tests/data/reveal/arithmetic.py
  numpy/typing/tests/data/reveal/array_constructors.py
  numpy/typing/tests/data/reveal/fromnumeric.py
  numpy/typing/tests/data/reveal/ndarray_misc.py
  numpy/typing/tests/data/reveal/numeric.py
Labels: 03 - Maintenance, 08 - Backport, static typing

#18910 BUG : for MINGW, threads.h existence test requires GLIBC > 2.12
  numpy/f2py/cfuncs.py
Labels: 00 - Bug

#18909 ENH: Improve the placeholder annotations within sub-modules (part 3)
  numpy/ma/__init__.pyi
  numpy/ma/core.pyi
  numpy/ma/extras.pyi
  numpy/ma/mrecords.pyi
  numpy/polynomial/__init__.pyi
  numpy/polynomial/_polybase.pyi
  numpy/polynomial/chebyshev.pyi
  numpy/polynomial/hermite.pyi
  numpy/polynomial/hermite_e.pyi
  numpy/polynomial/laguerre.pyi
  numpy/polynomial/legendre.pyi
  numpy/polynomial/polynomial.pyi
  numpy/polynomial/polyutils.pyi
Labels: 01 - Enhancement, static typing

#18921 MAINT: Allow more recursion depth for scalar tests.
  numpy/core/tests/test_scalarmath.py
Labels: 03 - Maintenance, 08 - Backport, component: numpy.core

#18923 BLD: remove unnecessary flag `-faltivec` on macOS
  numpy/distutils/system_info.py
Labels: 08 - Backport, 36 - Build

#18925 BUG: for MINGW, threads.h existence test requires GLIBC > 2.12
  numpy/f2py/cfuncs.py
Labels: 00 - Bug, 08 - Backport, component: numpy.f2py

#18922 BUG: Initialize the full nditer buffer in case of error
  numpy/core/src/multiarray/nditer_api.c
  numpy/core/src/multiarray/nditer_constr.c
  numpy/core/tests/test_nditer.py
Labels: 00 - Bug, 08 - Backport, component: numpy.core

#18864 MAINT: Remove dead codepath in generalized ufuncs
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_multiarray.py
Labels: 03 - Maintenance

#18836 MAINT: Generalize and shorten the ufunc "trivially iterable" path
  numpy/core/src/common/lowlevel_strided_loops.h
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_mem_overlap.py
Labels: 03 - Maintenance

#18924 MAINT, CI: treats _SIMD module build warnings as errors through CI only
  numpy/core/src/_simd/_simd.dispatch.c.src
Labels: 03 - Maintenance, 08 - Backport, component: numpy.core

#18918 DOC: fix documentation of cloning over ssh
  doc/source/dev/gitwash/development_setup.rst
Labels: 04 - Documentation, component: Documentation

#18843 DOC: Clarify isreal docstring
  numpy/lib/type_check.py
Labels: 04 - Documentation, component: numpy.lib

#18933 BUG: Fix underflow error in AVX512 implementation of ufunc exp/f64
  numpy/core/src/umath/loops_exponent_log.dispatch.c.src
  numpy/core/tests/test_ufunc.py
Labels: 00 - Bug, component: SIMD

#18930 BUG: Make changelog recognize ``gh-`` as a PR number prefix.
  doc/changelog/1.17.0-changelog.rst
  doc/changelog/1.18.0-changelog.rst
  doc/changelog/1.19.0-changelog.rst
  doc/changelog/1.20.0-changelog.rst
  tools/changelog.py
Labels: 00 - Bug, 03 - Maintenance, 09 - Backport-Candidate

#18934 DOC: Add a release note for the improved placeholder annotations
  .gitignore
  doc/release/upcoming_changes/18934.improvement.rst
Labels: 04 - Documentation, static typing

#18927 NEP: add mailing list thread, fixes from review
  doc/neps/nep-0049.rst
Labels: 04 - Documentation, component: NEP

#18941 BUG: Make changelog recognize gh- as a PR number prefix.
  doc/changelog/1.17.0-changelog.rst
  doc/changelog/1.18.0-changelog.rst
  doc/changelog/1.19.0-changelog.rst
  doc/changelog/1.20.0-changelog.rst
  tools/changelog.py
Labels: 00 - Bug, 03 - Maintenance, 08 - Backport

#18943 TST: xfail `TestCond.test_nan` unconditionally
  numpy/linalg/tests/test_linalg.py
Labels: 03 - Maintenance, 05 - Testing, component: numpy.linalg

#18955 DOC: add an extra example in runtests.py help test
  runtests.py
Labels: 04 - Documentation

#18954 DOC: Update beginners docu for sum function with axis
  doc/source/user/absolute_beginners.rst
Labels: 04 - Documentation

#18956 DOC: change copyright SciPy to NumPy
  doc/source/conf.py
Labels: 04 - Documentation

#18959 DOC: improve numpy.histogram2d() documentation
  numpy/lib/twodim_base.py
Labels: 04 - Documentation

#18962 DOC: Update a page title with proper case
  doc/source/dev/releasing.rst
Labels: 04 - Documentation

#18972 ENH: Include co-authors in changelog.
  tools/changelog.py
Labels: 01 - Enhancement

#18961 DOC: add note and examples to `isrealobj` docstring
  numpy/lib/type_check.py
Labels: 04 - Documentation

#18967 BUG: fix np.ma.masked_where(copy=False) when input has no mask
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
Labels: 00 - Bug, component: numpy.ma

#18982 MAINT: Cleanup tools/changelog.py
  tools/changelog.py
Labels: 03 - Maintenance

#18983 REL: Update main after 1.20.3 release.
  doc/changelog/1.20.3-changelog.rst
  doc/source/release.rst
  doc/source/release/1.20.2-notes.rst
  doc/source/release/1.20.3-notes.rst
Labels: 04 - Documentation, 14 - Release, component: Documentation

#18889 ENH: Add SIMD operations for min and max value comparision
  numpy/core/src/_simd/_simd.dispatch.c.src
  numpy/core/src/common/simd/avx2/math.h
  numpy/core/src/common/simd/avx512/math.h
  numpy/core/src/common/simd/neon/math.h
  numpy/core/src/common/simd/sse/math.h
  numpy/core/src/common/simd/vsx/math.h
  numpy/core/tests/test_simd.py
Labels: 01 - Enhancement, component: SIMD

#18989 BUG: fix potential buffer overflow(#18939)
  numpy/core/src/multiarray/ctors.c
Labels: 00 - Bug

#18936 DOC: Update performance for new PRNG
  doc/source/reference/random/performance.rst
Labels: 04 - Documentation

#18960 BUG: fixed ma.average ignoring masked weights
  numpy/ma/extras.py
  numpy/ma/tests/test_extras.py
Labels: 00 - Bug, component: numpy.ma

#18958 MAINT: Do not use deprecated ``mktemp()``
  numpy/core/tests/test_memmap.py
  numpy/core/tests/test_multiarray.py
Labels: 03 - Maintenance, 07 - Deprecation

#18998 ENH: Improve annotations of the `item`, `tolist`, `take` and `repeat` methods
  numpy/__init__.pyi
  numpy/core/fromnumeric.pyi
  numpy/typing/tests/data/fail/fromnumeric.py
  numpy/typing/tests/data/pass/ndarray_misc.py
  numpy/typing/tests/data/pass/scalars.py
  numpy/typing/tests/data/reveal/ndarray_misc.py
  numpy/typing/tests/data/reveal/scalars.py
Labels: 01 - Enhancement, static typing

#18996 MAINT: Remove warning when checking AVX512f on MSVC
  numpy/distutils/checks/extra_avx512f_reduce.c
Labels: 03 - Maintenance

#18987 BUG: Update coordinates in PyArray_ITER_GOTO1D
  numpy/core/include/numpy/ndarraytypes.h
  numpy/core/src/multiarray/_multiarray_tests.c.src
  numpy/core/src/multiarray/iterators.c
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug, component: numpy.core

#18965 DOC: Improve description of array scalar in glossary
  doc/source/glossary.rst
Labels: 04 - Documentation

#19007 BUG: fix potential use of null pointer in nditer buffers
  numpy/core/src/multiarray/nditer_constr.c
Labels: 00 - Bug, 09 - Backport-Candidate

#19009 BUG: fix variable misprint checking wrong variable in umath tests
  numpy/core/src/umath/_umath_tests.c.src
Labels: 00 - Bug

#19008 BUG: fix variable misprint in multiarray test code
  numpy/core/src/multiarray/_multiarray_tests.c.src
Labels: 00 - Bug

#18880 API: Ensure that casting does not affect ufunc loop
  doc/release/upcoming_changes/18880.compatibility.rst
  doc/source/reference/ufuncs.rst
  numpy/core/src/umath/ufunc_object.c
  numpy/core/src/umath/ufunc_type_resolution.c
  numpy/core/src/umath/ufunc_type_resolution.h
  numpy/core/tests/test_scalar_methods.py
  numpy/core/tests/test_ufunc.py
Labels: 30 - API, 62 - Python API

#19014 Revert "BUG: Update coordinates in PyArray_ITER_GOTO1D"
  numpy/core/include/numpy/ndarraytypes.h
  numpy/core/src/multiarray/_multiarray_tests.c.src
  numpy/core/src/multiarray/iterators.c
  numpy/core/tests/test_multiarray.py
Labels: 03 - Maintenance

#18999 DEP: Ensure the string promotion FutureWarning is raised
  doc/release/upcoming_changes/18116.future.rst
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_regression.py
  numpy/ma/tests/test_mrecords.py
Labels: 07 - Deprecation

#19018 DOC: "NumPy" <- "numpy" in NumPy Fundamentals - Indexing
  doc/source/user/basics.indexing.rst
Labels: 04 - Documentation

#18895 DOC: Improve cumsum documentation
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#19026 DOC: Clarify minimum numpy version needed to use random c-api
  doc/source/reference/random/c-api.rst
Labels: 04 - Documentation

#19005 ENH: Add dtype-support to 11 `ndarray` / `generic` methods
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/ndarray_misc.py
  numpy/typing/tests/data/pass/ndarray_misc.py
  numpy/typing/tests/data/pass/scalars.py
  numpy/typing/tests/data/reveal/ndarray_misc.py
  numpy/typing/tests/data/reveal/scalars.py
Labels: 01 - Enhancement, static typing

#19002 ENH: Add annotations for `np.broadcast` and `np.DataSource`
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/datasource.py
  numpy/typing/tests/data/pass/multiarray.py
  numpy/typing/tests/data/reveal/datasource.py
  numpy/typing/tests/data/reveal/multiarray.py
Labels: 01 - Enhancement, static typing

#18935 API: Add `npt.NDArray`, a runtime-subscriptable alias for `np.ndarray`
  doc/release/upcoming_changes/18935.new_feature.rst
  numpy/__init__.pyi
  numpy/core/_add_newdocs.py
  numpy/lib/index_tricks.pyi
  numpy/lib/ufunclike.pyi
  numpy/typing/__init__.py
  numpy/typing/_add_docstring.py
  numpy/typing/_array_like.py
  numpy/typing/_callable.py
  numpy/typing/_generic_alias.py
  numpy/typing/tests/test_generic_alias.py
Labels: 30 - API, static typing

#19021 DOC: Add comment for ifdef macro guard
  numpy/core/src/common/simd/avx2/math.h
  numpy/core/src/common/simd/avx512/math.h
  numpy/core/src/common/simd/neon/math.h
  numpy/core/src/common/simd/sse/math.h
Labels: 04 - Documentation

#19011 BUG: fix ValueError in PyArray_Std on win_amd64
  numpy/core/src/multiarray/calculation.c
Labels: 00 - Bug, 09 - Backport-Candidate

#19031 DEP: Deprecate 4 `ndarray.ctypes` methods
  doc/release/upcoming_changes/19031.deprecation.rst
  doc/source/user/misc.rst
  numpy/core/_internal.py
  numpy/core/tests/test_deprecations.py
Labels: 07 - Deprecation

#19035 MAINT: Python3 classes do not need to inherit from object
  doc/neps/nep-0013-ufunc-overrides.rst
  numpy/core/tests/test_cpu_features.py
  numpy/core/tests/test_regression.py
  numpy/core/tests/test_umath.py
  numpy/core/tests/test_umath_complex.py
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/tests/test_ccompiler_opt.py
  tools/travis-sorter.py
Labels: 03 - Maintenance

#19041 DOC: Improve trapz docstring
  numpy/lib/function_base.py
Labels: 04 - Documentation

#19037 BUG: use PyLong_FromSsize_t where needed
  numpy/core/src/multiarray/nditer_pywrap.c
Labels: 00 - Bug

#16987 ENH: Phase unwrapping generalized to arbitrary interval size
  doc/release/upcoming_changes/16987.improvement.rst
  numpy/lib/function_base.py
  numpy/lib/tests/test_function_base.py
Labels: 01 - Enhancement, 62 - Python API, component: numpy.lib

#19043 DOC: Fix typo in release notes for v1.21
  doc/release/upcoming_changes/17727.performance.rst
Labels: 04 - Documentation

#18676 MAINT: Implement new style promotion for `np.result_type`, etc.
  azure-pipelines.yml
  doc/source/reference/global_state.rst
  doc/source/reference/ufuncs.rst
  numpy/core/code_generators/genapi.py
  numpy/core/include/numpy/ndarraytypes.h
  numpy/core/setup.py
  numpy/core/src/multiarray/_multiarray_tests.c.src
  numpy/core/src/multiarray/abstractdtypes.c
  numpy/core/src/multiarray/abstractdtypes.h
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/src/multiarray/array_coercion.h
  numpy/core/src/multiarray/array_method.c
  numpy/core/src/multiarray/common_dtype.c
  numpy/core/src/multiarray/common_dtype.h
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/convert_datatype.h
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/src/multiarray/legacy_dtype_implementation.c
  numpy/core/src/multiarray/legacy_dtype_implementation.h
  numpy/core/src/multiarray/methods.c
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/multiarray/number.c
  numpy/core/tests/test_casting_unittests.py
  numpy/core/tests/test_dtype.py
  numpy/core/tests/test_shape_base.py
Labels: 03 - Maintenance

#19001 DEP: Deprecate error clearing for special method in array-coercion
  doc/release/upcoming_changes/19001.deprecation.rst
  numpy/core/src/multiarray/ctors.c
  numpy/core/tests/test_deprecations.py
Labels: 07 - Deprecation

#19047 BUG, SIMD: Fix NumPy build on ppc64le(IBM/Power) for old versions of GCC(<=6)
  numpy/core/src/common/simd/vsx/arithmetic.h
  numpy/core/src/common/simd/vsx/operators.h
Labels: 00 - Bug, 09 - Backport-Candidate, 36 - Build, component: SIMD

#19048 BUG: Fix duplicate variable names in compiler check for AVX512_SKX
  numpy/core/setup_common.py
Labels: 00 - Bug

#19052 ENH: Improve the `np.ufunc` annotations
  numpy/__init__.pyi
  numpy/core/_add_newdocs.py
  numpy/core/_internal.py
  numpy/typing/__init__.py
  numpy/typing/_ufunc.pyi
  numpy/typing/setup.py
  numpy/typing/tests/data/fail/ufuncs.py
  numpy/typing/tests/data/pass/ufuncs.py
  numpy/typing/tests/data/reveal/ufuncs.py
Labels: 01 - Enhancement, static typing

#19046 BUG, SIMD: Fix unexpected result of uint8 division on X86
  numpy/core/src/common/simd/avx2/arithmetic.h
  numpy/core/src/common/simd/avx512/arithmetic.h
  numpy/core/src/common/simd/intdiv.h
  numpy/core/src/common/simd/sse/arithmetic.h
  numpy/core/tests/test_simd.py
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, component: SIMD

#19055 DOC: Forward port missing 1.18.5 release note.
  doc/changelog/1.18.5-changelog.rst
  doc/source/release.rst
  doc/source/release/1.18.5-notes.rst
Labels: 03 - Maintenance, 04 - Documentation

#18766 ENH, SIMD: Replace libdivide functions of signed integer division with universal intrinsics
  numpy/core/code_generators/generate_umath.py
  numpy/core/src/common/simd/intdiv.h
  numpy/core/src/umath/loops.c.src
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/loops_arithmetic.dispatch.c.src
Labels: 01 - Enhancement, component: SIMD

#19063 ENH: Stubs for array_equal appear out of date.
  numpy/core/numeric.pyi
Labels: 01 - Enhancement, static typing

#19066 BUG: Fixed an issue wherein `nanmedian` could return an array with the wrong dtype
  numpy/lib/nanfunctions.py
  numpy/lib/tests/test_nanfunctions.py
Labels: 00 - Bug

#19068 MAINT: Update mailmap
  .mailmap
Labels: 03 - Maintenance

#19070 REL: Prepare for NumPy 1.22.0 development
  doc/release/upcoming_changes/15271.compatibility.rst
  doc/release/upcoming_changes/16987.improvement.rst
  doc/release/upcoming_changes/17492.deprecation.rst
  doc/release/upcoming_changes/17586.deprecation.rst
  doc/release/upcoming_changes/17727.performance.rst
  doc/release/upcoming_changes/17843.new_feature.rst
  doc/release/upcoming_changes/17900.expired.rst
  doc/release/upcoming_changes/17921.compatibility.rst
  doc/release/upcoming_changes/18070.improvement.rst
  doc/release/upcoming_changes/18110.change.rst
  doc/release/upcoming_changes/18116.future.rst
  doc/release/upcoming_changes/18322.new_feature.rst
  doc/release/upcoming_changes/18629.new_feature.rst
  doc/release/upcoming_changes/18657.performance.rst
  doc/release/upcoming_changes/18658.compatibility.rst
  doc/release/upcoming_changes/18666.improvement.rst
  doc/release/upcoming_changes/18695.new_feature.rst
  doc/release/upcoming_changes/18697.expired.rst
  doc/release/upcoming_changes/18718.c_api.rst
  doc/release/upcoming_changes/18718.compatibility.rst
  doc/release/upcoming_changes/18737.new_feature.rst
  doc/release/upcoming_changes/18874.change.rst
  doc/release/upcoming_changes/18880.compatibility.rst
  doc/release/upcoming_changes/18906.new_function.rst
  doc/release/upcoming_changes/18934.improvement.rst
  doc/release/upcoming_changes/18935.new_feature.rst
  doc/release/upcoming_changes/18963.expired.rst
  doc/release/upcoming_changes/19001.deprecation.rst
  doc/release/upcoming_changes/19031.deprecation.rst
  doc/release/upcoming_changes/19049.compatibility.rst
  doc/source/release.rst
  doc/source/release/1.21.0-notes.rst
  doc/source/release/1.22.0-notes.rst
  numpy/core/code_generators/cversions.txt
  numpy/core/include/numpy/numpyconfig.h
  numpy/core/setup_common.py
  pavement.py
Labels: 14 - Release

#19072 BUG, TST: Fix test_numpy_version.
  numpy/tests/test_numpy_version.py
  numpy/version.py
Labels: 00 - Bug, 05 - Testing

#19071 BUG: Fix compile-time test of POPCNT
  numpy/distutils/checks/cpu_popcnt.c
Labels: 00 - Bug, 09 - Backport-Candidate, 36 - Build, component: SIMD, component: numpy.distutils

#19074 BUG: Fix compile-time test of POPCNT
  numpy/distutils/checks/cpu_popcnt.c
Labels: 00 - Bug, 08 - Backport, 36 - Build, component: SIMD, component: numpy.distutils

#19075 BUG: Fix test_numpy_version.
  numpy/tests/test_numpy_version.py
  numpy/version.py
Labels: 00 - Bug, 05 - Testing, 08 - Backport

#19073 REL: Prepare 1.21.0 release
  .mailmap
  doc/changelog/1.21.0-changelog.rst
  doc/release/upcoming_changes/15271.compatibility.rst
  doc/release/upcoming_changes/16987.improvement.rst
  doc/release/upcoming_changes/17492.deprecation.rst
  doc/release/upcoming_changes/17586.deprecation.rst
  doc/release/upcoming_changes/17727.performance.rst
  doc/release/upcoming_changes/17843.new_feature.rst
  doc/release/upcoming_changes/17900.expired.rst
  doc/release/upcoming_changes/17921.compatibility.rst
  doc/release/upcoming_changes/18070.improvement.rst
  doc/release/upcoming_changes/18110.change.rst
  doc/release/upcoming_changes/18116.future.rst
  doc/release/upcoming_changes/18322.new_feature.rst
  doc/release/upcoming_changes/18629.new_feature.rst
  doc/release/upcoming_changes/18657.performance.rst
  doc/release/upcoming_changes/18658.compatibility.rst
  doc/release/upcoming_changes/18666.improvement.rst
  doc/release/upcoming_changes/18695.new_feature.rst
  doc/release/upcoming_changes/18697.expired.rst
  doc/release/upcoming_changes/18718.c_api.rst
  doc/release/upcoming_changes/18718.compatibility.rst
  doc/release/upcoming_changes/18737.new_feature.rst
  doc/release/upcoming_changes/18874.change.rst
  doc/release/upcoming_changes/18880.compatibility.rst
  doc/release/upcoming_changes/18906.new_function.rst
  doc/release/upcoming_changes/18934.improvement.rst
  doc/release/upcoming_changes/18935.new_feature.rst
  doc/release/upcoming_changes/18963.expired.rst
  doc/release/upcoming_changes/19001.deprecation.rst
  doc/release/upcoming_changes/19031.deprecation.rst
  doc/release/upcoming_changes/19049.compatibility.rst
  doc/source/release/1.21.0-notes.rst
  numpy/core/code_generators/cversions.txt
  numpy/core/setup_common.py
Labels: 14 - Release

#19087 DOC: Add note to savez about naming variables with keyword `file`.
  numpy/lib/npyio.py
Labels: 04 - Documentation

#19089 DOC: Add example to histogram2d docstring
  numpy/lib/twodim_base.py
Labels: 04 - Documentation

#19094 BUG: Fixed an issue wherein `_GenericAlias.__getitem__` would raise for types with >1 parameters
  numpy/typing/_add_docstring.py
  numpy/typing/_generic_alias.py
  numpy/typing/tests/test_generic_alias.py
Labels: 00 - Bug, 08 - Backport, component: numpy.typing, static typing

#19092 BUG: Fixed an issue wherein `_GenericAlias.__getitem__` would raise for types with >1 parameters
  numpy/typing/_add_docstring.py
  numpy/typing/_generic_alias.py
  numpy/typing/tests/test_generic_alias.py
Labels: 00 - Bug, component: numpy.typing, static typing

#19090 MAINT: removed unused imports listed in LGTM
  numpy/core/defchararray.py
  numpy/core/records.py
  numpy/distutils/fcompiler/nv.py
  numpy/f2py/crackfortran.py
  numpy/lib/npyio.py
  numpy/ma/core.py
  numpy/ma/extras.py
  numpy/typing/_array_like.py
  numpy/typing/_callable.py
Labels: 03 - Maintenance

#19086 BUG: Linter should only run on pull requests.
  azure-pipelines.yml
Labels: 00 - Bug, 09 - Backport-Candidate, component: CI

#19100 BUG: Linter should only run on pull requests.
  azure-pipelines.yml
Labels: 00 - Bug, 08 - Backport, component: CI

#19096 BUG: Fix setup.py to work in maintenance branches.
  setup.py
Labels: 00 - Bug, 09 - Backport-Candidate, component: build

#19099 DOC: fixed unsigned integer alias links.
  doc/source/reference/arrays.scalars.rst
Labels: 04 - Documentation

#19110 DOC: Fix the documented default value of the `order` parameter of `np.asarray`
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation

#19120 BUG: Fix setup.py to work in maintenance branches.
  setup.py
Labels: 00 - Bug, 08 - Backport, component: build

#18759 BUG: revise string_from_pyobj/try_pyarr_from_string with respect to malloc and copy.
  numpy/f2py/cfuncs.py
  numpy/f2py/rules.py
  numpy/f2py/tests/src/array_from_pyobj/wrapmodule.c
  numpy/f2py/tests/test_return_character.py
  numpy/f2py/tests/test_string.py
Labels: 00 - Bug, component: numpy.f2py

#19118 MAINT: Misc cleaning of `numpy.typing`
  numpy/typing/__init__.py
  numpy/typing/_array_like.py
  numpy/typing/_callable.py
  numpy/typing/_char_codes.py
  numpy/typing/_dtype_like.py
  numpy/typing/_generic_alias.py
  numpy/typing/_shape.py
  numpy/typing/_ufunc.pyi
  numpy/typing/mypy_plugin.py
Labels: 03 - Maintenance, component: numpy.typing, static typing

#19098 BUG, SIMD: Fix detect host/native CPU features on ICC during compile-time
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/checks/cpu_avx.c
  numpy/distutils/checks/cpu_avx2.c
  numpy/distutils/checks/cpu_avx512_clx.c
  numpy/distutils/checks/cpu_avx512_cnl.c
  numpy/distutils/checks/cpu_avx512_icl.c
  numpy/distutils/checks/cpu_avx512_knl.c
  numpy/distutils/checks/cpu_avx512_knm.c
  numpy/distutils/checks/cpu_avx512_skx.c
  numpy/distutils/checks/cpu_avx512cd.c
  numpy/distutils/checks/cpu_avx512f.c
  numpy/distutils/checks/cpu_f16c.c
  numpy/distutils/checks/cpu_fma3.c
  numpy/distutils/checks/cpu_popcnt.c
  numpy/distutils/checks/cpu_sse.c
  numpy/distutils/checks/cpu_sse2.c
  numpy/distutils/checks/cpu_sse3.c
  numpy/distutils/checks/cpu_sse41.c
  numpy/distutils/checks/cpu_sse42.c
  numpy/distutils/checks/cpu_ssse3.c
Labels: 00 - Bug, 09 - Backport-Candidate, 36 - Build, component: SIMD, component: numpy.distutils

#19124 BUG: Fixed an issue wherein `poly1d.__getitem__` could return scalars of the wrong dtype
  numpy/lib/polynomial.py
  numpy/lib/tests/test_polynomial.py
Labels: 00 - Bug

#19119 BUG: Adjust shallow clone in the gitpod container
  tools/gitpod/gitpod.Dockerfile
Labels: 00 - Bug

#19062 ENH: Add a mypy plugin for inferring the precision of `np.ctypeslib.c_intp`
  doc/release/upcoming_changes/19062.new_feature.rst
  numpy/core/_internal.pyi
  numpy/ctypeslib.pyi
  numpy/typing/__init__.py
  numpy/typing/mypy_plugin.py
  numpy/typing/tests/data/reveal/ctypeslib.py
  numpy/typing/tests/data/reveal/ndarray_misc.py
  numpy/typing/tests/test_typing.py
Labels: 01 - Enhancement, static typing

#19132 BUG: Use larger fetch depth in gitpod.yml
  .github/workflows/gitpod.yml
Labels: 00 - Bug, 37 - Gitpod

#19130 ENH: SIMD architectures to show_config
  numpy/distutils/misc_util.py
Labels: 01 - Enhancement

#18964 DOC: replace np.ma functions' return types with `MaskedArray`
  numpy/ma/core.py
Labels: 04 - Documentation, component: numpy.ma

#19142 BUG: expose `short_version` as previously in version.py
  numpy/tests/test_numpy_version.py
  numpy/version.py
Labels: 00 - Bug

#19115 DOC: Misc fixes to `absolute_beginners.html`
  doc/source/user/absolute_beginners.rst
Labels: 04 - Documentation

#19144 BUG: expose short_version as previously in version.py
  numpy/tests/test_numpy_version.py
  numpy/version.py
Labels: 00 - Bug, 06 - Regression, 08 - Backport
