Repository numpy/numpy, pull requests merged in 2021-10, with the labels that each got.

#19981 DOC: Deindent some sphinx declarations to avoid warnings.
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#20004 DOC: Fix typos in the random and f2py documentation.
  numpy/f2py/crackfortran.py
  numpy/f2py/symbolic.py
  numpy/random/src/distributions/random_hypergeometric.c
Labels: 04 - Documentation

#20010 MAINT: correct linker flags for NAG Fortran compiler
  numpy/distutils/fcompiler/nag.py
Labels: component: numpy.distutils, 03 - Maintenance

#15847 BUG: avoid infinite recurrence on dependencies in crackfortran
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/test_crackfortran.py
Labels: 00 - Bug, component: numpy.f2py

#19899 DOC: replace return type in np.ma.* docstring
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
Labels: 04 - Documentation

#18984 DOC: add example showing how to convert POSIX timestamps to datetime64
  doc/source/reference/arrays.datetime.rst
Labels: 04 - Documentation

#20000 BUG,DEP: Allow (arg-)partition to accept `uint64` indices
  doc/release/upcoming_changes/20000.deprecation.rst
  numpy/core/_add_newdocs.py
  numpy/core/fromnumeric.py
  numpy/core/src/multiarray/item_selection.c
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug, 07 - Deprecation

#19731 BUG: fix time cast-safety for `factor*unit` e.g. in `10**6*ms == 1*s`
  numpy/core/src/multiarray/datetime.c
  numpy/core/tests/test_datetime.py
Labels: 00 - Bug, component: numpy.datetime64

#20019 MAINT:redundant 'else' statement with 'for' loop#19077
  numpy/typing/mypy_plugin.py
Labels: 03 - Maintenance

#20018 ENH: core: More informative error message for broadcast(*args)
  numpy/core/src/multiarray/iterators.c
  numpy/core/tests/test_numeric.py
Labels: 01 - Enhancement, component: numpy.core

#20006 ENH: Add annotations for `np.lib.function_base` part 1
  numpy/__init__.pyi
  numpy/core/function_base.pyi
  numpy/lib/function_base.pyi
  numpy/typing/tests/data/fail/lib_function_base.pyi
  numpy/typing/tests/data/fail/ndarray_misc.pyi
  numpy/typing/tests/data/reveal/lib_function_base.pyi
  numpy/typing/tests/data/reveal/ndarray_misc.pyi
Labels: 01 - Enhancement, static typing

#20027 ENH: Add missing parameters to the `nan<x>` functions
  doc/release/upcoming_changes/20027.improvement.rst
  numpy/core/fromnumeric.py
  numpy/lib/nanfunctions.py
  numpy/lib/nanfunctions.pyi
  numpy/lib/tests/test_nanfunctions.py
Labels: 01 - Enhancement, component: numpy.lib, 62 - Python API

#20034 ENH: Add annotations for `np.lib.function_base` part 2/3
  numpy/lib/function_base.pyi
  numpy/typing/tests/data/fail/lib_function_base.pyi
  numpy/typing/tests/data/reveal/lib_function_base.pyi
  numpy/typing/tests/test_typing.py
Labels: 01 - Enhancement, static typing

#20036 ENH: Add annotations for `np.lib.function_base` part 3/3
  numpy/lib/function_base.pyi
  numpy/typing/tests/data/fail/lib_function_base.pyi
  numpy/typing/tests/data/reveal/lib_function_base.pyi
Labels: 01 - Enhancement, static typing

#20040 TST: Add python 3.10 to the CI
  .github/workflows/build_test.yml
  setup.py
Labels: 05 - Testing

#18775 DOC: Ensure that we add documentation also as to the dict for types
  numpy/core/src/multiarray/compiled_base.c
Labels: 04 - Documentation, 09 - Backport-Candidate

#20051 DOC:add-html-reference-to-some-ma-methods
  doc/source/reference/routines.ma.rst
Labels: 04 - Documentation

#20235 DOC: fix typo in example, put the return statement inside the with context
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation

#20234 MAINT: Update vs2017 to vs2019.
  azure-pipelines.yml
Labels: 03 - Maintenance

#20230 ENH: Add annotations for `np.ctypeslib`
  numpy/ctypeslib.pyi
  numpy/typing/tests/data/reveal/ctypeslib.pyi
  numpy/typing/tests/test_typing.py
Labels: 01 - Enhancement, static typing

#20237 BUG: `VOID_nonzero` could sometimes mutate alignment flag
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/tests/test_numeric.py
Labels: 00 - Bug, 09 - Backport-Candidate

#20243 DOC: Fixes wording for fmod and remainder functions.
  numpy/core/code_generators/ufunc_docstrings.py
Labels: 04 - Documentation

#20242 DOC: centralized min-max documentation
  doc/source/reference/routines.math.rst
  doc/source/reference/routines.statistics.rst
Labels: 04 - Documentation

#20238 BUG: Fix environment checking logic for `NUMPY_WARN_IF_NO_MEM_POLICY`
  numpy/core/src/multiarray/arrayobject.c
  numpy/core/tests/test_mem_policy.py
Labels: 00 - Bug

#20139 MAINT,BUG: Fix `ufunc.at` to use new ufunc API
  numpy/core/src/multiarray/dtypemeta.h
  numpy/core/src/umath/dispatching.c
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_custom_dtypes.py
  numpy/core/tests/test_ufunc.py
Labels: 03 - Maintenance

#20255 DOC: fix missing link in "What is NumPy?" to broadcasting
  doc/source/user/whatisnumpy.rst
Labels: 04 - Documentation
