Repository numpy/numpy, pull requests merged in 2021-08, with the labels that each got.

#19578 TST: Add basic tests for custom DType (scaled float) ufuncs
  numpy/core/src/multiarray/array_method.c
  numpy/core/src/umath/_scaled_float_dtype.c
  numpy/core/src/umath/dispatching.c
  numpy/core/src/umath/dispatching.h
  numpy/core/tests/test_custom_dtypes.py
Labels: 05 - Testing

#19600 BUG: Fix bad write in masked iterator output copy paths
  numpy/core/src/multiarray/lowlevel_strided_loops.c.src
  numpy/core/tests/test_nditer.py
Labels: 00 - Bug, 09 - Backport-Candidate

#19605 DEV: Update default Python in benchmark config.
  benchmarks/asv.conf.json
  benchmarks/asv_compare.conf.json.tpl
Labels: 16 - Development

#19607 BUG: Fix NaT handling in the PyArray_CompareFunc for datetime and timedelta
  numpy/core/src/multiarray/arraytypes.c.src
Labels: 00 - Bug

#19561 DOC: Remove explicit parameter sparse=False in meshgrid() indexing example
  numpy/lib/function_base.py
Labels: 04 - Documentation

#19590 DOC Fix sphinx warnings related to scope of c:macro.
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/iterator.rst
Labels: 04 - Documentation

#19593 DOC,MAINT: Update wording surrounding `fname` parameter for loadtxt/genfromtxt
  numpy/lib/npyio.py
Labels: 04 - Documentation

#19485 TST/BENCH: Adding test coverage and benchmarks for floating point umath functions
  benchmarks/benchmarks/bench_ufunc_strides.py
  numpy/core/tests/data/generate_umath_validation_data.cpp
  numpy/core/tests/data/umath-validation-set-arccos.csv
  numpy/core/tests/data/umath-validation-set-arccosh.csv
  numpy/core/tests/data/umath-validation-set-arcsin.csv
  numpy/core/tests/data/umath-validation-set-arcsinh.csv
  numpy/core/tests/data/umath-validation-set-arctan.csv
  numpy/core/tests/data/umath-validation-set-arctanh.csv
  numpy/core/tests/data/umath-validation-set-cbrt.csv
  numpy/core/tests/data/umath-validation-set-cos.csv
  numpy/core/tests/data/umath-validation-set-cosh.csv
  numpy/core/tests/data/umath-validation-set-exp2.csv
  numpy/core/tests/data/umath-validation-set-expm1.csv
  numpy/core/tests/data/umath-validation-set-log10.csv
  numpy/core/tests/data/umath-validation-set-log1p.csv
  numpy/core/tests/data/umath-validation-set-log2.csv
  numpy/core/tests/data/umath-validation-set-sin.csv
  numpy/core/tests/data/umath-validation-set-sinh.csv
  numpy/core/tests/data/umath-validation-set-tan.csv
  numpy/core/tests/data/umath-validation-set-tanh.csv
  numpy/core/tests/test_umath.py
  numpy/core/tests/test_umath_accuracy.py
Labels: 05 - Testing

#19587 MAINT: Refactor DType slots into an opaque, allocated struct
  numpy/core/include/numpy/ndarraytypes.h
  numpy/core/src/multiarray/_multiarray_tests.c.src
  numpy/core/src/multiarray/abstractdtypes.c
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/src/multiarray/array_method.c
  numpy/core/src/multiarray/common.c
  numpy/core/src/multiarray/common_dtype.c
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/datetime.c
  numpy/core/src/multiarray/descriptor.c
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/src/multiarray/dtypemeta.h
  numpy/core/src/multiarray/usertypes.c
  numpy/core/src/umath/_scaled_float_dtype.c
  numpy/core/src/umath/dispatching.c
  numpy/core/src/umath/legacy_array_method.c
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_array_coercion.py
  numpy/core/tests/test_casting_unittests.py
Labels: 03 - Maintenance

#19598 PERF: Speed-up common case of loadtxt()ing non-hex floats.
  numpy/lib/npyio.py
  numpy/lib/tests/test_io.py
Labels: 01 - Enhancement, component: numpy.lib

#19616 MAINT: In loadtxt, refactor detection of the number of columns.
  numpy/lib/npyio.py
Labels: 03 - Maintenance

#19613 DOC: isclose accepts boolean input
  numpy/core/numeric.py
Labels: 04 - Documentation

#19619 MAINT: Include .coveragerc in source distributions to support runtests.py.
  MANIFEST.in
Labels: 03 - Maintenance

#19612 TST: Bump the python 3.10 test version from beta4 to rc1
  .github/workflows/build_test.yml
  numpy/core/numerictypes.pyi
  numpy/core/tests/test_umath_complex.py
  numpy/lib/tests/test_utils.py
Labels: 05 - Testing, 09 - Backport-Candidate

#19622 MAINT: Skip a type check in loadtxt when using user converters.
  numpy/lib/npyio.py
Labels: 03 - Maintenance

#19615 MAINT: Proposal to expire three deprecated functions in numpy.lib.npyio
  doc/release/upcoming_changes/19615.expired.rst
  numpy/__init__.pyi
  numpy/core/_add_newdocs.py
  numpy/lib/__init__.pyi
  numpy/lib/npyio.py
  numpy/lib/npyio.pyi
  numpy/lib/tests/test_io.py
  numpy/tests/test_public_api.py
Labels: 03 - Maintenance

#19580 ENH: Add basic promoter capability to ufunc dispatching
  numpy/core/src/umath/_scaled_float_dtype.c
  numpy/core/src/umath/dispatching.c
  numpy/core/src/umath/dispatching.h
  numpy/core/tests/test_custom_dtypes.py
Labels: 01 - Enhancement

#19539 DEP: Remove deprecated numeric style dtype strings
  doc/release/upcoming_changes/19539.expired.rst
  numpy/core/_type_aliases.py
  numpy/core/src/multiarray/descriptor.c
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_dtype.py
Labels: 00 - Bug, 07 - Deprecation

#19642 BLD, SIMD: Fix testing extra checks when `-Werror` isn't applicable for Clang
  numpy/distutils/ccompiler_opt.py
Labels: 09 - Backport-Candidate, component: SIMD, 36 - Build

#19639 MAINT: Update Cython version for Python 3.10.
  pyproject.toml
  tools/cythonize.py
Labels: 03 - Maintenance, 36 - Build

#19640 BUG: Remove logical object ufuncs with bool output
  numpy/core/code_generators/generate_umath.py
  numpy/core/tests/test_ufunc.py
Labels: 00 - Bug, 09 - Backport-Candidate

#19646 MAINT: Update Cython version for Python 3.10.
  pyproject.toml
  test_requirements.txt
  tools/cythonize.py
Labels: 03 - Maintenance, 08 - Backport

#19628 TST: avoid distutils.sysconfig in runtests.py
  runtests.py
Labels: 05 - Testing, 09 - Backport-Candidate

#19648 TST: Bump the python 3.10 test version from beta4 to rc1
  .github/workflows/build_test.yml
  numpy/core/tests/test_umath_complex.py
  numpy/lib/tests/test_utils.py
Labels: 05 - Testing, 08 - Backport

#19651 TST: avoid distutils.sysconfig in runtests.py
  runtests.py
Labels: 05 - Testing, 08 - Backport

#19652 MAINT: add missing dunder method to nditer type hints
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/nditer.py
Labels: 03 - Maintenance, 08 - Backport, static typing

#19645 DOC: Reorganized the documentation contribution docs
  doc/source/_templates/indexcontent.html
  doc/source/conf.py
  doc/source/dev/howto-docs.rst
  doc/source/dev/howto_build_docs.rst
  doc/source/dev/index.rst
  doc/source/doc_conventions.rst
  doc/source/docs/howto_document.rst
  doc/source/docs/index.rst
  doc/source/user/absolute_beginners.rst
  doc/source/user/index.rst
Labels: 04 - Documentation

#19654 BUG: add base to templated arguments for platlib
  runtests.py
Labels: 00 - Bug

#19527 BLD: Add LoongArch support
  doc/release/upcoming_changes/19527.new_feature.rst
  numpy/core/include/numpy/npy_cpu.h
  numpy/core/include/numpy/npy_endian.h
Labels: 56 - Needs Release Note., 36 - Build

#19656 BLD, SIMD: Fix testing extra checks when `-Werror` isn't applicable for Clang
  numpy/distutils/ccompiler_opt.py
Labels: 08 - Backport, component: SIMD, 36 - Build

#19657 BUG: Remove logical object ufuncs with bool output
  numpy/core/code_generators/generate_umath.py
  numpy/core/tests/test_ufunc.py
Labels: 00 - Bug, 08 - Backport

#19658 MAINT: Include .coveragerc in source distributions to support runtests.py.
  MANIFEST.in
Labels: 03 - Maintenance, 08 - Backport

#19659 BUG: Fix bad write in masked iterator output copy paths
  numpy/core/src/multiarray/lowlevel_strided_loops.c.src
  numpy/core/tests/test_nditer.py
Labels: 00 - Bug, 08 - Backport

#19660 ENH: Add support for windows on arm targets
  doc/release/upcoming_changes/19513.new_feature.rst
  numpy/core/include/numpy/npy_cpu.h
  numpy/core/tests/test_scalarprint.py
  numpy/random/src/philox/philox.h
Labels: 01 - Enhancement, 08 - Backport

#19632 BUG,DEP: Non-default UFunc signature/dtype usage should be deprecated
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_ufunc.py
Labels: 00 - Bug, 09 - Backport-Candidate

#19244 BUG: Fix an issue wherein assigment to `np.ma.masked_array` ignores mask in index
  numpy/ma/core.py
  numpy/ma/tests/test_old_ma.py
Labels: 00 - Bug, component: numpy.ma

#19582 BLD: loaded extra flags when checking for libflame
  numpy/distutils/system_info.py
Labels: 09 - Backport-Candidate, 36 - Build

#19666 MAINT: Add Python 3.10 to supported versions.
  setup.py
Labels: 03 - Maintenance

#19668 TST,BUG: Sanitize path-separators when running `runtest.py`
  runtests.py
Labels: 00 - Bug, 05 - Testing, 08 - Backport

#19661 BUG: add base to templated arguments for platlib
  runtests.py
Labels: 00 - Bug, 08 - Backport

#19662 BUG,DEP: Non-default UFunc signature/dtype usage should be deprecated
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_ufunc.py
Labels: 00 - Bug, 07 - Deprecation, 08 - Backport

#19671 BLD: load extra flags when checking for libflame
  numpy/distutils/system_info.py
Labels: 08 - Backport, 36 - Build

#19672 BLD: update circleCI docker image
  .circleci/config.yml
Labels: 09 - Backport-Candidate, 36 - Build

#19676 BLD: update circleCI docker image
  .circleci/config.yml
Labels: 36 - Build

#19667 ENH: Add annotations for `np.lib.npyio`
  numpy/lib/npyio.pyi
  numpy/typing/tests/data/fail/modules.py
  numpy/typing/tests/data/fail/npyio.py
  numpy/typing/tests/data/reveal/npyio.py
  runtests.py
Labels: 01 - Enhancement, static typing

#19678 REL: Update main after 1.21.2 release.
  doc/changelog/1.21.2-changelog.rst
  doc/source/release.rst
  doc/source/release/1.21.2-notes.rst
Labels: 14 - Release

#19683 ENH: Add annotations for `np.lib.stride_tricks`
  numpy/lib/stride_tricks.pyi
  numpy/typing/tests/data/fail/stride_tricks.py
  numpy/typing/tests/data/reveal/stride_tricks.py
Labels: 01 - Enhancement, static typing

#19680 ENH: Allow `np.fromregex` to accept `os.PathLike` implementations
  doc/release/upcoming_changes/19680.improvement.rst
  numpy/lib/npyio.py
  numpy/lib/npyio.pyi
  numpy/lib/tests/test_io.py
  numpy/typing/tests/data/fail/npyio.py
  numpy/typing/tests/data/reveal/npyio.py
Labels: 01 - Enhancement

#19627 BUG: Ignore whitespaces while parsing gufunc signatures
  numpy/core/tests/test_ufunc.py
  numpy/lib/function_base.py
  numpy/lib/tests/test_function_base.py
Labels: 00 - Bug

#19692 DOC: Fix trivial doc typo.
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#19695 DOC: Fix typo in `unwrap` docstring.
  numpy/lib/function_base.py
Labels: 04 - Documentation

#19702 MAINT: Replace deprecated unittest aliases
  tools/swig/test/testFarray.py
Labels: 03 - Maintenance

#19665 MAINT: Drop Python3.7 from supported versions.
  .github/workflows/build_test.yml
  azure-pipelines.yml
  doc/release/upcoming_changes/19655.change.rst
  numpy/__init__.py
  numpy/core/src/multiarray/alloc.c
  numpy/tests/test_public_api.py
  setup.py
Labels: 03 - Maintenance

#19698 DOC: fix typo in example
  doc/source/user/basics.creation.rst
Labels: 04 - Documentation

#19714 MAINT: Remove redundant Python2 float/int conversions
  numpy/core/tests/test_datetime.py
  numpy/core/tests/test_numeric.py
  numpy/fft/tests/test_pocketfft.py
  numpy/random/tests/test_generator_mt19937_regressions.py
  numpy/random/tests/test_randomstate_regression.py
  numpy/random/tests/test_regression.py
Labels: 03 - Maintenance

#19727 DOC: fix basics.creation.rst to address issue 19726
  doc/source/user/basics.creation.rst
Labels: 04 - Documentation

#19693 MAINT: In loadtxt, inline read_data.
  numpy/lib/npyio.py
Labels: 03 - Maintenance

#19732 MAINT: Spelling fixes in documentation
  numpy/core/src/common/npy_cpu_dispatch.h
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/tests/test_simd.py
Labels: 03 - Maintenance

#18585 ENH: Implementation of the NEP 47 (adopting the array API standard)
  doc/release/upcoming_changes/18585.new_feature.rst
  numpy/_pytesttester.py
  numpy/array_api/__init__.py
  numpy/array_api/_array_object.py
  numpy/array_api/_constants.py
  numpy/array_api/_creation_functions.py
  numpy/array_api/_data_type_functions.py
  numpy/array_api/_dtypes.py
  numpy/array_api/_elementwise_functions.py
  numpy/array_api/_linear_algebra_functions.py
  numpy/array_api/_manipulation_functions.py
  numpy/array_api/_searching_functions.py
  numpy/array_api/_set_functions.py
  numpy/array_api/_sorting_functions.py
  numpy/array_api/_statistical_functions.py
  numpy/array_api/_typing.py
  numpy/array_api/_utility_functions.py
  numpy/array_api/setup.py
  numpy/array_api/tests/__init__.py
  numpy/array_api/tests/test_array_object.py
  numpy/array_api/tests/test_creation_functions.py
  numpy/array_api/tests/test_elementwise_functions.py
  numpy/setup.py
  numpy/tests/test_public_api.py
Labels: 01 - Enhancement, component: NEP, 30 - API

#19742 MAINT: Remove redundant test.
  azure-pipelines.yml
Labels: 03 - Maintenance, component: CI

#19743 MAINT: Avoid use of confusing compat aliases.
  numpy/lib/npyio.py
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
Labels: 03 - Maintenance

#19745 ENH: Add dtype-support to 3 `generic`/`ndarray` methods
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/ndarray_conversion.py
  numpy/typing/tests/data/reveal/scalars.py
Labels: 01 - Enhancement, 08 - Backport, static typing

#19733 DOC: add citation file for GitHub support
  CITATION.bib
Labels: 04 - Documentation

#19730 BUG: Fix reference leak of capi_tmp in f2py/cb_rules.py
  numpy/f2py/cb_rules.py
Labels: 00 - Bug, component: numpy.f2py

#19736 BUG: Fix passing a MaskedArray instance to ``MaskedArray.__setitem__``
  numpy/ma/core.py
  numpy/ma/tests/test_old_ma.py
Labels: 00 - Bug

#19715 BUG: Casting bool_ to float16
  numpy/core/src/multiarray/lowlevel_strided_loops.c.src
  numpy/core/tests/test_casting_unittests.py
Labels: 00 - Bug

#19407 DOC: Rearranged parts of the Indexing docs to consolidate content
  doc/source/reference/arrays.indexing.rst
  doc/source/reference/routines.indexing.rst
  doc/source/reference/routines.rst
  doc/source/user/basics.indexing.rst
Labels: 04 - Documentation

#19784 MAINT: Remove typing code-paths specific to Python 3.7
  environment.yml
  numpy/__init__.pyi
  numpy/_pytesttester.pyi
  numpy/core/_asarray.pyi
  numpy/core/_type_aliases.pyi
  numpy/core/_ufunc_config.pyi
  numpy/core/arrayprint.pyi
  numpy/core/einsumfunc.pyi
  numpy/core/fromnumeric.pyi
  numpy/core/function_base.pyi
  numpy/core/multiarray.pyi
  numpy/core/numeric.pyi
  numpy/core/numerictypes.pyi
  numpy/core/shape_base.pyi
  numpy/f2py/__init__.pyi
  numpy/lib/arraypad.pyi
  numpy/lib/arrayterator.pyi
  numpy/lib/format.pyi
  numpy/lib/index_tricks.pyi
  numpy/lib/npyio.pyi
  numpy/lib/shape_base.pyi
  numpy/lib/stride_tricks.pyi
  numpy/lib/type_check.pyi
  numpy/lib/utils.pyi
  numpy/random/_generator.pyi
  numpy/random/_mt19937.pyi
  numpy/random/_pcg64.pyi
  numpy/random/_philox.pyi
  numpy/random/_sfc64.pyi
  numpy/random/bit_generator.pyi
  numpy/random/mtrand.pyi
  numpy/testing/_private/utils.pyi
  numpy/typing/__init__.py
  numpy/typing/_array_like.py
  numpy/typing/_callable.py
  numpy/typing/_char_codes.py
  numpy/typing/_dtype_like.py
  numpy/typing/_shape.py
  numpy/typing/_ufunc.pyi
  numpy/typing/tests/data/reveal/arraypad.py
  numpy/typing/tests/test_runtime.py
  numpy/typing/tests/test_typing_extensions.py
  test_requirements.txt
Labels: 03 - Maintenance, static typing

#19799 TST: Drop typing-extensions from test_requirements.txt
  test_requirements.txt
Labels: 05 - Testing, static typing

#19802 STY: Use the new PEP 457 positional-only syntax for typing
  numpy/__init__.pyi
  numpy/core/_ufunc_config.pyi
  numpy/core/einsumfunc.pyi
  numpy/core/multiarray.pyi
  numpy/core/shape_base.pyi
  numpy/lib/arraypad.pyi
  numpy/lib/npyio.pyi
  numpy/lib/shape_base.pyi
  numpy/lib/utils.pyi
  numpy/testing/_private/utils.pyi
  numpy/typing/_callable.py
  numpy/typing/_ufunc.pyi
Labels: 03 - Maintenance, static typing
