Repository numpy/numpy, pull requests merged in 2021-04, with the labels that each got.

#18706 DOC: Add release notes to upcoming_changes
  doc/release/upcoming_changes/18629.new_feature.rst
  doc/release/upcoming_changes/18695.new_feature.rst
Labels: 04 - Documentation, component: Documentation

#18712 DOC: Simplifies Mandelbrot set plot in Quickstart guide
  doc/source/user/quickstart.rst
Labels: 04 - Documentation

#18722 DOC: deduplicate dtype basic types (2)
  doc/source/reference/arrays.scalars.rst
  doc/source/user/basics.types.rst
Labels: 04 - Documentation

#18708 TST: add tests for using np.meshgrid for higher dimensional grids.
  numpy/lib/tests/test_function_base.py
Labels: 05 - Testing

#18075 ENH, SIMD: Dispatch for unsigned floor division
  .gitignore
  benchmarks/benchmarks/bench_ufunc.py
  numpy/core/code_generators/generate_umath.py
  numpy/core/setup.py
  numpy/core/src/umath/loops.c.src
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/loops_arithmetic.dispatch.c.src
  numpy/core/tests/test_umath.py
Labels: 01 - Enhancement, 25 - WIP, component: SIMD

#18731 BUG: Check out requirements and raise when not satisfied
  numpy/random/_common.pyx
  numpy/random/tests/test_generator_mt19937.py
Labels: 00 - Bug

#18741 DOC: Emphasize distinctions between np.copy and ndarray.copy
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation

#18733 DEV: Adds gitpod to numpy
  .gitpod.yml
  environment.yml
  tools/gitpod/Dockerfile
Labels: 16 - Development, 37 - Gitpod

#18737 BLD: introduce use of BLAS_LIBS and LAPACK_LIBS in distutils/system_info
  doc/release/upcoming_changes/18737.new_feature.rst
  doc/source/user/building.rst
  numpy/distutils/system_info.py
Labels: 36 - Build, component: numpy.distutils

#18750 MAINT: Allow more recursion depth for scalar tests.
  numpy/core/tests/test_scalarmath.py
Labels: 03 - Maintenance, component: numpy.core

#18753 BLD: Negative zero handling with ifort
  numpy/distutils/fcompiler/intel.py
Labels: 36 - Build

#18751 BUG: Regression #18075 | Fixing Ufunc TD generation order
  numpy/core/code_generators/generate_umath.py
  numpy/core/tests/test_regression.py
Labels: 00 - Bug

#18739 MAINT: Add exception chaining where appropriate
  numpy/core/code_generators/genapi.py
Labels: 03 - Maintenance

#18758 DOC: Update howto-docs with link to NumPy tutorials.
  doc/source/dev/howto-docs.rst
Labels: 04 - Documentation

#18728 MAINT: Add exception chaining where appropriate
  benchmarks/benchmarks/bench_linalg.py
  benchmarks/benchmarks/bench_ufunc_strides.py
  numpy/random/_common.pyx
  tools/cythonize.py
Labels: 03 - Maintenance

#18718 API, DEP: Move ufunc signature parsing to the start
  doc/neps/nep-0043-extensible-ufuncs.rst
  doc/release/upcoming_changes/18718.c_api.rst
  doc/release/upcoming_changes/18718.compatibility.rst
  numpy/core/src/umath/ufunc_object.c
  numpy/core/src/umath/ufunc_type_resolution.c
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_ufunc.py
  numpy/typing/tests/data/pass/ufuncs.py
Labels: 07 - Deprecation, 30 - API, 62 - Python API

#18764 MAINT: Remove `__all__` in favor of explicit re-exports
  numpy/__init__.pyi
Labels: 03 - Maintenance, 08 - Backport, static typing

#18763 BUG: Correct `datetime64` missing type overload for `datetime.date` #18640
  numpy/__init__.pyi
  numpy/typing/tests/data/pass/scalars.py
Labels: 00 - Bug, 08 - Backport, static typing

#18765 ENH: Improve the placeholder annotations for the main numpy namespace
  numpy/__init__.pyi
  tools/functions_missing_types.py
Labels: 01 - Enhancement, static typing

#18768 BLD: Strip extra newline when dumping gfortran version on MacOS
  numpy/distutils/fcompiler/gnu.py
Labels: 08 - Backport, 36 - Build, component: build

#18769 BUG: fix segfault in object/longdouble operations
  numpy/core/src/umath/scalarmath.c.src
  numpy/core/tests/test_scalarmath.py
Labels: 00 - Bug, 08 - Backport, component: numpy.core

#18771 DOC: Use: from numpy.testing import ...
  numpy/testing/_private/utils.py
Labels: 04 - Documentation

#18770 DOC: More concise "How to import NumPy" description
  doc/source/user/absolute_beginners.rst
Labels: 04 - Documentation

#18772 CI: Use informational mode for codecov
  .codecov.yml
Labels: 25 - WIP

#18778 MAINT: Relax the integer-type-constraint of `npt._ShapeLike`
  numpy/__init__.pyi
  numpy/typing/_shape.py
  numpy/typing/tests/data/pass/array_constructors.py
Labels: 03 - Maintenance, 09 - Backport-Candidate, static typing

#18779 DOC: fix spelling of "reccomended" ("recommended")
  numpy/random/_generator.pyx
Labels: 04 - Documentation

#18785 DOC: change `dec.parametrize` to `pytest.mark.parametrize`
  doc/TESTS.rst.txt
Labels: 04 - Documentation

#18787 DOC: Document newer pytest conventions
  doc/TESTS.rst.txt
  doc/source/conf.py
Labels: 04 - Documentation

#18780 ENH: Improve the placeholder annotations for the main numpy namespace (part 2)
  numpy/__init__.pyi
Labels: 01 - Enhancement, static typing

#18781 ENH: Add `__all__` to a number of public modules
  numpy/fft/__init__.py
  numpy/fft/__init__.pyi
  numpy/linalg/__init__.py
  numpy/linalg/__init__.pyi
  numpy/polynomial/__init__.py
  numpy/polynomial/__init__.pyi
Labels: 01 - Enhancement

#18789 DEV: Pin pydata-sphinx-theme to 0.5.2.
  environment.yml
Labels: 16 - Development

#18792 MAINT: Use recent towncrier releases on PyPI.
  .circleci/config.yml
  doc/HOWTO_RELEASE.rst.txt
  release_requirements.txt
Labels: 03 - Maintenance, component: CI, component: Documentation

#18794 MAINT: Use towncrier build explicitly
  .circleci/config.yml
  doc/HOWTO_RELEASE.rst.txt
  doc/release/upcoming_changes/README.rst
  release_requirements.txt
  tools/ci/test_all_newsfragments_used.py
Labels: 03 - Maintenance, 08 - Backport, component: CI, component: Documentation

#18791 DOC: Fixes small things in the genfromtext docstring
  numpy/lib/npyio.py
Labels: 04 - Documentation

#18795 SIMD, TEST: Workaround for misaligned stack GCC BUG ABI on WIN64
  numpy/core/src/_simd/_simd_vector.inc
Labels: 00 - Bug, 05 - Testing, component: SIMD

#18796 DOC: Misc Numpydoc and formatting for proper parsing.
  numpy/core/_add_newdocs.py
  numpy/lib/utils.py
Labels: 04 - Documentation

#18761 DOC: Small fixes (including formatting) for NEP 43
  doc/neps/nep-0043-extensible-ufuncs.rst
Labels: 04 - Documentation

#18801 DOC: fix typo in frexp docstring
  numpy/core/code_generators/ufunc_docstrings.py
Labels: 04 - Documentation

#18802 DOC: Improve random.choice() documentation
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
Labels: 04 - Documentation

#18799 MAINT: Improve the placeholder annotations for the main numpy namespace (part 3)
  numpy/__init__.pyi
Labels: 03 - Maintenance, static typing

#18800 MAINT: Relax miscellaneous integer-type constraints
  numpy/__init__.pyi
Labels: 03 - Maintenance, 09 - Backport-Candidate, static typing

#18809 MAINT: runtests help text cleanup
  runtests.py
Labels: 03 - Maintenance

#18812 DOC: Document howto build documentation in a virtual environment
  doc/source/docs/howto_build_docs.rst
Labels: 04 - Documentation

#18813 BUG: Initialize the full nditer buffer in case of error
  numpy/core/src/multiarray/nditer_api.c
  numpy/core/src/multiarray/nditer_constr.c
  numpy/core/tests/test_nditer.py
Labels: 00 - Bug, 09 - Backport-Candidate

#18777 DOC: update random and asserts in test guidelines
  doc/TESTS.rst.txt
  doc/source/reference/routines.testing.rst
Labels: 04 - Documentation

#18820 MAINT: Remove incorrect inline
  numpy/core/src/multiarray/array_coercion.c
Labels: 03 - Maintenance

#18797 DOC: Update random c-api documentation
  doc/source/reference/random/c-api.rst
Labels: 04 - Documentation, component: numpy.random

#18818 ENH: Add annotations for 4 objects in `np.core.numerictypes`
  numpy/__init__.pyi
  numpy/core/numerictypes.py
  numpy/core/numerictypes.pyi
  numpy/typing/tests/data/pass/numerictypes.py
  numpy/typing/tests/data/reveal/numerictypes.py
Labels: 01 - Enhancement, static typing

#18823 MAINT: Minor fix to add reference link to numpy.fill_diagonal function
  doc/source/user/tutorial-svd.rst
Labels: 03 - Maintenance, 04 - Documentation, component: Documentation

#18825 MAINT: Update README.md
  README.md
Labels: 03 - Maintenance

#18786 DOC: add note for clip() special case a_min > a_max See #18782
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#18831 BUG: Prevent nan being used in percentile
  numpy/lib/function_base.py
  numpy/lib/tests/test_function_base.py
Labels: 00 - Bug

#17737 MAINT, Benchmark: print the supported CPU features during the run of performance tests
  benchmarks/benchmarks/__init__.py
  numpy/_pytesttester.py
  numpy/lib/utils.py
Labels: 03 - Maintenance

#18841 DOC: Add favicon
  doc/source/_static/favicon/apple-touch-icon.png
  doc/source/_static/favicon/favicon-16x16.png
  doc/source/_static/favicon/favicon-32x32.png
  doc/source/_static/favicon/favicon.ico
  doc/source/conf.py
Labels: 04 - Documentation

#18842 ENH: Improve the placeholder annotations within sub-modules
  numpy/__init__.pyi
  numpy/char.pyi
  numpy/ctypeslib.pyi
  numpy/emath.pyi
  numpy/f2py/__init__.pyi
  numpy/fft/__init__.pyi
  numpy/matrixlib/__init__.pyi
  numpy/rec.pyi
  numpy/testing/__init__.pyi
Labels: 01 - Enhancement, static typing

#18837 ENH, SIMD: Add support for dispatching C++ sources
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/command/build_clib.py
  numpy/distutils/command/build_ext.py
Labels: 01 - Enhancement, component: SIMD

#18845 DOC: Move Sphinx numpy target in reference index.
  doc/source/reference/index.rst
Labels: 04 - Documentation, component: Documentation

#18851 MAINT: Disable pip version check for azure lint check.
  azure-pipelines.yml
Labels: 03 - Maintenance, component: CI

#18822 DEV: general Gitpod enhancements
  .github/workflows/docker.yml
  .github/workflows/gitpod.yml
  .gitpod.yml
  .hadolint.yaml
  environment.yml
  tools/gitpod/Dockerfile
  tools/gitpod/gitpod.Dockerfile
  tools/gitpod/settings.json
  tools/gitpod/workspace_config
Labels: 16 - Development, 37 - Gitpod

#18839 DOC: Add Gitpod development documentation
  doc/source/dev/development_gitpod.rst
  doc/source/dev/gitpod-imgs/NumPy-github.png
  doc/source/dev/gitpod-imgs/NumPy-gitpod-branches.png
  doc/source/dev/gitpod-imgs/gitpod-edit-permissions-gh.png
  doc/source/dev/gitpod-imgs/gitpod-workspace.png
  doc/source/dev/gitpod-imgs/installing-gitpod-io.png
  doc/source/dev/gitpod-imgs/rst-rendering.png
  doc/source/dev/gitpod-imgs/vscode-rst.png
  doc/source/dev/gitpod-imgs/vscode-statusbar.png
  doc/source/dev/index.rst
Labels: 04 - Documentation, 37 - Gitpod

#18856 MAINT: Fix the typo "implment"
  numpy/core/src/common/simd/avx2/arithmetic.h
  numpy/core/src/common/simd/avx512/arithmetic.h
  numpy/core/src/common/simd/sse/arithmetic.h
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/convert_datatype.h
Labels: 03 - Maintenance

#18862 TST: Skip f2py TestSharedMemory for LONGDOUBLE on macos/arm64
  numpy/f2py/tests/test_array_from_pyobj.py
Labels: 05 - Testing

#18869 MAINT: Fix azure linter problems with pip 21.1
  azure-pipelines.yml
Labels: 03 - Maintenance, component: CI

#18855 STY: change CRLF line terminators to Unix
  .github/PULL_REQUEST_TEMPLATE.md
  doc/release/upcoming_changes/17727.performance.rst
  doc/source/_static/numpylogo.svg
  doc/source/user/how-to-how-to.rst
  doc/source/user/how-to-io.rst
  doc/source/user/install.rst
  doc/source/user/who_covid_19_sit_rep_time_series.csv
  numpy/core/src/common/npy_cpuinfo_parser.h
Labels: 03 - Maintenance

#18853 ENH: Improve the placeholder annotations within sub-modules (part 2)
  numpy/__init__.pyi
  numpy/core/__init__.pyi
  numpy/lib/__init__.pyi
  numpy/lib/_version.pyi
  numpy/lib/arraypad.pyi
  numpy/lib/arraysetops.pyi
  numpy/lib/format.pyi
  numpy/lib/function_base.pyi
  numpy/lib/histograms.pyi
  numpy/lib/mixins.pyi
  numpy/lib/nanfunctions.pyi
  numpy/lib/npyio.pyi
  numpy/lib/polynomial.pyi
  numpy/lib/scimath.pyi
  numpy/lib/shape_base.pyi
  numpy/lib/stride_tricks.pyi
  numpy/lib/twodim_base.pyi
  numpy/lib/type_check.pyi
  numpy/lib/utils.pyi
  numpy/linalg/__init__.pyi
  numpy/typing/tests/test_isfile.py
Labels: 01 - Enhancement, static typing

#18877 MAINT: Update PyPy version used by CI
  .github/workflows/build_test.yml
Labels: 03 - Maintenance, component: CI
