Repository numpy/numpy, pull requests merged in 2021-07, with the labels that each got.

#19381 MAINT: Modify initialization order during multiarray import
  numpy/core/src/multiarray/multiarraymodule.c
Labels: 03 - Maintenance

#19058 BUG: Fixes to getter signatures
  numpy/core/src/_simd/_simd_vector.inc
  numpy/core/src/multiarray/datetime_busdaycal.c
  numpy/core/src/multiarray/descriptor.c
  numpy/core/src/multiarray/descriptor.h
  numpy/core/src/multiarray/flagsobject.c
  numpy/core/src/multiarray/getset.c
  numpy/core/src/multiarray/iterators.c
  numpy/core/src/multiarray/nditer_pywrap.c
  numpy/core/src/multiarray/scalartypes.c.src
  numpy/core/src/umath/ufunc_object.c
Labels: 00 - Bug

#19371 MAINT: Use cast-is-view flag for the ufunc trivial-loop check
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/umath/ufunc_object.c
Labels: 03 - Maintenance

#19392 BUG: Fix NULL special case in object-to-any cast code
  numpy/core/src/multiarray/dtype_transfer.c
  numpy/core/tests/test_casting_unittests.py
Labels: 00 - Bug, 08 - Backport

#19391 BUG: Do not raise deprecation warning for all nans in unique (#19301)
  numpy/lib/arraysetops.py
  numpy/lib/tests/test_arraysetops.py
Labels: 00 - Bug, 08 - Backport

#19390 ENH: SIMD architectures to show_config
  numpy/distutils/misc_util.py
Labels: 01 - Enhancement, 08 - Backport

#19402 DOC: typo fix
  numpy/lib/format.py
Labels: 04 - Documentation

#19394 BUG, SIMD: Fix infinite loop during count non-zero on GCC-11
  numpy/core/src/multiarray/item_selection.c
Labels: 00 - Bug, 09 - Backport-Candidate, component: SIMD

#19393 MAINT: fix overly broad exception handling listed in LGTM
  numpy/lib/utils.py
  numpy/linalg/lapack_lite/make_lite.py
Labels: 03 - Maintenance

#19409 BUG: fix some memory leaks in ufunc_object
  numpy/core/src/umath/ufunc_object.c
Labels: 00 - Bug

#19396 BUG: fix a numpy.npiter leak in npyiter_multi_index_set
  numpy/core/src/multiarray/nditer_pywrap.c
  numpy/core/tests/test_nditer.py
Labels: 00 - Bug, 09 - Backport-Candidate

#19356 API: Ensure np.vectorize outputs can be subclasses.
  doc/release/upcoming_changes/19356.change.rst
  numpy/lib/function_base.py
  numpy/lib/tests/test_function_base.py
Labels: 00 - Bug, 30 - API, component: numpy.lib

#18762 MAINT: Remove unused imports and unreachable code
  numpy/compat/py3k.py
  numpy/core/multiarray.py
  numpy/lib/format.py
  numpy/lib/index_tricks.py
  numpy/ma/extras.py
  numpy/ma/mrecords.py
  numpy/typing/_array_like.py
Labels: 03 - Maintenance

#19211 ENH: Adding keepdims to np.argmin,np.argmax
  doc/release/upcoming_changes/19211.new_feature.rst
  numpy/__init__.pyi
  numpy/core/fromnumeric.py
  numpy/core/fromnumeric.pyi
  numpy/core/src/multiarray/calculation.c
  numpy/core/src/multiarray/calculation.h
  numpy/core/src/multiarray/methods.c
  numpy/core/tests/test_multiarray.py
  numpy/ma/core.py
  numpy/ma/core.pyi
Labels: 01 - Enhancement, 62 - Python API, component: numpy.core

#19416 DOC: Remove duplicate information about governance
  doc/source/dev/governance/governance.rst
  doc/source/dev/governance/index.rst
  doc/source/dev/governance/people.rst
Labels: 04 - Documentation

#19426 MAINT: Use arm64-graviton2 for testing on travis
  .travis.yml
Labels: 03 - Maintenance, 09 - Backport-Candidate, component: CI

#19430 MAINT: Use arm64-graviton2 for testing on travis
  .travis.yml
Labels: 03 - Maintenance, 08 - Backport, component: CI

#19434 MAINT: Fix the module of `flagsobj`
  numpy/__init__.pyi
  numpy/core/multiarray.pyi
  numpy/core/src/multiarray/flagsobject.c
Labels: 03 - Maintenance

#19419 BUG: fix markinnerspace in f2py
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/test_crackfortran.py
Labels: 00 - Bug, component: numpy.f2py

#19436 ENH: Improve the annotations of `flagsobj`
  numpy/core/multiarray.pyi
Labels: 01 - Enhancement, static typing

#19431 MAINT: Delete old SSE2 `absolute` implementation
  numpy/core/src/umath/simd.inc.src
Labels: 03 - Maintenance

#19403 BUG: Fix memory leak in function npyiter_multi_index_set
  numpy/core/src/multiarray/number.c
Labels: 00 - Bug

#19442 MAINT: Use "with open(...)"
  numpy/_version.py
  versioneer.py
Labels: 03 - Maintenance

#19446 MAINT: Start testing with Python 3.10.0b3.
  .github/workflows/build_test.yml
Labels: 03 - Maintenance, component: CI

#19450 TST: Simplify property-based test
  numpy/core/tests/test_numeric.py
Labels: 05 - Testing

#19440 MAINT: factored out _PyArray_ArgMinMaxCommon
  numpy/core/src/multiarray/calculation.c
  numpy/core/tests/test_multiarray.py
Labels: 03 - Maintenance

#19451 BUG: Make openblas_support support ILP64 on Windows.
  tools/openblas_support.py
Labels: 00 - Bug

#19456 TST: Fix a `GenericAlias` test failure for python 3.9.0
  numpy/typing/tests/test_generic_alias.py
Labels: 05 - Testing, static typing

#19445 DOC: broadcast_to() supports int as shape parameter
  numpy/lib/stride_tricks.py
Labels: 04 - Documentation

#19458 MAINT: Avoid unicode characters in division SIMD code comments
  numpy/core/src/umath/loops_arithmetic.dispatch.c.src
Labels: 03 - Maintenance, 09 - Backport-Candidate

#19462 BUILD: move to OpenBLAS 0.3.16
  .travis.yml
  tools/openblas_support.py
Labels: 09 - Backport-Candidate

#19463 MAINT: Use straight arm64 in TravisCI.
  .travis.yml
Labels: 03 - Maintenance, component: CI

#19418 DOC: Removing tutorials from sphinx documentation
  doc/source/user/index.rst
  doc/source/user/quickstart.rst
  doc/source/user/tutorial-ma.rst
  doc/source/user/tutorial-svd.rst
  doc/source/user/tutorials_index.rst
  doc/source/user/who_covid_19_sit_rep_time_series.csv
Labels: 04 - Documentation

#19447 DOC: BLAS/LAPACK linking rules
  .gitignore
  numpy/distutils/misc_util.py
Labels: 04 - Documentation

#19475 DOC: Fix see also references in `numpy.resize`
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#19316 BUG: Fix warning problems of the mod operator
  numpy/core/src/npymath/npy_math_internal.h.src
  numpy/core/src/umath/scalarmath.c.src
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, Triage-review

#19404 NEP: update NEP with the PyDataMem_Handler struct as implemented in the PR
  doc/neps/nep-0049.rst
Labels: Triage-review

#19151 ENH: Vectorising np.linalg.qr
  doc/release/upcoming_changes/19151.improvement.rst
  numpy/linalg/linalg.py
  numpy/linalg/tests/test_linalg.py
  numpy/linalg/umath_linalg.c.src
Labels: 01 - Enhancement, component: numpy.linalg

#19491 MAINT: Disable test_blas64_dot.
  numpy/linalg/tests/test_linalg.py
Labels: 03 - Maintenance, 05 - Testing, component: numpy.linalg

#19483 MAINT: Update for using openblas64_.
  azure-pipelines.yml
  azure-steps-windows.yml
Labels: 03 - Maintenance, component: CI

#19486 DOC: Add link to NumPy PDF docs
  doc/source/_templates/indexcontent.html
Labels: 04 - Documentation

#19493 TST: generalise `clip` test
  numpy/core/tests/test_numeric.py
Labels: 05 - Testing

#19495 BUILD: update OpenBLAS to v0.3.17
  doc/release/upcoming_changes/19462.change.rst
  tools/openblas_support.py
Labels: 08 - Backport, 36 - Build

#19496 MAINT: Avoid unicode characters in division SIMD code comments
  numpy/core/src/umath/loops_arithmetic.dispatch.c.src
Labels: 03 - Maintenance, 08 - Backport

#19498 MAINT: Update manylinux ci test to manylinux2014
  azure-pipelines.yml
Labels: 03 - Maintenance, component: CI

#19499 BUG, SIMD: Fix infinite loop during count non-zero on GCC-11
  numpy/core/src/multiarray/item_selection.c
Labels: 00 - Bug, 08 - Backport, component: SIMD

#19500 BUG: fix a numpy.npiter leak in npyiter_multi_index_set
  numpy/core/src/multiarray/nditer_pywrap.c
  numpy/core/tests/test_nditer.py
Labels: 00 - Bug, 08 - Backport

#19501 TST: Fix a `GenericAlias` test failure for python 3.9.0
  numpy/typing/tests/test_generic_alias.py
Labels: 05 - Testing, 08 - Backport, static typing

#19502 MAINT: Start testing with Python 3.10.0b3.
  .github/workflows/build_test.yml
Labels: 03 - Maintenance, 08 - Backport, component: CI

#19468 MAINT: Add missing `dtype` overloads for object- and ctypes-based inputs
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/dtype.py
  numpy/typing/tests/data/reveal/dtype.py
Labels: 03 - Maintenance, 09 - Backport-Candidate, static typing

#19503 MAINT: Add missing dtype overloads for object- and ctypes-based inputs
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/dtype.py
  numpy/typing/tests/data/reveal/dtype.py
Labels: 03 - Maintenance, 08 - Backport, static typing

#19506 DOC: Fix typos
  doc/source/reference/c-api/coremath.rst
Labels: 04 - Documentation

#19369 DOC: Moved VQ example & target from duplicate array broadcasting doc
  doc/source/user/basics.broadcasting.rst
  doc/source/user/broadcasting_1.svg
  doc/source/user/broadcasting_2.svg
  doc/source/user/broadcasting_3.svg
  doc/source/user/broadcasting_4.svg
  doc/source/user/broadcasting_5.svg
  doc/source/user/theory.broadcast_1.gif
  doc/source/user/theory.broadcast_2.gif
  doc/source/user/theory.broadcast_3.gif
  doc/source/user/theory.broadcast_4.gif
  doc/source/user/theory.broadcast_5.png
  doc/source/user/theory.broadcasting.rst
Labels: 04 - Documentation

#19479 BLD: Add clang `-ftrapping-math` also for `compiler_so`
  doc/release/upcoming_changes/19479.compatibility.rst
  numpy/core/src/umath/loops_exponent_log.dispatch.c.src
  numpy/distutils/ccompiler.py
Labels: 36 - Build

#19497 MAINT: set Python version for 1.21.x to `<3.11`
  setup.py
Labels: 03 - Maintenance, 14 - Release

#19512 REL: Update main after 1.21.1 release.
  doc/changelog/1.21.1-changelog.rst
  doc/source/release.rst
  doc/source/release/1.21.1-notes.rst
Labels: 14 - Release, component: Documentation

#18536 ENH: Add smallest_normal and smallest_subnormal attributes to finfo
  doc/release/upcoming_changes/18536.improvement.rst
  numpy/core/getlimits.py
  numpy/core/machar.py
  numpy/core/tests/test_getlimits.py
  numpy/core/tests/test_longdouble.py
  numpy/core/tests/test_numeric.py
  numpy/core/tests/test_scalarmath.py
  numpy/core/tests/test_ufunc.py
  numpy/core/tests/test_umath.py
Labels: 01 - Enhancement, 62 - Python API

#19422 DOC: Additional ideas related to numpy-tutorials integration
  doc/source/_templates/indexcontent.html
  doc/source/conf.py
  doc/source/user/index.rst
  doc/source/user/quickstart.rst
Labels: 04 - Documentation

#19408 ENH: Add annotations for misc python-based functions
  numpy/__init__.pyi
  numpy/lib/__init__.pyi
Labels: 01 - Enhancement, static typing

#19421 ENH: Add annotations for `np.core.getlimits`
  numpy/__init__.pyi
  numpy/core/getlimits.pyi
  numpy/typing/tests/data/reveal/getlimits.py
Labels: 01 - Enhancement, static typing

#19444 ENH: Add annotations for `np.lib.shape_base`
  numpy/__init__.pyi
  numpy/core/_add_newdocs.py
  numpy/lib/shape_base.pyi
  numpy/typing/tests/data/reveal/ndarray_misc.py
  numpy/typing/tests/data/reveal/shape_base.py
Labels: 01 - Enhancement, static typing

#19526 MAINT: bump Sphinx in environment.yml file
  environment.yml
Labels: 03 - Maintenance

#19459 ENH: Add the `axis` and `ndim` attributes to `np.AxisError`
  doc/release/upcoming_changes/19459.new_feature.rst
  doc/source/reference/routines.other.rst
  numpy/__init__.pyi
  numpy/core/_exceptions.py
  numpy/core/tests/test__exceptions.py
  numpy/typing/tests/data/fail/warnings_and_errors.py
  numpy/typing/tests/data/pass/warnings_and_errors.py
  numpy/typing/tests/data/reveal/warnings_and_errors.py
Labels: 01 - Enhancement, 62 - Python API

#18330 TST: Add cygwin build to CI
  .github/workflows/cygwin.yml
  numpy/core/include/numpy/random/distributions.h
  numpy/core/src/common/npy_config.h
  numpy/core/tests/test_scalarmath.py
  tools/list_installed_dll_dependencies_cygwin.sh
Labels: 05 - Testing

#19525 TST: Test that `numpy.typing` can be imported in the absence of typing-extensions
  numpy/tests/test_reloading.py
  numpy/typing/tests/test_typing_extensions.py
Labels: 05 - Testing, static typing

#19538 DOC: Fix typo in PCG64
  numpy/random/_pcg64.pyx
Labels: 04 - Documentation

#19535 TST: Add Cygwin to the x86 feature tests.
  numpy/core/tests/test_cpu_features.py
Labels: 05 - Testing, component: SIMD

#19534 BLD: Tell fortran compiler Cygwin doesn't support rpath.
  numpy/distutils/fcompiler/gnu.py
Labels: 36 - Build

#19543 MAINT: Improve the `np.core.numerictypes` stubs
  numpy/core/numerictypes.pyi
  numpy/typing/tests/data/fail/numerictypes.py
  numpy/typing/tests/data/reveal/numerictypes.py
Labels: 03 - Maintenance, static typing

#19533 BUG: Fix an issue wherein importing `numpy.typing` could raise
  numpy/typing/_array_like.py
  numpy/typing/_dtype_like.py
  numpy/typing/tests/test_typing_extensions.py
Labels: 00 - Bug, 08 - Backport, component: numpy.typing, static typing

#19542 TST: Parametrize a few more tests.
  numpy/core/tests/test_numeric.py
  numpy/core/tests/test_umath.py
Labels: 05 - Testing

#19545 DOC: Add clarification
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation

#19546 DOC: Add link and explanation of `_add_newdocs` to developer guide
  doc/source/dev/howto-docs.rst
Labels: 04 - Documentation

#19547 BLD: Use cygpath utility for path conversion in cyg2win32
  numpy/distutils/misc_util.py
Labels: 36 - Build

#19557 DOC: clarify doc re: unsupported keys in savez.
  numpy/lib/npyio.py
Labels: 04 - Documentation

#19560 TST: Bump the GitHub actions python 3.10 version
  .github/workflows/build_test.yml
Labels: 05 - Testing

#19559 ENH: Add annotations for `__path__` and `PytestTester`
  numpy/__init__.pyi
  numpy/_pytesttester.pyi
  numpy/f2py/__init__.pyi
  numpy/fft/__init__.pyi
  numpy/lib/__init__.pyi
  numpy/linalg/__init__.pyi
  numpy/ma/__init__.pyi
  numpy/matrixlib/__init__.pyi
  numpy/polynomial/__init__.pyi
  numpy/random/__init__.pyi
  numpy/testing/__init__.pyi
  numpy/typing/__init__.py
  numpy/typing/tests/data/reveal/modules.py
Labels: 01 - Enhancement, static typing

#19567 DOC: Fix Unknown section warning when building docs
  numpy/distutils/misc_util.py
Labels: 04 - Documentation

#19566 DOC: Remove `dot` docstring in numpy/core/_add_newdocs.py
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation

#19554 MAINT: add missing dunder method to nditer type hints
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/nditer.py
Labels: 03 - Maintenance, 09 - Backport-Candidate, static typing

#19540 MAINT: Update the `np.finfo` annotations
  numpy/__init__.pyi
  numpy/core/getlimits.pyi
  numpy/typing/tests/data/reveal/getlimits.py
Labels: 03 - Maintenance, static typing

#19568 BUG: Seed random state in test_vonmises_large_kappa_range.
  numpy/random/tests/test_generator_mt19937.py
Labels: 00 - Bug, 05 - Testing, component: numpy.random

#19565 DOC: Fix sphinx warnings in c-info.beyond-basics.rst
  doc/source/reference/c-api/array.rst
  doc/source/user/c-info.beyond-basics.rst
  numpy/core/include/numpy/ndarraytypes.h
Labels: 04 - Documentation

#19564 TST: Add "Scaled float" custom DType for testng
  numpy/core/arrayprint.py
  numpy/core/setup.py
  numpy/core/src/common/umathmodule.h
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/umath/_scaled_float_dtype.c
  numpy/core/tests/test_custom_dtypes.py
Labels: 05 - Testing

#19513 ENH: Add support for windows on arm targets
  doc/release/upcoming_changes/19513.new_feature.rst
  numpy/core/include/numpy/npy_cpu.h
  numpy/core/tests/test_scalarprint.py
  numpy/random/src/philox/philox.h
Labels: 01 - Enhancement, 09 - Backport-Candidate, 56 - Needs Release Note.

#19572 MAINT: Cleanup unused function _move_axis_to_0
  numpy/core/numeric.py
Labels: 03 - Maintenance

#19576 MAINT: Make Python3.8 the default for CI testing.
  .github/workflows/build_test.yml
  .github/workflows/cygwin.yml
  .travis.yml
  azure-pipelines.yml
Labels: 03 - Maintenance

#19571 MAINT: Refactor UFunc core to use NEP 43 style dispatching
  doc/source/reference/c-api/types-and-structures.rst
  numpy/core/include/numpy/ufuncobject.h
  numpy/core/setup.py
  numpy/core/src/multiarray/array_method.c
  numpy/core/src/multiarray/array_method.h
  numpy/core/src/multiarray/nditer_constr.c
  numpy/core/src/umath/dispatching.c
  numpy/core/src/umath/dispatching.h
  numpy/core/src/umath/legacy_array_method.c
  numpy/core/src/umath/legacy_array_method.h
  numpy/core/src/umath/ufunc_object.c
  numpy/core/src/umath/ufunc_type_resolution.c
  numpy/core/src/umath/ufunc_type_resolution.h
  numpy/core/tests/test_scalarmath.py
  numpy/core/tests/test_ufunc.py
Labels: 03 - Maintenance
