Repository numpy/numpy, pull requests merged in 2022-02, with the labels that each got.

#20940 MAINT: f2py: don't generate code that triggers `-Wsometimes-uninitialized`
  numpy/f2py/cb_rules.py
Labels: component: numpy.f2py, 03 - Maintenance

#20963 MAINT: be more tolerant of setuptools>=60
  setup.py
Labels: 03 - Maintenance

#20872 BUG: Loss of precision in longdouble min
  numpy/core/src/umath/loops_minmax.dispatch.c.src
  numpy/core/tests/test_umath.py
Labels: 00 - Bug

#20966 DOC: update python minimal version to build from source
  doc/source/user/building.rst
Labels: 04 - Documentation

#20973 DOC: switch Python intersphinx link from dev to stable.
  doc/source/conf.py
Labels: 04 - Documentation

#20956 DOC: Improve NEP page layout with nested toctrees
  doc/neps/.gitignore
  doc/neps/accepted.rst.tmpl
  doc/neps/deferred.rst.tmpl
  doc/neps/finished.rst.tmpl
  doc/neps/index.rst
  doc/neps/index.rst.tmpl
  doc/neps/meta.rst.tmpl
  doc/neps/open.rst.tmpl
  doc/neps/provisional.rst.tmpl
  doc/neps/rejected.rst.tmpl
  doc/neps/tools/build_index.py
Labels: 04 - Documentation

#20185 DOC: Added explanation document on interoperability
  doc/source/reference/arrays.classes.rst
  doc/source/reference/arrays.interface.rst
  doc/source/user/basics.interoperability.rst
  doc/source/user/basics.rst
  doc/source/user/c-info.beyond-basics.rst
  tools/refguide_check.py
Labels: 04 - Documentation

#20967 MAINT: Update to numpydoc v1.2
  doc_requirements.txt
  environment.yml
Labels: 03 - Maintenance

#20960 ENH: review return values for PyArray_DescrNew
  numpy/core/src/multiarray/_multiarray_tests.c.src
  numpy/core/src/multiarray/arrayobject.c
  numpy/core/src/multiarray/buffer.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/descriptor.c
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/src/multiarray/getset.c
  numpy/core/src/multiarray/methods.c
  numpy/core/src/multiarray/nditer_constr.c
  numpy/core/src/multiarray/scalarapi.c
  numpy/core/src/multiarray/scalartypes.c.src
Labels: 01 - Enhancement, 09 - Backport-Candidate

#20975 MAINT: refactor NonNull in API functions
  numpy/core/code_generators/genapi.py
  numpy/core/code_generators/numpy_api.py
  numpy/core/src/multiarray/convert.c
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/methods.c
  numpy/core/src/multiarray/scalarapi.c
Labels: 03 - Maintenance

#20904 ENH,BUG: Expand the experimental DType API and fix small exposed issue
  numpy/core/include/numpy/experimental_dtype_api.h
  numpy/core/setup.py
  numpy/core/src/multiarray/array_method.c
  numpy/core/src/multiarray/array_method.h
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/dtype_transfer.c
  numpy/core/src/multiarray/dtype_transfer.h
  numpy/core/src/multiarray/experimental_public_dtype_api.c
  numpy/core/src/umath/legacy_array_method.c
  numpy/core/src/umath/legacy_array_method.h
  numpy/core/src/umath/wrapping_array_method.c
Labels: 01 - Enhancement

#20982 MAINT: f2py: don't generate code that triggers ``-Wsometimes-uninitialized``.
  numpy/f2py/cb_rules.py
Labels: component: numpy.f2py, 03 - Maintenance, 08 - Backport

#20983 BUG: Fix incorrect return type in reduce without initial value
  numpy/core/src/umath/reduction.c
  numpy/core/tests/test_ufunc.py
Labels: 00 - Bug, 08 - Backport

#20984 ENH: review return values for PyArray_DescrNew (#20960)
  numpy/core/src/multiarray/_multiarray_tests.c.src
  numpy/core/src/multiarray/arrayobject.c
  numpy/core/src/multiarray/buffer.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/descriptor.c
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/src/multiarray/getset.c
  numpy/core/src/multiarray/methods.c
  numpy/core/src/multiarray/nditer_constr.c
  numpy/core/src/multiarray/scalarapi.c
  numpy/core/src/multiarray/scalartypes.c.src
Labels: 01 - Enhancement, 08 - Backport

#20985 MAINT: be more tolerant of setuptools >= 60
  setup.py
Labels: 03 - Maintenance, 08 - Backport

#20986 BUG: Fix misplaced return.
  numpy/core/src/multiarray/dtype_transfer.c
Labels: 00 - Bug, 08 - Backport

#20990 MAINT: Further small return value validation fixes
  numpy/core/src/multiarray/buffer.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/descriptor.c
  numpy/core/src/multiarray/methods.c
  tools/swig/pyfragments.swg
Labels: 03 - Maintenance, 09 - Backport-Candidate

#20992 MAINT: Further small return value validation fixes
  numpy/core/src/multiarray/buffer.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/descriptor.c
  numpy/core/src/multiarray/methods.c
  tools/swig/pyfragments.swg
Labels: 03 - Maintenance, 08 - Backport

#20989 REL: Prepare for NumPy 1.22.2 release.
  doc/changelog/1.22.2-changelog.rst
  doc/source/release/1.22.2-notes.rst
Labels: 14 - Release, component: Documentation

#20996 MAINT: use brackets in github action syntax
  .github/workflows/wheels.yml
Labels: 03 - Maintenance

#20994 REL: Update main after 1.22.2 release.
  .mailmap
  doc/changelog/1.22.2-changelog.rst
  doc/source/release.rst
  doc/source/release/1.22.2-notes.rst
Labels: 14 - Release, component: Documentation

#20133 ENH: Vectorize quicksort for 32-bit dtype using AVX-512
  benchmarks/benchmarks/bench_function_base.py
  numpy/core/setup.py
  numpy/core/src/common/simd/avx512/arithmetic.h
  numpy/core/src/npysort/quicksort.c.src
  numpy/core/src/npysort/x86-qsort.dispatch.c.src
  numpy/core/src/npysort/x86-qsort.h
  numpy/core/tests/test_multiarray.py
Labels: 01 - Enhancement, component: SIMD

#21010 MAINT: Fix warning message for deprecated keyword
  numpy/lib/function_base.py
Labels: 03 - Maintenance

#20999 DOC: Remove mention of deleted subpackages in numpy docstring
  numpy/__init__.py
Labels: 04 - Documentation, 03 - Maintenance

#20580 ENH: Move `loadtxt` to C for much better speed
  doc/release/upcoming_changes/20580.compatibility.rst
  doc/release/upcoming_changes/20580.new_feature.rst
  doc/release/upcoming_changes/20580.performance.rst
  numpy/core/setup.py
  numpy/core/src/multiarray/conversion_utils.c
  numpy/core/src/multiarray/conversion_utils.h
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/multiarray/textreading/conversions.c
  numpy/core/src/multiarray/textreading/conversions.h
  numpy/core/src/multiarray/textreading/field_types.c
  numpy/core/src/multiarray/textreading/field_types.h
  numpy/core/src/multiarray/textreading/growth.c
  numpy/core/src/multiarray/textreading/growth.h
  numpy/core/src/multiarray/textreading/parser_config.h
  numpy/core/src/multiarray/textreading/readtext.c
  numpy/core/src/multiarray/textreading/readtext.h
  numpy/core/src/multiarray/textreading/rows.c
  numpy/core/src/multiarray/textreading/rows.h
  numpy/core/src/multiarray/textreading/str_to_int.c
  numpy/core/src/multiarray/textreading/str_to_int.h
  numpy/core/src/multiarray/textreading/stream.h
  numpy/core/src/multiarray/textreading/stream_pyobject.c
  numpy/core/src/multiarray/textreading/stream_pyobject.h
  numpy/core/src/multiarray/textreading/tokenize.c.src
  numpy/core/src/multiarray/textreading/tokenize.h
  numpy/lib/npyio.py
  numpy/lib/tests/test_io.py
  numpy/lib/tests/test_loadtxt.py
Labels: 01 - Enhancement

#21003 ENH: Suppress over-/underflow RuntimeWarning in assert_array_equal
  numpy/testing/_private/utils.py
  numpy/testing/tests/test_utils.py
Labels: 01 - Enhancement

#19898 DOC: Fixed Refguide errors
  doc/source/user/basics.indexing.rst
  doc/source/user/basics.types.rst
  tools/refguide_check.py
Labels: 04 - Documentation

#21000 MAINT: Replace LooseVersion by _pep440.
  numpy/compat/__init__.py
  numpy/compat/_pep440.py
  numpy/core/setup.py
  numpy/core/setup_common.py
  numpy/core/tests/test_cython.py
  numpy/core/tests/test_scalarmath.py
  numpy/random/tests/test_extending.py
  setup.py
  tools/cythonize.py
Labels: 03 - Maintenance

#21020 DOC: imbalanced backticks
  numpy/core/code_generators/ufunc_docstrings.py
  numpy/polynomial/polynomial.py
Labels: 04 - Documentation

#20974 DOC: Include special case in `hsplit` doc
  numpy/lib/shape_base.py
Labels: 04 - Documentation

#20883 BUG: Fix `np.array_api.can_cast()` by not relying on `np.can_cast()`
  numpy/array_api/_data_type_functions.py
  numpy/array_api/tests/test_data_type_functions.py
  numpy/array_api/tests/test_validation.py
Labels: 00 - Bug

#21021 TYP,ENH: Add dtype-typing support to `fromnumeric` (part 2)
  .gitignore
  numpy/core/fromnumeric.pyi
  numpy/typing/tests/data/fail/fromnumeric.pyi
  numpy/typing/tests/data/reveal/fromnumeric.pyi
Labels: 01 - Enhancement, static typing

#21024 API: Disallow strings in logical ufuncs
  numpy/core/src/umath/dispatching.c
  numpy/core/tests/test_ufunc.py
Labels: 09 - Backport-Candidate, 30 - API

#20976 ENH,BENCH: Optimize floor_divide for VSX4/Power10
  benchmarks/benchmarks/bench_ufunc.py
  doc/release/upcoming_changes/20821.improvement.rst
  numpy/core/src/common/simd/intdiv.h
  numpy/core/src/common/simd/vsx/arithmetic.h
  numpy/core/src/umath/loops_arithmetic.dispatch.c.src
Labels: 01 - Enhancement, component: SIMD

#21027 BUG: use `concurrent.futures.ThreadPoolExecutor` in distutils instead of `multiprocessing.pool.ThreadPool`
  numpy/distutils/ccompiler.py
Labels: 00 - Bug

#20363 SIMD: Replace SVML/ASM of tanh(f32, f64) with universal intrinsics
  numpy/core/code_generators/generate_umath.py
  numpy/core/setup.py
  numpy/core/src/_simd/_simd.dispatch.c.src
  numpy/core/src/common/simd/avx2/memory.h
  numpy/core/src/common/simd/avx512/memory.h
  numpy/core/src/common/simd/neon/memory.h
  numpy/core/src/common/simd/sse/memory.h
  numpy/core/src/common/simd/vsx/memory.h
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/loops_hyperbolic.dispatch.c.src
  numpy/core/src/umath/loops_umath_fp.dispatch.c.src
  numpy/core/tests/test_simd.py
Labels: component: SIMD

#21031 MAINT, STY: Style fixes to quicksort.cpp
  numpy/core/src/npysort/quicksort.cpp
Labels: 03 - Maintenance

#21037 DOC: Consistency of :: syntax.
  numpy/lib/utils.py
Labels: 04 - Documentation

#21040 DOC: "See Also" should not have backticks.
  numpy/typing/_nested_sequence.py
Labels: 04 - Documentation

#21039 MAINT: Remove the RELAXED_STRIDES_CHECKING env variable
  .github/actions/action.yml
  .github/workflows/build_test.yml
  doc/release/upcoming_changes/20220.compatibility.rst
  doc/source/reference/arrays.ndarray.rst
  doc/source/reference/global_state.rst
  numpy/core/include/numpy/ndarraytypes.h
  numpy/core/setup.py
  numpy/core/src/common/array_assign.c
  numpy/core/src/multiarray/buffer.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/flagsobject.c
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/multiarray/shape.c
  numpy/core/tests/test_api.py
  numpy/core/tests/test_multiarray.py
  numpy/core/tests/test_regression.py
  tox.ini
Labels: 03 - Maintenance

#21035 BUILD: remove condition on upload step
  .github/workflows/wheels.yml
Labels: 36 - Build

#20846 ENH, SIMD: improve argmax/argmin performance
  benchmarks/benchmarks/bench_reduce.py
  numpy/core/setup.py
  numpy/core/src/multiarray/argfunc.dispatch.c.src
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/arraytypes.h.src
  numpy/core/tests/test_multiarray.py
Labels: 01 - Enhancement, component: SIMD

#21042 MAINT, STY: Style fixups.
  numpy/core/src/npysort/binsearch.cpp
  numpy/core/src/npysort/selection.cpp
Labels: 03 - Maintenance

#21025 MAINT: Use C++ for tokenizer unicode-kind templating
  numpy/core/setup.py
  numpy/core/src/multiarray/textreading/growth.h
  numpy/core/src/multiarray/textreading/parser_config.h
  numpy/core/src/multiarray/textreading/stream.h
  numpy/core/src/multiarray/textreading/tokenize.cpp
  numpy/core/src/multiarray/textreading/tokenize.h
Labels: 03 - Maintenance

#21054 BUG: (loadtxt) Ignore last empty field when `delimiter=None`
  numpy/core/src/multiarray/textreading/tokenize.cpp
  numpy/lib/tests/test_loadtxt.py
Labels: 00 - Bug

#21015 DOC: Added note about possible arange signatures
  numpy/core/_add_newdocs.py
  numpy/core/overrides.py
Labels: 04 - Documentation

#21060 TYP: Add dtype-typing support to `fromnumeric` part 3
  .gitignore
  numpy/core/fromnumeric.pyi
  numpy/typing/tests/data/fail/fromnumeric.pyi
  numpy/typing/tests/data/reveal/fromnumeric.pyi
Labels: 01 - Enhancement, static typing

#21068 DOC: Fix spelling and grammar in documentation for quantile().
  numpy/lib/function_base.py
Labels: 04 - Documentation

#21061 BLD,ENH: Add vsx3 and vsx4 as targets when building cos/sin and tanh
  numpy/core/src/umath/loops_hyperbolic.dispatch.c.src
  numpy/core/src/umath/loops_trigonometric.dispatch.c.src
Labels: 36 - Build

#21067 BUG: Fix unpickling an empty ndarray with a none-zero dimension
  numpy/core/src/multiarray/methods.c
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug, 09 - Backport-Candidate

#21071 BUG: Ensure equality/identity comparison with `__array_function__`
  numpy/core/src/multiarray/arrayfunction_override.c
  numpy/core/tests/test_overrides.py
Labels: 00 - Bug

#20774 DOC: explicitly define numpy.datetime64 semantics
  doc/source/reference/arrays.datetime.rst
Labels: 04 - Documentation

#20875 DEP: deprecate `numpy.distutils`, and add a migration guide
  doc/release/upcoming_changes/20875.deprecation.rst
  doc/source/reference/distutils.rst
  doc/source/reference/distutils_guide.rst
  doc/source/reference/distutils_status_migration.rst
  doc/source/reference/index.rst
  numpy/distutils/__init__.py
Labels: component: numpy.distutils, 07 - Deprecation

#21074 BUG: Replace ``ssize_t`` with ``size_t`` in tokenize.cpp
  numpy/core/src/multiarray/textreading/tokenize.cpp
Labels: 00 - Bug

#20987 BLD: Try adding aarch64 wheels [wheel build]
  .github/workflows/wheels.yml
  .travis.yml
  tools/wheels/upload_wheels.sh
Labels: 36 - Build

#21085 MAINT: point to html docs on distutils migration in deprecation message
  numpy/distutils/__init__.py
Labels: component: numpy.distutils, 03 - Maintenance

#21077 TYP,MAINT: Remove inconsistencies between `fromnumeric` functions and `ndarray` methods
  numpy/__init__.pyi
  numpy/core/fromnumeric.pyi
Labels: 03 - Maintenance, static typing

#21097 MAINT: update cython, pypy for cython0.29.28 and pypy v7.3.8 release
  .github/workflows/build_test.yml
  .github/workflows/wheels.yml
  INSTALL.rst.txt
  pyproject.toml
  test_requirements.txt
Labels: 03 - Maintenance

#19345 ENH: Move `ensure_dtype_nbo` onto the DType as `ensure_canonical`
  numpy/core/src/multiarray/array_method.c
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/convert_datatype.h
  numpy/core/src/multiarray/datetime.c
  numpy/core/src/multiarray/dtype_transfer.c
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/src/multiarray/dtypemeta.h
  numpy/core/src/umath/legacy_array_method.c
  numpy/core/src/umath/ufunc_type_resolution.c
Labels: 01 - Enhancement, component: numpy.dtype

#21100 BLD: Comment out broken macOS PyPy build [wheel build]
  .github/workflows/wheels.yml
Labels: 36 - Build

#20559 DOC: Refactoring f2py user guide
  doc/source/f2py/code/add-edited.pyf
  doc/source/f2py/code/add-improved.f
  doc/source/f2py/code/add.f
  doc/source/f2py/code/add.pyf
  doc/source/f2py/code/filter.f
  doc/source/f2py/code/myroutine-edited.pyf
  doc/source/f2py/code/myroutine.f90
  doc/source/f2py/code/myroutine.pyf
  doc/source/f2py/f2py-examples.rst
  doc/source/f2py/f2py-reference.rst
  doc/source/f2py/f2py-user.rst
  doc/source/f2py/f2py.getting-started.rst
  doc/source/f2py/index.rst
  doc/source/f2py/python-usage.rst
  doc/source/f2py/signature-file.rst
  doc/source/f2py/usage.rst
  doc/source/glossary.rst
  doc/source/user/c-info.python-as-glue.rst
  numpy/f2py/__init__.py
  numpy/f2py/f2py2e.py
  tools/refguide_check.py
Labels: 04 - Documentation, component: numpy.f2py

#21102 TYP,MAINT: Explicitly allow sequences of array-likes in `np.concatenate`
  numpy/core/multiarray.pyi
  numpy/typing/tests/data/fail/false_positives.pyi
  numpy/typing/tests/data/reveal/array_constructors.pyi
  numpy/typing/tests/data/reveal/false_positives.pyi
Labels: 03 - Maintenance, 09 - Backport-Candidate, static typing

#21088 DEV: add distutils deprecation warning filter to pytest conf
  pytest.ini
Labels: 16 - Development

#21109 MAINT: Fix incorrect signature in readtext header file
  numpy/core/src/multiarray/textreading/readtext.h
Labels: 03 - Maintenance

#19346 API: Fix `np.result_type(structured_dtype)` to "canonicalize"
  numpy/core/src/multiarray/descriptor.c
  numpy/core/src/multiarray/descriptor.h
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/tests/test_dtype.py
Labels: 30 - API

#21108 TYP, ENH: Mark non-subclassable classes as `final`
  numpy/__init__.pyi
  numpy/typing/_ufunc.pyi
Labels: 01 - Enhancement, static typing

#21111 TYP, MAINT: Relax the `obj` type in `__array_finalize__`
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/ndarray_misc.pyi
  numpy/typing/tests/data/reveal/chararray.pyi
  numpy/typing/tests/data/reveal/memmap.pyi
  numpy/typing/tests/data/reveal/ndarray_misc.pyi
  numpy/typing/tests/data/reveal/rec.pyi
Labels: 03 - Maintenance, static typing

#21110 CI: Improve concurrency to cancel running jobs on PR update
  .github/workflows/build_test.yml
  .github/workflows/cygwin.yml
  .github/workflows/wheels.yml
Labels: component: CI

#21119 BUG, ENH: np._from_dlpack: export correct device information
  numpy/core/src/multiarray/dlpack.c
  numpy/core/tests/test_dlpack.py
Labels: 00 - Bug

#21106 TYP,MAINT: Explicitly allow sequences of array-likes in `np.concatenate`
  numpy/core/multiarray.pyi
  numpy/typing/tests/data/fail/false_positives.pyi
  numpy/typing/tests/data/reveal/array_constructors.pyi
  numpy/typing/tests/data/reveal/false_positives.pyi
Labels: 03 - Maintenance, 08 - Backport, static typing

#21113 BUG: Fix numba DUFuncs added loops getting picked up
  numpy/core/src/umath/dispatching.c
Labels: 00 - Bug, 09 - Backport-Candidate

#16895 MAINT: extend delete single value optimization
  numpy/lib/function_base.py
  numpy/lib/tests/test_function_base.py
Labels: component: numpy.lib, 03 - Maintenance

#21127 BLD,DOC: skip broken ipython 8.1.0
  doc_requirements.txt
Labels: 09 - Backport-Candidate, 36 - Build
