Repository numpy/numpy, pull requests merged in 2022-06, with the labels that each got.

#21471 DOC: adding docstring to TooHardError class
  numpy/core/_exceptions.py
Labels: 04 - Documentation

#21641 DOC: Note version-switcher update in the release walkthrough
  doc/RELEASE_WALKTHROUGH.rst
Labels: 04 - Documentation

#21623 ENH: Add equals_nans kwarg to np.unique Fixes #20326
  doc/release/upcoming_changes/21623.new_feature.rst
  numpy/lib/arraysetops.py
  numpy/lib/tests/test_arraysetops.py
Labels: 62 - Python API

#16154 ENH: Add support for symbol to polynomial package
  doc/release/upcoming_changes/16154.new_feature.rst
  doc/source/reference/routines.polynomials.classes.rst
  doc/source/reference/routines.polynomials.rst
  numpy/polynomial/_polybase.py
  numpy/polynomial/tests/test_printing.py
  numpy/polynomial/tests/test_symbol.py
Labels: 01 - Enhancement, component: numpy.polynomial, 54 - Needs decision, 62 - Python API

#21646 ENH: Add equals_nan kwarg to np.unique
  doc/release/upcoming_changes/21623.new_feature.rst
  numpy/lib/arraysetops.py
  numpy/lib/tests/test_arraysetops.py
Labels: 01 - Enhancement

#21651 MAINT: Remove unused/not useful CODEOWNERS file again
  .github/CODEOWNERS
Labels: 03 - Maintenance

#21660 MAINT: Adapt the npt._GenericAlias backport to Python 3.11 types.GenericAlias changes
  .github/workflows/build_test.yml
  environment.yml
  numpy/_typing/_generic_alias.py
  numpy/typing/tests/test_generic_alias.py
  test_requirements.txt
Labels: 03 - Maintenance, 08 - Backport, static typing

#21659 BUG: Fix a bug left after f2py2e refactor
  numpy/f2py/f2py2e.py
Labels: 00 - Bug, component: numpy.f2py, 09 - Backport-Candidate

#21649 MAINT: Start testing with Python 3.11.
  .github/workflows/build_test.yml
  numpy/core/tests/test_multiarray.py
Labels: 03 - Maintenance, 08 - Backport

#21645 DEP: Remove `normed=` keyword argument from histograms
  doc/release/upcoming_changes/21645.expired.rst
  numpy/lib/histograms.py
  numpy/lib/histograms.pyi
  numpy/lib/tests/test_histograms.py
  numpy/lib/twodim_base.py
  numpy/lib/twodim_base.pyi
  numpy/typing/tests/data/fail/histograms.pyi
Labels: 07 - Deprecation

#21658 MAINT: improved overflow check to avoid undefined behavior
  numpy/core/src/umath/scalarmath.c.src
Labels: 03 - Maintenance

#21662 DOC: ``np`` in double backticks.
  numpy/__init__.py
Labels: 04 - Documentation

#21661 TYP, ENH: Add annotations for the `equal_nan` keyword to `np.unique`
  numpy/lib/arraysetops.pyi
Labels: 01 - Enhancement, static typing

#21666 MAINT: Change array API unique_*() functions to not compare nans as equal
  numpy/array_api/_set_functions.py
Labels: 03 - Maintenance, component: numpy.array_api

#15782 ENH: complete the 'vars' list of a module
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/src/crackfortran/pubprivmod.f90
  numpy/f2py/tests/test_crackfortran.py
Labels: 01 - Enhancement, component: numpy.f2py

#21675 DOC: Add note about broadcasting support for `random.Generator.multinomial`
  numpy/random/_generator.pyx
Labels: 04 - Documentation

#21664 DOC: Misc RST reformatting.
  doc/source/dev/development_workflow.rst
  doc/source/reference/arrays.datetime.rst
  doc/source/reference/arrays.ndarray.rst
  doc/source/reference/arrays.scalars.rst
  doc/source/reference/distutils_status_migration.rst
  doc/source/reference/swig.interface-file.rst
  doc/source/user/basics.creation.rst
  doc/source/user/basics.indexing.rst
  doc/source/user/basics.rec.rst
  doc/source/user/depending_on_numpy.rst
  numpy/core/multiarray.py
Labels: 04 - Documentation

#19388 ENH: Support character and character string arrays
  doc/release/upcoming_changes/19388.improvement.rst
  doc/release/upcoming_changes/19388.new_feature.rst
  doc/source/f2py/advanced.rst
  doc/source/f2py/code/asterisk1.f90
  doc/source/f2py/code/asterisk2.f90
  doc/source/f2py/code/results/asterisk1_session.dat
  doc/source/f2py/code/results/asterisk2_session.dat
  doc/source/f2py/signature-file.rst
  numpy/f2py/auxfuncs.py
  numpy/f2py/capi_maps.py
  numpy/f2py/cb_rules.py
  numpy/f2py/cfuncs.py
  numpy/f2py/common_rules.py
  numpy/f2py/crackfortran.py
  numpy/f2py/f90mod_rules.py
  numpy/f2py/func2subr.py
  numpy/f2py/rules.py
  numpy/f2py/src/fortranobject.c
  numpy/f2py/src/fortranobject.h
  numpy/f2py/tests/src/array_from_pyobj/wrapmodule.c
  numpy/f2py/tests/test_array_from_pyobj.py
  numpy/f2py/tests/test_callback.py
  numpy/f2py/tests/test_character.py
  numpy/f2py/tests/test_crackfortran.py
  numpy/f2py/tests/test_docs.py
  numpy/f2py/tests/test_return_character.py
  numpy/f2py/tests/util.py
Labels: 01 - Enhancement, component: numpy.f2py

#21681 MAINT: Point documentation version switcher at the docs homepage
  doc/RELEASE_WALKTHROUGH.rst
  doc/source/_static/versions.json
  doc/source/conf.py
Labels: 03 - Maintenance, 09 - Backport-Candidate

#21684 MAINT: Point documentation version switcher at the docs homepage
  doc/RELEASE_WALKTHROUGH.rst.txt
  doc/source/conf.py
Labels: 03 - Maintenance, 08 - Backport

#21663 DEP: Deprecate (rather than remove) the int-via-float parsing in loadtxt
  numpy/core/src/multiarray/textreading/parser_config.h
  numpy/core/src/multiarray/textreading/readtext.c
  numpy/core/src/multiarray/textreading/str_to_int.c
  numpy/core/tests/test_deprecations.py
Labels: 07 - Deprecation, 09 - Backport-Candidate

#21689 DOC: Fix broadcasting documentation.
  doc/source/user/basics.broadcasting.rst
Labels: 04 - Documentation

#21688 DEP: Deprecate (rather than remove) the int-via-float parsing in loadtxt
  doc/source/release/1.23.0-notes.rst
  numpy/core/src/multiarray/textreading/parser_config.h
  numpy/core/src/multiarray/textreading/readtext.c
  numpy/core/src/multiarray/textreading/str_to_int.c
  numpy/core/tests/test_deprecations.py
Labels: 07 - Deprecation, 08 - Backport

#21692 MAINT: Renamed doc/records.rst.txt to doc/records.rst
  doc/records.rst
Labels: 03 - Maintenance

#21690 BUG: Prevent attempted broadcasting of 0-D output operands in ufuncs
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_ufunc.py
Labels: 00 - Bug, 09 - Backport-Candidate

#21691 BUG: Small fixupes found using valgrind
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/textreading/tokenize.cpp
Labels: 00 - Bug, 09 - Backport-Candidate

#21697 BUG: Fix a refactor leftover bug
  numpy/f2py/f2py2e.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#21627 ENH: adding casting option to numpy.stack.
  .gitignore
  doc/release/upcoming_changes/21627.new_feature.rst
  numpy/core/shape_base.py
  numpy/core/shape_base.pyi
  numpy/core/tests/test_shape_base.py
Labels: 01 - Enhancement, 62 - Python API

#21698 BUG: Prevent attempted broadcasting of 0-D output operands in ufuncs
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_ufunc.py
Labels: 00 - Bug, 07 - Deprecation, 08 - Backport

#21701 BUG: Enable fortran preprocessing for ifort on Windows
  numpy/distutils/fcompiler/intel.py
Labels: 00 - Bug, component: numpy.distutils

#21704 DOC: Mention positional-only arguments in the array API compatibility doc
  doc/source/reference/array_api.rst
Labels: 04 - Documentation

#21527 PERF: Fast path for dtype lookup of float and long
  numpy/core/src/multiarray/array_coercion.c
Labels: 03 - Maintenance

#16971 BUG: Fix three `complex`- & `float128`-related issues with `nd_grid`
  numpy/lib/index_tricks.py
  numpy/lib/tests/test_index_tricks.py
Labels: 00 - Bug, component: numpy.lib

#21564 TST: Enable doctests in IO Howto with testsetup and testcleanup
  doc/source/user/how-to-io.rst
Labels: 05 - Testing, 04 - Documentation

#21707 MAINT: generate_umath.py: do not write full path into output files
  numpy/core/code_generators/generate_umath.py
Labels: 03 - Maintenance

#21709 TST: Fixup loadtxt int-via-float tests when in release mode
  numpy/core/tests/test_deprecations.py
  numpy/lib/tests/test_loadtxt.py
Labels: 00 - Bug, 05 - Testing, 09 - Backport-Candidate

#21710 TST: Fixup loadtxt int-via-float tests when in release mode
  numpy/core/tests/test_deprecations.py
  numpy/lib/tests/test_loadtxt.py
Labels: 00 - Bug, 05 - Testing, 08 - Backport

#21705 BLD, SIMD: Fix detect armhf and hardened the Neon/ASIMD compile-time tests
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/checks/cpu_asimd.c
  numpy/distutils/checks/cpu_asimddp.c
  numpy/distutils/checks/cpu_asimdfhm.c
  numpy/distutils/checks/cpu_asimdhp.c
  numpy/distutils/checks/cpu_neon.c
  numpy/distutils/checks/cpu_neon_fp16.c
  numpy/distutils/checks/cpu_neon_vfpv4.c
Labels: component: numpy.distutils, 09 - Backport-Candidate, component: SIMD, 36 - Build

#21712 BUG: `.f2py_f2cmap` doesn't map `long_long` and other options
  numpy/f2py/capi_maps.py
  numpy/f2py/rules.py
  numpy/f2py/tests/src/f2cmap/.f2py_f2cmap
  numpy/f2py/tests/src/f2cmap/isoFortranEnvMap.f90
  numpy/f2py/tests/test_f2cmap.py
Labels: 00 - Bug, component: numpy.f2py

#21716 ENH: Implement string comparison ufuncs (or almost)
  benchmarks/benchmarks/bench_strings.py
  numpy/core/include/numpy/experimental_dtype_api.h
  numpy/core/setup.py
  numpy/core/src/common/numpyos.h
  numpy/core/src/multiarray/array_method.h
  numpy/core/src/multiarray/arrayobject.c
  numpy/core/src/multiarray/common_dtype.h
  numpy/core/src/multiarray/convert_datatype.h
  numpy/core/src/multiarray/dtypemeta.h
  numpy/core/src/multiarray/experimental_public_dtype_api.c
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/umath/dispatching.c
  numpy/core/src/umath/dispatching.h
  numpy/core/src/umath/string_ufuncs.cpp
  numpy/core/src/umath/string_ufuncs.h
  numpy/core/src/umath/umathmodule.c
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_strings.py
  numpy/core/tests/test_unicode.py
Labels: 01 - Enhancement, 08 - Backport

#21718 BUG: use explicit einsum_path whenever it is given
  numpy/core/einsumfunc.py
  numpy/core/tests/test_einsum.py
Labels: 00 - Bug, 08 - Backport

#21721 BLD, SIMD: Fix detect armhf and hardened the Neon/ASIMD compile-time tests
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/checks/cpu_asimd.c
  numpy/distutils/checks/cpu_asimddp.c
  numpy/distutils/checks/cpu_asimdfhm.c
  numpy/distutils/checks/cpu_asimdhp.c
  numpy/distutils/checks/cpu_neon.c
  numpy/distutils/checks/cpu_neon_fp16.c
  numpy/distutils/checks/cpu_neon_vfpv4.c
Labels: component: numpy.distutils, 08 - Backport, component: SIMD, 36 - Build

#21722 BUG: .f2py_f2cmap doesn't map long_long and other options
  numpy/f2py/capi_maps.py
  numpy/f2py/rules.py
  numpy/f2py/tests/src/f2cmap/.f2py_f2cmap
  numpy/f2py/tests/src/f2cmap/isoFortranEnvMap.f90
  numpy/f2py/tests/test_f2cmap.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#21720 BUG: Enable fortran preprocessing for ifort on Windows
  numpy/distutils/fcompiler/intel.py
Labels: 00 - Bug, component: numpy.distutils, 08 - Backport

#21719 BUG: Small fixupes found using valgrind
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/textreading/tokenize.cpp
Labels: 00 - Bug, 08 - Backport

#21728 API: Retain `arr.base` more strictly in `np.frombuffer`
  numpy/core/src/multiarray/ctors.c
  numpy/core/tests/test_multiarray.py
Labels: 30 - API

#21729 REL: Prepare for the NumPy 1.23.0rc3 release.
  doc/changelog/1.23.0-changelog.rst
  doc/release/upcoming_changes/21623.new_feature.rst
  doc/source/release/1.23.0-notes.rst
Labels: 14 - Release

#20914 BUG: change `ma.mean` dtype to be consistent with `np.mean`
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
Labels: 00 - Bug

#20913 ENH, SIMD: Extend universal intrinsics to support IBMZ
  doc/release/upcoming_changes/20913.improvement.rst
  numpy/core/src/_simd/_simd.dispatch.c.src
  numpy/core/src/_simd/_simd_convert.inc
  numpy/core/src/_simd/_simd_inc.h.src
  numpy/core/src/common/npy_cpu_dispatch.h
  numpy/core/src/common/simd/avx2/avx2.h
  numpy/core/src/common/simd/avx512/avx512.h
  numpy/core/src/common/simd/emulate_maskop.h
  numpy/core/src/common/simd/intdiv.h
  numpy/core/src/common/simd/neon/neon.h
  numpy/core/src/common/simd/simd.h
  numpy/core/src/common/simd/sse/sse.h
  numpy/core/src/common/simd/vec/arithmetic.h
  numpy/core/src/common/simd/vec/conversion.h
  numpy/core/src/common/simd/vec/math.h
  numpy/core/src/common/simd/vec/memory.h
  numpy/core/src/common/simd/vec/misc.h
  numpy/core/src/common/simd/vec/operators.h
  numpy/core/src/common/simd/vec/reorder.h
  numpy/core/src/common/simd/vec/utils.h
  numpy/core/src/common/simd/vec/vec.h
  numpy/core/src/multiarray/argfunc.dispatch.c.src
  numpy/core/src/multiarray/einsum_sumprod.c.src
  numpy/core/src/umath/loops_arithm_fp.dispatch.c.src
  numpy/core/src/umath/loops_arithmetic.dispatch.c.src
  numpy/core/src/umath/loops_comparison.dispatch.c.src
  numpy/core/src/umath/loops_hyperbolic.dispatch.c.src
  numpy/core/src/umath/loops_minmax.dispatch.c.src
  numpy/core/src/umath/loops_trigonometric.dispatch.c.src
  numpy/core/src/umath/loops_unary_fp.dispatch.c.src
  numpy/core/tests/test_simd.py
  numpy/core/tests/test_simd_module.py
  tools/travis-test.sh
Labels: 01 - Enhancement, 56 - Needs Release Note., component: SIMD

#21734 ENH: Check that we are targeting x86 or x64 architecture before using bsr asm instruction
  numpy/core/src/common/simd/intdiv.h
Labels: 01 - Enhancement

#21735 ENH: cross compilation: use sysconfig to determine if x86_64 linux
  numpy/core/setup.py
Labels: 01 - Enhancement

#20924 MAINT: Simplify element setting and use it for filling
  doc/release/upcoming_changes/20924.compatibility.rst
  numpy/core/_add_newdocs.py
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/src/multiarray/convert.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/src/multiarray/iterators.c
  numpy/core/tests/test_array_coercion.py
  numpy/core/tests/test_multiarray.py
Labels: 03 - Maintenance, 58 - Ready for review, Triaged

#21733 ENH: Fix pointer size determination for cross build
  numpy/linalg/setup.py
Labels: 01 - Enhancement

#21587 DOC: update logarithm docs as per theory.
  numpy/core/code_generators/ufunc_docstrings.py
Labels: 04 - Documentation

#21731 ENH: Ensure dispatcher TypeErrors report original name
  numpy/core/overrides.py
  numpy/core/tests/test_overrides.py
Labels: 01 - Enhancement, Triage-review

#21648 ENH: issue overflow warning when using `abs` on `np.int8(-128)`
  numpy/core/src/umath/scalarmath.c.src
  numpy/core/tests/test_scalarmath.py
  numpy/typing/tests/data/pass/arithmetic.py
Labels: 01 - Enhancement, 59 - Needs tests

#21745 MAINT: Remove FPE helper code that is unnecessary on C99/C++11
  numpy/core/src/npymath/ieee754.c.src
Labels: 03 - Maintenance

#21437 ENH: Add floating point error checking to (almost) all casts
  doc/release/upcoming_changes/21437.improvement.rst
  numpy/core/include/numpy/ndarraytypes.h
  numpy/core/src/common/lowlevel_strided_loops.h
  numpy/core/src/common/umathmodule.h
  numpy/core/src/multiarray/array_assign_array.c
  numpy/core/src/multiarray/array_assign_scalar.c
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/src/multiarray/array_method.h
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/dtype_transfer.c
  numpy/core/src/multiarray/lowlevel_strided_loops.c.src
  numpy/core/src/multiarray/mapping.c
  numpy/core/src/multiarray/mapping.h
  numpy/core/src/multiarray/nditer_api.c
  numpy/core/src/multiarray/nditer_constr.c
  numpy/core/src/multiarray/nditer_impl.h
  numpy/core/src/umath/extobj.c
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_array_coercion.py
  numpy/core/tests/test_casting_floatingpoint_errors.py
  numpy/core/tests/test_half.py
  numpy/core/tests/test_indexing.py
  numpy/core/tests/test_numeric.py
  numpy/core/tests/test_regression.py
  numpy/core/tests/test_ufunc.py
  numpy/ma/tests/test_core.py
Labels: 01 - Enhancement

#21748 BUG: Fix for npyv_orc_b8 and npyv_xnor_b8 for s390x (z13)
  numpy/core/src/common/simd/vec/operators.h
Labels: 00 - Bug

#21749 BUG, SIMD: Fix detecting NEON/ASIMD on aarch64
  numpy/distutils/checks/cpu_asimd.c
Labels: 00 - Bug, 09 - Backport-Candidate

#21567 BUG: Adding the default pytest doctest instead of the ValueError
  numpy/_pytesttester.py
Labels: 00 - Bug

#21754 BUG, SIMD: Fix detecting NEON/ASIMD on aarch64
  numpy/distutils/checks/cpu_asimd.c
Labels: 00 - Bug, 08 - Backport

#21732 ENH: Add support for platforms with missing fenv flags
  numpy/core/src/npymath/ieee754.c.src
  numpy/core/src/npymath/ieee754.cpp
Labels: 01 - Enhancement

#21759 BUG: Fix small reference leaks found with pytest-leaks
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/multiarray/textreading/rows.c
  numpy/lib/tests/test_loadtxt.py
Labels: 00 - Bug, 09 - Backport-Candidate

#21757 BUG: Do not skip value-based promotion path for large Python integers
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/tests/test_dtype.py
Labels: 00 - Bug, 08 - Backport

#21761 BUG: Fix small reference leaks found with pytest-leaks
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/multiarray/textreading/rows.c
  numpy/lib/tests/test_loadtxt.py
Labels: 00 - Bug, 08 - Backport

#21403 MAINT: remove some names from main numpy namespace
  numpy/__init__.py
  numpy/__init__.pyi
Labels: 01 - Enhancement, 03 - Maintenance

#21084 MAINT: Fix computation of numpy.array_api.linalg.vector_norm
  numpy/array_api/linalg.py
Labels: 03 - Maintenance

#21771 MAINT: Add a check of the return value of PyMem_Calloc().
  numpy/core/src/multiarray/textreading/readtext.c
Labels: component: numpy.core, 03 - Maintenance, 09 - Backport-Candidate

#21773 MAINT: fix typo in string_ufuncs.cpp
  numpy/core/src/umath/string_ufuncs.cpp
Labels: 03 - Maintenance

#21777 REV: Revert "ENH: Implement string comparison ufuncs (or almost) "
  benchmarks/benchmarks/bench_strings.py
  numpy/core/include/numpy/experimental_dtype_api.h
  numpy/core/setup.py
  numpy/core/src/common/numpyos.h
  numpy/core/src/multiarray/array_method.h
  numpy/core/src/multiarray/arrayobject.c
  numpy/core/src/multiarray/common_dtype.h
  numpy/core/src/multiarray/convert_datatype.h
  numpy/core/src/multiarray/dtypemeta.h
  numpy/core/src/multiarray/experimental_public_dtype_api.c
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/umath/dispatching.c
  numpy/core/src/umath/dispatching.h
  numpy/core/src/umath/string_ufuncs.cpp
  numpy/core/src/umath/string_ufuncs.h
  numpy/core/src/umath/umathmodule.c
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_strings.py
  numpy/core/tests/test_unicode.py
Labels: 34 - Reversion

#21779 MAINT: random: Disallow complex inputs in multivariate_normal
  numpy/random/_generator.pyx
  numpy/random/tests/test_generator_mt19937.py
Labels: component: numpy.random, 03 - Maintenance

#21790 ENH: add overflow handling for scalar `negative` operation
  numpy/core/src/umath/scalarmath.c.src
  numpy/core/tests/test_scalarmath.py
Labels: 01 - Enhancement

#21794 BUG: lib: A loadtxt error message had two values reversed.
  numpy/core/src/multiarray/textreading/rows.c
  numpy/lib/tests/test_loadtxt.py
Labels: 00 - Bug, component: numpy.lib, 09 - Backport-Candidate

#21796 BUG: Fix comparison for empty structured arrays
  numpy/core/src/multiarray/arrayobject.c
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug

#21789 ENH: Change f2c declarations with void return type to int
  numpy/linalg/lapack_lite/f2c.c
  numpy/linalg/lapack_lite/f2c.h
Labels: 01 - Enhancement

#21798 MAINT: use PyErr_SetString in _import_array where possible
  numpy/core/code_generators/generate_numpy_api.py
Labels: 03 - Maintenance

#21809 MAINT: Add a check of the return value of PyMem_Calloc().
  numpy/core/src/multiarray/textreading/readtext.c
Labels: component: numpy.core, 03 - Maintenance, 08 - Backport

#21811 REL: Prepare for the NumPy 1.23.0 release
  doc/changelog/1.23.0-changelog.rst
  doc/source/release/1.23.0-notes.rst
Labels: 14 - Release

#21823 MAINT: Try fixing broken Anaconda uploads.
  tools/wheels/upload_wheels.sh
Labels: 03 - Maintenance

#21825 REL: Prepare for the NumPy 1.23.0 release (2)
  doc/changelog/1.23.0-changelog.rst
Labels: 14 - Release

#21797 MAINT: Reduce object construction in np.require
  numpy/core/_asarray.py
Labels: 01 - Enhancement, 03 - Maintenance

#21830 DOC: Change substract to subtract in comment
  numpy/core/src/common/simd/neon/math.h
Labels: 04 - Documentation

#21817 ENH: Always fill object fields with None rather than NULL
  numpy/core/src/multiarray/arrayobject.c
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/umath/loops.c.src
  numpy/core/tests/test_casting_unittests.py
  numpy/core/tests/test_multiarray.py
Labels: 01 - Enhancement

#21812 BUG: Define `<`, `<=`, `>`, `>=` for masked arrays
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
Labels: 00 - Bug, 30 - API

#21836 DOC: F2PY documentation improvements
  doc/source/f2py/advanced.rst
  doc/source/f2py/code/f2cmap_demo.f
  doc/source/f2py/code/meson.build
  doc/source/f2py/usage.rst
Labels: 04 - Documentation, component: numpy.f2py, 03 - Maintenance

#21842 BUG: Fix in1d for empty integer array as input
  numpy/lib/arraysetops.py
  numpy/lib/tests/test_arraysetops.py
Labels: 00 - Bug

#21595 ENH: Add strict parameter to assert_array_equal. Fixes #9542
  doc/release/upcoming_changes/21595.new_feature.rst
  numpy/testing/_private/utils.py
  numpy/testing/_private/utils.pyi
  numpy/testing/tests/test_utils.py
Labels: 01 - Enhancement, component: numpy.testing, 62 - Python API

#21815 BUG: Fix discovered MachAr (still used within valgrind)
  numpy/core/_machar.py
  numpy/core/getlimits.py
Labels: 00 - Bug

#21723 DOC: Update sphinx, numpydoc, and pydata-sphinx-theme
  azure-pipelines.yml
  doc/source/conf.py
  doc_requirements.txt
  environment.yml
  tools/refguide_check.py
Labels: 04 - Documentation

#21626 API: Introduce optional (and partial) NEP 50 weak scalar logic
  doc/neps/nep-0050-scalar-promotion.rst
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/conftest.py
  numpy/core/_methods.py
  numpy/core/_ufunc_config.py
  numpy/core/_ufunc_config.pyi
  numpy/core/include/numpy/ndarraytypes.h
  numpy/core/multiarray.py
  numpy/core/numeric.py
  numpy/core/src/multiarray/abstractdtypes.c
  numpy/core/src/multiarray/abstractdtypes.h
  numpy/core/src/multiarray/arrayobject.h
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/convert_datatype.h
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/umath/dispatching.c
  numpy/core/src/umath/dispatching.h
  numpy/core/src/umath/ufunc_object.c
  numpy/core/src/umath/ufunc_type_resolution.c
  numpy/core/tests/test_dtype.py
  numpy/core/tests/test_einsum.py
  numpy/core/tests/test_half.py
  numpy/core/tests/test_nep50_promotions.py
  numpy/core/tests/test_scalarmath.py
  numpy/core/tests/test_ufunc.py
  numpy/lib/tests/test_function_base.py
  numpy/linalg/tests/test_linalg.py
  numpy/testing/_private/utils.py
Labels: 30 - API

#21851 BUG: Use `keepdims` during normalization in `np.average` and `np.ma.average`
  numpy/lib/function_base.py
  numpy/lib/tests/test_function_base.py
  numpy/ma/extras.py
  numpy/ma/tests/test_extras.py
Labels: 00 - Bug, component: numpy.lib, 09 - Backport-Candidate

#21855 DOC: Replace the mathematical notation N(...) with text.
  numpy/matlib.py
  numpy/polynomial/polynomial.py
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
Labels: 04 - Documentation

#21848 BUG: Handle NaNs correctly for float16 during sorting
  numpy/core/src/npysort/binsearch.cpp
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug, 09 - Backport-Candidate

#21857 BUG: Reject non integer array-likes with size 1 in delete
  numpy/lib/function_base.py
  numpy/lib/tests/test_function_base.py
Labels: 00 - Bug, 06 - Regression, 09 - Backport-Candidate

#21869 DOC: mention changes to `max_rows` behaviour in `np.loadtxt`
  numpy/lib/npyio.py
Labels: 04 - Documentation, 08 - Backport

#21867 BUG: Handle NaNs correctly for float16 during sorting
  numpy/core/src/npysort/binsearch.cpp
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug, 08 - Backport

#21866 BUG: Fix discovered MachAr (still used within valgrind)
  numpy/core/_machar.py
  numpy/core/getlimits.py
Labels: 00 - Bug, 08 - Backport

#21872 CI: tools: Remove a long but obsolete comment from travis-test.sh
  tools/travis-test.sh
Labels: 03 - Maintenance, component: CI

#21863 ENH,MAINT: Improve and simplify scalar floating point warnings
  numpy/core/_ufunc_config.py
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/umath/scalarmath.c.src
  numpy/lib/tests/test_arraypad.py
Labels: 01 - Enhancement

#21849 MAINT: Update the documentation Makefile
  .gitignore
  doc/HOWTO_RELEASE.rst
  doc/Makefile
  doc/RELEASE_WALKTHROUGH.rst
Labels: 03 - Maintenance

#21884 MAINT: Fix non-void function does not return a value warning
  numpy/linalg/lapack_lite/f2c.c
Labels: 03 - Maintenance

#21860 BUG: Fix numpy.isin for timedelta dtype
  numpy/lib/arraysetops.py
  numpy/lib/tests/test_arraysetops.py
Labels: 00 - Bug, 06 - Regression

#21881 MAINT: Disable checks for Win workaround for GCC
  numpy/core/tests/test_multiarray.py
Labels: 03 - Maintenance

#21885 DOC: Link to PEP-484 in the typing docs
  numpy/typing/__init__.py
Labels: 04 - Documentation, Static typing
