Repository numpy/numpy, pull requests merged in 2022-01, with the labels that each got.

#20691 DOC, ENH: Added pngs for svgs for pdf build
  doc/source/user/broadcasting_1.png
  doc/source/user/broadcasting_2.png
  doc/source/user/broadcasting_3.png
  doc/source/user/broadcasting_4.png
  doc/source/user/broadcasting_5.png
Labels: 04 - Documentation, 09 - Backport-Candidate

#20693 DOC: Replaced svgs with pngs in the Broadcasting doc
  doc/source/user/basics.broadcasting.rst
Labels: 04 - Documentation, 09 - Backport-Candidate

#20698 DOC:Fixed the link on user-guide landing page
  doc/source/reference/index.rst
Labels: 04 - Documentation, 09 - Backport-Candidate

#20697 REL: Update main after 1.22.0 release.
  .mailmap
  doc/changelog/1.22.0-changelog.rst
  doc/source/release/1.22.0-notes.rst
Labels: 14 - Release, 04 - Documentation, component: Documentation

#20701 MAINT, DOC: Post 1.22.0 release fixes.
  doc/RELEASE_WALKTHROUGH.rst.txt
  doc_requirements.txt
Labels: 04 - Documentation, 03 - Maintenance, 09 - Backport-Candidate

#20702 MAINT, DOC: Post 1.22.0 release fixes.
  doc/RELEASE_WALKTHROUGH.rst.txt
  doc_requirements.txt
Labels: 04 - Documentation, 03 - Maintenance, 08 - Backport

#20703 DOC, BUG: Use pngs instead of svgs.
  doc/source/user/basics.broadcasting.rst
  doc/source/user/broadcasting_1.png
  doc/source/user/broadcasting_2.png
  doc/source/user/broadcasting_3.png
  doc/source/user/broadcasting_4.png
  doc/source/user/broadcasting_5.png
Labels: 00 - Bug, 04 - Documentation, 08 - Backport

#20704 DOC:Fixed the link on user-guide landing page
  doc/source/reference/index.rst
Labels: 04 - Documentation, 08 - Backport

#20710 TYP: Allow `ndindex` to accept integer tuples
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/index_tricks.pyi
  numpy/typing/tests/data/reveal/index_tricks.pyi
Labels: 03 - Maintenance, 09 - Backport-Candidate, static typing

#20708 DOC: fix broken documentation references in mtrand.pyx
  numpy/random/mtrand.pyx
Labels: 04 - Documentation

#20712 BUG: Restore vc141 support
  numpy/core/src/npymath/npy_math_internal.h.src
Labels: 00 - Bug, component: numpy.core, 09 - Backport-Candidate

#20714 BUG: Restore vc141 support
  numpy/core/src/npymath/npy_math_internal.h.src
Labels: 00 - Bug, component: numpy.core, 08 - Backport

#20719 TYP: change type annotation for `__array_namespace__` to ModuleType
  numpy/array_api/_array_object.py
Labels: 09 - Backport-Candidate, static typing, component: numpy.array_api

#20721 BUG: Fix array dimensions solver for multidimensional arguments in f2py
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/test_crackfortran.py
Labels: 00 - Bug, 06 - Regression, component: numpy.f2py, 09 - Backport-Candidate

#20713 DOC: Add Code of Conduct to README.md
  README.md
Labels: 04 - Documentation

#20720 TYP: add a few type annotations to `numpy.array_api.Array`
  numpy/array_api/_array_object.py
Labels: static typing, component: numpy.array_api

#15006 ENH: add support for operator() in crackfortran.
  doc/release/upcoming_changes/15006.new_feature.rst
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/src/crackfortran/operators.f90
  numpy/f2py/tests/test_crackfortran.py
Labels: 01 - Enhancement, component: numpy.f2py

#20726 TYP, MAINT: Allow `ndindex` to accept integer tuples
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/index_tricks.pyi
  numpy/typing/tests/data/reveal/index_tricks.pyi
Labels: 03 - Maintenance, 08 - Backport, static typing, component: numpy.typing

#20725 TYP: change type annotation for `__array_namespace__` to ModuleType
  numpy/array_api/_array_object.py
Labels: 08 - Backport, static typing, component: numpy.array_api

#20724 BUG: Fix array dimensions solver for multidimensional arguments in f2py
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/test_crackfortran.py
Labels: 00 - Bug, 06 - Regression, component: numpy.f2py, 08 - Backport

#20683 DOC: Updated pointer spacing for consistency.
  doc/source/user/c-info.ufunc-tutorial.rst
Labels: 04 - Documentation

#20730 DOC: Document that dtype, strides, shape attributes should not be set
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation

#20695 BLD: Add NPY_DISABLE_SVML env var to opt out of SVML
  numpy/core/setup.py
Labels: 36 - Build

#20738 ENH: fix a typo in the example trigger for wheels
  .github/workflows/wheels.yml
Labels: 01 - Enhancement

#20729 BUG: Relax dtype identity check in reductions
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_ufunc.py
Labels: 00 - Bug, 59 - Needs tests

#20678 BUG: Remove trailing dec point in dragon4positional
  numpy/core/src/multiarray/dragon4.c
  numpy/core/tests/test_scalarprint.py
Labels: 00 - Bug

#20722 ENH: Removed requirement for C-contiguity when changing to dtype of different size
  doc/release/upcoming_changes/20722.expired.rst
  doc/release/upcoming_changes/20722.new_feature.rst
  numpy/core/_add_newdocs.py
  numpy/core/src/multiarray/getset.c
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_multiarray.py
  numpy/lib/stride_tricks.py
Labels: 01 - Enhancement

#20689 BUG: Added check for NULL data in ufuncs
  doc/source/reference/c-api/ufunc.rst
  numpy/core/src/umath/ufunc_type_resolution.c
  numpy/core/src/umath/umathmodule.c
Labels: 00 - Bug

#20754 MAINT: Relax asserts to match relaxed reducelike resolution behaviour
  numpy/core/src/umath/ufunc_object.c
Labels: 03 - Maintenance, 09 - Backport-Candidate

#20758 DOC: Capitalization and missing word in docs
  doc/source/reference/c-api/ufunc.rst
Labels: 04 - Documentation

#20757 BUG: Relax dtype identity check in reductions
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_ufunc.py
Labels: 00 - Bug, component: numpy.core, 08 - Backport

#20731 DOC: fix OpenBLAS version in release note
  doc/source/release/1.22.0-notes.rst
Labels: 04 - Documentation

#20750 TYP: Allow time manipulation functions to accept `data` and `timedelta` objects
  numpy/__init__.pyi
  numpy/core/multiarray.pyi
  numpy/typing/tests/data/reveal/multiarray.pyi
Labels: 03 - Maintenance, 09 - Backport-Candidate, static typing

#20759 MAINT: Raise RuntimeError if setuptools version is too recent.
  setup.py
Labels: 03 - Maintenance, 09 - Backport-Candidate, 36 - Build

#20763 TYP: Allow time manipulation functions to accept `date` and `timedelta` objects
  numpy/__init__.pyi
  numpy/core/multiarray.pyi
  numpy/typing/tests/data/reveal/multiarray.pyi
Labels: 03 - Maintenance, 08 - Backport, static typing

#20768 TYP: Relax the type of `ndarray.__array_finalize__`
  numpy/__init__.pyi
Labels: 03 - Maintenance, 08 - Backport, static typing

#20776 DOC: fix remaining "easy" doctests errors
  doc/source/user/basics.rec.rst
  doc/source/user/misc.rst
Labels: 04 - Documentation

#20741 DOC: add instructions for cross compilation
  doc/source/user/building.rst
Labels: 04 - Documentation

#20783 DOC: Update Copyright to 2022 [License]
  LICENSE.txt
  doc/source/conf.py
Labels: 04 - Documentation

#20773 BUG: method without self argument should be static
  numpy/core/code_generators/generate_umath.py
Labels: 00 - Bug

#20779 MAINT: removed duplicate 'int' type in ScalarType
  numpy/core/numerictypes.py
  numpy/core/numerictypes.pyi
  numpy/typing/tests/data/pass/numerictypes.py
  numpy/typing/tests/data/reveal/numerictypes.pyi
Labels: 03 - Maintenance

#20643 PERF: Optimize array check for bounded 0,1 values
  numpy/random/_common.pyx
Labels: 06 - Regression, 03 - Maintenance, 09 - Backport-Candidate

#20766 ENH: Make ndarray.__array_finalize__ a callable no-op
  doc/release/upcoming_changes/20766.deprecation.rst
  doc/release/upcoming_changes/20766.improvement.rst
  numpy/__init__.pyi
  numpy/core/_add_newdocs.py
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/getset.c
  numpy/core/src/multiarray/methods.c
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_multiarray.py
  numpy/ma/tests/test_subclassing.py
Labels: 01 - Enhancement, component: numpy.core

#20131 BUG: min/max is slow, re-implement using NEON (#17989)
  .gitignore
  benchmarks/benchmarks/bench_reduce.py
  benchmarks/benchmarks/bench_ufunc_strides.py
  numpy/core/code_generators/generate_umath.py
  numpy/core/setup.py
  numpy/core/src/umath/loops.c.src
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/loops_minmax.dispatch.c.src
  numpy/core/src/umath/simd.inc.src
Labels: 00 - Bug, component: SIMD

#20789 DOC: git:// protocol deprecated by github.
  doc/source/dev/gitwash/following_latest.rst
Labels: 04 - Documentation

#20786 BUG, DOC: Fixes SciPy docs build warnings
  numpy/f2py/symbolic.py
  numpy/f2py/tests/test_symbolic.py
Labels: 00 - Bug

#20792 TST: Bump mypy to 0.931
  environment.yml
  test_requirements.txt
Labels: 05 - Testing, static typing

#20794 TYP: Type the NEP 35 `like` parameter via a `__array_function__` protocol
  numpy/core/_asarray.pyi
  numpy/core/multiarray.pyi
  numpy/core/numeric.pyi
  numpy/lib/npyio.pyi
  numpy/lib/twodim_base.pyi
  numpy/typing/__init__.py
  numpy/typing/_array_like.py
  numpy/typing/tests/data/fail/array_constructors.pyi
  numpy/typing/tests/data/reveal/array_constructors.pyi
Labels: 01 - Enhancement, static typing

#20798 PERF: Optimize array check for bounded 0,1 values
  numpy/random/_common.pyx
Labels: 06 - Regression, 03 - Maintenance, 08 - Backport

#20797 DOC: fix OpenBLAS version in release note
  doc/source/release/1.22.0-notes.rst
Labels: 04 - Documentation, 08 - Backport

#20796 BUG, DOC: Fixes SciPy docs build warnings
  numpy/f2py/symbolic.py
  numpy/f2py/tests/test_symbolic.py
Labels: 00 - Bug, 04 - Documentation, 08 - Backport

#20795 MAINT: Raise RuntimeError if setuptools version is too recent.
  setup.py
Labels: 03 - Maintenance, 08 - Backport, 36 - Build

#20788 BUG: `array_api.argsort(descending=True)` respects relative sort order
  numpy/array_api/_sorting_functions.py
  numpy/array_api/tests/test_sorting_functions.py
Labels: 00 - Bug, 09 - Backport-Candidate

#20793 BUG: Fix that reducelikes honour out always (and live int he future)
  numpy/core/src/umath/ufunc_object.c
Labels: 00 - Bug, 09 - Backport-Candidate

#20762 BUG: Allow integer inputs for pow-related functions in `array_api`
  numpy/array_api/_array_object.py
  numpy/array_api/_elementwise_functions.py
  numpy/array_api/tests/test_array_object.py
  numpy/array_api/tests/test_elementwise_functions.py
Labels: 00 - Bug, 09 - Backport-Candidate, component: numpy.array_api

#20807 BUG: Allow integer inputs for pow-related functions in `array_api`
  numpy/array_api/_array_object.py
  numpy/array_api/_elementwise_functions.py
  numpy/array_api/tests/test_array_object.py
  numpy/array_api/tests/test_elementwise_functions.py
Labels: 00 - Bug, 08 - Backport, component: numpy.array_api

#20784 MAINT, DOC: fix new typos detected by codespell
  doc/RELEASE_WALKTHROUGH.rst.txt
  doc/neps/nep-0005-generalized-ufuncs.rst
  doc/release/upcoming_changes/15006.new_feature.rst
  doc/source/reference/simd/build-options.rst
  numpy/_globals.py
  numpy/core/_add_newdocs.py
  numpy/core/include/numpy/experimental_dtype_api.h
  numpy/core/src/common/simd/vsx/vsx.h
  numpy/core/src/umath/reduction.c
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_api.py
  numpy/distutils/checks/cpu_vxe.c
  numpy/f2py/crackfortran.py
  numpy/lib/npyio.py
  numpy/testing/_private/extbuild.py
Labels: 03 - Maintenance

#20813 MAINT: fix typo
  numpy/core/src/umath/loops_minmax.dispatch.c.src
Labels: 03 - Maintenance

#20811 MAINT, DOC: discard repeated words
  doc/source/dev/gitwash/development_setup.rst
  doc/source/reference/c-api/iterator.rst
  doc/source/reference/c-api/ufunc.rst
  doc/source/reference/random/parallel.rst
  doc/source/reference/swig.interface-file.rst
  doc/source/user/basics.subclassing.rst
  doc/source/user/building.rst
  doc/source/user/c-info.how-to-extend.rst
  numpy/core/_add_newdocs.py
  numpy/core/numeric.py
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/src/multiarray/common.c
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/dtype_transfer.c
  numpy/core/src/multiarray/nditer_constr.c
  numpy/core/src/npymath/npy_math_complex.c.src
  numpy/core/src/umath/dispatching.c
  numpy/core/src/umath/ufunc_type_resolution.c
  numpy/core/tests/test_indexing.py
  numpy/doc/ufuncs.py
  numpy/lib/function_base.py
  numpy/lib/histograms.py
  numpy/lib/nanfunctions.py
  numpy/polynomial/chebyshev.py
  numpy/polynomial/hermite.py
  numpy/polynomial/laguerre.py
  numpy/polynomial/legendre.py
  numpy/random/_common.pyx
  numpy/random/_examples/cython/extending.pyx
  numpy/random/bit_generator.pyx
  numpy/random/tests/test_generator_mt19937.py
  numpy/testing/_private/parameterized.py
  tools/swig/README
  tools/swig/numpy.i
Labels: 04 - Documentation, 03 - Maintenance

#20814 DOC: Refer to NumPy, not pandas, in main page
  doc/source/index.rst
Labels: 00 - Bug, 04 - Documentation, 08 - Backport

#20815 DOC: Update Copyright to 2022 [License]
  LICENSE.txt
  doc/source/conf.py
Labels: 04 - Documentation, 03 - Maintenance, 08 - Backport

#20816 DOC: discard repeated words in NEPs
  doc/neps/nep-0022-ndarray-duck-typing-overview.rst
  doc/neps/nep-0023-backwards-compatibility.rst
  doc/neps/nep-0041-improved-dtype-support.rst
  doc/neps/nep-0042-new-dtypes.rst
  doc/neps/nep-0043-extensible-ufuncs.rst
Labels: 04 - Documentation

#20791 BUG: Return correctly shaped inverse indices in `array_api` set functions
  numpy/array_api/_set_functions.py
  numpy/array_api/tests/test_set_functions.py
Labels: 00 - Bug, 09 - Backport-Candidate

#20819 BUG: Return correctly shaped inverse indices in array_api set functions
  numpy/array_api/_set_functions.py
  numpy/array_api/tests/test_set_functions.py
Labels: 00 - Bug, 08 - Backport, component: numpy.array_api

#20747 BLD: Upload wheel artifacts separately [wheel build]
  .github/workflows/wheels.yml
Labels: 36 - Build

#20818 BUG: Fix build of third-party extensions with Py_LIMITED_API
  numpy/core/include/numpy/ufuncobject.h
  numpy/core/tests/examples/cython/checks.pyx
  numpy/core/tests/examples/cython/setup.py
  numpy/core/tests/examples/limited_api/limited_api.c
  numpy/core/tests/examples/limited_api/setup.py
  numpy/core/tests/test_cython.py
  numpy/core/tests/test_limited_api.py
Labels: 00 - Bug, 05 - Testing, 09 - Backport-Candidate

#20827 TYP: Fix pyright being unable to infer the `real` and `imag` output type
  numpy/__init__.pyi
Labels: 03 - Maintenance, 09 - Backport-Candidate, static typing

#20823 REL: Update main after 1.22.1 release.
  .mailmap
  doc/changelog/1.22.1-changelog.rst
  doc/source/release.rst
  doc/source/release/1.22.1-notes.rst
Labels: 14 - Release, 04 - Documentation

#20732 Convert timsort.c.src to C++
  numpy/core/setup.py
  numpy/core/src/common/numpy_tag.h
  numpy/core/src/npysort/npysort_common.h
  numpy/core/src/npysort/timsort.cpp
Labels: C++

#20833 BUG: Fix comparator function signatures
  numpy/core/src/multiarray/arraytypes.c.src
Labels: 00 - Bug, 09 - Backport-Candidate

#15844 ENH: add inline definition of access rights for Fortran types
  doc/release/upcoming_changes/15844.new_feature.rst
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/src/crackfortran/accesstype.f90
  numpy/f2py/tests/test_crackfortran.py
Labels: 01 - Enhancement, component: numpy.f2py

#20842 BLD: Add NPY_DISABLE_SVML env var to opt out of SVML
  numpy/core/setup.py
Labels: 08 - Backport, 36 - Build

#20843 BUG: Fix build of third-party extensions with Py_LIMITED_API
  numpy/core/include/numpy/ufuncobject.h
  numpy/core/tests/examples/cython/checks.pyx
  numpy/core/tests/examples/cython/setup.py
  numpy/core/tests/examples/limited_api/limited_api.c
  numpy/core/tests/examples/limited_api/setup.py
  numpy/core/tests/test_cython.py
  numpy/core/tests/test_limited_api.py
Labels: 00 - Bug, 05 - Testing, 08 - Backport

#20844 TYP: Fix pyright being unable to infer the `real` and `imag` output type
  numpy/__init__.pyi
Labels: 03 - Maintenance, 08 - Backport, static typing

#20845 BUG: Fix comparator function signatures
  numpy/core/src/multiarray/arraytypes.c.src
Labels: 00 - Bug, 08 - Backport

#20847 MAINT: remove outdated mingw32 fseek support
  numpy/core/include/numpy/npy_common.h
Labels: component: numpy.core, 03 - Maintenance, 09 - Backport-Candidate

#20285 ENH, SIMD: add new universal intrinsics for floor/rint
  numpy/core/src/_simd/_simd.dispatch.c.src
  numpy/core/src/common/simd/avx2/math.h
  numpy/core/src/common/simd/avx512/math.h
  numpy/core/src/common/simd/neon/math.h
  numpy/core/src/common/simd/sse/math.h
  numpy/core/src/common/simd/vsx/math.h
  numpy/core/tests/test_simd.py
Labels: 01 - Enhancement, component: SIMD

#20821 ENH: Add CPU feature detection for POWER10 (VSX4)
  doc/source/reference/simd/generated_tables/cpu_features.inc
  numpy/core/src/common/npy_cpu_features.c.src
  numpy/core/src/common/npy_cpu_features.h
  numpy/core/tests/test_cpu_features.py
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/checks/cpu_vsx4.c
  numpy/distutils/checks/extra_vsx4_mma.c
  numpy/distutils/command/build.py
  numpy/distutils/tests/test_ccompiler_opt.py
Labels: 01 - Enhancement, 56 - Needs Release Note.

#20810 DOC: Restore MaskedArray.hardmask documentation
  numpy/ma/core.py
Labels: 04 - Documentation, component: numpy.ma

#20834 DOC: Update ndarray.argmax + argmin documentation with keepdims param #20700
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation

#20829 MAINT: Translate mergesort.c.src to C++ using templates.
  numpy/core/setup.py
  numpy/core/src/npysort/mergesort.c.src
  numpy/core/src/npysort/mergesort.cpp
Labels: component: numpy.core, 03 - Maintenance, C++

#20851 DOC: Fix typo in meshgrid example
  numpy/lib/function_base.py
Labels: 04 - Documentation

#20854 DEV: Update dependencies and Docker image
  environment.yml
  tools/gitpod/Dockerfile
Labels: 16 - Development

#20857 BUG: Fix pre-builds in Gitpod
  .gitpod.yml
Labels: 00 - Bug

#20397 SIMD: replace raw AVX512 of floor/trunc/rint with universal intrinsics
  numpy/core/code_generators/generate_umath.py
  numpy/core/src/umath/loops.c.src
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/loops_unary_fp.dispatch.c.src
  numpy/core/src/umath/simd.inc.src
Labels: component: SIMD

#20660 MAINT: update OpenBLAS to 0.3.19
  tools/openblas_support.py
Labels: 03 - Maintenance

#20861 DOC: fix formatting of mean example
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#20831 BUG: Avoid importing numpy.distutils on import numpy.testing (#20769)
  numpy/testing/_private/extbuild.py
Labels: 00 - Bug, 09 - Backport-Candidate

#20865 MAINT: Fix inconsistent PyPI casing
  README.md
  doc/changelog/1.12.0-changelog.rst
  doc/changelog/1.20.0-changelog.rst
  doc/neps/nep-0017-split-out-maskedarray.rst
  doc/source/release/1.10.3-notes.rst
  doc/source/release/1.11.1-notes.rst
  doc/source/release/1.12.1-notes.rst
  setup.py
Labels: 03 - Maintenance

#20867 DOC: Cosmetic docstring fix for numpydoc.
  numpy/random/mtrand.pyx
Labels: 04 - Documentation

#20869 DOC: random: Fix spelling of 'precision'.
  doc/source/reference/random/index.rst
  doc/source/reference/random/new-or-different.rst
Labels: 04 - Documentation, component: numpy.random

#20876 DOC: Fixes minor formatting issue related to nested inline markup.
  doc/source/dev/development_workflow.rst
Labels: 04 - Documentation

#20878 DOC,TST: Fix Pandas code example
  doc/source/user/absolute_beginners.rst
Labels: 04 - Documentation

#20866 ENH: Add changes that allow NumPy to compile with clang-cl
  numpy/core/include/numpy/ndarraytypes.h
  numpy/core/include/numpy/npy_common.h
  numpy/core/src/common/simd/intdiv.h
  numpy/core/src/multiarray/common_dtype.c
  numpy/core/src/umath/loops_unary_fp.dispatch.c.src
Labels: 01 - Enhancement, 36 - Build

#20868 BUG: Gitpod Remove lock file --unshallow
  .gitpod.yml
Labels: 00 - Bug

#20858 TYP: Relax the return-type of `np.vectorize`
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/lib_function_base.pyi
Labels: 03 - Maintenance, 09 - Backport-Candidate, static typing

#20745 ENH: add hook and test for PyInstaller.
  numpy/__init__.py
  numpy/_pyinstaller/__init__.py
  numpy/_pyinstaller/hook-numpy.py
  numpy/_pyinstaller/pyinstaller-smoke.py
  numpy/_pyinstaller/test_pyinstaller.py
  numpy/setup.py
  setup.py
  tools/travis-test.sh
Labels: 01 - Enhancement

#20886 BUG: distutils: fix building mixed C/Fortran extensions
  numpy/distutils/command/build_ext.py
Labels: 00 - Bug, component: numpy.distutils, 09 - Backport-Candidate

#20881 BUG: fix f2py's define for threading when building with Mingw
  numpy/f2py/cfuncs.py
Labels: 00 - Bug, component: numpy.f2py, 09 - Backport-Candidate

#20885 TYP,ENH: Improve typing with the help of `ParamSpec`
  numpy/lib/function_base.pyi
  numpy/lib/shape_base.pyi
  numpy/testing/_private/utils.pyi
  numpy/typing/tests/data/fail/testing.pyi
  numpy/typing/tests/data/reveal/testing.pyi
Labels: 01 - Enhancement, static typing, component: numpy.typing

#20887 TYP,MAINT: Add aliases for commonly used unions
  numpy/__init__.pyi
  numpy/core/function_base.pyi
  numpy/core/multiarray.pyi
  numpy/core/numeric.pyi
  numpy/core/numerictypes.pyi
  numpy/core/shape_base.pyi
  numpy/ctypeslib.pyi
  numpy/fft/helper.pyi
  numpy/lib/arraypad.pyi
  numpy/lib/arraysetops.pyi
  numpy/lib/function_base.pyi
  numpy/lib/npyio.pyi
  numpy/lib/shape_base.pyi
  numpy/lib/stride_tricks.pyi
  numpy/lib/twodim_base.pyi
  numpy/lib/type_check.pyi
  numpy/typing/__init__.py
  numpy/typing/_array_like.py
  numpy/typing/_dtype_like.py
  numpy/typing/tests/data/fail/multiarray.pyi
  numpy/typing/tests/data/reveal/array_constructors.pyi
Labels: 03 - Maintenance, static typing, component: numpy.typing

#20874 BUG: mtrand cannot be imported on Cygwin
  numpy/core/include/numpy/random/distributions.h
  numpy/random/setup.py
Labels: 00 - Bug

#20674 BUG: array interface PyCapsule reference
  numpy/core/src/multiarray/ctors.c
  numpy/core/tests/test_array_interface.py
Labels: 00 - Bug, 09 - Backport-Candidate

#20912 DOC,TST: Fix Pandas code example as per new release
  doc/source/user/absolute_beginners.rst
Labels: 04 - Documentation, 08 - Backport

#20906 BUG: Avoid importing numpy.distutils on import numpy.testing
  numpy/testing/_private/extbuild.py
Labels: 00 - Bug, 08 - Backport

#20907 MAINT: remove outdated mingw32 fseek support
  numpy/core/include/numpy/npy_common.h
Labels: component: numpy.core, 03 - Maintenance, 08 - Backport

#20909 BUG: fix f2py's define for threading when building with Mingw
  numpy/f2py/cfuncs.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#20910 BUG: distutils: fix building mixed C/Fortran extensions
  numpy/distutils/command/build_ext.py
Labels: 00 - Bug, component: numpy.distutils, 08 - Backport

#20911 BUG: Fix the return type of random_float_fill
  numpy/random/_common.pxd
Labels: 00 - Bug

#20917 DOC: fix np.ma.flatnotmasked_contiguous docstring
  numpy/ma/extras.py
Labels: 04 - Documentation

#20916 TYP,MAINT: Add annotations for `flatiter.__setitem__`
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/flatiter.pyi
Labels: 03 - Maintenance, 09 - Backport-Candidate, static typing

#20908 TYP: Relax the return-type of np.vectorize
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/lib_function_base.pyi
Labels: 03 - Maintenance, static typing

#20900 TYP,ENH: Add annotations for `np.lib.mixins`
  numpy/lib/mixins.pyi
Labels: 01 - Enhancement, static typing

#20902 TYP,ENH: Add dtype-typing support to `np.core.fromnumeric` (part 1)
  numpy/core/fromnumeric.pyi
  numpy/typing/tests/data/fail/fromnumeric.pyi
  numpy/typing/tests/data/reveal/fromnumeric.pyi
Labels: 01 - Enhancement, static typing

#20918 TYP: Added missing where typehints in fromnumeric.pyi
  numpy/__init__.pyi
  numpy/core/fromnumeric.pyi
Labels: 09 - Backport-Candidate, static typing

#20927 DOC: lib/io.py was renamed to lib/npyio.py
  numpy/lib/npyio.py
Labels: 04 - Documentation

#20934 BUG: Fix build_ext interaction with non-numpy extensions
  numpy/distutils/command/build_ext.py
Labels: 00 - Bug, 09 - Backport-Candidate

#20931 BUG: Fix missing intrinsics for windows/arm64 target
  numpy/core/src/npymath/npy_math_internal.h.src
Labels: 00 - Bug, 09 - Backport-Candidate

#20935 TYP, MAINT: Add annotations for flatiter.__setitem__
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/flatiter.pyi
Labels: 03 - Maintenance, 08 - Backport, static typing

#20936 MAINT, TYP: Added missing where typehints in fromnumeric.pyi
  numpy/__init__.pyi
  numpy/core/fromnumeric.pyi
Labels: 03 - Maintenance, 08 - Backport, static typing

#20937 BUG: Fix build_ext interaction with non numpy extensions
  numpy/distutils/command/build_ext.py
Labels: 00 - Bug, 08 - Backport

#20938 BUG: Fix missing intrinsics for windows/arm64 target
  numpy/core/src/npymath/npy_math_internal.h.src
Labels: 00 - Bug, 08 - Backport

#20944 DOC: improper doc syntax (markdown and imbalanced ticks).
  numpy/core/shape_base.py
  numpy/distutils/ccompiler_opt.py
Labels: 04 - Documentation

#20946 MAINT: Fix typo in setup.py
  numpy/random/setup.py
Labels: 03 - Maintenance

#20948 MAINT, DOC: NEP link update
  doc/neps/conf.py
  doc/neps/nep-0040-legacy-datatype-impl.rst
  doc/neps/nep-0042-new-dtypes.rst
Labels: 04 - Documentation, component: Documentation, 03 - Maintenance, component: NEP

#20835 DEP: Removed deprecated error clearing
  doc/release/upcoming_changes/20835.expired.rst
  numpy/core/src/multiarray/ctors.c
  numpy/core/tests/test_array_coercion.py
  numpy/core/tests/test_deprecations.py
Labels: 07 - Deprecation

#20955 BUG: Fix incorrect return type in reduce without initial value
  numpy/core/src/umath/reduction.c
  numpy/core/tests/test_ufunc.py
Labels: 00 - Bug, 09 - Backport-Candidate
