Repository numpy/numpy, pull requests merged in 2022-04, with the labels that each got.

#20668 TST: Initialize f2py2e tests of the F2PY CLI
  numpy/f2py/rules.py
  numpy/f2py/tests/src/cli/hi77.f
  numpy/f2py/tests/src/cli/hiworld.f90
  numpy/f2py/tests/test_f2py2e.py
Labels: 05 - Testing, component: numpy.f2py

#21227 [Road to C++] numpy/linalg/umath_linalg.c.src conversion
  numpy/linalg/setup.py
  numpy/linalg/umath_linalg.cpp
Labels: C++

#21287 MAINT: Use C++ inline and include files in C++ files.
  numpy/core/src/multiarray/textreading/tokenize.cpp
  numpy/core/src/npysort/binsearch.cpp
  numpy/core/src/npysort/radixsort.cpp
  numpy/core/src/npysort/selection.cpp
  numpy/core/src/npysort/timsort.cpp
  numpy/core/src/npysort/x86-qsort.dispatch.cpp
  numpy/core/tests/data/generate_umath_validation_data.cpp
  numpy/linalg/umath_linalg.cpp
Labels: 03 - Maintenance, C++

#21286 DOC: double backticks and links
  doc/source/dev/index.rst
Labels: 04 - Documentation

#21290 DOC: Improve documentation formatting
  numpy/lib/function_base.py
  numpy/lib/histograms.py
Labels: 04 - Documentation

#21269 DOC: Improve "random.generator.shuffle" docs page
  doc/source/reference/random/generator.rst
  numpy/random/_generator.pyx
Labels: 04 - Documentation

#21260 Add a document that enumerates the differences between numpy and numpy.array_api
  doc/source/reference/array_api.rst
  doc/source/reference/index.rst
  numpy/array_api/_array_object.py
  numpy/array_api/_data_type_functions.py
  numpy/array_api/_sorting_functions.py
  numpy/array_api/linalg.py
Labels: component: Documentation, component: numpy.array_api

#21295 MAINT: Clean-up includes of auto-generated umath code
  numpy/core/src/common/umathmodule.h
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/umath/umathmodule.c
Labels: component: numpy.core, 03 - Maintenance

#21291 DOC: Add space after argument name
  numpy/core/code_generators/generate_umath.py
  numpy/distutils/ccompiler.py
  numpy/distutils/ccompiler_opt.py
  numpy/lib/format.py
  numpy/lib/function_base.py
  numpy/lib/npyio.py
  numpy/ma/core.py
  numpy/random/_pickle.py
Labels: 04 - Documentation

#21307 MAINT: bump versions in Github actions configuration to v3.
  .github/workflows/build_test.yml
  .github/workflows/cygwin.yml
  .github/workflows/docker.yml
  .github/workflows/gitpod.yml
  .github/workflows/wheels.yml
Labels: 03 - Maintenance

#17709 BUG: Fix norm type promotion
  doc/release/upcoming_changes/17709.compatibility.rst
  numpy/linalg/linalg.py
  numpy/linalg/tests/test_linalg.py
Labels: 00 - Bug, component: numpy.linalg, Triaged

#21315 DOC: a typo fix
  numpy/random/mtrand.pyx
Labels: 04 - Documentation, 03 - Maintenance

#21314 DOC: various spell checks and typo fixes
  benchmarks/benchmarks/bench_linalg.py
  doc/C_STYLE_GUIDE.rst.txt
  doc/EXAMPLE_DOCSTRING.rst.txt
  doc/neps/nep-0002-warnfix.rst
  doc/neps/nep-0009-structured_array_extensions.rst
  doc/neps/nep-0012-missing-data.rst
  doc/neps/nep-0017-split-out-maskedarray.rst
  doc/neps/nep-0024-missing-data-2.rst
  doc/neps/nep-0027-zero-rank-arrarys.rst
  doc/neps/nep-0031-uarray.rst
  doc/neps/nep-0038-SIMD-optimizations.rst
  doc/neps/tools/build_index.py
  doc/source/dev/howto-docs.rst
  doc/source/glossary.rst
  doc/source/reference/random/new-or-different.rst
  doc/source/reference/simd/how-it-works.rst
  doc/source/user/basics.broadcasting.rst
  doc/source/user/basics.interoperability.rst
  doc/source/user/basics.rec.rst
Labels: 04 - Documentation

#21318 REV: Revert pull request #20464 from charris/backport-20354
  numpy/core/setup.py
Labels: 34 - Reversion

#21323 REL: Prepare for NumPy 1.21.6 release.
  .circleci/config.yml
  azure-pipelines.yml
  doc/changelog/1.21.6-changelog.rst
  doc/source/conf.py
  doc/source/release/1.21.6-notes.rst
  doc/source/user/absolute_beginners.rst
Labels: 14 - Release

#21331 REL: Update main after 1.21.6 release.
  doc/changelog/1.21.6-changelog.rst
  doc/source/release.rst
  doc/source/release/1.21.6-notes.rst
Labels: 14 - Release

#21330 DOC: Add F2PY tests documentation
  doc/source/f2py/code/add-test.f
  doc/source/f2py/f2py-reference.rst
  doc/source/f2py/f2py-testing.rst
Labels: 04 - Documentation, component: numpy.f2py

#21345 TYP: Let `ndarray` fancy indexing always return an `ndarray`
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/ndarray_misc.pyi
Labels: 01 - Enhancement, static typing

#21347 MAINT: Fix failing simd and cygwin tests.
  .github/workflows/build_test.yml
  .github/workflows/cygwin.yml
Labels: 03 - Maintenance, 09 - Backport-Candidate

#21349 MAINT: Update setup-cygwin to v3 again.
  .github/workflows/cygwin.yml
Labels: 03 - Maintenance, component: CI

#21350 MAINT: Fix failing simd and cygwin tests.
  .github/workflows/build_test.yml
  .github/workflows/cygwin.yml
Labels: 03 - Maintenance, 08 - Backport, component: CI

#21355 MAINT: Remove the reference to the “good first issue” label
  README.md
Labels: 03 - Maintenance

#21133 DOC: Note interop from "subclassing" docs and explain when to avoid
  doc/source/user/basics.interoperability.rst
  doc/source/user/basics.subclassing.rst
Labels: 04 - Documentation

#21348 DEV: reverted misplaced install of "esbonio".
  .gitpod.yml
Labels: 16 - Development

#21354 ENH: Improve `np.kron` performance
  doc/release/upcoming_changes/21354.performance.rst
  numpy/lib/shape_base.py
Labels: 01 - Enhancement

#21356 DOC: Fix a typo in docstring of MT19937
  numpy/random/_mt19937.pyx
Labels: 04 - Documentation

#21285 BLD: Bump cibuildwheel and enable more PyPy
  .github/workflows/wheels.yml
  .travis.yml
  pyproject.toml
Labels: 36 - Build

#21032 DOC: fix sphinx errors due to np.emath references
  doc/source/reference/routines.emath.rst
  numpy/core/code_generators/ufunc_docstrings.py
Labels: 04 - Documentation

#20669 CI, TST: Run Cygwin CI with Netlib reference BLAS and re-enable linalg tests
  .github/workflows/cygwin.yml
  numpy/linalg/tests/test_linalg.py
Labels: Triaged

#21368 MAINT: Fix failing Python 3.8 32-bit Windows test.
  azure-pipelines.yml
Labels: 03 - Maintenance, 09 - Backport-Candidate, component: CI

#21360 MAINT: Add compile flag to disable voltbl on MSVC 142
  numpy/core/setup.py
Labels: 03 - Maintenance

#21372 BUG: Allow legacy dtypes to cast to datetime again
  numpy/core/src/multiarray/convert_datatype.c
Labels: 00 - Bug, 09 - Backport-Candidate

#21321 BUG: Stop using PyBytesObject.ob_shash deprecated in Python 3.11, fixes #21317.
  numpy/core/src/multiarray/scalarapi.c
Labels: 00 - Bug, 09 - Backport-Candidate

#21366 BUG: fix compilation error for VS 141 and earlier
  numpy/core/src/npysort/x86-qsort.dispatch.cpp
Labels: 00 - Bug

#21324 BUG: Make mmap handling safer in frombuffer
  numpy/core/_add_newdocs.py
  numpy/core/src/multiarray/ctors.c
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug, 09 - Backport-Candidate

#21382 DOC: non-orphan page, and casing.
  doc/source/user/index.rst
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation

#21388 MAINT: be sure to match base and docker images
  .github/workflows/build_test.yml
Labels: 03 - Maintenance

#21392 BUG: add linux guard per #21386
  numpy/core/src/common/npy_cpu_features.c.src
Labels: 00 - Bug, 09 - Backport-Candidate

#21124 ENH,SIMD: Vectorize modulo/divide using the universal intrinsics (VSX4)
  numpy/core/code_generators/generate_umath.py
  numpy/core/setup.py
  numpy/core/src/umath/loops.c.src
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/loops_arithmetic.dispatch.c.src
  numpy/core/src/umath/loops_modulo.dispatch.c.src
Labels: 01 - Enhancement, component: SIMD

#21367 MAINT: Translate ieee754.c.src to C++ using templates.
  numpy/core/include/numpy/utils.h
  numpy/core/setup.py
  numpy/core/src/npymath/ieee754.cpp
  setup.py
Labels: 03 - Maintenance, C++

#21187 ENH: F2PY build output determinism
  doc/release/upcoming_changes/21187.new_feature.rst
  doc/source/f2py/buildtools/index.rst
  doc/source/f2py/buildtools/meson.rst
  doc/source/f2py/code/meson.build
  doc/source/f2py/code/meson_upd.build
  doc/source/f2py/usage.rst
  numpy/f2py/f2py2e.py
  numpy/f2py/rules.py
Labels: 01 - Enhancement

#21407 MAINT: Reduce f2py verbiage for valid parameters
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/test_return_real.py
Labels: component: numpy.f2py, 03 - Maintenance

#21415 BUG: Fix handling of skip-empty-wrappers
  numpy/f2py/f2py2e.py
  numpy/f2py/tests/test_return_real.py
  numpy/f2py/tests/test_semicolon_split.py
Labels: 00 - Bug, component: numpy.f2py

#21413 DOC: Secure PR template URLs [ci skip]
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 00 - Bug, 04 - Documentation
