Repository numpy/numpy, pull requests merged in 2022-08, with the labels that each got.

#22071 MAINT: fix typo in test_array_object.py
  numpy/array_api/tests/test_array_object.py
Labels: 03 - Maintenance

#22078 ENH: reorder includes for testing on top of system installations of NumPy
  numpy/testing/_private/extbuild.py
Labels: 01 - Enhancement, 08 - Backport

#21954 TST: Add tests for FP16 umath functions
  numpy/core/tests/test_umath.py
  numpy/core/tests/test_umath_accuracy.py
Labels: 05 - Testing

#22096 PERF: Improve intrinsics for tobits and pack on Apple silicon
  numpy/core/src/common/simd/neon/conversion.h
Labels: 03 - Maintenance

#22083 BUG: Fix skip condition for test_loss_of_precision[complex256]
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, 09 - Backport-Candidate

#22099 TST: Remove workaround for gh-9968 from `test_scalar_methods.test_roundtrip`
  numpy/core/tests/test_scalar_methods.py
Labels: 05 - Testing

#22105 TST: fix test_linear_interpolation_formula_symmetric
  numpy/lib/tests/test_function_base.py
Labels: 05 - Testing

#22106 TST: fix test_linear_interpolation_formula_symmetric
  numpy/lib/tests/test_function_base.py
Labels: 05 - Testing, 08 - Backport

#21976 ENH: Add the capability to swap the singleton bit generator
  doc/release/upcoming_changes/21976.new_feature.rst
  numpy/random/__init__.pyi
  numpy/random/mtrand.pyi
  numpy/random/mtrand.pyx
  numpy/random/tests/test_randomstate.py
  numpy/typing/tests/data/pass/random.py
  numpy/typing/tests/data/reveal/random.pyi
Labels: 01 - Enhancement

#22110 BUG: Address failures in aarch64 gcc builds due to #22096
  numpy/core/src/common/simd/neon/conversion.h
Labels: 00 - Bug

#22111 BUG: Missed a case in the diff merge for #22110
  numpy/core/src/common/simd/neon/conversion.h
Labels: 00 - Bug

#22112 MAINT: remove redundant reversal of eigenvalues order in svd path
  numpy/linalg/linalg.py
Labels: 03 - Maintenance

#22102 BLD: Try building python3.11 wheels.
  .github/workflows/wheels.yml
Labels: 36 - Build

#21152 DOC: verifying bug existence and fixes - replacement for PR 17851
  doc/source/user/how-to-verify-bug.rst
  doc/source/user/howtos_index.rst
  tools/refguide_check.py
Labels: 04 - Documentation

#22115 BLD: Build python3.11.0rc1 wheels.
  .github/workflows/wheels.yml
Labels: 08 - Backport, 36 - Build

#22120 DOC: Explain spawn_key a little more.
  numpy/random/bit_generator.pyx
Labels: 04 - Documentation, component: numpy.random

#22118 DOC: Fix documentation for percentile and quantile
  numpy/lib/function_base.py
Labels: 04 - Documentation

#22127 BLD: Add Python 3.11 wheels to aarch64 build
  .travis.yml
Labels: 09 - Backport-Candidate, 36 - Build

#22124 DEV: supporting IBM i system
  numpy/distutils/ccompiler.py
  numpy/distutils/fcompiler/__init__.py
  numpy/distutils/fcompiler/gnu.py
Labels: 16 - Development, 09 - Backport-Candidate

#22132 DOC: Add a release note for bit generator reduce changes
  doc/release/upcoming_changes/22014.improvement.rst
Labels: 04 - Documentation

#22130 MAINT: Update main after 1.23.2 release.
  doc/changelog/1.23.2-changelog.rst
  doc/source/release.rst
  doc/source/release/1.23.2-notes.rst
Labels: 03 - Maintenance

#22136 BLD: Add Python 3.11 wheels to aarch64 build
  .travis.yml
Labels: 08 - Backport, 36 - Build

#22116 MAINT,DOC: Remove sphinx-panels in favor of sphinx-design
  doc/source/_static/numpy.css
  doc/source/conf.py
  doc/source/index.rst
  doc/source/reference/arrays.interface.rst
  doc/source/user/basics.interoperability.rst
  doc/source/user/how-to-how-to.rst
  doc/source/user/quickstart.rst
  doc_requirements.txt
  environment.yml
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation, 03 - Maintenance

#22144 DOC: Add missing word
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#22143 MAINT: Update the RELEASE_WALKTHROUGH file.
  doc/RELEASE_WALKTHROUGH.rst
Labels: 03 - Maintenance

#22142 MAINT: Update setup.py for Python 3.11.
  setup.py
Labels: 03 - Maintenance, 09 - Backport-Candidate

#22148 MAINT: Update setup.py for Python 3.11.
  setup.py
Labels: 03 - Maintenance, 08 - Backport

#22122 DOC: Explain how to use sequences of integers as seeds.
  doc/source/reference/random/index.rst
  doc/source/reference/random/parallel.rst
Labels: 04 - Documentation, component: numpy.random

#22149 DOC: Copy-edit the 'partition' docstring.
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#22043 BLD: use macos-11 image on azure, macos-1015 is deprecated
  azure-pipelines.yml
Labels: 03 - Maintenance, 36 - Build

#22117 DOC: Reorganize user guide outline
  doc/source/bugs.rst
  doc/source/dev/depending_on_numpy.rst
  doc/source/dev/index.rst
  doc/source/dev/underthehood.rst
  doc/source/user/basics.rst
  doc/source/user/byteswapping.rst
  doc/source/user/index.rst
  doc/source/user/misc.rst
Labels: 04 - Documentation

#22150 CI: Test NumPy build against old versions of GCC(6, 7, 8)
  .github/workflows/build_test.yml
  INSTALL.rst
  doc/source/user/building.rst
  numpy/core/src/common/simd/avx512/arithmetic.h
  numpy/core/src/npysort/x86-qsort.dispatch.cpp
Labels: 00 - Bug, 09 - Backport-Candidate, component: SIMD, 36 - Build

#22155 CI: Test NumPy build against old versions of GCC(6, 7, 8)
  .github/workflows/build_test.yml
  INSTALL.rst.txt
  doc/source/user/building.rst
  numpy/core/src/common/simd/avx512/arithmetic.h
  numpy/core/src/npysort/x86-qsort.dispatch.cpp
Labels: 03 - Maintenance, 08 - Backport, component: SIMD, 36 - Build

#22156 MAINT: support IBM i system
  numpy/distutils/ccompiler.py
  numpy/distutils/fcompiler/__init__.py
  numpy/distutils/fcompiler/gnu.py
Labels: 03 - Maintenance, 08 - Backport

#22139 DEP: drop support for msvc<=1900 and Interix
  doc/release/upcoming_changes/22139.expired.rst
  numpy/core/include/numpy/npy_math.h
  numpy/core/setup.py
  numpy/core/src/common/npy_config.h
  numpy/random/src/pcg64/pcg64.h
Labels: 07 - Deprecation

#21468 ENH: Use `threadpoolctl` in `show_runtime` (a new function)
  doc/release/upcoming_changes/21468.new_feature.rst
  doc/source/reference/routines.other.rst
  numpy/lib/utils.py
  numpy/tests/test_public_api.py
Labels: 01 - Enhancement

#22159 DEP: drop older cygwin compatibility shims
  doc/release/upcoming_changes/22159.expired.rst
  numpy/core/src/common/npy_config.h
Labels: 07 - Deprecation

#22154 DOC: add more prominent warnings to pin setuptools
  doc/source/dev/depending_on_numpy.rst
  doc/source/reference/distutils.rst
Labels: 04 - Documentation, component: numpy.distutils

#22090 MAINT: Simplify npymath
  azure-pipelines.yml
  numpy/core/include/numpy/npy_math.h
  numpy/core/setup.py
  numpy/core/setup_common.py
  numpy/core/src/_simd/_simd.h
  numpy/core/src/common/npy_config.h
  numpy/core/src/common/numpyos.c
  numpy/core/src/multiarray/common.h
  numpy/core/src/npymath/ieee754.c.src
  numpy/core/src/npymath/ieee754.cpp
  numpy/core/src/npymath/npy_math_internal.h.src
  numpy/core/src/umath/_umath_tests.c.src
  numpy/core/src/umath/umathmodule.c
Labels: 03 - Maintenance, component: npy_math

#22169 MAINT: fix defines for universal2 python builds of NumPy
  numpy/core/include/numpy/numpyconfig.h
  numpy/core/setup.py
Labels: 03 - Maintenance

#22152 BUG: Support using libunwind for backtrack
  numpy/core/setup_common.py
  numpy/core/src/multiarray/temp_elide.c
  numpy/linalg/umath_linalg.cpp
Labels: 00 - Bug

#22179 TST: Implemented an unused test for np.random.randint
  numpy/random/tests/test_random.py
Labels: 05 - Testing

#22189 MAINT: fix an incorrect pointer type usage in f2py
  numpy/f2py/cfuncs.py
Labels: component: numpy.f2py, 03 - Maintenance, 09 - Backport-Candidate
