Repository numpy/numpy, pull requests merged in 2022-09, with the labels that each got.

#22194 BUG: Fix circleci build
  .circleci/config.yml
  doc_requirements.txt
  release_requirements.txt
Labels: 00 - Bug, component: CI

#22195 BUG: Fix circleci build
  .circleci/config.yml
  doc_requirements.txt
  release_requirements.txt
Labels: 00 - Bug, 08 - Backport, component: CI

#22199 MAINT: Unpin towncrier
  doc_requirements.txt
  pyproject.toml
Labels: 03 - Maintenance

#22024 BUG: Expose string_heapsort algorithm in a shared header
  numpy/core/src/npysort/heapsort.cpp
  numpy/core/src/npysort/npysort_heapsort.h
  numpy/core/src/npysort/quicksort.cpp
Labels: 00 - Bug, component: numpy.core, 09 - Backport-Candidate, C++

#22009 BUG: fix np.average for Fraction elements
  numpy/lib/function_base.py
  numpy/lib/tests/test_function_base.py
Labels: 00 - Bug, component: numpy.lib

#22205 DOC: Clarify that `like` is not passed to `function`
  numpy/core/numeric.py
Labels: 04 - Documentation

#22206 DOC: Fix typo disutils -> distutils in numpy.distutils migration page
  doc/source/reference/distutils_status_migration.rst
Labels: 04 - Documentation

#22171 DOC: Note symmetry requirement in `multivariate_normal` error
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
Labels: 00 - Bug, 04 - Documentation

#22210 DOC: Fix typos in cast warning release note
  doc/release/upcoming_changes/21437.improvement.rst
Labels: 04 - Documentation

#22193 BUG: change overloads to play nice with pyright.
  numpy/_typing/__init__.py
  numpy/_typing/_array_like.py
  numpy/core/numeric.pyi
Labels: 00 - Bug, Static typing

#22216 MAINT: fix an incorrect pointer type usage in f2py
  numpy/f2py/cfuncs.py
Labels: component: numpy.f2py, 03 - Maintenance, 08 - Backport

#22215 BUG: Support using libunwind for backtrack
  numpy/core/setup_common.py
  numpy/core/src/multiarray/temp_elide.c
  numpy/linalg/umath_linalg.cpp
Labels: 00 - Bug, 08 - Backport

#22212 TYP,BUG: Reduce argument validation in C-based `__class_getitem__`
  numpy/core/src/multiarray/methods.c
  numpy/core/src/multiarray/scalartypes.c.src
  numpy/core/tests/test_arraymethod.py
  numpy/core/tests/test_scalar_methods.py
Labels: 00 - Bug, 09 - Backport-Candidate, Static typing

#22204 TST,BUG: Use fork context to fix MacOS savez test
  numpy/lib/tests/test_io.py
Labels: 00 - Bug, 05 - Testing, 09 - Backport-Candidate

#22220 BUG: change overloads to play nice with pyright.
  numpy/_typing/__init__.py
  numpy/_typing/_array_like.py
  numpy/core/numeric.pyi
Labels: 00 - Bug, 08 - Backport, Static typing

#22221 TST,BUG: Use fork context to fix MacOS savez test
  numpy/lib/tests/test_io.py
Labels: 00 - Bug, 05 - Testing, 08 - Backport

#22222 TYP,BUG: Reduce argument validation in C-based ``__class_getitem__``
  numpy/core/src/multiarray/methods.c
  numpy/core/src/multiarray/scalartypes.c.src
  numpy/core/tests/test_arraymethod.py
  numpy/core/tests/test_scalar_methods.py
Labels: 00 - Bug, 08 - Backport, Static typing

#21981 TST: ensure `np.equal.reduce` raises a `TypeError`
  numpy/core/src/umath/dispatching.c
  numpy/core/tests/test_ufunc.py
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, 05 - Testing, 09 - Backport-Candidate, triage review

#21928 BUG: Fix the implementation of numpy.array_api.vecdot
  numpy/array_api/linalg.py
Labels: 00 - Bug, 09 - Backport-Candidate, triage review

#21995 BUG: Distinguish exact vs. equivalent dtype for C type aliases.
  doc/release/upcoming_changes/21995.compatibility.rst
  numpy/array_api/tests/test_asarray.py
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/ma/tests/test_core.py
Labels: 00 - Bug

#22223 TST: ensure ``np.equal.reduce`` raises a ``TypeError``
  numpy/core/src/umath/dispatching.c
  numpy/core/tests/test_ufunc.py
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, 05 - Testing, 08 - Backport

#22224 BUG: Fix the implementation of numpy.array_api.vecdot
  numpy/array_api/linalg.py
Labels: 00 - Bug, 08 - Backport, component: numpy.array_api

#22227 DOC: fix up release note
  doc/release/upcoming_changes/21995.compatibility.rst
Labels: 04 - Documentation

#21507 BUG: Better report integer division overflow
  numpy/core/src/umath/loops_modulo.dispatch.c.src
  numpy/core/src/umath/scalarmath.c.src
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, 09 - Backport-Candidate, triage review

#22230 BUG: Better report integer division overflow (backport)
  numpy/core/src/umath/loops_arithmetic.dispatch.c.src
  numpy/core/src/umath/loops_modulo.dispatch.c.src
  numpy/core/src/umath/scalarmath.c.src
  numpy/core/tests/test_regression.py
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, 08 - Backport

#22236 BUG: Fix incorrect refcounting in new `asarray` path
  numpy/core/src/multiarray/multiarraymodule.c
Labels: 00 - Bug

#22228 MAINT: Remove long deprecated functionality from np.ma
  doc/release/upcoming_changes/22228.expired.rst
  numpy/ma/core.py
  numpy/ma/tests/test_deprecations.py
Labels: component: numpy.ma, 03 - Maintenance, 56 - Needs Release Note.

#22242 BLD: add back stdlib.h include in pcg64.h
  numpy/random/src/pcg64/pcg64.h
Labels: 36 - Build

#22245 MAINT: random: remove `get_info` from "extending with Cython" example
  numpy/random/_examples/cython/setup.py
Labels: 04 - Documentation, component: numpy.random, 03 - Maintenance

#22239 MAINT: Update main after 1.23.3 release.
  .mailmap
  doc/changelog/1.23.3-changelog.rst
  doc/source/release.rst
  doc/source/release/1.23.3-notes.rst
Labels: 03 - Maintenance

#22253 DOC: Update concatenate exception message.
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/tests/test_shape_base.py
Labels: 04 - Documentation

#22251 TST: Move new `asarray` test to a more appropriate place.
  numpy/array_api/tests/test_asarray.py
  numpy/core/tests/test_array_coercion.py
Labels: 05 - Testing

#22240 ENH: Use SVML for fp32 and fp64 power and arctan2
  benchmarks/benchmarks/bench_ufunc.py
  numpy/core/code_generators/generate_umath.py
  numpy/core/src/common/npy_svml.h
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/loops_umath_fp.dispatch.c.src
  numpy/core/tests/test_umath.py
Labels: 01 - Enhancement

#22282 DOC: Add example for find
  numpy/core/defchararray.py
Labels: 04 - Documentation

#22304 DOC: default_rng cleanup
  numpy/random/mtrand.pyx
Labels: 04 - Documentation, component: numpy.random

#22298 DOC: add example for ma.unique function
  numpy/ma/extras.py
Labels: 04 - Documentation

#22279 DOC: Add example to msort docstring
  numpy/lib/function_base.py
Labels: 04 - Documentation

#22296 BUG: Memory leaks in numpy.nested_iters
  numpy/core/src/multiarray/nditer_pywrap.c
Labels: 00 - Bug, component: numpy.core

#22272 MAINT, Haiku defines neither __STDC_NO_THREADS__ nor __GLIBC__
  numpy/core/include/numpy/npy_os.h
  numpy/f2py/cfuncs.py
Labels: 03 - Maintenance

#22263 DOC: Clarified how finfo works with complex numbers (#22260)
  numpy/core/getlimits.py
Labels: 04 - Documentation

#22295 DOC: Added an example for isupper() function
  numpy/core/defchararray.py
Labels: 04 - Documentation

#22276 DOC: Update for return value of np.ptp()
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#22294 DOC: add examples to np.char.multiply
  numpy/core/defchararray.py
Labels: 04 - Documentation

#22309 DOC: Correct usage example for np.char.decode docstring
  numpy/core/defchararray.py
Labels: 04 - Documentation

#22285 DOC: Add `isupper` examples
  numpy/core/defchararray.py
Labels: 04 - Documentation

#22259 DOC: Better report integer division overflow (#21506)
  doc/release/upcoming_changes/21506.change.rst
Labels: 04 - Documentation

#22291 DOC: Add examples for isdigit and str_len
  numpy/core/defchararray.py
Labels: 04 - Documentation

#22312 MAINT, TST: Shorten test output on travis builds
  tools/travis-test.sh
Labels: 05 - Testing, 03 - Maintenance

#22314 MAINT: Shorten wheel test output on travis builds
  tools/wheels/cibw_test_command.sh
Labels: 03 - Maintenance, component: CI

#22256 DOC: Add C API example for NPY_ITER_MULTI_INDEX
  doc/source/reference/c-api/iterator.rst
Labels: 04 - Documentation

#22321 MAINT: core: Fix a typo in a datetime error message.
  numpy/core/src/multiarray/datetime.c
Labels: 03 - Maintenance

#22324 MAINT: update function's __module__ attribute in deprecate
  numpy/lib/tests/test_utils.py
  numpy/lib/utils.py
Labels: 03 - Maintenance

#22327 BUG: Fix complex vector dot with more than NPY_CBLAS_CHUNK elements
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug, 09 - Backport-Candidate

#22319 TST: add functional tests for kron
  numpy/lib/tests/test_shape_base.py
Labels: 05 - Testing

#22332 DOC: Minor typo in docs
  doc/source/user/c-info.python-as-glue.rst
Labels: 04 - Documentation

#22306 ENH: Implement essential intrinsics required by the upcoming SIMD optimizations(0)
  numpy/core/src/_simd/_simd.dispatch.c.src
  numpy/core/src/common/simd/avx2/math.h
  numpy/core/src/common/simd/avx2/misc.h
  numpy/core/src/common/simd/avx2/operators.h
  numpy/core/src/common/simd/avx512/arithmetic.h
  numpy/core/src/common/simd/avx512/math.h
  numpy/core/src/common/simd/avx512/misc.h
  numpy/core/src/common/simd/avx512/operators.h
  numpy/core/src/common/simd/neon/math.h
  numpy/core/src/common/simd/neon/misc.h
  numpy/core/src/common/simd/neon/operators.h
  numpy/core/src/common/simd/simd.h
  numpy/core/src/common/simd/sse/math.h
  numpy/core/src/common/simd/sse/misc.h
  numpy/core/src/common/simd/sse/operators.h
  numpy/core/src/common/simd/vec/math.h
  numpy/core/src/common/simd/vec/misc.h
  numpy/core/src/common/simd/vec/operators.h
  numpy/core/src/npysort/x86-qsort.dispatch.cpp
  numpy/core/src/umath/loops_minmax.dispatch.c.src
  numpy/core/tests/test_simd.py
Labels: 01 - Enhancement, component: SIMD

#22326 CI, SIMD: Test and build without the support of AVX2 and AVX512
  .github/workflows/build_test.yml
  tools/travis-test.sh
Labels: component: CI, component: SIMD

#22336 MAINT: Rm numpydoc remnant example docstring.
  doc/example.py
Labels: 04 - Documentation

#22325 SIMD: Improve the performance of NEON vector initializer
  numpy/core/src/common/simd/neon/misc.h
Labels: 01 - Enhancement, component: SIMD

#22280 DOC: updated the description for array-like type in histogramdd (#19823)
  numpy/lib/histograms.py
Labels: 04 - Documentation

#22300 DOC: examples for `np.char.isdecimal` and `np.char.isnumeric`
  numpy/core/defchararray.py
Labels: 04 - Documentation, component: numpy.core

#22292 DOC: Add copyto example
  numpy/core/multiarray.py
Labels: 04 - Documentation

#22331 DOC: Adding examples to `ma.max` function
  numpy/ma/core.py
Labels: 04 - Documentation

#22334 DOC: Added missing dtype attribute to `iinfo` and `finfo` docstring
  numpy/core/getlimits.py
Labels: 04 - Documentation

#22297 DOC: Add example to np.prod
  numpy/core/fromnumeric.py
Labels: 04 - Documentation, component: numpy.core

#21955 ENH: Vectorize FP16 umath functions using AVX512
  benchmarks/benchmarks/bench_ufunc_strides.py
  numpy/core/code_generators/generate_umath.py
  numpy/core/setup.py
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/loops_umath_fp.dispatch.c.src
Labels: 01 - Enhancement, component: SIMD

#22342 MAINT: update sde toolkit to 9.0, fix download link
  .github/workflows/build_test.yml
Labels: 03 - Maintenance

#22344 DOC: fixed minor typo in percentile docstring
  numpy/lib/function_base.py
Labels: 04 - Documentation

#22254 DOC: Improve `converters` parameter description for loadtxt
  numpy/lib/npyio.py
Labels: 04 - Documentation

#22343 DOC: fixed two more typos in docstrings
  numpy/lib/nanfunctions.py
Labels: 04 - Documentation

#22354 MAINT: switch sponsor link from numfocus to opencollective
  .github/CODE_OF_CONDUCT.md
  .github/FUNDING.yml
Labels: 03 - Maintenance

#22147 DOC: fix linalg.tensorsolve docstring
  numpy/linalg/linalg.py
Labels: 04 - Documentation

#22308 DOC: add examples to numpy.char.replace
  numpy/core/defchararray.py
Labels: 04 - Documentation, component: numpy.core
