Repository numpy/numpy, pull requests merged in 2022-10, with the labels that each got.

#22362 DOC: Updated amin/amax output dimensions for tuple axis
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#22356 REV: Loosen `lookfor`'s import try/except again
  numpy/lib/utils.py
Labels: 09 - Backport-Candidate, 34 - Reversion

#22357 TYP,ENH: Mark `numpy.typing` protocols as runtime checkable
  doc/release/upcoming_changes/22357.improvement.rst
  numpy/_typing/_array_like.py
  numpy/_typing/_dtype_like.py
  numpy/_typing/_nested_sequence.py
  numpy/typing/tests/test_runtime.py
Labels: 01 - Enhancement, 09 - Backport-Candidate, Static typing

#22302 DOC: Change in the documentation for chebpts2 method
  numpy/polynomial/chebyshev.py
Labels: 04 - Documentation

#22358 ENH,TYP: Add special casing for `ndarray`-based indexing
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/ndarray_misc.pyi
Labels: 01 - Enhancement, Static typing

#22360 TST,TYP: Bump mypy to 0.981
  environment.yml
  numpy/typing/tests/data/fail/scalars.pyi
  numpy/typing/tests/data/reveal/ctypeslib.pyi
  numpy/typing/tests/data/reveal/flatiter.pyi
  pytest.ini
  test_requirements.txt
Labels: 05 - Testing, 09 - Backport-Candidate, Static typing

#22365 BUG: Add `__array_api_version__` to `numpy.array_api` namespace
  numpy/array_api/__init__.py
Labels: 00 - Bug, 09 - Backport-Candidate

#22370 MAINT: update sde toolkit to 9.0, fix download link
  .github/workflows/build_test.yml
Labels: 03 - Maintenance, 08 - Backport

#22368 BUG: Add ``__array_api_version__`` to ``numpy.array_api`` namespace
  numpy/array_api/__init__.py
Labels: 00 - Bug, 08 - Backport

#22359 TYP,MAINT: Change more overloads to play nice with pyright
  numpy/__init__.pyi
  numpy/_typing/__init__.py
Labels: 03 - Maintenance, 09 - Backport-Candidate, Static typing

#22363 DOC: Added examples to `maa.min` function
  numpy/ma/core.py
Labels: 04 - Documentation

#22374 DOC: typo additional colon in beginners tutorial
  doc/source/user/absolute_beginners.rst
Labels: 04 - Documentation

#22372 DOC: Update delimiter param description.
  numpy/lib/npyio.py
Labels: 04 - Documentation

#22046 BUG: Make `mask_invalid` consistent with `mask_where` if `copy` is set to `False`
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
Labels: 00 - Bug

#20321 ENH: allow NumPy created .npy files to be appended in-place
  numpy/lib/format.py
  numpy/lib/tests/test_format.py
Labels: 01 - Enhancement, triaged

#22382 BLD: use macos-11 image on azure, macos-1015 is deprecated
  azure-pipelines.yml
Labels: 03 - Maintenance, 08 - Backport, 36 - Build

#22383 MAINT: random: remove ``get_info`` from "extending with Cython" example
  numpy/random/_examples/cython/setup.py
Labels: 04 - Documentation, component: numpy.random, 03 - Maintenance, 08 - Backport

#22384 BUG: Fix complex vector dot with more than NPY_CBLAS_CHUNK elements
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug, 08 - Backport

#22387 REV: Loosen ``lookfor``'s import try/except again
  numpy/lib/utils.py
Labels: 08 - Backport, 34 - Reversion

#22388 TYP,ENH: Mark ``numpy.typing`` protocols as runtime checkable
  doc/release/upcoming_changes/22357.improvement.rst
  numpy/_typing/_array_like.py
  numpy/_typing/_dtype_like.py
  numpy/_typing/_nested_sequence.py
  numpy/typing/tests/test_runtime.py
Labels: 01 - Enhancement, 08 - Backport, Static typing

#22389 TYP,MAINT: Change more overloads to play nice with pyright
  numpy/__init__.pyi
  numpy/_typing/__init__.py
Labels: 03 - Maintenance, 08 - Backport, Static typing

#22390 TST,TYP: Bump mypy to 0.981
  environment.yml
  numpy/typing/tests/data/fail/scalars.pyi
  numpy/typing/tests/data/reveal/ctypeslib.pyi
  numpy/typing/tests/data/reveal/flatiter.pyi
  pytest.ini
  test_requirements.txt
Labels: 05 - Testing, 08 - Backport, Static typing

#22391 DOC: Update delimiter param description.
  numpy/lib/npyio.py
Labels: 04 - Documentation, 08 - Backport

#22161 MAINT: simplify complex math function handling in npymath
  numpy/core/feature_detection_cmath.h
  numpy/core/setup.py
  numpy/core/setup_common.py
  numpy/core/src/npymath/npy_math_complex.c.src
Labels: 03 - Maintenance

#22392 BUG: Memory leaks in numpy.nested_iters
  numpy/core/src/multiarray/nditer_pywrap.c
Labels: 00 - Bug, component: numpy.core, 08 - Backport

#22393 MAINT: Ensure graceful handling of large header sizes
  numpy/lib/format.py
  numpy/lib/npyio.py
  numpy/lib/tests/test_format.py
  numpy/lib/utils.py
Labels: 03 - Maintenance, 09 - Backport-Candidate

#22313 DEP: Deprecate fastCopyAndTranspose
  doc/release/upcoming_changes/22313.deprecation.rst
  numpy/core/_add_newdocs.py
  numpy/core/multiarray.py
  numpy/core/numeric.py
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/tests/test_api.py
  numpy/linalg/linalg.py
  numpy/tests/test_public_api.py
Labels: 07 - Deprecation, triaged

#22398 DOC: Update broken link to diataxis framework.
  doc/neps/nep-0044-restructuring-numpy-docs.rst
Labels: 04 - Documentation

#22399 MAINT: Fix typos found by codespell
  doc/neps/nep-0050-scalar-promotion.rst
  doc/release/upcoming_changes/21437.improvement.rst
  doc/source/dev/development_workflow.rst
  doc/source/f2py/windows/conda.rst
  doc/source/f2py/windows/index.rst
  doc/source/f2py/windows/pgi.rst
  doc/source/reference/array_api.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/security.rst
  numpy/__init__.pyi
  numpy/_pyinstaller/pyinstaller-smoke.py
  numpy/core/include/numpy/ndarraytypes.h
  numpy/core/src/common/simd/avx2/math.h
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/flagsobject.c
  numpy/core/src/multiarray/hashdescr.c
  numpy/core/src/multiarray/textreading/conversions.c
  numpy/core/src/multiarray/textreading/field_types.h
  numpy/core/src/multiarray/textreading/rows.c
  numpy/core/src/npysort/x86-qsort.dispatch.cpp
  numpy/core/src/umath/loops_hyperbolic.dispatch.c.src
  numpy/core/src/umath/scalarmath.c.src
  numpy/core/tests/test_array_interface.py
  numpy/core/tests/test_multiarray.py
  numpy/core/tests/test_scalarmath.py
  numpy/core/tests/test_umath.py
  numpy/f2py/src/fortranobject.c
  numpy/lib/tests/test_io.py
  numpy/random/_generator.pyx
  setup.cfg
  tools/ci/push_docs_to_repo.py
Labels: 03 - Maintenance

#22401 MAINT: fix obsolete code comment
  setup.py
Labels: 03 - Maintenance

#22407 DOC: Fix title level for release note improvements
  doc/release/upcoming_changes/21807.improvement.rst
  doc/release/upcoming_changes/22014.improvement.rst
Labels: 04 - Documentation

#22421 DOC: Replace CObject with Capsule consistently
  doc/source/f2py/python-usage.rst
  doc/source/reference/c-api/array.rst
  doc/source/user/c-info.beyond-basics.rst
  numpy/f2py/cfuncs.py
Labels: 04 - Documentation

#22379 ENH: allow explicit `like=None` in all array creation functions
  numpy/core/multiarray.pyi
  numpy/core/src/multiarray/arrayfunction_override.c
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/tests/test_multiarray.py
  numpy/core/tests/test_overrides.py
Labels: 01 - Enhancement

#22385 DEP: Deprecate conversion of out-of-bound Python integers
  doc/release/upcoming_changes/22393.deprecation.rst
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/arraytypes.h.src
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_array_coercion.py
  numpy/core/tests/test_casting_unittests.py
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_dtype.py
  numpy/core/tests/test_einsum.py
  numpy/core/tests/test_getlimits.py
  numpy/core/tests/test_multiarray.py
  numpy/core/tests/test_numeric.py
  numpy/core/tests/test_regression.py
  numpy/core/tests/test_scalar_ctors.py
  numpy/core/tests/test_scalarmath.py
  numpy/core/tests/test_umath.py
  numpy/f2py/tests/test_return_complex.py
  numpy/f2py/tests/test_return_logical.py
  numpy/f2py/tests/test_return_real.py
  numpy/ma/core.py
Labels: 07 - Deprecation

#22418 TST, BLD: Fix failing aarch64 wheel builds.
  numpy/core/tests/test_multiarray.py
  tools/wheels/cibw_test_command.sh
Labels: 05 - Testing, 09 - Backport-Candidate, 36 - Build

#22424 TST: Fix failing aarch64 wheel builds.
  numpy/core/tests/test_multiarray.py
  tools/wheels/cibw_test_command.sh
Labels: 05 - Testing, 08 - Backport

#22425 REL: Prepare for the NumPy 1.23.4 release (1)
  doc/changelog/1.23.4-changelog.rst
  doc/source/release/1.23.4-notes.rst
Labels: 14 - Release

#22419 MAINT: Remove PyCObject from the SWIG interface
  tools/swig/numpy.i
Labels: 03 - Maintenance

#22430 MAINT: Update main after 1.23.4 release.
  doc/RELEASE_WALKTHROUGH.rst
  doc/changelog/1.23.4-changelog.rst
  doc/source/release.rst
  doc/source/release/1.23.4-notes.rst
Labels: 03 - Maintenance

#22406 DOC: Add changelog for ``masked_invalid`` change.
  doc/release/upcoming_changes/22046.change.rst
Labels: 04 - Documentation

#22432 MAINT: always use sys.base_prefix, never use sys.real_prefix
  numpy/distutils/mingw32ccompiler.py
Labels: 03 - Maintenance

#22440 MAINT: fix typo in f2c_lapack.c
  numpy/linalg/lapack_lite/f2c_lapack.c
Labels: 03 - Maintenance

#22441 MAINT,DOC: Revert "MAINT: fix typo in f2c_lapack.c"
  numpy/linalg/lapack_lite/f2c_lapack.c
Labels: 03 - Maintenance

#22438 MAINT: Update versioneer 0.19 → 0.26
  numpy/_version.py
  tools/lint_diff.ini
  versioneer.py
Labels: 03 - Maintenance, 36 - Build

#22409 DOC: Adopt a harmonic color scheme with the dark mode of pydata-sphinx-theme
  doc/source/_static/numpy.css
Labels: 04 - Documentation

#22447 TYP: Spelling alignment for array flag literal
  numpy/core/multiarray.pyi
Labels: Static typing

#21875 ENH: Implement correct scalar and integer overflow errors for NEP 50
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/dtypemeta.h
  numpy/core/src/umath/scalarmath.c.src
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_mem_overlap.py
  numpy/core/tests/test_nep50_promotions.py
  numpy/random/bit_generator.pyx
  numpy/typing/tests/data/pass/ndarray_misc.py
Labels: 01 - Enhancement

#22453 DOC: Update NEP 50 text since integer conversion errors now exist.
  doc/neps/nep-0050-scalar-promotion.rst
Labels: 04 - Documentation

#22442 ENH: unstructured_to_structured converts dtype argument
  numpy/lib/recfunctions.py
  numpy/lib/tests/test_recfunctions.py
Labels: 01 - Enhancement

#21853 DOC: Update the docstring for np.around
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#22168 ENH: Remove AVX related functions from non x86 based builds
  numpy/core/setup.py
  numpy/core/setup_common.py
  numpy/core/src/umath/loops.c.src
Labels: 01 - Enhancement, component: SIMD

#16507 BUG: Do not allow nditer to reduce the mask
  numpy/core/src/multiarray/nditer_constr.c
  numpy/core/tests/test_nditer.py
Labels: 00 - Bug, component: numpy.core

#22463 DOC: remove mention of `ipython -p numpy`.
  numpy/__init__.py
Labels: 04 - Documentation

#22456 DEP: Proposal to deprecate the `msort` convenience function
  doc/release/upcoming_changes/22456.deprecation.rst
  doc/source/reference/routines.sort.rst
  numpy/lib/function_base.py
  numpy/lib/tests/test_function_base.py
Labels: 07 - Deprecation

#22462 MAINT: refactor mandatory npymath functions to #define macros
  numpy/core/include/numpy/npy_math.h
  numpy/core/setup_common.py
  numpy/core/src/npymath/ieee754.cpp
  numpy/core/src/npymath/npy_math_internal.h.src
Labels: 03 - Maintenance

#22458 ENH: Allow all allocated operands in nditer/NpyIter
  doc/release/upcoming_changes/22457.change.rst
  numpy/core/src/multiarray/nditer_constr.c
  numpy/core/tests/test_nditer.py
Labels: 01 - Enhancement

#22433 DOC: remove reference to Python 2
  numpy/distutils/command/config.py
Labels: 04 - Documentation

#22466 MAINT: Ensure that fmin loops do not show up multiple times
  numpy/core/code_generators/generate_umath.py
Labels: 03 - Maintenance

#22450 BUG: Fix boundschecking for random.logseries
  numpy/random/_common.pxd
  numpy/random/_common.pyx
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
  numpy/random/tests/test_generator_mt19937.py
  numpy/random/tests/test_randomstate.py
Labels: 00 - Bug, component: numpy.random, 09 - Backport-Candidate

#22475 MAINT: remove code specific to Python 2
  numpy/_globals.py
Labels: 03 - Maintenance

#22480 DOC: fix typo in advanced_debugging.rst [skip ci]
  doc/source/dev/development_advanced_debugging.rst
Labels: 04 - Documentation

#22479 MAINT: remove u-prefix for former Unicode strings
  benchmarks/benchmarks/bench_io.py
  doc/neps/conf.py
  numpy/core/tests/test_api.py
  numpy/core/tests/test_arrayprint.py
  numpy/core/tests/test_defchararray.py
  numpy/core/tests/test_dtype.py
  numpy/core/tests/test_einsum.py
  numpy/core/tests/test_multiarray.py
  numpy/core/tests/test_nditer.py
  numpy/core/tests/test_numerictypes.py
  numpy/core/tests/test_overrides.py
  numpy/core/tests/test_regression.py
  numpy/core/tests/test_scalarinherit.py
  numpy/core/tests/test_ufunc.py
  numpy/core/tests/test_unicode.py
  numpy/lib/tests/test_arraypad.py
  numpy/lib/tests/test_format.py
  numpy/lib/tests/test_io.py
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
  numpy/ma/tests/test_regression.py
Labels: 03 - Maintenance

#22487 TST,MAINT: Replace most setup with setup_method (also teardown)
  doc/TESTS.rst
  numpy/core/tests/test_arrayprint.py
  numpy/core/tests/test_defchararray.py
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_half.py
  numpy/core/tests/test_indexing.py
  numpy/core/tests/test_memmap.py
  numpy/core/tests/test_multiarray.py
  numpy/core/tests/test_numeric.py
  numpy/core/tests/test_numerictypes.py
  numpy/core/tests/test_overrides.py
  numpy/core/tests/test_records.py
  numpy/core/tests/test_umath.py
  numpy/core/tests/test_umath_complex.py
  numpy/distutils/tests/test_ccompiler_opt.py
  numpy/distutils/tests/test_ccompiler_opt_conf.py
  numpy/distutils/tests/test_exec_command.py
  numpy/distutils/tests/test_system_info.py
  numpy/f2py/tests/test_assumed_shape.py
  numpy/f2py/tests/util.py
  numpy/lib/tests/test__datasource.py
  numpy/lib/tests/test_function_base.py
  numpy/lib/tests/test_histograms.py
  numpy/lib/tests/test_io.py
  numpy/lib/tests/test_recfunctions.py
  numpy/ma/tests/test_core.py
  numpy/ma/tests/test_extras.py
  numpy/ma/tests/test_mrecords.py
  numpy/ma/tests/test_old_ma.py
  numpy/ma/tests/test_subclassing.py
  numpy/matrixlib/tests/test_masked_matrix.py
  numpy/random/tests/test_generator_mt19937.py
  numpy/random/tests/test_random.py
  numpy/random/tests/test_randomstate.py
  numpy/testing/tests/test_utils.py
Labels: 05 - Testing, 09 - Backport-Candidate

#22488 MAINT, CI: Switch to cygwin/cygwin-install-action@v2
  .github/workflows/cygwin.yml
Labels: 03 - Maintenance, 09 - Backport-Candidate, component: CI

#22489 TST, MAINT: Replace most setup with setup_method (also teardown)
  doc/TESTS.rst.txt
  numpy/core/tests/test_arrayprint.py
  numpy/core/tests/test_defchararray.py
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_half.py
  numpy/core/tests/test_indexing.py
  numpy/core/tests/test_memmap.py
  numpy/core/tests/test_multiarray.py
  numpy/core/tests/test_numeric.py
  numpy/core/tests/test_numerictypes.py
  numpy/core/tests/test_overrides.py
  numpy/core/tests/test_records.py
  numpy/core/tests/test_umath.py
  numpy/core/tests/test_umath_complex.py
  numpy/distutils/tests/test_ccompiler_opt.py
  numpy/distutils/tests/test_ccompiler_opt_conf.py
  numpy/distutils/tests/test_exec_command.py
  numpy/distutils/tests/test_system_info.py
  numpy/f2py/tests/test_assumed_shape.py
  numpy/f2py/tests/util.py
  numpy/lib/tests/test__datasource.py
  numpy/lib/tests/test_function_base.py
  numpy/lib/tests/test_histograms.py
  numpy/lib/tests/test_io.py
  numpy/lib/tests/test_recfunctions.py
  numpy/ma/tests/test_core.py
  numpy/ma/tests/test_extras.py
  numpy/ma/tests/test_mrecords.py
  numpy/ma/tests/test_old_ma.py
  numpy/ma/tests/test_subclassing.py
  numpy/matrixlib/tests/test_masked_matrix.py
  numpy/random/tests/test_generator_mt19937.py
  numpy/random/tests/test_random.py
  numpy/random/tests/test_randomstate.py
  numpy/testing/tests/test_utils.py
Labels: 05 - Testing, 03 - Maintenance, 08 - Backport

#22491 TST: Make cygwin build run for branches.
  .github/workflows/cygwin.yml
Labels: 05 - Testing

#22483 MAINT: change subprocess arguments from Python>=3.7
  benchmarks/asv_pip_nopep517.py
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/exec_command.py
  numpy/distutils/lib2def.py
  numpy/distutils/misc_util.py
  numpy/f2py/__init__.py
  setup.py
Labels: 03 - Maintenance

#22490 MAINT, CI: Switch to cygwin/cygwin-install-action@v2
  .github/workflows/cygwin.yml
Labels: 03 - Maintenance, component: CI

#22485 TST: Make test_partial_iteration_cleanup robust but require leak checker
  numpy/core/tests/test_nditer.py
Labels: 05 - Testing, 09 - Backport-Candidate

#22494 TST: Make test_partial_iteration_cleanup robust but require leak checker
  numpy/core/tests/test_nditer.py
Labels: 05 - Testing, 08 - Backport

#22505 DOC: fixed minor typo in f2py docs
  doc/source/f2py/buildtools/index.rst
Labels: 04 - Documentation

#22500 DOC: added example in char
  doc/source/reference/routines.char.rst
Labels: 04 - Documentation
