Repository numpy/numpy, pull requests merged in 2023-04, with the labels that each got.

#23504 DOC: Remove doc for non-existing `PyArray_XDECREF_ERR`
  doc/source/reference/c-api/array.rst
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/core/src/multiarray/ctors.c
Labels: 04 - Documentation

#23498 MAINT: improve error when a dtype doesn't support the buffer interface
  numpy/core/src/multiarray/buffer.c
Labels: 03 - Maintenance

#23509 DOC: Fix a structure in `NPY_TYPES`
  doc/source/reference/c-api/dtype.rst
Labels: 04 - Documentation

#23516 DOC: add missing punctuation in a C API .rst file
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#23521 ENH: Raise C++ standard to C++17
  meson.build
  numpy/core/setup.py
  numpy/core/src/npymath/npy_math_private.h
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/command/build_clib.py
  numpy/distutils/command/build_ext.py
  numpy/linalg/setup.py
  setup.py
Labels: 01 - Enhancement

#23495 BUG: fix loading and storing big arrays on s390x
  numpy/core/src/common/simd/vec/memory.h
  numpy/core/tests/test_ufunc.py
Labels: 00 - Bug

#23357 ENH: ``__repr__`` for NpzFile object
  doc/release/upcoming_changes/23357.improvement.rst
  numpy/lib/npyio.py
  numpy/lib/npyio.pyi
  numpy/lib/tests/test_io.py
Labels: 01 - Enhancement, component: numpy.lib

#23544 MAINT: Bump larsoner/circleci-artifacts-redirector-action
  .github/workflows/circleci.yml
Labels: 03 - Maintenance, 08 - Backport, component: CI

#23543 BUG: fix loading and storing big arrays on s390x
  numpy/core/src/common/simd/vec/memory.h
  numpy/core/tests/test_ufunc.py
Labels: 00 - Bug, 08 - Backport, component: SIMD

#23519 DOC: Fix a reference to built-in `len` in `char.str_len` docstring
  numpy/core/defchararray.py
Labels: 04 - Documentation, component: numpy.core

#23549 DOC: Fix incorrect operators for member access in `array.rst`
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#23553 DOC: Fix description of `PyArray_DiscardWritebackIfCopy`
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#23551 BLD: fix instances of MSVC detection in `meson.build`
  numpy/core/meson.build
  numpy/meson.build
Labels: 00 - Bug, 36 - Build, Meson

#23558 DOC: Fix missing punctuation in `array.rst`
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#23555 DEP: deprecate np.math and np.lib.math
  numpy/__init__.py
  numpy/core/tests/test_deprecations.py
  numpy/lib/__init__.py
Labels: 07 - Deprecation

#23560 DOC: Fix parameter type of `PyArray_DiscardWritebackIfCopy`
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#23562 DOC: Fix document structure of `PyUfuncObject`
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#23565 DOC: Add directive for C-type `PyArrayMapIterObject`
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#23559 BLD: add static to std_c_flags program. Move macosx_arm64 wheel build to cirrus. Add regular macosx_arm64 job (closes #23538, #21765)
  .cirrus.star
  .github/workflows/wheels.yml
  numpy/distutils/ccompiler.py
  numpy/f2py/crackfortran.py
  pyproject.toml
  setup.py
  tools/ci/cirrus_macosx_arm64.yml
  tools/ci/cirrus_wheels.yml
  tools/wheels/cibw_before_build.sh
  tools/wheels/gfortran_utils.sh
Labels: 36 - Build

#23393 DOC: Add Examples for np.ma.right_shift
  numpy/ma/core.py
Labels: 04 - Documentation

#23382 DOC: fixing a typo in polynomial roots Doc & cross-referencing domain #23374
  numpy/polynomial/_polybase.py
Labels: 04 - Documentation

#23569 TST: try readding test_new_policy on musl
  numpy/core/tests/test_mem_policy.py
Labels: 05 - Testing

#23440 BUG: accept zeros on numpy.random dirichlet function
  numpy/random/_generator.pyx
  numpy/random/tests/test_randomstate.py
Labels: 00 - Bug

#23568 MAINT: remove usages of sys.exc_info
  numpy/f2py/diagnose.py
Labels: 03 - Maintenance

#23275 ENH: Modify `np.logspace` so that the `base` argument broadcasts against `start` and `stop`
  doc/release/upcoming_changes/23275.improvement.rst
  numpy/core/function_base.py
  numpy/core/tests/test_function_base.py
Labels: 01 - Enhancement, component: numpy.core

#23578 CI: fix Circle CI doc build html preview link
  .github/workflows/circleci.yml
Labels: component: CI

#23530 DOC: Add example for Polynomial.degree().
  numpy/polynomial/_polybase.py
Labels: 04 - Documentation

#23584 DOC: Remove descriptions of non-existent C-types
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#23010 BENCH: Add coverage for remaining array_api operations
  benchmarks/benchmarks/bench_core.py
  benchmarks/benchmarks/bench_creation.py
  benchmarks/benchmarks/bench_lib.py
  benchmarks/benchmarks/bench_linalg.py
  benchmarks/benchmarks/bench_manipulate.py
  benchmarks/benchmarks/bench_reduce.py
  benchmarks/benchmarks/bench_ufunc.py
  benchmarks/benchmarks/common.py
Labels: 28 - Benchmark

#23587 DOC: Fix module name of `autoattribute` in maskedarray document
  doc/source/reference/maskedarray.baseclass.rst
Labels: 04 - Documentation

#23593 BUG: lib: Tiny fix for the loadtxt tokenizer when PyMem_Malloc() fails.
  numpy/core/src/multiarray/textreading/tokenize.cpp
Labels: 00 - Bug, component: numpy.lib, C++

#23594 DOC: Refactor description of `PyArray_Descr`
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#21785 BUG: fix `_selected_real_kind_func` return values for macOS on arm64
  .github/workflows/build_test.yml
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/test_kind.py
Labels: 00 - Bug, component: numpy.f2py

#23596 MAINT: Update conftest for newer hypothesis versions
  numpy/conftest.py
Labels: 05 - Testing

#23597 MAINT: Fix broken links in site.cfg.example
  site.cfg.example
Labels: 03 - Maintenance

#23601 BLD: use the C++ linker to link `_multiarray_umath.so`
  doc/release/upcoming_changes/23601.change.rst
  numpy/core/setup.py
Labels: component: numpy.core, 03 - Maintenance, 36 - Build

#23604 BUG, BLD: Fix indentation bug in distutils
  numpy/distutils/command/build_ext.py
Labels: 00 - Bug, 36 - Build

#23605 DOC: pull tags and initialize submodules in development install insructions
  doc/source/dev/index.rst
Labels: 04 - Documentation

#23557 ENH: Use threshold also inside SubArrayFormat.
  numpy/core/arrayprint.py
  numpy/core/tests/test_arrayprint.py
Labels: 01 - Enhancement, component: numpy.core

#23617 DOC: Use correct fill_value instead of value for np.full in 1.24.0 note
  doc/source/release/1.24.0-notes.rst
Labels: 04 - Documentation

#23591 ENH: refactor zero-filling and expose dtype API slot for it
  numpy/core/include/numpy/_dtype_api.h
  numpy/core/src/multiarray/common.c
  numpy/core/src/multiarray/common.h
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/dtype_traversal.c
  numpy/core/src/multiarray/dtype_traversal.h
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/src/multiarray/dtypemeta.h
  numpy/core/src/multiarray/getset.c
  numpy/core/src/multiarray/refcount.c
  numpy/core/src/multiarray/refcount.h
Labels: 01 - Enhancement

#23602 BUG: Add packaging to benchmark dependencies
  benchmarks/asv.conf.json
  benchmarks/asv_compare.conf.json.tpl
Labels: 00 - Bug

#10615 DEP: deprecate scalar conversions for arrays with ndim > 0
  doc/release/upcoming_changes/10615.deprecation.rst
  numpy/core/function_base.py
  numpy/core/src/multiarray/common.c
  numpy/core/src/multiarray/common.h
  numpy/core/src/multiarray/methods.c
  numpy/core/src/multiarray/number.c
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_multiarray.py
Labels: component: numpy.core, 07 - Deprecation, 62 - Python API, triage review

#23627 BUG: Ignore invalid and overflow warnings in masked setitem
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
Labels: 00 - Bug, 09 - Backport-Candidate

#23470 BUG: Fix bug in parsing F77 style string arrays.
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/src/string/scalar_string.f90
  numpy/f2py/tests/test_character.py
Labels: 00 - Bug, component: numpy.f2py, 09 - Backport-Candidate

#23636 MAINT: Update conftest for newer hypothesis versions
  numpy/conftest.py
Labels: 03 - Maintenance, 08 - Backport

#23639 DOC: Fix incorrectly formatted roles in c-api document
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#23634 BUG: Ignore invalid and overflow warnings in masked setitem
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
Labels: 00 - Bug, 08 - Backport

#23637 BUG: Fix bug in parsing F77 style string arrays.
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/src/string/scalar_string.f90
  numpy/f2py/tests/test_character.py
Labels: 00 - Bug, 08 - Backport

#23631 DOC: Clarify that defining NPY_NO_DEPRECATED_API does not determine ABI compatibility
  doc/source/reference/c-api/deprecations.rst
Labels: 04 - Documentation

#23585 DOC: np.random index reorganization
  doc/source/reference/random/bit_generators/index.rst
  doc/source/reference/random/compatibility.rst
  doc/source/reference/random/index.rst
  doc/source/reference/random/legacy.rst
  doc/source/reference/random/new-or-different.rst
Labels: 04 - Documentation, component: numpy.random

#23640 DOC: Downgrade sphinx version to 5
  doc_requirements.txt
Labels: 04 - Documentation

#23644 MAINT: Update main after 1.24.3 release.
  .mailmap
  doc/changelog/1.24.3-changelog.rst
  doc/source/release.rst
  doc/source/release/1.24.3-notes.rst
Labels: 03 - Maintenance

#23650 DOC: Corrects scalar string documentation in regards to trailing null…
  numpy/core/_add_newdocs_scalars.py
Labels: 04 - Documentation

#23298 ENH: Extend the functionlty of C++ type `np::Half`
  numpy/core/meson.build
  numpy/core/setup.py
  numpy/core/src/common/common.hpp
  numpy/core/src/common/float_status.hpp
  numpy/core/src/common/half.hpp
  numpy/core/src/common/half_private.hpp
  numpy/core/src/common/npdef.hpp
  numpy/core/src/common/npstd.hpp
  numpy/core/src/common/utils.hpp
  numpy/core/src/npymath/halffloat.c
  numpy/core/src/npymath/halffloat.cpp
Labels: 01 - Enhancement

#23658 MAINT: allow sphinx6, sync with conda environment.yml
  doc_requirements.txt
Labels: 03 - Maintenance

#23660 DEP: Finalize checking for sequence-like if something is array-like
  doc/release/upcoming_changes/23660.expired.rst
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/tests/test_array_coercion.py
  numpy/core/tests/test_deprecations.py
Labels: 07 - Deprecation

#23657 DOC: Improve description of skip commands for CI
  doc/source/dev/development_workflow.rst
Labels: 04 - Documentation

#23668 DOC: add release note for npzfile membership test
  doc/release/upcoming_changes/23661.performance.rst
Labels: 04 - Documentation

#23358 API: Add DType classes into new `numpy.dtypes` module
  doc/release/upcoming_changes/23358.improvement.rst
  doc/source/reference/routines.other.rst
  numpy/__init__.py
  numpy/core/__init__.py
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/arraytypes.h.src
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/src/multiarray/dtypemeta.h
  numpy/core/src/multiarray/scalartypes.c.src
  numpy/core/src/multiarray/usertypes.c
  numpy/core/tests/test_dtype.py
  numpy/dtypes.py
  numpy/dtypes.pyi
  numpy/meson.build
  numpy/tests/test_public_api.py
Labels: 30 - API, 62 - Python API

#23666 DEP,BUG: Finalize subarray dtype FutureWarning and fix its assignment
  doc/release/upcoming_changes/23666.expired.rst
  numpy/core/src/multiarray/arrayobject.c
  numpy/core/src/multiarray/convert.c
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/ctors.h
  numpy/core/src/multiarray/dtype_transfer.c
  numpy/core/src/multiarray/einsum.c.src
  numpy/core/src/multiarray/getset.c
  numpy/core/src/multiarray/mapping.c
  numpy/core/src/multiarray/methods.c
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/multiarray/shape.c
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_array_coercion.py
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_ufunc.py
Labels: 07 - Deprecation

#23677 MAINT: bump website theme version
  doc_requirements.txt
  environment.yml
  numpy/dtypes.py
Labels: 03 - Maintenance

#22493 MAINT: remove redundant open() modes and io.open() alias
  doc/postprocess.py
  doc/preprocess.py
  doc/source/reference/simd/gen_features.py
  numpy/core/code_generators/genapi.py
  numpy/core/tests/test_cpu_features.py
  numpy/core/tests/test_longdouble.py
  numpy/distutils/ccompiler.py
  numpy/distutils/command/build_ext.py
  numpy/distutils/command/build_src.py
  numpy/distutils/command/install.py
  numpy/distutils/fcompiler/ibm.py
  numpy/distutils/misc_util.py
  numpy/distutils/system_info.py
  numpy/distutils/tests/test_system_info.py
  numpy/f2py/capi_maps.py
  numpy/linalg/lapack_lite/clapack_scrub.py
  numpy/linalg/lapack_lite/make_lite.py
  numpy/testing/_private/utils.py
  numpy/typing/tests/test_typing.py
  runtests.py
  setup.py
  tools/cythonize.py
  tools/openblas_support.py
  tools/wheels/check_license.py
Labels: 03 - Maintenance

#18053 ENH: Adding Object dtype to einsum
  doc/release/upcoming_changes/18053.new_feature.rst
  numpy/core/src/multiarray/convert.c
  numpy/core/src/multiarray/einsum.c.src
  numpy/core/src/multiarray/einsum_sumprod.c.src
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/tests/test_einsum.py
  numpy/core/tests/test_regression.py
Labels: 01 - Enhancement

#23528 ENH: Allow, and default to, downstream building with old API
  doc/release/upcoming_changes/23528.compatibility.rst
  doc/source/dev/depending_on_numpy.rst
  doc/source/dev/reviewer_guidelines.rst
  numpy/core/code_generators/cversions.txt
  numpy/core/code_generators/genapi.py
  numpy/core/code_generators/numpy_api.py
  numpy/core/include/numpy/arrayscalars.h
  numpy/core/include/numpy/ndarraytypes.h
  numpy/core/include/numpy/numpyconfig.h
  numpy/core/include/numpy/ufuncobject.h
  numpy/core/meson.build
  numpy/core/setup_common.py
  numpy/core/tests/test_mem_policy.py
Labels: 01 - Enhancement

#23489 DOC: Fixing incorrect sentence - Boolean array indexing #23377
  doc/source/user/basics.indexing.rst
Labels: 04 - Documentation

#23129 TST: add tests for numpy.quantile
  numpy/lib/tests/test_function_base.py
Labels: 05 - Testing

#23600 BUG: Infer return types for Fortran functions in `f2py`
  doc/source/f2py/code/ftype.f
  numpy/f2py/crackfortran.py
  numpy/f2py/func2subr.py
  numpy/f2py/tests/src/crackfortran/gh23598.f90
  numpy/f2py/tests/src/crackfortran/gh23598Warn.f90
  numpy/f2py/tests/test_crackfortran.py
  numpy/f2py/tests/test_f2py2e.py
Labels: 00 - Bug, component: numpy.f2py

#23680 BUG: Fix masked array ravel order for A (and somewhat K)
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
Labels: 00 - Bug, 09 - Backport-Candidate

#23684 DOC: Fix return type of `PyArray_EinsteinSum`
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation
