Repository numpy/numpy, pull requests merged in 2023-09, with the labels that each got.

#24607 DOC: Fix import find_common_type warning[skip actions][skip cirrus][s…
  doc/source/reference/routines.dtype.rst
Labels: 04 - Documentation

#24578 API: Update `lib.polynomial` and `lib.npyio` namespaces
  doc/source/reference/routines.io.rst
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_expired_attrs_2_0.py
  numpy/core/tests/test_deprecations.py
  numpy/lib/__init__.py
  numpy/lib/__init__.pyi
  numpy/lib/_datasource.py
  numpy/lib/_npyio_impl.py
  numpy/lib/_npyio_impl.pyi
  numpy/lib/_polynomial_impl.py
  numpy/lib/_polynomial_impl.pyi
  numpy/lib/npyio.py
  numpy/lib/npyio.pyi
  numpy/lib/tests/test_io.py
  numpy/tests/test_public_api.py
  numpy/typing/tests/data/fail/datasource.pyi
  numpy/typing/tests/data/reveal/datasource.pyi
  numpy/typing/tests/data/reveal/npyio.pyi
  tools/refguide_check.py
Labels: 30 - API, Numpy 2.0 API Changes

#24573 DOC: Update building docs to use Meson
  INSTALL.rst
  benchmarks/README.rst
  building_with_meson.md
  doc/RELEASE_WALKTHROUGH.rst
  doc/TESTS.rst
  doc/source/dev/development_environment.rst
  doc/source/dev/howto_build_docs.rst
  doc/source/dev/index.rst
  doc/source/user/building.rst
Labels: 04 - Documentation, 09 - Backport-Candidate, Meson

#24581 API: Update `lib.index_tricks` namespace
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/core/tests/test_function_base.py
  numpy/lib/__init__.py
  numpy/lib/__init__.pyi
  numpy/lib/_arraypad_impl.py
  numpy/lib/_index_tricks_impl.py
  numpy/lib/_index_tricks_impl.pyi
  numpy/lib/_shape_base_impl.py
  numpy/lib/tests/test_index_tricks.py
  numpy/ma/extras.py
  numpy/tests/test_public_api.py
Labels: 30 - API, Numpy 2.0 API Changes

#24611 TYP: Add the missing `casting` keyword to `np.clip`
  numpy/core/fromnumeric.pyi
Labels: 09 - Backport-Candidate, Static typing

#24612 DOC: Replace "cube cube-root" with "cube root" in cbrt docstring
  numpy/core/code_generators/ufunc_docstrings.py
Labels: 04 - Documentation

#24606 BUG: Change Cython ``binding`` directive to "False".
  numpy/random/_generator.pyx
  numpy/random/_mt19937.pyx
  numpy/random/_pcg64.pyx
  numpy/random/_philox.pyx
  numpy/random/_sfc64.pyx
  numpy/random/bit_generator.pyx
  numpy/random/mtrand.pyx
Labels: 00 - Bug, component: numpy.random

#24613 ENH: Adopt new macOS Accelerate BLAS/LAPACK Interfaces, including ILP64
  .cirrus.star
  .github/workflows/macos.yml
  build_requirements.txt
  doc/release/upcoming_changes/24053.new_feature.rst
  environment.yml
  numpy/core/src/common/npy_cblas.h
  numpy/distutils/system_info.py
  numpy/linalg/meson.build
  numpy/meson.build
  tools/ci/cirrus_arm.yml
Labels: 01 - Enhancement, component: numpy.linalg, component: numpy.core, 08 - Backport

#24614 DOC: Update building docs to use Meson
  INSTALL.rst
  benchmarks/README.rst
  building_with_meson.md
  doc/RELEASE_WALKTHROUGH.rst
  doc/TESTS.rst
  doc/source/dev/development_environment.rst
  doc/source/dev/howto_build_docs.rst
  doc/source/dev/index.rst
  doc/source/user/building.rst
Labels: 04 - Documentation, 08 - Backport, Meson

#24615 TYP: Add the missing ``casting`` keyword to ``np.clip``
  numpy/core/fromnumeric.pyi
Labels: 08 - Backport, Static typing

#24616 TST: convert cython test from setup.py to meson
  numpy/core/tests/examples/cython/meson.build
  numpy/core/tests/test_cython.py
Labels: 05 - Testing, 08 - Backport

#24618 DOC: Fix markups for code blocks
  doc/HOWTO_RELEASE.rst
  doc/source/user/how-to-partition.rst
  numpy/core/numeric.py
  numpy/lib/_polynomial_impl.py
  numpy/testing/_private/utils.py
Labels: 04 - Documentation

#24617 MAINT: Fixup ``fromnumeric.pyi``
  numpy/core/fromnumeric.pyi
Labels: 03 - Maintenance, Static typing

#24555 BUG, ENH: Fix `iso_c_binding` type maps and fix `bind(c)` support
  doc/release/upcoming_changes/24555.improvement.rst
  doc/release/upcoming_changes/24555.new_feature.rst
  numpy/f2py/_isocbind.py
  numpy/f2py/auxfuncs.py
  numpy/f2py/capi_maps.py
  numpy/f2py/crackfortran.py
  numpy/f2py/func2subr.py
  numpy/f2py/tests/src/isocintrin/isoCtests.f90
  numpy/f2py/tests/test_isoc.py
Labels: 00 - Bug, component: numpy.f2py, 09 - Backport-Candidate

#24622 BUG, ENH: Fix ``iso_c_binding`` type maps and fix ``bind(c)`` support
  doc/release/upcoming_changes/24555.improvement.rst
  doc/release/upcoming_changes/24555.new_feature.rst
  numpy/f2py/_isocbind.py
  numpy/f2py/auxfuncs.py
  numpy/f2py/capi_maps.py
  numpy/f2py/crackfortran.py
  numpy/f2py/func2subr.py
  numpy/f2py/tests/src/isocintrin/isoCtests.f90
  numpy/f2py/tests/test_isoc.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#24623 TYP: Explicitly declare `dtype` and `generic` as hashable
  numpy/__init__.pyi
Labels: 09 - Backport-Candidate, Static typing

#24628 TYP: Allow `binary_repr` to accept any object implementing `__index__`
  numpy/core/numeric.pyi
Labels: 09 - Backport-Candidate, Static typing

#24629 TYP: Allow ``binary_repr`` to accept any object implementing ``__index__``
  numpy/core/numeric.pyi
Labels: 08 - Backport, Static typing

#24630 TYP: Explicitly declare ``dtype`` and ``generic`` hashable
  numpy/__init__.pyi
Labels: 08 - Backport, Static typing

#24605 DOC: fix isreal docstring (complex -> imaginary)
  numpy/lib/_type_check_impl.py
Labels: 04 - Documentation

#24631 DOC: Clarify usage of --include-paths as an f2py CLI argument
  doc/source/f2py/usage.rst
Labels: 04 - Documentation, component: numpy.f2py

#24626 DOC: add release notes link to PyPI.
  pyproject.toml
Labels: 04 - Documentation

#24638 MAINT: Bump actions/checkout from 3.6.0 to 4.0.0
  .github/workflows/build_test.yml
  .github/workflows/codeql.yml
  .github/workflows/cygwin.yml
  .github/workflows/dependency-review.yml
  .github/workflows/emscripten.yml
  .github/workflows/linux_meson.yml
  .github/workflows/macos.yml
  .github/workflows/scorecards.yml
  .github/workflows/wheels.yml
  .github/workflows/windows_clangcl.yml
  .github/workflows/windows_meson.yml
Labels: 03 - Maintenance

#24461 SIMD: Refactor partial load workaround for Clang
  meson.build
  numpy/core/meson.build
  numpy/core/src/common/simd/avx2/memory.h
  numpy/core/src/common/simd/avx512/memory.h
  numpy/core/src/common/simd/neon/memory.h
  numpy/core/src/common/simd/simd.h
  numpy/core/src/common/simd/sse/memory.h
  numpy/core/src/common/simd/vec/memory.h
  numpy/core/src/umath/loops_arithm_fp.dispatch.c.src
  numpy/core/src/umath/loops_unary_fp.dispatch.c.src
Labels: 09 - Backport-Candidate, component: SIMD

#24420 SIMD: Introduce tracer for enabled CPU targets on each optimized function
  doc/release/upcoming_changes/24420.new_feature.rst
  doc/source/reference/simd/build-options.rst
  meson_cpu/main_config.h.in
  numpy/core/code_generators/generate_umath.py
  numpy/core/meson.build
  numpy/core/setup.py
  numpy/core/src/common/npy_cpu_dispatch.c
  numpy/core/src/common/npy_cpu_dispatch.h
  numpy/core/src/common/npy_cpu_dispatch_distutils.h
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/umath/_umath_tests.dispatch.c
  numpy/lib/__init__.py
  numpy/lib/_utils_impl.py
  numpy/lib/introspect.py
  numpy/tests/test_public_api.py
Labels: 09 - Backport-Candidate, component: SIMD

#24647 ENH: ``meson`` backend for ``f2py``
  doc/release/upcoming_changes/24532.new_feature.rst
  numpy/distutils/command/build_src.py
  numpy/f2py/_backends/__init__.py
  numpy/f2py/_backends/_backend.py
  numpy/f2py/_backends/_distutils.py
  numpy/f2py/_backends/_meson.py
  numpy/f2py/_backends/meson.build.template
  numpy/f2py/auxfuncs.py
  numpy/f2py/f2py2e.py
  numpy/f2py/setup.py
  numpy/f2py/tests/src/f2cmap/isoFortranEnvMap.f90
Labels: 01 - Enhancement, component: numpy.f2py, 08 - Backport

#24644 MAINT: remove the `oldnumeric.h` header
  numpy/core/include/meson.build
  numpy/core/include/numpy/oldnumeric.h
Labels: 03 - Maintenance

#24648 MAINT: Refactor partial load Workaround for Clang
  meson.build
  numpy/core/meson.build
  numpy/core/src/common/simd/avx2/memory.h
  numpy/core/src/common/simd/avx512/memory.h
  numpy/core/src/common/simd/neon/memory.h
  numpy/core/src/common/simd/simd.h
  numpy/core/src/common/simd/sse/memory.h
  numpy/core/src/common/simd/vec/memory.h
  numpy/core/src/umath/loops_arithm_fp.dispatch.c.src
  numpy/core/src/umath/loops_unary_fp.dispatch.c.src
Labels: 03 - Maintenance, 08 - Backport, component: SIMD

#24445 API: Cleaning `numpy/__init__.py` and main namespace - Part 4 [NEP 52]
  doc/release/upcoming_changes/24445.deprecation.rst
  doc/source/reference/routines.array-manipulation.rst
  doc/source/reference/routines.ma.rst
  doc/source/reference/routines.math.rst
  doc/source/user/quickstart.rst
  numpy/core/fromnumeric.py
  numpy/core/shape_base.py
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_overrides.py
  numpy/lib/_arraysetops_impl.py
  numpy/lib/_function_base_impl.py
  numpy/lib/_shape_base_impl.py
  numpy/lib/tests/test_arraysetops.py
  numpy/lib/tests/test_function_base.py
  numpy/matrixlib/tests/test_interaction.py
  numpy/tests/test_public_api.py
  numpy/typing/tests/data/reveal/arraysetops.pyi
  numpy/typing/tests/data/reveal/shape_base.pyi
Labels: 30 - API, 62 - Python API, Numpy 2.0 API Changes

#24610 MAINT: Avoid creating an intermediate array in np.quantile
  numpy/lib/_function_base_impl.py
Labels: 03 - Maintenance

#24653 REL: Prepare for the NumPy 1.26.0rc1 release.
  .mailmap
  doc/changelog/1.26.0-changelog.rst
  doc/release/upcoming_changes/23789.new_feature.rst
  doc/release/upcoming_changes/24053.new_feature.rst
  doc/release/upcoming_changes/24532.new_feature.rst
  doc/release/upcoming_changes/24555.improvement.rst
  doc/release/upcoming_changes/24555.new_feature.rst
  doc/source/release/1.26.0-notes.rst
  pyproject.toml
  pyproject.toml.setuppy
Labels: 14 - Release

#24498 MAINT: Re-write 16-bit qsort dispatch
  numpy/core/src/npysort/simd_qsort_16bit.dispatch.cpp
Labels: 03 - Maintenance, triage review, component: SIMD

#24659 BLD: allow specifying the long double format to avoid the runtime check
  numpy/core/meson.build
Labels: 01 - Enhancement, 08 - Backport, 36 - Build

#24625 CI: Switch SIMD tests to meson
  .github/meson_actions/action.yml
  .github/workflows/linux_simd.yml
Labels: component: CI, component: SIMD

#24665 BLD: fix bug in random.mtrand extension, don't link libnpyrandom
  numpy/random/meson.build
Labels: 00 - Bug, component: numpy.random, 08 - Backport, 36 - Build

#24671 BLD: build wheels for 32-bit Python on Windows, using MSVC
  .github/workflows/wheels.yml
  numpy/random/tests/test_extending.py
  pyproject.toml
  tools/wheels/cibw_test_command.sh
  tools/wheels/repair_windows.sh
Labels: 14 - Release, 09 - Backport-Candidate, 36 - Build, Meson

#24675 Backport 24671
  .github/workflows/wheels.yml
  numpy/random/tests/test_extending.py
  pyproject.toml
  tools/wheels/cibw_test_command.sh
  tools/wheels/repair_windows.sh
Labels: 14 - Release, 08 - Backport, 36 - Build, Meson

#24677 DOC: improve the docstring's examples for np.searchsorted
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#24674 DOC: Remove extra indents in documents
  doc/source/dev/alignment.rst
  doc/source/dev/development_environment.rst
  doc/source/dev/development_workflow.rst
  doc/source/dev/howto-docs.rst
  doc/source/dev/internals.rst
  doc/source/f2py/usage.rst
  doc/source/reference/random/upgrading-pcg64.rst
  doc/source/reference/simd/build-options.rst
  doc/source/reference/swig.interface-file.rst
  doc/source/reference/swig.testing.rst
  doc/source/user/basics.io.genfromtxt.rst
  doc/source/user/basics.subclassing.rst
  doc/source/user/how-to-how-to.rst
Labels: 04 - Documentation

#24487 DOC: Fix reference warning in some rst and code files.
  doc/source/reference/arrays.dtypes.rst
  doc/source/reference/routines.array-creation.rst
  doc/source/release/1.16.0-notes.rst
  doc/source/release/1.20.0-notes.rst
  doc/source/release/1.20.2-notes.rst
  doc/source/release/1.7.0-notes.rst
  doc/source/user/basics.indexing.rst
  numpy/typing/__init__.py
Labels: 04 - Documentation

#24540 API: Add ``lib.array_utils`` namespace
  doc/release/upcoming_changes/24540.change.rst
  doc/source/reference/routines.other.rst
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_expired_attrs_2_0.py
  numpy/core/multiarray.py
  numpy/core/numeric.py
  numpy/lib/__init__.py
  numpy/lib/_array_utils_impl.py
  numpy/lib/_array_utils_impl.pyi
  numpy/lib/_utils_impl.py
  numpy/lib/_utils_impl.pyi
  numpy/lib/array_utils.py
  numpy/lib/array_utils.pyi
  numpy/lib/tests/test_array_utils.py
  numpy/lib/tests/test_utils.py
  numpy/tests/test_public_api.py
  numpy/typing/tests/data/fail/lib_utils.pyi
  numpy/typing/tests/data/pass/lib_utils.py
  numpy/typing/tests/data/pass/modules.py
  numpy/typing/tests/data/reveal/lib_utils.pyi
Labels: 30 - API, Numpy 2.0 API Changes

#24695 CI: enable use of Cirrus CI compute credits by collaborators
  tools/ci/cirrus_arm.yml
  tools/ci/cirrus_wheels.yml
Labels: component: CI

#24697 API: Readd `sctypeDict` to the main namespace
  numpy/__init__.py
  numpy/core/__init__.py
Labels: 30 - API, Numpy 2.0 API Changes

#23282 BUG: Fix data stmt handling for complex values in f2py
  numpy/f2py/auxfuncs.py
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/src/crackfortran/data_stmts.f90
  numpy/f2py/tests/test_data.py
Labels: 00 - Bug, component: numpy.f2py, 09 - Backport-Candidate

#24701 BUG: Fix data stmt handling for complex values in f2py
  numpy/f2py/auxfuncs.py
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/src/crackfortran/data_stmts.f90
  numpy/f2py/tests/test_data.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#24702 DOC: Fix typos
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#24705 TYP: Add annotations for the py3.12 buffer protocol
  numpy/__init__.pyi
  numpy/_typing/_array_like.py
  numpy/array_api/_typing.py
  numpy/typing/tests/data/reveal/array_constructors.pyi
Labels: 03 - Maintenance, 09 - Backport-Candidate, Static typing

#24707 TYP: Add annotations for the py3.12 buffer protocol
  numpy/__init__.pyi
  numpy/_typing/_array_like.py
  numpy/array_api/_typing.py
  numpy/typing/tests/data/reveal/array_constructors.pyi
Labels: 03 - Maintenance, 08 - Backport, Static typing

#24696 DOC: Updated the f2py docs to remove a note on `-fimplicit-none`
  doc/source/f2py/buildtools/meson.rst
Labels: 04 - Documentation

#24715 DOC: Fix trailing backticks characters.
  doc/source/release/1.14.0-notes.rst
  numpy/random/bit_generator.pyx
Labels: 04 - Documentation

#24717 MAINT: remove relaxed strides debug build setting
  .github/workflows/linux.yml
  doc/release/upcoming_changes/24717.change.rst
  doc/source/reference/arrays.ndarray.rst
  doc/source/reference/global_state.rst
  meson_options.txt
  numpy/_pytesttester.py
  numpy/core/config.h.in
  numpy/core/meson.build
  numpy/core/numeric.py
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/textreading/rows.c
  numpy/core/tests/test_multiarray.py
  numpy/core/tests/test_regression.py
Labels: 03 - Maintenance

#24519 MAINT: remove `setup.py` and other files for distutils builds
  .gitattributes
  .github/actions/action.yml
  .github/workflows/emscripten.yml
  .gitignore
  LICENSES_bundled.txt
  MANIFEST.in
  doc/HOWTO_RELEASE.rst
  numpy/_build_utils/setup.py
  numpy/_build_utils/tempita.py
  numpy/_pytesttester.py
  numpy/_typing/setup.py
  numpy/array_api/setup.py
  numpy/compat/setup.py
  numpy/core/code_generators/cversions.txt
  numpy/core/code_generators/numpy_api.py
  numpy/core/feature_detection_cmath.h
  numpy/core/feature_detection_math.h
  numpy/core/meson.build
  numpy/core/setup.py
  numpy/core/setup_common.py
  numpy/distutils/setup.py
  numpy/f2py/setup.py
  numpy/fft/setup.py
  numpy/lib/setup.py
  numpy/linalg/setup.py
  numpy/ma/setup.py
  numpy/matrixlib/setup.py
  numpy/polynomial/setup.py
  numpy/random/setup.py
  numpy/setup.py
  numpy/testing/setup.py
  numpy/typing/setup.py
  pyproject.toml.setuppy
  runtests.py
  setup.cfg
  setup.py
  site.cfg.example
  tools/cythonize.py
  tools/npy_tempita/__init__.py
  tools/npy_tempita/_looper.py
  tools/npy_tempita/compat3.py
  tools/npy_tempita/license.txt
  tools/travis-before-install.sh
  tools/travis-sorter.py
  tools/travis-test.sh
  tox.ini
Labels: 03 - Maintenance

#24721 DOC: Doc fixes and updates.
  .spin/cmds.py
  doc/RELEASE_WALKTHROUGH.rst
  doc/source/user/building.rst
Labels: 04 - Documentation

#24722 REL: Prepare for the NumPy 1.26.0 release
  doc/changelog/1.26.0-changelog.rst
  doc/source/release/1.26.0-notes.rst
  numpy/f2py/__init__.pyi
  pyproject.toml
  pyproject.toml.setuppy
Labels: 14 - Release, 03 - Maintenance

#24725 MAINT: Update main after 1.26.0 release.
  .mailmap
  doc/changelog/1.26.0-changelog.rst
  doc/source/release.rst
  doc/source/release/1.26.0-notes.rst
Labels: 04 - Documentation, 03 - Maintenance

#24690 DOC: Fix reference warning in some rst files
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/data_memory.rst
  doc/source/reference/c-api/dtype.rst
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#24620 DOC: Update NEP 52 file
  doc/neps/nep-0052-python-api-cleanup.rst
Labels: 04 - Documentation, Numpy 2.0 API Changes

#24693 DOC: NumPy 2.0 migration guide
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/user/index.rst
  numpy/_expired_attrs_2_0.py
  numpy/lib/_array_utils_impl.py
Labels: 04 - Documentation, Numpy 2.0 API Changes

#24742 MAINT: Update cibuildwheel version
  .github/workflows/wheels.yml
  tools/ci/cirrus_wheels.yml
Labels: 03 - Maintenance

#24735 MAINT: Update RELEASE_WALKTHROUGH
  doc/Makefile
  doc/RELEASE_WALKTHROUGH.rst
  release_requirements.txt
Labels: 03 - Maintenance

#24748 MAINT: fix version string in wheels built with setup.py
  numpy/distutils/core.py
Labels: 00 - Bug, 09 - Backport-Candidate

#24682 API: Remove `ptp`, `itemset` and `newbyteorder` from `np.ndarray` class
  doc/source/reference/arrays.ndarray.rst
  doc/source/reference/c-api/array.rst
  doc/source/user/byteswapping.rst
  numpy/__init__.pyi
  numpy/_expired_attrs_2_0.py
  numpy/core/_add_newdocs.py
  numpy/core/fromnumeric.py
  numpy/core/getlimits.py
  numpy/core/records.py
  numpy/core/src/multiarray/getset.c
  numpy/core/src/multiarray/methods.c
  numpy/core/src/multiarray/scalartypes.c.src
  numpy/core/tests/test_datetime.py
  numpy/core/tests/test_half.py
  numpy/core/tests/test_indexerrors.py
  numpy/core/tests/test_longdouble.py
  numpy/core/tests/test_multiarray.py
  numpy/core/tests/test_nditer.py
  numpy/core/tests/test_regression.py
  numpy/core/tests/test_unicode.py
  numpy/lib/tests/test_function_base.py
  numpy/linalg/tests/test_linalg.py
  numpy/ma/tests/test_core.py
  numpy/ma/tests/test_old_ma.py
  numpy/matrixlib/defmatrix.py
  numpy/matrixlib/tests/test_defmatrix.py
  numpy/typing/tests/data/pass/ndarray_conversion.py
  numpy/typing/tests/data/pass/ndarray_misc.py
  numpy/typing/tests/data/reveal/ndarray_misc.pyi
Labels: 30 - API, triage review, Numpy 2.0 API Changes

#24733 BLD, BUG: Fix build failure for host flags e.g. `-march=native` on unsupported architectures
  meson_cpu/meson.build
Labels: 00 - Bug, 09 - Backport-Candidate, component: SIMD, 36 - Build

#24766 DOC: add a note on the ``.c.src`` format to the distutils migration page
  doc/source/reference/distutils_status_migration.rst
Labels: 04 - Documentation, component: numpy.distutils

#24680 ENH: add parameter `strict` to `assert_allclose`
  doc/release/upcoming_changes/24680.new_feature.rst
  numpy/testing/_private/utils.py
  numpy/testing/_private/utils.pyi
  numpy/testing/tests/test_utils.py
Labels: 01 - Enhancement

#24741 MAINT: Remove cibuildwheel pin in cirrus_wheels
  tools/ci/cirrus_wheels.yml
Labels: 03 - Maintenance

#24753 BLD: add libquadmath to licences and other tweaks
  .github/workflows/linux.yml
  .github/workflows/windows.yml
  azure-steps-windows.yml
  tools/ci/cirrus_wheels.yml
  tools/openblas_support.py
  tools/wheels/LICENSE_linux.txt
  tools/wheels/LICENSE_osx.txt
  tools/wheels/LICENSE_win32.txt
  tools/wheels/cibw_before_build.sh
Labels: 09 - Backport-Candidate, 36 - Build

#24667 DOC: TEST.rst: add example with `pytest.mark.parametrize`
  doc/TESTS.rst
Labels: 04 - Documentation

#24771 BLD, BUG: Fix build failure for host flags e.g. `-march=native` on unsupported architectures
  meson_cpu/meson.build
Labels: 00 - Bug, 08 - Backport, component: SIMD, 36 - Build

#24773 DOC: Updated the f2py docs to remove a note on -fimplicit-none
  doc/source/f2py/buildtools/meson.rst
Labels: 04 - Documentation, 08 - Backport

#24752 DOC: Fix reference warning in some rst files
  doc/source/reference/arrays.classes.rst
  numpy/core/defchararray.py
  numpy/core/numeric.py
Labels: 04 - Documentation

#24772 MAINT: align test_dispatcher s390x targets with _umath_tests_mtargets
  numpy/core/tests/test_cpu_dispatcher.py
Labels: 03 - Maintenance, 09 - Backport-Candidate

#24776 BUG: Fix SIMD f32 trunc test on s390x when baseline is none
  numpy/core/tests/test_simd_module.py
Labels: 00 - Bug, 08 - Backport

#24762 BUG: Fix order of Windows OS detection macros.
  numpy/core/include/numpy/npy_os.h
Labels: 00 - Bug, 09 - Backport-Candidate

#24785 BLD: add libquadmath to licences and other tweaks (#24753)
  .github/workflows/windows.yml
  .github/workflows/windows_meson.yml
  azure-steps-windows.yml
  tools/ci/cirrus_wheels.yml
  tools/openblas_support.py
  tools/wheels/LICENSE_linux.txt
  tools/wheels/LICENSE_osx.txt
  tools/wheels/LICENSE_win32.txt
  tools/wheels/cibw_before_build.sh
Labels: 08 - Backport, 36 - Build

#24786 MAINT: Activate ``use-compute-credits`` for Cirrus.
  tools/ci/cirrus_arm.yml
  tools/ci/cirrus_wheels.yml
Labels: 03 - Maintenance

#24793 MAINT: fix licence path win
  tools/wheels/LICENSE_win32.txt
Labels: 03 - Maintenance, 09 - Backport-Candidate

#24792 TYP,DOC: Document the `np.number` parameter type as invariant
  numpy/typing/__init__.py
Labels: 04 - Documentation, Static typing

#24787 DOC: Closes issue #24730, 'sigma' to 'signum' in piecewise example
  numpy/lib/_function_base_impl.py
Labels: 04 - Documentation

#24781 MAINT, DOC: fix typos found by codespell
  doc/neps/nep-0021-advanced-indexing.rst
  doc/neps/nep-0052-python-api-cleanup.rst
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/reference/arrays.interface.rst
  doc/source/reference/c-api/dtype.rst
  doc/source/release/1.22.0-notes.rst
  doc/source/release/1.22.4-notes.rst
  doc/source/release/1.25.2-notes.rst
  doc/source/release/1.3.0-notes.rst
  doc/source/user/basics.subclassing.rst
  meson_cpu/meson.build
  numpy/core/src/common/npy_cpu_dispatch_distutils.h
  numpy/core/src/common/simd/simd.h
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/mapping.c
  numpy/core/src/multiarray/scalartypes.c.src
  numpy/core/tests/test_umath_complex.py
  numpy/lib/_function_base_impl.py
  numpy/lib/_shape_base_impl.py
Labels: 04 - Documentation, 03 - Maintenance

#24780 DOC: Replace http:// by https://
  INSTALL.rst
  doc/source/dev/development_environment.rst
  doc/source/dev/development_workflow.rst
  doc/source/dev/gitwash/git_links.inc
  doc/source/dev/gitwash/git_resources.rst
  doc/source/dev/governance/governance.rst
  doc/source/dev/howto-docs.rst
  doc/source/dev/howto_build_docs.rst
  doc/source/dev/internals.rst
  doc/source/reference/arrays.interface.rst
  doc/source/reference/random/bit_generators/index.rst
  doc/source/reference/random/parallel.rst
  doc/source/reference/random/upgrading-pcg64.rst
  doc/source/reference/swig.interface-file.rst
  doc/source/reference/swig.testing.rst
  doc/source/user/absolute_beginners.rst
  doc/source/user/basics.interoperability.rst
  doc/source/user/quickstart.rst
  numpy/core/getlimits.py
  numpy/core/src/common/simd/intdiv.h
  numpy/core/src/multiarray/dragon4.c
  numpy/core/src/multiarray/dragon4.h
  numpy/core/src/npymath/npy_math_complex.c.src
  numpy/core/src/npymath/npy_math_internal.h.src
  numpy/core/src/umath/loops_arithmetic.dispatch.c.src
  numpy/lib/_function_base_impl.py
  numpy/lib/_histograms_impl.py
  numpy/linalg/lapack_lite/README.rst
  numpy/random/_generator.pyx
  numpy/random/_mt19937.pyx
  numpy/random/_pcg64.pyx
  numpy/random/_sfc64.pyx
  numpy/random/bit_generator.pyx
  numpy/random/mtrand.pyx
  numpy/random/src/mt19937/mt19937-jump.h
  numpy/random/src/pcg64/pcg64.c
  numpy/random/src/pcg64/pcg64.h
  numpy/random/src/splitmix64/splitmix64.c
  numpy/typing/mypy_plugin.py
  tools/c_coverage/HOWTO_C_COVERAGE.txt
Labels: 04 - Documentation

#24804 MAINT: fix licence path win
  tools/wheels/LICENSE_win32.txt
Labels: 03 - Maintenance, 08 - Backport

#24758 ENH: fix printing structured dtypes with a non-legacy dtype member
  numpy/core/_dtype.py
  numpy/core/tests/test_custom_dtypes.py
Labels: 01 - Enhancement

#24257 BUG: Add size check for threaded array assignment
  benchmarks/benchmarks/bench_manipulate.py
  numpy/core/src/multiarray/array_assign_array.c
Labels: 00 - Bug

#24811 DOC: explain why we avoid string.ascii_letters
  numpy/core/einsumfunc.py
Labels: 03 - Maintenance

#24813 BUG: Fix order of Windows OS detection macros.
  numpy/core/include/numpy/npy_os.h
Labels: 00 - Bug, 08 - Backport

#24816 MAINT: Upgrade to spin 0.7
  .spin/cmds.py
  build_requirements.txt
  pyproject.toml
Labels: 03 - Maintenance

#24817 DOC: Fix markups for emphasis
  doc/source/reference/arrays.ndarray.rst
  doc/source/user/how-to-how-to.rst
  numpy/core/shape_base.py
  numpy/lib/_function_base_impl.py
  numpy/ma/core.py
  numpy/typing/__init__.py
Labels: 04 - Documentation

#24820 MAINT: remove `wheel` as a build dependency
  INSTALL.rst
  build_requirements.txt
Labels: 03 - Maintenance

#24825 DOC: Fix docstring of matrix class
  numpy/matrixlib/defmatrix.py
Labels: 04 - Documentation

#21429 ENH: Added `bitwise_count` UFuncs
  benchmarks/benchmarks/bench_ufunc.py
  benchmarks/benchmarks/bench_ufunc_strides.py
  doc/release/upcoming_changes/19355.new_feature.rst
  doc/source/reference/routines.math.rst
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/core/_methods.py
  numpy/core/code_generators/generate_umath.py
  numpy/core/code_generators/ufunc_docstrings.py
  numpy/core/src/npymath/npy_math_internal.h.src
  numpy/core/src/umath/loops.c.src
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/loops_autovec.dispatch.c.src
  numpy/core/tests/test_ufunc.py
  numpy/core/tests/test_umath.py
  numpy/core/tests/test_umath_accuracy.py
  numpy/core/umath.py
  numpy/matrixlib/tests/test_defmatrix.py
  numpy/typing/tests/data/reveal/ufuncs.pyi
Labels: 01 - Enhancement, 62 - Python API

#24681 BUG: Fix weak promotion with some mixed float/int dtypes
  numpy/core/src/multiarray/abstractdtypes.c
  numpy/core/src/multiarray/common_dtype.c
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/tests/test_nep50_promotions.py
Labels: 00 - Bug

#24828 BUG, SIMD: use scalar cmul on bad Apple clang x86_64
  numpy/core/src/umath/loops_arithm_fp.dispatch.c.src
Labels: 00 - Bug, 09 - Backport-Candidate

#24831 BUG, SIMD: use scalar cmul on bad Apple clang x86_64 (#24828)
  numpy/core/src/umath/loops_arithm_fp.dispatch.c.src
Labels: 00 - Bug, 08 - Backport

#24807 API: Remove zero names from dtype aliases
  numpy/_typing/_char_codes.py
  numpy/core/_type_aliases.py
  numpy/core/src/multiarray/descriptor.c
  numpy/core/tests/test_dtype.py
Labels: 30 - API, Numpy 2.0 API Changes
