Repository numpy/numpy, pull requests merged in 2023-11, with the labels that each got.

#25042 BUG: ensure passing `np.dtype` to itself doesn't crash
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/tests/test_dtype.py
Labels: 00 - Bug, 09 - Backport-Candidate

#25039 MAINT: Adjust typing for readded `np.long`
  numpy/__init__.pyi
  numpy/_core/numerictypes.pyi
  numpy/_typing/_dtype_like.py
  numpy/ctypeslib.pyi
  numpy/random/_generator.pyi
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyi
  numpy/random/mtrand.pyx
  numpy/typing/tests/data/reveal/numerictypes.pyi
  numpy/typing/tests/data/reveal/random.pyi
  numpy/typing/tests/data/reveal/scalars.pyi
Labels: 03 - Maintenance, Static typing

#24975 DOC: correct Logo SVG files rendered in dark by Figma
  branding/logo/logomark/numpylogoicon.svg
  branding/logo/primary/numpylogo.svg
  branding/logo/secondary/numpylogo2.svg
Labels: 04 - Documentation

#25037 MAINT: Unpin urllib3 for anaconda-client install
  .github/workflows/wheels.yml
  tools/ci/cirrus_wheels.yml
Labels: 03 - Maintenance

#25006 DOC: update ndarray.item docstring
  numpy/_core/_add_newdocs.py
Labels: 04 - Documentation

#25050 TST: Ensure test is not run on 32bit platforms
  numpy/_core/tests/test_ufunc.py
Labels: 05 - Testing, 09 - Backport-Candidate

#25051 MAINT: Make bitfield integers unsigned
  numpy/_core/src/_simd/_simd_inc.h.src
Labels: 03 - Maintenance

#24224 API: Make 64bit default integer on 64bit windows
  doc/release/upcoming_changes/24224.change.rst
  doc/source/numpy_2_0_migration_guide.rst
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/__init__.pyi
  numpy/_core/_add_newdocs_scalars.py
  numpy/_core/_type_aliases.py
  numpy/_core/code_generators/generate_numpy_api.py
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/include/numpy/npy_common.h
  numpy/_core/src/multiarray/abstractdtypes.c
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/src/umath/_operand_flag_tests.c
  numpy/_core/src/umath/_umath_tests.c.src
  numpy/_core/src/umath/loops.c.src
  numpy/_core/src/umath/loops.h.src
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/examples/cython/checks.pyx
  numpy/_core/tests/test_cython.py
  numpy/_core/tests/test_dtype.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_numerictypes.py
  numpy/_core/tests/test_scalarbuffer.py
  numpy/_core/tests/test_ufunc.py
  numpy/_typing/_char_codes.py
  numpy/ctypeslib.pyi
  numpy/random/_common.pxd
  numpy/random/_common.pyx
  numpy/random/mtrand.pyx
  numpy/random/tests/test_random.py
  numpy/random/tests/test_randomstate.py
  numpy/random/tests/test_randomstate_regression.py
  numpy/typing/tests/data/reveal/ctypeslib.pyi
  numpy/typing/tests/data/reveal/random.pyi
Labels: 30 - API, 36 - Build

#25030 DOC: Include `np.long` in `arrays.scalars.rst`
  doc/source/dev/development_environment.rst
  doc/source/reference/arrays.scalars.rst
  doc/source/reference/figures/dtype-hierarchy.dia
  doc/source/reference/figures/dtype-hierarchy.pdf
  doc/source/reference/figures/dtype-hierarchy.png
  numpy/_core/multiarray.py
Labels: 04 - Documentation, Numpy 2.0 API Changes

#25056 DOC: Small fixes for NEP 52
  doc/neps/nep-0052-python-api-cleanup.rst
Labels: 04 - Documentation

#24981 DOC: revisions to "absolute beginners" tutorial
  doc/source/user/absolute_beginners.rst
Labels: 04 - Documentation

#24868 ENH: Add find/rfind ufuncs for unicode and byte dtypes
  benchmarks/benchmarks/bench_core.py
  doc/release/upcoming_changes/24868.new_feature.rst
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/defchararray.py
  numpy/_core/src/umath/dispatching.c
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_fastsearch.h
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/tests/test_ufunc.py
Labels: 56 - Needs Release Note., 25 - WIP

#25059 MAINT: `np.long` typing nitpick
  numpy/dtypes.pyi
Labels: 03 - Maintenance, Numpy 2.0 API Changes

#25063 BLD: change default of the `allow-noblas` option to true
  .github/workflows/linux_blas.yml
  .github/workflows/macos.yml
  meson_options.txt
  pyproject.toml
Labels: component: build, 09 - Backport-Candidate, 36 - Build

#25067 DOC: add missing word to internals.rst
  doc/source/dev/internals.rst
Labels: 04 - Documentation

#25068 TST: skip flaky test in test_histogram
  numpy/lib/tests/test_histograms.py
Labels: 05 - Testing

#24968 BLD: mingw-w64 build fixes
  numpy/meson.build
Labels: 09 - Backport-Candidate, 36 - Build

#24996 DOC: Clarify a point in basic indexing user guide
  doc/source/user/basics.indexing.rst
Labels: 04 - Documentation

#25049 MAINT: Update meson build infrastructure.
  numpy/core/include/numpy/npy_common.h
  numpy/core/meson.build
  numpy/core/src/common/numpyos.c
  numpy/lib/tests/test_histograms.py
  numpy/meson.build
Labels: 03 - Maintenance, 08 - Backport, 25 - WIP

#24984 DOC: fix reference in user/basics.rec.html#record-arrays
  doc/source/user/basics.rec.rst
Labels: 04 - Documentation

#24814 MAINT: align test_dispatcher s390x targets with _umath_tests_mtargets
  numpy/core/src/umath/_umath_tests.dispatch.c
  numpy/core/tests/test_cpu_dispatcher.py
Labels: 03 - Maintenance, 08 - Backport, component: SIMD

#24806 BUG: Fix build on ppc64 when the baseline set to Power9 or higher
  .github/workflows/linux_qemu.yml
  meson_cpu/ppc64/meson.build
  numpy/_core/src/common/half.hpp
  numpy/_core/tests/test_half.py
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/checks/extra_vsx3_half_double.c
Labels: 00 - Bug, 09 - Backport-Candidate

#24663 ENH: optimisation of array_equal
  numpy/_core/numeric.py
  numpy/core/numeric.py
Labels: 01 - Enhancement

#25062 ENH: Change add/isalpha ufuncs to use buffer class & general clean-up
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_fastsearch.h
  numpy/_core/src/umath/string_ufuncs.cpp
Labels: 01 - Enhancement

#25017 ENH: Added `notes` command for spin
  .spin/cmds.py
  pyproject.toml
  tools/ci/test_all_newsfragments_used.py
Labels: 01 - Enhancement, 16 - Development

#25089 BUG, BLD: Fixed VSX4 feature check
  meson_cpu/ppc64/meson.build
Labels: 00 - Bug, 09 - Backport-Candidate

#24947 ENH: Add startswith & endswith ufuncs for unicode and bytes dtypes
  benchmarks/benchmarks/bench_core.py
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/defchararray.py
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/tests/test_ufunc.py
Labels: 01 - Enhancement

#25090 BUG: Make n a long int for np.random.multinomial
  numpy/random/mtrand.pyx
  numpy/random/tests/test_randomstate.py
Labels: 00 - Bug

#25081 DOC: Provide migration notes for scalar inspection functions
  doc/source/numpy_2_0_migration_guide.rst
  numpy/_expired_attrs_2_0.py
Labels: 04 - Documentation, Numpy 2.0 API Changes

#25094 BUG: Avoid intp conversion regression in Cython 3
  numpy/__init__.cython-30.pxd
  numpy/_core/tests/examples/cython/checks.pyx
  numpy/_core/tests/test_cython.py
  numpy/random/mtrand.pyx
Labels: 00 - Bug

#25095 BUG: Avoid intp conversion regression in Cython 3 (backport)
  numpy/__init__.cython-30.pxd
  numpy/core/tests/examples/cython/checks.pyx
  numpy/core/tests/test_cython.py
Labels: 00 - Bug, 08 - Backport

#25102 MAINT: Print towncrier output file location
  .spin/cmds.py
Labels: 16 - Development, 03 - Maintenance

#24951 ENH: Add isdigit/isspace/isdecimal/isnumeric ufuncs for string types
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/defchararray.py
  numpy/_core/src/common/numpyos.c
  numpy/_core/src/common/numpyos.h
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_ufuncs.cpp
Labels: 01 - Enhancement

#25107 CI: remove obsolete jobs, and move macOS and conda Azure jobs to Meson and GHA
  .github/workflows/linux.yml
  .github/workflows/linux_blas.yml
  azure-pipelines.yml
Labels: 03 - Maintenance, component: CI

#25060 DOC: standardize capitalization of NEP headings
  doc/neps/nep-0000.rst
  doc/neps/nep-0001-npy-format.rst
  doc/neps/nep-0002-warnfix.rst
  doc/neps/nep-0005-generalized-ufuncs.rst
  doc/neps/nep-0006-newbugtracker.rst
  doc/neps/nep-0007-datetime-proposal.rst
  doc/neps/nep-0008-groupby_additions.rst
  doc/neps/nep-0010-new-iterator-ufunc.rst
  doc/neps/nep-0011-deferred-ufunc-evaluation.rst
  doc/neps/nep-0012-missing-data.rst
  doc/neps/nep-0016-abstract-array.rst
  doc/neps/nep-0017-split-out-maskedarray.rst
  doc/neps/nep-0019-rng-policy.rst
  doc/neps/nep-0020-gufunc-signature-enhancement.rst
  doc/neps/nep-0021-advanced-indexing.rst
  doc/neps/nep-0022-ndarray-duck-typing-overview.rst
  doc/neps/nep-0023-backwards-compatibility.rst
  doc/neps/nep-0024-missing-data-2.rst
  doc/neps/nep-0026-missing-data-summary.rst
  doc/neps/nep-0027-zero-rank-arrarys.rst
  doc/neps/nep-0028-website-redesign.rst
  doc/neps/nep-0029-deprecation_policy.rst
  doc/neps/nep-0030-duck-array-protocol.rst
  doc/neps/nep-0031-uarray.rst
  doc/neps/nep-0034-infer-dtype-is-object.rst
  doc/neps/nep-0035-array-creation-dispatch-with-array-function.rst
  doc/neps/nep-0038-SIMD-optimizations.rst
  doc/neps/nep-0040-legacy-datatype-impl.rst
  doc/neps/nep-0041-improved-dtype-support.rst
  doc/neps/nep-0043-extensible-ufuncs.rst
  doc/neps/nep-0044-restructuring-numpy-docs.rst
  doc/neps/nep-0045-c_style_guide.rst
  doc/neps/nep-0046-sponsorship-guidelines.rst
  doc/neps/nep-0047-array-api-standard.rst
  doc/neps/nep-0048-spending-project-funds.rst
  doc/neps/nep-0049.rst
  doc/neps/nep-0050-scalar-promotion.rst
  doc/neps/nep-0051-scalar-representation.rst
  doc/neps/nep-0052-python-api-cleanup.rst
  doc/neps/nep-0053-c-abi-evolution.rst
  doc/neps/nep-0055-string_dtype.rst
  doc/neps/nep-template.rst
Labels: 04 - Documentation

#25108 CI: Add linux_qemu action and remove travis testing.
  .github/workflows/linux_qemu.yml
  .github/workflows/windows.yml
  .travis.yml
  meson_cpu/ppc64/meson.build
  numpy/core/src/common/half.hpp
  numpy/core/tests/test_half.py
  numpy/core/tests/test_ufunc.py
  numpy/distutils/ccompiler_opt.py
Labels: 01 - Enhancement, 08 - Backport, component: CI

#25099 DOC: Fix license identifier for OpenBLAS
  tools/wheels/LICENSE_linux.txt
  tools/wheels/LICENSE_osx.txt
  tools/wheels/LICENSE_win32.txt
Labels: 04 - Documentation

#25112 MAINT: Update .spin/cmds.py from main.
  .spin/cmds.py
  pyproject.toml
Labels: 03 - Maintenance, 08 - Backport

#25115 MAINT: Add missing `noexcept` to shuffle helpers
  numpy/random/_generator.pyx
Labels: 03 - Maintenance, 08 - Backport

#25116 DOC: Fix license identifier for OpenBLAS
  tools/wheels/LICENSE_linux.txt
  tools/wheels/LICENSE_osx.txt
  tools/wheels/LICENSE_win32.txt
Labels: 04 - Documentation, 08 - Backport

#25117 BLD: improve detection of Netlib libblas/libcblas/liblapack
  .github/workflows/linux_blas.yml
  tools/ci/cirrus_arm.yml
Labels: 03 - Maintenance, 08 - Backport, 36 - Build

#25113 DOC: Visually divide main license and bundled licenses in wheels
  tools/wheels/cibw_before_build.sh
Labels: 04 - Documentation, 08 - Backport

#25093 BLD: Fix features.h detection for Meson builds [1.26.x Backport]
  numpy/core/config.h.in
  numpy/core/src/common/npy_config.h
  numpy/core/tests/test_umath.py
Labels: 08 - Backport, 36 - Build

#25118 MAINT: Make bitfield integers unsigned
  numpy/core/src/_simd/_simd_inc.h.src
Labels: 03 - Maintenance, 08 - Backport

#25119 BUG: Make n a long int for np.random.multinomial
  numpy/random/mtrand.pyx
  numpy/random/tests/test_randomstate.py
Labels: 00 - Bug, 08 - Backport

#25120 BLD: change default of the ``allow-noblas`` option to true.
  .github/workflows/linux_blas.yml
  .github/workflows/macos.yml
  meson_options.txt
  pyproject.toml
Labels: component: build, 08 - Backport, 36 - Build

#25121 BUG: ensure passing ``np.dtype`` to itself doesn't crash
  numpy/core/src/multiarray/descriptor.c
  numpy/core/tests/test_dtype.py
Labels: 00 - Bug, 08 - Backport

#25130 MAINT: prepare 1.26.x for further development
  doc/source/release.rst
  doc/source/release/1.26.3-notes.rst
  pavement.py
  pyproject.toml
  pyproject.toml.setuppy
Labels: 03 - Maintenance

#25127 DOC: angle: update documentation of convention when magnitude of argument is zero
  numpy/lib/_function_base_impl.py
Labels: 04 - Documentation

#24878 ENH: isclose/allclose: support array_like `atol`/`rtol`
  doc/release/upcoming_changes/24878.improvement.rst
  numpy/_core/numeric.py
  numpy/_core/tests/test_numeric.py
Labels: 01 - Enhancement

#25073 BLD,BUG: quadmath required where available [f2py]
  doc/source/f2py/windows/index.rst
  numpy/f2py/_backends/meson.build.template
Labels: component: numpy.f2py, 09 - Backport-Candidate, 36 - Build

#25078 BUG: alpha doesn't use REAL(10)
  numpy/f2py/crackfortran.py
Labels: 00 - Bug

#25092 BLD: Fix features.h detection and blocklist complex trig funcs on musl
  numpy/_core/config.h.in
  numpy/_core/src/common/npy_config.h
  numpy/_core/tests/test_umath.py
Labels: 09 - Backport-Candidate, 36 - Build

#25124 DOC: `f2py` CLI documentation enhancements
  doc/source/f2py/usage.rst
  numpy/f2py/crackfortran.py
  numpy/f2py/f2py2e.py
Labels: component: numpy.f2py, 03 - Maintenance

#25105 API: Remove `__array_prepare__`
  doc/release/upcoming_changes/25105.python_removal.rst
  doc/source/reference/arrays.classes.rst
  doc/source/user/basics.subclassing.rst
  doc/source/user/basics.ufuncs.rst
  numpy/__init__.pyi
  numpy/_core/_add_newdocs.py
  numpy/_core/defchararray.py
  numpy/_core/src/multiarray/methods.c
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/src/umath/ufunc_object.h
  numpy/_core/src/umath/umathmodule.c
  numpy/_core/tests/test_umath.py
  numpy/lib/_shape_base_impl.py
  numpy/lib/_shape_base_impl.pyi
  numpy/lib/tests/test_ufunclike.py
  numpy/linalg/_linalg.py
  numpy/ma/core.py
  numpy/ma/core.pyi
  numpy/typing/tests/data/reveal/ndarray_misc.pyi
Labels: 07 - Deprecation

#25131 MAINT: Update main after 1.26.2 release.
  doc/changelog/1.26.2-changelog.rst
  doc/source/release.rst
  doc/source/release/1.26.2-notes.rst
Labels: 03 - Maintenance

#25085 BLD: limit scipy-openblas32 wheel to 0.3.23.293.2
  .github/workflows/linux.yml
  .github/workflows/linux_compiler_sanitizers.yml
  .github/workflows/linux_musl.yml
  .github/workflows/windows.yml
  azure-pipelines.yml
  azure-steps-windows.yml
  tools/ci/run_32_bit_linux_docker.sh
Labels: 36 - Build

#25022 Add None to array_api __getitem__
  numpy/array_api/_array_object.py
Labels: component: numpy.array_api

#25144 DOC: Fix typo in NumPy 2.0 migration guide
  doc/source/numpy_2_0_migration_guide.rst
Labels: 04 - Documentation

#25140 DOC: clarify boolean index error message
  numpy/_core/src/multiarray/mapping.c
  numpy/_core/tests/test_indexing.py
Labels: 04 - Documentation

#25146 BUG: fix issues with `newaxis` and `linalg.solve` in `numpy.array_api`
  numpy/array_api/__init__.py
  numpy/array_api/_constants.py
  numpy/array_api/linalg.py
Labels: 00 - Bug, 03 - Maintenance, 09 - Backport-Candidate, component: numpy.array_api

#25141 TST: Explicitly pass NumPy path to cython during tests (also speed them up)
  numpy/_core/tests/examples/cython/meson.build
  numpy/_core/tests/test_cython.py
Labels: 05 - Testing, 09 - Backport-Candidate

#25138 API: Remove The MapIter API from public
  doc/release/upcoming_changes/25138.c_api_removal.rst
  doc/source/reference/c-api/array.rst
  numpy/_core/code_generators/cversions.txt
  numpy/_core/code_generators/generate_numpy_api.py
  numpy/_core/code_generators/numpy_api.py
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/src/common/lowlevel_strided_loops.h
  numpy/_core/src/multiarray/_multiarray_tests.c.src
  numpy/_core/src/multiarray/mapping.c
  numpy/_core/src/multiarray/mapping.h
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_multiarray.py
Labels: 30 - API, Numpy 2.0 API Changes

#25104 ENH: Add str_len & count ufuncs for unicode and bytes dtypes
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/defchararray.py
  numpy/_core/src/umath/string_ufuncs.cpp
Labels: 01 - Enhancement

#25129 BUG: Fix FP overflow error in division when the divisor is scalar
  numpy/_core/src/umath/loops_arithm_fp.dispatch.c.src
  numpy/_core/tests/test_umath.py
Labels: 00 - Bug, 09 - Backport-Candidate, component: SIMD

#25136 BUG: Fix -fsanitize=alignment issue in numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/arraytypes.c.src
Labels: 00 - Bug, 09 - Backport-Candidate

#24691 ENH: Add the Array Iterator API to Cython
  numpy/__init__.cython-30.pxd
  numpy/_core/tests/examples/cython/checks.pyx
  numpy/_core/tests/test_cython.py
Labels: 01 - Enhancement

#25156 API: Remove PyArray_REFCNT and NPY_REFCOUNT
  doc/release/upcoming_changes/25156.c_api_removal.rst
  doc/source/reference/c-api/array.rst
  numpy/__init__.pxd
  numpy/_core/include/numpy/ndarrayobject.h
  numpy/_core/src/multiarray/shape.c
Labels: 30 - API

#25165 DOC: mention submodule init in source install instructions
  INSTALL.rst
  doc/source/user/building.rst
Labels: 04 - Documentation

#25158 API: Make `encoding=None` the default in loadtxt
  doc/release/upcoming_changes/25158.compatibility.rst
  doc/source/user/basics.io.genfromtxt.rst
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/defchararray.py
  numpy/lib/_function_base_impl.py
  numpy/lib/_npyio_impl.py
  numpy/lib/tests/test_io.py
  numpy/lib/tests/test_loadtxt.py
  numpy/testing/_private/extbuild.py
Labels: 30 - API

#24869 BUG: Fix ma.convolve if propagate_mask=False
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
Labels: 00 - Bug, component: numpy.ma

#25154 MAINT: Cleanup mapiter struct a bit
  numpy/_core/src/multiarray/lowlevel_strided_loops.c.src
  numpy/_core/src/multiarray/mapping.c
  numpy/_core/src/multiarray/mapping.h
  numpy/_core/src/umath/ufunc_object.c
Labels: 03 - Maintenance

#24949 API: Enforce ABI version and print info when compiled against 1.x
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/core/_multiarray_umath.py
Labels: 30 - API

#25160 BUG: Fix moving compiled executable to root with f2py -c on Windows
  numpy/f2py/_backends/_meson.py
Labels: 00 - Bug, component: numpy.f2py, 09 - Backport-Candidate

#24939 DOC: Add legacy directive to mark outdated objects
  doc/source/_static/numpy.css
  doc/source/conf.py
  doc/source/dev/howto-docs.rst
Labels: 04 - Documentation

#25181 BUG: Disallow shadowed modulenames
  doc/release/upcoming_changes/25181.compatibility.rst
  doc/source/f2py/usage.rst
  numpy/f2py/f2py2e.py
  numpy/f2py/tests/src/cli/gh_22819.pyf
  numpy/f2py/tests/test_f2py2e.py
Labels: 00 - Bug

#25185 MAINT: Fix sneaky typo [f2py]
  numpy/f2py/f2py2e.py
  numpy/f2py/tests/test_f2py2e.py
Labels: 00 - Bug, component: numpy.f2py, 03 - Maintenance

#25192 MAINT: Pin scipy-openblas version.
  .github/workflows/linux_musl.yml
  .github/workflows/windows.yml
  azure-steps-windows.yml
Labels: 05 - Testing, 03 - Maintenance

#25186 BUG: Handle `common` blocks with `kind` specifications from modules
  doc/release/upcoming_changes/25186.improvement.rst
  numpy/f2py/auxfuncs.py
  numpy/f2py/cfuncs.py
  numpy/f2py/common_rules.py
  numpy/f2py/f90mod_rules.py
  numpy/f2py/tests/src/common/gh19161.f90
  numpy/f2py/tests/test_common.py
Labels: 00 - Bug, component: numpy.f2py

#25188 TYP: add None to ``__getitem__`` in ``numpy.array_api``
  numpy/array_api/_array_object.py
Labels: 08 - Backport, Static typing, component: numpy.array_api

#25191 BUG: Fix FP overflow error in division when the divisor is scalar
  numpy/core/src/umath/loops_arithm_fp.dispatch.c.src
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, 08 - Backport, component: SIMD

#25190 BUG: alpha doesn't use REAL(10)
  numpy/f2py/crackfortran.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#25189 BLD,BUG: quadmath required where available [f2py]
  doc/source/f2py/windows/index.rst
  numpy/f2py/_backends/meson.build.template
Labels: component: numpy.f2py, 08 - Backport, 36 - Build

#25176 DOC: replace integer overflow example
  doc/source/user/basics.types.rst
Labels: 04 - Documentation

#25198 MAINT: Replace deprecated ctypes.ARRAY(item_type, size) with item_type * size
  numpy/_core/tests/test_ufunc.py
Labels: 03 - Maintenance

#24791 BUG: Fix f2py to enable use of string optional inout argument
  numpy/f2py/cfuncs.py
  numpy/f2py/tests/src/string/gh24662.f90
  numpy/f2py/tests/test_character.py
Labels: 00 - Bug, component: numpy.f2py, 09 - Backport-Candidate

#25203 TST: Explicitly pass NumPy path to cython during tests (also speed them up)
  numpy/core/tests/examples/cython/meson.build
  numpy/core/tests/test_cython.py
Labels: 05 - Testing, 08 - Backport

#25201 BUG: Fix f2py to enable use of string optional inout argument
  numpy/f2py/cfuncs.py
  numpy/f2py/tests/src/string/gh24662.f90
  numpy/f2py/tests/test_character.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#25202 BUG: Fix -fsanitize=alignment issue in numpy/_core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/arraytypes.c.src
Labels: 00 - Bug, 08 - Backport

#25204 BUG: fix issues with ``newaxis`` and ``linalg.solve`` in ``numpy.array_api``
  numpy/array_api/__init__.py
  numpy/array_api/_constants.py
  numpy/array_api/linalg.py
Labels: 00 - Bug, 03 - Maintenance, 08 - Backport, component: numpy.array_api

#25195 BUG: Fix single to half-precision conversion on PPC64/VSX3
  numpy/_core/src/common/half.hpp
Labels: 00 - Bug, 09 - Backport-Candidate

#25205 BUG: Disallow shadowed modulenames
  doc/release/upcoming_changes/25181.compatibility.rst
  doc/source/f2py/usage.rst
  numpy/f2py/f2py2e.py
  numpy/f2py/setup.py
  numpy/f2py/tests/src/cli/gh_22819.pyf
  numpy/f2py/tests/test_f2py2e.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#25209 ENH: Expose abstract DType classes in the experimental DType API
  numpy/_core/include/numpy/experimental_dtype_api.h
  numpy/_core/src/multiarray/experimental_public_dtype_api.c
Labels: 01 - Enhancement

#25217 BUG: Handle common blocks with kind specifications from modules
  doc/release/upcoming_changes/25186.improvement.rst
  numpy/f2py/auxfuncs.py
  numpy/f2py/cfuncs.py
  numpy/f2py/common_rules.py
  numpy/f2py/f90mod_rules.py
  numpy/f2py/tests/src/callback/gh25211.f
  numpy/f2py/tests/src/callback/gh25211.pyf
  numpy/f2py/tests/src/common/gh19161.f90
  numpy/f2py/tests/test_callback.py
  numpy/f2py/tests/test_common.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#25218 BUG: Fix moving compiled executable to root with f2py -c on Windows
  numpy/f2py/_backends/_meson.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#25219 BUG: Fix single to half-precision conversion on PPC64/VSX3
  numpy/core/src/common/half.hpp
Labels: 00 - Bug, 08 - Backport

#25184 MAINT,DOC: Fix inline licenses `f2py`
  doc/source/f2py/index.rst
  numpy/f2py/__init__.py
  numpy/f2py/_isocbind.py
  numpy/f2py/auxfuncs.py
  numpy/f2py/capi_maps.py
  numpy/f2py/cb_rules.py
  numpy/f2py/cfuncs.py
  numpy/f2py/common_rules.py
  numpy/f2py/crackfortran.py
  numpy/f2py/f2py2e.py
  numpy/f2py/f90mod_rules.py
  numpy/f2py/func2subr.py
  numpy/f2py/rules.py
  numpy/f2py/symbolic.py
  numpy/f2py/use_rules.py
Labels: 04 - Documentation, component: numpy.f2py, 03 - Maintenance, 09 - Backport-Candidate

#25162 NEP: Update NEP 55
  doc/neps/_static/nep-0055-arena-string-memory-layout.svg
  doc/neps/_static/nep-0055-heap-string-memory-layout.svg
  doc/neps/_static/nep-0055-short-string-memory-layout.svg
  doc/neps/nep-0055-string_dtype.rst
Labels: component: NEP

#25222 DOC: Fix wrong return type for PyArray_CastScalarToCType
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#25221 TST: f2py: fix issue in test skip condition
  numpy/f2py/tests/test_f2py2e.py
Labels: 05 - Testing, component: numpy.f2py, 03 - Maintenance, 09 - Backport-Candidate

#25194 DOC: Try to be nicer about compile
  doc/source/f2py/usage.rst
  numpy/f2py/__init__.py
  numpy/f2py/_backends/_distutils.py
  numpy/f2py/tests/test_compile_function.py
Labels: 04 - Documentation

#25123 MAINT,BUG: Never import distutils above 3.12 [f2py]
  numpy/f2py/f2py2e.py
  numpy/f2py/tests/test_f2py2e.py
Labels: 00 - Bug, component: numpy.f2py, 03 - Maintenance, 09 - Backport-Candidate

#25227 TST: f2py: fix issue in test skip condition
  numpy/f2py/tests/test_f2py2e.py
Labels: 05 - Testing, component: numpy.f2py, 03 - Maintenance, 08 - Backport

#25196 DOC: `f2py` rewrite with `meson` details
  doc/source/f2py/buildtools/distutils-to-meson.rst
  doc/source/f2py/buildtools/distutils.rst
  doc/source/f2py/buildtools/index.rst
  doc/source/f2py/buildtools/meson.rst
  doc/source/f2py/f2py-examples.rst
  doc/source/f2py/f2py.getting-started.rst
  doc/source/f2py/index.rst
  doc/source/f2py/python-usage.rst
  doc/source/f2py/signature-file.rst
  doc/source/f2py/usage.rst
  doc/source/f2py/windows/index.rst
Labels: 04 - Documentation, component: numpy.f2py, 09 - Backport-Candidate

#25193 MAINT: Kill all instances of f2py.compile
  doc/release/upcoming_changes/25193.compatibility.rst
  doc/source/f2py/code/results/compile_session.dat
  doc/source/f2py/usage.rst
  numpy/f2py/__init__.py
  numpy/f2py/tests/test_compile_function.py
Labels: component: numpy.f2py, 03 - Maintenance, 07 - Deprecation

#15457 BUG: Adds support for array parameter declaration in fortran code
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/src/parameter/constant_array.f90
  numpy/f2py/tests/test_crackfortran.py
  numpy/f2py/tests/test_parameter.py
Labels: 00 - Bug, component: numpy.f2py

#25111 TST: Use `meson` for testing ``f2py``
  numpy/distutils/tests/test_build_ext.py
  numpy/distutils/tests/utilities.py
  numpy/f2py/_backends/_meson.py
  numpy/f2py/tests/test_abstract_interface.py
  numpy/f2py/tests/test_array_from_pyobj.py
  numpy/f2py/tests/test_block_docstring.py
  numpy/f2py/tests/test_callback.py
  numpy/f2py/tests/test_character.py
  numpy/f2py/tests/test_common.py
  numpy/f2py/tests/test_crackfortran.py
  numpy/f2py/tests/test_data.py
  numpy/f2py/tests/test_docs.py
  numpy/f2py/tests/test_f2cmap.py
  numpy/f2py/tests/test_isoc.py
  numpy/f2py/tests/test_kind.py
  numpy/f2py/tests/test_mixed.py
  numpy/f2py/tests/test_module_doc.py
  numpy/f2py/tests/test_quoted_character.py
  numpy/f2py/tests/test_return_character.py
  numpy/f2py/tests/test_return_complex.py
  numpy/f2py/tests/test_return_integer.py
  numpy/f2py/tests/test_return_real.py
  numpy/f2py/tests/test_semicolon_split.py
  numpy/f2py/tests/test_value_attrspec.py
  numpy/f2py/tests/util.py
Labels: 05 - Testing, component: numpy.f2py, 09 - Backport-Candidate, component: CI, Meson

#25249 MAINT: do not use ``long`` type
  numpy/random/_generator.pyx
Labels: 03 - Maintenance, 08 - Backport

#25257 TST: PyPy needs another gc.collect on latest versions
  numpy/_core/tests/test_mem_policy.py
Labels: 05 - Testing

#25232 DEV: Enable the `spin lldb`
  build_requirements.txt
  pyproject.toml
Labels: 16 - Development

#25149 API: bump MAXDIMS/MAXARGS to 64 introduce NPY_AXIS_RAVEL
  doc/release/upcoming_changes/25149.c_api.rst
  doc/release/upcoming_changes/25149.c_api_removal.rst
  doc/release/upcoming_changes/25149.change.rst
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/types-and-structures.rst
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/_core/include/numpy/ndarrayobject.h
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/src/multiarray/_multiarray_tests.c.src
  numpy/_core/src/multiarray/calculation.c
  numpy/_core/src/multiarray/compiled_base.c
  numpy/_core/src/multiarray/conversion_utils.c
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/iterators.c
  numpy/_core/src/multiarray/methods.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/multiarray/refcount.c
  numpy/_core/src/multiarray/sequence.c
  numpy/_core/tests/test_conversion_utils.py
  numpy/_core/tests/test_indexing.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_numeric.py
  numpy/_core/tests/test_overrides.py
  numpy/_core/tests/test_regression.py
  numpy/_core/tests/test_shape_base.py
  numpy/_core/tests/test_umath.py
Labels: 30 - API

#25167 MAINT: Add ``array-api-tests`` CI stage, add ``ndarray.__array_namespace__``
  .github/workflows/linux.yml
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_core/src/multiarray/methods.c
  numpy/_core/tests/test_regression.py
  tools/ci/array-api-skips.txt
Labels: 03 - Maintenance, Numpy 2.0 API Changes

#25271 API: Shrink MultiIterObject and make `NPY_MAXARGS` a runtime macro
  doc/release/upcoming_changes/25271.c_api.rst
  doc/source/reference/c-api/array.rst
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/include/numpy/npy_2_compat.h
Labels: 30 - API

#25250 DOC: fix typo (alignment)
  doc/source/user/basics.indexing.rst
Labels: 04 - Documentation

#25248 DOC: Add release note for Highway VQSort on AArch64
  doc/release/upcoming_changes/24018.improvement.rst
Labels: 04 - Documentation

#25272 DOC: Mention installing threadpoolctl in issue template [skip ci]
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: 04 - Documentation

#25267 BUG: Fix module name bug in signature files [urgent] [f2py]
  numpy/f2py/f2py2e.py
  numpy/f2py/tests/test_f2py2e.py
Labels: 00 - Bug, component: numpy.f2py, 09 - Backport-Candidate
