Repository numpy/numpy, pull requests merged in 2023-06, with the labels that each got.

#23854 DOC:removed examples which refers to a non existent function
  numpy/lib/npyio.py
Labels: 04 - Documentation

#23857 BUG: fix cron syntax
  .github/workflows/wheels.yml
Labels: 00 - Bug

#23855 BUG: make use of locals() in a comprehension fully compatible with Python 3.12
  numpy/core/arrayprint.py
Labels: 00 - Bug

#23859 DOC: Note that f2py isn't consiered safe
  doc/source/reference/security.rst
Labels: 04 - Documentation

#23729 ENH: allow int sequences as shape arguments in numpy.memmap
  doc/release/upcoming_changes/23729.improvement.rst
  numpy/core/memmap.py
  numpy/core/tests/test_memmap.py
Labels: 01 - Enhancement

#23861 MAINT: Remove all "NumPy 2" as that should be main now
  .github/workflows/build_test.yml
  doc/release/upcoming_changes/23861.change.rst
  doc/source/reference/global_state.rst
  numpy/__init__.py
  numpy/core/multiarray.py
  numpy/core/numeric.py
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/multiarray/multiarraymodule.h
  numpy/lib/function_base.py
  numpy/lib/tests/test_function_base.py
Labels: 03 - Maintenance

#23868 DOC: Fix `NPY_OUT_ARRAY` to `NPY_ARRAY_OUT_ARRAY` in how-to-extend guide
  doc/source/user/c-info.how-to-extend.rst
Labels: 04 - Documentation

#23846 TST: Add tests for np.argsort
  numpy/core/tests/test_multiarray.py
Labels: 05 - Testing

#23871 NEP: Fix NEP 53 file format and minor formatting issue
  doc/neps/nep-0053-c-abi-evolution.rst
Labels: 04 - Documentation, 03 - Maintenance, 09 - Backport-Candidate

#23876 NEP: Fix NEP 53 file format and minor formatting issue
  doc/neps/nep-0053-c-abi-evolution.rst
Labels: 04 - Documentation, 03 - Maintenance, 08 - Backport, component: NEP

#23875 MAINT: Update ``download-wheels``.
  tools/download-wheels.py
Labels: 03 - Maintenance, 08 - Backport

#23877 DOC: update distutils migration guide
  doc/source/reference/distutils_status_migration.rst
Labels: 04 - Documentation, 08 - Backport

#23872 DOC: Try to clarify the `NPY_TARGET_VERSION` release note
  doc/source/release/1.25.0-notes.rst
Labels: 04 - Documentation

#23882 TST: Add tests for np.argsort (#23846)
  numpy/core/tests/test_multiarray.py
Labels: 05 - Testing, 08 - Backport

#23888 TYP,DOC: Annotate and document the ``metadata`` parameter of the ``dtype`` constructor
  numpy/__init__.pyi
  numpy/core/_add_newdocs.py
  numpy/typing/tests/data/reveal/dtype.pyi
Labels: 04 - Documentation, 08 - Backport, Static typing

#23890 TYP,DOC: Annotate and document the ``metadata`` parameter of the ``dtype`` constructor
  numpy/__init__.pyi
  numpy/core/_add_newdocs.py
  numpy/typing/tests/data/reveal/dtype.pyi
Labels: 04 - Documentation, 08 - Backport, Static typing

#23897 DOC: Fix transpose() description with a correct reference to atleast_2d()
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#23902 MAINT: Use ``--allow-downgrade`` option for rtools.
  azure-steps-windows.yml
Labels: 03 - Maintenance, 09 - Backport-Candidate

#23905 MAINT: Use ``--allow-downgrade`` option for rtools.
  azure-steps-windows.yml
Labels: 03 - Maintenance, 08 - Backport

#23911 BUG: Allow np.info on non-hashable objects with a dtype
  numpy/core/getlimits.py
  numpy/core/tests/test_getlimits.py
Labels: 00 - Bug, 09 - Backport-Candidate

#23898 API: Change string to bool conversions to be consistent with Python
  doc/release/upcoming_changes/23871.change.rst
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/tests/test_api.py
  numpy/core/tests/test_multiarray.py
Labels: 30 - API, 62 - Python API

#23914 DOC: Fix reference `ComplexWarning` in release note
  doc/source/release/1.5.0-notes.rst
Labels: 04 - Documentation

#23906 MAINT: Use vectorcall for call forwarding in methods
  numpy/core/src/multiarray/methods.c
  numpy/core/tests/test_argparse.py
Labels: 03 - Maintenance

#23915 DOC: Update development_environment doc.
  doc/source/dev/depending_on_numpy.rst
  doc/source/dev/development_environment.rst
  doc/source/dev/index.rst
Labels: 04 - Documentation

#23920 DOC: fix DOI on badge
  README.md
Labels: 04 - Documentation

#23921 DEP: Expire the PyDataMem_SetEventHook deprecation and remove it
  doc/release/upcoming_changes/23921.expired.rst
  doc/source/reference/c-api/data_memory.rst
  numpy/core/code_generators/cversions.txt
  numpy/core/code_generators/numpy_api.py
  numpy/core/include/numpy/ndarraytypes.h
  numpy/core/src/multiarray/_multiarray_tests.c.src
  numpy/core/src/multiarray/alloc.c
  numpy/core/tests/test_deprecations.py
Labels: 07 - Deprecation

#23925 MAINT: Disable SIMD version of float64 sin and cos
  numpy/core/src/umath/loops_trigonometric.dispatch.c.src
  numpy/core/tests/data/generate_umath_validation_data.cpp
  numpy/core/tests/data/umath-validation-set-cos.csv
  numpy/core/tests/data/umath-validation-set-sin.csv
Labels: 03 - Maintenance, 09 - Backport-Candidate

#23927 DOC: Fix references to `r_` in `mr_class` docstring
  numpy/ma/extras.py
Labels: 04 - Documentation

#23932 BUG: Allow np.info on non-hashable objects with a dtype
  numpy/core/getlimits.py
  numpy/core/tests/test_getlimits.py
Labels: 00 - Bug, 08 - Backport

#23933 MAINT: Disable SIMD version of float64 sin and cos
  numpy/core/src/umath/loops_trigonometric.dispatch.c.src
  numpy/core/tests/data/generate_umath_validation_data.cpp
  numpy/core/tests/data/umath-validation-set-cos.csv
  numpy/core/tests/data/umath-validation-set-sin.csv
Labels: 03 - Maintenance, 08 - Backport

#23922 API: Remove `seterrobj`/`geterrobj`/`extobj=` and related C-API functions
  doc/release/upcoming_changes/23922.c_api_removal.rst
  doc/release/upcoming_changes/23922.python_removal.rst
  doc/source/reference/c-api/ufunc.rst
  doc/source/reference/ufuncs.rst
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/_typing/_ufunc.pyi
  numpy/array_api/linalg.py
  numpy/core/_add_newdocs.py
  numpy/core/_internal.py
  numpy/core/_ufunc_config.py
  numpy/core/code_generators/cversions.txt
  numpy/core/code_generators/numpy_api.py
  numpy/core/fromnumeric.pyi
  numpy/core/multiarray.py
  numpy/core/multiarray.pyi
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/umath/extobj.c
  numpy/core/src/umath/extobj.h
  numpy/core/src/umath/reduction.c
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_errstate.py
  numpy/core/tests/test_numeric.py
  numpy/core/tests/test_ufunc.py
  numpy/core/umath.py
  numpy/linalg/linalg.py
  numpy/typing/tests/data/pass/ufuncs.py
  numpy/typing/tests/data/reveal/multiarray.pyi
  pyproject.toml
Labels: 30 - API

#23941 BUG: Fix NpyIter cleanup in einsum error path
  numpy/core/src/multiarray/einsum.c.src
Labels: 00 - Bug, 09 - Backport-Candidate

#23881 ENH: Add array API standard v2022.12 support to numpy.array_api
  doc/release/upcoming_changes/23789.new_feature.rst
  numpy/array_api/__init__.py
  numpy/array_api/_array_object.py
  numpy/array_api/_data_type_functions.py
  numpy/array_api/_dtypes.py
  numpy/array_api/_elementwise_functions.py
  numpy/array_api/_searching_functions.py
  numpy/array_api/_sorting_functions.py
  numpy/array_api/_statistical_functions.py
  numpy/array_api/linalg.py
  numpy/array_api/tests/test_array_object.py
  numpy/array_api/tests/test_data_type_functions.py
  numpy/array_api/tests/test_elementwise_functions.py
Labels: 01 - Enhancement, component: numpy.array_api

#23847 MAINT: const correctness for the generalized ufunc C API
  doc/release/upcoming_changes/23847.c_api.rst
  numpy/core/include/numpy/ufuncobject.h
  numpy/core/src/umath/dispatching.c
  numpy/core/src/umath/ufunc_object.c
  numpy/core/src/umath/ufunc_type_resolution.c
Labels: 03 - Maintenance

#23943 DOC: Update required C++ version in building.rst (and copy-edit).
  doc/source/user/building.rst
Labels: 04 - Documentation, 09 - Backport-Candidate

#23830 API: deprecate compat and selected lib utils
  numpy/__init__.py
  numpy/_utils/_convertions.py
  numpy/compat/__init__.py
  numpy/compat/tests/test_compat.py
  numpy/core/_methods.py
  numpy/core/_type_aliases.py
  numpy/core/defchararray.py
  numpy/core/memmap.py
  numpy/core/numerictypes.py
  numpy/core/records.py
  numpy/core/setup.py
  numpy/core/src/multiarray/methods.h
  numpy/core/tests/test_datetime.py
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_dtype.py
  numpy/core/tests/test_multiarray.py
  numpy/core/tests/test_overrides.py
  numpy/core/tests/test_records.py
  numpy/core/tests/test_regression.py
  numpy/core/tests/test_ufunc.py
  numpy/f2py/tests/util.py
  numpy/lib/_iotools.py
  numpy/lib/format.py
  numpy/lib/npyio.py
  numpy/lib/tests/test_io.py
  numpy/lib/tests/test_regression.py
  numpy/lib/tests/test_utils.py
  numpy/lib/utils.py
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
  numpy/ma/tests/test_mrecords.py
  numpy/ma/tests/test_old_ma.py
  numpy/matrixlib/tests/test_masked_matrix.py
  numpy/random/tests/test_generator_mt19937.py
  numpy/random/tests/test_random.py
  numpy/random/tests/test_randomstate.py
  numpy/tests/test_public_api.py
  numpy/tests/test_reloading.py
  numpy/typing/tests/data/fail/lib_utils.pyi
  numpy/typing/tests/data/pass/lib_utils.py
  numpy/typing/tests/data/reveal/lib_utils.pyi
Labels: 30 - API

#23923 BUG:Fix for call to 'vec_st' is ambiguous
  numpy/core/src/common/simd/vec/memory.h
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/tests/test_ccompiler_opt.py
Labels: 00 - Bug, component: SIMD, 36 - Build

#23945 BUG: Fixup for win64 fwrite issue
  numpy/core/src/multiarray/convert.c
Labels: 00 - Bug, 08 - Backport

#23950 MAINT: Upgrade install-rtools version
  .github/workflows/wheels.yml
Labels: 03 - Maintenance, 09 - Backport-Candidate, 36 - Build

#23951 MAINT: Upgrade install-rtools version
  .github/workflows/wheels.yml
Labels: 03 - Maintenance, 08 - Backport

#23946 BUG: Fix NpyIter cleanup in einsum error path
  numpy/core/src/multiarray/einsum.c.src
Labels: 00 - Bug, 08 - Backport

#23948 DOC: Update required C++ version in building.rst (and copy-edit).
  doc/source/user/building.rst
Labels: 04 - Documentation, 08 - Backport

#23949 BUG:Fix for call to 'vec_st' is ambiguous
  numpy/core/src/common/simd/vec/memory.h
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/tests/test_ccompiler_opt.py
Labels: 00 - Bug, 08 - Backport, 36 - Build

#23953 BUG: Fix AVX2 intrinsic npyv_store2_till_s64 on MSVC > 19.29
  numpy/core/src/common/simd/avx2/memory.h
Labels: 00 - Bug, 09 - Backport-Candidate, component: SIMD

#23955 ENH: Add array API standard v2022.12 support to numpy.array_api
  doc/release/upcoming_changes/23789.new_feature.rst
  numpy/array_api/__init__.py
  numpy/array_api/_array_object.py
  numpy/array_api/_data_type_functions.py
  numpy/array_api/_dtypes.py
  numpy/array_api/_elementwise_functions.py
  numpy/array_api/_searching_functions.py
  numpy/array_api/_sorting_functions.py
  numpy/array_api/_statistical_functions.py
  numpy/array_api/linalg.py
  numpy/array_api/tests/test_array_object.py
  numpy/array_api/tests/test_data_type_functions.py
  numpy/array_api/tests/test_elementwise_functions.py
Labels: 01 - Enhancement, 08 - Backport, component: numpy.array_api

#23956 BUG: Fix AVX2 intrinsic npyv_store2_till_s64 on MSVC > 19.29
  numpy/core/src/common/simd/avx2/memory.h
Labels: 00 - Bug, 08 - Backport, component: SIMD

#23960 DOC: adding release note for 23809
  doc/release/upcoming_changes/23809.expired.rst
Labels: 04 - Documentation

#23961 BLD: update pypy in CI to latest version
  .github/workflows/build_test.yml
Labels: 36 - Build

#23962 TEST: change subprocess call to capture stderr too
  numpy/testing/_private/utils.py
Labels: 09 - Backport-Candidate

#23944 DOC: const correctness in PyUFunc_FromFuncAndData... functions
  doc/source/reference/c-api/ufunc.rst
  doc/source/user/c-info.ufunc-tutorial.rst
Labels: 04 - Documentation

#23963 TEST: change subprocess call to capture stderr too
  numpy/testing/_private/utils.py
Labels: 05 - Testing, component: numpy.testing, 08 - Backport

#23936 ENH,API: Make the errstate/extobj a contextvar
  doc/release/upcoming_changes/23936.change.rst
  doc/release/upcoming_changes/23936.improvement.rst
  doc/source/reference/c-api/ufunc.rst
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/__init__.pyi
  numpy/core/_ufunc_config.py
  numpy/core/include/numpy/ufuncobject.h
  numpy/core/src/common/umathmodule.h
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/umath/extobj.c
  numpy/core/src/umath/extobj.h
  numpy/core/src/umath/ufunc_object.c
  numpy/core/src/umath/ufunc_object.h
  numpy/core/src/umath/umathmodule.c
  numpy/core/umath.py
  numpy/typing/tests/data/reveal/constants.pyi
Labels: 01 - Enhancement

#23965 MAINT: Simplify codespaces conda environment activation
  .devcontainer/setup.sh
Labels: 03 - Maintenance

#23966 REL: Prepare for the NumPy 1.25.0 release
  .mailmap
  doc/changelog/1.25.0-changelog.rst
  doc/source/release/1.25.0-notes.rst
Labels: 14 - Release, 36 - Build

#23964 MAINT: Remove references to removed functions
  doc/source/reference/routines.err.rst
  numpy/core/_ufunc_config.py
Labels: 04 - Documentation, 03 - Maintenance

#23968 MAINT: prepare 1.25.x for further development
  doc/source/dev/depending_on_numpy.rst
  doc/source/release.rst
  doc/source/release/1.25.1-notes.rst
  pavement.py
Labels: 03 - Maintenance

#23969 MAINT: Update main after 1.25.0 release.
  .mailmap
  doc/changelog/1.25.0-changelog.rst
  doc/source/release/1.25.0-notes.rst
Labels: 04 - Documentation, 03 - Maintenance

#23982 BLD: Port long double identification to C for meson
  numpy/core/meson.build
Labels: 36 - Build

#23838 BLD: switch to meson-python as the default build backend
  .circleci/config.yml
  .github/workflows/build_test.yml
  .github/workflows/emscripten.yml
  .github/workflows/wheels.yml
  azure-pipelines.yml
  azure-steps-windows.yml
  meson.build
  numpy/core/tests/test_arrayprint.py
  numpy/core/tests/test_einsum.py
  numpy/core/tests/test_longdouble.py
  numpy/core/tests/test_mem_policy.py
  numpy/core/tests/test_print.py
  numpy/core/tests/test_scalarprint.py
  numpy/core/tests/test_strings.py
  numpy/core/tests/test_umath.py
  numpy/f2py/tests/test_return_integer.py
  numpy/f2py/tests/test_return_real.py
  numpy/meson.build
  numpy/random/tests/test_extending.py
  numpy/tests/test_public_api.py
  pyproject.toml
  pyproject.toml.setuppy
  tools/ci/cirrus_wheels.yml
  tools/openblas_support.py
  tools/wheels/check_license.py
  tools/wheels/cibw_before_build.sh
  tools/wheels/cibw_test_command.sh
  tools/wheels/repair_windows.sh
Labels: component: build, 36 - Build, Meson

#23983 BLD: change file extension for installed static libraries back to `.lib`
  numpy/core/meson.build
  numpy/meson.build
  numpy/random/meson.build
  numpy/random/tests/test_extending.py
Labels: component: numpy.random, 36 - Build, Meson

#23985 Revert "TST: disable longdouble string/print tests on Linux aarch64"
  numpy/core/tests/test_arrayprint.py
  numpy/core/tests/test_longdouble.py
  numpy/core/tests/test_print.py
  numpy/core/tests/test_scalarprint.py
  numpy/core/tests/test_strings.py
Labels: 03 - Maintenance

#23990 DOC: Fix np.vectorize Doc
  numpy/lib/function_base.py
Labels: 04 - Documentation

#23913 ENH: let zeros, empty, and empty_like accept dtype classes
  numpy/core/src/multiarray/ctors.c
  numpy/core/src/multiarray/ctors.h
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/tests/test_custom_dtypes.py
  numpy/core/tests/test_numeric.py
Labels: 01 - Enhancement

#23995 MAINT: Do not use ``--side-by-side`` choco option
  azure-steps-windows.yml
Labels: 03 - Maintenance

#23980 MAINT: use `yield from` where applicable
  numpy/array_api/tests/test_array_object.py
  numpy/lib/tests/test_loadtxt.py
Labels: 03 - Maintenance

#23997 MAINT: make naming of C aliases for dtype classes consistent
  numpy/core/include/numpy/_dtype_api.h
  numpy/core/include/numpy/experimental_dtype_api.h
Labels: 03 - Maintenance

#23991 CI: BLD: build wheels and fix test suite for Python 3.12
  .github/workflows/wheels.yml
  numpy/__init__.py
  numpy/_pytesttester.py
  numpy/core/tests/test_array_interface.py
  numpy/core/tests/test_dtype.py
  numpy/core/tests/test_mem_policy.py
  numpy/core/tests/test_regression.py
  numpy/lib/tests/test_format.py
  numpy/meson.build
  numpy/random/tests/test_extending.py
  numpy/tests/test_ctypeslib.py
  numpy/tests/test_public_api.py
  numpy/typing/tests/test_isfile.py
  test_requirements.txt
  tools/ci/cirrus_wheels.yml
Labels: 36 - Build

#24004 BUG: Fix reduction `return NULL` to be `goto fail`
  numpy/core/src/umath/reduction.c
Labels: 00 - Bug, 09 - Backport-Candidate

#23998 DEP: Expire `set_numeric_ops` and the corresponding C functions deprecation
  doc/release/upcoming_changes/23998.expired.rst
  doc/source/reference/c-api/array.rst
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/core/_add_newdocs.py
  numpy/core/code_generators/cversions.txt
  numpy/core/code_generators/numpy_api.py
  numpy/core/multiarray.py
  numpy/core/numeric.py
  numpy/core/src/multiarray/_multiarray_tests.c.src
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/multiarray/number.c
  numpy/core/src/multiarray/number.h
  numpy/core/tests/test_deprecations.py
  tools/functions_missing_types.py
Labels: 07 - Deprecation

#24012 MAINT: Remove hardcoded f2py numeric/numarray compatibility switch
  numpy/f2py/capi_maps.py
Labels: 03 - Maintenance

#24011 API: Remove `old_defines.h` (part of NumPy 1.7 deprecated C-API)
  doc/release/upcoming_changes/24011.c_api_removal.rst
  numpy/core/include/meson.build
  numpy/core/include/numpy/npy_1_7_deprecated_api.h
  numpy/core/include/numpy/old_defines.h
Labels: 30 - API

#23979 MAINT: Fix typos found by codespell
  doc/release/upcoming_changes/23871.change.rst
  doc/source/reference/security.rst
  numpy/core/include/numpy/_dtype_api.h
  numpy/core/include/numpy/numpyconfig.h
  numpy/core/numeric.py
  numpy/core/tests/test_cpu_features.py
  numpy/core/tests/test_einsum.py
  numpy/core/tests/test_nditer.py
  site.cfg.example
Labels: 03 - Maintenance

#23977 MAINT: pipes.quote → shlex.quote
  numpy/distutils/_shell_utils.py
Labels: 03 - Maintenance

#24027 DOC: Fix reference to `__array_struct__` in `arrays.interface.rst`
  doc/source/reference/arrays.interface.rst
Labels: 04 - Documentation

#24030 BUG: Avoid undefined behavior in array.astype()
  numpy/core/src/multiarray/methods.c
  numpy/core/tests/test_api.py
Labels: 00 - Bug, 09 - Backport-Candidate

#24031 BUG: Ensure __array_ufunc__ works without any kwargs passed
  numpy/core/src/multiarray/methods.c
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, 09 - Backport-Candidate

#24036 BLD: Port long double identification to C for meson
  numpy/core/meson.build
Labels: 08 - Backport, 36 - Build, Meson

#24037 BUG: Fix reduction ``return NULL`` to be ``goto fail``
  numpy/core/src/umath/reduction.c
Labels: 00 - Bug, 08 - Backport

#24038 BUG: Avoid undefined behavior in array.astype()
  numpy/core/src/multiarray/methods.c
  numpy/core/tests/test_api.py
Labels: 00 - Bug, 08 - Backport

#24039 BUG: Ensure ``__array_ufunc__`` works without any kwargs passed
  numpy/core/src/multiarray/methods.c
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, 08 - Backport

#24044 BLD: Use urllib < 2.0.0 for anaconda-client.
  tools/wheels/upload_wheels.sh
Labels: 36 - Build

#24046 DOC: Fix reference to python module `string` in `routines.char.rst`
  doc/source/reference/routines.char.rst
Labels: 04 - Documentation

#24025 TST: improve test for Cholesky decomposition
  numpy/linalg/tests/test_linalg.py
Labels: 05 - Testing

#24048 MAINT: prepare 1.24.x for further development
  doc/source/release.rst
  doc/source/release/1.24.5-notes.rst
  pavement.py
Labels: 03 - Maintenance

#24049 MAINT: Update main after 1.24.4 release.
  doc/changelog/1.24.4-changelog.rst
  doc/source/release.rst
  doc/source/release/1.24.4-notes.rst
Labels: 03 - Maintenance

#24054 BUG: Multiply or divides using SIMD without a full vector can cause divide-by-zero
  numpy/core/src/umath/loops_arithm_fp.dispatch.c.src
Labels: 00 - Bug

#24051 MAINT: Pin urllib3 to avoid anaconda-client bug.
  .github/workflows/wheels.yml
  tools/ci/cirrus_wheels.yml
Labels: 03 - Maintenance, component: build, 09 - Backport-Candidate

#24014 BUG: Make errstate decorator compatible with threading
  numpy/__init__.pyi
  numpy/core/_ufunc_config.py
  numpy/core/tests/test_errstate.py
  numpy/typing/tests/data/reveal/ufunc_config.pyi
Labels: 00 - Bug

#24058 DOC: Remove references to ``PyArray_SetNumericOps`` and ``PyArray_GetNumericOps`` in release note
  doc/source/release/1.16.0-notes.rst
Labels: 04 - Documentation

#24059 MAINT: Remove ability to enter errstate twice (sequentially)
  doc/release/upcoming_changes/23936.change.rst
  numpy/core/_ufunc_config.py
  numpy/core/tests/test_errstate.py
Labels: 03 - Maintenance

#24017 MAINT: Further cleanups for errstate
  numpy/core/src/umath/extobj.c
  numpy/core/src/umath/extobj.h
  numpy/core/src/umath/ufunc_object.c
Labels: 03 - Maintenance

#24060 BLD: use `-ftrapping-math` with Clang on macOS in Meson build
  meson.build
Labels: 36 - Build, Meson

#24071 MAINT: Overwrite previous wheels when uploading to anaconda.
  tools/wheels/upload_wheels.sh
Labels: 03 - Maintenance

#24075 DOC: Add missing indentation in ``ma.mT`` docstring
  numpy/ma/core.py
Labels: 04 - Documentation

#24077 DOC: Fix documentation for `ndarray.mT`
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation

#24076 DOC: Fix incorrect reST markups in ``numpy.void`` docstring
  numpy/core/_add_newdocs_scalars.py
Labels: 04 - Documentation

#24068 DOC: Add NpzFile class documentation.
  doc/source/reference/routines.io.rst
Labels: 04 - Documentation

#24029 DOC: Add link to NEPs in top navbar
  doc/source/conf.py
Labels: 04 - Documentation
