Repository numpy/numpy, pull requests merged in 2023-08, with the labels that each got.

#24311 BLD: update openblas to newer version
  tools/openblas_support.py
Labels: 36 - Build

#24152 DOC: Fix reference warning for recarray.
  doc/source/reference/arrays.classes.rst
  doc/source/reference/routines.array-creation.rst
Labels: 04 - Documentation

#24308 MAINT: Massive update of files from main for numpy 1.26
  .circleci/config.yml
  .cirrus.star
  .github/workflows/build_test.yml
  .github/workflows/emscripten.yml
  .github/workflows/linux_meson.yml
  .github/workflows/linux_musl.yml
  .github/workflows/wheels.yml
  .github/workflows/windows_meson.yml
  .spin/cmds.py
  azure-pipelines.yml
  azure-steps-windows.yml
  build_requirements.txt
  meson_options.txt
  numpy/_utils/__init__.py
  numpy/_utils/_convertions.py
  numpy/core/tests/test_mem_policy.py
  numpy/core/tests/test_umath.py
  numpy/f2py/capi_maps.py
  numpy/f2py/cfuncs.py
  numpy/f2py/tests/test_return_integer.py
  numpy/f2py/tests/test_return_real.py
  numpy/f2py/tests/util.py
  numpy/meson.build
  numpy/random/_examples/cython/setup.py
  numpy/random/_generator.pyx
  numpy/random/_mt19937.pyx
  numpy/random/_pcg64.pyx
  numpy/random/_philox.pyx
  numpy/random/_sfc64.pyx
  numpy/random/bit_generator.pyx
  numpy/random/meson.build
  numpy/random/mtrand.pyx
  numpy/random/src/distributions/distributions.c
  numpy/random/src/mt19937/randomkit.h
  numpy/random/src/pcg64/pcg64.orig.h
  numpy/random/tests/test_extending.py
  numpy/random/tests/test_generator_mt19937.py
  numpy/random/tests/test_generator_mt19937_regressions.py
  numpy/random/tests/test_random.py
  numpy/random/tests/test_randomstate.py
  pyproject.toml
  pyproject.toml.setuppy
  test_requirements.txt
  tools/ci/cirrus_macosx_arm64.yml
  tools/ci/cirrus_wheels.yml
  tools/openblas_support.py
  tools/travis-before-install.sh
  tools/travis-test.sh
  tools/wheels/repair_windows.sh
Labels: 03 - Maintenance

#24322 CI: fix wheel builds on the 1.26.x branch
  .github/workflows/linux_meson.yml
  .github/workflows/wheels.yml
  numpy/__init__.py
  numpy/_pytesttester.py
  numpy/core/meson.build
  numpy/core/tests/test_array_interface.py
  numpy/core/tests/test_dtype.py
  numpy/core/tests/test_regression.py
  numpy/lib/tests/test_format.py
  numpy/tests/test_ctypeslib.py
  numpy/tests/test_public_api.py
  numpy/typing/tests/test_isfile.py
  numpy/typing/tests/test_typing.py
  pyproject.toml
  tools/wheels/check_license.py
  tools/wheels/cibw_before_build.sh
  tools/wheels/cibw_test_command.sh
Labels: component: CI, 36 - Build

#24315 DOC: Fix some links in documents
  doc/source/reference/arrays.scalars.rst
  doc/source/user/basics.rec.rst
  doc/source/user/whatisnumpy.rst
  numpy/core/_add_newdocs.py
  numpy/lib/arrayterator.py
  numpy/lib/recfunctions.py
  numpy/typing/__init__.py
Labels: 04 - Documentation

#24326 BLD: update openblas to newer version
  tools/openblas_support.py
Labels: 08 - Backport, 36 - Build

#24328 BUG: fix choose refcount leak
  numpy/core/src/multiarray/item_selection.c
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug, 08 - Backport

#24312 DEP: Finalize `fastCopyAndTranpose` and other old C-funcs/members deprecations
  doc/release/upcoming_changes/24312.expired.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/types-and-structures.rst
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/core/_add_newdocs.py
  numpy/core/code_generators/cversions.txt
  numpy/core/code_generators/numpy_api.py
  numpy/core/include/numpy/ndarraytypes.h
  numpy/core/multiarray.py
  numpy/core/numeric.py
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/calculation.c
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/src/multiarray/scalarapi.c
  numpy/core/src/multiarray/usertypes.c
  numpy/core/tests/test_api.py
  numpy/tests/test_public_api.py
  tools/functions_missing_types.py
Labels: 07 - Deprecation

#24220 BUG: random: Fix generation of nan by dirichlet.
  numpy/random/_generator.pyx
  numpy/random/tests/test_generator_mt19937.py
  numpy/random/tests/test_randomstate.py
Labels: 00 - Bug, component: numpy.random

#24331 DOC: Fix reference warning for buffer.
  doc/source/reference/arrays.dtypes.rst
  doc/source/reference/arrays.interface.rst
  doc/source/reference/arrays.ndarray.rst
Labels: 04 - Documentation

#24332 DOC: Refactor description of ``PyArray_FromAny/PyArray_CheckFromAny``
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#24338 BUG: random: Fix generation of nan by dirichlet.
  numpy/random/_generator.pyx
  numpy/random/tests/test_generator_mt19937.py
  numpy/random/tests/test_randomstate.py
Labels: 00 - Bug, 08 - Backport

#24337 TST: fix running the test suite in builds without BLAS/LAPACK
  numpy/linalg/tests/test_linalg.py
  numpy/linalg/umath_linalg.cpp
  numpy/testing/_private/utils.py
Labels: 05 - Testing, 08 - Backport

#24340 MAINT: Dependabot updates from main
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/linux_meson.yml
  .github/workflows/scorecards.yml
  .github/workflows/windows_clangcl.yml
Labels: 03 - Maintenance

#24342 MAINT: Add back NPY_RUN_MYPY_IN_TESTSUITE=1
  .github/workflows/linux_meson.yml
Labels: 03 - Maintenance

#24349 BUG: polynomial: Handle non-array inputs in polynomial class __call__ method.
  numpy/polynomial/_polybase.py
  numpy/polynomial/tests/test_classes.py
Labels: 00 - Bug, component: numpy.polynomial

#24346 DOC: use nightly dependencies [skip actions] [azp skip] [skip travis]
  .circleci/config.yml
  doc/source/dev/development_workflow.rst
  doc/source/user/basics.indexing.rst
Labels: 04 - Documentation

#24353 MAINT: Update ``extbuild.py`` from main.
  numpy/testing/_private/extbuild.py
Labels: 03 - Maintenance, Meson

#24354 TST: fix distutils tests for deprecations in recent setuptools versions
  numpy/distutils/tests/test_system_info.py
Labels: 05 - Testing, component: numpy.distutils, 09 - Backport-Candidate

#24356 TST: fix distutils tests for deprecations in recent setuptools versions
  numpy/distutils/tests/test_system_info.py
Labels: 05 - Testing, component: numpy.distutils, 08 - Backport

#24316 API: Cleaning `numpy/__init__.py` and main namespace - Part 1 [NEP 52]
  numpy/__init__.py
  numpy/core/tests/test__exceptions.py
  numpy/core/tests/test_api.py
  numpy/core/tests/test_array_coercion.py
  numpy/core/tests/test_casting_floatingpoint_errors.py
  numpy/core/tests/test_casting_unittests.py
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_einsum.py
  numpy/core/tests/test_indexing.py
  numpy/core/tests/test_mem_overlap.py
  numpy/core/tests/test_multiarray.py
  numpy/core/tests/test_nditer.py
  numpy/core/tests/test_numeric.py
  numpy/core/tests/test_regression.py
  numpy/core/tests/test_scalarmath.py
  numpy/core/tests/test_shape_base.py
  numpy/core/tests/test_ufunc.py
  numpy/exceptions.py
  numpy/lib/arraysetops.py
  numpy/lib/npyio.py
  numpy/lib/tests/test_arraysetops.py
  numpy/lib/tests/test_financial_expired.py
  numpy/lib/tests/test_function_base.py
  numpy/lib/tests/test_io.py
  numpy/lib/tests/test_nanfunctions.py
  numpy/lib/tests/test_shape_base.py
  numpy/linalg/tests/test_linalg.py
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
  numpy/ma/tests/test_extras.py
  numpy/random/tests/test_generator_mt19937.py
  numpy/tests/test_public_api.py
  numpy/tests/test_reloading.py
  numpy/typing/tests/data/fail/warnings_and_errors.pyi
  numpy/typing/tests/data/pass/scalars.py
  numpy/typing/tests/data/pass/warnings_and_errors.py
  numpy/typing/tests/data/reveal/warnings_and_errors.pyi
Labels: 62 - Python API

#24360 BENCH: fix small array det benchmark
  benchmarks/benchmarks/bench_linalg.py
Labels: 28 - Benchmark

#24358 BUG: flexible inheritance segfault
  numpy/core/src/multiarray/scalartypes.c.src
  numpy/core/tests/test_regression.py
Labels: 00 - Bug

#24364 BUG: Remove #undef complex from npy_common.h
  numpy/core/include/numpy/npy_common.h
  numpy/core/src/multiarray/buffer.c
  numpy/linalg/lapack_lite/f2c.c
  numpy/linalg/lapack_lite/f2c.h
  numpy/linalg/lapack_lite/f2c_blas.c
  numpy/linalg/lapack_lite/f2c_blas.c.patch
  numpy/linalg/lapack_lite/f2c_c_lapack.c
  numpy/linalg/lapack_lite/f2c_c_lapack.c.patch
  numpy/linalg/lapack_lite/f2c_config.c
  numpy/linalg/lapack_lite/f2c_lapack.c
  numpy/linalg/lapack_lite/f2c_lapack.c.patch
  numpy/linalg/lapack_lite/make_lite.py
Labels: 00 - Bug

#24362 DOC: Add release notes for complex types changes in 2.x
  doc/release/upcoming_changes/24085.improvement.rst
  doc/source/reference/c-api/coremath.rst
Labels: 04 - Documentation

#24374 MAINT: Update cibuildwheel for cirrus builds
  tools/ci/cirrus_wheels.yml
Labels: 03 - Maintenance, 09 - Backport-Candidate

#24371 MAINT: Fix codespaces setup.sh script
  .devcontainer/setup.sh
Labels: 03 - Maintenance, 09 - Backport-Candidate

#24375 MAINT: Update cibuildwheel to version 2.15.0
  .github/workflows/wheels.yml
  tools/ci/cirrus_wheels.yml
Labels: 03 - Maintenance, 08 - Backport

#24380 DOC: Remove extra indents in documents
  doc/source/reference/arrays.interface.rst
  doc/source/reference/arrays.ndarray.rst
  doc/source/reference/arrays.nditer.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/datetimes.rst
  doc/source/reference/routines.polynomials.classes.rst
  doc/source/user/c-info.how-to-extend.rst
  doc/source/user/how-to-io.rst
  numpy/core/_add_newdocs.py
  numpy/polynomial/__init__.py
Labels: 04 - Documentation

#24381 MAINT: Fix codespaces setup.sh script
  .devcontainer/setup.sh
Labels: 03 - Maintenance, 08 - Backport

#24383 DOC: Fix reference warning for ABCPolyBase.
  numpy/polynomial/chebyshev.py
  numpy/polynomial/hermite.py
  numpy/polynomial/hermite_e.py
  numpy/polynomial/laguerre.py
  numpy/polynomial/legendre.py
  numpy/polynomial/polynomial.py
Labels: 04 - Documentation, component: numpy.polynomial

#23096 BLD, SIMD: The meson CPU dispatcher implementation
  .github/meson_actions/action.yml
  .github/workflows/build_test.yml
  MANIFEST.in
  build_requirements.txt
  doc/source/user/quickstart.rst
  meson.build
  meson_cpu/arm/meson.build
  meson_cpu/main_config.h.in
  meson_cpu/meson.build
  meson_cpu/ppc64/meson.build
  meson_cpu/s390x/meson.build
  meson_cpu/x86/meson.build
  meson_options.txt
  numpy/core/meson.build
  numpy/core/src/_simd/_simd.c
  numpy/core/src/_simd/_simd.dispatch.c.src
  numpy/core/src/common/npy_cpu_dispatch.h
  numpy/core/src/common/simd/sse/arithmetic.h
Labels: 01 - Enhancement, 09 - Backport-Candidate, Meson

#24196 MAINT: Remove versioneer
  .gitattributes
  .gitignore
  MANIFEST.in
  doc/Makefile
  generate_version.py
  meson.build
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_build_utils/gitversion.py
  numpy/_version.py
  numpy/core/__init__.py
  numpy/core/setup.py
  numpy/lib/__init__.py
  numpy/meson.build
  numpy/tests/test_numpy_version.py
  numpy/tests/test_public_api.py
  numpy/typing/tests/data/pass/modules.py
  numpy/typing/tests/data/reveal/modules.pyi
  numpy/typing/tests/data/reveal/version.pyi
  numpy/version.py
  pyproject.toml.setuppy
  setup.py
  tools/lint_diff.ini
  versioneer.py
Labels: 03 - Maintenance, 09 - Backport-Candidate

#24405 BLD, SIMD: The meson CPU dispatcher implementation
  .github/meson_actions/action.yml
  .github/workflows/build_test.yml
  MANIFEST.in
  build_requirements.txt
  doc/source/user/quickstart.rst
  meson.build
  meson_cpu/arm/meson.build
  meson_cpu/main_config.h.in
  meson_cpu/meson.build
  meson_cpu/ppc64/meson.build
  meson_cpu/s390x/meson.build
  meson_cpu/x86/meson.build
  meson_options.txt
  numpy/core/meson.build
  numpy/core/src/_simd/_simd.c
  numpy/core/src/_simd/_simd.dispatch.c.src
  numpy/core/src/common/npy_cpu_dispatch.h
  numpy/core/src/common/simd/sse/arithmetic.h
Labels: 01 - Enhancement, 08 - Backport, 36 - Build, Meson

#24406 MAINT: Remove versioneer
  .gitattributes
  .gitignore
  MANIFEST.in
  doc/Makefile
  generate_version.py
  meson.build
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_build_utils/gitversion.py
  numpy/_version.py
  numpy/core/__init__.py
  numpy/core/setup.py
  numpy/lib/__init__.py
  numpy/meson.build
  numpy/tests/test_numpy_version.py
  numpy/tests/test_public_api.py
  numpy/typing/tests/data/pass/modules.py
  numpy/typing/tests/data/reveal/modules.pyi
  numpy/typing/tests/data/reveal/version.pyi
  numpy/version.py
  pyproject.toml.setuppy
  setup.py
  tools/lint_diff.ini
  versioneer.py
Labels: 03 - Maintenance, 08 - Backport

#24357 API: Cleaning numpy/__init__.py and main namespace - Part 2 [NEP 52]
  doc/source/reference/constants.rst
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/array_api/_array_object.py
  numpy/core/__init__.py
  numpy/core/_type_aliases.py
  numpy/core/code_generators/ufunc_docstrings.py
  numpy/core/function_base.pyi
  numpy/core/numeric.py
  numpy/core/src/multiarray/conversion_utils.c
  numpy/core/src/multiarray/mapping.c
  numpy/core/tests/test_api.py
  numpy/core/tests/test_array_coercion.py
  numpy/core/tests/test_conversion_utils.py
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_function_base.py
  numpy/core/tests/test_nditer.py
  numpy/core/tests/test_ufunc.py
  numpy/core/tests/test_umath.py
  numpy/core/tests/test_umath_complex.py
  numpy/core/umath.py
  numpy/doc/__init__.py
  numpy/doc/constants.py
  numpy/lib/__init__.py
  numpy/lib/__init__.pyi
  numpy/lib/arrayterator.py
  numpy/lib/function_base.py
  numpy/lib/function_base.pyi
  numpy/lib/nanfunctions.py
  numpy/lib/tests/test_function_base.py
  numpy/lib/ufunclike.py
  numpy/lib/utils.py
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
  numpy/testing/tests/test_utils.py
  numpy/tests/test_public_api.py
  numpy/typing/tests/data/fail/constants.pyi
  numpy/typing/tests/data/fail/lib_function_base.pyi
  numpy/typing/tests/data/fail/multiarray.pyi
  numpy/typing/tests/data/reveal/arrayterator.pyi
  numpy/typing/tests/data/reveal/constants.pyi
  numpy/typing/tests/data/reveal/lib_function_base.pyi
  numpy/typing/tests/data/reveal/multiarray.pyi
  tools/functions_missing_types.py
Labels: 62 - Python API

#24400 TST: revert xfail in `test_umath.py`
  numpy/core/tests/test_umath.py
Labels: 05 - Testing, component: numpy.core, 03 - Maintenance

#24409 REL: Prepare for the NumPy 1.26.0b1 release.
  doc/changelog/1.26.0-changelog.rst
  doc/source/release/1.26.0-notes.rst
  numpy/tests/test_ctypeslib.py
  pyproject.toml
  pyproject.toml.setuppy
Labels: 14 - Release, 03 - Maintenance

#24413 BUG: cleanup warnings [skip azp][skip circle][skip travis][skip cirrus]
  numpy/_build_utils/gitversion.py
  numpy/core/src/multiarray/compiled_base.c
Labels: 00 - Bug, 09 - Backport-Candidate

#24412 [BUG] Return value of use_hugepage in hugepage_setup
  numpy/__init__.py
Labels: 03 - Maintenance

#24419 CI/BUG: add Python 3.12 CI job and fix `numpy.distutils` AttributeError
  .github/workflows/build_test.yml
  numpy/__init__.py
  numpy/tests/test_ctypeslib.py
  tools/check_installed_files.py
Labels: 03 - Maintenance, component: CI

#24414 BLD: allow specifying the long double format to avoid the runtime check
  numpy/core/meson.build
Labels: 01 - Enhancement, 36 - Build

#24291 CI: improve test suite runtime via pytest parallelism and disabling mypy in most jobs
  .github/workflows/mypy.yml
  .spin/cmds.py
  numpy/typing/tests/test_typing.py
  pyproject.toml
  tools/wheels/cibw_test_command.sh
Labels: component: CI, Static typing

#24422 MAINT: Remove unused variable `i`
  numpy/core/src/multiarray/scalartypes.c.src
Labels: 03 - Maintenance

#24427 MAINT: revert adding `distutils` and `array_api` to `np.__all__`
  numpy/__init__.py
Labels: 03 - Maintenance

#24421 DOC: Remove mixed capitalization
  doc/source/f2py/buildtools/index.rst
  doc/source/user/c-info.beyond-basics.rst
  doc/source/user/index.rst
Labels: 04 - Documentation

#24434 DOC: Fix reference warning for types-and-structures.rst.
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#24439 MAINT: Pin upper version of sphinx.
  doc_requirements.txt
Labels: 03 - Maintenance

#24435 CI: cirrus run linux_aarch64 first
  .cirrus.star
  tools/ci/cirrus_arm.yml
Labels: component: CI

#24452 ENH: Add prefix to _ALIGN Macro
  numpy/core/src/multiarray/_multiarray_tests.c.src
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/common.h
  numpy/core/src/multiarray/lowlevel_strided_loops.c.src
  numpy/core/src/umath/_scaled_float_dtype.c
Labels: 01 - Enhancement, 09 - Backport-Candidate

#24453 MAINT: Pin upper version of sphinx.
  doc_requirements.txt
Labels: 03 - Maintenance, 08 - Backport

#24455 ENH: Add prefix to _ALIGN Macro
  numpy/core/src/multiarray/_multiarray_tests.c.src
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/common.h
  numpy/core/src/multiarray/lowlevel_strided_loops.c.src
  numpy/core/src/umath/_scaled_float_dtype.c
Labels: 01 - Enhancement, 08 - Backport

#24456 BUG: cleanup warnings [skip azp][skip circle][skip travis][skip cirrus]
  numpy/_build_utils/gitversion.py
  numpy/core/src/multiarray/compiled_base.c
Labels: 00 - Bug, 08 - Backport

#24457 Upgrade to spin 0.5
  .spin/cmds.py
  build_requirements.txt
  pyproject.toml
Labels: 03 - Maintenance

#24460 MAINT: Upgrade to spin 0.5
  .spin/cmds.py
  build_requirements.txt
  pyproject.toml
Labels: 03 - Maintenance, 08 - Backport

#24442 DOC: Fix reference warning in Arrayterator and recfunctions.
  numpy/lib/arrayterator.py
  numpy/lib/recfunctions.py
Labels: 04 - Documentation

#24393 DOC: Add missing sphinx reference roles
  doc/source/reference/arrays.nditer.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/iterator.rst
  doc/source/reference/c-api/ufunc.rst
  numpy/core/_add_newdocs.py
  numpy/core/_add_newdocs_scalars.py
  numpy/core/_ufunc_config.py
  numpy/core/defchararray.py
  numpy/core/numeric.py
  numpy/exceptions.py
  numpy/lib/index_tricks.py
  numpy/lib/utils.py
  numpy/polynomial/chebyshev.py
  numpy/polynomial/hermite.py
  numpy/polynomial/hermite_e.py
  numpy/polynomial/laguerre.py
  numpy/polynomial/legendre.py
  numpy/polynomial/polynomial.py
Labels: 04 - Documentation

#24463 MAINT: Fix broken link in runtests.py
  runtests.py
Labels: 04 - Documentation

#24471 DOC: Fix some incorrect markups
  doc/source/reference/c-api/iterator.rst
  doc/source/release/1.16.0-notes.rst
  numpy/core/_add_newdocs.py
  numpy/core/arrayprint.py
  numpy/core/code_generators/ufunc_docstrings.py
  numpy/core/fromnumeric.py
  numpy/core/shape_base.py
  numpy/lib/stride_tricks.py
  numpy/polynomial/chebyshev.py
  numpy/polynomial/hermite.py
  numpy/polynomial/hermite_e.py
  numpy/polynomial/laguerre.py
  numpy/polynomial/legendre.py
  numpy/polynomial/polynomial.py
  numpy/random/bit_generator.pyx
Labels: 04 - Documentation

#24484 BUG: fix NPY_cast_info error handling in choose
  numpy/core/src/multiarray/item_selection.c
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug

#24486 BUG: ``asv dev`` has been removed, use ``asv run`` instead.
  tools/travis-test.sh
Labels: 00 - Bug, 03 - Maintenance, 09 - Backport-Candidate

#24481 DOC: Rm np.who from autosummary.
  doc/source/reference/routines.other.rst
Labels: 04 - Documentation

#24488 MAINT: Stop testing on ppc64le.
  .travis.yml
Labels: 03 - Maintenance, component: CI

#24370 BLD: Clean up build for complex
  numpy/core/config.h.in
  numpy/core/include/numpy/_numpyconfig.h.in
  numpy/core/include/numpy/npy_common.h
  numpy/core/meson.build
  numpy/core/setup.py
Labels: 01 - Enhancement

#24485 DOC: Fix some broken links
  doc/source/reference/arrays.nditer.rst
  numpy/core/_ufunc_config.py
  numpy/core/defchararray.py
  numpy/core/fromnumeric.py
  numpy/lib/format.py
  numpy/lib/function_base.py
  numpy/lib/index_tricks.py
  numpy/lib/utils.py
  numpy/random/mtrand.pyx
Labels: 04 - Documentation

#24493 CI: GitHub Actions CI job restructuring
  .github/actions/action.yml
  .github/workflows/linux.yml
  .github/workflows/linux_blas.yml
  .github/workflows/linux_simd.yml
  .github/workflows/windows.yml
  .github/workflows/windows_meson.yml
  build_requirements.txt
Labels: 01 - Enhancement, component: CI

#24496 BUG: Fix meson build failure due to unchanged inplace auto-generated dispatch config headers
  .gitignore
  numpy/distutils/command/build_clib.py
  numpy/distutils/command/build_ext.py
Labels: 00 - Bug, component: numpy.distutils, 08 - Backport, component: SIMD

#24473 MAINT: Improve docstring and performance of trimseq
  numpy/polynomial/polyutils.py
  numpy/polynomial/tests/test_polyutils.py
Labels: 03 - Maintenance

#24494 API: Remove deprecated `msort` function
  doc/release/upcoming_changes/24494.expired.rst
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/lib/function_base.py
  numpy/lib/function_base.pyi
  numpy/lib/tests/test_function_base.py
Labels: 30 - API

#24510 DOC: Add missing changelogs for NEP 52 PRs
  doc/release/upcoming_changes/21199.c_api.rst
  doc/release/upcoming_changes/22449.change.rst
  doc/release/upcoming_changes/23729.improvement.rst
  doc/release/upcoming_changes/23762.new_function.rst
  doc/release/upcoming_changes/23789.new_feature.rst
  doc/release/upcoming_changes/23809.expired.rst
  doc/release/upcoming_changes/23847.c_api.rst
  doc/release/upcoming_changes/23861.change.rst
  doc/release/upcoming_changes/23871.change.rst
  doc/release/upcoming_changes/23919.c_api_removal.rst
  doc/release/upcoming_changes/23921.expired.rst
  doc/release/upcoming_changes/23922.c_api_removal.rst
  doc/release/upcoming_changes/23922.python_removal.rst
  doc/release/upcoming_changes/23936.change.rst
  doc/release/upcoming_changes/23936.improvement.rst
  doc/release/upcoming_changes/23998.expired.rst
  doc/release/upcoming_changes/24011.c_api_removal.rst
  doc/release/upcoming_changes/24085.improvement.rst
  doc/release/upcoming_changes/24126.change.rst
  doc/release/upcoming_changes/24144.python_removal.rst
  doc/release/upcoming_changes/24258.c_api.rst
  doc/release/upcoming_changes/24271.c_api_removal.rst
  doc/release/upcoming_changes/24312.expired.rst
  doc/release/upcoming_changes/24321.python_removal.rst
  doc/release/upcoming_changes/24494.expired.rst
  doc/source/release/2.0.0-notes.rst
Labels: 04 - Documentation

#24511 BUG: Use a default assignment for git_hash [skip ci]
  numpy/_build_utils/gitversion.py
Labels: 00 - Bug, 09 - Backport-Candidate

#24469 DEP: Replace deprecation warning for non-integral arguments in polynomial with exception
  numpy/polynomial/chebyshev.py
  numpy/polynomial/hermite.py
  numpy/polynomial/hermite_e.py
  numpy/polynomial/laguerre.py
  numpy/polynomial/legendre.py
  numpy/polynomial/polynomial.py
  numpy/polynomial/polyutils.py
  numpy/polynomial/tests/test_polynomial.py
Labels: 03 - Maintenance

#24476 MAINT: Move `RankWarning` to exceptions module
  doc/source/reference/routines.polynomials.poly1d.rst
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/exceptions.py
  numpy/exceptions.pyi
  numpy/lib/__init__.pyi
  numpy/lib/polynomial.py
  numpy/lib/polynomial.pyi
  numpy/polynomial/chebyshev.py
  numpy/polynomial/hermite.py
  numpy/polynomial/hermite_e.py
  numpy/polynomial/laguerre.py
  numpy/polynomial/legendre.py
  numpy/polynomial/polynomial.py
  numpy/polynomial/polyutils.py
  numpy/polynomial/polyutils.pyi
  numpy/polynomial/tests/test_classes.py
  numpy/typing/tests/data/reveal/warnings_and_errors.pyi
Labels: 03 - Maintenance

#24479 CI: Implements Cross-Compile Builds for armhf, ppc64le, and s390x
  .github/workflows/linux_qemu.yml
  numpy/core/tests/test_simd_module.py
Labels: 01 - Enhancement, component: CI

#24513 API: Update `lib.histograms` namespace
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/lib/__init__.py
  numpy/lib/__init__.pyi
  numpy/lib/_histograms_impl.py
  numpy/lib/_histograms_impl.pyi
  numpy/lib/function_base.py
  numpy/lib/tests/test_histograms.py
  numpy/tests/test_public_api.py
Labels: 30 - API

#24515 BUG: fix issue with git-version script, needs a shebang to run
  meson.build
  numpy/_build_utils/gitversion.py
  numpy/meson.build
Labels: 00 - Bug, 03 - Maintenance, 09 - Backport-Candidate

#24522 BUG: Use a default assignment for git_hash [skip ci]
  numpy/_build_utils/gitversion.py
Labels: 00 - Bug, 08 - Backport

#24521 BUG: fix issue with git-version script, needs a shebang to run
  meson.build
  numpy/_build_utils/gitversion.py
  numpy/meson.build
Labels: 00 - Bug, 03 - Maintenance, 08 - Backport

#24526 BUG: Fix common block handling in f2py
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/src/crackfortran/gh22648.pyf
  numpy/f2py/tests/test_crackfortran.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#24524 BUG: fix NPY_cast_info error handling in choose
  numpy/core/src/multiarray/item_selection.c
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug, 08 - Backport

#24516 DOC: unpin sphinx
  doc/source/conf.py
  doc_requirements.txt
Labels: 04 - Documentation

#24518 MAINT: Add expiration notes for NumPy 2.0 removals
  numpy/__init__.py
  numpy/_expired_attrs_2_0.py
  numpy/meson.build
Labels: 03 - Maintenance

#24299 BUG: Fix assumed length f2py regression
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/src/string/gh24008.f
  numpy/f2py/tests/test_character.py
Labels: 00 - Bug, component: numpy.f2py, 09 - Backport-Candidate

#24517 MAINT: Harmonize fortranobject, drop C99 style for loop
  numpy/f2py/src/fortranobject.c
Labels: 03 - Maintenance

#24527 TYP: add kind argument to numpy.isin type specification
  numpy/lib/arraysetops.pyi
Labels: Static typing

#24520 CI: remove obsolete jobs, and move macOS and conda Azure jobs to Meson and GHA
  .github/meson_actions/action.yml
  .github/workflows/linux.yml
  .github/workflows/linux_blas.yml
  .github/workflows/macos.yml
  .travis.yml
  azure-pipelines.yml
  environment.yml
Labels: 03 - Maintenance, component: CI

#23764 CI,TYP: Bump mypy to 1.4.1
  environment.yml
  numpy/core/numeric.pyi
  numpy/lib/shape_base.pyi
  numpy/testing/_private/utils.pyi
  numpy/typing/tests/data/fail/modules.pyi
  numpy/typing/tests/data/fail/npyio.pyi
  numpy/typing/tests/data/mypy.ini
  numpy/typing/tests/data/pass/lib_utils.py
  numpy/typing/tests/data/pass/ufunc_config.py
  numpy/typing/tests/data/reveal/arithmetic.pyi
  numpy/typing/tests/data/reveal/array_constructors.pyi
  numpy/typing/tests/data/reveal/arraysetops.pyi
  numpy/typing/tests/data/reveal/bitwise_ops.pyi
  numpy/typing/tests/data/reveal/dtype.pyi
  numpy/typing/tests/data/reveal/einsumfunc.pyi
  numpy/typing/tests/data/reveal/histograms.pyi
  numpy/typing/tests/data/reveal/index_tricks.pyi
  numpy/typing/tests/data/reveal/lib_function_base.pyi
  numpy/typing/tests/data/reveal/lib_polynomial.pyi
  numpy/typing/tests/data/reveal/lib_utils.pyi
  numpy/typing/tests/data/reveal/linalg.pyi
  numpy/typing/tests/data/reveal/mod.pyi
  numpy/typing/tests/data/reveal/multiarray.pyi
  numpy/typing/tests/data/reveal/nbit_base_example.pyi
  numpy/typing/tests/data/reveal/ndarray_misc.pyi
  numpy/typing/tests/data/reveal/numerictypes.pyi
  numpy/typing/tests/data/reveal/random.pyi
  numpy/typing/tests/data/reveal/scalars.pyi
  numpy/typing/tests/data/reveal/twodim_base.pyi
  numpy/typing/tests/data/reveal/type_check.pyi
  numpy/typing/tests/data/reveal/ufuncs.pyi
  runtests.py
  test_requirements.txt
  tools/travis-test.sh
Labels: 09 - Backport-Candidate, Static typing

#24541 CI,TYP: Bump mypy to 1.4.1
  environment.yml
  numpy/core/numeric.pyi
  numpy/lib/shape_base.pyi
  numpy/testing/_private/utils.pyi
  numpy/typing/tests/data/fail/modules.pyi
  numpy/typing/tests/data/fail/npyio.pyi
  numpy/typing/tests/data/mypy.ini
  numpy/typing/tests/data/pass/lib_utils.py
  numpy/typing/tests/data/pass/ufunc_config.py
  numpy/typing/tests/data/reveal/arithmetic.pyi
  numpy/typing/tests/data/reveal/array_constructors.pyi
  numpy/typing/tests/data/reveal/arraysetops.pyi
  numpy/typing/tests/data/reveal/bitwise_ops.pyi
  numpy/typing/tests/data/reveal/dtype.pyi
  numpy/typing/tests/data/reveal/einsumfunc.pyi
  numpy/typing/tests/data/reveal/histograms.pyi
  numpy/typing/tests/data/reveal/index_tricks.pyi
  numpy/typing/tests/data/reveal/lib_function_base.pyi
  numpy/typing/tests/data/reveal/lib_polynomial.pyi
  numpy/typing/tests/data/reveal/lib_utils.pyi
  numpy/typing/tests/data/reveal/linalg.pyi
  numpy/typing/tests/data/reveal/mod.pyi
  numpy/typing/tests/data/reveal/multiarray.pyi
  numpy/typing/tests/data/reveal/nbit_base_example.pyi
  numpy/typing/tests/data/reveal/ndarray_misc.pyi
  numpy/typing/tests/data/reveal/numerictypes.pyi
  numpy/typing/tests/data/reveal/random.pyi
  numpy/typing/tests/data/reveal/scalars.pyi
  numpy/typing/tests/data/reveal/twodim_base.pyi
  numpy/typing/tests/data/reveal/type_check.pyi
  numpy/typing/tests/data/reveal/ufuncs.pyi
  runtests.py
  test_requirements.txt
  tools/travis-test.sh
Labels: 08 - Backport, Static typing

#24542 BUG: Fix assumed length f2py regression
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/src/string/gh24008.f
  numpy/f2py/tests/test_character.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#24523 CI: switch the Cygwin job to Meson
  .github/workflows/cygwin.yml
  numpy/core/meson.build
Labels: component: CI

#24545 TYP: add kind argument to numpy.isin type specification
  numpy/lib/arraysetops.pyi
Labels: 03 - Maintenance, 08 - Backport, Static typing

#24544 MAINT: Harmonize fortranobject
  numpy/f2py/src/fortranobject.c
Labels: component: numpy.f2py, 03 - Maintenance, 08 - Backport

#24539 CI: fix CircleCI job for move to Meson
  .circleci/config.yml
  numpy/core/multiarray.py
  numpy/ma/core.py
Labels: component: CI

#24549 DOC: fix typos in percentile documentation
  numpy/lib/function_base.py
Labels: 04 - Documentation

#24547 DOC: Cleanup removed objects
  doc/source/reference/routines.array-creation.rst
  doc/source/reference/routines.dtype.rst
  doc/source/reference/routines.io.rst
  doc/source/reference/routines.other.rst
  numpy/core/numerictypes.py
  numpy/core/records.py
  numpy/lib/type_check.py
Labels: 04 - Documentation

#24535 CI: remove spurious wheel build action runs
  .github/workflows/wheels.yml
Labels: component: CI

#24556 BUG: fix comparisons between masked and unmasked structured arrays
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
Labels: 00 - Bug, component: numpy.ma, 09 - Backport-Candidate

#24505 DOC: Fix mentions in `isin` docs
  numpy/lib/arraysetops.py
Labels: 04 - Documentation

#24538 API: Update `lib.function_base` namespace
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_expired_attrs_2_0.py
  numpy/core/tests/test_deprecations.py
  numpy/lib/__init__.py
  numpy/lib/__init__.pyi
  numpy/lib/_function_base_impl.py
  numpy/lib/_function_base_impl.pyi
  numpy/lib/_nanfunctions_impl.py
  numpy/lib/_nanfunctions_impl.pyi
  numpy/lib/index_tricks.py
  numpy/lib/polynomial.py
  numpy/lib/tests/test_function_base.py
  numpy/ma/core.py
  numpy/ma/core.pyi
  numpy/ma/extras.py
  numpy/tests/test_public_api.py
Labels: 30 - API, Numpy 2.0 API Changes

#24559 BUG: ensure nomask in comparison result is not broadcast
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
Labels: 00 - Bug, component: numpy.ma, 09 - Backport-Candidate

#24560 CI/BENCH: move more jobs to Meson and fix all broken benchmarks
  .github/workflows/linux.yml
  .spin/cmds.py
  benchmarks/benchmarks/bench_core.py
  benchmarks/benchmarks/bench_creation.py
  benchmarks/benchmarks/bench_itemselection.py
  benchmarks/benchmarks/bench_linalg.py
  benchmarks/benchmarks/bench_ma.py
  benchmarks/benchmarks/bench_manipulate.py
  benchmarks/benchmarks/bench_reduce.py
  benchmarks/benchmarks/bench_shape_base.py
  benchmarks/benchmarks/bench_ufunc.py
  benchmarks/benchmarks/bench_ufunc_strides.py
  benchmarks/benchmarks/common.py
Labels: component: benchmarks, component: CI

#24561 BUG: fix comparisons between masked and unmasked structured arrays
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
Labels: 00 - Bug, component: numpy.ma, 08 - Backport

#24562 DOC: Fix typos
  numpy/core/_add_newdocs.py
  numpy/core/code_generators/ufunc_docstrings.py
Labels: 04 - Documentation

#24537 API: Update `lib.type_check` namespace
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/lib/__init__.py
  numpy/lib/__init__.pyi
  numpy/lib/_type_check_impl.py
  numpy/lib/_type_check_impl.pyi
  numpy/lib/polynomial.py
  numpy/lib/scimath.py
  numpy/lib/tests/test_type_check.py
  numpy/testing/_private/utils.py
  numpy/tests/test_public_api.py
Labels: 30 - API, Numpy 2.0 API Changes

#24483 NEP: add NEP 55 for a variable width string dtype
  doc/neps/nep-0055-string_dtype.rst
Labels: component: NEP

#24579 DOC: fix `import mat` warning.
  doc/source/reference/routines.matlib.rst
Labels: 04 - Documentation

#24582 DOC: fix typos in ndarray.setflags doc
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation

#24571 MAINT: Add tests for Polynomial with fractions.Fraction coefficients
  numpy/polynomial/tests/test_polynomial.py
Labels: 03 - Maintenance

#24577 API: Update `lib.twodim_base` namespace
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/lib/__init__.py
  numpy/lib/__init__.pyi
  numpy/lib/_function_base_impl.py
  numpy/lib/_twodim_base_impl.py
  numpy/lib/_twodim_base_impl.pyi
  numpy/lib/polynomial.py
  numpy/linalg/linalg.py
  numpy/tests/test_public_api.py
Labels: 30 - API, Numpy 2.0 API Changes

#24567 API: Update `arraypad`,`arraysetops`, `ufunclike` and `utils` namespaces in `np.lib`
  benchmarks/benchmarks/__init__.py
  doc/source/reference/routines.set.rst
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_pytesttester.py
  numpy/core/tests/test_deprecations.py
  numpy/lib/__init__.py
  numpy/lib/__init__.pyi
  numpy/lib/_arraypad_impl.py
  numpy/lib/_arraypad_impl.pyi
  numpy/lib/_arraysetops_impl.py
  numpy/lib/_arraysetops_impl.pyi
  numpy/lib/_function_base_impl.py
  numpy/lib/_type_check_impl.py
  numpy/lib/_ufunclike_impl.py
  numpy/lib/_ufunclike_impl.pyi
  numpy/lib/_utils_impl.py
  numpy/lib/_utils_impl.pyi
  numpy/lib/format.py
  numpy/lib/tests/test_arraypad.py
  numpy/lib/tests/test_arraysetops.py
  numpy/lib/tests/test_format.py
  numpy/lib/tests/test_ufunclike.py
  numpy/lib/tests/test_utils.py
  numpy/ma/extras.py
  numpy/tests/test_public_api.py
Labels: 30 - API, Numpy 2.0 API Changes

#24477 MAINT: Remove deprecated functions [NEP 52]
  doc/release/upcoming_changes/24477.python_removal.rst
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_expired_attrs_2_0.py
  numpy/core/_add_newdocs.py
  numpy/core/fromnumeric.py
  numpy/core/numerictypes.py
  numpy/core/numerictypes.pyi
  numpy/core/tests/test_deprecations.py
  numpy/core/tests/test_numerictypes.py
  numpy/core/tests/test_regression.py
  numpy/ma/core.py
  numpy/typing/tests/data/pass/numerictypes.py
  numpy/typing/tests/data/reveal/numerictypes.pyi
Labels: 03 - Maintenance, Numpy 2.0 API Changes

#24584 BLD: fix `_umath_linalg` dependencies
  numpy/linalg/meson.build
Labels: 09 - Backport-Candidate, 36 - Build

#24590 CI: Exclude import libraries from list of DLLs on Cygwin.
  tools/list_numpy_dlls.sh
Labels: 03 - Maintenance, 08 - Backport, component: CI

#24591 BLD: fix ``_umath_linalg`` dependencies
  numpy/linalg/meson.build
Labels: 08 - Backport, 36 - Build

#24594 MAINT: Stop testing on ppc64le.
  .travis.yml
Labels: 03 - Maintenance, 08 - Backport, component: CI

#24589 NEP: fix typos and formatting in NEP 55
  doc/neps/nep-0055-string_dtype.rst
Labels: 03 - Maintenance, component: NEP

#24053 ENH: Adopt new macOS Accelerate BLAS/LAPACK Interfaces, including ILP64
  .github/workflows/macos.yml
  doc/release/upcoming_changes/24053.new_feature.rst
  numpy/core/src/common/npy_cblas.h
  numpy/distutils/system_info.py
  numpy/linalg/meson.build
  numpy/meson.build
Labels: 01 - Enhancement, component: numpy.linalg, component: numpy.core, 09 - Backport-Candidate

#24206 TST: convert remaining setup.py tests to meson instead
  numpy/core/tests/examples/cython/meson.build
  numpy/core/tests/test_cython.py
Labels: 05 - Testing, 09 - Backport-Candidate

#24598 DOC: fix two misspellings in documentation
  doc/source/glossary.rst
  doc/source/user/how-to-partition.rst
Labels: 04 - Documentation

#24600 DOC: wrong name in docs
  numpy/polynomial/chebyshev.py
Labels: 04 - Documentation

#24601 BLD: meson-cpu: fix SIMD support on platforms with no features
  meson_cpu/meson.build
Labels: 00 - Bug, 09 - Backport-Candidate, 36 - Build, Meson

#24599 DOC: unpin sphinx to pick up 7.2.5
  doc_requirements.txt
Labels: 04 - Documentation

#24602 BLD: meson-cpu: fix SIMD support on platforms with no features
  meson_cpu/meson.build
Labels: 00 - Bug, 08 - Backport, 36 - Build, Meson

#24566 API: Update `lib.shape_base` namespace
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_expired_attrs_2_0.py
  numpy/core/tests/test_deprecations.py
  numpy/lib/__init__.py
  numpy/lib/__init__.pyi
  numpy/lib/_shape_base_impl.py
  numpy/lib/_shape_base_impl.pyi
  numpy/lib/tests/test_shape_base.py
  numpy/testing/tests/test_utils.py
  numpy/tests/test_public_api.py
  numpy/typing/tests/data/reveal/shape_base.pyi
Labels: 30 - API, Numpy 2.0 API Changes
