Repository numpy/numpy, pull requests merged in 2023-01, with the labels that each got.

#22906 BUG: np.loadtxt cannot load text file with quoted fields separated by whitespace
  numpy/core/src/multiarray/textreading/tokenize.cpp
  numpy/lib/npyio.py
  numpy/lib/tests/test_loadtxt.py
Labels: 00 - Bug, 09 - Backport-Candidate

#22905 TST: Add linspace test case for any_step_zero and not _mult_inplace
  numpy/core/tests/test_function_base.py
Labels: 05 - Testing

#22879 BUG: Fixes for numpy.testing.overrides
  numpy/testing/__init__.py
  numpy/testing/overrides.py
Labels: 00 - Bug

#22902 MAINT: Replace Python3.8 by Python3.9.
  .circleci/config.yml
  .github/workflows/build_test.yml
  .github/workflows/cygwin.yml
  .github/workflows/wheels.yml
  .travis.yml
  azure-pipelines.yml
  tools/ci/cirrus_general.yml
Labels: 03 - Maintenance, 36 - Build

#22889 ENH: Speedup ufunc.at when casting is not needed
  benchmarks/benchmarks/bench_ufunc.py
  numpy/core/src/umath/legacy_array_method.c
  numpy/core/src/umath/loops_arithm_fp.dispatch.c.src
  numpy/core/src/umath/ufunc_object.c
  numpy/core/tests/test_ufunc.py
Labels: 01 - Enhancement

#22917 DOC: document NPY_DISABLE_CPU_FEATURES
  doc/source/reference/global_state.rst
  doc/source/reference/simd/build-options.rst
  doc/source/reference/simd/how-it-works.rst
Labels: 04 - Documentation

#22918 TST: split long ufunc.at test
  numpy/core/tests/test_ufunc.py
Labels: 05 - Testing

#22927 MAINT: Remove distutils usage in travis-test.sh.
  tools/travis-test.sh
Labels: 03 - Maintenance

#22931 TST: Add fixture to avoid issue with randomizing test order.
  numpy/polynomial/tests/test_printing.py
Labels: 00 - Bug, 05 - Testing, component: numpy.polynomial, 09 - Backport-Candidate

#22923 ENH: Create string dtype instances from the abstract dtype
  doc/release/upcoming_changes/22863.new_feature.rst
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/tests/test_dtype.py
Labels: 01 - Enhancement, 62 - Python API

#22936 DOC: (LaTeX) fix 'fontenc' key for usage with xelatex
  doc/source/conf.py
Labels: 04 - Documentation

#22952 DOC: remove old LaTeX hack if Sphinx is at 5.0.0 or later (fix #22941)
  doc/source/conf.py
Labels: 04 - Documentation

#22954 BUG, SIMD: Fix spurious invalid exception for sin/cos on arm64/clang
  numpy/core/src/common/simd/neon/operators.h
Labels: 00 - Bug, 09 - Backport-Candidate, component: SIMD

#22947 MAINT: Add additional information to missing scalar AttributeError
  numpy/__init__.py
  numpy/core/tests/test_deprecations.py
Labels: 03 - Maintenance, 09 - Backport-Candidate

#22939 MAINT: Move export for scipy arm64 helper into main module
  numpy/core/include/numpy/npy_math.h
  numpy/core/meson.build
  numpy/core/setup.py
  numpy/core/src/npymath/arm64_exports.c
Labels: 03 - Maintenance, 09 - Backport-Candidate

#22938 DOC: Update docstring of `multivariate_normal`
  numpy/random/_generator.pyx
Labels: 04 - Documentation

#22962 MAINT: use pypy3.9 in testing
  .github/workflows/build_test.yml
  azure-pipelines.yml
  azure-steps-windows.yml
  numpy/distutils/mingw32ccompiler.py
Labels: 03 - Maintenance

#22934 DOC: Add releases to NEP 29
  doc/neps/nep-0029-deprecation_policy.rst
Labels: 04 - Documentation

#22964 MAINT: Update python 3.11-dev to 3.11.
  .github/workflows/build_test.yml
Labels: 03 - Maintenance, component: CI

#22965 MAINT: Update python 3.11-dev to 3.11.
  .github/workflows/build_test.yml
Labels: 03 - Maintenance, 08 - Backport, component: CI

#22966 DOC: Remove dangling deprecation warning
  doc/source/user/basics.indexing.rst
Labels: 04 - Documentation, 08 - Backport

#22967 ENH: Detect CPU features on FreeBSD/powerpc64*
  numpy/core/src/common/npy_cpu_features.c
  numpy/distutils/ccompiler_opt.py
Labels: 01 - Enhancement, 08 - Backport, component: SIMD, 36 - Build

#22968 BUG: np.loadtxt cannot load text file with quoted fields separated by whitespace
  numpy/core/src/multiarray/textreading/tokenize.cpp
  numpy/lib/npyio.py
  numpy/lib/tests/test_loadtxt.py
Labels: 00 - Bug, 08 - Backport

#22969 TST: Add fixture to avoid issue with randomizing test order.
  numpy/polynomial/tests/test_printing.py
Labels: 00 - Bug, 05 - Testing, 08 - Backport

#22970 BUG: Fix fill violating read-only flag. (#22959)
  numpy/core/src/multiarray/convert.c
  numpy/core/tests/test_multiarray.py
Labels: 00 - Bug, 08 - Backport

#22971 MAINT: Add additional information to missing scalar AttributeError
  numpy/__init__.py
  numpy/core/tests/test_deprecations.py
Labels: 03 - Maintenance, 08 - Backport

#22972 MAINT: Move export for scipy arm64 helper into main module
  numpy/core/include/numpy/npy_math.h
  numpy/core/setup.py
  numpy/core/src/npymath/arm64_exports.c
Labels: 03 - Maintenance, 08 - Backport

#22976 BUG, SIMD: Fix spurious invalid exception for sin/cos on arm64/clang
  numpy/core/src/common/simd/neon/operators.h
Labels: 00 - Bug, 08 - Backport, component: SIMD

#22911 DOC: Remove Gitpod as a local build option for users
  doc/source/dev/howto_build_docs.rst
  doc/source/user/building.rst
Labels: 04 - Documentation

#22779 DOC: All integer values must be non-negative
  numpy/random/bit_generator.pyx
Labels: 04 - Documentation

#22981 DOC: remove extraneous backtick from warning
  numpy/core/src/multiarray/arraytypes.c.src
Labels: 04 - Documentation

#22980 MAINT: Fix some noisy clang suggestions.
  numpy/core/src/npysort/selection.cpp
Labels: 03 - Maintenance

#22863 ENH: allow NEP 42 dtypes to work with np.char
  doc/release/upcoming_changes/22863.new_feature.rst
  doc/release/upcoming_changes/22963.new_feature.rst
  numpy/core/defchararray.py
  numpy/core/src/multiarray/dtypemeta.h
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/tests/test_defchararray.py
Labels: 01 - Enhancement, 56 - Needs Release Note.

#22986 BUG: Ensure correct loop order in sin, cos, and arctan2
  numpy/core/code_generators/generate_umath.py
  numpy/core/tests/test_umath.py
Labels: 00 - Bug

#22988 DOC: add information about disabling SIMD for crashes
  doc/source/user/troubleshooting-importerror.rst
Labels: 04 - Documentation

#22989 BUG: Ensure correct loop order in sin, cos, and arctan2
  numpy/core/code_generators/generate_umath.py
  numpy/core/tests/test_umath.py
Labels: 00 - Bug, 08 - Backport

#22991 DOC: Fix gh-22990 by correcting docstring of result_type
  numpy/core/multiarray.py
Labels: 04 - Documentation

#22996 ENH: Improve loadtxt error with dtype and non-matchinig column number
  numpy/core/src/multiarray/textreading/rows.c
  numpy/lib/tests/test_loadtxt.py
Labels: 01 - Enhancement

#22998 DEP: Finalize `+arr` returning a copy e.g. for string arrays
  doc/release/upcoming_changes/22998.expired.rst
  numpy/core/src/multiarray/number.c
  numpy/core/tests/test_deprecations.py
Labels: 07 - Deprecation

#22916 ENH: Faster numpy.load (try/except _filter_header)
  benchmarks/benchmarks/bench_io.py
  numpy/lib/format.py
  numpy/lib/tests/test_format.py
Labels: 01 - Enhancement, triaged

#23013 DOC: Fix a typo in f2py meson docs
  doc/source/f2py/buildtools/meson.rst
Labels: 04 - Documentation, component: numpy.f2py

#23015 DOC: Add version added information for the strict parameter in assert_array_equal
  numpy/testing/_private/utils.py
Labels: 04 - Documentation, 09 - Backport-Candidate

#22885 MAINT: `f2py` cleanup
  numpy/distutils/ccompiler.py
  numpy/distutils/fcompiler/__init__.py
  numpy/f2py/crackfortran.py
Labels: component: numpy.f2py, 03 - Maintenance

#22723 DOC: Structured array doc update to note `dtype[name]`
  doc/source/user/basics.rec.rst
Labels: 04 - Documentation

#22960 DOC: Add example for np.ma.diag
  numpy/ma/core.py
Labels: 04 - Documentation, component: numpy.ma

#22921 BLD: Build wheels with cibuildwheel 2.12.0
  .github/workflows/wheels.yml
  numpy/core/src/common/simd/neon/operators.h
  tools/ci/cirrus_general.yml
Labels: 25 - WIP, 36 - Build

#22562 DOC: #22266 Add examples for tril_indices_from(), triu_indices_from()
  numpy/lib/twodim_base.py
Labels: 04 - Documentation

#23026 CI: Bump debug test to ubuntu-latest/22.04 rather than 20.04
  .github/workflows/build_test.yml
Labels: 03 - Maintenance, component: CI

#23016 BUG: use `_Alignof` rather than `offsetof()` on most compilers
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/common.h
Labels: 09 - Backport-Candidate

#23020 ENH: Improve array function overhead by using vectorcall
  benchmarks/benchmarks/bench_core.py
  doc/release/upcoming_changes/23020.change.rst
  doc/release/upcoming_changes/23020.performance.rst
  numpy/core/_asarray.py
  numpy/core/arrayprint.py
  numpy/core/fromnumeric.py
  numpy/core/numeric.py
  numpy/core/overrides.py
  numpy/core/src/multiarray/arrayfunction_override.c
  numpy/core/src/multiarray/arrayfunction_override.h
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/tests/test_overrides.py
  numpy/lib/function_base.py
  numpy/lib/nanfunctions.py
  numpy/lib/npyio.py
  numpy/lib/polynomial.py
  numpy/lib/twodim_base.py
  numpy/linalg/linalg.py
Labels: 01 - Enhancement

#22997 API: Fix cython exception handling for exported extern C functions
  doc/release/upcoming_changes/22997.improvement.rst
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
Labels: 30 - API

#23019 DEP: Finalize the non-sequence stacking deprecation
  doc/release/upcoming_changes/23019.expired.rst
  numpy/core/shape_base.py
  numpy/core/tests/test_shape_base.py
  numpy/lib/shape_base.py
  numpy/lib/tests/test_shape_base.py
Labels: 07 - Deprecation

#23030 DOC: Add version added information for the strict parameter in assert_array_equal
  numpy/testing/_private/utils.py
Labels: 04 - Documentation, 08 - Backport

#23031 BUG: use `_Alignof` rather than `offsetof()` on most compilers
  numpy/core/src/multiarray/arraytypes.c.src
  numpy/core/src/multiarray/common.h
Labels: 00 - Bug, 08 - Backport

#22776 BUG: fix ma.diff not preserving mask when using append/prepend
  doc/release/upcoming_changes/22776.improvement.rst
  numpy/ma/core.py
  numpy/ma/core.pyi
  numpy/ma/tests/test_core.py
Labels: 01 - Enhancement, component: numpy.ma, 62 - Python API

#23038 DOC: Ignore attribute FutureWarning in doc build
  doc/source/conf.py
Labels: 04 - Documentation

#23039 BUG: Implement `ArrayFunctionDispatcher.__get__`
  numpy/core/src/multiarray/arrayfunction_override.c
  numpy/core/tests/test_overrides.py
Labels: 00 - Bug

#23011 DEP: deprecate np.finfo(None)
  doc/release/upcoming_changes/23011.deprecation.rst
  numpy/core/getlimits.py
  numpy/core/tests/test_deprecations.py
Labels: 07 - Deprecation

#23047 MAINT: dtype.name works for NEP 42 dtypes
  numpy/core/_dtype.py
  numpy/core/tests/test_custom_dtypes.py
Labels: 03 - Maintenance

#23041 MAINT: Remove all nose testing support.
  doc/release/upcoming_changes/23041.expired.rst
  numpy/__init__.py
  numpy/_pyinstaller/hook-numpy.py
  numpy/core/_add_newdocs.py
  numpy/core/tests/test_deprecations.py
  numpy/testing/__init__.py
  numpy/testing/__init__.pyi
  numpy/testing/_private/decorators.py
  numpy/testing/_private/noseclasses.py
  numpy/testing/_private/nosetester.py
  numpy/testing/_private/parameterized.py
  numpy/testing/_private/utils.py
  numpy/testing/tests/test_doctesting.py
  numpy/testing/tests/test_utils.py
  numpy/tests/test_public_api.py
  numpy/typing/tests/data/reveal/testing.pyi
Labels: 03 - Maintenance, 07 - Deprecation

#23054 MAINT: Move unused import into hook for pyinstaller
  numpy/_pyinstaller/hook-numpy.py
  numpy/core/_add_newdocs.py
Labels: 03 - Maintenance

#22864 CI: musllinux_x86_64
  .github/workflows/linux_musl.yml
  numpy/core/tests/test_mem_policy.py
  numpy/core/tests/test_umath.py
  numpy/testing/_private/utils.py
  tools/openblas_support.py
Labels: 03 - Maintenance, component: CI

#20970 ENH: Move identity to the ArrayMethod to allow customization
  numpy/core/include/numpy/experimental_dtype_api.h
  numpy/core/src/multiarray/array_method.c
  numpy/core/src/multiarray/array_method.h
  numpy/core/src/multiarray/experimental_public_dtype_api.c
  numpy/core/src/umath/_scaled_float_dtype.c
  numpy/core/src/umath/legacy_array_method.c
  numpy/core/src/umath/reduction.c
  numpy/core/src/umath/reduction.h
  numpy/core/src/umath/ufunc_object.c
  numpy/core/src/umath/ufunc_object.h
  numpy/core/src/umath/wrapping_array_method.c
  numpy/core/tests/test_custom_dtypes.py
  numpy/core/tests/test_ufunc.py
Labels: 01 - Enhancement, triage review

#23060 DEP: Remove the deprecated ``utils.py`` shim.
  doc/release/upcoming_changes/23060.expired.rst
  numpy/testing/utils.py
  numpy/tests/test_public_api.py
Labels: 07 - Deprecation, 56 - Needs Release Note.

#23064 DOC: Fixup docs after the code removal
  doc/source/conf.py
  doc/source/reference/routines.testing.rst
Labels: 04 - Documentation

#23065 DOC: fail the CI build and do not deploy if docs are not created
  .circleci/config.yml
  tools/ci/push_docs_to_repo.py
Labels: 04 - Documentation

#23066 BUG: fix broken numpy.distutils Fortran handling
  .github/workflows/cygwin.yml
  numpy/distutils/ccompiler.py
  numpy/distutils/fcompiler/__init__.py
Labels: 00 - Bug, component: numpy.distutils

#22769 BLD: Meson `__config__` generation
  doc/release/upcoming_changes/22769.improvement.rst
  numpy/__config__.py.in
  numpy/meson.build
  numpy/tests/test_numpy_config.py
Labels: component: build, Meson

#23076 DEV: Fix shell configuration in devcontainer
  .devcontainer/devcontainer.json
  .devcontainer/setup.sh
Labels: 16 - Development

#21888 MAINT: changing the method of checking for nan / inf values linalg.eig
  numpy/linalg/linalg.py
Labels: component: numpy.lib, 03 - Maintenance

#23079 BUG: Fix `integer / float` scalar promotion
  numpy/core/src/umath/scalarmath.c.src
  numpy/core/tests/test_scalarmath.py
Labels: 00 - Bug, 09 - Backport-Candidate

#23092 DOC: fix typo in C API reference
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#23077 BUG: Fix for npyv__trunc_s32_f32 (VXE)
  numpy/core/src/common/simd/vec/conversion.h
Labels: 00 - Bug, 06 - Regression, 09 - Backport-Candidate, component: SIMD

#23094 BUG: fix type in resolve_descriptors_function typedef
  numpy/core/include/numpy/experimental_dtype_api.h
Labels: 00 - Bug

#23087 DOC, ENH: Improve docstring of real_if_close
  numpy/lib/type_check.py
Labels: 04 - Documentation

#23093 BUG: Fixup f2py's handling a very little bit
  numpy/f2py/cfuncs.py
Labels: 00 - Bug

#22908 DOC: Pull existing PR workflow
  doc/source/dev/development_workflow.rst
Labels: 04 - Documentation

#23045 DOC: Improved nbytes description
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation

#23097 BUILD: error when building with python<3.9 [skip ci]
  setup.py
Labels: 36 - Build

#23098 BUG: Handle arrays in `conf_data`
  numpy/meson.build
Labels: 00 - Bug, component: build, Meson

#22559 DOC #22266 Add examples for diag_indices_from()
  numpy/lib/index_tricks.py
Labels: 04 - Documentation

#23113 ENH: Add slots to NDArrayOperatorsMixin allowing them in subclasses
  doc/release/upcoming_changes/23113.improvement.rst
  numpy/lib/mixins.py
  numpy/ma/tests/test_subclassing.py
Labels: 01 - Enhancement

#23117 Re-submission of PR23006
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/iterator.rst
Labels: 04 - Documentation

#23121 DOC:fix type in bitwise_ior
  numpy/core/code_generators/ufunc_docstrings.py
Labels: 04 - Documentation

#22165 ENH: Implement SIMD versions of isnan,isinf, isfinite and signbit
  .gitignore
  numpy/core/code_generators/generate_umath.py
  numpy/core/meson.build
  numpy/core/setup.py
  numpy/core/src/umath/loops.c.src
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/loops_unary_fp_le.dispatch.c.src
  numpy/core/src/umath/simd.inc.src
  numpy/core/tests/test_api.py
  numpy/core/tests/test_umath.py
Labels: 01 - Enhancement, component: SIMD

#23090 BUG: Fix crash when using complex double scalars with NEP 50
  numpy/core/src/multiarray/abstractdtypes.h
Labels: 00 - Bug, component: numpy.core

#23128 BUG: Add missing <type_traits> header.
  numpy/linalg/umath_linalg.cpp
Labels: 00 - Bug

#23127 BLD: use conda to install anaconda-client for upload
  .github/workflows/wheels.yml
  tools/ci/cirrus_general.yml
  tools/wheels/upload_wheels.sh
Labels: 36 - Build

#23111 MAINT: Allow export/import of bools in dlpack
  .gitattributes
  numpy/core/src/common/dlpack/dlpack.h
  numpy/core/src/multiarray/dlpack.c
  numpy/core/tests/test_dlpack.py
Labels: 03 - Maintenance

#23130 MAINT, BLD: Update wheel and GitPython versions.
  build_requirements.txt
  linter_requirements.txt
  pyproject.toml
  release_requirements.txt
  test_requirements.txt
Labels: 03 - Maintenance, 36 - Build

#21056 ENH: re-implement SIMD kernels of complex operations
  .gitignore
  benchmarks/benchmarks/bench_ufunc_strides.py
  numpy/core/code_generators/generate_umath.py
  numpy/core/meson.build
  numpy/core/setup.py
  numpy/core/src/_simd/_simd.dispatch.c.src
  numpy/core/src/_simd/_simd_easyintrin.inc
  numpy/core/src/common/simd/avx2/arithmetic.h
  numpy/core/src/common/simd/avx2/memory.h
  numpy/core/src/common/simd/avx2/reorder.h
  numpy/core/src/common/simd/avx512/arithmetic.h
  numpy/core/src/common/simd/avx512/maskop.h
  numpy/core/src/common/simd/avx512/memory.h
  numpy/core/src/common/simd/avx512/reorder.h
  numpy/core/src/common/simd/emulate_maskop.h
  numpy/core/src/common/simd/neon/arithmetic.h
  numpy/core/src/common/simd/neon/memory.h
  numpy/core/src/common/simd/neon/reorder.h
  numpy/core/src/common/simd/sse/arithmetic.h
  numpy/core/src/common/simd/sse/memory.h
  numpy/core/src/common/simd/sse/reorder.h
  numpy/core/src/common/simd/vec/arithmetic.h
  numpy/core/src/common/simd/vec/memory.h
  numpy/core/src/common/simd/vec/reorder.h
  numpy/core/src/umath/loops.c.src
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/loops_arithm_fp.dispatch.c.src
  numpy/core/src/umath/loops_unary_complex.dispatch.c.src
  numpy/core/src/umath/simd.inc.src
  numpy/core/tests/test_simd.py
Labels: 01 - Enhancement, component: SIMD
