Repository numpy/numpy, pull requests merged in 2023-05, with the labels that each got.

#23691 BUG: random: Don't return negative values from Generator.geometric.
  numpy/random/src/distributions/distributions.c
  numpy/random/tests/test_generator_mt19937_regressions.py
Labels: 00 - Bug, component: numpy.random

#23696 DOC: Fix link to site.cfg.example
  doc/source/reference/distutils_status_migration.rst
Labels: 04 - Documentation

#23695 BUG: Correct sin/cos float64 range check functions
  numpy/core/src/umath/loops_trigonometric.dispatch.c.src
  numpy/core/tests/test_umath.py
Labels: 00 - Bug

#23700 DOC: Resolve length/index ambiguity in numpy.outer docstring
  numpy/core/numeric.py
Labels: 04 - Documentation

#22137 ENH allow for specifying CPU features to enable via `NPY_ENABLE_CPU_FEATURES` environment variable
  22137.new_feature.rst
  numpy/core/src/common/npy_cpu_features.c
  numpy/core/src/common/npy_cpu_features.h
  numpy/core/tests/test_cpu_features.py
Labels: 01 - Enhancement, component: SIMD

#23699 MAINT: refactor PyArray_Repeat to avoid PyArray_INCREF
  numpy/core/src/multiarray/item_selection.c
  numpy/core/tests/test_multiarray.py
Labels: 03 - Maintenance

#23706 MAINT: Remove gisnan, gisinf, and gisfinite from testing code
  numpy/testing/_private/utils.py
Labels: 03 - Maintenance

#23678 MAINT: Pin rtools version on Windows.
  azure-steps-windows.yml
Labels: 03 - Maintenance, 09 - Backport-Candidate, 25 - WIP, component: CI

#23711 BUG: Fix compilation of halffloat with gcc 13.1
  numpy/core/src/common/half.hpp
  numpy/core/src/common/npstd.hpp
Labels: 00 - Bug, 36 - Build, C++

#23715 MAINT, BLD: Install rtools 4.0 for Windows wheels.
  .github/workflows/wheels.yml
Labels: 03 - Maintenance, 09 - Backport-Candidate, 36 - Build

#23716 BUG: Cannot mix ``uses`` and ``run`` in workflow script
  .github/workflows/wheels.yml
Labels: 00 - Bug, 09 - Backport-Candidate, 36 - Build

#23720 MAINT, BLD: Pin rtools to version 4.0 for Windows builds.
  .github/workflows/wheels.yml
  azure-steps-windows.yml
Labels: 03 - Maintenance, 08 - Backport, 36 - Build

#23721 BLD: update to OpenBLAS 0.3.23
  tools/openblas_support.py
Labels: 36 - Build

#23713 ENH: Make signed/unsigned integer comparisons exact
  doc/release/upcoming_changes/23713.improvement.rst
  numpy/core/code_generators/generate_umath.py
  numpy/core/src/umath/loops.c.src
  numpy/core/src/umath/loops.h.src
  numpy/core/src/umath/ufunc_type_resolution.c
  numpy/core/tests/test_umath.py
Labels: 01 - Enhancement

#23726 DOC: fix incorrect description of raise condition in numpy.testing.assert_array_less's docstring
  numpy/testing/_private/utils.py
Labels: 04 - Documentation

#23709 MAINT: Add "noexcept" markers to Cython functions that do not raise exceptions
  .github/workflows/build_test.yml
  build_requirements.txt
  numpy/random/_common.pxd
  numpy/random/_common.pyx
  numpy/random/_mt19937.pyx
  numpy/random/_pcg64.pyx
  numpy/random/_philox.pyx
  numpy/random/_sfc64.pyx
  pyproject.toml
  test_requirements.txt
Labels: 03 - Maintenance

#23735 TYP: Update type annotations for the numpy 1.25 release
  .gitignore
  numpy/__init__.pyi
  numpy/core/einsumfunc.pyi
  numpy/core/fromnumeric.pyi
  numpy/exceptions.pyi
  numpy/ma/__init__.pyi
  numpy/ma/core.pyi
  numpy/typing/tests/data/fail/einsumfunc.pyi
  numpy/typing/tests/data/reveal/einsumfunc.pyi
  numpy/typing/tests/data/reveal/modules.pyi
Labels: Static typing

#23736 MAINT: Copy rtools installation from install-rtools.
  azure-steps-windows.yml
Labels: 03 - Maintenance, 09 - Backport-Candidate

#23705 MAINT: Reorganize the way windowing functions ensure float64 result
  numpy/lib/function_base.py
Labels: 03 - Maintenance

#23728 BUG: fix the method for checking local files
  numpy/compat/py3k.py
  numpy/compat/tests/test_compat.py
Labels: 00 - Bug

#23620 MAINT: Add a proper implementation for structured zerofill
  numpy/core/src/multiarray/dtype_traversal.c
  numpy/core/src/multiarray/dtype_traversal.h
  numpy/core/src/multiarray/dtypemeta.c
  numpy/core/src/multiarray/refcount.c
  numpy/core/src/multiarray/refcount.h
  numpy/core/src/multiarray/usertypes.c
Labels: 03 - Maintenance

#23743 DOC: Add symbol in docstring for classes derived from ABCPolyBase
  numpy/polynomial/chebyshev.py
  numpy/polynomial/hermite.py
  numpy/polynomial/hermite_e.py
  numpy/polynomial/laguerre.py
  numpy/polynomial/legendre.py
  numpy/polynomial/polynomial.py
Labels: 04 - Documentation

#23747 DOC: clarify differences between ravel and reshape(-1)
  numpy/core/fromnumeric.py
Labels: 04 - Documentation

#23753 MAINT, BLD: Disable spr for clang
  numpy/distutils/checks/cpu_avx512_spr.c
Labels: 03 - Maintenance, 36 - Build

#23756 DOC: Rm bool8 from docs
  doc/source/reference/arrays.scalars.rst
  numpy/core/_add_newdocs_scalars.py
Labels: 04 - Documentation

#23599 BUG: Fix crackfortran groups for endifs with comments
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/src/crackfortran/gh23533.f
  numpy/f2py/tests/test_crackfortran.py
Labels: 00 - Bug, component: numpy.f2py

#23757 BUG: properly handle tuple keys in NpZFile.__getitem__
  numpy/lib/npyio.py
  numpy/lib/tests/test_io.py
Labels: 00 - Bug

#23746 ENH: add fast path for str(scalar_int)
  benchmarks/benchmarks/bench_scalar.py
  numpy/core/src/multiarray/scalartypes.c.src
  numpy/core/tests/test_arrayprint.py
Labels: 01 - Enhancement

#22539 DEP: Deprecate `np.find_common_type`
  doc/release/upcoming_changes/22539.change.rst
  doc/release/upcoming_changes/22539.deprecation.rst
  numpy/__init__.pyi
  numpy/core/numerictypes.py
  numpy/core/numerictypes.pyi
  numpy/core/tests/test_nep50_promotions.py
  numpy/core/tests/test_numerictypes.py
  numpy/core/tests/test_regression.py
  numpy/lib/index_tricks.py
  numpy/ma/tests/test_core.py
  numpy/typing/tests/data/fail/numerictypes.pyi
  numpy/typing/tests/data/pass/numerictypes.py
  numpy/typing/tests/data/reveal/numerictypes.pyi
Labels: 07 - Deprecation

#23758 MAINT: compatibility with cython3
  numpy/random/_pcg64.pyx
  numpy/random/_philox.pyx
Labels: 03 - Maintenance

#23739 BUG: fix the method for checking local files for 1.24.x
  numpy/compat/py3k.py
  numpy/compat/tests/test_compat.py
  numpy/lib/format.py
Labels: 00 - Bug, 08 - Backport

#23761 BUG: Fix masked array ravel order for A (and somewhat K)
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
Labels: 00 - Bug, 08 - Backport

#23727 DOC: Rewrite docstrings of `ogrid` and `mgrid`
  numpy/lib/index_tricks.py
Labels: 04 - Documentation

#23750 MAINT: do not use copyswapn in array sorting internals
  numpy/core/src/multiarray/item_selection.c
Labels: 03 - Maintenance

#23765 MAINT: fix signed/unsigned int comparison warnings
  numpy/core/src/multiarray/convert.c
  numpy/core/src/umath/loops_trigonometric.dispatch.c.src
Labels: 03 - Maintenance

#23768 TYP: Relax the `genfromtxt` return dtype when the dtype is unspecified
  numpy/lib/npyio.pyi
  numpy/typing/tests/data/reveal/npyio.pyi
Labels: 03 - Maintenance, Static typing

#23659 ENH: Restore TypeError cleanup in array function dispatching
  numpy/core/src/multiarray/arrayfunction_override.c
  numpy/core/tests/test_overrides.py
Labels: 01 - Enhancement

#23769 DOC: clarify how inputs of PyArray_ResultType are used
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#23505 BUG: Use 2GiB chunking code for fwrite() on mingw32/64
  numpy/core/include/numpy/npy_common.h
  numpy/core/src/multiarray/convert.c
Labels: 00 - Bug

#23770 MAINT: do not use copyswap in where internals
  benchmarks/benchmarks/bench_function_base.py
  numpy/core/src/multiarray/multiarraymodule.c
Labels: 03 - Maintenance

#23740 BLD: updates to the Meson build
  building_with_meson.md
  meson.build
  meson_options.txt
  numpy/core/src/umath/override.c
  numpy/meson.build
  tools/ci/cirrus_macosx_arm64.yml
Labels: 03 - Maintenance, Meson

#23723 MAINT: Do not use copyswap as part of indexing
  benchmarks/benchmarks/bench_indexing.py
  benchmarks/benchmarks/common.py
  numpy/core/src/common/lowlevel_strided_loops.h
  numpy/core/src/multiarray/lowlevel_strided_loops.c.src
  numpy/core/src/multiarray/mapping.c
Labels: 03 - Maintenance, triage review

#23779 DOC: Fix link from mtrand.randint -> Generator.integers.
  numpy/random/mtrand.pyx
Labels: 04 - Documentation

#23776 ENH: replace depcrecated distutils use in convenience function
  numpy/ctypeslib.py
Labels: 01 - Enhancement

#23772 DOC: added note for git tagging
  doc/source/dev/development_environment.rst
Labels: 04 - Documentation

#23790 DOC: used a more readable if/else form than old-style ternary operators in the 'byteorder' and 'newbyteorder' docstrings
  numpy/core/_add_newdocs.py
Labels: 04 - Documentation

#23742 BUG: Fix NEP 50 promotion in some concat/choose paths
  numpy/core/src/multiarray/convert_datatype.c
  numpy/core/src/multiarray/multiarraymodule.c
  numpy/core/tests/test_nep50_promotions.py
Labels: 00 - Bug

#23794 API: add aliases for object and void dtype classes to dtype API
  numpy/core/include/numpy/_dtype_api.h
  numpy/core/include/numpy/experimental_dtype_api.h
  numpy/core/src/multiarray/experimental_public_dtype_api.c
Labels: 30 - API

#23371 ENH: drop dtype metadata
  doc/release/upcoming_changes/23371.improvement.rst
  numpy/lib/format.py
  numpy/lib/tests/test_format.py
  numpy/lib/tests/test_utils.py
  numpy/lib/utils.py
Labels: 01 - Enhancement, 56 - Needs Release Note., triage review

#23652 ENH: structured_to_unstructured: view more often
  doc/release/upcoming_changes/23652.improvement.rst
  numpy/lib/recfunctions.py
  numpy/lib/tests/test_recfunctions.py
Labels: 01 - Enhancement

#23579 NEP: Create draft NEP for C-API evolution
  doc/neps/nep-0053-c-abi-evolution.md
  doc/source/reference/c-api/deprecations.rst
Labels: component: NEP

#23804 REL: Prepare main for NumPy 2.0.0 development
  doc/release/upcoming_changes/10615.deprecation.rst
  doc/release/upcoming_changes/18053.new_feature.rst
  doc/release/upcoming_changes/18535.improvement.rst
  doc/release/upcoming_changes/21120.new_feature.rst
  doc/release/upcoming_changes/22315.performance.rst
  doc/release/upcoming_changes/22539.change.rst
  doc/release/upcoming_changes/22539.deprecation.rst
  doc/release/upcoming_changes/22575.compatibility.rst
  doc/release/upcoming_changes/22637.compatibility.rst
  doc/release/upcoming_changes/22638.deprecation.rst
  doc/release/upcoming_changes/22638.expired.rst
  doc/release/upcoming_changes/22644.new_feature.rst
  doc/release/upcoming_changes/22675.compatibility.rst
  doc/release/upcoming_changes/22707.compatibility.rst
  doc/release/upcoming_changes/22707.expired.rst
  doc/release/upcoming_changes/22707.improvement.rst
  doc/release/upcoming_changes/22769.improvement.rst
  doc/release/upcoming_changes/22776.improvement.rst
  doc/release/upcoming_changes/22786.new_feature.rst
  doc/release/upcoming_changes/22863.new_feature.rst
  doc/release/upcoming_changes/22963.new_feature.rst
  doc/release/upcoming_changes/22982.new_feature.rst
  doc/release/upcoming_changes/22997.improvement.rst
  doc/release/upcoming_changes/22998.expired.rst
  doc/release/upcoming_changes/23011.deprecation.rst
  doc/release/upcoming_changes/23019.expired.rst
  doc/release/upcoming_changes/23020.change.rst
  doc/release/upcoming_changes/23020.performance.rst
  doc/release/upcoming_changes/23041.expired.rst
  doc/release/upcoming_changes/23060.expired.rst
  doc/release/upcoming_changes/23105.compatibility.rst
  doc/release/upcoming_changes/23113.improvement.rst
  doc/release/upcoming_changes/23136.performance.rst
  doc/release/upcoming_changes/23195.improvement.rst
  doc/release/upcoming_changes/23229.compatibility.rst
  doc/release/upcoming_changes/23240.compatibility.rst
  doc/release/upcoming_changes/23275.improvement.rst
  doc/release/upcoming_changes/23302.deprecation.rst
  doc/release/upcoming_changes/23314.deprecation.rst
  doc/release/upcoming_changes/23322.improvement.rst
  doc/release/upcoming_changes/23357.improvement.rst
  doc/release/upcoming_changes/23358.improvement.rst
  doc/release/upcoming_changes/23371.improvement.rst
  doc/release/upcoming_changes/23376.expired.rst
  doc/release/upcoming_changes/23403.expired.rst
  doc/release/upcoming_changes/23480.expired.rst
  doc/release/upcoming_changes/23528.compatibility.rst
  doc/release/upcoming_changes/23601.change.rst
  doc/release/upcoming_changes/23652.improvement.rst
  doc/release/upcoming_changes/23660.expired.rst
  doc/release/upcoming_changes/23661.performance.rst
  doc/release/upcoming_changes/23666.expired.rst
  doc/release/upcoming_changes/23713.improvement.rst
  doc/source/release.rst
  doc/source/release/2.0.0-notes.rst
  numpy/core/code_generators/cversions.txt
  pavement.py
Labels: 14 - Release, 03 - Maintenance

#23813 DOC: Clean up errstate handling in our tests
  numpy/core/_add_newdocs.py
  numpy/core/_ufunc_config.py
Labels: 04 - Documentation

#23814 DOC: switching to use the plot directive
  numpy/lib/function_base.py
  numpy/lib/histograms.py
Labels: 04 - Documentation

#23819 BUG: Doctest doesn't have a SHOW_WARNINGS directive.
  numpy/core/_ufunc_config.py
Labels: 00 - Bug

#23822 DOC: Added `pathlib.Path` where applicable
  numpy/lib/_datasource.py
  numpy/lib/npyio.py
  numpy/lib/tests/test_io.py
Labels: 04 - Documentation, component: numpy.lib

#23828 MAINT: fix typos found by codespell
  doc/neps/nep-0053-c-abi-evolution.md
  numpy/core/src/common/half.hpp
  numpy/core/src/common/half_private.hpp
  numpy/core/src/multiarray/dtype_traversal.c
  numpy/core/src/multiarray/dtypemeta.h
  numpy/lib/index_tricks.py
  numpy/lib/tests/test_utils.py
  numpy/random/_generator.pyx
  numpy/random/src/mt19937/randomkit.h
Labels: 03 - Maintenance

#23826 MAINT: io.open → open
  numpy/core/tests/test_multiarray.py
  numpy/lib/_datasource.py
  numpy/lib/tests/test_io.py
Labels: 03 - Maintenance

#23809 MAINT: removing the deprecated submodule
  numpy/core/_add_newdocs.py
  numpy/core/meson.build
  numpy/core/setup.py
  numpy/core/umath_tests.py
  numpy/tests/test_public_api.py
Labels: 03 - Maintenance

#23836 DOC: update distutils migration guide
  doc/source/reference/distutils_status_migration.rst
Labels: 04 - Documentation, 09 - Backport-Candidate

#23537 NEP: add NEP on a Python API cleanup for NumPy 2.0
  doc/neps/nep-0052-python-api-cleanup.rst
Labels: component: NEP

#23840 REL: Prepare for the NumPy 1.25.0rc1 release
  .mailmap
  22137.new_feature.rst
  doc/changelog/1.25.0-changelog.rst
  doc/release/numpy2_changes/23089.change.rst
  doc/release/numpy2_changes/README.md
  doc/release/upcoming_changes/10615.deprecation.rst
  doc/release/upcoming_changes/18053.new_feature.rst
  doc/release/upcoming_changes/18535.improvement.rst
  doc/release/upcoming_changes/21120.new_feature.rst
  doc/release/upcoming_changes/22315.performance.rst
  doc/release/upcoming_changes/22539.change.rst
  doc/release/upcoming_changes/22539.deprecation.rst
  doc/release/upcoming_changes/22575.compatibility.rst
  doc/release/upcoming_changes/22637.compatibility.rst
  doc/release/upcoming_changes/22638.deprecation.rst
  doc/release/upcoming_changes/22638.expired.rst
  doc/release/upcoming_changes/22644.new_feature.rst
  doc/release/upcoming_changes/22675.compatibility.rst
  doc/release/upcoming_changes/22707.compatibility.rst
  doc/release/upcoming_changes/22707.expired.rst
  doc/release/upcoming_changes/22707.improvement.rst
  doc/release/upcoming_changes/22769.improvement.rst
  doc/release/upcoming_changes/22776.improvement.rst
  doc/release/upcoming_changes/22786.new_feature.rst
  doc/release/upcoming_changes/22863.new_feature.rst
  doc/release/upcoming_changes/22963.new_feature.rst
  doc/release/upcoming_changes/22982.new_feature.rst
  doc/release/upcoming_changes/22997.improvement.rst
  doc/release/upcoming_changes/22998.expired.rst
  doc/release/upcoming_changes/23011.deprecation.rst
  doc/release/upcoming_changes/23019.expired.rst
  doc/release/upcoming_changes/23020.change.rst
  doc/release/upcoming_changes/23020.performance.rst
  doc/release/upcoming_changes/23041.expired.rst
  doc/release/upcoming_changes/23060.expired.rst
  doc/release/upcoming_changes/23105.compatibility.rst
  doc/release/upcoming_changes/23113.improvement.rst
  doc/release/upcoming_changes/23136.performance.rst
  doc/release/upcoming_changes/23195.improvement.rst
  doc/release/upcoming_changes/23229.compatibility.rst
  doc/release/upcoming_changes/23240.compatibility.rst
  doc/release/upcoming_changes/23275.improvement.rst
  doc/release/upcoming_changes/23302.deprecation.rst
  doc/release/upcoming_changes/23314.deprecation.rst
  doc/release/upcoming_changes/23322.improvement.rst
  doc/release/upcoming_changes/23357.improvement.rst
  doc/release/upcoming_changes/23358.improvement.rst
  doc/release/upcoming_changes/23371.improvement.rst
  doc/release/upcoming_changes/23376.expired.rst
  doc/release/upcoming_changes/23403.expired.rst
  doc/release/upcoming_changes/23480.expired.rst
  doc/release/upcoming_changes/23528.compatibility.rst
  doc/release/upcoming_changes/23601.change.rst
  doc/release/upcoming_changes/23652.improvement.rst
  doc/release/upcoming_changes/23660.expired.rst
  doc/release/upcoming_changes/23661.performance.rst
  doc/release/upcoming_changes/23666.expired.rst
  doc/release/upcoming_changes/23713.improvement.rst
  doc/source/release/1.25.0-notes.rst
Labels: 14 - Release

#23843 MAINT: Update download-wheels
  tools/download-wheels.py
Labels: 03 - Maintenance, 09 - Backport-Candidate

#23825 BLD: use cython3 for one CI run
  .github/workflows/build_test.yml
  numpy/core/tests/test_ufunc.py
  numpy/random/_generator.pyx
  numpy/random/_philox.pyx
  tools/travis-before-install.sh
  tools/travis-test.sh
Labels: 36 - Build

#23834 MAINT: IOError → OSError
  benchmarks/benchmarks/__init__.py
  numpy/distutils/command/config.py
Labels: 03 - Maintenance

#23845 MAINT: Do not call PyArray_Item_XDECREF in PyArray_Pack
  numpy/core/src/multiarray/array_coercion.c
  numpy/core/src/multiarray/convert_datatype.c
Labels: 03 - Maintenance

#23787 DOC: Add brief note about custom converters to genfromtext.
  numpy/lib/npyio.py
Labels: 04 - Documentation
