Repository numpy/numpy, pull requests merged in 2024-01, with the labels that each got.

#25516 MAINT,BUG: Fix `--dep` when `-L -l` are present
  numpy/f2py/_backends/_meson.py
Labels: 00 - Bug, component: numpy.f2py, 03 - Maintenance

#25511 DOC: np.any: add multidimensional example
  numpy/_core/fromnumeric.py
Labels: 04 - Documentation

#25512 DOC: add a section for dealing with NumPy 2.0 for downstream packages
  doc/source/dev/depending_on_numpy.rst
  doc/source/numpy_2_0_migration_guide.rst
Labels: 04 - Documentation

#25354 DOC: Add example for ``np.random.default_rng().binomial()``
  numpy/random/_generator.pyx
Labels: 04 - Documentation

#25515 BUG: three string ufunc bugs, one leading to segfault
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/tests/test_defchararray.py
  numpy/_core/tests/test_regression.py
Labels: 00 - Bug, component: numpy.core

#25473 MAINT: use cholesky_up gufunc for upper Cholesky decomposition
  numpy/linalg/_linalg.py
  numpy/linalg/tests/test_linalg.py
  numpy/linalg/umath_linalg.cpp
Labels: component: numpy.linalg, 03 - Maintenance

#25523 MAINT: prepare 1.26.x for further development
  doc/source/release.rst
  doc/source/release/1.26.4-notes.rst
  pavement.py
  pyproject.toml
  pyproject.toml.setuppy
Labels: 03 - Maintenance

#25524 MAINT: Update main after 1.26.3 release.
  .mailmap
  doc/changelog/1.26.3-changelog.rst
  doc/source/release.rst
  doc/source/release/1.26.3-notes.rst
Labels: 03 - Maintenance

#25530 DOC: Add ``rng.chisquare()`` plot
  numpy/random/_generator.pyx
Labels: 04 - Documentation

#25522 BUG: fix incorrect strcmp implementation for unequal length strings
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/tests/test_defchararray.py
Labels: 00 - Bug

#24777 BUG: `numpy.array_api`: fix `linalg.cholesky` upper decomp for complex dtypes
  numpy/array_api/linalg.py
Labels: 00 - Bug

#25534 DOC: Indicate order is kwarg-only for ndarray.reshape.
  numpy/_core/_add_newdocs.py
Labels: 04 - Documentation

#24997 DOC: Use `spin` to generate changelog
  .spin/cmds.py
  doc/RELEASE_WALKTHROUGH.rst
Labels: 04 - Documentation

#25535 MAINT: fix ufunc debug tracing
  numpy/_core/src/umath/ufunc_object.c
Labels: 03 - Maintenance, component: numpy.ufunc

#25539 BUG: ``numpy.array_api``: fix ``linalg.cholesky`` upper decomp for complex dtypes
  numpy/array_api/linalg.py
Labels: 00 - Bug, 08 - Backport

#25540 DOC: Fix typo in random.geometric docstring
  numpy/random/_generator.pyx
Labels: 04 - Documentation

#25510 BUG:Fix incorrect 'inner' method type annotation in __array_ufunc_
  numpy/__init__.pyi
  numpy/_typing/_ufunc.pyi
  numpy/lib/mixins.pyi
Labels: 00 - Bug, Static typing

#25527 DOC: Improve ``polynomial`` docs
  numpy/polynomial/polynomial.py
Labels: 04 - Documentation

#25495 API: adjust nD fft ``s`` param to array API
  doc/release/upcoming_changes/25495.deprecation.rst
  doc/release/upcoming_changes/25495.improvement.rst
  numpy/fft/_pocketfft.py
  numpy/fft/tests/test_pocketfft.py
Labels: 30 - API

#25525 MAINT: optimization and broadcasting for .replace() method for strings.
  numpy/_core/defchararray.py
  numpy/_core/tests/test_defchararray.py
Labels: component: numpy.core, 03 - Maintenance

#25507 DOC: mention string, bytes, and void dtypes in dtype intro
  doc/source/reference/routines.other.rst
  doc/source/reference/routines.rst
  doc/source/user/basics.types.rst
  numpy/dtypes.py
Labels: 04 - Documentation

#25541 ENH: add ability to use weights that align with specified axis in num…
  numpy/lib/_function_base_impl.py
  numpy/lib/tests/test_function_base.py
  numpy/ma/extras.py
  numpy/ma/tests/test_extras.py
Labels: 01 - Enhancement, component: numpy.lib

#25463 ENH: Add np.strings namespace
  doc/release/upcoming_changes/25463.new_feature.rst
  doc/source/reference/routines.rst
  doc/source/reference/routines.strings.rst
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/defchararray.pyi
  numpy/_core/include/numpy/_numpyconfig.h.in
  numpy/_core/meson.build
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_fastsearch.h
  numpy/_core/strings.py
  numpy/_core/strings.pyi
  numpy/_core/tests/test_strings.py
  numpy/meson.build
  numpy/strings/__init__.py
  numpy/strings/__init__.pyi
  numpy/tests/test_public_api.py
  numpy/typing/tests/data/fail/char.pyi
  numpy/typing/tests/data/fail/strings.pyi
  numpy/typing/tests/data/pass/modules.py
  numpy/typing/tests/data/reveal/char.pyi
  numpy/typing/tests/data/reveal/strings.pyi
Labels: 01 - Enhancement

#25555 MAINT, BLD: Fix unused inline functions warnings on clang
  numpy/_core/src/umath/loops_arithmetic.dispatch.c.src
  numpy/_core/src/umath/loops_exponent_log.dispatch.c.src
  numpy/_core/src/umath/loops_minmax.dispatch.c.src
  numpy/_core/src/umath/loops_trigonometric.dispatch.c.src
  numpy/_core/src/umath/loops_unary.dispatch.c.src
  numpy/linalg/umath_linalg.cpp
Labels: 03 - Maintenance, 09 - Backport-Candidate

#25441 API,ENH: Change definition of complex sign
  doc/release/upcoming_changes/25441.change.rst
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/function_base.py
  numpy/_core/src/umath/loops.c.src
  numpy/_core/tests/test_regression.py
  numpy/_core/tests/test_umath.py
Labels: 01 - Enhancement, component: numpy.ufunc, 30 - API

#25553 BUG: Fix return shape of inverse_indices in unique_inverse
  doc/source/release/2.0.0-notes.rst
  numpy/lib/_arraysetops_impl.py
  numpy/lib/tests/test_arraysetops.py
Labels: 00 - Bug, component: numpy.lib, triaged

#25560 BUG: np.linalg.vector_norm: return correct shape for keepdims
  numpy/linalg/_linalg.py
  numpy/linalg/tests/test_linalg.py
Labels: 00 - Bug, 09 - Backport-Candidate

#25558 ENH: Add replace ufunc to np.strings
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/strings.py
  numpy/_core/strings.pyi
  numpy/_core/tests/test_strings.py
  numpy/strings/__init__.pyi
  numpy/typing/tests/data/fail/strings.pyi
  numpy/typing/tests/data/reveal/strings.pyi
Labels: 01 - Enhancement

#25573 MAINT: add a C alias for the default integer DType
  numpy/_core/include/numpy/experimental_dtype_api.h
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/dtypemeta.h
  numpy/_core/src/multiarray/experimental_public_dtype_api.c
Labels: 03 - Maintenance

#25584 CI: Bump azure pipeline timeout to 120 minutes
  azure-pipelines.yml
Labels: 03 - Maintenance, 08 - Backport, component: CI

#25585 MAINT, BLD: Fix unused inline functions warnings on clang
  numpy/core/src/umath/loops_arithmetic.dispatch.c.src
  numpy/core/src/umath/loops_exponent_log.dispatch.c.src
  numpy/core/src/umath/loops_minmax.dispatch.c.src
  numpy/core/src/umath/loops_trigonometric.dispatch.c.src
  numpy/core/src/umath/loops_unary.dispatch.c.src
  numpy/linalg/umath_linalg.cpp
Labels: 03 - Maintenance, 08 - Backport

#24935 DOC: Update lexsort docstring for axis kwargs
  numpy/_core/multiarray.py
Labels: 04 - Documentation

#25593 DOC: fix typos in 2.0 migration guide
  doc/source/numpy_2_0_migration_guide.rst
Labels: 04 - Documentation

#25592 BUG: Fix undefined behavior when converting NaN float16 to datetime or timedelta
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/tests/test_datetime.py
Labels: 00 - Bug

#25317 ENH: Add fft optional extension submodule to numpy.array_api
  numpy/array_api/__init__.py
  numpy/array_api/fft.py
  numpy/tests/test_public_api.py
Labels: 01 - Enhancement, component: numpy.array_api

#25520 DOC: unambiguous np.histogram dtype description
  numpy/lib/_histograms_impl.py
Labels: 04 - Documentation

#25563 SIMD: Extend the enabled targets for Google Highway quicksort
  meson_options.txt
  numpy/_core/meson.build
  numpy/_core/src/common/npstd.hpp
  numpy/_core/src/common/utils.hpp
  numpy/_core/src/npysort/heapsort.hpp
  numpy/_core/src/npysort/highway_qsort_16bit.dispatch.cpp
  numpy/_core/src/npysort/quicksort.hpp
Labels: component: SIMD

#25608 MAINT: skip installing rtools on azure
  azure-steps-windows.yml
Labels: 03 - Maintenance

#25595 BUG: Allow ``None`` as ``api_version`` in ``__array_namespace__`` method
  numpy/__init__.pyi
  numpy/_core/src/multiarray/methods.c
  numpy/_core/tests/test_regression.py
Labels: 00 - Bug, Numpy 2.0 API Changes

#25169 API: Introduce ``correction`` argument for ``np.var`` and ``np.std`` [Array API]
  doc/release/upcoming_changes/25169.new_feature.rst
  doc/source/reference/array_api.rst
  numpy/_core/fromnumeric.py
  numpy/_core/fromnumeric.pyi
  numpy/_core/tests/test_numeric.py
  numpy/lib/_nanfunctions_impl.py
  numpy/lib/tests/test_nanfunctions.py
  tools/ci/array-api-skips.txt
Labels: 30 - API, Numpy 2.0 API Changes

#25233 API: Add ``device`` and ``to_device`` to ``numpy.ndarray`` [Array API]
  doc/release/upcoming_changes/25233.new_feature.rst
  doc/source/reference/array_api.rst
  numpy/__init__.pyi
  numpy/_core/_add_newdocs.py
  numpy/_core/function_base.py
  numpy/_core/function_base.pyi
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/multiarray.py
  numpy/_core/multiarray.pyi
  numpy/_core/numeric.py
  numpy/_core/numeric.pyi
  numpy/_core/src/multiarray/conversion_utils.c
  numpy/_core/src/multiarray/conversion_utils.h
  numpy/_core/src/multiarray/getset.c
  numpy/_core/src/multiarray/methods.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/multiarray/multiarraymodule.h
  numpy/_core/tests/test_multiarray.py
  numpy/fft/_helper.py
  numpy/fft/_helper.pyi
  numpy/lib/_twodim_base_impl.py
  numpy/lib/_twodim_base_impl.pyi
  numpy/matrixlib/tests/test_defmatrix.py
  tools/ci/array-api-skips.txt
Labels: 30 - API, Numpy 2.0 API Changes

#25437 API: Add ``rtol`` to ``matrix_rank`` and ``stable`` [Array API]
  doc/release/upcoming_changes/25437.new_feature.rst
  numpy/__init__.pyi
  numpy/_core/fromnumeric.py
  numpy/_core/fromnumeric.pyi
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/src/multiarray/_multiarray_tests.c.src
  numpy/_core/src/multiarray/conversion_utils.c
  numpy/_core/src/multiarray/conversion_utils.h
  numpy/_core/src/multiarray/methods.c
  numpy/_core/tests/test_multiarray.py
  numpy/linalg/_linalg.py
  numpy/linalg/_linalg.pyi
  numpy/linalg/tests/test_linalg.py
  numpy/ma/core.py
  numpy/ma/core.pyi
  tools/ci/array-api-skips.txt
Labels: 30 - API, Numpy 2.0 API Changes

#25615 MAINT: add `newaxis` to `__all__` in `numpy.array_api`
  numpy/array_api/__init__.py
Labels: 03 - Maintenance, component: numpy.array_api

#25613 BLD: fix building for windows ARM64
  numpy/_core/src/common/npy_cpu_features.c
Labels: 36 - Build

#25430 TST: Fix test_numeric on riscv64
  numpy/_core/tests/test_numeric.py
Labels: 05 - Testing

#25609 DOC: fft: correct docs about recent deprecations
  doc/release/upcoming_changes/25495.deprecation.rst
  doc/release/upcoming_changes/25495.improvement.rst
  numpy/fft/_pocketfft.py
Labels: 04 - Documentation, component: numpy.f2py

#25575 ENH: Wrap string ufuncs in np.strings to allow default arguments
  doc/source/reference/routines.strings.rst
  numpy/_core/strings.py
  numpy/_core/strings.pyi
Labels: 01 - Enhancement

#25336 API: make arange `start` argument positional-only
  doc/release/upcoming_changes/25336.compatibility.rst
  numpy/_core/_add_newdocs.py
  numpy/_core/src/common/npy_argparse.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/tests/test_multiarray.py
Labels: 30 - API

#25620 MAINT: add ``newaxis`` to ``__all__`` in ``numpy.array_api``
  numpy/array_api/__init__.py
Labels: 03 - Maintenance, 08 - Backport, component: numpy.array_api

#25619 BLD: fix building for windows ARM64
  numpy/core/src/common/npy_cpu_features.c
Labels: 08 - Backport, 36 - Build

#25618 TST: Fix test_numeric on riscv64
  numpy/core/tests/test_numeric.py
Labels: 05 - Testing, 08 - Backport

#25627 TST: Fix f2py doc test collection in editable installs
  numpy/f2py/tests/test_docs.py
Labels: 05 - Testing, component: numpy.f2py

#25628 TST: Fix test_warning_calls on Python 3.12
  numpy/tests/test_warnings.py
Labels: 05 - Testing

#25629 TST: Bump pytz to 2023.3.post1
  test_requirements.txt
Labels: 05 - Testing

#25641 DOC: Remove a duplicated argument `shape` in `empty_like`
  numpy/_core/multiarray.py
Labels: 04 - Documentation

#25409 API,MAINT: Reorganize array-wrap calling and introduce ``return_scalar``
  doc/release/upcoming_changes/25408.deprecation.rst
  doc/source/reference/arrays.classes.rst
  doc/source/user/basics.subclassing.rst
  numpy/__init__.pyi
  numpy/_core/defchararray.py
  numpy/_core/memmap.py
  numpy/_core/meson.build
  numpy/_core/src/multiarray/arrayobject.c
  numpy/_core/src/multiarray/arraywrap.c
  numpy/_core/src/multiarray/arraywrap.h
  numpy/_core/src/multiarray/calculation.c
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/ctors.h
  numpy/_core/src/multiarray/shape.c
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_deprecations.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_umath.py
  numpy/lib/_shape_base_impl.pyi
  numpy/lib/tests/test_function_base.py
  numpy/lib/tests/test_ufunclike.py
  numpy/ma/core.py
  numpy/ma/core.pyi
  numpy/ma/tests/test_subclassing.py
Labels: 30 - API

#25643 TST: Fix test_warning_calls on Python 3.12
  numpy/tests/test_warnings.py
Labels: 05 - Testing, 08 - Backport

#25645 TST: Bump pytz to 2023.3.post1
  test_requirements.txt
Labels: 05 - Testing, 08 - Backport

#25570 ENH: change list-of-array to tuple-of-array returns (Numba compat)
  doc/release/upcoming_changes/25570.change
  numpy/_core/shape_base.py
  numpy/_core/shape_base.pyi
  numpy/lib/_function_base_impl.py
  numpy/lib/_function_base_impl.pyi
  numpy/lib/_histograms_impl.py
  numpy/lib/_histograms_impl.pyi
  numpy/lib/_index_tricks_impl.py
  numpy/lib/_index_tricks_impl.pyi
  numpy/lib/_shape_base_impl.py
  numpy/lib/_shape_base_impl.pyi
  numpy/lib/_stride_tricks_impl.py
  numpy/lib/_stride_tricks_impl.pyi
  numpy/typing/tests/data/reveal/array_constructors.pyi
  numpy/typing/tests/data/reveal/histograms.pyi
  numpy/typing/tests/data/reveal/index_tricks.pyi
  numpy/typing/tests/data/reveal/lib_function_base.pyi
  numpy/typing/tests/data/reveal/shape_base.pyi
  numpy/typing/tests/data/reveal/stride_tricks.pyi
Labels: 62 - Python API, Numpy 2.0 API Changes

#25646 DOC: Fix links to f2py codes
  doc/source/f2py/advanced/use_cases.rst
Labels: 04 - Documentation

#25370 ENH: Make numpy.array_api more portable
  doc/release/upcoming_changes/25370.compatibility.rst
  doc/source/reference/array_api.rst
  numpy/array_api/_array_object.py
  numpy/array_api/_creation_functions.py
  numpy/array_api/_data_type_functions.py
  numpy/array_api/_dtypes.py
  numpy/array_api/_manipulation_functions.py
  numpy/array_api/_searching_functions.py
  numpy/array_api/_statistical_functions.py
  numpy/array_api/_typing.py
  numpy/array_api/fft.py
  numpy/array_api/linalg.py
  numpy/array_api/tests/test_array_object.py
  numpy/array_api/tests/test_creation_functions.py
  numpy/array_api/tests/test_data_type_functions.py
  numpy/array_api/tests/test_indexing_functions.py
Labels: component: numpy.array_api

#25648 DOC: fix syntax highlighting issues in added f2py docs
  doc/source/f2py/advanced/boilerplating.rst
Labels: 04 - Documentation, component: numpy.f2py

#23347 DOC: changed formula in random.Generator.pareto doc #22701
  numpy/random/_generator.pyx
Labels: 04 - Documentation, component: numpy.random

#24254 ENH: add weighted quantile for inverted_cdf
  doc/release/upcoming_changes/24254.new_feature.rst
  numpy/lib/_function_base_impl.py
  numpy/lib/_function_base_impl.pyi
  numpy/lib/_nanfunctions_impl.py
  numpy/lib/tests/test_function_base.py
  numpy/lib/tests/test_nanfunctions.py
Labels: 01 - Enhancement

#25650 DOC: improve structure of reference guide
  doc/source/reference/arrays.rst
  doc/source/reference/c-api/coremath.rst
  doc/source/reference/distutils_guide.rst
  doc/source/reference/index.rst
  doc/source/reference/routines.array-manipulation.rst
  doc/source/reference/routines.bitwise.rst
  doc/source/reference/routines.help.rst
  doc/source/reference/routines.indexing.rst
  doc/source/reference/routines.other.rst
  doc/source/reference/routines.padding.rst
  doc/source/reference/routines.rst
Labels: 04 - Documentation, component: documentation

#25652 BUG: Fix AVX512 build flags on Intel Classic Compiler
  meson_cpu/x86/meson.build
Labels: 00 - Bug, 09 - Backport-Candidate, 32 - Installation, component: SIMD, Meson

#24214 ENH: Create helper for conversion to arrays
  numpy/_core/_add_newdocs.py
  numpy/_core/code_generators/genapi.py
  numpy/_core/fromnumeric.py
  numpy/_core/function_base.py
  numpy/_core/meson.build
  numpy/_core/src/multiarray/array_converter.c
  numpy/_core/src/multiarray/array_converter.h
  numpy/_core/src/multiarray/convert_datatype.h
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/ctors.h
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/multiarray/multiarraymodule.h
  numpy/lib/_arraysetops_impl.py
  numpy/lib/_function_base_impl.py
  numpy/lib/_shape_base_impl.py
  numpy/lib/_twodim_base_impl.py
Labels: 01 - Enhancement

#25521 DOC: Improve error messages for random.choice
  numpy/random/_generator.pyx
Labels: 04 - Documentation

#25651 ENH: Allow strings in logical ufuncs
  doc/release/upcoming_changes/25651.improvement.rst
  numpy/_core/src/umath/dispatching.c
  numpy/_core/tests/test_ufunc.py
Labels: 01 - Enhancement

#25658 BUG: Fix AVX512 build flags on Intel Classic Compiler
  .github/workflows/macos.yml
  meson_cpu/x86/meson.build
Labels: 00 - Bug, 08 - Backport, 32 - Installation, component: SIMD, Meson

#25669 BLD: fix potential issue with escape sequences in `__config__.py`
  numpy/__config__.py.in
Labels: 03 - Maintenance, 09 - Backport-Candidate, 36 - Build

#25656 DOC: add autosummary API reference for DType clases.
  doc/source/reference/routines.dtypes.rst
Labels: 04 - Documentation

#25670 BLD: fix potential issue with escape sequences in ``__config__.py``
  numpy/__config__.py.in
Labels: 03 - Maintenance, 08 - Backport, 36 - Build

#25673 BUG: Ensure meson updates generated umath doc correctly.
  numpy/_core/meson.build
Labels: 00 - Bug, 36 - Build

#25664 DOC: minor improvement to the partition() docstrings
  numpy/_core/_add_newdocs.py
  numpy/_core/fromnumeric.py
Labels: 04 - Documentation

#25630 BUG: Use large file fallocate on 32 bit linux platforms
  numpy/core/feature_detection_stdio.h
  numpy/core/src/multiarray/convert.c
Labels: 00 - Bug, 08 - Backport

#25678 DOC: fix docstring of quantile and percentile
  numpy/lib/_function_base_impl.py
Labels: 04 - Documentation

#25674 DOC: add a section on NumPy's module structure to the refguide
  doc/source/f2py/usage.rst
  doc/source/reference/distutils.rst
  doc/source/reference/index.rst
  doc/source/reference/module_structure.rst
  doc/source/reference/routines.char.rst
  doc/source/reference/routines.ctypeslib.rst
  doc/source/reference/routines.dtypes.rst
  doc/source/reference/routines.emath.rst
  doc/source/reference/routines.lib.rst
  doc/source/reference/routines.matlib.rst
  doc/source/reference/routines.polynomials-package.rst
  doc/source/reference/routines.rec.rst
  doc/source/reference/routines.rst
  doc/source/reference/routines.strings.rst
  doc/source/reference/routines.testing.overrides.rst
  doc/source/reference/routines.testing.rst
  numpy/_core/records.py
  numpy/dtypes.py
  numpy/lib/_function_base_impl.py
Labels: 01 - Enhancement, 04 - Documentation, component: documentation

#25668 BUG: correct irfft with n=1 on larger input
  doc/release/upcoming_changes/25536.new_feature.rst
  numpy/fft/_pocketfft_umath.c
  numpy/fft/tests/test_pocketfft.py
Labels: 00 - Bug, component: numpy.fft

#25689 MAINT: Simplify scalar int division a bit (no need for helper func)
  numpy/_core/src/umath/scalarmath.c.src
Labels: 03 - Maintenance

#25695 DOC: empty: standardize notes about uninitialized values
  numpy/_core/_add_newdocs.py
  numpy/_core/multiarray.py
  numpy/ma/extras.py
  numpy/matlib.py
Labels: 04 - Documentation

#25683 DOC: Try add a section on NEP 50 to migration guide
  doc/neps/nep-0050-scalar-promotion.rst
  doc/source/numpy_2_0_migration_guide.rst
Labels: 04 - Documentation

#25699 DOC: Fix some references in document
  doc/source/reference/arrays.classes.rst
  doc/source/reference/arrays.ndarray.rst
  doc/source/reference/c-api/data_memory.rst
  doc/source/reference/c-api/types-and-structures.rst
  doc/source/user/basics.types.rst
  numpy/lib/_histograms_impl.py
  numpy/lib/_npyio_impl.py
  numpy/lib/_polynomial_impl.py
  numpy/lib/_utils_impl.py
  numpy/polynomial/chebyshev.py
  numpy/polynomial/hermite.py
  numpy/polynomial/hermite_e.py
  numpy/polynomial/laguerre.py
  numpy/polynomial/legendre.py
  numpy/polynomial/polynomial.py
Labels: 04 - Documentation

#25709 MAINT: Include header defining backtrace
  numpy/_core/src/multiarray/temp_elide.c
Labels: 03 - Maintenance

#25710 TST: marks on a fixture have no effect
  numpy/typing/tests/test_typing.py
Labels: 05 - Testing, 09 - Backport-Candidate

#25715 [MAINT] Add regression test for np.geomspace
  numpy/_core/tests/test_function_base.py
Labels: 05 - Testing

#25718 CI: pin cygwin python to 3.9.16-1 and fix typing tests [skip cirrus][skip azp][skip circle]
  .github/workflows/cygwin.yml
  numpy/typing/tests/test_typing.py
Labels: 03 - Maintenance, 08 - Backport, component: CI

#25717 DOC: Fix some minor formatting errors in NEPs
  doc/neps/nep-0050-scalar-promotion.rst
  doc/neps/nep-0053-c-abi-evolution.rst
Labels: 04 - Documentation

#24711 BUG: Fix np.quantile([Fraction(2,1)], 0.5)
  numpy/lib/_function_base_impl.py
  numpy/lib/tests/test_function_base.py
Labels: 00 - Bug, component: numpy.lib, 09 - Backport-Candidate

#25697 CI: add pinning for scipy-openblas wheels
  .circleci/config.yml
  .github/meson_actions/action.yml
  .github/workflows/emscripten.yml
  .github/workflows/linux.yml
  .github/workflows/linux_blas.yml
  .github/workflows/linux_compiler_sanitizers.yml
  .github/workflows/linux_musl.yml
  .github/workflows/linux_qemu.yml
  .github/workflows/linux_simd.yml
  .github/workflows/macos.yml
  .github/workflows/mypy.yml
  .github/workflows/wheels.yml
  .github/workflows/windows.yml
  .spin/cmds.py
  azure-pipelines.yml
  azure-steps-windows.yml
  building_with_meson.md
  doc/RELEASE_WALKTHROUGH.rst
  doc/make.bat
  doc/source/building/index.rst
  doc/source/dev/development_environment.rst
  doc/source/dev/howto_build_docs.rst
  doc/source/dev/index.rst
  pyproject.toml
  requirements/all_requirements.txt
  requirements/build_requirements.txt
  requirements/ci32_requirements.txt
  requirements/ci_requirements.txt
  requirements/doc_requirements.txt
  requirements/linter_requirements.txt
  requirements/release_requirements.txt
  requirements/test_requirements.txt
  tools/ci/cirrus_arm.yml
  tools/ci/run_32_bit_linux_docker.sh
Labels: component: CI

#25727 DOC: Remove function name without signature in ``ma``
  numpy/ma/extras.py
Labels: 04 - Documentation

#25712 API: Make any and all return booleans by default
  doc/release/upcoming_changes/25712.change.rst
  numpy/_core/_methods.py
  numpy/_core/fromnumeric.py
  numpy/_core/tests/test_multiarray.py
  numpy/lib/tests/test_function_base.py
Labels: 30 - API

#25734 DOC: Fix markups of code literals in ``polynomial``
  numpy/polynomial/__init__.py
  numpy/polynomial/_polybase.py
  numpy/polynomial/chebyshev.py
  numpy/polynomial/hermite.py
  numpy/polynomial/hermite_e.py
  numpy/polynomial/laguerre.py
  numpy/polynomial/legendre.py
  numpy/polynomial/polynomial.py
Labels: 04 - Documentation

#25730 ENH: add a pkg-config file and a `numpy-config` script
  doc/release/upcoming_changes/25730.new_feature.rst
  numpy/_configtool.py
  numpy/_core/meson.build
  numpy/_core/numpy.pc.in
  numpy/lib/_utils_impl.py
  numpy/meson.build
  numpy/tests/test_configtool.py
  pyproject.toml
Labels: 01 - Enhancement, component: distribution

#25529 DOC: Add ``rng.f()`` plot
  numpy/random/_generator.pyx
Labels: 04 - Documentation

#24745 ENH: Change default values in polynomial package
  doc/source/reference/routines.polynomials.classes.rst
  doc/source/reference/routines.polynomials.rst
  numpy/polynomial/chebyshev.py
  numpy/polynomial/hermite.py
  numpy/polynomial/hermite_e.py
  numpy/polynomial/laguerre.py
  numpy/polynomial/legendre.py
  numpy/polynomial/polynomial.py
  numpy/polynomial/tests/test_printing.py
Labels: 01 - Enhancement, component: numpy.polynomial
