Repository numpy/numpy, pull requests merged in 2024-02, with the labels that each got.

#25740 DOC: Fix doctest failure in ``polynomial``
  numpy/polynomial/chebyshev.py
  numpy/polynomial/legendre.py
Labels: 04 - Documentation

#25738 MAINT: add `trapezoid` as the new name for `trapz`
  doc/release/upcoming_changes/24445.deprecation.rst
  doc/source/numpy_2_0_migration_guide.rst
  numpy/__init__.py
  numpy/lib/_function_base_impl.py
  numpy/lib/tests/test_function_base.py
Labels: component: numpy.lib, 03 - Maintenance

#25732 CI: use version 0.3.26.0.2 of scipy-openblas wheels
  .spin/cmds.py
  requirements/ci32_requirements.txt
  requirements/ci_requirements.txt
Labels: component: CI

#25594 MAINT: replace uses of cython numpy.math.pxd with native routines
  numpy/random/_common.pyx
Labels: 36 - Build

#25528 DOC: Add notes to ``rng.bytes()``
  numpy/random/_generator.pyx
Labels: 04 - Documentation

#25707 DOC: fix a small np.einsum example
  numpy/_core/_add_newdocs.py
  numpy/_core/einsumfunc.py
Labels: 04 - Documentation

#25755 MAINT: Include header defining backtrace
  numpy/core/src/multiarray/temp_elide.c
Labels: 03 - Maintenance, 08 - Backport

#25756 BUG: Fix np.quantile([Fraction(2,1)], 0.5) (#24711)
  numpy/lib/function_base.py
  numpy/lib/tests/test_function_base.py
Labels: 00 - Bug, component: numpy.lib, 08 - Backport

#25431 DOC: Improve ``np.mean`` documentation of the out argument
  numpy/_core/fromnumeric.py
  numpy/lib/_nanfunctions_impl.py
Labels: 04 - Documentation, 57 - Close?

#25758 DOC: Fix summary table in linalg routines document
  doc/source/reference/routines.linalg.rst
Labels: 04 - Documentation

#25574 DOC: ensure that docstrings for np.ndarray.copy, np.copy and np.array all mention (or link to explanation) that object arrays are shallow-copied
  numpy/_core/_add_newdocs.py
  numpy/lib/_function_base_impl.py
Labels: 04 - Documentation

#25761 DEP: Finalize future warning for shape=1 descriptor dropping shape
  doc/release/upcoming_changes/25761.expired.rst
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/tests/test_deprecations.py
  numpy/_core/tests/test_dtype.py
Labels: 07 - Deprecation

#25323 BUG: Restore missing asstr import
  numpy/f2py/tests/util.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#25753 DOC: Fix ``ufunc.reduceat`` doc for ``dtype``
  numpy/_core/_add_newdocs.py
Labels: 04 - Documentation

#25636 MAINT: Move np.char methods to np.strings
  doc/source/reference/routines.char.rst
  doc/source/reference/routines.rst
  doc/source/reference/routines.strings.rst
  numpy/_core/defchararray.py
  numpy/_core/strings.py
  numpy/_core/strings.pyi
  numpy/strings/__init__.pyi
  numpy/tests/test_public_api.py
  numpy/typing/tests/data/fail/strings.pyi
  numpy/typing/tests/data/reveal/strings.pyi
  tools/refguide_check.py
Labels: 03 - Maintenance

#25751 DOC: Update ruff rule instruction
  doc/source/numpy_2_0_migration_guide.rst
Labels: 04 - Documentation, Numpy 2.0 API Changes

#25771 MAINT: prepare 1.26.x for further development
  .github/workflows/scorecards.yml
  .github/workflows/wheels.yml
  doc/source/release.rst
  doc/source/release/1.26.5-notes.rst
  pavement.py
  pyproject.toml
  pyproject.toml.setuppy
Labels: 03 - Maintenance

#25772 MAINT: Update main after 1.26.4 release.
  doc/changelog/1.26.4-changelog.rst
  doc/source/release.rst
  doc/source/release/1.26.4-notes.rst
Labels: 04 - Documentation, 03 - Maintenance

#25783 DOC: Remove references to ``distutils`` in simd document
  doc/source/reference/simd/build-options.rst
Labels: 04 - Documentation

#24193 DEP: Remove datetime64 deprecation warning when constructing with timezone
  doc/release/upcoming_changes/24193.change.rst
  numpy/_core/_add_newdocs_scalars.py
  numpy/_core/src/multiarray/datetime.c
  numpy/_core/src/multiarray/datetime_strings.c
  numpy/_core/tests/test_datetime.py
  numpy/_core/tests/test_deprecations.py
Labels: 01 - Enhancement

#25347 API: Introduce stringdtype [NEP 55]
  doc/neps/nep-0055-string_dtype.rst
  doc/release/upcoming_changes/25347.c_api.rst
  doc/release/upcoming_changes/25347.new_feature.rst
  doc/source/reference/c-api/dtype.rst
  doc/source/user/basics.rst
  doc/source/user/basics.strings.rst
  numpy/_core/_add_newdocs.py
  numpy/_core/_dtype.py
  numpy/_core/_internal.py
  numpy/_core/code_generators/cversions.txt
  numpy/_core/code_generators/genapi.py
  numpy/_core/code_generators/numpy_api.py
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/meson.build
  numpy/_core/src/common/gil_utils.h
  numpy/_core/src/common/templ_common.h.src
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/conversion_utils.c
  numpy/_core/src/multiarray/conversion_utils.h
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/dtypemeta.h
  numpy/_core/src/multiarray/einsum_sumprod.c.src
  numpy/_core/src/multiarray/experimental_public_dtype_api.c
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/multiarray/stringdtype/casts.c
  numpy/_core/src/multiarray/stringdtype/casts.h
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/src/multiarray/stringdtype/dtype.h
  numpy/_core/src/multiarray/stringdtype/static_string.c
  numpy/_core/src/multiarray/stringdtype/static_string.h
  numpy/_core/src/multiarray/stringdtype/utf8_utils.c
  numpy/_core/src/multiarray/stringdtype/utf8_utils.h
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_fastsearch.h
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/src/umath/string_ufuncs.h
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/src/umath/stringdtype_ufuncs.h
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/src/umath/umathmodule.c
  numpy/_core/strings.py
  numpy/_core/tests/_natype.py
  numpy/_core/tests/test_stringdtype.py
  numpy/_core/tests/test_strings.py
Labels: 30 - API

#25768 DOC: in ufuncs ``dtype`` is not ignored when ``out`` is passed
  doc/source/user/basics.ufuncs.rst
Labels: 04 - Documentation

#25790 MAINT: Private device struct shouldn't be in public header
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/src/multiarray/conversion_utils.h
Labels: 03 - Maintenance

#25793 MAINT: update docstrings of string ufuncs to mention StringDType
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/strings.py
Labels: 03 - Maintenance

#25794 DEP: expire some deprecations
  doc/release/upcoming_changes/25794.expired.rst
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/numeric.py
  numpy/_core/src/multiarray/_multiarray_tests.c.src
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/getset.c
  numpy/_core/tests/test_deprecations.py
  numpy/_core/tests/test_multiarray.py
Labels: 07 - Deprecation

#25774 DOC: Update docs build dependencies install cmd
  doc/source/dev/howto_build_docs.rst
Labels: 04 - Documentation

#25795 DOC: fix docstring example in f2py.get_include
  doc/source/f2py/f2py-examples.rst
  numpy/f2py/__init__.py
Labels: 04 - Documentation, component: numpy.f2py

#25505 BLD: replace uses of openblas_support with openblas wheels [wheel build]
  .github/workflows/linux.yml
  .github/workflows/linux_blas.yml
  .github/workflows/wheels.yml
  .github/workflows/windows.yml
  .spin/cmds.py
  doc/release/upcoming_changes/25730.new_feature.rst
  pyproject.toml
  requirements/ci32_requirements.txt
  requirements/ci_requirements.txt
  tools/ci/cirrus_arm.yml
  tools/ci/cirrus_wheels.yml
  tools/openblas_support.py
  tools/wheels/LICENSE_win32.txt
  tools/wheels/cibw_before_build.sh
  tools/wheels/repair_windows.sh
Labels: 36 - Build

#25797 MAINT: Move ``NPY_VSTRING`` and make ``NPY_NTYPES NPY_TYPES_LEGACY``
  doc/release/upcoming_changes/25347.c_api.rst
  doc/source/reference/c-api/dtype.rst
  doc/source/reference/c-api/types-and-structures.rst
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/src/multiarray/abstractdtypes.c
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/can_cast_table.h
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/datetime.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/einsum_sumprod.c.src
  numpy/_core/src/multiarray/legacy_dtype_implementation.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/src/multiarray/scalartypes.h
  numpy/_core/src/multiarray/usertypes.c
  numpy/_core/src/umath/ufunc_type_resolution.c
  numpy/_core/tests/test_dtype.py
  numpy/f2py/tests/src/array_from_pyobj/wrapmodule.c
  tools/replace_old_macros.sed
Labels: 03 - Maintenance

#25800 REV: revert tuple/list return type changes for `*split` functions
  doc/release/upcoming_changes/25570.change
  numpy/lib/_shape_base_impl.py
  numpy/lib/_shape_base_impl.pyi
  numpy/typing/tests/data/reveal/shape_base.pyi
Labels: 03 - Maintenance, 62 - Python API, 34 - Reversion

#25792 API: Create ``PyArray_DescrProto`` for legacy descriptor registration
  doc/release/upcoming_changes/25792.c_api.rst
  doc/source/reference/c-api/array.rst
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/src/multiarray/_multiarray_tests.c.src
  numpy/_core/src/multiarray/usertypes.c
  numpy/_core/src/multiarray/usertypes.h
  numpy/_core/src/umath/_rational_tests.c
Labels: 30 - API

#25801 DOC: Update ``np.char.array`` docstring
  numpy/_core/defchararray.py
Labels: 04 - Documentation

#23967 DOC: Fix references to `trimseq` in docstrings
  numpy/polynomial/polyutils.py
Labels: 04 - Documentation

#25803 BLD: restore 'setup-args=-Duse-ilp64=true' in cibuildwheel [wheel build]
  pyproject.toml
Labels: 36 - Build

#25533 DOC: Improve ``poisson`` plot
  numpy/random/_generator.pyx
Labels: 04 - Documentation

#25804 MAINT: Use preprocessor directive rather than code when adding casts
  numpy/_core/src/multiarray/arraytypes.c.src
Labels: 03 - Maintenance

#25807 DOC: Fix code-block formatting for new PyArray_RegisterDataType docs
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#25745 DEV: add .editorconfig for C/C++
  .editorconfig
Labels: 16 - Development, triage review

#25806 DOC: Update the CPU build options document
  doc/source/reference/simd/build-options.rst
Labels: 04 - Documentation

#25814 MAINT: Use ``_ITEMSIZE`` rather than ``_DESCR(arr)->elsize``
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/src/common/array_assign.c
  numpy/_core/src/multiarray/array_assign_scalar.c
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/calculation.c
  numpy/_core/src/multiarray/compiled_base.c
  numpy/_core/src/multiarray/convert.c
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/getset.c
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/src/multiarray/iterators.c
  numpy/_core/src/multiarray/methods.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/src/multiarray/shape.c
  numpy/_core/src/umath/ufunc_object.c
  numpy/f2py/src/fortranobject.c
  numpy/f2py/src/fortranobject.h
Labels: 03 - Maintenance

#25818 MAINT: Propagate requirement of cython 0.29.34
  numpy/core/tests/test_cython.py
  setup.py
Labels: 03 - Maintenance

#25617 BUG: Pass newline to datasource.open() in numpy.lib.npio.
  numpy/lib/npyio.py
  numpy/lib/npyio.pyi
  numpy/lib/tests/test_io.py
Labels: 56 - Needs Release Note.

#25821 BUG: ensure that FFT routines can deal with integer and bool arrays
  numpy/fft/_pocketfft.py
  numpy/fft/tests/test_pocketfft.py
Labels: 00 - Bug, component: numpy.fft

#25822 BLD: use homebrew gfortran
  tools/ci/cirrus_wheels.yml
Labels: 36 - Build

#25754 API: Expose the dtype C API
  doc/release/upcoming_changes/25754.c_api.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/types-and-structures.rst
  numpy/_core/_add_newdocs.py
  numpy/_core/code_generators/cversions.txt
  numpy/_core/code_generators/genapi.py
  numpy/_core/code_generators/generate_numpy_api.py
  numpy/_core/code_generators/numpy_api.py
  numpy/_core/include/meson.build
  numpy/_core/include/numpy/_public_dtype_api_table.h
  numpy/_core/include/numpy/dtype_api.h
  numpy/_core/include/numpy/experimental_dtype_api.h
  numpy/_core/include/numpy/ndarrayobject.h
  numpy/_core/meson.build
  numpy/_core/src/common/umathmodule.h
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/src/multiarray/array_converter.c
  numpy/_core/src/multiarray/array_method.c
  numpy/_core/src/multiarray/array_method.h
  numpy/_core/src/multiarray/common_dtype.c
  numpy/_core/src/multiarray/common_dtype.h
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/datetime.c
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/src/multiarray/dtype_traversal.c
  numpy/_core/src/multiarray/dtype_traversal.h
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/dtypemeta.h
  numpy/_core/src/multiarray/experimental_public_dtype_api.c
  numpy/_core/src/multiarray/experimental_public_dtype_api.h
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/multiarray/number.c
  numpy/_core/src/multiarray/public_dtype_api.c
  numpy/_core/src/multiarray/public_dtype_api.h
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/src/multiarray/usertypes.c
  numpy/_core/src/umath/_scaled_float_dtype.c
  numpy/_core/src/umath/_umath_tests.c.src
  numpy/_core/src/umath/dispatching.c
  numpy/_core/src/umath/dispatching.h
  numpy/_core/src/umath/extobj.c
  numpy/_core/src/umath/legacy_array_method.c
  numpy/_core/src/umath/special_integer_comparisons.cpp
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/src/umath/wrapping_array_method.c
Labels: 30 - API

#25828 DOC: two minor fixes for DType API doc formatting
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#25830 DOC: Fix typo in nep 0052
  doc/neps/nep-0052-python-api-cleanup.rst
Labels: 04 - Documentation

#25796 MAINT: combine string ufuncs by passing on auxilliary data
  numpy/_core/include/numpy/dtype_api.h
  numpy/_core/src/multiarray/array_method.c
  numpy/_core/src/multiarray/array_method.h
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
Labels: component: numpy.core, 03 - Maintenance

#25775 ENH: Add index/rindex ufuncs for unicode and bytes dtypes
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/strings.py
  numpy/_core/tests/test_strings.py
Labels: 01 - Enhancement

#25813 DOC: Update genfromtxt documentation
  numpy/lib/_npyio_impl.py
Labels: 04 - Documentation

#25833 DOC: Fix some reference warnings
  doc/source/reference/arrays.classes.rst
  doc/source/reference/routines.array-manipulation.rst
  doc/source/release/1.20.0-notes.rst
  numpy/distutils/ccompiler.py
  numpy/distutils/misc_util.py
Labels: 04 - Documentation

#25834 BUG: ensure static_string.buf is never NULL for a non-null string
  .github/workflows/linux_compiler_sanitizers.yml
  numpy/_core/src/multiarray/stringdtype/static_string.c
Labels: 00 - Bug

#25739 TST: run macos_arm64 test on Github Actions
  .github/workflows/macos.yml
  numpy/linalg/tests/test_linalg.py
  tools/ci/cirrus_arm.yml
Labels: 05 - Testing

#25842 DOC: Fix some incorrect rst markups
  doc/DISTUTILS.rst
  doc/source/reference/arrays.dtypes.rst
  doc/source/reference/c-api/array.rst
  doc/source/release/1.13.0-notes.rst
  doc/source/user/basics.strings.rst
Labels: 04 - Documentation

#25839 TST: fix Cython compile test which invokes `meson`
  numpy/_core/tests/test_cython.py
Labels: 05 - Testing

#25816 API: Introduce ``PyDataType_FLAGS`` accessor for public access
  doc/release/upcoming_changes/25816.c_api.rst
  doc/release/upcoming_changes/25816.change.rst
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/_core/include/numpy/ndarrayobject.h
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/src/multiarray/einsum_sumprod.c.src
  numpy/_core/tests/examples/cython/checks.pyx
  numpy/_core/tests/test_cython.py
Labels: 30 - API

#25817 ENH: Add more const qualifiers to C API arguments
  numpy/_core/include/numpy/ndarraytypes.h
Labels: 01 - Enhancement

#25791 ENH: Add rest of unary ufuncs for unicode/bytes dtypes
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/src/common/numpyos.c
  numpy/_core/src/common/numpyos.h
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/strings.py
  numpy/_core/tests/test_stringdtype.py
  numpy/_core/tests/test_strings.py
Labels: 01 - Enhancement

#25838 MAINT: Update pinned setuptools for Python < 3.12
  requirements/test_requirements.txt
Labels: 03 - Maintenance, 25 - WIP

#25843 BUG: ensure empty cholesky upper does not hang.
  numpy/linalg/tests/test_regression.py
  numpy/linalg/umath_linalg.cpp
Labels: 00 - Bug, component: numpy.linalg

#25845 DOC: Fix some typos
  doc/source/reference/c-api/array.rst
  doc/source/user/basics.strings.rst
  numpy/polynomial/hermite.py
Labels: 04 - Documentation

#25812 API: Make ``descr->f`` only accessible through ``PyDataType_GetArrFuncs``
  doc/release/upcoming_changes/25812.c_api.rst
  doc/source/reference/c-api/types-and-structures.rst
  numpy/_core/code_generators/cversions.txt
  numpy/_core/code_generators/numpy_api.py
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/src/common/cblasfuncs.c
  numpy/_core/src/multiarray/_multiarray_tests.c.src
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/calculation.c
  numpy/_core/src/multiarray/compiled_base.c
  numpy/_core/src/multiarray/convert.c
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/datetime.c
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/src/multiarray/dtype_transfer.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/dtypemeta.h
  numpy/_core/src/multiarray/getset.c
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/src/multiarray/iterators.c
  numpy/_core/src/multiarray/legacy_dtype_implementation.c
  numpy/_core/src/multiarray/methods.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/multiarray/number.c
  numpy/_core/src/multiarray/scalarapi.c
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/src/multiarray/usertypes.c
  numpy/_core/src/npysort/binsearch.cpp
  numpy/_core/src/npysort/heapsort.cpp
  numpy/_core/src/npysort/mergesort.cpp
  numpy/_core/src/npysort/npysort_common.h
  numpy/_core/src/npysort/quicksort.cpp
  numpy/_core/src/npysort/timsort.cpp
  numpy/_core/src/umath/_scaled_float_dtype.c
Labels: 30 - API

#25856 MAINT: Remove unnnecessary size argument in StringDType initializer
  numpy/_core/_add_newdocs.py
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/strings.py
Labels: 03 - Maintenance

#25851 DOC: Fix some reference warnings
  doc/source/dev/internals.code-explanations.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/iterator.rst
  doc/source/reference/c-api/types-and-structures.rst
  doc/source/reference/routines.dtypes.rst
  doc/source/reference/routines.testing.rst
Labels: 04 - Documentation

#25854 BUG: Correctly refcount array descr in empty_like
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/tests/test_numeric.py
Labels: 00 - Bug

#25862 Revert "API: Make ``descr->f`` only accessible through ``PyDataType_GetArrFuncs``"
  doc/release/upcoming_changes/25812.c_api.rst
  doc/source/reference/c-api/types-and-structures.rst
  numpy/_core/code_generators/cversions.txt
  numpy/_core/code_generators/numpy_api.py
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/src/common/cblasfuncs.c
  numpy/_core/src/multiarray/_multiarray_tests.c.src
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/calculation.c
  numpy/_core/src/multiarray/compiled_base.c
  numpy/_core/src/multiarray/convert.c
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/datetime.c
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/src/multiarray/dtype_transfer.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/dtypemeta.h
  numpy/_core/src/multiarray/getset.c
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/src/multiarray/iterators.c
  numpy/_core/src/multiarray/legacy_dtype_implementation.c
  numpy/_core/src/multiarray/methods.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/multiarray/number.c
  numpy/_core/src/multiarray/scalarapi.c
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/src/multiarray/usertypes.c
  numpy/_core/src/npysort/binsearch.cpp
  numpy/_core/src/npysort/heapsort.cpp
  numpy/_core/src/npysort/mergesort.cpp
  numpy/_core/src/npysort/npysort_common.h
  numpy/_core/src/npysort/quicksort.cpp
  numpy/_core/src/npysort/timsort.cpp
  numpy/_core/src/umath/_scaled_float_dtype.c
Labels: component: numpy._core, 03 - Maintenance

#25861 CI: make chocolatey fail when a dependency doesn't install
  .github/workflows/wheels.yml
  .github/workflows/windows.yml
  azure-steps-windows.yml
Labels: 03 - Maintenance, component: CI

#25847 MAINT: Adjust rest of string ufuncs to static_data approach
  numpy/_core/src/umath/string_ufuncs.cpp
Labels: 03 - Maintenance

#25865 ENH: print traceback after printing ABI mismatch error
  numpy/core/_multiarray_umath.py
Labels: 01 - Enhancement

#25870 BUG: use print to actually output something
  .github/workflows/linux.yml
  .github/workflows/linux_blas.yml
  tools/check_openblas_version.py
Labels: 00 - Bug

#25876 API: Remove no-op C API functions
  numpy/_core/code_generators/cversions.txt
  numpy/_core/code_generators/numpy_api.py
  numpy/_core/src/multiarray/datetime.c
Labels: 30 - API

#25879 DOC: Add a document entry of ``PyArray_DescrProto``
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#25881 BUG: Fix gh-25867 for used functions and subroutines
  .gitattributes
  .gitignore
  numpy/f2py/f90mod_rules.py
  numpy/f2py/tests/src/module_data/mod.mod
  numpy/f2py/tests/src/modules/gh25337/data.f90
  numpy/f2py/tests/src/modules/gh25337/use_data.f90
  numpy/f2py/tests/src/modules/module_data_docstring.f90
  numpy/f2py/tests/src/modules/use_modules.f90
  numpy/f2py/tests/test_module_doc.py
  numpy/f2py/tests/test_modules.py
  numpy/f2py/tests/test_regression.py
Labels: 00 - Bug, component: numpy.f2py

#25883 BUG: fix typo in 'message' static variable of TestDeprecatedDTypeParenthesizedRepeatCount
  numpy/_core/tests/test_deprecations.py
Labels: 00 - Bug

#25885 DOC: fix typos
  doc/changelog/1.20.0-changelog.rst
  doc/neps/nep-0054-simd-cpp-highway.rst
  doc/release/upcoming_changes/25816.change.rst
  doc/source/f2py/advanced/boilerplating.rst
  doc/source/f2py/buildtools/distutils-to-meson.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/types-and-structures.rst
  doc/source/release/1.21.1-notes.rst
  doc/source/release/1.23.0-notes.rst
  doc/source/release/2.0.0-notes.rst
  doc/source/user/basics.strings.rst
Labels: 04 - Documentation

#25884 BUG: Fix typo in LEGACY_CONS_NON_NEGATVE_INBOUNDS_LONG
  numpy/random/_common.pxd
  numpy/random/_common.pyx
  numpy/random/mtrand.pyx
Labels: 00 - Bug

#25866 API: Fix compat header and add new import helpers
  doc/release/upcoming_changes/25866.c_api.rst
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/ufunc.rst
  numpy/_core/code_generators/generate_ufunc_api.py
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/include/numpy/ufuncobject.h
  numpy/_core/src/umath/_umath_tests.c.src
Labels: 30 - API

#25864 ENH: Implement multiply ufunc for unicode & bytes
  numpy/_core/defchararray.py
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/src/umath/ufunc_type_resolution.c
  numpy/_core/strings.py
  numpy/_core/tests/test_strings.py
Labels: 01 - Enhancement

#25877 BUG: Include broadcasting for ``rtol`` argument in ``matrix_rank``
  numpy/linalg/_linalg.py
  numpy/linalg/tests/test_regression.py
Labels: 00 - Bug, Numpy 2.0 API Changes

#25886 MAINT: fix code comment typos in numpy/ directory
  numpy/_core/_add_newdocs.py
  numpy/_core/code_generators/generate_numpy_api.py
  numpy/_core/include/numpy/ndarrayobject.h
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/src/common/simd/intdiv.h
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/stringdtype/static_string.c
  numpy/_core/src/multiarray/stringdtype/static_string.h
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/tests/examples/cython/checks.pyx
  numpy/_core/tests/test_numeric.py
  numpy/_core/tests/test_stringdtype.py
  numpy/fft/_pocketfft.py
  numpy/linalg/_linalg.py
Labels: 03 - Maintenance

#25542 NEP: add NEP 56 on array API standard support in main namespace
  doc/neps/nep-0056-array-api-main-namespace.rst
Labels: component: NEP

#25901 BLD: Add meson check to test presence of pocketfft git submodule
  numpy/fft/meson.build
Labels: 36 - Build

#25894 CI, BLD, TST: Re-enable Emscripten/Pyodide CI job for NumPy
  .github/workflows/emscripten.yml
  .gitignore
  meson_cpu/meson.build
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_stringdtype.py
  numpy/_core/tests/test_ufunc.py
  numpy/f2py/tests/__init__.py
  numpy/f2py/tests/util.py
  numpy/tests/test_configtool.py
  requirements/emscripten_test_requirements.txt
  requirements/test_requirements.txt
  tools/ci/emscripten/0001-do-not-set-meson-environment-variable-pyodide-gh-4502.patch
  tools/ci/emscripten/emscripten.meson.cross
Labels: component: CI

#25891 ENH: Add expandtabs ufunc for string & unicode dtypes
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/strings.py
  numpy/_core/tests/test_strings.py
  numpy/_core/umath.py
Labels: 01 - Enhancement
