Repository numpy/numpy, pull requests merged in 2024-12, with the labels that each got.

#27886 MAINT: Move uint aligned check to actual transfer function setup
  numpy/_core/src/multiarray/nditer_api.c
  numpy/_core/src/multiarray/nditer_constr.c
  numpy/_core/src/multiarray/nditer_impl.h
  numpy/_core/tests/test_nditer.py
Labels: 03 - Maintenance

#27887 MAINT: A few other small nditer fixes
  numpy/_core/src/multiarray/nditer_constr.c
Labels: 03 - Maintenance

#27891 ENH: update `__module__` in `numpy.random` module
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
  numpy/tests/test_public_api.py
Labels: 01 - Enhancement

#27784 BUG: ``sinc``: fix underflow for float16
  numpy/lib/_function_base_impl.py
  numpy/lib/tests/test_function_base.py
Labels: 03 - Maintenance

#27895 DOC: Fix double import in docs (#27878)
  doc/source/reference/random/index.rst
Labels: 04 - Documentation, 08 - Backport

#27898 MAINT: Remove ``25675.new_feature.rst`` snippet.
  doc/release/upcoming_changes/25675.new_feature.rst
Labels: 03 - Maintenance

#27875 MAINT: Ensure correct handling for very large unicode strings
  numpy/_core/src/multiarray/common.c
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/tests/test_strings.py
Labels: 03 - Maintenance, 09 - Backport-Candidate

#27904 MAINT: Ensure correct handling for very large unicode strings
  numpy/_core/src/multiarray/common.c
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/tests/test_strings.py
Labels: 03 - Maintenance, 08 - Backport

#27906 MAINT: Use mask_store instead of store for compiler workaround
  numpy/_core/src/umath/loops_exponent_log.dispatch.c.src
Labels: 03 - Maintenance, 08 - Backport

#27905 MAINT: Ensure correct handling for very large unicode strings
  numpy/_core/src/multiarray/common.c
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/tests/test_strings.py
Labels: 03 - Maintenance, 08 - Backport

#27862 MAINT: Drop Python 3.10 support.
  .github/workflows/linux.yml
  .github/workflows/linux_musl.yml
  .github/workflows/linux_simd.yml
  .github/workflows/macos.yml
  .github/workflows/mypy.yml
  .github/workflows/wheels.yml
  .github/workflows/windows.yml
  INSTALL.rst
  azure-pipelines.yml
  numpy/_core/src/multiarray/stringdtype/static_string.c
  pyproject.toml
  tools/ci/cirrus_arm.yml
  tools/ci/cirrus_wheels.yml
  tools/ci/run_32_bit_linux_docker.sh
Labels: 03 - Maintenance

#27877 ENH: Refactor ``__qualname__`` across API
  numpy/__config__.py.in
  numpy/__config__.pyi
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_core/multiarray.py
  numpy/_core/strings.py
  numpy/_core/tests/test_umath.py
  numpy/_typing/_ufunc.pyi
  numpy/ma/core.py
  numpy/ma/extras.py
  numpy/ma/timer_comparison.py
  numpy/random/mtrand.pyx
  numpy/tests/test_public_api.py
  numpy/typing/tests/data/reveal/ufuncs.pyi
Labels: 01 - Enhancement

#27896 PERF: improve multithreaded ufunc scaling
  doc/release/upcoming_changes/27896.performance.rst
  numpy/_core/code_generators/genapi.py
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/meson.build
  numpy/_core/src/common/npy_hashtable.cpp
  numpy/_core/src/common/npy_hashtable.h
  numpy/_core/src/multiarray/common.h
  numpy/_core/src/multiarray/npy_static_data.h
  numpy/_core/src/umath/dispatching.cpp
  numpy/_core/src/umath/dispatching.h
  numpy/_core/src/umath/ufunc_object.h
  numpy/_core/src/umath/ufunc_type_resolution.h
Labels: 09 - Backport-Candidate, 39 - free-threading

#27916 MAINT: Bump actions/cache from 4.1.2 to 4.2.0
  .github/workflows/linux_qemu.yml
  .github/workflows/macos.yml
Labels: 03 - Maintenance

#27917 CI: Use hashes in specifying some actions.
  .github/workflows/linux.yml
  .github/workflows/linux_qemu.yml
Labels: 03 - Maintenance

#27910 MAINT: Make qualname tests more specific and fix code where needed
  numpy/_core/numerictypes.py
  numpy/linalg/lapack_litemodule.c
  numpy/ma/core.py
  numpy/tests/test_public_api.py
Labels: 03 - Maintenance

#27899 TST: add timeouts for github actions tests and wheel builds.
  .github/meson_actions/action.yml
  .github/workflows/linux.yml
  .github/workflows/linux_blas.yml
  .github/workflows/linux_compiler_sanitizers.yml
  .github/workflows/linux_musl.yml
  .github/workflows/linux_qemu.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  numpy/linalg/tests/test_linalg.py
  requirements/test_requirements.txt
  tools/wheels/cibw_test_command.sh
Labels: 05 - Testing, 39 - free-threading

#27928 REL: Prepare for the NumPy 2.2.0 release [wheel build]
  .mailmap
  doc/changelog/2.2.0-changelog.rst
  doc/release/upcoming_changes/27896.performance.rst
  doc/source/release/2.2.0-notes.rst
  pyproject.toml
  tools/ci/cirrus_wheels.yml
Labels: 14 - Release

#27930 MAINT: Fix cirrus MacOs wheel builds [wheel build]
  tools/ci/cirrus_wheels.yml
Labels: 03 - Maintenance, 09 - Backport-Candidate

#27933 BUG: fix building numpy on musl s390x
  numpy/_core/src/common/npy_cpu_features.c
Labels: 00 - Bug

#27935 MAINT: Prepare 2.2.x for further development
  doc/source/release.rst
  doc/source/release/2.2.1-notes.rst
  pavement.py
  pyproject.toml
Labels: 03 - Maintenance

#27936 MAINT: Update main after 2.2.0 release.
  .mailmap
  doc/changelog/2.2.0-changelog.rst
  doc/source/release/2.2.0-notes.rst
Labels: 03 - Maintenance

#27950 TEST: cleanups [skip cirrus][skip azp]
  numpy/f2py/tests/util.py
  numpy/ma/tests/test_core.py
Labels: 05 - Testing, 08 - Backport

#27955 BUG: fix use-after-free error in npy_hashtable.cpp
  numpy/_core/src/common/npy_hashtable.cpp
Labels: 00 - Bug, 09 - Backport-Candidate, 39 - free-threading

#27956 BLD: add missing include to fix build with freethreading
  numpy/_core/src/common/npy_hashtable.cpp
Labels: 09 - Backport-Candidate, 36 - Build

#27939 MAINT: Fix cirrus MacOs wheel builds [wheel build]
  tools/ci/cirrus_wheels.yml
Labels: 03 - Maintenance, 08 - Backport

#27958 BUG: fix use-after-free error in npy_hashtable.cpp (#27955)
  numpy/_core/src/common/npy_hashtable.cpp
Labels: 00 - Bug, 08 - Backport, 39 - free-threading

#27959 BLD: add missing include
  numpy/_core/src/common/npy_hashtable.cpp
Labels: 08 - Backport, 36 - Build

#27947 BUG:fix compile error libatomic link test to meson.build
  numpy/meson.build
Labels: 00 - Bug, 09 - Backport-Candidate

#27927 DOC: Use internal/intersphinx links for neps.
  doc/C_STYLE_GUIDE.rst
  doc/neps/index.rst
  doc/neps/nep-0016-abstract-array.rst
  doc/neps/nep-0021-advanced-indexing.rst
  doc/neps/nep-0022-ndarray-duck-typing-overview.rst
  doc/neps/nep-0023-backwards-compatibility.rst
  doc/source/reference/simd/index.rst
  numpy/lib/mixins.py
Labels: 04 - Documentation

#27288 BUG: Scalar array comparison should return np.bool
  doc/release/upcoming_changes/27288.improvement.rst
  numpy/_core/src/multiarray/arrayobject.c
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/src/umath/funcs.inc.src
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_scalarmath.py
Labels: 00 - Bug

#27648 MAINT: Fix the code style to our C-Style-Guide
  numpy/_core/src/umath/string_buffer.h
Labels: 03 - Maintenance

#27981 DOC: Document abi3 compat
  doc/source/dev/depending_on_numpy.rst
Labels: 04 - Documentation

#27982 BUG:fix compile error libatomic link test to meson.build
  numpy/meson.build
Labels: 00 - Bug, 08 - Backport

#27860 MAINT: Add helper for static or heap allocated scratch space
  numpy/_core/src/multiarray/alloc.c
  numpy/_core/src/multiarray/alloc.h
  numpy/_core/src/multiarray/convert.c
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/methods.c
  numpy/_core/src/multiarray/nditer_constr.c
  numpy/_core/src/multiarray/textreading/conversions.c
  numpy/_core/src/umath/ufunc_object.c
Labels: 01 - Enhancement

#27324 DOC: Removing module name from by-topic docs
  doc/source/reference/distutils.rst
  doc/source/reference/random/index.rst
  doc/source/reference/routines.linalg.rst
  doc/source/reference/routines.testing.rst
  numpy/exceptions.py
  numpy/fft/__init__.py
Labels: 04 - Documentation

#27967 TYP: Fix falsely rejected value types in ``ndarray.__setitem__``
  numpy/__init__.pyi
  numpy/typing/tests/data/pass/simple.py
Labels: 00 - Bug, 09 - Backport-Candidate, Static typing

#27991 MAINT: Don't wrap ``#include <Python.h>`` with ``extern "C"``
  numpy/_core/include/numpy/ndarraytypes.h
Labels: 03 - Maintenance, 08 - Backport

#27990 TYP: Fix falsely rejected value types in ``ndarray.__setitem__``
  numpy/__init__.pyi
  numpy/typing/tests/data/pass/simple.py
Labels: 00 - Bug, 08 - Backport, Static typing

#27992 BUG: Fix segfault in stringdtype lexsort
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 09 - Backport-Candidate

#27993 BUG: Fix segfault in stringdtype lexsort
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 08 - Backport

#27997 MAINT: Remove unnecessary (and not safe in free-threaded) 1-D hack
  numpy/_core/src/umath/ufunc_object.c
Labels: 03 - Maintenance

#27976 MAINT: Apply assorted ruff/flake8-pyi rules (PYI)
  numpy/__init__.pyi
  numpy/_core/_ufunc_config.pyi
  numpy/_core/arrayprint.pyi
  numpy/_core/multiarray.pyi
  numpy/_core/tests/test_multiarray.py
  numpy/_typing/_char_codes.py
  numpy/fft/_pocketfft.pyi
  numpy/lib/_function_base_impl.pyi
  numpy/lib/_npyio_impl.pyi
  numpy/random/mtrand.pyi
  numpy/tests/test_public_api.py
  numpy/typing/tests/data/fail/array_like.pyi
  numpy/typing/tests/data/fail/flatiter.pyi
  numpy/typing/tests/data/fail/nested_sequence.pyi
  numpy/typing/tests/data/fail/twodim_base.pyi
  numpy/typing/tests/data/pass/numeric.py
  numpy/typing/tests/data/reveal/fromnumeric.pyi
  numpy/typing/tests/data/reveal/nested_sequence.pyi
  numpy/typing/tests/data/reveal/numeric.pyi
  numpy/typing/tests/data/reveal/twodim_base.pyi
Labels: 03 - Maintenance

#27999 DOC, MAINT: Fix typos found by codespell
  doc/source/building/index.rst
  numpy/lib/_function_base_impl.py
Labels: 04 - Documentation

#28001 DOC: Fix documentation for np.dtype.kind to include 'T' for StringDType
  numpy/_core/_add_newdocs.py
Labels: 04 - Documentation

#27522 ENH: Cleanup npy_find_array_wrap
  numpy/_core/src/multiarray/arraywrap.c
  numpy/_core/tests/test_ufunc.py
Labels: 01 - Enhancement

#28003 MAINT: random: Tweak module code in mtrand.pyx to fix a Cython warning.
  numpy/random/mtrand.pyx
Labels: component: numpy.random, 03 - Maintenance, 09 - Backport-Candidate

#28005 BUG: Cython API was missing NPY_UINTP.
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/_core/tests/examples/cython/checks.pyx
  numpy/_core/tests/test_cython.py
Labels: 00 - Bug, 09 - Backport-Candidate

#28006 MAINT: random: Tweak module code in mtrand.pyx to fix a Cython warning.
  numpy/random/mtrand.pyx
Labels: component: numpy.random, 03 - Maintenance, 08 - Backport

#28007 BUG: Cython API was missing NPY_UINTP.
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/_core/tests/examples/cython/checks.pyx
  numpy/_core/tests/test_cython.py
Labels: 00 - Bug, 08 - Backport

#28009 TST: lib: Test average with object dtype and no weights.
  numpy/lib/tests/test_function_base.py
Labels: 05 - Testing, component: numpy.lib

#28004 DOC: fix several doctests in dtype method docstrings
  numpy/_core/_add_newdocs.py
Labels: 04 - Documentation

#28013 DOC: Fixed typos in development_advanced_debugging.rst
  doc/source/dev/development_advanced_debugging.rst
Labels: 04 - Documentation

#28008 BUG: Fix handling of matrix class in np.unique.
  numpy/lib/_arraysetops_impl.py
  numpy/lib/tests/test_arraysetops.py
Labels: 00 - Bug, component: numpy.lib

#27883 MAINT,ENH: Reorganize buffered iteration setup
  numpy/_core/src/multiarray/nditer_api.c
  numpy/_core/src/multiarray/nditer_constr.c
  numpy/_core/src/multiarray/nditer_impl.h
  numpy/_core/tests/test_nditer.py
Labels: 03 - Maintenance

#27922 MAINT: Move user pointers out of axisdata and simplify iternext
  numpy/_core/src/multiarray/nditer_api.c
  numpy/_core/src/multiarray/nditer_constr.c
  numpy/_core/src/multiarray/nditer_impl.h
  numpy/_core/src/multiarray/nditer_templ.c.src
  numpy/_core/tests/test_nditer.py
Labels: 03 - Maintenance

#28021 CI: pin scipy-doctest to 1.5.1
  .github/workflows/linux.yml
  requirements/doc_requirements.txt
Labels: 03 - Maintenance, 08 - Backport

#28022 MAINT: Add all submodules to ruff exclusion list.
  ruff.toml
Labels: 03 - Maintenance

#28015 MAINT: run ruff from the repository root
  tools/linter.py
Labels: 03 - Maintenance

#27998 API,MAINT: Make ``NpyIter_GetTransferFlags`` public and avoid old uses
  doc/release/upcoming_changes/27998.c_api.rst
  doc/source/reference/c-api/iterator.rst
  numpy/_core/code_generators/cversions.txt
  numpy/_core/code_generators/numpy_api.py
  numpy/_core/src/multiarray/common.h
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/einsum.c.src
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/src/multiarray/mapping.c
  numpy/_core/src/multiarray/nditer_api.c
  numpy/_core/src/multiarray/nditer_constr.c
  numpy/_core/src/multiarray/nditer_impl.h
  numpy/_core/src/umath/reduction.c
  numpy/_core/src/umath/ufunc_object.c
Labels: 30 - API

#28032 BUG,MAINT: Fix size bug in new alloc helper and use it in one more place
  numpy/_core/src/multiarray/alloc.h
  numpy/_core/src/multiarray/common_dtype.c
Labels: 00 - Bug

#28033 MAINT: Use userpointers to avoid NPY_MAXARGS in iternext()
  numpy/_core/src/multiarray/nditer_api.c
  numpy/_core/src/multiarray/nditer_templ.c.src
  numpy/_core/tests/test_nditer.py
Labels: 03 - Maintenance

#28039 TYP: allow `None` in operand sequence of nditer
  numpy/__init__.pyi
  numpy/typing/tests/data/pass/nditer.py
Labels: Static typing

#28044 TYP: allow ``None`` in operand sequence of nditer
  numpy/__init__.pyi
  numpy/typing/tests/data/pass/nditer.py
Labels: 03 - Maintenance, 08 - Backport, Static typing

#28050 MAINT: Prepare 2.2.x for further development
  doc/source/release.rst
  doc/source/release/2.2.2-notes.rst
  pavement.py
  pyproject.toml
Labels: 03 - Maintenance

#28053 TYP: fix ``void`` arrays not accepting ``str`` keys in ``__setitem__``
  numpy/__init__.pyi
  numpy/typing/tests/data/pass/ndarray_misc.py
Labels: 00 - Bug, 06 - Regression, 09 - Backport-Candidate, Static typing

#28055 TYP: fix ``void`` arrays not accepting ``str`` keys in ``__setitem__``
  numpy/__init__.pyi
  numpy/typing/tests/data/pass/ndarray_misc.py
Labels: 00 - Bug, 06 - Regression, 08 - Backport, Static typing

#28051 MAINT: Update main after 2.2.1 release.
  .mailmap
  doc/changelog/2.2.1-changelog.rst
  doc/source/release.rst
  doc/source/release/2.2.1-notes.rst
Labels: 03 - Maintenance

#28035 MAINT: Move `lib.format` and `ctypeslib` to submodules/private files
  numpy/ctypeslib/__init__.py
  numpy/ctypeslib/__init__.pyi
  numpy/ctypeslib/_ctypeslib.py
  numpy/ctypeslib/_ctypeslib.pyi
  numpy/lib/__init__.py
  numpy/lib/_format_impl.py
  numpy/lib/_format_impl.pyi
  numpy/lib/_npyio_impl.py
  numpy/lib/_utils_impl.pyi
  numpy/lib/format.py
  numpy/lib/format.pyi
  numpy/lib/introspect.py
  numpy/lib/mixins.py
  numpy/meson.build
  numpy/tests/test_public_api.py
  numpy/typing/tests/test_isfile.py
Labels: 03 - Maintenance

#28056 BUG: Fix f2py directives and `--lower` casing
  numpy/f2py/auxfuncs.py
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/src/regression/lower_f2py_fortran.f90
  numpy/f2py/tests/test_regression.py
Labels: 00 - Bug, component: numpy.f2py

#28060 CI: fix check that GIL remains disabled for free-threaded wheels
  tools/wheels/cibw_test_command.sh
Labels: component: CI, 39 - free-threading

#28058 MAINT: Update `spin lint` command
  .spin/cmds.py
  tools/linter.py
Labels: 03 - Maintenance

#27978 MAINT: Apply assorted ruff/flake8-simplify rules (SIM)
  doc/source/conf.py
  numpy/_core/tests/_natype.py
  numpy/_core/tests/test_regression.py
  numpy/f2py/auxfuncs.py
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/test_callback.py
  numpy/f2py/tests/test_f2py2e.py
  numpy/f2py/tests/test_return_character.py
  numpy/f2py/tests/test_return_complex.py
  numpy/f2py/tests/test_return_integer.py
  numpy/f2py/tests/test_return_logical.py
  numpy/f2py/tests/test_return_real.py
  numpy/f2py/use_rules.py
  numpy/lib/_arraypad_impl.py
  numpy/lib/_function_base_impl.py
  numpy/matrixlib/tests/test_defmatrix.py
  numpy/polynomial/_polybase.py
  numpy/tests/test_public_api.py
Labels: 03 - Maintenance

#28065 TYP: fix unnecessarily broad `integer` binop return types
  numpy/_typing/_callable.pyi
  numpy/typing/tests/data/reveal/arithmetic.pyi
Labels: 09 - Backport-Candidate, Static typing

#28066 TYP: fix unnecessarily broad `integer` binop return types (#28065)
  numpy/_typing/_callable.pyi
  numpy/typing/tests/data/reveal/arithmetic.pyi
Labels: 03 - Maintenance, 08 - Backport, Static typing

#27856 SIMD: add lsx optimization for loongarch, and add Qemu tests
  .github/workflows/linux_qemu.yml
  meson.options
  meson_cpu/loongarch64/meson.build
  meson_cpu/main_config.h.in
  meson_cpu/meson.build
  numpy/_core/include/numpy/npy_cpu.h
  numpy/_core/meson.build
  numpy/_core/src/_simd/_simd.dispatch.c.src
  numpy/_core/src/_simd/_simd_easyintrin.inc
  numpy/_core/src/common/npy_cpu_features.c
  numpy/_core/src/common/npy_cpu_features.h
  numpy/_core/src/common/simd/intdiv.h
  numpy/_core/src/common/simd/lsx/arithmetic.h
  numpy/_core/src/common/simd/lsx/conversion.h
  numpy/_core/src/common/simd/lsx/lsx.h
  numpy/_core/src/common/simd/lsx/math.h
  numpy/_core/src/common/simd/lsx/memory.h
  numpy/_core/src/common/simd/lsx/misc.h
  numpy/_core/src/common/simd/lsx/operators.h
  numpy/_core/src/common/simd/lsx/reorder.h
  numpy/_core/src/common/simd/simd.h
  numpy/_core/src/umath/loops_arithmetic.dispatch.c.src
  numpy/_core/tests/test_cpu_dispatcher.py
  numpy/_core/tests/test_cpu_features.py
  numpy/distutils/ccompiler_opt.py
  numpy/distutils/checks/cpu_lsx.c
Labels: 01 - Enhancement, component: SIMD

#28069 MAINT: update NEP 29
  doc/neps/nep-0029-deprecation_policy.rst
Labels: 03 - Maintenance

#28074 DOC: clarify np.gradient varargs requirement for axis parameter
  numpy/lib/_function_base_impl.py
Labels: 04 - Documentation

#28075 MAINT: Replace usage of fixed strides with inner strides in einsum
  numpy/_core/src/multiarray/einsum.c.src
Labels: 03 - Maintenance

#28073 TYP: use mypy_primer to surface type checking regressions
  .github/workflows/mypy_primer.yml
  .github/workflows/mypy_primer_comment.yml
Labels: component: CI, Static typing
