Repository numpy/numpy, pull requests merged in 2024-08, with the labels that each got.

#27019 TYP: improved ``numpy.array`` type hints for array-like input
  numpy/_core/multiarray.pyi
  numpy/typing/tests/data/reveal/array_constructors.pyi
Labels: Static typing

#27081 CI: Upgrade ``array-api-tests``
  .github/workflows/linux.yml
  numpy/_core/numeric.py
  numpy/_core/tests/test_numeric.py
  tools/ci/array-api-xfails.txt
Labels: 40 - array API standard

#27027 BUG: Fix simd loadable stride logic
  numpy/_core/src/common/simd/simd.h
  numpy/_core/src/umath/loops_arithm_fp.dispatch.c.src
  numpy/_core/src/umath/loops_exponent_log.dispatch.c.src
  numpy/_core/src/umath/loops_hyperbolic.dispatch.c.src
  numpy/_core/src/umath/loops_minmax.dispatch.c.src
  numpy/_core/src/umath/loops_trigonometric.dispatch.cpp
  numpy/_core/src/umath/loops_umath_fp.dispatch.c.src
  numpy/_core/src/umath/loops_unary.dispatch.c.src
  numpy/_core/src/umath/loops_unary_complex.dispatch.c.src
  numpy/_core/src/umath/loops_unary_fp.dispatch.c.src
  numpy/_core/src/umath/loops_unary_fp_le.dispatch.c.src
  numpy/_core/tests/test_ufunc.py
Labels: 00 - Bug

#27087 ENH: mark the dragon4 scratch space as thread-local
  numpy/_core/src/multiarray/dragon4.c
  numpy/_core/tests/test_arrayprint.py
  numpy/_core/tests/test_multithreading.py
  numpy/testing/_private/utils.py
Labels: 01 - Enhancement, 39 - free-threading

#27076 DEP: lib: Deprecate acceptance of float (and more) in bincount.
  numpy/_core/src/multiarray/compiled_base.c
  numpy/_core/tests/test_deprecations.py
  numpy/lib/tests/test_function_base.py
Labels: component: numpy.lib, 03 - Maintenance, 07 - Deprecation

#26848 TYP: include the ``|`` prefix for ``dtype`` char codes
  numpy/_typing/_char_codes.py
Labels: Static typing

#27094 DOC: Add release note about deprecation introduced in gh-27076.
  doc/release/upcoming_changes/27076.deprecation.rst
Labels: 04 - Documentation

#27095 DOC: Fix indentation of a few release notes.
  doc/release/upcoming_changes/26388.performance.rst
  doc/release/upcoming_changes/26452.deprecation.rst
  doc/release/upcoming_changes/27076.deprecation.rst
Labels: 04 - Documentation

#27090 DOC: update np.shares_memory() docs
  numpy/_core/multiarray.py
Labels: 04 - Documentation

#25705 DOC: Add documentation explaining our promotion rules
  doc/source/reference/arrays.promotion.rst
  doc/source/reference/arrays.rst
  doc/source/reference/figures/nep-0050-promotion-no-fonts.svg
Labels: 04 - Documentation

#27102 DOC: Fixup promotion doc
  doc/source/reference/arrays.promotion.rst
Labels: 04 - Documentation

#27098 BUG: add missing error handling in public_dtype_api.c
  numpy/_core/src/multiarray/public_dtype_api.c
Labels: 00 - Bug, 09 - Backport-Candidate

#27108 DOC: remove incorrect docstring comment
  numpy/_core/src/multiarray/dtypemeta.c
Labels: 04 - Documentation

#27096 BUG: Complex printing tests fail on Windows ARM64
  numpy/_core/include/numpy/npy_math.h
Labels: 00 - Bug

#27091 API,BUG: Fix copyto (and ufunc) handling of scalar cast safety
  doc/release/upcoming_changes/27091.change.rst
  numpy/_core/src/multiarray/abstractdtypes.c
  numpy/_core/src/multiarray/abstractdtypes.h
  numpy/_core/src/multiarray/array_assign_scalar.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_api.py
  numpy/_core/tests/test_numeric.py
  numpy/_core/tests/test_ufunc.py
Labels: 00 - Bug, 30 - API

#27008 TYP,BUG: Complete type stubs for ``numpy.dtypes``
  numpy/dtypes.pyi
Labels: Static typing

#27112 BUG: Fix repr for integer scalar subclasses
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/tests/test_scalarinherit.py
Labels: 00 - Bug

#27113 DEV: make linter.py runnable from outside the root of the repo
  tools/linter.py
Labels: 16 - Development

#27057 BUG: fix another cast setup in array_assign_subscript
  numpy/_core/src/multiarray/mapping.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 09 - Backport-Candidate, component: numpy.strings

#27110 BLD: cp313 cp313t linux_aarch64 [wheel build]
  tools/ci/cirrus_wheels.yml
Labels: 36 - Build

#27122 BUG: Use the new npyv_loadable_stride_ functions for ldexp and frexp
  numpy/_core/src/common/simd/avx512/avx512.h
  numpy/_core/src/umath/fast_loop_macros.h
  numpy/_core/src/umath/loops_exponent_log.dispatch.c.src
Labels: 00 - Bug, 08 - Backport

#27128 BUG: add missing error handling in public_dtype_api.c
  numpy/_core/src/multiarray/public_dtype_api.c
Labels: 00 - Bug, 08 - Backport

#27129 BUG: fix another cast setup in array_assign_subscript
  numpy/_core/src/multiarray/mapping.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 08 - Backport, component: numpy.strings

#27130 BUG: Fix building NumPy in FIPS mode
  numpy/_core/code_generators/genapi.py
Labels: 00 - Bug, 08 - Backport

#26081 TYP: Make array _ShapeType bound and covariant
  doc/release/upcoming_changes/26081.improvement.rst
  doc/release/upcoming_changes/README.rst
  numpy/__init__.pyi
  numpy/_core/defchararray.pyi
  numpy/_core/records.pyi
  numpy/ma/core.pyi
  numpy/ma/mrecords.pyi
  numpy/typing/tests/data/fail/shape.pyi
  numpy/typing/tests/data/pass/shape.py
  numpy/typing/tests/data/reveal/shape.pyi
Labels: Static typing

#27127 BUG: Fix missing error return in copyto
  numpy/_core/src/multiarray/multiarraymodule.c
Labels: 00 - Bug

#27117 BUG: Ensure that scalar binops prioritize __array_ufunc__
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_scalarmath.py
Labels: 00 - Bug

#27134 REL: Prepare main for 2.2.0 development
  doc/release/upcoming_changes/12150.improvement.rst
  doc/release/upcoming_changes/26081.improvement.rst
  doc/release/upcoming_changes/26103.c_api.rst
  doc/release/upcoming_changes/26268.expired.rst
  doc/release/upcoming_changes/26285.change.rst
  doc/release/upcoming_changes/26285.performance.rst
  doc/release/upcoming_changes/26292.new_feature.rst
  doc/release/upcoming_changes/26313.change.rst
  doc/release/upcoming_changes/26388.performance.rst
  doc/release/upcoming_changes/26452.deprecation.rst
  doc/release/upcoming_changes/26501.new_feature.rst
  doc/release/upcoming_changes/26579.new_function.rst
  doc/release/upcoming_changes/26580.new_feature.rst
  doc/release/upcoming_changes/26611.expired.rst
  doc/release/upcoming_changes/26611.new_feature.rst
  doc/release/upcoming_changes/26656.improvement.rst
  doc/release/upcoming_changes/26724.new_feature.rst
  doc/release/upcoming_changes/26750.improvement.rst
  doc/release/upcoming_changes/26766.change.rst
  doc/release/upcoming_changes/26842.c_api.rst
  doc/release/upcoming_changes/26846.improvement.rst
  doc/release/upcoming_changes/26908.c_api.rst
  doc/release/upcoming_changes/26981.new_feature.rst
  doc/release/upcoming_changes/27076.deprecation.rst
  doc/release/upcoming_changes/27091.change.rst
  doc/source/release.rst
  doc/source/release/2.2.0-notes.rst
  numpy/_core/code_generators/cversions.txt
  pavement.py
  pyproject.toml
Labels: 14 - Release, 16 - Development

#27101 TST, DOC: add doc and test for transpose axes with negative indices
  numpy/_core/fromnumeric.py
  numpy/_core/tests/test_numeric.py
Labels: 05 - Testing

#27144 MAINT: Scipy openblas 0.3.27.44.4
  numpy/linalg/tests/test_regression.py
  requirements/ci32_requirements.txt
  requirements/ci_requirements.txt
  tools/wheels/LICENSE_linux.txt
  tools/wheels/LICENSE_osx.txt
  tools/wheels/LICENSE_win32.txt
Labels: 03 - Maintenance, 08 - Backport

#27143 BUG: Do not accidentally store dtype metadata in ``np.save``
  numpy/lib/format.py
  numpy/lib/tests/test_format.py
  numpy/lib/tests/test_utils.py
Labels: 00 - Bug, 09 - Backport-Candidate

#27146 MAINT: Scipy openblas 0.3.27.44.4
  numpy/linalg/tests/test_regression.py
  requirements/ci32_requirements.txt
  requirements/ci_requirements.txt
  tools/wheels/LICENSE_linux.txt
  tools/wheels/LICENSE_osx.txt
  tools/wheels/LICENSE_win32.txt
Labels: 03 - Maintenance, 08 - Backport

#27149 BUG: Do not accidentally store dtype metadata in ``np.save``
  numpy/lib/format.py
  numpy/lib/tests/test_format.py
  numpy/lib/tests/test_utils.py
Labels: 00 - Bug, 08 - Backport

#27151 BUG: Do not accidentally store dtype metadata in ``np.save``
  numpy/lib/format.py
  numpy/lib/tests/test_format.py
  numpy/lib/tests/test_utils.py
Labels: 00 - Bug, 08 - Backport

#27148 BUG: Raise if histogram cannot create finite bin sizes
  numpy/lib/_histograms_impl.py
  numpy/lib/tests/test_histograms.py
Labels: 00 - Bug

#27147 BLD: use smaller scipy-openblas builds
  doc/release/upcoming_changes/27147.performance.rst
  requirements/ci32_requirements.txt
  requirements/ci_requirements.txt
Labels: 09 - Backport-Candidate, 36 - Build

#27157 TYP: add td64 overload for `mean`
  numpy/_core/fromnumeric.pyi
  numpy/typing/tests/data/fail/fromnumeric.pyi
  numpy/typing/tests/data/reveal/fromnumeric.pyi
Labels: Static typing

#27162 BLD: use smaller scipy-openblas builds
  doc/release/upcoming_changes/27147.performance.rst
  requirements/ci32_requirements.txt
  requirements/ci_requirements.txt
Labels: 08 - Backport, 36 - Build

#27145 ENH: fix thread-unsafe C API usages
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/src/multiarray/textreading/rows.c
Labels: 01 - Enhancement, 09 - Backport-Candidate, 39 - free-threading

#27166 ENH: fix thread-unsafe C API usages
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/src/multiarray/textreading/rows.c
Labels: 01 - Enhancement, 08 - Backport, 39 - free-threading

#27168 DOC: add td64 example in `np.mean`
  numpy/_core/fromnumeric.py
Labels: 04 - Documentation

#27164 MAINT: use npy_argparse for einsum
  numpy/_core/src/multiarray/multiarraymodule.c
Labels: 03 - Maintenance

#27182 REV: Revert undef I and document it
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/reference/c-api/types-and-structures.rst
  numpy/_core/include/numpy/npy_common.h
Labels: 00 - Bug, 09 - Backport-Candidate, 34 - Reversion

#27176 REL: Prepare for the NumPy 2.1.0rc1 release [wheel build]
  .mailmap
  doc/changelog/2.1.0-changelog.rst
  doc/release/upcoming_changes/12150.improvement.rst
  doc/release/upcoming_changes/26081.improvement.rst
  doc/release/upcoming_changes/26103.c_api.rst
  doc/release/upcoming_changes/26268.expired.rst
  doc/release/upcoming_changes/26285.change.rst
  doc/release/upcoming_changes/26285.performance.rst
  doc/release/upcoming_changes/26292.new_feature.rst
  doc/release/upcoming_changes/26313.change.rst
  doc/release/upcoming_changes/26388.performance.rst
  doc/release/upcoming_changes/26452.deprecation.rst
  doc/release/upcoming_changes/26501.new_feature.rst
  doc/release/upcoming_changes/26579.new_function.rst
  doc/release/upcoming_changes/26580.new_feature.rst
  doc/release/upcoming_changes/26611.expired.rst
  doc/release/upcoming_changes/26611.new_feature.rst
  doc/release/upcoming_changes/26656.improvement.rst
  doc/release/upcoming_changes/26724.new_feature.rst
  doc/release/upcoming_changes/26750.improvement.rst
  doc/release/upcoming_changes/26766.change.rst
  doc/release/upcoming_changes/26842.c_api.rst
  doc/release/upcoming_changes/26846.improvement.rst
  doc/release/upcoming_changes/26908.c_api.rst
  doc/release/upcoming_changes/26981.new_feature.rst
  doc/release/upcoming_changes/27076.deprecation.rst
  doc/release/upcoming_changes/27091.change.rst
  doc/release/upcoming_changes/27147.performance.rst
  doc/source/release/2.1.0-notes.rst
  pyproject.toml
Labels: 14 - Release

#27180 DOC: Add release notes for #26897
  doc/release/upcoming_changes/26897.improvement.rst
Labels: 04 - Documentation

#27181 DOC: Add release notes for #27008
  doc/release/upcoming_changes/27008.improvement.rst
Labels: 04 - Documentation

#27189 MAINT: improve download script
  tools/download-wheels.py
Labels: 03 - Maintenance, 09 - Backport-Candidate

#27193 REV: Revert undef I and document it
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/reference/c-api/types-and-structures.rst
  numpy/_core/include/numpy/npy_common.h
Labels: 00 - Bug, 08 - Backport, 34 - Reversion

#27195 REV: Revert undef I and document it
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/reference/c-api/types-and-structures.rst
  numpy/_core/include/numpy/npy_common.h
Labels: 00 - Bug, 08 - Backport, 34 - Reversion

#27197 MAINT: update default NPY_FEATURE_VERSION after dropping py39
  numpy/_core/include/numpy/numpyconfig.h
Labels: 03 - Maintenance, 08 - Backport

#27196 BUILD: improve download script
  tools/download-wheels.py
Labels: 03 - Maintenance, 08 - Backport

#27178 TYP,TST: Bump mypy to 1.11.1
  environment.yml
  numpy/typing/tests/data/fail/false_positives.pyi
  numpy/typing/tests/data/pass/literal.py
  requirements/test_requirements.txt
Labels: 05 - Testing, 03 - Maintenance, Static typing

#27202 BUG: Fix NPY_RAVEL_AXIS on backwards compatible NumPy 2 builds
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/tests/examples/cython/checks.pyx
  numpy/_core/tests/test_cython.py
Labels: 00 - Bug, 09 - Backport-Candidate

#27200 DOC: add free-threading release notes
  doc/source/release/2.1.0-notes.rst
Labels: 04 - Documentation

#27209 BUG: Fix NPY_RAVEL_AXIS on backwards compatible NumPy 2 builds
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/tests/examples/cython/checks.pyx
  numpy/_core/tests/test_cython.py
Labels: 00 - Bug, 08 - Backport

#27213 BUG: Fix NPY_RAVEL_AXIS on backwards compatible NumPy 2 builds
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/tests/examples/cython/checks.pyx
  numpy/_core/tests/test_cython.py
Labels: 00 - Bug, 08 - Backport

#27207 TYP: Deprecate calling ``numpy.save`` with ``fix_imports`` (PEP 702)
  numpy/lib/_npyio_impl.pyi
  numpy/typing/tests/data/fail/npyio.pyi
Labels: Static typing

#27153 TYP: Fix incompatible overrides in the ``numpy._typing._ufunc`` stubs
  numpy/_typing/_ufunc.pyi
Labels: Static typing

#27152 TYP: Simpllified ufunc imports in ``numpy._typing``
  numpy/_typing/__init__.py
  numpy/_typing/_ufunc.py
Labels: Static typing

#27100 TYP: Fixed & improved type hints for ``numpy.histogram2d``
  numpy/lib/_twodim_base_impl.pyi
  numpy/typing/tests/data/reveal/twodim_base.pyi
Labels: Static typing

#27150 TYP: Sane defaults for the platform-specific ``NBitBase`` types.
  numpy/_typing/__init__.py
  numpy/_typing/_nbit.py
  numpy/_typing/_nbit_base.py
  numpy/typing/mypy_plugin.py
Labels: Static typing

#26944 TYP: Annotate ``numpy._core._type_aliases``.
  numpy/_core/_type_aliases.pyi
  numpy/typing/tests/data/reveal/numerictypes.pyi
Labels: Static typing

#27216 TYP: Fixed & improved type hints for ``numpy.histogram2d``
  numpy/lib/_twodim_base_impl.pyi
  numpy/typing/tests/data/reveal/twodim_base.pyi
Labels: 08 - Backport, Static typing

#27217 TYP: Fix incompatible overrides in the ``numpy._typing._ufunc`` stubs
  numpy/_typing/_ufunc.pyi
Labels: 08 - Backport, Static typing

#27208 TYP: Disallow scalars and 0d-arrays in ``numpy.nonzero``
  numpy/_core/fromnumeric.pyi
  numpy/typing/tests/data/fail/fromnumeric.pyi
  numpy/typing/tests/data/reveal/fromnumeric.pyi
Labels: Static typing

#26570 CI, BLD: Use `cibuildwheel` to build WASM NumPy wheels
  .github/workflows/emscripten.yml
  pyproject.toml
Labels: component: CI

#27160 DEP: Finalize ``bool(empty_array)`` deprecation
  doc/release/upcoming_changes/27160.expired.rst
  doc/source/reference/arrays.ndarray.rst
  numpy/_core/src/multiarray/number.c
  numpy/_core/tests/test_deprecations.py
  numpy/_core/tests/test_multiarray.py
Labels: 07 - Deprecation

#27219 TYP: Replace ``ellipsis`` with ``types.EllipsisType``
  numpy/__init__.pyi
  numpy/_core/records.pyi
  numpy/lib/_arrayterator_impl.pyi
  numpy/typing/tests/data/reveal/index_tricks.pyi
Labels: Static typing

#27226 BUG: Fix ``PyArray_ZeroContiguousBuffer`` (resize) with struct dtypes
  numpy/_core/src/multiarray/refcount.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug, 09 - Backport-Candidate

#27228 DOC: Remove obsolete note from the top of the 2.0.0 release notes.
  doc/source/release/2.0.0-notes.rst
Labels: 04 - Documentation

#27229 BUG: Fix ``PyArray_ZeroContiguousBuffer`` (resize) with struct dtypes
  numpy/_core/src/multiarray/refcount.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug, 08 - Backport

#25984 BUG: Allow fitting of degree zero polynomials with Polynomial.fit
  numpy/polynomial/_polybase.py
  numpy/polynomial/tests/test_polynomial.py
Labels: 00 - Bug, 09 - Backport-Candidate

#27223 DOC: add docs on thread safety in NumPy
  doc/source/reference/c-api/array.rst
  doc/source/reference/global_state.rst
  doc/source/reference/index.rst
  doc/source/reference/thread_safety.rst
  doc/source/user/c-info.beyond-basics.rst
Labels: 04 - Documentation, 09 - Backport-Candidate, 39 - free-threading

#27233 DOC: add docs on thread safety in NumPy
  doc/source/reference/c-api/array.rst
  doc/source/reference/global_state.rst
  doc/source/reference/index.rst
  doc/source/reference/thread_safety.rst
  doc/source/user/c-info.beyond-basics.rst
Labels: 04 - Documentation, 08 - Backport, 39 - free-threading

#27234 BUG: Allow fitting of degree zero polynomials with Polynomial.fit
  numpy/polynomial/_polybase.py
  numpy/polynomial/tests/test_polynomial.py
Labels: 00 - Bug

#27236 REL: Prepare for the NumPy 2.1.0 release [wheel build]
  doc/changelog/2.1.0-changelog.rst
  doc/release/upcoming_changes/26897.improvement.rst
  doc/release/upcoming_changes/27008.improvement.rst
  doc/source/release/2.1.0-notes.rst
  pyproject.toml
Labels: 14 - Release

#27242 MAINT: Update main after 2.1.0 release.
  .mailmap
  doc/changelog/2.1.0-changelog.rst
  doc/source/release/2.1.0-notes.rst
Labels: 04 - Documentation, 03 - Maintenance

#27255 BUG: revert unintended change in the return value of set_printoptions
  numpy/_core/arrayprint.py
  numpy/_core/tests/test_arrayprint.py
Labels: 00 - Bug, 09 - Backport-Candidate

#27249 BUG: fix reference counting bug in __array_interface__ implementation
  numpy/_core/src/multiarray/ctors.c
Labels: 00 - Bug, 09 - Backport-Candidate

#27261 TST: Add regression test for missing descr in array-interface
  numpy/_core/tests/test_array_coercion.py
Labels: 05 - Testing

#27203 DOC: update PyArray_CheckAxis doc
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#27266 BUG: fix reference counting bug in __array_interface__ implementation…
  numpy/_core/src/multiarray/ctors.c
Labels: 00 - Bug, 08 - Backport

#27267 TST: Add regression test for missing descr in array-interface
  numpy/_core/tests/test_array_coercion.py
Labels: 05 - Testing, 08 - Backport

#27262 BUG: Fix #27256 and #27257
  doc/release/upcoming_changes/26766.change.rst
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/fromnumeric.py
  numpy/_core/fromnumeric.pyi
  numpy/_core/tests/test_numeric.py
  numpy/lib/_ufunclike_impl.py
Labels: 00 - Bug, 04 - Documentation, 09 - Backport-Candidate

#27272 ENH: make check-{docs,tutorials} fail on dtype mismatch
  doc/source/user/basics.rec.rst
  doc/source/user/basics.types.rst
  doc/source/user/byteswapping.rst
  numpy/_core/_add_newdocs.py
  numpy/_core/_ufunc_config.py
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/fromnumeric.py
  numpy/conftest.py
  numpy/lib/_function_base_impl.py
  numpy/ma/core.py
  numpy/polynomial/polynomial.py
  numpy/random/mtrand.pyx
Labels: 01 - Enhancement

#27276 BUG: Fix #27256 and #27257
  doc/release/upcoming_changes/26766.change.rst
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/fromnumeric.py
  numpy/_core/fromnumeric.pyi
  numpy/_core/tests/test_numeric.py
  numpy/lib/_ufunclike_impl.py
Labels: 00 - Bug, 04 - Documentation, 08 - Backport

#27277 DOC/DEV/CI: mambaforge -> miniforge
  .github/workflows/macos.yml
  doc/source/building/index.rst
Labels: 04 - Documentation

#27275 BUG: Fix array_equal for numeric and non-numeric scalar types
  numpy/_core/numeric.py
  numpy/_core/tests/test_numeric.py
Labels: 00 - Bug, 09 - Backport-Candidate

#27088 WHL: bump (musl) linux image [wheel build]
  .github/workflows/linux_musl.yml
  .github/workflows/wheels.yml
  doc/release/upcoming_changes/27088.change.rst
  pyproject.toml
Labels: 03 - Maintenance

#27116 DOC: update NEP 50 draft status to "Final"
  doc/neps/nep-0050-scalar-promotion.rst
Labels: 04 - Documentation

#27278 BUG: Fix array_equal for numeric and non-numeric scalar types
  numpy/_core/numeric.py
  numpy/_core/tests/test_numeric.py
Labels: 00 - Bug, 08 - Backport

#27279 BUG: Fix array_equal for numeric and non-numeric scalar types
  numpy/_core/numeric.py
  numpy/_core/tests/test_numeric.py
Labels: 00 - Bug, 08 - Backport

#27285 MAINT: prepare 2.0.x for further development
  doc/source/release.rst
  doc/source/release/2.0.3-notes.rst
  pavement.py
  pyproject.toml
Labels: 03 - Maintenance

#27286 MAINT: Update main after the 2.0.2 release
  doc/changelog/2.0.2-changelog.rst
  doc/source/release.rst
  doc/source/release/2.0.2-notes.rst
Labels: 03 - Maintenance, 09 - Backport-Candidate

#27287 MAINT: Update maintenance/2.1.x after the 2.0.2 release
  doc/changelog/2.0.2-changelog.rst
  doc/source/release.rst
  doc/source/release/2.0.2-notes.rst
Labels: 03 - Maintenance

#27290 MAINT: Keep applying ruff/pyupgrade rules (UP)
  numpy/_core/numerictypes.py
  numpy/lib/_array_utils_impl.pyi
Labels: 03 - Maintenance

#27291 DOC, MAINT: Fix new typos found by codespell
  doc/release/upcoming_changes/27147.performance.rst
  doc/source/reference/arrays.promotion.rst
  numpy/_core/src/multiarray/dlpack.c
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/tests/test_array_coercion.py
Labels: 04 - Documentation

#27049 BUG: f2py: better handle filtering of public/private subroutines
  numpy/f2py/auxfuncs.py
  numpy/f2py/f90mod_rules.py
  numpy/f2py/tests/src/modules/gh26920/two_mods_with_no_public_entities.f90
  numpy/f2py/tests/src/modules/gh26920/two_mods_with_one_public_routine.f90
  numpy/f2py/tests/test_modules.py
Labels: 00 - Bug, component: numpy.f2py, 09 - Backport-Candidate

#27298 MAINT: Apply ruff/flynt rules (FLY)
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/lib/_utils_impl.py
  numpy/linalg/_linalg.py
  tools/refguide_check.py
Labels: 03 - Maintenance

#27289 MAINT: Start applying ruff rules (RUF)
  benchmarks/benchmarks/__init__.py
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_core/numerictypes.py
  numpy/_core/tests/test_stringdtype.py
  numpy/core/_utils.py
  numpy/ctypeslib.py
  numpy/f2py/_backends/_distutils.py
  numpy/f2py/capi_maps.py
  numpy/f2py/crackfortran.py
  numpy/f2py/use_rules.py
  numpy/lib/_function_base_impl.py
  numpy/lib/_nanfunctions_impl.py
Labels: 03 - Maintenance

#27293 MAINT: Keep applying ruff/flake8-bugbear rules (B)
  benchmarks/benchmarks/bench_ma.py
  benchmarks/benchmarks/bench_ufunc.py
  doc/neps/tools/build_index.py
  numpy/_core/numeric.py
  numpy/_core/tests/test_deprecations.py
  numpy/_core/tests/test_simd.py
  numpy/_core/tests/test_ufunc.py
  numpy/_core/tests/test_umath_accuracy.py
  numpy/f2py/f2py2e.py
  numpy/f2py/tests/test_array_from_pyobj.py
  numpy/f2py/tests/test_callback.py
  numpy/f2py/tests/test_docs.py
  numpy/random/tests/test_extending.py
  tools/c_coverage/c_coverage_report.py
Labels: 03 - Maintenance

#27295 MAINT: Start applying rruff/flake8-pie rules (PIE)
  doc/postprocess.py
  numpy/f2py/symbolic.py
  numpy/lib/_npyio_impl.py
Labels: 03 - Maintenance

#27302 BUG: Fix bug in ``doc/neps/tools/build_index.py``
  doc/neps/tools/build_index.py
Labels: 00 - Bug, 06 - Regression

#27284 BLD: cp311- macosx_arm64 wheels [wheel build]
  tools/ci/cirrus_wheels.yml
Labels: 09 - Backport-Candidate, 36 - Build

#27304 BUG: f2py: better handle filtering of public/private subroutines
  numpy/f2py/auxfuncs.py
  numpy/f2py/f90mod_rules.py
  numpy/f2py/tests/src/modules/gh26920/two_mods_with_no_public_entities.f90
  numpy/f2py/tests/src/modules/gh26920/two_mods_with_one_public_routine.f90
  numpy/f2py/tests/test_modules.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#27303 BLD: cp311- macosx_arm64 wheels [wheel build]
  tools/ci/cirrus_wheels.yml
Labels: 08 - Backport, 36 - Build

#27296 MAINT: Start applying ruff/flake8-comprehensions rules (C4)
  benchmarks/benchmarks/bench_linalg.py
  doc/source/reference/random/performance.py
  numpy/_core/einsumfunc.py
  numpy/_core/tests/test_cython.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_nditer.py
  numpy/_core/tests/test_regression.py
  numpy/_core/tests/test_shape_base.py
  numpy/f2py/_backends/_meson.py
  numpy/f2py/tests/test_character.py
  numpy/lib/_arrayterator_impl.py
  numpy/lib/_npyio_impl.py
  numpy/lib/introspect.py
  numpy/lib/recfunctions.py
  numpy/ma/core.py
  numpy/ma/mrecords.py
  numpy/ma/tests/test_core.py
  numpy/ma/tests/test_subclassing.py
  numpy/tests/test_numpy_config.py
  numpy/typing/tests/data/pass/simple.py
  tools/changelog.py
  tools/wheels/check_license.py
Labels: 03 - Maintenance

#27297 MAINT: Apply ruff/flake8-raise rules (RSE)
  benchmarks/benchmarks/bench_ufunc.py
  numpy/__init__.py
  numpy/_core/numerictypes.py
  numpy/_core/tests/test_mem_overlap.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_regression.py
  numpy/fft/tests/test_pocketfft.py
  numpy/lib/tests/test_function_base.py
  numpy/lib/tests/test_regression.py
  numpy/polynomial/chebyshev.py
  numpy/polynomial/polynomial.py
  numpy/polynomial/polyutils.py
  numpy/testing/tests/test_utils.py
  tools/c_coverage/c_coverage_report.py
Labels: 03 - Maintenance

#27237 TYP: Fix several typing issues in ``numpy.polynomial``
  numpy/polynomial/_polybase.pyi
  numpy/polynomial/_polytypes.pyi
Labels: Static typing

#27210 TYP: Semi-transparent ``numpy.shape`` shape-type annotations.
  numpy/_core/fromnumeric.pyi
  numpy/typing/tests/data/reveal/fromnumeric.pyi
Labels: Static typing

#27179 TYP: Improved ``numpy.piecewise`` type-hints
  numpy/lib/_function_base_impl.pyi
  numpy/typing/tests/data/fail/lib_function_base.pyi
  numpy/typing/tests/data/reveal/lib_function_base.pyi
Labels: Static typing

#27177 TYP: 1-d ``numpy.arange`` return shape-type
  numpy/_core/multiarray.pyi
  numpy/typing/tests/data/reveal/array_constructors.pyi
Labels: Static typing

#27139 TYP: Fixed & improved ``numpy.dtype.__new__``
  numpy/__init__.pyi
  numpy/_typing/__init__.py
  numpy/_typing/_char_codes.py
  numpy/typing/tests/data/mypy.ini
  numpy/typing/tests/data/reveal/dtype.pyi
Labels: Static typing

#26994 TYP: Typing fixes for ``numpy.iinfo`` & ``numpy.finfo``
  numpy/__init__.pyi
Labels: Static typing

#26979 TYP: Explicit ``numpy.__all__`` in the stubs
  numpy/__init__.pyi
Labels: Static typing

#26941 TYP: Non-distributive ``numpy.generic`` type args.
  numpy/_typing/_callable.pyi
  numpy/typing/tests/data/reveal/arithmetic.pyi
  numpy/typing/tests/data/reveal/bitwise_ops.pyi
  numpy/typing/tests/data/reveal/mod.pyi
Labels: Static typing

#26865 TYP: add missing annotations for ``numpy.object_.__new__``
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/scalars.pyi
Labels: Static typing

#27156 MAINT: Remove any promotion-state switching logic
  doc/release/upcoming_changes/27156.change.rst
  doc/source/reference/c-api/array.rst
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_core/_methods.py
  numpy/_core/_ufunc_config.py
  numpy/_core/multiarray.py
  numpy/_core/numeric.py
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/convert_datatype.h
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/umath/dispatching.c
  numpy/_core/src/umath/scalarmath.c.src
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/src/umath/ufunc_type_resolution.c
  numpy/_core/tests/test_dtype.py
  numpy/_core/tests/test_einsum.py
  numpy/_core/tests/test_half.py
  numpy/_core/tests/test_nep50_promotions.py
  numpy/_core/tests/test_numeric.py
  numpy/_core/tests/test_scalarmath.py
  numpy/_core/tests/test_ufunc.py
  numpy/conftest.py
  numpy/lib/tests/test_function_base.py
  numpy/linalg/tests/test_linalg.py
  numpy/testing/_private/utils.py
Labels: 03 - Maintenance
