Repository numpy/numpy, pull requests merged in 2024-04, with the labels that each got.

#26190 BUG: fix reference counting error in wrapping_method_resolve_descriptors
  numpy/_core/src/umath/wrapping_array_method.c
Labels: 00 - Bug, 09 - Backport-Candidate

#26187 TST: Use platform.machine() for improved portability on riscv64
  numpy/_core/tests/test_numeric.py
  numpy/_core/tests/test_umath.py
Labels: 05 - Testing

#26192 BUG: Infinite Loop in numpy.base_repr
  numpy/_core/numeric.py
  numpy/_core/tests/test_numeric.py
Labels: 00 - Bug, 08 - Backport

#26193 BUG: fix reference counting error in wrapping_method_resolve_descriptors
  numpy/_core/src/umath/wrapping_array_method.c
Labels: 00 - Bug, 08 - Backport

#26097 DOC: Mention `copy=True` for `__array__` method in the migration guide.
  doc/source/numpy_2_0_migration_guide.rst
Labels: 04 - Documentation, 09 - Backport-Candidate

#26136 BUG: fixed datetime64[ns] conversion issue in numpy.vectorize, see #25936
  numpy/lib/_function_base_impl.py
  numpy/lib/tests/test_function_base.py
Labels: 00 - Bug

#26134 CI, BLD: Push NumPy's Emscripten/Pyodide wheels nightly to Anaconda.org PyPI index
  .github/workflows/emscripten.yml
Labels: component: CI

#26135 BUG: masked array division should ignore all FPEs in mask calculation
  numpy/ma/core.py
  numpy/ma/tests/test_core.py
Labels: 00 - Bug

#26205 BUG: introduce PyArray_SafeCast to fix issues around stringdtype views
  numpy/_core/_internal.py
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/convert_datatype.h
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/multiarray/stringdtype/casts.c
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 08 - Backport

#26155 NEP: add NEP 56 mailing list resolution
  doc/neps/nep-0056-array-api-main-namespace.rst
Labels: component: NEP

#26210 API: Readd `np.bool_` typing stub
  numpy/__init__.pyi
  numpy/_core/tests/_natype.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_stringdtype.py
  numpy/lib/tests/test_function_base.py
  numpy/typing/tests/data/pass/scalars.py
  numpy/typing/tests/data/reveal/numerictypes.pyi
  numpy/typing/tests/data/reveal/scalars.pyi
Labels: 09 - Backport-Candidate, 30 - API, Static typing, Numpy 2.0 API Changes

#26212 BENCH: Add benchmarks for np.power(x,2) and np.power(x,0.5)
  benchmarks/benchmarks/bench_ufunc.py
Labels: 05 - Testing, component: benchmarks

#26207 TST: account for immortal objects in test_iter_refcount
  numpy/_core/tests/test_nditer.py
Labels: 05 - Testing

#26232 MAINT: fix typo in _add_newdoc_ufunc docstring
  numpy/_core/_add_newdocs.py
Labels: 03 - Maintenance

#26239 DOC: add versionadded for copy keyword in np.asarray docstring
  numpy/_core/_add_newdocs.py
Labels: 04 - Documentation

#26241 DOC: Fixup intp/uintp documentation for ssize_t/size_t changes
  doc/source/reference/arrays.scalars.rst
  doc/source/reference/c-api/dtype.rst
Labels: 04 - Documentation, 09 - Backport-Candidate

#26229 TST: skip limited API test on nogil python build
  numpy/_core/tests/test_limited_api.py
  numpy/_core/tests/test_nditer.py
  numpy/testing/_private/utils.py
Labels: 05 - Testing

#26222 MAINT: Drop Python 3.9
  .github/workflows/linux.yml
  .github/workflows/linux_simd.yml
  .github/workflows/mypy.yml
  .github/workflows/wheels.yml
  INSTALL.rst
  azure-pipelines.yml
  building_with_meson.md
  pyproject.toml
  tools/ci/cirrus_arm.yml
  tools/ci/cirrus_wheels.yml
  tools/ci/run_32_bit_linux_docker.sh
Labels: 03 - Maintenance, component: CI, 36 - Build

#26227 MAINT: utilize ufunc API const correctness internally
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/src/umath/_operand_flag_tests.c
  numpy/_core/src/umath/_rational_tests.c
  numpy/_core/src/umath/_umath_tests.c.src
  numpy/fft/_pocketfft_umath.cpp
  numpy/linalg/umath_linalg.cpp
Labels: 03 - Maintenance

#26256 MAINT: Update array-api-tests job
  .github/workflows/linux.yml
  tools/ci/array-api-skips.txt
Labels: 03 - Maintenance, 08 - Backport

#26245 DOC: Update `__array__` `copy` keyword docs
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/user/basics.dispatch.rst
  doc/source/user/basics.interoperability.rst
  numpy/_core/_add_newdocs.py
  numpy/_core/src/multiarray/ctors.c
Labels: 04 - Documentation, 09 - Backport-Candidate

#26259 DOC: Backport various documentation fixes
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/reference/arrays.scalars.rst
  doc/source/reference/c-api/dtype.rst
  doc/source/user/basics.dispatch.rst
  doc/source/user/basics.interoperability.rst
  numpy/_core/_add_newdocs.py
  numpy/_core/src/multiarray/ctors.c
Labels: 04 - Documentation, 08 - Backport

#26251 MNT: disable the allocator cache for nogil builds
  numpy/_core/src/multiarray/alloc.c
Labels: 03 - Maintenance, 39 - no-GIL

#26258 BLD: update to OpenBLAS 0.3.27
  requirements/ci32_requirements.txt
  requirements/ci_requirements.txt
Labels: 09 - Backport-Candidate, 36 - Build

#26262 BLD: update to OpenBLAS 0.3.27.0.1
  requirements/ci32_requirements.txt
  requirements/ci_requirements.txt
Labels: 08 - Backport, 36 - Build

#26263 MAINT: fix typo
  numpy/_core/include/numpy/npy_2_compat.h
Labels: 03 - Maintenance, 09 - Backport-Candidate

#26264 MAINT: fix typo in #include example
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation, 03 - Maintenance, 09 - Backport-Candidate

#26267 MAINT: Update URL in nep 0014 - domain change
  doc/neps/nep-0014-dropping-python2.7-proposal.rst
Labels: 03 - Maintenance

#26265 MAINT: Fix some typos
  doc/source/reference/c-api/array.rst
  numpy/_core/include/numpy/npy_2_compat.h
Labels: 04 - Documentation, 03 - Maintenance, 08 - Backport

#26270 BUG: ensure np.vectorize doesn't truncate fixed-width strings
  numpy/_core/tests/test_regression.py
  numpy/lib/_function_base_impl.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26272 BUG: Fixes for ``np.vectorize``.
  numpy/_core/tests/test_regression.py
  numpy/lib/_function_base_impl.py
  numpy/lib/tests/test_function_base.py
Labels: 00 - Bug

#26283 DOC: correct PR referenced in __array_wraps__ change note
  doc/source/release/2.0.0-notes.rst
Labels: 04 - Documentation

#26219 ENH: Enable RVV CPU feature detection
  meson_cpu/main_config.h.in
  meson_cpu/meson.build
  meson_cpu/riscv64/meson.build
  numpy/_core/src/common/npy_cpu_features.c
  numpy/_core/src/common/npy_cpu_features.h
  numpy/distutils/checks/cpu_rvv.c
Labels: 01 - Enhancement, component: build, component: SIMD

#26284 TST: run the smoke tests on more python versions
  .github/workflows/linux.yml
Labels: 05 - Testing

#26281 BUG: Workaround for Intel Compiler mask conversion bug
  numpy/_core/src/common/simd/avx512/conversion.h
Labels: 00 - Bug, 09 - Backport-Candidate, component: SIMD

#26260 BUG: Ensure seed sequences are restored through pickling
  numpy/random/_generator.pyi
  numpy/random/_generator.pyx
  numpy/random/_pickle.py
  numpy/random/bit_generator.pyi
  numpy/random/bit_generator.pyx
  numpy/random/meson.build
  numpy/random/mtrand.pyi
  numpy/random/mtrand.pyx
  numpy/random/tests/data/generator_pcg64_np121.pkl.gz
  numpy/random/tests/data/generator_pcg64_np126.pkl.gz
  numpy/random/tests/data/sfc64_np126.pkl.gz
  numpy/random/tests/test_direct.py
  numpy/random/tests/test_generator_mt19937.py
  numpy/random/tests/test_randomstate.py
  numpy/typing/tests/data/pass/random.py
  numpy/typing/tests/data/reveal/random.pyi
Labels: 00 - Bug, 09 - Backport-Candidate

#26274 BLD: use install-tags to optionally install tests
  .github/workflows/linux.yml
  numpy/_core/_add_newdocs.py
  numpy/_core/meson.build
  numpy/_core/src/multiarray/_multiarray_tests.c.src
  numpy/_pyinstaller/tests/__init__.py
  numpy/_pyinstaller/tests/pyinstaller-smoke.py
  numpy/_pyinstaller/tests/test_pyinstaller.py
  numpy/fft/meson.build
  numpy/linalg/meson.build
  numpy/meson.build
  numpy/random/meson.build
  pyproject.toml
  tools/check_installed_files.py
Labels: 01 - Enhancement, component: build

#26268 API: Disallow 0D input arrays in ``nonzero``
  doc/release/upcoming_changes/26268.expired.rst
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/tests/test_deprecations.py
  numpy/_core/tests/test_numeric.py
  tools/ci/array-api-skips.txt
Labels: 30 - API

#26261 ENH: introduce a notion of "compatible" stringdtype instances
  doc/neps/nep-0055-string_dtype.rst
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/src/multiarray/stringdtype/dtype.h
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/tests/_natype.py
  numpy/_core/tests/test_stringdtype.py
Labels: 01 - Enhancement, 09 - Backport-Candidate

#26297 BUG: Workaround for Intel Compiler mask conversion bug
  numpy/_core/src/common/simd/avx512/conversion.h
  requirements/doc_requirements.txt
Labels: 00 - Bug, 08 - Backport, component: SIMD

#26125 DOC: Bump pydata-sphinx-theme version
  .circleci/config.yml
  doc/release/upcoming_changes/25908.improvement.rst
  doc/source/_static/numpy.css
  doc/source/conf.py
  doc/source/index.rst
  environment.yml
  requirements/doc_requirements.txt
Labels: 04 - Documentation

#26299 MAINT: Pin sphinx to version 7.2.6
  requirements/doc_requirements.txt
Labels: 05 - Testing, 03 - Maintenance

#26282 MNT: replace _PyDict_GetItemStringWithError with PyDict_GetItemStringRef
  numpy/_core/src/common/ufunc_override.c
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/number.c
  numpy/_core/src/umath/override.c
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/src/umath/umathmodule.c
Labels: 03 - Maintenance, 39 - no-GIL

#26293 BUG: Ensure seed sequences are restored through pickling (#26260)
  numpy/random/_generator.pyi
  numpy/random/_generator.pyx
  numpy/random/_pickle.py
  numpy/random/bit_generator.pyi
  numpy/random/bit_generator.pyx
  numpy/random/meson.build
  numpy/random/mtrand.pyi
  numpy/random/mtrand.pyx
  numpy/random/tests/data/generator_pcg64_np121.pkl.gz
  numpy/random/tests/data/generator_pcg64_np126.pkl.gz
  numpy/random/tests/data/sfc64_np126.pkl.gz
  numpy/random/tests/test_direct.py
  numpy/random/tests/test_generator_mt19937.py
  numpy/random/tests/test_randomstate.py
  numpy/typing/tests/data/pass/random.py
  numpy/typing/tests/data/reveal/random.pyi
Labels: 00 - Bug, 08 - Backport

#26301 BLD: In 1.26.x, do not upper-bound the meson-python version
  pyproject.toml
Labels: 36 - Build

#26151 BUG: Fix test_impossible_feature_enable failing without BASELINE_FEAT
  numpy/_core/src/common/npy_cpu_features.c
  numpy/_core/tests/test_cpu_features.py
Labels: 00 - Bug

#26248 MAINT,BUG: Robust string meson template substitution
  numpy/f2py/_backends/_meson.py
  numpy/f2py/_backends/meson.build.template
Labels: component: numpy.f2py, 03 - Maintenance, 09 - Backport-Candidate, triage review

#26302 BLD: use newer openblas wheels [wheel build]
  requirements/ci32_requirements.txt
  requirements/ci_requirements.txt
Labels: 36 - Build

#26307 BLD: use newer openblas wheels [wheel build]
  requirements/ci32_requirements.txt
  requirements/ci_requirements.txt
Labels: 08 - Backport, 36 - Build

#26306 MAINT: Robust string meson template substitution
  numpy/f2py/_backends/_meson.py
  numpy/f2py/_backends/meson.build.template
Labels: component: numpy.f2py, 03 - Maintenance, 08 - Backport

#26305 DOC: Bump pydata-sphinx-theme version
  .circleci/config.yml
  doc/source/_static/numpy.css
  doc/source/conf.py
  doc/source/index.rst
  environment.yml
  requirements/doc_requirements.txt
Labels: 04 - Documentation, 08 - Backport

#26311 DOC: Follow-up fixes for new theme
  doc/source/_static/numpy.css
Labels: 04 - Documentation, 09 - Backport-Candidate

#26312 DOC: Follow-up fixes for new theme
  doc/source/_static/numpy.css
Labels: 04 - Documentation, 08 - Backport

#26286 BLD: ensure libnpymath and highway static libs use hidden visibility
  numpy/_core/meson.build
Labels: 36 - Build

#26304 MAINT: address improper error handling and cleanup for `spin`
  .spin/cmds.py
  pyproject.toml
Labels: 03 - Maintenance, 09 - Backport-Candidate

#26215 API: Enforce one copy for ``__array__`` when ``copy=True``
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/src/multiarray/array_coercion.h
  numpy/_core/src/multiarray/arrayobject.c
  numpy/_core/src/multiarray/common.c
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/ctors.h
  numpy/_core/tests/test_array_coercion.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_protocols.py
Labels: 01 - Enhancement, 30 - API

#26294 MNT: disable the coercion cache for the nogil build
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/tests/test_multithreading.py
Labels: 39 - no-GIL

#26317 BUG: use PyArray_SafeCast in array_astype
  numpy/_core/src/multiarray/methods.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26319 BUG: fix spin bench not running on Windows
  .spin/cmds.py
Labels: 00 - Bug

#26303 DOC: add explanation of dtype to parameter values for np.append
  numpy/lib/_function_base_impl.py
Labels: 04 - Documentation

#26324 BUG: Fix invalid constructor in string_fastsearch.h with C++ >= 20.
  numpy/_core/src/umath/string_fastsearch.h
Labels: 00 - Bug, 09 - Backport-Candidate

#26330 BUG: Fix invalid constructor in string_fastsearch.h with C++ >= 20.
  numpy/_core/src/umath/string_fastsearch.h
Labels: 00 - Bug, 08 - Backport

#26331 MAINT: address improper error handling and cleanup for ``spin``
  .spin/cmds.py
  pyproject.toml
Labels: 03 - Maintenance, 08 - Backport

#26332 BUG: use PyArray_SafeCast in array_astype
  numpy/_core/src/multiarray/methods.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 08 - Backport

#26334 MAINT: Disable compiler sanitizer tests on 2.0.x
  .github/workflows/linux_compiler_sanitizers.yml
Labels: 03 - Maintenance, component: CI

#26325 TST: Skip Cython test for editable install
  numpy/_core/tests/test_array_interface.py
  numpy/_core/tests/test_cython.py
  numpy/_core/tests/test_limited_api.py
  numpy/_core/tests/test_mem_policy.py
  numpy/_pyinstaller/tests/__init__.py
  numpy/distutils/tests/test_misc_util.py
  numpy/f2py/tests/__init__.py
  numpy/random/tests/test_extending.py
  numpy/testing/_private/utils.py
  pytest.ini
Labels: 05 - Testing

#26320 DOC: Add replacement NEP links in superseded, replaced-by fields
  doc/neps/nep-0000.rst
  doc/neps/nep-0030-duck-array-protocol.rst
  doc/neps/nep-0031-uarray.rst
  doc/neps/nep-0037-array-module.rst
  doc/neps/nep-0047-array-api-standard.rst
  doc/neps/nep-0056-array-api-main-namespace.rst
  doc/neps/tools/build_index.py
Labels: 04 - Documentation

#26292 API: Add ``shape`` and ``copy`` arguments to ``numpy.reshape``
  doc/release/upcoming_changes/26292.new_feature.rst
  doc/source/user/absolute_beginners.rst
  numpy/__init__.pyi
  numpy/_core/_add_newdocs.py
  numpy/_core/fromnumeric.py
  numpy/_core/fromnumeric.pyi
  numpy/_core/src/multiarray/methods.c
  numpy/_core/src/multiarray/shape.c
  numpy/_core/src/multiarray/shape.h
  numpy/_core/tests/test_numeric.py
  tools/ci/array-api-skips.txt
Labels: 01 - Enhancement, 30 - API

#26340 DOC: Added small clarification note, based on discussion in issue #25778
  doc/source/reference/random/index.rst
  doc/source/reference/random/parallel.rst
Labels: 04 - Documentation

#26351 ENH: introduce a notion of "compatible" stringdtype instances #26261
  doc/neps/nep-0055-string_dtype.rst
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/src/multiarray/stringdtype/dtype.h
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/tests/_natype.py
  numpy/_core/tests/test_stringdtype.py
Labels: 01 - Enhancement, 08 - Backport

#26354 BUG: Fix rfft for even input length.
  numpy/fft/_pocketfft_umath.cpp
  numpy/fft/tests/test_pocketfft.py
Labels: 00 - Bug, component: numpy.fft, 09 - Backport-Candidate, C++

#26359 MAINT: Simplify bugfix for even rfft
  numpy/fft/_pocketfft_umath.cpp
Labels: component: numpy.fft, 03 - Maintenance, 09 - Backport-Candidate, C++

#26358 BUG: Fix rfft for even input length.
  numpy/fft/_pocketfft_umath.cpp
  numpy/fft/tests/test_pocketfft.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport, C++

#26357 DOC: Added small clarification note, based on discussion in issue #25778
  doc/source/reference/random/index.rst
  doc/source/reference/random/parallel.rst
Labels: 04 - Documentation, 08 - Backport

#26360 MAINT: Simplify bugfix for even rfft
  numpy/fft/_pocketfft_umath.cpp
Labels: component: numpy.fft, 03 - Maintenance, 08 - Backport, C++

#26353 BUG: ensure text padding ufuncs handle stringdtype nan-like nulls
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/strings.py
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug

#26103 API: Default to hidden visibility for API tables
  doc/release/upcoming_changes/26103.c_api.rst
  doc/source/reference/c-api/array.rst
  numpy/_core/code_generators/generate_numpy_api.py
  numpy/_core/code_generators/generate_ufunc_api.py
Labels: 54 - Needs decision, 30 - API, triaged

#26348 NOGIL: Make loop data cache and dispatch cache thread-safe in nogil build
  numpy/_core/src/common/npy_hashtable.c
  numpy/_core/src/common/npy_hashtable.h
  numpy/_core/src/umath/legacy_array_method.c
  numpy/_core/tests/test_multithreading.py
Labels: 39 - no-GIL

#26355 ENH: add support for nan-like null strings in string replace
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/strings.py
  numpy/_core/tests/test_stringdtype.py
Labels: 01 - Enhancement, 09 - Backport-Candidate

#26364 TST: static types are now immortal in the default build too
  numpy/_core/tests/test_nditer.py
Labels: 05 - Testing
