Repository numpy/numpy, pull requests merged in 2024-10, with the labels that each got.

#27503 BUG: avoid segfault on bad arguments in ndarray.__array_function__
  numpy/_core/src/multiarray/methods.c
  numpy/_core/tests/test_overrides.py
Labels: 00 - Bug, component: numpy._core, 09 - Backport-Candidate

#27501 MAINT: Bump pypa/cibuildwheel from 2.21.1 to 2.21.2
  .github/workflows/wheels.yml
Labels: 03 - Maintenance, 08 - Backport

#27506 BUG: avoid segfault on bad arguments in ndarray.__array_function__
  numpy/_core/src/multiarray/methods.c
  numpy/_core/tests/test_overrides.py
Labels: 00 - Bug, component: numpy._core, 08 - Backport

#27508 MAINT: Pin setuptools for testing [wheel build]
  requirements/test_requirements.txt
Labels: 03 - Maintenance

#27512 MAINT: prepare 2.1.x for further development
  doc/source/release.rst
  doc/source/release/2.1.3-notes.rst
  pavement.py
  pyproject.toml
Labels: 03 - Maintenance

#27511 TYP: Annotate type aliases without annotation
  numpy/_core/_asarray.pyi
  numpy/_core/_ufunc_config.pyi
  numpy/_core/arrayprint.pyi
  numpy/_core/einsumfunc.pyi
  numpy/_core/multiarray.pyi
  numpy/_core/numeric.pyi
  numpy/_core/records.pyi
  numpy/ctypeslib.pyi
  numpy/fft/_pocketfft.pyi
  numpy/lib/_arraypad_impl.pyi
  numpy/lib/_arrayterator_impl.pyi
  numpy/lib/_function_base_impl.pyi
  numpy/lib/_histograms_impl.pyi
  numpy/lib/_polynomial_impl.pyi
  numpy/lib/_twodim_base_impl.pyi
  numpy/polynomial/__init__.pyi
  numpy/random/_generator.pyi
  numpy/random/bit_generator.pyi
  numpy/random/mtrand.pyi
  numpy/testing/_private/utils.pyi
Labels: Static typing

#27513 MAINT: Update main after NumPy 2.1.2 release
  .mailmap
  doc/changelog/2.1.2-changelog.rst
  doc/source/release.rst
  doc/source/release/2.1.2-notes.rst
Labels: 03 - Maintenance

#27517 BENCH: Add benchmarks for np.non_zero
  benchmarks/benchmarks/bench_core.py
Labels: 28 - Benchmark

#27510 TYP: Mark stub-only classes as `@type_check_only`
  numpy/__init__.pyi
  numpy/_array_api_info.pyi
  numpy/_core/_type_aliases.pyi
  numpy/_core/_ufunc_config.pyi
  numpy/_core/arrayprint.pyi
  numpy/_core/multiarray.pyi
  numpy/_core/numerictypes.pyi
  numpy/_core/records.pyi
  numpy/_typing/_callable.pyi
  numpy/_typing/_ufunc.pyi
  numpy/f2py/__init__.pyi
  numpy/lib/_arraypad_impl.pyi
  numpy/lib/_function_base_impl.pyi
  numpy/lib/_npyio_impl.pyi
  numpy/lib/_shape_base_impl.pyi
  numpy/lib/_type_check_impl.pyi
  numpy/lib/_utils_impl.pyi
  numpy/polynomial/_polytypes.pyi
  numpy/random/_mt19937.pyi
  numpy/random/_pcg64.pyi
  numpy/random/_philox.pyi
  numpy/random/_sfc64.pyi
  numpy/random/bit_generator.pyi
Labels: Static typing

#27497 DOC: Correct selected C docstrings to eliminate warnings
  numpy/_core/include/numpy/dtype_api.h
  numpy/_core/src/common/npy_argparse.c
  numpy/_core/src/common/npy_argparse.h
  numpy/_core/src/common/npy_import.h
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/src/multiarray/array_method.c
  numpy/_core/src/multiarray/common.c
  numpy/_core/src/multiarray/common.h
  numpy/_core/src/multiarray/common_dtype.c
  numpy/_core/src/multiarray/conversion_utils.c
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/mapping.c
  numpy/_core/src/multiarray/textreading/rows.c
  numpy/_core/src/multiarray/usertypes.c
  numpy/_core/src/umath/dispatching.c
  numpy/_core/src/umath/ufunc_object.c
Labels: 04 - Documentation

#27521 TYP: Fill in the missing ``__all__`` exports
  numpy/_core/defchararray.pyi
  numpy/_core/einsumfunc.pyi
  numpy/_core/fromnumeric.pyi
  numpy/_core/function_base.pyi
  numpy/_core/getlimits.pyi
  numpy/_core/memmap.pyi
  numpy/_core/multiarray.pyi
  numpy/_core/numeric.pyi
  numpy/_core/numerictypes.pyi
  numpy/_core/records.pyi
  numpy/_core/shape_base.pyi
  numpy/_pytesttester.pyi
  numpy/char/__init__.pyi
  numpy/ctypeslib.pyi
  numpy/exceptions.pyi
  numpy/f2py/__init__.pyi
  numpy/fft/__init__.pyi
  numpy/fft/_helper.pyi
  numpy/fft/_pocketfft.pyi
  numpy/lib/__init__.pyi
  numpy/lib/_array_utils_impl.pyi
  numpy/lib/_arraypad_impl.pyi
  numpy/lib/_arraysetops_impl.pyi
  numpy/lib/_arrayterator_impl.pyi
  numpy/lib/_function_base_impl.pyi
  numpy/lib/_histograms_impl.pyi
  numpy/lib/_index_tricks_impl.pyi
  numpy/lib/_nanfunctions_impl.pyi
  numpy/lib/_npyio_impl.pyi
  numpy/lib/_polynomial_impl.pyi
  numpy/lib/_scimath_impl.pyi
  numpy/lib/_shape_base_impl.pyi
  numpy/lib/_stride_tricks_impl.pyi
  numpy/lib/_twodim_base_impl.pyi
  numpy/lib/_type_check_impl.pyi
  numpy/lib/_ufunclike_impl.pyi
  numpy/lib/_utils_impl.pyi
  numpy/lib/_version.pyi
  numpy/lib/format.pyi
  numpy/lib/mixins.pyi
  numpy/linalg/__init__.pyi
  numpy/linalg/_linalg.pyi
  numpy/ma/__init__.pyi
  numpy/ma/core.pyi
  numpy/ma/extras.pyi
  numpy/ma/mrecords.pyi
  numpy/matrixlib/__init__.pyi
  numpy/matrixlib/defmatrix.pyi
  numpy/random/__init__.pyi
  numpy/rec/__init__.pyi
  numpy/strings/__init__.pyi
  numpy/testing/__init__.pyi
  numpy/testing/_private/utils.pyi
  numpy/typing/tests/data/pass/random.py
  numpy/typing/tests/data/reveal/random.pyi
  numpy/typing/tests/data/reveal/strings.pyi
Labels: Static typing

#27518 TST: Add tests for np.nonzero with different input types
  numpy/_core/tests/test_numeric.py
Labels: 05 - Testing

#27499 DOC: fix missing arguments (copy and device) from asanyarray's signature
  numpy/_core/_add_newdocs.py
Labels: 04 - Documentation

#27520 TYP: Remove unused imports in the stubs
  numpy/__init__.pyi
  numpy/_typing/_callable.pyi
  numpy/ctypeslib.pyi
  numpy/lib/_npyio_impl.pyi
  numpy/lib/_type_check_impl.pyi
  numpy/linalg/_linalg.pyi
  numpy/random/_generator.pyi
  numpy/version.pyi
Labels: Static typing

#27538 MAINT: Bump pypa/cibuildwheel from 2.21.2 to 2.21.3
  .github/workflows/wheels.yml
Labels: 03 - Maintenance, 08 - Backport

#27539 MAINT: MSVC does not support #warning directive
  numpy/_core/include/numpy/numpyconfig.h
Labels: 03 - Maintenance, 08 - Backport

#27534 BUG: Fix user dtype can-cast with python scalar during promotion
  numpy/_core/src/multiarray/convert_datatype.c
Labels: 00 - Bug, 09 - Backport-Candidate

#27543 BUG: Fix user dtype can-cast with python scalar during promotion
  numpy/_core/src/multiarray/convert_datatype.c
Labels: 00 - Bug, 08 - Backport

#27408 DOC: more informative _excluded_ argument explanation in np.vectorize
  numpy/lib/_function_base_impl.py
Labels: 04 - Documentation

#26406 DOC: Changed vdot docs as suggested
  numpy/_core/multiarray.py
Labels: 04 - Documentation

#26642 DOC: Add examples to ``np.char``
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/strings.py
Labels: 04 - Documentation

#27469 DOC: Added `CONTRIBUTING.rst`
  CONTRIBUTING.rst
  doc/source/dev/index.rst
Labels: 04 - Documentation

#27470 TYP: Add type stubs for stringdtype in np.char and np.strings
  numpy/_core/defchararray.pyi
  numpy/_core/strings.pyi
  numpy/_typing/__init__.py
  numpy/_typing/_array_like.py
  numpy/typing/tests/data/fail/strings.pyi
  numpy/typing/tests/data/reveal/char.pyi
  numpy/typing/tests/data/reveal/strings.pyi
  numpy/typing/tests/test_typing.py
Labels: 56 - Needs Release Note., Static typing, component: numpy.strings

#27558 MAINT: distutils: remove obsolete search for `ecc` executable
  numpy/distutils/intelccompiler.py
Labels: component: numpy.distutils, 03 - Maintenance

#27561 DEV: bump ``python`` to 3.12 in environment.yml
  .github/workflows/macos.yml
  environment.yml
Labels: 16 - Development, 08 - Backport, component: CI

#27565 MAINT: Use miniforge for macos conda test.
  .github/workflows/macos.yml
Labels: 03 - Maintenance, component: CI

#27566 BUILD: satisfy gcc-13 pendantic errors
  numpy/_core/src/multiarray/alloc.c
  numpy/_core/src/umath/scalarmath.c.src
Labels: 08 - Backport, 36 - Build

#27569 BUG: handle possible error for PyTraceMallocTrack
  doc/source/reference/c-api/array.rst
  numpy/_core/src/multiarray/alloc.c
Labels: 00 - Bug, 08 - Backport

#27570 BLD: start building Windows free-threaded wheels [wheel build]
  .github/workflows/wheels.yml
Labels: 14 - Release, 08 - Backport, component: CI, 36 - Build, 39 - free-threading

#27571 BUILD: vendor tempita from Cython
  LICENSES_bundled.txt
  numpy/_build_utils/tempita.py
  numpy/_build_utils/tempita/LICENSE.txt
  numpy/_build_utils/tempita/__init__.py
  numpy/_build_utils/tempita/_looper.py
  numpy/_build_utils/tempita/_tempita.py
Labels: 08 - Backport, 36 - Build

#27557 BUG: Fix warning "differs in levels of indirection" in npy_atomic.h with MSVC
  numpy/_core/src/common/npy_atomic.h
Labels: 00 - Bug, 09 - Backport-Candidate

#27574 BUG: Fix warning "differs in levels of indirection" in npy_atomic.h with MSVC
  numpy/_core/src/common/npy_atomic.h
Labels: 00 - Bug, 08 - Backport

#27579 BUG: Adjust numpy.i for SWIG 4.3 compatibility
  tools/swig/numpy.i
Labels: 00 - Bug

#27556 DOC: Clarify use of standard deviation in mtrand.pyx
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
Labels: 04 - Documentation

#27587 BLD: treat SVML object files better to avoid compiler warnings
  numpy/_core/meson.build
Labels: 03 - Maintenance, 36 - Build

#27593 BUG: Adjust numpy.i for SWIG 4.3 compatibility
  tools/swig/numpy.i
Labels: 00 - Bug, 08 - Backport

#27598 DOC: add examples to ctypeslib
  numpy/ctypeslib.py
Labels: 04 - Documentation

#27604 DOC: Fix rendering in docstring of nan_to_num
  numpy/lib/_type_check_impl.py
Labels: 04 - Documentation

#27613 BUG: Fix Linux QEMU CI workflow
  .github/workflows/linux_qemu.yml
Labels: 00 - Bug, 09 - Backport-Candidate

#27595 DOC: Clarify obj parameter types in numpy.delete documentation
  numpy/lib/_function_base_impl.py
Labels: 04 - Documentation

#27616 BUG: Fix Linux QEMU CI workflow
  .github/workflows/linux_qemu.yml
Labels: 00 - Bug, 08 - Backport

#27617 DOC: Update the RELEASE_WALKTHROUGH.rst file.
  doc/RELEASE_WALKTHROUGH.rst
Labels: 04 - Documentation

#27612 ENH: Add comments to `string_fastsearch.h` , rename some C-methods
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_fastsearch.h
Labels: 01 - Enhancement

#27644 DOC: Remove ambiguity in docs for ndarray.byteswap()
  numpy/_core/_add_newdocs.py
Labels: 04 - Documentation

#27650 BLD: Do not set __STDC_VERSION__ to zero during build
  numpy/_core/meson.build
  numpy/_core/src/common/npy_atomic.h
Labels: 36 - Build

#27630 ENH: Extern memory management to Cython
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
Labels: 01 - Enhancement

#27652 TYP,TST: Bump ``mypy`` from ``1.11.1`` to ``1.13.0``
  environment.yml
  numpy/typing/tests/data/fail/testing.pyi
  requirements/test_requirements.txt
Labels: 05 - Testing, 03 - Maintenance, Static typing

#27653 TYP: Fix Array API method signatures
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/ndarray_misc.pyi
Labels: Static typing

#27661 BUG: np.cov transpose control
  doc/release/upcoming_changes/27661.compatibility.rst
  numpy/lib/_function_base_impl.py
  numpy/lib/tests/test_function_base.py
Labels: 00 - Bug, component: numpy.lib, 56 - Needs Release Note.

#27663 ENH: fix wasm32 runtime type error in numpy._core
  numpy/_core/src/multiarray/dtypemeta.c
Labels: 00 - Bug, 01 - Enhancement, 09 - Backport-Candidate

#27659 TYP: Transparent ``ndarray`` unary operator method signatures
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/ndarray_assignability.pyi
Labels: Static typing

#27668 BLD: Do not set __STDC_VERSION__ to zero during build
  numpy/_core/meson.build
  numpy/_core/src/common/npy_atomic.h
Labels: 08 - Backport, 36 - Build

#27669 ENH: fix wasm32 runtime type error in numpy._core
  numpy/_core/src/multiarray/dtypemeta.c
Labels: 00 - Bug, 01 - Enhancement, 08 - Backport

#27666 BUG: Fix a reference count leak in npy_find_descr_for_scalar.
  numpy/_core/src/multiarray/abstractdtypes.c
Labels: 00 - Bug

#27627 ENH: Re-enable VSX from build targets for sin/cos
  numpy/_core/meson.build
Labels: 01 - Enhancement, component: SIMD, HWY

#27636 BUG: fixes for StringDType/unicode promoters
  doc/release/upcoming_changes/27636.improvement.rst
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/strings.py
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 09 - Backport-Candidate

#27673 BUG: fixes for StringDType/unicode promoters
  doc/release/upcoming_changes/27636.improvement.rst
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/strings.py
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 08 - Backport

#27672 BUG: Fix a reference count leak in npy_find_descr_for_scalar.
  numpy/_core/src/multiarray/abstractdtypes.c
Labels: 00 - Bug, 08 - Backport

#15181 ENH: Add nd-support to trim_zeros
  numpy/lib/_function_base_impl.py
  numpy/lib/_function_base_impl.pyi
  numpy/lib/tests/test_function_base.py
Labels: 01 - Enhancement, component: numpy.lib, 25 - WIP

#27678 DOC: fix incorrect versionadded for np.std
  numpy/_core/fromnumeric.py
Labels: 04 - Documentation
