Repository numpy/numpy, pull requests merged in 2024-07, with the labels that each got.

#26724 ENH: Add Array API 2023.12 version support
  .github/workflows/linux.yml
  doc/release/upcoming_changes/26724.new_feature.rst
  doc/source/reference/routines.math.rst
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_core/_methods.py
  numpy/_core/fromnumeric.py
  numpy/_core/fromnumeric.pyi
  numpy/_core/numeric.py
  numpy/_core/numeric.pyi
  numpy/_core/src/multiarray/methods.c
  numpy/_core/tests/test_numeric.py
  numpy/_core/tests/test_regression.py
  numpy/lib/tests/test_function_base.py
  numpy/typing/tests/data/pass/fromnumeric.py
  numpy/typing/tests/data/reveal/fromnumeric.pyi
  requirements/test_requirements.txt
  tools/ci/array-api-skips.txt
Labels: 01 - Enhancement

#26716 DOC: Add clarifications np.argpartition
  numpy/_core/fromnumeric.py
  numpy/_core/tests/test_multiarray.py
Labels: 04 - Documentation

#26826 DOC: remove hack to override _add_newdocs_scalars
  doc/source/conf.py
Labels: 04 - Documentation

#26832 DOC: remove hack to override _add_newdocs_scalars (#26826)
  doc/source/conf.py
Labels: 04 - Documentation, 08 - Backport

#26823 TYP: fix missing sys import in numeric.pyi
  numpy/_core/numeric.pyi
Labels: 00 - Bug, 08 - Backport, Static typing

#26822 BUG: Ensure output order follows input in numpy.fft
  numpy/fft/_pocketfft.py
  numpy/fft/tests/test_pocketfft.py
Labels: 00 - Bug, 08 - Backport

#26799 MNT: Update dlpack docs and typing stubs
  numpy/__init__.pyi
  numpy/_core/_add_newdocs.py
Labels: 01 - Enhancement, 03 - Maintenance

#26789 BUG: avoid side-effect of 'include complex.h'
  numpy/_core/include/numpy/npy_common.h
Labels: 03 - Maintenance, 09 - Backport-Candidate

#26722 DOC: Update roadmap a bit more
  doc/neps/roadmap.rst
Labels: 04 - Documentation

#26835 BUG: avoid side-effect of 'include complex.h'
  numpy/_core/include/numpy/npy_common.h
Labels: 00 - Bug, 08 - Backport

#26836 BUG: fix max_rows and chunked string/datetime reading in ``loadtxt``
  numpy/lib/_npyio_impl.py
  numpy/lib/tests/test_loadtxt.py
Labels: 00 - Bug, component: numpy.lib, 08 - Backport

#26837 BUG: fix PyArray_ImportNumPyAPI under -Werror=strict-prototypes
  numpy/_core/include/numpy/npy_2_compat.h
Labels: 00 - Bug, 08 - Backport

#26808 DOC: Change selected hardlinks to NEPs to intersphinx mappings
  doc/source/dev/development_environment.rst
  doc/source/dev/howto-docs.rst
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/reference/array_api.rst
  doc/source/reference/c-api/strings.rst
Labels: 04 - Documentation

#26679 DOC: add ``np.linalg`` examples
  numpy/linalg/_linalg.py
Labels: 04 - Documentation

#26841 BENCH: Missing ufunc in benchmarks
  benchmarks/benchmarks/bench_ufunc.py
Labels: 28 - Benchmark

#26849 BUG: Mismatched allocation domains in `PyArray_FillWithScalar`
  numpy/_core/src/multiarray/convert.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26842 BUILD: clean out py2 stuff from npy_3kcompat.h
  doc/Py3K.rst
  doc/release/upcoming_changes/26842.c_api.rst
  doc/source/f2py/code/var.pyf
  numpy/_core/include/numpy/npy_3kcompat.h
  numpy/_core/src/multiarray/array_method.c
  numpy/_core/src/multiarray/multiarraymodule.c
Labels: 03 - Maintenance, 36 - Build

#26856 DOC: Update some documentation
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/release/2.0.0-notes.rst
  numpy/_core/code_generators/ufunc_docstrings.py
Labels: 04 - Documentation, 08 - Backport

#26868 BUG: fancy indexing copy
  numpy/_core/src/multiarray/mapping.c
  numpy/_core/tests/test_indexing.py
Labels: 00 - Bug, component: numpy._core, 08 - Backport

#26869 BUG: Mismatched allocation domains in ``PyArray_FillWithScalar``
  numpy/_core/src/multiarray/convert.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug, 08 - Backport

#26870 BUG: Handle --f77flags and --f90flags for meson [wheel build]
  .github/workflows/wheels.yml
  numpy/f2py/_backends/_meson.py
  numpy/f2py/_backends/meson.build.template
  numpy/f2py/f2py2e.py
  numpy/f2py/tests/src/regression/f77fixedform.f95
  numpy/f2py/tests/test_regression.py
  numpy/f2py/tests/util.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#26550 BUG: Make Polynomial evaluation adhere to nep 50
  benchmarks/benchmarks/bench_polynomial.py
  numpy/polynomial/chebyshev.py
  numpy/polynomial/hermite.py
  numpy/polynomial/hermite_e.py
  numpy/polynomial/laguerre.py
  numpy/polynomial/legendre.py
  numpy/polynomial/polynomial.py
  numpy/polynomial/polyutils.py
  numpy/polynomial/tests/test_polynomial.py
Labels: 03 - Maintenance

#26744 BUG: Fix new DTypes and new string promotion when signature is involved
  numpy/_core/src/multiarray/abstractdtypes.h
  numpy/_core/src/umath/dispatching.c
  numpy/_core/src/umath/dispatching.h
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26880 DOC: Fix small incorrect markup
  doc/source/reference/c-api/iterator.rst
Labels: 04 - Documentation

#26881 DOC, MAINT: fix typos found by codespell
  doc/Makefile
  doc/neps/nep-0055-string_dtype.rst
  doc/neps/nep-0056-array-api-main-namespace.rst
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/reference/array_api.rst
  doc/source/reference/c-api/array.rst
  doc/source/release/2.0.0-notes.rst
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/src/_simd/_simd_vector.inc
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/src/multiarray/common_dtype.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/multiarraymodule.h
  numpy/_core/src/umath/special_integer_comparisons.cpp
  numpy/_core/strings.py
  numpy/_core/tests/test_dtype.py
  numpy/_core/tests/test_function_base.py
  numpy/_core/tests/test_numerictypes.py
  numpy/_core/tests/test_umath.py
  numpy/distutils/misc_util.py
  numpy/lib/_polynomial_impl.py
  numpy/linalg/_linalg.py
  tools/wheels/cibw_test_command.sh
Labels: 04 - Documentation

#26882 MAINT: start applying ruff/pyupgrade rules (UP)
  benchmarks/benchmarks/bench_ufunc.py
  numpy/_core/tests/test_array_coercion.py
  numpy/_core/tests/test_indexing.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_overrides.py
  numpy/_core/tests/test_records.py
  numpy/_core/tests/test_regression.py
  numpy/_core/tests/test_shape_base.py
  numpy/_core/tests/test_stringdtype.py
  numpy/f2py/auxfuncs.py
  numpy/f2py/crackfortran.py
  numpy/f2py/symbolic.py
  numpy/f2py/tests/test_crackfortran.py
  numpy/f2py/tests/util.py
  numpy/lib/_version.py
  numpy/lib/tests/test_loadtxt.py
  numpy/lib/tests/test_nanfunctions.py
  numpy/lib/tests/test_packbits.py
  numpy/lib/tests/test_regression.py
  numpy/lib/tests/test_shape_base.py
  numpy/ma/tests/test_core.py
  numpy/ma/tests/test_mrecords.py
  numpy/polynomial/polyutils.py
  numpy/random/tests/test_smoke.py
Labels: 03 - Maintenance

#26879 MAINT: start applying ruff/flake8-simplify rules (SIM)
  numpy/_core/_dtype.py
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/numerictypes.py
  numpy/_core/tests/test_cpu_features.py
  numpy/distutils/extension.py
  numpy/distutils/misc_util.py
  numpy/f2py/tests/test_array_from_pyobj.py
  numpy/f2py/tests/util.py
  numpy/lib/_arraypad_impl.py
  numpy/lib/_datasource.py
  numpy/lib/_iotools.py
  numpy/lib/_type_check_impl.py
  numpy/ma/core.py
  numpy/matrixlib/defmatrix.py
  numpy/tests/test_public_api.py
  tools/c_coverage/c_coverage_report.py
Labels: 03 - Maintenance

#26776 BUG: remove numpy.f2py from excludedimports
  numpy/_pyinstaller/hook-numpy.py
Labels: 00 - Bug, component: numpy.f2py

#26883 BUG: Make issctype always return bool.
  numpy/_core/numerictypes.py
  numpy/_core/tests/test_numerictypes.py
Labels: 00 - Bug

#26858 TYP: Annotate type aliases as ``typing.TypeAlias``
  numpy/__init__.pyi
  numpy/_typing/_array_like.py
  numpy/_typing/_dtype_like.py
  numpy/_typing/_scalars.py
  numpy/_typing/_shape.py
  numpy/linalg/_linalg.pyi
Labels: Static typing

#26884 MAINT: Remove a redundant import from the generated __ufunc_api.h.
  numpy/_core/code_generators/generate_ufunc_api.py
Labels: component: numpy._core, 03 - Maintenance

#26888 BUG: remove numpy.f2py from excludedimports
  numpy/_pyinstaller/hook-numpy.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#26717 DOC: Mention more error paths and try to consolidate import errors
  doc/source/user/troubleshooting-importerror.rst
Labels: 04 - Documentation

#26895 DOC: Change documentation copyright strings to use a dynamic end year
  doc/neps/conf.py
  doc/source/conf.py
Labels: 04 - Documentation

#26896 DOC: Change NEP hardlinks to intersphinx mappings.
  doc/neps/content.rst
  doc/neps/nep-0018-array-function-protocol.rst
  doc/neps/nep-0030-duck-array-protocol.rst
  doc/neps/nep-0031-uarray.rst
  doc/neps/nep-0035-array-creation-dispatch-with-array-function.rst
  doc/neps/nep-0036-fair-play.rst
  doc/neps/nep-0037-array-module.rst
  doc/neps/nep-0054-simd-cpp-highway.rst
Labels: 04 - Documentation

#26891 DOC: Add a note that one should free the proto struct
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#26903 BUG: Fix off-by-one error in amount of characters in strip
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/tests/test_strings.py
Labels: 09 - Backport-Candidate

#26780 MAINT: use an atomic load/store and a mutex to initialize the argparse and runtime import caches
  numpy/_core/meson.build
  numpy/_core/src/common/npy_argparse.c
  numpy/_core/src/common/npy_argparse.h
  numpy/_core/src/common/npy_atomic.h
  numpy/_core/src/common/npy_ctypes.h
  numpy/_core/src/common/npy_import.c
  numpy/_core/src/common/npy_import.h
  numpy/_core/src/multiarray/_multiarray_tests.c.src
  numpy/_core/src/multiarray/arrayfunction_override.c
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/getset.c
  numpy/_core/src/multiarray/methods.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/multiarray/npy_static_data.c
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/src/multiarray/strfuncs.c
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/src/umath/funcs.inc.src
  numpy/_core/src/umath/override.c
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/src/umath/ufunc_type_resolution.c
  numpy/_core/src/umath/umathmodule.c
  numpy/_core/tests/test_argparse.py
  numpy/meson.build
Labels: 03 - Maintenance, 39 - no-GIL

#26913 MAINT: declare that NumPy's C extensions support running without the GIL
  numpy/_core/src/_simd/_simd.c
  numpy/_core/src/multiarray/_multiarray_tests.c.src
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/umath/_operand_flag_tests.c
  numpy/_core/src/umath/_rational_tests.c
  numpy/_core/src/umath/_struct_ufunc_tests.c
  numpy/_core/src/umath/_umath_tests.c.src
  numpy/f2py/tests/test_abstract_interface.py
  numpy/f2py/tests/test_callback.py
  numpy/fft/_pocketfft_umath.cpp
  numpy/linalg/lapack_litemodule.c
  numpy/linalg/umath_linalg.cpp
Labels: 03 - Maintenance, 39 - no-GIL

#26919 BUG,MAINT: Fix utf-8 character stripping memory access
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/tests/test_strings.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26901 BUG: `np.loadtxt` return F_CONTIGUOUS ndarray if row size is too big
  numpy/_core/src/multiarray/textreading/rows.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug

#26914 API: Partially revert unique with return_inverse
  doc/source/release/2.0.0-notes.rst
  numpy/lib/_arraysetops_impl.py
  numpy/lib/tests/test_arraysetops.py
Labels: 09 - Backport-Candidate, 30 - API

#26892 ENH: Allow use of clip with Python integers to always succeed
  numpy/_core/_methods.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_numeric.py
Labels: 01 - Enhancement

#26930 BUG: Fix out-of-bound minimum offset for in1d table method
  numpy/lib/_arraysetops_impl.py
  numpy/lib/tests/test_arraysetops.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26931 BUG: Fix running full test command in docstring
  .spin/cmds.py
Labels: 00 - Bug

#26769 BUG: Quantile closest_observation to round to nearest even order
  doc/release/upcoming_changes/26656.improvement.rst
  numpy/lib/_function_base_impl.py
  numpy/lib/tests/test_function_base.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26943 TYP,BUG: Remove non-existant ``numpy.__git_version__`` in the stubs.
  numpy/__init__.pyi
Labels: Static typing

#26946 TYP: Add missing typecodes in ``numpy._core.numerictypes.typecodes``
  numpy/_core/numerictypes.pyi
  numpy/typing/tests/data/reveal/numerictypes.pyi
Labels: Static typing

#26929 TYP: Positional-only dunder binop method parameters
  numpy/__init__.pyi
Labels: Static typing

#26937 TYP,BUG: Remove ``numpy.cast`` and ``numpy.disp`` from the typing stubs.
  numpy/__init__.pyi
  numpy/lib/_function_base_impl.pyi
Labels: Static typing

#26872 TYP: use `types.CapsuleType` on python>=3.13
  numpy/__init__.pyi
Labels: Static typing

#26950 MAINT: add freethreading_compatible directive to cython build
  .github/workflows/linux.yml
  numpy/_core/tests/examples/cython/meson.build
  numpy/_core/tests/examples/cython/setup.py
  numpy/meson.build
  numpy/random/_examples/cython/meson.build
  numpy/random/meson.build
  tools/wheels/cibw_test_command.sh
Labels: 03 - Maintenance, 39 - no-GIL

#26887 BUG: Fix new DTypes and new string promotion when signature is involved
  numpy/_core/src/multiarray/abstractdtypes.h
  numpy/_core/src/umath/dispatching.c
  numpy/_core/src/umath/dispatching.h
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 08 - Backport

#26959 BUG: Quantile closest_observation to round to nearest even order
  doc/release/upcoming_changes/26656.improvement.rst
  numpy/lib/_function_base_impl.py
  numpy/lib/tests/test_function_base.py
Labels: 00 - Bug, 08 - Backport

#26960 BUG: Fix off-by-one error in amount of characters in strip
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/tests/test_strings.py
Labels: 00 - Bug, 08 - Backport

#26961 API: Partially revert unique with return_inverse
  doc/source/release/2.0.0-notes.rst
  numpy/lib/_arraysetops_impl.py
  numpy/lib/tests/test_arraysetops.py
Labels: 08 - Backport, 30 - API

#26963 BUG: Fix out-of-bound minimum offset for in1d table method
  numpy/lib/_arraysetops_impl.py
  numpy/lib/tests/test_arraysetops.py
Labels: 00 - Bug, 08 - Backport

#26962 BUG,MAINT: Fix utf-8 character stripping memory access
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/tests/test_strings.py
Labels: 00 - Bug, 08 - Backport

#26935 BUG: fix `f2py` tests to work with v2 API
  numpy/f2py/tests/src/array_from_pyobj/wrapmodule.c
  numpy/f2py/tests/util.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26968 MAINT: add a 'tests' install tag to the `numpy._core._simd` extension module
  numpy/_core/meson.build
Labels: 03 - Maintenance

#26971 BUG: fix f2py tests to work with v2 API
  numpy/f2py/tests/src/array_from_pyobj/wrapmodule.c
  numpy/f2py/tests/util.py
Labels: 00 - Bug, 08 - Backport

#26954 TYP: Replace ``typing.Optional[T]`` with ``T | None`` in the ``numpy.typing`` tests
  numpy/typing/tests/data/pass/arithmetic.py
  numpy/typing/tests/data/pass/ufunclike.py
Labels: Static typing

#26927 TYP: Transparent `__array__` shape-type
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/flatiter.pyi
Labels: Static typing

#26975 TYP: Use ``Final`` and ``LiteralString`` for the constants in ``numpy.version``
  numpy/version.pyi
Labels: Static typing

#26964 DOC: Issue template for static typing
  .github/ISSUE_TEMPLATE/typing.yml
Labels: 04 - Documentation

#26928 TYP: Covariant `numpy.flatiter` type parameter
  numpy/__init__.pyi
Labels: Static typing

#26867 TYP,BUG: fix ``numpy.__dir__`` annotations
  numpy/__init__.pyi
Labels: Static typing

#26873 TYP: improved `numpy._array_api_info` typing
  numpy/_array_api_info.pyi
  numpy/typing/tests/data/reveal/array_api_info.pyi
Labels: Static typing

#26429 TYP: npyio: loadtxt: usecols: add None type
  numpy/lib/_npyio_impl.pyi
Labels: 03 - Maintenance, Static typing

#26938 TYP,BUG: Fix ``dtype`` type alias specialization issue in ``__init__.pyi``
  numpy/__init__.pyi
Labels: Static typing

#26831 DOC: AI generated examples for ma.correlate.
  numpy/ma/core.py
Labels: 04 - Documentation

#26827 DOC: AI-Gen examples ctypeslib.as_ctypes_types
  numpy/ctypeslib.py
Labels: 04 - Documentation

#26972 BUG: Off by one in memory overlap check
  numpy/_core/src/umath/fast_loop_macros.h
  numpy/_core/src/umath/loops_utils.h.src
  numpy/_core/tests/test_regression.py
Labels: 00 - Bug

#26989 DOC: fix ctypes example
  numpy/ctypeslib.py
Labels: 04 - Documentation

#26985 BUG: Add object cast to avoid warning with limited API
  numpy/_core/include/numpy/dtype_api.h
  numpy/_core/tests/examples/limited_api/limited_api_latest.c
  numpy/_core/tests/examples/limited_api/meson.build
  numpy/_core/tests/test_limited_api.py
Labels: 00 - Bug

#26995 BUG: Add object cast to avoid warning with limited API
  numpy/_core/include/numpy/dtype_api.h
  numpy/_core/tests/examples/limited_api/limited_api_latest.c
  numpy/_core/tests/examples/limited_api/meson.build
  numpy/_core/tests/test_limited_api.py
Labels: 00 - Bug, 08 - Backport

#26991 MAINT: mark scipy-openblas nightly tests as allowed to fail
  .github/workflows/linux_blas.yml
Labels: 03 - Maintenance

#26980 add sphinx-copybutton
  doc/source/conf.py
  environment.yml
  requirements/doc_requirements.txt
Labels: 04 - Documentation

#27001 MAINT: prepare 2.0.x for further development
  doc/source/release.rst
  doc/source/release/2.0.2-notes.rst
  pavement.py
  pyproject.toml
Labels: 03 - Maintenance

#27002 MAINT: Update main after 2.0.1 release.
  .mailmap
  doc/changelog/2.0.1-changelog.rst
  doc/source/release.rst
  doc/source/release/2.0.1-notes.rst
Labels: 04 - Documentation, 03 - Maintenance

#26996 ENH: Add ``__slots__`` to private (sub-)classes in ``numpy.lib._index_tricks_impl``
  numpy/lib/_index_tricks_impl.py
  numpy/ma/extras.py
Labels: 01 - Enhancement

#26829 DOC: AI-Gen examples for ma.put
  numpy/ma/core.py
Labels: 04 - Documentation

#26828 DOC: AI generated examples for ma.left_shift.
  numpy/ma/core.py
Labels: 04 - Documentation

#26830 DOC: AI generated examples for ma.reshape
  numpy/ma/core.py
Labels: 04 - Documentation

#27009 TST, MAINT: Loosen required test precision
  numpy/fft/tests/test_pocketfft.py
Labels: 05 - Testing, 03 - Maintenance

#26969 BUG: Fix unicode strip
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/tests/test_strings.py
Labels: 00 - Bug

#26908 ENH: Provide a hook for gufuncs to process core dimensions.
  doc/source/reference/c-api/generalized-ufuncs.rst
  numpy/_core/code_generators/cversions.txt
  numpy/_core/include/numpy/numpyconfig.h
  numpy/_core/include/numpy/ufuncobject.h
  numpy/_core/meson.build
  numpy/_core/src/umath/_umath_tests.c.src
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_ufunc.py
Labels: 01 - Enhancement, component: numpy._core, component: numpy.ufunc, 63 - C API

#27010 DOC: update tutorials link
  doc/source/user/index.rst
Labels: 04 - Documentation

#26846 MAINT: back printoptions with a true context variable
  doc/release/upcoming_changes/26846.improvement.rst
  numpy/_core/arrayprint.py
  numpy/_core/meson.build
  numpy/_core/multiarray.py
  numpy/_core/printoptions.py
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/multiarray/multiarraymodule.h
  numpy/_core/src/multiarray/npy_static_data.c
  numpy/_core/src/multiarray/npy_static_data.h
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/tests/test_arrayprint.py
  numpy/_core/tests/test_multithreading.py
Labels: 03 - Maintenance, 56 - Needs Release Note., 39 - free-threading

#26766 ENH: Support integer dtype inputs in rounding functions
  doc/release/upcoming_changes/26766.change.rst
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/src/umath/loops.h.src
  numpy/_core/src/umath/loops_autovec.dispatch.c.src
  numpy/_core/tests/test_umath.py
  tools/ci/array-api-skips.txt
Labels: 01 - Enhancement

#27015 DOC: Fix migration note for `alltrue` and `sometrue`
  doc/source/numpy_2_0_migration_guide.rst
  numpy/_expired_attrs_2_0.py
Labels: 04 - Documentation

#26984 TYP,BUG: Fix potentially unresolved typevar in ``median`` and ``percentile``
  numpy/lib/_function_base_impl.pyi
Labels: Static typing

#26992 TYP: Covariant ``numpy.ndenumerate`` type parameter
  numpy/__init__.pyi
Labels: Static typing

#26942 TYP: Improved ``numpy.generic`` rich comparison operator type annotations.
  numpy/__init__.pyi
  numpy/_typing/_callable.pyi
  numpy/typing/tests/data/reveal/comparisons.pyi
Labels: Static typing

#27017 DOC: Release note for feature added in gh-26908.
  doc/release/upcoming_changes/26908.c_api.rst
Labels: 04 - Documentation

#26897 TYP: type hint ``numpy.polynomial``
  numpy/polynomial/__init__.pyi
  numpy/polynomial/_polybase.pyi
  numpy/polynomial/_polytypes.pyi
  numpy/polynomial/chebyshev.pyi
  numpy/polynomial/hermite.pyi
  numpy/polynomial/hermite_e.pyi
  numpy/polynomial/laguerre.pyi
  numpy/polynomial/legendre.pyi
  numpy/polynomial/polynomial.pyi
  numpy/polynomial/polyutils.pyi
  numpy/typing/tests/data/reveal/polynomial_polybase.pyi
  numpy/typing/tests/data/reveal/polynomial_polyutils.pyi
  numpy/typing/tests/data/reveal/polynomial_series.pyi
Labels: 01 - Enhancement, Static typing

#26871 TYP: adopt ``typing.LiteralString`` and use more of ``typing.Literal``
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/getlimits.pyi
Labels: Static typing

#26993 TYP,BUG: FIx ``numpy.ndenumerate`` annotations for ``object_`` sctype
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/index_tricks.pyi
Labels: Static typing

#26983 TYP,BUG: Type annotations for ``numpy.trapezoid``
  numpy/__init__.pyi
  numpy/lib/_function_base_impl.pyi
  numpy/typing/tests/data/reveal/lib_function_base.pyi
Labels: Static typing

#26875 TYP,BUG: Replace ``numpy._typing._UnknownType`` with ``typing.Never``
  numpy/_typing/_array_like.py
Labels: Static typing

#26847 TYP: fix ``ufunc`` method type annotations
  numpy/__init__.pyi
  numpy/_typing/_ufunc.pyi
  numpy/typing/tests/data/fail/ufuncs.pyi
  numpy/typing/tests/data/reveal/ufuncs.pyi
Labels: 00 - Bug, Static typing

#27021 BUG: cfuncs.py: fix crash when sys.stderr is not available
  numpy/f2py/auxfuncs.py
  numpy/f2py/cfuncs.py
  numpy/f2py/f2py2e.py
Labels: 00 - Bug, 08 - Backport

#27022 DOC: Fix migration note for ``alltrue`` and ``sometrue``
  doc/source/numpy_2_0_migration_guide.rst
  numpy/_expired_attrs_2_0.py
Labels: 04 - Documentation, 08 - Backport

#26981 ENH: add support in f2py to declare gil-disabled support
  .github/workflows/linux.yml
  doc/release/upcoming_changes/26981.new_feature.rst
  doc/source/f2py/usage.rst
  numpy/conftest.py
  numpy/f2py/capi_maps.py
  numpy/f2py/f2py2e.py
  numpy/f2py/rules.py
  numpy/f2py/tests/src/array_from_pyobj/wrapmodule.c
  numpy/f2py/tests/test_abstract_interface.py
  numpy/f2py/tests/test_callback.py
  numpy/f2py/tests/test_f2py2e.py
  numpy/f2py/tests/util.py
  tools/wheels/cibw_test_command.sh
Labels: component: numpy.f2py, 39 - free-threading

#27011 MAINT: replace PyThread_type_lock with PyMutex on Python >= 3.13.0b3
  numpy/_core/src/common/npy_argparse.c
  numpy/_core/src/common/npy_hashtable.c
  numpy/_core/src/common/npy_hashtable.h
  numpy/_core/src/common/npy_import.c
  numpy/_core/src/common/npy_import.h
  numpy/_core/src/multiarray/stringdtype/static_string.c
  numpy/linalg/umath_linalg.cpp
Labels: 03 - Maintenance, component: numpy.strings, 39 - free-threading

#27025 DOC: Replace np.matrix in .view() docstring example.
  numpy/_core/_add_newdocs.py
Labels: 04 - Documentation

#27014 BUG: fix gcd inf
  numpy/_core/_internal.py
  numpy/_core/tests/test_umath.py
Labels: 00 - Bug

#27026 DOC: fix tiny typo
  benchmarks/README.rst
Labels: 04 - Documentation

#26904 BUG,ENH: Fix generic scalar infinite recursion issues
  numpy/_core/src/multiarray/npy_static_data.c
  numpy/_core/src/multiarray/npy_static_data.h
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/src/umath/scalarmath.c.src
  numpy/_core/tests/test_scalarmath.py
Labels: 00 - Bug, triage review

#27031 DOC: document 'floatmode' and 'legacy' keys from np.get_printoptions' return dict
  numpy/_core/arrayprint.py
Labels: 04 - Documentation

#26934 MAINT: add PyArray_ZeroContiguousBuffer helper and use it in PyArray_Resize
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/refcount.c
  numpy/_core/src/multiarray/refcount.h
  numpy/_core/src/multiarray/shape.c
  numpy/_core/tests/test_stringdtype.py
Labels: 03 - Maintenance

#26905 API: Do not consider subclasses for NEP 50 weak promotion
  numpy/_core/src/multiarray/abstractdtypes.h
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/src/umath/scalarmath.c.src
  numpy/_core/tests/test_scalarmath.py
Labels: 30 - API

#27046 BUG: random: prevent zipf from hanging when parameter is large.
  numpy/random/src/distributions/distributions.c
  numpy/random/tests/test_generator_mt19937_regressions.py
Labels: 00 - Bug, component: numpy.random

#27047 BUG: use proper input and output descriptor in array_assign_subscript cast setup
  numpy/_core/src/multiarray/mapping.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug

#27043 CI: unify free-threaded wheel builds with other builds
  .github/workflows/free-threaded-wheels.yml
  .github/workflows/wheels.yml
  numpy/f2py/tests/test_f2py2e.py
Labels: component: CI, 39 - free-threading

#27048 BUG: random: Fix long delays/hangs with zipf(a) when a near 1.
  numpy/random/src/distributions/distributions.c
  numpy/random/src/legacy/legacy-distributions.c
  numpy/random/tests/test_generator_mt19937_regressions.py
Labels: 00 - Bug, component: numpy.random

#27052 TST: fix issues with tests that use numpy.testing.extbuild
  numpy/_core/tests/test_array_interface.py
  numpy/_core/tests/test_mem_policy.py
  numpy/testing/_private/extbuild.py
Labels: 05 - Testing, 39 - free-threading

#27050 BUG: Mirror VQSORT_ENABLED logic in Quicksort
  numpy/_core/meson.build
  numpy/_core/src/npysort/highway_qsort.dispatch.cpp
  numpy/_core/src/npysort/highway_qsort.hpp
  numpy/_core/src/npysort/highway_qsort_16bit.dispatch.cpp
  numpy/_core/src/npysort/quicksort.cpp
Labels: 00 - Bug, 09 - Backport-Candidate

#27051 TST: Refactor to consistently use CompilerChecker
  doc/source/f2py/f2py-testing.rst
  numpy/f2py/tests/test_f2py2e.py
  numpy/f2py/tests/util.py
Labels: 05 - Testing, component: numpy.f2py, 09 - Backport-Candidate

#27034 BUG: random: Fix edge case of Johnk's algorithm for the beta distribution.
  numpy/random/src/distributions/distributions.c
  numpy/random/tests/test_generator_mt19937_regressions.py
Labels: 00 - Bug, component: numpy.random

#27061 BUG: use proper input and output descriptor in array_assign_subscript cast setup
  numpy/_core/src/multiarray/mapping.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 08 - Backport

#27060 MAINT: linalg: Simplify some linalg gufuncs.
  numpy/linalg/_linalg.py
  numpy/linalg/umath_linalg.cpp
Labels: component: numpy.linalg, 03 - Maintenance

#27059 ENH: Disable name suggestions on some AttributeErrors
  numpy/__init__.py
  numpy/lib/__init__.py
Labels: 01 - Enhancement

#27073 BUG: Mirror VQSORT_ENABLED logic in Quicksort
  numpy/_core/meson.build
  numpy/_core/src/npysort/highway_qsort.dispatch.cpp
  numpy/_core/src/npysort/highway_qsort.hpp
  numpy/_core/src/npysort/highway_qsort_16bit.dispatch.cpp
  numpy/_core/src/npysort/quicksort.cpp
Labels: 00 - Bug, 08 - Backport

#27077 BUG: Off by one in memory overlap check
  numpy/_core/src/umath/fast_loop_macros.h
  numpy/_core/src/umath/loops_utils.h.src
  numpy/_core/tests/test_regression.py
Labels: 00 - Bug, 08 - Backport

#27079 MAINT: 3.9/10 cleanups
  numpy/_core/src/common/npy_pycompat.h
  numpy/_core/src/multiarray/methods.c
  numpy/_core/tests/test_nditer.py
  numpy/_core/tests/test_umath.py
  numpy/testing/tests/test_utils.py
Labels: 03 - Maintenance

#27058 DOC: Add some missing examples for `np.strings` methods
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/strings.py
Labels: 04 - Documentation

#27085 ENH: fixes for warnings on free-threaded wheel builds
  numpy/_core/tests/test_nep50_promotions.py
  numpy/linalg/tests/test_linalg.py
  numpy/random/_examples/cython/meson.build
Labels: 01 - Enhancement, 39 - free-threading
