Repository numpy/numpy, pull requests merged in 2024-03, with the labels that each got.

#25890 MAINT: refactor StringDType static_string implementation a bit.
  numpy/_core/src/multiarray/stringdtype/static_string.c
  numpy/_core/tests/test_stringdtype.py
Labels: component: numpy._core, 03 - Maintenance

#25911 MAINT: remove `numpy.array_api` module
  doc/neps/nep-0047-array-api-standard.rst
  doc/neps/nep-0056-array-api-main-namespace.rst
  doc/source/reference/array_api.rst
  doc/source/release/2.0.0-notes.rst
  numpy/array_api/__init__.py
  numpy/array_api/_array_object.py
  numpy/array_api/_constants.py
  numpy/array_api/_creation_functions.py
  numpy/array_api/_data_type_functions.py
  numpy/array_api/_dtypes.py
  numpy/array_api/_elementwise_functions.py
  numpy/array_api/_indexing_functions.py
  numpy/array_api/_manipulation_functions.py
  numpy/array_api/_searching_functions.py
  numpy/array_api/_set_functions.py
  numpy/array_api/_sorting_functions.py
  numpy/array_api/_statistical_functions.py
  numpy/array_api/_typing.py
  numpy/array_api/_utility_functions.py
  numpy/array_api/fft.py
  numpy/array_api/linalg.py
  numpy/array_api/tests/__init__.py
  numpy/array_api/tests/test_array_object.py
  numpy/array_api/tests/test_creation_functions.py
  numpy/array_api/tests/test_data_type_functions.py
  numpy/array_api/tests/test_elementwise_functions.py
  numpy/array_api/tests/test_indexing_functions.py
  numpy/array_api/tests/test_manipulation_functions.py
  numpy/array_api/tests/test_set_functions.py
  numpy/array_api/tests/test_sorting_functions.py
  numpy/array_api/tests/test_validation.py
  numpy/meson.build
  numpy/tests/test_public_api.py
  pyproject.toml
Labels: 03 - Maintenance, component: numpy.array_api

#25897 API: Make descr->f only accessible through ``PyDataType_GetArrFuncs``
  doc/release/upcoming_changes/25812.c_api.rst
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/reference/c-api/types-and-structures.rst
  numpy/_core/code_generators/cversions.txt
  numpy/_core/code_generators/numpy_api.py
  numpy/_core/include/numpy/ndarrayobject.h
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/src/common/cblasfuncs.c
  numpy/_core/src/multiarray/_multiarray_tests.c.src
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/calculation.c
  numpy/_core/src/multiarray/compiled_base.c
  numpy/_core/src/multiarray/convert.c
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/datetime.c
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/src/multiarray/dtype_transfer.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/dtypemeta.h
  numpy/_core/src/multiarray/getset.c
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/src/multiarray/iterators.c
  numpy/_core/src/multiarray/legacy_dtype_implementation.c
  numpy/_core/src/multiarray/methods.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/multiarray/number.c
  numpy/_core/src/multiarray/scalarapi.c
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/src/multiarray/usertypes.c
  numpy/_core/src/npysort/binsearch.cpp
  numpy/_core/src/npysort/heapsort.cpp
  numpy/_core/src/npysort/mergesort.cpp
  numpy/_core/src/npysort/npysort_common.h
  numpy/_core/src/npysort/quicksort.cpp
  numpy/_core/src/npysort/timsort.cpp
  numpy/_core/src/umath/_scaled_float_dtype.c
Labels: 30 - API

#25915 DOC: Fix some document build errors about rst markups
  doc/release/upcoming_changes/25168.change.rst
  doc/release/upcoming_changes/25866.c_api.rst
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/types-and-structures.rst
  doc/source/reference/c-api/ufunc.rst
Labels: 04 - Documentation

#25692 DOC: Clarify deprecated width Parameter in numpy.binary_repr #25634 [skip azp]
  numpy/_core/numeric.py
Labels: 04 - Documentation

#25603 DOC: Update tensordot documentation
  numpy/_core/numeric.py
Labels: 04 - Documentation

#25924 BUG: remove vestiges of array_api [wheel build]
  numpy/__init__.py
  numpy/_pytesttester.py
Labels: 00 - Bug

#25921 DOC: update and copy-edit 2.0.0 release notes
  doc/release/upcoming_changes/25168.change.rst
  doc/release/upcoming_changes/25754.c_api.rst
  doc/release/upcoming_changes/25812.c_api.rst
  doc/release/upcoming_changes/25816.c_api.rst
  doc/release/upcoming_changes/25816.change.rst
  doc/release/upcoming_changes/25866.c_api.rst
  doc/source/reference/c-api/array.rst
  doc/source/release.rst
  doc/source/release/2.0.0-notes.rst
Labels: 04 - Documentation

#25928 DOC: Add note about np.char & np.strings in 2.0 migration guide
  doc/source/numpy_2_0_migration_guide.rst
Labels: 04 - Documentation

#25929 DOC: Add mention of complex number changes to migration guide
  doc/source/numpy_2_0_migration_guide.rst
Labels: 04 - Documentation

#25920 NEP: update status fields of many NEPs
  doc/neps/meta.rst.tmpl
  doc/neps/nep-0021-advanced-indexing.rst
  doc/neps/nep-0023-backwards-compatibility.rst
  doc/neps/nep-0030-duck-array-protocol.rst
  doc/neps/nep-0031-uarray.rst
  doc/neps/nep-0036-fair-play.rst
  doc/neps/nep-0037-array-module.rst
  doc/neps/nep-0038-SIMD-optimizations.rst
  doc/neps/nep-0045-c_style_guide.rst
  doc/neps/nep-0046-sponsorship-guidelines.rst
  doc/neps/nep-0047-array-api-standard.rst
  doc/neps/nep-0048-spending-project-funds.rst
  doc/neps/nep-0056-array-api-main-namespace.rst
  doc/neps/tools/build_index.py
Labels: component: NEP

#25931 BUG: fix reference leak in PyArray_FromArrayAttr_int
  numpy/_core/src/multiarray/ctors.c
Labels: 00 - Bug

#25932 TST: skip rather than xfail a few tests to address CI log pollution
  numpy/_core/tests/test_numeric.py
  numpy/f2py/tests/test_f2py2e.py
Labels: 05 - Testing

#25802 MAINT,API: Make metadata, c_metadata, fields, and names only exist on old-style dtypes
  doc/source/reference/c-api/array.rst
  doc/source/release/2.0.0-notes.rst
  numpy/_core/include/numpy/arrayscalars.h
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/include/numpy/npy_1_7_deprecated_api.h
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/src/multiarray/_multiarray_tests.c.src
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/src/multiarray/arrayobject.c
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/buffer.c
  numpy/_core/src/multiarray/common.c
  numpy/_core/src/multiarray/common.h
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/datetime.c
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/src/multiarray/descriptor.h
  numpy/_core/src/multiarray/dtype_transfer.c
  numpy/_core/src/multiarray/dtype_traversal.c
  numpy/_core/src/multiarray/dtype_traversal.h
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/dtypemeta.h
  numpy/_core/src/multiarray/hashdescr.c
  numpy/_core/src/multiarray/legacy_dtype_implementation.c
  numpy/_core/src/multiarray/mapping.c
  numpy/_core/src/multiarray/methods.c
  numpy/_core/src/multiarray/refcount.c
  numpy/_core/src/multiarray/scalarapi.c
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/src/multiarray/shape.c
  numpy/_core/src/multiarray/stringdtype/casts.c
  numpy/_core/src/multiarray/textreading/field_types.c
  numpy/_core/src/multiarray/usertypes.c
  numpy/_core/src/multiarray/usertypes.h
  numpy/_core/src/umath/ufunc_type_resolution.c
Labels: 03 - Maintenance

#25933 MAINT: ensure towncrier can be run >1x, and is included in `spin docs`
  .gitignore
  .spin/cmds.py
  doc/RELEASE_WALKTHROUGH.rst
  doc/release/upcoming_changes/README.rst
  doc/release/upcoming_changes/template.rst
  doc/source/release/2.0.0-notes.rst
  doc/source/release/template.rst
  pyproject.toml
Labels: component: documentation, 03 - Maintenance

#25939 DOC: Add entries of ``npy_datetime`` and ``npy_timedelta``
  doc/source/reference/c-api/datetimes.rst
  doc/source/reference/c-api/dtype.rst
Labels: 04 - Documentation

#25947 DOC: Fix incorrect rst markups of c function directives
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#25950 BUG: Fix reference leak in niche user old user dtypes
  numpy/_core/src/multiarray/usertypes.c
  numpy/_core/tests/test_dtype.py
Labels: 00 - Bug, 09 - Backport-Candidate

#25946 DOC: Add and fixup/move docs for descriptor changes
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/types-and-structures.rst
  doc/source/release/2.0.0-notes.rst
Labels: 04 - Documentation

#25914 API: Remove broadcasting ambiguity from np.linalg.solve
  numpy/linalg/_linalg.py
  numpy/linalg/tests/test_linalg.py
Labels: 30 - API

#25945 BLD: try to build most macOS wheels on GHA
  .github/workflows/macos.yml
  .github/workflows/wheels.yml
  pyproject.toml
  tools/ci/cirrus_wheels.yml
Labels: component: CI, 36 - Build

#25952 BLD: use hash for mamba action
  .github/workflows/wheels.yml
Labels: 36 - Build

#21760 MAINT: Make output of Polynomial representations consistent
  doc/release/upcoming_changes/21760.compatibility.rst
  numpy/polynomial/_polybase.py
  numpy/polynomial/tests/test_printing.py
Labels: 03 - Maintenance, 56 - Needs Release Note., triaged

#25943 API: Restructure the dtype struct to be new dtype friendly
  doc/source/reference/c-api/types-and-structures.rst
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/_core/include/numpy/ndarrayobject.h
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/src/common/mem_overlap.c
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/buffer.c
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/src/multiarray/dtype_traversal.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/hashdescr.c
  numpy/_core/src/multiarray/usertypes.c
  numpy/f2py/src/fortranobject.c
Labels: 30 - API

#25944 BUG: avoid incorrect stringdtype allocator sharing from array copies
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/src/multiarray/stringdtype/casts.c
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/src/multiarray/stringdtype/dtype.h
  numpy/_core/src/multiarray/stringdtype/static_string.c
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug

#25948 MAINT: Introduce NPY_FEATURE_VERSION_STRING and report it in error
  numpy/_core/code_generators/generate_numpy_api.py
  numpy/_core/include/numpy/numpyconfig.h
Labels: 03 - Maintenance

#25954 API: Expose `PyArray_Pack`
  doc/source/reference/c-api/array.rst
  doc/source/release/2.0.0-notes.rst
  numpy/_core/code_generators/cversions.txt
  numpy/_core/code_generators/numpy_api.py
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/src/multiarray/array_coercion.h
Labels: 30 - API

#25955 API: revert position-only 'start' in 'np.arange'
  doc/source/release/2.0.0-notes.rst
  numpy/_core/_add_newdocs.py
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/tests/test_multiarray.py
Labels: 30 - API

#25962 DOC: fix typos and rearrange CI
  .circleci/config.yml
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#25937 DOC: 2.0 release highlights and compat notes changes
  doc/release/upcoming_changes/21760.compatibility.rst
  doc/source/dev/depending_on_numpy.rst
  doc/source/numpy_2_0_migration_guide.rst
  doc/source/reference/module_structure.rst
  doc/source/reference/routines.linalg.rst
  doc/source/release/2.0.0-notes.rst
  doc/source/user/basics.types.rst
Labels: 04 - Documentation

#25971 DOC: Fix a note section markup in ``dtype.rst``
  doc/source/reference/c-api/dtype.rst
Labels: 04 - Documentation

#25972 DOC: Fix module setting of ``MaskedArray``
  numpy/ma/core.py
Labels: 04 - Documentation

#25973 DOC: Backport gh-25971 and gh-25972
  doc/source/reference/c-api/dtype.rst
  numpy/ma/core.py
Labels: 04 - Documentation, 08 - Backport

#25970 MAINT: Prepare main for NumPy 2.1.0 development
  doc/source/release.rst
  doc/source/release/2.1.0-notes.rst
  numpy/_core/code_generators/cversions.txt
  pavement.py
  pyproject.toml
Labels: 14 - Release, 03 - Maintenance

#25977 REL: Prepare for the NumPy 2.0.0b1 release [wheel build]
  .mailmap
  doc/changelog/2.0.0-changelog.rst
  doc/source/release/2.0.0-notes.rst
  pyproject.toml
Labels: 14 - Release

#25964 CI: fix last docbuild warnings
  .circleci/config.yml
  doc/source/conf.py
  doc/source/user/how-to-io.rst
  numpy/_core/records.py
  numpy/lib/_npyio_impl.py
  numpy/lib/tests/test_io.py
Labels: 03 - Maintenance, 09 - Backport-Candidate, component: CI

#25983 CI: fix last docbuild warnings
  .circleci/config.yml
  doc/source/conf.py
  doc/source/user/how-to-io.rst
  numpy/_core/records.py
  numpy/lib/_npyio_impl.py
  numpy/lib/tests/test_io.py
Labels: 03 - Maintenance, 08 - Backport, component: CI

#25981 BLD: push a tag builds a wheel
  .github/workflows/wheels.yml
Labels: 09 - Backport-Candidate, 36 - Build

#25986 BLD: push a tag builds a wheel
  .github/workflows/wheels.yml
Labels: 08 - Backport, 36 - Build

#25987 REL: Prepare for the NumPy 2.0.0b1 release (2) [wheel build]
  doc/changelog/2.0.0-changelog.rst
  doc/source/release/2.0.0-notes.rst
Labels: 14 - Release

#25985 BLD: omit pp39-macosx_arm64 from matrix
  .github/workflows/wheels.yml
Labels: 09 - Backport-Candidate, 36 - Build

#25988 DOC: Remove unused parameter description
  numpy/_core/src/multiarray/array_method.c
Labels: 04 - Documentation

#25990 CI: clean up some unused `choco install` invocations
  azure-steps-windows.yml
Labels: component: CI

#25995 CI: don't use `fetch-tags` in wheel build jobs
  .github/workflows/wheels.yml
Labels: 09 - Backport-Candidate, component: CI

#25996 CI: don't use ``fetch-tags`` in wheel build jobs
  .github/workflows/wheels.yml
Labels: 03 - Maintenance, 08 - Backport, component: CI

#25997 REL: Prepare for the NumPy 2.0.0b1 release (3)
  doc/changelog/2.0.0-changelog.rst
  doc/source/release/2.0.0-notes.rst
  numpy/fft/tests/test_pocketfft.py
Labels: 14 - Release

#25974 BUG: Raise error for negative-sized fixed-width dtype
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/tests/test_dtype.py
  numpy/_core/tests/test_numeric.py
Labels: 00 - Bug

#26000 BUG: Filter out broken Highway platform
  numpy/_core/meson.build
Labels: 00 - Bug, 09 - Backport-Candidate, component: SIMD

#25908 ENH: Add center/ljust/rjust/zfill ufuncs for unicode and bytes
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/strings.py
  numpy/_core/tests/test_stringdtype.py
  numpy/_core/tests/test_strings.py
  numpy/_core/umath.py
Labels: 01 - Enhancement

#26008 DOC: mention the `exceptions` namespace in the 2.0.0 release notes
  doc/source/release/2.0.0-notes.rst
Labels: 04 - Documentation

#26009 MAINT: Remove sdist task from pavement.py
  pavement.py
Labels: 03 - Maintenance, 08 - Backport

#26014 MAINT: remove the now-unused `NPY_NO_SIGNAL`
  numpy/_core/include/numpy/_numpyconfig.h.in
  numpy/_core/meson.build
Labels: component: numpy._core, 03 - Maintenance, 09 - Backport-Candidate

#26006 TST: remove usage of ProcessPoolExecutor in stringdtype tests
  numpy/_core/tests/test_stringdtype.py
Labels: 05 - Testing

#25913 NEP: NEP 55 updates and add @mhvk as an author
  doc/neps/_static/nep-0055-arena-string-memory-layout.svg
  doc/neps/_static/nep-0055-heap-string-memory-layout.svg
  doc/neps/_static/nep-0055-short-string-memory-layout.svg
  doc/neps/nep-0055-string_dtype.rst
Labels: component: NEP

#26015 MAINT: remove now-unused `NPY_USE_C99_FORMAT`
  numpy/_core/include/numpy/_numpyconfig.h.in
  numpy/_core/meson.build
Labels: component: numpy._core, 03 - Maintenance, 09 - Backport-Candidate

#26005 DOC: indicate stringdtype support in docstrings for string operations
  doc/release/upcoming_changes/25908.improvement.rst
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/strings.py
Labels: 04 - Documentation, 09 - Backport-Candidate

#26016 MAINT: handle `NPY_ALLOW_THREADS` and related build option better
  doc/source/reference/c-api/array.rst
  numpy/_core/include/numpy/_numpyconfig.h.in
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/meson.build
  numpy/_core/src/common/python_xerbla.c
  numpy/linalg/lapack_lite/python_xerbla.c
Labels: component: numpy._core, 03 - Maintenance, 09 - Backport-Candidate

#25975 BUG: Fixes np.put receiving empty array causes endless loop
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug

#25999 BUG: fix kwarg handling in assert_warn [skip cirrus][skip azp]
  numpy/testing/_private/utils.py
  numpy/testing/tests/test_utils.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26017 MAINT: avoid use of flexible array member in public header
  numpy/_core/include/numpy/ndarraytypes.h
Labels: 03 - Maintenance, 09 - Backport-Candidate

#26012 ENH: install StringDType promoter for add
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/tests/test_stringdtype.py
Labels: 01 - Enhancement, 09 - Backport-Candidate

#26021 BUG: Fix reference leak in niche user old user dtypes
  numpy/core/src/multiarray/usertypes.c
  numpy/core/tests/test_dtype.py
Labels: 00 - Bug, 08 - Backport

#26022 BUG: Fixes np.put receiving empty array causes endless loop
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug, 08 - Backport

#26023 MAINT: Bump pypa/cibuildwheel from 2.16.5 to 2.17.0
  .github/workflows/wheels.yml
Labels: 03 - Maintenance, 08 - Backport

#26024 BUG: raise error trying to coerce object arrays containing timedelta64('NaT') to StringDType
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26025 BUG: fix reference count leak in __array__ internals
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26027 BUG: add missing error handling in string to int cast internals
  numpy/_core/src/multiarray/stringdtype/casts.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26033 MAINT: Remove partition and split-like functions from numpy.strings
  numpy/_core/defchararray.py
  numpy/_core/strings.py
Labels: 03 - Maintenance, 09 - Backport-Candidate

#26035 MAINT: remove the now-unused ``NPY_NO_SIGNAL``
  numpy/_core/include/numpy/_numpyconfig.h.in
  numpy/_core/meson.build
Labels: 03 - Maintenance, 08 - Backport

#26034 MAINT: remove now-unused ``NPY_USE_C99_FORMAT``
  numpy/_core/include/numpy/_numpyconfig.h.in
  numpy/_core/meson.build
Labels: component: numpy._core, 03 - Maintenance, 08 - Backport

#26036 MAINT: handle ``NPY_ALLOW_THREADS`` and related build option better
  doc/source/reference/c-api/array.rst
  numpy/_core/include/numpy/_numpyconfig.h.in
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/meson.build
  numpy/_core/src/common/python_xerbla.c
  numpy/linalg/lapack_lite/python_xerbla.c
Labels: component: numpy._core, 03 - Maintenance, 08 - Backport

#26040 BUG: Filter out broken Highway platform
  numpy/_core/meson.build
Labels: 00 - Bug, 08 - Backport, component: SIMD

#26041 BLD: omit pp39-macosx_arm64 from matrix [wheel build]
  .github/workflows/wheels.yml
Labels: 08 - Backport, 36 - Build

#26042 BUG: fix kwarg handling in assert_warn [skip cirrus][skip azp]
  numpy/testing/_private/utils.py
  numpy/testing/tests/test_utils.py
Labels: 00 - Bug, 08 - Backport

#26048 MAINT: avoid use of flexible array member in public header
  numpy/_core/include/numpy/ndarraytypes.h
Labels: 03 - Maintenance, 08 - Backport

#26047 ENH: install StringDType promoter for add
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/tests/test_stringdtype.py
Labels: 01 - Enhancement, 08 - Backport

#26049 BUG: raise error trying to coerce object arrays containing timedelta64('NaT') to StringDType
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 08 - Backport

#26053 CI: clean up some unused `choco install` invocations
  azure-steps-windows.yml
Labels: 03 - Maintenance, 08 - Backport, component: CI

#26051 BUG: add missing error handling in string to int cast internals
  numpy/_core/src/multiarray/stringdtype/casts.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 08 - Backport

#26050 BUG: fix reference count leak in __array__ internals
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug, 08 - Backport

#26064 MAINT: Make PyArrayMultiIterObject struct "smaller"
  doc/source/reference/c-api/types-and-structures.rst
  numpy/_core/include/numpy/ndarraytypes.h
Labels: 03 - Maintenance, 09 - Backport-Candidate

#26068 DOC: Backport np.strings docstrings
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/strings.py
Labels: 04 - Documentation, 08 - Backport

#26067 DOC: note stringdtype output support in np.strings docstrings
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/strings.py
Labels: 04 - Documentation

#26066 BUG: Allow the new string dtype summation to work
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26052 MAINT: Remove partition and split-like functions from numpy.strings
  numpy/_core/defchararray.py
  numpy/_core/strings.py
Labels: 03 - Maintenance, 08 - Backport

#26070 DOC clarifications on debugging numpy
  doc/source/dev/development_environment.rst
Labels: 04 - Documentation

#26071 BUG: fix logic error in stringdtype maximum/minimum ufunc
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26073 DOC clarifications on debugging numpy
  doc/source/dev/development_environment.rst
Labels: 04 - Documentation, 08 - Backport

#26074 BUG: fix logic error in stringdtype maximum/minimum ufunc
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 08 - Backport

#26075 BUG: Allow the new string dtype summation to work
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 08 - Backport

#26076 MAINT: Make PyArrayMultiIterObject struct "smaller"
  doc/source/reference/c-api/types-and-structures.rst
  numpy/_core/include/numpy/ndarraytypes.h
Labels: 03 - Maintenance, 08 - Backport

#26080 BUG: adapt cython files to new complex declarations
  doc/source/numpy_2_0_migration_guide.rst
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/_core/tests/examples/cython/checks.pyx
  numpy/_core/tests/test_cython.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26089 TYP: Adjust typing for `np.random.integers` and `np.random.randint`
  numpy/random/_generator.pyi
  numpy/random/mtrand.pyi
  numpy/typing/tests/data/reveal/random.pyi
Labels: 09 - Backport-Candidate, Static typing

#26090 API: Require reduce promoters to start with None to match
  numpy/_core/src/umath/dispatching.c
  numpy/_core/src/umath/reduction.c
  numpy/_core/tests/test_stringdtype.py
Labels: 09 - Backport-Candidate, 30 - API

#26085 MAINT: Bump actions/cache from 4.0.1 to 4.0.2
  .github/workflows/linux_qemu.yml
  .github/workflows/macos.yml
Labels: 03 - Maintenance, 08 - Backport

#26099 DOC: fix type in doc/source/user/absolute_beginners.rst
  doc/source/user/absolute_beginners.rst
Labels: 04 - Documentation

#26109 BUG: adapt cython files to new complex declarations (#26080)
  doc/source/numpy_2_0_migration_guide.rst
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/_core/tests/examples/cython/checks.pyx
  numpy/_core/tests/test_cython.py
Labels: 00 - Bug, 08 - Backport

#26110 TYP: Adjust ``np.random.integers`` and ``np.random.randint``
  numpy/random/_generator.pyi
  numpy/random/mtrand.pyi
  numpy/typing/tests/data/reveal/random.pyi
Labels: 08 - Backport, Static typing

#26112 TST: fix incorrect dtype in test
  numpy/_core/tests/test_stringdtype.py
Labels: 05 - Testing

#26111 API: Require reduce promoters to start with None to match
  numpy/_core/src/umath/dispatching.c
  numpy/_core/src/umath/reduction.c
  numpy/_core/tests/test_stringdtype.py
Labels: 08 - Backport, 30 - API

#26118 MAINT: install all-string promoter for multiply
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/tests/test_stringdtype.py
Labels: 03 - Maintenance, 08 - Backport

#26119 BUG: fix reference counting error in stringdtype setup
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
Labels: 00 - Bug, 09 - Backport-Candidate

#26063 MAINT,API: Const qualify some new API (mostly new DType API)
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/types-and-structures.rst
  numpy/_core/include/numpy/dtype_api.h
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/src/multiarray/array_method.c
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/convert_datatype.h
  numpy/_core/src/multiarray/datetime.c
  numpy/_core/src/multiarray/dtype_traversal.c
  numpy/_core/src/multiarray/dtype_traversal.h
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/dtypemeta.h
  numpy/_core/src/multiarray/stringdtype/casts.c
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/src/multiarray/stringdtype/static_string.c
  numpy/_core/src/umath/_scaled_float_dtype.c
  numpy/_core/src/umath/legacy_array_method.c
  numpy/_core/src/umath/legacy_array_method.h
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/src/umath/ufunc_type_resolution.c
  numpy/_core/src/umath/ufunc_type_resolution.h
  numpy/_core/src/umath/wrapping_array_method.c
Labels: 03 - Maintenance, 09 - Backport-Candidate

#26122 BUG: fix reference counting error in stringdtype setup
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
Labels: 00 - Bug, 08 - Backport

#26124 MAINT,API: Const qualify some new API (mostly new DType API)
  doc/source/reference/c-api/array.rst
  doc/source/reference/c-api/types-and-structures.rst
  numpy/_core/include/numpy/dtype_api.h
  numpy/_core/include/numpy/npy_2_compat.h
  numpy/_core/src/multiarray/array_method.c
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/convert_datatype.h
  numpy/_core/src/multiarray/datetime.c
  numpy/_core/src/multiarray/dtype_traversal.c
  numpy/_core/src/multiarray/dtype_traversal.h
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/dtypemeta.h
  numpy/_core/src/multiarray/stringdtype/casts.c
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/src/multiarray/stringdtype/static_string.c
  numpy/_core/src/umath/_scaled_float_dtype.c
  numpy/_core/src/umath/legacy_array_method.c
  numpy/_core/src/umath/legacy_array_method.h
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/src/umath/ufunc_type_resolution.c
  numpy/_core/src/umath/ufunc_type_resolution.h
  numpy/_core/src/umath/wrapping_array_method.c
Labels: 03 - Maintenance, 08 - Backport

#26128 DOC: Update absolute_beginners.rst
  doc/source/user/absolute_beginners.rst
Labels: 04 - Documentation

#26108 MAINT: Remove unnecessarily defensive code from dlpack deleter
  numpy/_core/src/multiarray/dlpack.c
Labels: 03 - Maintenance

#26131 MAINT: add missing noexcept clauses
  numpy/__init__.cython-30.pxd
  numpy/random/_bounded_integers.pxd.in
Labels: 03 - Maintenance, 08 - Backport

#26132 MAINT: add missing noexcept clauses (1/2)
  numpy/__init__.cython-30.pxd
  numpy/random/_bounded_integers.pxd.in
Labels: 03 - Maintenance, 08 - Backport

#26082 ENH: Add partition/rpartition ufunc for string dtypes
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/defchararray.py
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/strings.py
  numpy/_core/tests/test_strings.py
  numpy/_core/umath.py
Labels: 01 - Enhancement

#26149 MAINT: Escalate import warning to an import error
  doc/source/user/troubleshooting-importerror.rst
  numpy/core/_multiarray_umath.py
Labels: 03 - Maintenance

#26154 MAINT: Bump actions/setup-python from 5.0.0 to 5.1.0
  .github/workflows/emscripten.yml
  .github/workflows/linux.yml
  .github/workflows/linux_blas.yml
  .github/workflows/linux_compiler_sanitizers.yml
  .github/workflows/linux_simd.yml
  .github/workflows/macos.yml
  .github/workflows/mypy.yml
  .github/workflows/wheels.yml
  .github/workflows/windows.yml
Labels: 03 - Maintenance, 08 - Backport

#26167 MAINT: Escalate import warning to an import error
  doc/source/user/troubleshooting-importerror.rst
  numpy/core/_multiarray_umath.py
Labels: 03 - Maintenance, 08 - Backport

#26142 BUG,MAINT: Fix __array__ bugs and simplify code
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/ctors.h
  numpy/_core/src/multiarray/methods.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26168 DOC: mention np.lib.NumPyVersion in the 2.0 migration guide
  doc/source/numpy_2_0_migration_guide.rst
Labels: 04 - Documentation, 09 - Backport-Candidate

#26116 ENH: inherit numerical dtypes from abstract ones.
  doc/source/reference/c-api/types-and-structures.rst
  numpy/_core/code_generators/generate_numpy_api.py
  numpy/_core/code_generators/numpy_api.py
  numpy/_core/include/numpy/_public_dtype_api_table.h
  numpy/_core/src/multiarray/abstractdtypes.c
  numpy/_core/src/multiarray/abstractdtypes.h
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/src/multiarray/array_converter.c
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/common.c
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/dtypemeta.h
  numpy/_core/src/multiarray/public_dtype_api.c
  numpy/_core/src/multiarray/usertypes.c
  numpy/_core/src/umath/dispatching.c
  numpy/_core/src/umath/special_integer_comparisons.cpp
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_stringdtype.py
  numpy/_core/tests/test_ufunc.py
Labels: 00 - Bug, 01 - Enhancement, 09 - Backport-Candidate, component: numpy.dtype

#26170 DOC: mention np.lib.NumPyVersion in the 2.0 migration guide
  doc/source/numpy_2_0_migration_guide.rst
Labels: 04 - Documentation, 08 - Backport

#26169 BUG,MAINT: Fix __array__ bugs and simplify code
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/ctors.h
  numpy/_core/src/multiarray/methods.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug, 08 - Backport

#26171 ENH: inherit numerical dtypes from abstract ones.
  doc/source/reference/c-api/types-and-structures.rst
  numpy/_core/code_generators/generate_numpy_api.py
  numpy/_core/code_generators/numpy_api.py
  numpy/_core/include/numpy/_public_dtype_api_table.h
  numpy/_core/src/multiarray/abstractdtypes.c
  numpy/_core/src/multiarray/abstractdtypes.h
  numpy/_core/src/multiarray/array_coercion.c
  numpy/_core/src/multiarray/array_converter.c
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/common.c
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/src/multiarray/dtypemeta.h
  numpy/_core/src/multiarray/public_dtype_api.c
  numpy/_core/src/multiarray/usertypes.c
  numpy/_core/src/umath/dispatching.c
  numpy/_core/src/umath/special_integer_comparisons.cpp
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_stringdtype.py
  numpy/_core/tests/test_ufunc.py
Labels: 00 - Bug, 01 - Enhancement, 08 - Backport, component: numpy.dtype

#26113 BLD: Do not use -O3 flag when building in debug mode
  numpy/_core/meson.build
Labels: 16 - Development, 36 - Build

#26172 DOC/TST: make `numpy.version` officially public
  doc/source/reference/module_structure.rst
  doc/source/reference/routines.version.rst
  numpy/_build_utils/gitversion.py
  numpy/tests/test_numpy_version.py
  numpy/tests/test_public_api.py
Labels: 04 - Documentation, 03 - Maintenance, 09 - Backport-Candidate

#26174 MAINT: Fix failure in routines.version.rst
  doc/source/reference/routines.version.rst
Labels: 00 - Bug, 04 - Documentation, 03 - Maintenance

#26173 DOC, TST: make ``numpy.version`` officially public
  doc/source/reference/module_structure.rst
  doc/source/reference/routines.version.rst
  numpy/_build_utils/gitversion.py
  numpy/tests/test_numpy_version.py
  numpy/tests/test_public_api.py
Labels: 04 - Documentation, 03 - Maintenance, 08 - Backport

#26162 BUG: Infinite Loop in numpy.base_repr
  numpy/_core/numeric.py
  numpy/_core/tests/test_numeric.py
Labels: 00 - Bug, 09 - Backport-Candidate

#26175 REL: Prepare for the NumPy 2.0.0rc1 release [wheel build]
  .mailmap
  doc/changelog/2.0.0-changelog.rst
  doc/source/release/2.0.0-notes.rst
  pyproject.toml
Labels: 14 - Release

#26185 MAINT: Update Pyodide to 0.25.1
  .github/workflows/emscripten.yml
  tools/ci/emscripten/0001-do-not-set-meson-environment-variable-pyodide-gh-4502.patch
Labels: 03 - Maintenance, 09 - Backport-Candidate

#26186 MAINT: Update Pyodide to 0.25.1
  .github/workflows/emscripten.yml
  tools/ci/emscripten/0001-do-not-set-meson-environment-variable-pyodide-gh-4502.patch
Labels: 03 - Maintenance, 08 - Backport
