Repository numpy/numpy, pull requests merged in 2025-01, with the labels that each got.

#28089 MAINT: bump ``mypy`` to ``1.14.1``
  environment.yml
  numpy/_typing/_array_like.py
  numpy/typing/tests/data/reveal/index_tricks.pyi
  requirements/test_requirements.txt
Labels: 03 - Maintenance, Static typing

#28101 DOC: Fix sphinx markup in source/reference/random/extending.rst
  doc/source/reference/random/extending.rst
Labels: 04 - Documentation, component: numpy.random

#28103 MAINT: random: Call np.import_array() in _examples/cython/extending_distributions.pyx
  numpy/random/_examples/cython/extending_distributions.pyx
Labels: component: numpy.random, 03 - Maintenance

#28100 DOC: Move linalg.outer from Decompositions to Matrix and vector products
  doc/source/reference/routines.linalg.rst
Labels: 04 - Documentation

#28102 MAINT: update oldest supported GCC version from 8.4 to 9.3
  .github/workflows/linux_simd.yml
  doc/release/upcoming_changes/28101.change.rst
  meson.build
Labels: 03 - Maintenance

#28090 DOC:Fixed docstring with example use of np.select
  numpy/lib/_function_base_impl.py
Labels: 04 - Documentation

#28080 ENH: Allow an arbitrary number of operands in nditer
  doc/release/upcoming_changes/28080.c_api.rst
  doc/release/upcoming_changes/28080.improvement.rst
  numpy/_core/src/multiarray/nditer_constr.c
  numpy/_core/src/multiarray/nditer_impl.h
  numpy/_core/src/multiarray/nditer_pywrap.c
  numpy/_core/tests/test_nditer.py
Labels: 01 - Enhancement

#28083 MAINT: Update LICENSE Copyright to 2025
  LICENSE.txt
Labels: 03 - Maintenance

#28094 DOC: Fix documentation example for numpy.ma.masked
  doc/source/reference/maskedarray.baseclass.rst
Labels: 04 - Documentation

#28108 TYP: Better ``ndarray`` binop return types for ``float64`` & ``complex128``
  numpy/__init__.pyi
  numpy/_typing/__init__.py
  numpy/_typing/_array_like.py
  numpy/typing/tests/data/reveal/arithmetic.pyi
  numpy/typing/tests/data/reveal/false_positives.pyi
  numpy/typing/tests/data/reveal/mod.pyi
Labels: 09 - Backport-Candidate, Static typing

#28109 TYP: Fix the incorrect ``bool`` return type of ``issubdtype``
  numpy/_core/numerictypes.pyi
Labels: 09 - Backport-Candidate, Static typing

#28114 TYP: Always accept ``date[time]`` in the ``datetime64`` constructor
  numpy/__init__.pyi
  numpy/typing/tests/data/pass/scalars.py
Labels: 08 - Backport, Static typing

#28113 TYP: Return the correct ``bool`` from ``issubdtype``
  numpy/_core/numerictypes.pyi
Labels: 08 - Backport, Static typing

#28120 BUG: Fix auxdata initialization in ufunc slow path
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_nep50_promotions.py
Labels: 00 - Bug, 08 - Backport

#28121 MAINT: Correct NumPy 2.3 C-API versioning and version information
  numpy/_core/code_generators/cversions.txt
  numpy/_core/include/numpy/numpyconfig.h
  numpy/_core/meson.build
Labels: 03 - Maintenance

#28116 MAINT: random: Explicitly cast RAND_INT_MAX to double to avoid compiler warning
  numpy/random/_common.pyx
  numpy/random/src/distributions/distributions.c
Labels: component: numpy.random, 03 - Maintenance

#27789 ENH: Implement np.strings.slice as a gufunc
  doc/release/upcoming_changes/27789.new_function.rst
  doc/source/reference/routines.strings.rst
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/defchararray.py
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/strings.py
  numpy/_core/tests/test_strings.py
  numpy/_core/umath.py
Labels: 01 - Enhancement

#28127 DOC: Improve slice docstrings
  doc/release/upcoming_changes/27789.new_function.rst
  doc/release/upcoming_changes/28102.change.rst
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/_core/strings.py
Labels: 04 - Documentation

#28129 DEP: Deprecate ``numpy.typing.mypy_plugin``
  numpy/typing/mypy_plugin.py
  pytest.ini
Labels: 07 - Deprecation, Static typing

#28130 CI: Fix mypy_primer comment workflow
  .github/workflows/mypy_primer_comment.yml
Labels: 03 - Maintenance, component: CI

#28128 BUG: Don't use C99 construct in import_array
  numpy/_core/code_generators/generate_numpy_api.py
  numpy/_core/code_generators/generate_ufunc_api.py
Labels: 00 - Bug

#28123 BUG: move reduction initialization to ufunc initialization
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/umath/legacy_array_method.c
  numpy/_core/tests/test_multithreading.py
  numpy/testing/_private/utils.py
Labels: 09 - Backport-Candidate, 39 - free-threading

#27869 TYP: Fix ``np.interp`` signature for scalar types
  numpy/lib/_function_base_impl.pyi
  numpy/typing/tests/data/reveal/lib_function_base.pyi
Labels: 09 - Backport-Candidate, Static typing

#28131 BUG: move reduction initialization to ufunc initialization
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/umath/legacy_array_method.c
  numpy/_core/tests/test_multithreading.py
  numpy/testing/_private/utils.py
Labels: 00 - Bug, 08 - Backport, 39 - free-threading

#28132 TYP: Fix ``interp`` to accept and return scalars
  numpy/lib/_function_base_impl.pyi
  numpy/typing/tests/data/reveal/lib_function_base.pyi
Labels: 08 - Backport, Static typing

#28133 BUG: call PyType_Ready in f2py to avoid data races
  numpy/f2py/rules.py
Labels: 00 - Bug, 09 - Backport-Candidate, 39 - free-threading

#28134 DEP: Deprecate ``numpy.typing.mypy_plugin``: The sequel
  doc/release/upcoming_changes/28129.deprecation.rst
  numpy/typing/mypy_plugin.py
Labels: 07 - Deprecation

#28137 BUG: call PyType_Ready in f2py to avoid data races
  numpy/f2py/rules.py
Labels: 00 - Bug, 08 - Backport, 39 - free-threading

#28142 ENH: inline UTF-8 byte counter and make it branchless
  numpy/_core/src/multiarray/stringdtype/utf8_utils.c
  numpy/_core/src/multiarray/stringdtype/utf8_utils.h
Labels: 01 - Enhancement, component: numpy.strings

#28144 BUG: remove unnecessary call to PyArray_UpdateFlags
  numpy/_core/src/multiarray/iterators.c
  numpy/_core/tests/test_multithreading.py
  numpy/testing/_private/utils.py
Labels: 00 - Bug, 09 - Backport-Candidate, 39 - free-threading

#28145 BUG: remove unnecessary call to PyArray_UpdateFlags
  numpy/_core/src/multiarray/iterators.c
  numpy/_core/tests/test_multithreading.py
  numpy/testing/_private/utils.py
Labels: 00 - Bug, 08 - Backport, 39 - free-threading

#28154 BUG: Avoid data race in PyArray_CheckFromAny_int
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/dtypemeta.h
  numpy/_core/tests/test_multithreading.py
  numpy/testing/_private/utils.py
Labels: 00 - Bug, 09 - Backport-Candidate, 39 - free-threading

#28160 BUG: Avoid data race in PyArray_CheckFromAny_int
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/dtypemeta.h
  numpy/_core/tests/test_multithreading.py
  numpy/testing/_private/utils.py
Labels: 00 - Bug, 08 - Backport, 39 - free-threading

#28163 MAINT: Avoid a redundant copy on `a[...] = b`
  numpy/_core/src/multiarray/arrayobject.c
  numpy/_core/tests/test_multiarray.py
Labels: 03 - Maintenance

#28168 TYP: Fix overlapping overloads issue in "2 in, 1 out" ufuncs
  numpy/_typing/_ufunc.pyi
Labels: 09 - Backport-Candidate, Static typing

#28169 TYP: preserve shape-type in ``ndarray.astype()``
  numpy/__init__.pyi
  numpy/_core/numeric.pyi
  numpy/typing/tests/data/reveal/ndarray_conversion.pyi
Labels: Static typing

#28161 DOC: Clarify `np.loadtxt` encoding argument default value in docstring
  numpy/lib/_npyio_impl.py
Labels: 04 - Documentation

#28170 TYP: Fix missing and spurious top-level exports
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/modules.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#28172 BUG: Include Python-including headers first
  numpy/_core/src/common/common.hpp
  numpy/_core/src/common/npstd.hpp
  numpy/_core/src/common/npy_hashtable.cpp
  numpy/_core/src/umath/dispatching.cpp
  numpy/_core/src/umath/fast_loop_macros.h
  numpy/fft/_pocketfft_umath.cpp
Labels: 00 - Bug

#28167 DOC: fix formatting typo in basics.copies.rst
  doc/source/user/basics.copies.rst
Labels: 04 - Documentation

#28177 TYP: preserve shape-type in ndarray.astype()
  numpy/__init__.pyi
  numpy/_core/numeric.pyi
  numpy/typing/tests/data/reveal/ndarray_conversion.pyi
Labels: 08 - Backport, 41 - Static typing

#28178 TYP: Fix missing and spurious top-level exports
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/modules.pyi
Labels: 08 - Backport, 41 - Static typing

#28176 TYP: Fix overlapping overloads issue in 2->1 ufuncs
  numpy/_typing/_ufunc.pyi
Labels: 08 - Backport, 41 - Static typing

#28175 BUG: Fix f2py directives and --lower casing
  numpy/f2py/auxfuncs.py
  numpy/f2py/crackfortran.py
  numpy/f2py/tests/src/regression/lower_f2py_fortran.f90
  numpy/f2py/tests/test_regression.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#28185 MAINT: Prepare 2.2.x for further development
  doc/source/release.rst
  doc/source/release/2.2.3-notes.rst
  pavement.py
  pyproject.toml
Labels: 03 - Maintenance

#28179 DOC: Remove duplicate wishlist tab in NEPs.
  doc/neps/index.rst
Labels: 04 - Documentation

#28189 MAINT, DOC: Add sphinx extension to allow svg images in PDF docs build
  doc/source/conf.py
Labels: 04 - Documentation, 03 - Maintenance

#28186 MAINT: Update main after 2.2.2 release.
  .mailmap
  doc/changelog/2.2.2-changelog.rst
  doc/source/release.rst
  doc/source/release/2.2.2-notes.rst
Labels: 03 - Maintenance

#28201 BUG: fix data race in a more minimal way on stable branch
  numpy/_core/src/multiarray/ctors.c
Labels: 00 - Bug

#28149 BUG: Fix ``from_float_positional`` errors for huge pads
  numpy/_core/src/multiarray/dragon4.c
  numpy/_core/tests/test_scalarprint.py
Labels: 00 - Bug, 09 - Backport-Candidate

#28203 BUG: fix data race in `np.repeat`
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/tests/test_multithreading.py
  numpy/testing/_private/utils.py
Labels: 00 - Bug, 09 - Backport-Candidate, 39 - free-threading

#28208 BUG: Fix ``from_float_positional`` errors for huge pads
  numpy/_core/src/multiarray/dragon4.c
  numpy/_core/tests/test_scalarprint.py
Labels: 00 - Bug, 08 - Backport

#28209 BUG: fix data race in np.repeat
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/tests/test_multithreading.py
  numpy/testing/_private/utils.py
Labels: 00 - Bug, 08 - Backport, 39 - free-threading

#28180 DOC: Update links in HOWTO_RELEASE.rst
  doc/HOWTO_RELEASE.rst
Labels: 04 - Documentation

#28210 corrected the numpy logo visibility issues on darkmode with the proper dark and lighmode logos
  doc/neps/conf.py
Labels: 04 - Documentation

#28148 MAINT: Replace usage of outdated fixed strides with inner strides in …
  numpy/_core/src/umath/reduction.c
Labels: 03 - Maintenance

#28219 DOC: Add versionadded directive for axis argument in trim_zeros function
  numpy/lib/_function_base_impl.py
Labels: 04 - Documentation

#28092 MAINT: LoongArch: switch away from the __loongarch64 preprocessor macro
  numpy/_core/include/numpy/npy_cpu.h
  numpy/_core/src/common/npy_cpu_features.c
Labels: 03 - Maintenance

#28183 MAINT: testing: specify python executable to use in extbuild
  numpy/testing/_private/extbuild.py
Labels: component: numpy.testing, 03 - Maintenance

#28223 MAINT: Add [[maybe_unused] to silence some warnings
  numpy/_core/src/umath/loops_hyperbolic.dispatch.cpp.src
Labels: 03 - Maintenance

#28226 DOC: Clarify ``__array__`` protocol arguments
  doc/source/reference/arrays.classes.rst
Labels: 04 - Documentation

#28230 DOC: FIx a link in Roadmap
  doc/neps/roadmap.rst
Labels: 04 - Documentation

#28235 MAINT: Compile fix for clang-cl on WoA
  numpy/_core/src/multiarray/_multiarray_tests.c.src
Labels: 03 - Maintenance, 09 - Backport-Candidate

#28234 BUG: Add cpp atomic support
  numpy/_core/src/common/npy_atomic.h
Labels: 00 - Bug, 09 - Backport-Candidate

#28228 BUG: handle case when StringDType na_object is nan in float to string cast
  numpy/_core/src/multiarray/stringdtype/casts.cpp
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/src/multiarray/stringdtype/dtype.h
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug

#28236 BUG: Add cpp atomic support (#28234)
  numpy/_core/src/common/npy_atomic.h
Labels: 00 - Bug, 08 - Backport

#28237 BLD: Compile fix for clang-cl on WoA
  numpy/_core/src/multiarray/_multiarray_tests.c.src
Labels: 03 - Maintenance, 08 - Backport, 36 - Build

#26745 ENH, DOC: Add support for interactive examples for NumPy with `jupyterlite-sphinx`
  .gitignore
  doc/Makefile
  doc/neps/roadmap.rst
  doc/release/upcoming_changes/26745.highlight.rst
  doc/source/_static/numpy.css
  doc/source/conf.py
  doc/source/jupyter_lite_config.json
  doc/source/reference/arrays.classes.rst
  doc/source/reference/arrays.datetime.rst
  doc/source/reference/arrays.dtypes.rst
  doc/source/reference/arrays.ndarray.rst
  doc/source/reference/arrays.nditer.rst
  doc/source/reference/arrays.scalars.rst
  doc/source/reference/constants.rst
  doc/source/reference/maskedarray.baseclass.rst
  doc/source/reference/maskedarray.generic.rst
  doc/source/reference/random/generator.rst
  doc/source/reference/random/index.rst
  doc/source/reference/routines.char.rst
  doc/source/reference/routines.polynomials.rst
  doc/source/reference/routines.rec.rst
  doc/source/reference/routines.rst
  doc/source/reference/routines.strings.rst
  doc/source/try_examples.json
  doc/source/user/absolute_beginners.rst
  environment.yml
  numpy/_core/code_generators/ufunc_docstrings.py
  numpy/lib/_polynomial_impl.py
  numpy/linalg/_linalg.py
  requirements/doc_requirements.txt
Labels: 01 - Enhancement, component: documentation

#28241 TYP: Avoid upcasting ``float64`` in the set-ops
  numpy/lib/_arraysetops_impl.pyi
  numpy/typing/tests/data/reveal/arraysetops.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#28243 TYP: Avoid upcasting ``float64`` in the set-ops
  numpy/lib/_arraysetops_impl.pyi
  numpy/typing/tests/data/reveal/arraysetops.pyi
Labels: 08 - Backport, 41 - Static typing

#28242 CI: Fix the github label for `TYP:` PR's and issues
  .github/ISSUE_TEMPLATE/typing.yml
  .github/pr-prefix-labeler.yml
Labels: 03 - Maintenance, component: CI

#28246 BLD: better fix for clang / ARM compiles
  numpy/_core/src/multiarray/_multiarray_tests.c.src
Labels: 09 - Backport-Candidate, 36 - Build

#28249 BLD: better fix for clang / ARM compiles
  numpy/_core/src/multiarray/_multiarray_tests.c.src
Labels: 08 - Backport, 36 - Build

#27343 ENH: Add support for flat indexing on flat iterator
  numpy/_core/src/multiarray/iterators.c
  numpy/_core/tests/test_indexing.py
  numpy/typing/tests/data/pass/flatiter.py
Labels: 01 - Enhancement

#28250 dtype.__repr__: prefer __name__ for user-defined types.
  doc/release/upcoming_changes/28250.improvement.rst
  numpy/_core/_dtype.py
  numpy/_core/tests/test_multiarray.py
Labels: 01 - Enhancement

#28232 BUG: Fix float128 FPE handling on ARM64 with Clang compiler
  numpy/_core/src/npymath/npy_math_internal.h.src
Labels: 00 - Bug
