Repository numpy/numpy, pull requests merged in 2025-03, with the labels that each got.

#28408 DOC: Update link to Nix in Cross Compilation
  doc/source/building/cross_compilation.rst
Labels: 04 - Documentation

#28406 BUG: Include Python.h first
  numpy/_core/src/multiarray/stringdtype/casts.cpp
Labels: 00 - Bug

#28393 BUG: Fix building on s390x with clang
  numpy/_core/src/common/simd/vec/operators.h
Labels: 00 - Bug

#28392 CI: build Linux aarch64 wheels on GitHub Actions
  .github/workflows/wheels.yml
  pyproject.toml
  tools/ci/cirrus_wheels.yml
Labels: component: CI

#28413 DOC: add scimath in np.lib submodules listing
  doc/source/numpy_2_0_migration_guide.rst
Labels: 04 - Documentation

#28414 DOC: Add missing punctuation to the random sampling page
  doc/source/reference/random/index.rst
Labels: 04 - Documentation

#28355 BUG: safer bincount casting
  numpy/_core/src/multiarray/compiled_base.c
  numpy/lib/tests/test_function_base.py
Labels: 00 - Bug, component: numpy._core, 09 - Backport-Candidate

#28420 BUG: safer bincount casting (backport to 2.2.x)
  numpy/_core/src/multiarray/compiled_base.c
  numpy/lib/tests/test_function_base.py
Labels: 00 - Bug, 08 - Backport

#28421 BUG: skip legacy dtype multithreaded test on 32 bit runners
  numpy/_core/tests/test_array_coercion.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_multithreading.py
  numpy/_core/tests/test_regression.py
  numpy/f2py/tests/test_return_real.py
  numpy/f2py/tests/test_semicolon_split.py
  numpy/lib/tests/test_format.py
  numpy/testing/_private/utils.py
Labels: 00 - Bug, 09 - Backport-Candidate

#28422 BUG: Fix building on s390x with clang
  numpy/_core/src/common/simd/vec/operators.h
Labels: 00 - Bug, 08 - Backport

#28423 CI: use QEMU 9.2.2 for Linux Qemu tests
  .github/workflows/linux_qemu.yml
Labels: 03 - Maintenance, 08 - Backport, component: CI

#28424 BUG: skip legacy dtype multithreaded test on 32 bit runners
  numpy/_core/tests/test_array_coercion.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_multithreading.py
  numpy/_core/tests/test_regression.py
  numpy/f2py/tests/test_return_real.py
  numpy/f2py/tests/test_semicolon_split.py
  numpy/lib/tests/test_format.py
  numpy/testing/_private/utils.py
Labels: 00 - Bug, 08 - Backport

#28427 DOC: remove mention of Poly.nickname
  numpy/polynomial/__init__.py
Labels: 04 - Documentation

#28431 MAINT: PY_VERSION_HEX simplify
  numpy/_core/src/multiarray/scalarapi.c
Labels: 03 - Maintenance

#28418 BUG: Fix searchsorted and CheckFromAny byte-swapping logic
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/tests/test_regression.py
Labels: 00 - Bug, 09 - Backport-Candidate

#28415 BLD: update cibuildwheel and build PyPy 3.11 wheels [wheel build]
  .github/workflows/linux.yml
  .github/workflows/wheels.yml
  azure-pipelines.yml
  pyproject.toml
  tools/ci/cirrus_wheels.yml
Labels: 36 - Build

#28436 BUILD: move to manylinux_2_28 wheel builds
  azure-pipelines.yml
  doc/HOWTO_RELEASE.rst
  doc/release/upcoming_changes/28436.change.rst
  pyproject.toml
  tools/wheels/gfortran_utils.sh
Labels: 03 - Maintenance

#28437 DOC: fix documentation for Flag checking functions and macros
  doc/source/reference/c-api/array.rst
Labels: 04 - Documentation

#28444 DOC: fix URL redirects
  README.md
Labels: 04 - Documentation

#28449 BUG: sanity check ``__array_interface__`` number of dimensions
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug, 08 - Backport

#28452 TYP: stub ``random._pickle``
  numpy/random/_pickle.pyi
  numpy/random/meson.build
Labels: 41 - Static typing, numtype

#23752 ENH: speed up matmul for non-contiguous operands #23588
  benchmarks/benchmarks/bench_linalg.py
  numpy/_core/src/umath/matmul.c.src
Labels: 03 - Maintenance

#28330 ENH: Ensure ``lib._format_impl.read_array`` handles file reading errors.
  numpy/lib/_format_impl.py
  numpy/lib/tests/test_format.py
Labels: 01 - Enhancement, component: numpy.lib

#28461 MAINT: Update dependabot.yml file
  .github/dependabot.yml
Labels: 03 - Maintenance

#28462 TYP: Add specializations to meshgrid stubs
  numpy/lib/_function_base_impl.pyi
  numpy/typing/tests/data/reveal/lib_function_base.pyi
Labels: 41 - Static typing

#28451 DOC: Add -avx512_spr to disable AVX512 in build options
  doc/source/reference/simd/build-options.rst
Labels: 04 - Documentation

#28473 DOC: add typing badge to README
  README.md
Labels: 04 - Documentation

#28475 MAINT: skip slow_pypy tests on pypy
  .spin/cmds.py
  doc/release/upcoming_changes/28436.change.rst
Labels: 03 - Maintenance

#28477 MAINT: fix typo in normal distribution functions docstrings
  numpy/random/mtrand.pyx
Labels: 03 - Maintenance

#28263 ENH: Add ARM64 (aarch64) CI testing
  .github/workflows/linux.yml
  .github/workflows/linux_simd.yml
  tools/ci/cirrus_arm.yml
Labels: 01 - Enhancement, component: CI

#28483 DOC: only change tp_name on CPython
  doc/source/conf.py
Labels: 04 - Documentation

#28480 ENH: Convert logical from C universal intrinsics to C++ using Highway
  numpy/_core/meson.build
  numpy/_core/src/umath/loops_logical.dispatch.c.src
  numpy/_core/src/umath/loops_logical.dispatch.cpp
Labels: 01 - Enhancement

#28489 MAINT: Enable building loop_logical on vector length agnostic architectures
  numpy/_core/src/umath/loops_logical.dispatch.cpp
Labels: 03 - Maintenance

#28491 TYP: fix typing errors in ``_core.shape_base``
  numpy/_core/shape_base.pyi
  numpy/typing/tests/data/reveal/array_constructors.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28495 DOC: let docstring mention that unique_values is now unsorted
  numpy/lib/_arraysetops_impl.py
Labels: 04 - Documentation, component: numpy.lib

#28211 MAINT: Hide decorator from pytest traceback
  numpy/_utils/__init__.py
Labels: 03 - Maintenance

#28447 DOC: repositioned bitwise_count under bit-wise operations
  doc/source/reference/routines.bitwise.rst
  doc/source/reference/routines.math.rst
Labels: 04 - Documentation

#28500 TYP: stub `numpy.random._bounded_integers`
  numpy/random/_bounded_integers.pyi
  numpy/random/meson.build
Labels: 41 - Static typing, numtype

#28502 TYP: stub `numpy.random._common`
  numpy/random/_common.pyi
  numpy/random/meson.build
Labels: 41 - Static typing, numtype

#28503 API: Always allow ``sorted=False`` and make a note about it
  numpy/lib/_arraysetops_impl.py
  numpy/lib/tests/test_arraysetops.py
Labels: 30 - API

#28507 MAINT: remove `ma.timer_comparison`
  numpy/ma/timer_comparison.py
  numpy/tests/test_public_api.py
Labels: 03 - Maintenance

#28512 TYP: Typing fixes backported from #28452, #28491, #28494
  numpy/_core/records.pyi
  numpy/_core/shape_base.pyi
  numpy/random/_pickle.pyi
  numpy/random/meson.build
  numpy/typing/tests/data/reveal/array_constructors.pyi
  numpy/typing/tests/data/reveal/rec.pyi
Labels: 08 - Backport, 41 - Static typing

#28510 MAINT: Hide decorator from pytest traceback
  numpy/_utils/__init__.py
Labels: 03 - Maintenance, 08 - Backport

#28505 TYP: stub ``numpy._core.umath``
  numpy/_core/meson.build
  numpy/_core/umath.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28506 TYP: fix typing errors in ``numpy.lib._arrayterator_impl``
  numpy/lib/_arrayterator_impl.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28508 TYP: fix signatures of ``ndarray.put`` and ``ndarray.view``
  numpy/__init__.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28511 TYP: fix stubtest errors in ``numpy._core``
  numpy/_core/fromnumeric.pyi
  numpy/_core/function_base.pyi
  numpy/_core/numeric.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28521 TYP: Backport fixes from #28505, #28506, #28508, and #28511
  numpy/__init__.pyi
  numpy/_core/fromnumeric.pyi
  numpy/_core/function_base.pyi
  numpy/_core/meson.build
  numpy/_core/numeric.pyi
  numpy/_core/umath.pyi
  numpy/lib/_arrayterator_impl.pyi
Labels: 08 - Backport, 41 - Static typing

#28531 ENH: Add Cygwin extensions to list to copy to CWD in f2py meson backend
  numpy/f2py/_backends/_meson.py
Labels: 01 - Enhancement

#28497 TYP: don't use literals in shape-types
  numpy/_core/fromnumeric.pyi
  numpy/_core/multiarray.pyi
  numpy/_core/numeric.pyi
  numpy/typing/tests/data/reveal/fromnumeric.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28509 TYP: annotate the missing ``ufunc.resolve_dtypes`` method
  numpy/__init__.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28513 TYP: stub ``numpy._core.overrides``
  numpy/_core/meson.build
  numpy/_core/overrides.pyi
  numpy/core/overrides.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28514 TYP: stub ``numpy._utils``
  numpy/_utils/__init__.pyi
  numpy/_utils/_convertions.pyi
  numpy/_utils/_inspect.pyi
  numpy/_utils/_pep440.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28515 TYP: stub ``numpy._core._dtype[_ctypes]``
  numpy/_core/_dtype.pyi
  numpy/_core/_dtype_ctypes.pyi
  numpy/_core/meson.build
  numpy/core/_dtype.pyi
  numpy/core/_dtype_ctypes.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28517 TYP: stub the remaining ``numpy._core.*`` modules
  numpy/_core/_add_newdocs.pyi
  numpy/_core/_add_newdocs_scalars.pyi
  numpy/_core/_exceptions.pyi
  numpy/_core/_machar.pyi
  numpy/_core/_methods.pyi
  numpy/_core/_simd.pyi
  numpy/_core/_string_helpers.pyi
  numpy/_core/meson.build
  numpy/_core/printoptions.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28518 TYP: stub the missing submodules of ``numpy.linalg``
  numpy/linalg/_linalg.pyi
  numpy/linalg/_umath_linalg.pyi
  numpy/linalg/lapack_lite.pyi
  numpy/linalg/linalg.pyi
  numpy/linalg/meson.build
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28519 TYP: stub ``numpy._pyinstaller``
  numpy/_pyinstaller/__init__.pyi
  numpy/_pyinstaller/hook-numpy.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28520 TYP: stub ``numpy.fft.helper`` (deprecated)
  numpy/fft/_helper.pyi
  numpy/fft/helper.pyi
  numpy/fft/meson.build
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28523 TYP: annotate the missing deprecated ``row_stack`` function
  numpy/__init__.pyi
  numpy/lib/_shape_base_impl.pyi
  numpy/matlib.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28533 TYP: Backport typing fixes from main (2)
  numpy/__init__.pyi
  numpy/_core/_add_newdocs.pyi
  numpy/_core/_add_newdocs_scalars.pyi
  numpy/_core/_dtype.pyi
  numpy/_core/_dtype_ctypes.pyi
  numpy/_core/_exceptions.pyi
  numpy/_core/_machar.pyi
  numpy/_core/_methods.pyi
  numpy/_core/_simd.pyi
  numpy/_core/_string_helpers.pyi
  numpy/_core/fromnumeric.pyi
  numpy/_core/meson.build
  numpy/_core/multiarray.pyi
  numpy/_core/numeric.pyi
  numpy/_core/overrides.pyi
  numpy/_core/printoptions.pyi
  numpy/_pyinstaller/__init__.pyi
  numpy/_pyinstaller/hook-numpy.pyi
  numpy/_utils/__init__.pyi
  numpy/_utils/_convertions.pyi
  numpy/_utils/_inspect.pyi
  numpy/_utils/_pep440.pyi
  numpy/core/_dtype.pyi
  numpy/core/_dtype_ctypes.pyi
  numpy/core/overrides.pyi
  numpy/fft/_helper.pyi
  numpy/fft/helper.pyi
  numpy/fft/meson.build
  numpy/lib/_shape_base_impl.pyi
  numpy/linalg/_linalg.pyi
  numpy/linalg/_umath_linalg.pyi
  numpy/linalg/lapack_lite.pyi
  numpy/linalg/linalg.pyi
  numpy/linalg/meson.build
  numpy/matlib.pyi
  numpy/typing/tests/data/reveal/fromnumeric.pyi
Labels: 08 - Backport, 41 - Static typing

#28525 TYP: fix stubtest errors in ``numpy.dtype`` and ``numpy.dtypes.*``
  numpy/__init__.pyi
  numpy/dtypes.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28526 TYP: fix stubtest errors in ``timedelta64`` and ``object_``
  numpy/__init__.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28527 TYP: fix stubtest errors in ``numpy.lib._function_base_impl``
  numpy/lib/_function_base_impl.pyi
  numpy/ma/extras.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28528 TYP: fix stubtest errors in ``numpy.lib._arraysetops_impl``
  numpy/lib/_arraysetops_impl.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28529 TYP: fix stubtest errors in ``numpy.lib._index_tricks_impl``
  numpy/__init__.pyi
  numpy/_core/fromnumeric.pyi
  numpy/lib/_index_tricks_impl.pyi
  numpy/typing/tests/data/pass/index_tricks.py
  numpy/typing/tests/data/reveal/fromnumeric.pyi
  numpy/typing/tests/data/reveal/index_tricks.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28534 TYP: Backport typing fixes from main (3)
  numpy/__init__.pyi
  numpy/_core/fromnumeric.pyi
  numpy/dtypes.pyi
  numpy/lib/_function_base_impl.pyi
  numpy/lib/_index_tricks_impl.pyi
  numpy/lib/_twodim_base_impl.pyi
  numpy/ma/extras.pyi
  numpy/typing/tests/data/pass/index_tricks.py
  numpy/typing/tests/data/reveal/fromnumeric.pyi
  numpy/typing/tests/data/reveal/index_tricks.pyi
Labels: 08 - Backport, 41 - Static typing

#28535 TYP: fix stubtest errors in ``numpy._core``
  numpy/_core/_internal.pyi
  numpy/_core/arrayprint.pyi
  numpy/_core/einsumfunc.pyi
  numpy/_core/multiarray.pyi
  numpy/_core/records.pyi
  numpy/typing/tests/data/fail/ndarray_misc.pyi
  numpy/typing/tests/data/pass/ndarray_misc.py
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28536 TYP: fix stubtest errors in ``numpy._globals``
  numpy/_globals.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28537 TYP: fix stubtest errors in ``numpy.mat[rix]lib``
  numpy/matlib.pyi
  numpy/matrixlib/defmatrix.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28538 TYP: fix stubtest errors in ``numpy.random``
  numpy/random/bit_generator.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28539 TYP: fix stubtest errors in ``numpy.testing``
  numpy/testing/__init__.pyi
  numpy/testing/_private/utils.pyi
  numpy/typing/tests/data/fail/testing.pyi
  numpy/typing/tests/data/reveal/testing.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28541 TYP: fix stubtest error in ``numpy.ma``
  numpy/ma/core.pyi
  numpy/ma/extras.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28540 TYP: fix typing errors in ``numpy.ndarray``
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/ndarray_misc.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28542 TYP: Backport typing fixes from main (4)
  numpy/__init__.pyi
  numpy/_core/_internal.pyi
  numpy/_core/arrayprint.pyi
  numpy/_core/einsumfunc.pyi
  numpy/_core/multiarray.pyi
  numpy/_core/records.pyi
  numpy/_globals.pyi
  numpy/ma/core.pyi
  numpy/ma/extras.pyi
  numpy/matlib.pyi
  numpy/matrixlib/defmatrix.pyi
  numpy/random/bit_generator.pyi
  numpy/testing/__init__.pyi
  numpy/testing/_private/utils.pyi
  numpy/typing/tests/data/fail/ndarray_misc.pyi
  numpy/typing/tests/data/fail/testing.pyi
  numpy/typing/tests/data/pass/ndarray_misc.py
  numpy/typing/tests/data/reveal/testing.pyi
Labels: 08 - Backport, 41 - Static typing

#28442 ENH: Check for floating point exceptions in dot
  doc/release/upcoming_changes/28442.improvement.rst
  numpy/_core/src/common/cblasfuncs.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug

#28545 MAINT: Prepare 2.2.x for further development
  doc/source/release.rst
  doc/source/release/2.2.5-notes.rst
  pavement.py
  pyproject.toml
Labels: 03 - Maintenance

#28546 MAINT: Update main after NumPy 2.2.4 release.
  doc/changelog/2.2.4-changelog.rst
  doc/source/release.rst
  doc/source/release/2.2.4-notes.rst
Labels: 03 - Maintenance

#28426 BUG: Limit the maximal number of bins for automatic histogram binning
  doc/release/upcoming_changes/28426.change.rst
  numpy/lib/_histograms_impl.py
  numpy/lib/tests/test_histograms.py
Labels: 00 - Bug

#28577 BUG: avoid deadlocks with C++ shared mutex in dispatch cache
  numpy/_core/src/umath/dispatching.cpp
Labels: 00 - Bug, 09 - Backport-Candidate

#28582 BUG: Fix return type of NpyIter_GetIterNext in Cython declarations
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/_core/tests/examples/cython/checks.pyx
  numpy/_core/tests/test_cython.py
Labels: 00 - Bug, 08 - Backport

#28583 BUG: avoid deadlocks with C++ shared mutex in dispatch cache
  numpy/_core/src/umath/dispatching.cpp
Labels: 00 - Bug, 08 - Backport, 39 - free-threading

#28522 TYP: stub ``numpy.f2py``
  numpy/f2py/__init__.pyi
  numpy/f2py/__version__.pyi
  numpy/f2py/_backends/__init__.pyi
  numpy/f2py/_backends/_backend.pyi
  numpy/f2py/_backends/_distutils.pyi
  numpy/f2py/_backends/_meson.pyi
  numpy/f2py/_isocbind.pyi
  numpy/f2py/_src_pyf.pyi
  numpy/f2py/auxfuncs.pyi
  numpy/f2py/capi_maps.pyi
  numpy/f2py/cb_rules.pyi
  numpy/f2py/cfuncs.pyi
  numpy/f2py/common_rules.pyi
  numpy/f2py/crackfortran.pyi
  numpy/f2py/diagnose.pyi
  numpy/f2py/f2py2e.pyi
  numpy/f2py/f90mod_rules.pyi
  numpy/f2py/func2subr.pyi
  numpy/f2py/rules.pyi
  numpy/f2py/symbolic.pyi
  numpy/f2py/use_rules.pyi
Labels: component: numpy.f2py, 41 - Static typing, numtype

#28498 TYP: accept non-integer shapes in array constructor without a dtype
  numpy/_core/multiarray.pyi
  numpy/_core/numeric.pyi
  numpy/typing/tests/data/fail/multiarray.pyi
  numpy/typing/tests/data/reveal/array_constructors.pyi
Labels: 41 - Static typing

#28492 TYP: fix typing errors in ``_core.strings``
  numpy/_core/strings.pyi
  numpy/typing/tests/data/fail/strings.pyi
  numpy/typing/tests/data/reveal/strings.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, numtype

#28585 TYP: fix typing errors in ``_core.strings``
  numpy/_core/strings.pyi
  numpy/typing/tests/data/fail/strings.pyi
  numpy/typing/tests/data/reveal/strings.pyi
Labels: 08 - Backport, 41 - Static typing, numtype

#28588 MAINT: Remove cibuildwheel workaround [wheel build]
  pyproject.toml
Labels: 03 - Maintenance, 36 - Build

#28569 Fixing various spelling errors
  doc/neps/nep-0021-advanced-indexing.rst
  doc/release/upcoming_changes/28254.expired.rst
  doc/release/upcoming_changes/28569.change.rst
  numpy/_core/src/multiarray/dragon4.c
  numpy/_core/tests/test_scalarprint.py
Labels: 03 - Maintenance, 56 - Needs Release Note.

#28556 NEP 54: Change status to Accepted
  doc/neps/nep-0054-simd-cpp-highway.rst
Labels: component: SIMD

#28141 DOC: Add instructions to build NumPy on WoA
  doc/source/building/index.rst
Labels: 04 - Documentation, triage review

#28591 TYP: Type masked array shape, dtype, __int__, and __float__
  numpy/ma/core.pyi
  numpy/typing/tests/data/fail/ma.pyi
  numpy/typing/tests/data/reveal/ma.pyi
Labels: 41 - Static typing

#28593 TYP: Type ``numpy.ma.min``
  numpy/ma/core.pyi
  numpy/typing/tests/data/fail/ma.pyi
  numpy/typing/tests/data/reveal/ma.pyi
Labels: 41 - Static typing

#28612 TYP: Type ``ma.max`` and ``ma.ptp``
  numpy/ma/core.pyi
  numpy/typing/tests/data/fail/ma.pyi
  numpy/typing/tests/data/reveal/ma.pyi
Labels: 41 - Static typing
