Repository numpy/numpy, pull requests merged in 2025-05, with the labels that each got.

#28870 MNT: retire old script for SVN repositories
  tools/commitstats.py
Labels: 03 - Maintenance

#28876 MNT: discard unused function using os.system()
  numpy/f2py/diagnose.py
Labels: 03 - Maintenance

#28872 DOC: consistent and updated LICENSE files for wheels
  tools/wheels/LICENSE_linux.txt
  tools/wheels/LICENSE_osx.txt
  tools/wheels/LICENSE_win32.txt
Labels: 04 - Documentation

#28874 DOC: `numpy.i` will not be included as part of SWIG
  tools/swig/README
Labels: 04 - Documentation

#28871 MNT: retire script superseded by ruff rule W605
  tools/find_deprecated_escaped_characters.py
Labels: 03 - Maintenance

#28845 TYP: Type ``MaskedArray.nonzero``
  numpy/ma/core.pyi
  numpy/typing/tests/data/reveal/ma.pyi
Labels: component: numpy.ma, 41 - Static typing

#28868 TYP: Type ``MaskedArray.{imag, real, baseclass, mT}``
  numpy/ma/core.pyi
  numpy/typing/tests/data/reveal/ma.pyi
Labels: component: numpy.ma, 41 - Static typing

#28882 MAINT: address warning in SWIG tests
  tools/swig/test/Array2.cxx
Labels: 03 - Maintenance

#28858 TYP: fix the ``set_module`` signature
  numpy/_utils/__init__.pyi
Labels: 41 - Static typing

#28857 TYP: implicit ``linalg`` private submodule re-exports
  numpy/linalg/__init__.pyi
Labels: 41 - Static typing, numtype

#28856 TYP: generic ``StringDType``
  doc/release/upcoming_changes/28856.improvement.rst
  numpy/dtypes.pyi
Labels: 41 - Static typing, component: numpy.strings, numtype

#28859 DOC: Replace http:// with https://
  doc/source/building/index.rst
  doc/source/building/introspecting_a_build.rst
  doc/source/f2py/f2py.getting-started.rst
  doc/source/f2py/windows/index.rst
  doc/source/user/basics.dispatch.rst
  doc/source/user/c-info.python-as-glue.rst
  doc/source/user/numpy-for-matlab-users.rst
Labels: 04 - Documentation

#28879 STY: Apply assorted ruff/refurb rules (FURB)
  benchmarks/benchmarks/__init__.py
  doc/source/reference/simd/gen_features.py
  numpy/_build_utils/tempita/_tempita.py
  numpy/_core/code_generators/generate_umath.py
  numpy/_core/strings.py
  numpy/_pytesttester.py
  numpy/f2py/tests/util.py
  numpy/testing/_private/extbuild.py
Labels: 03 - Maintenance

#28880 TYP: Type ``MaskedArray.all`` and ``MaskedArray.any``
  numpy/ma/core.pyi
  numpy/typing/tests/data/fail/ma.pyi
  numpy/typing/tests/data/reveal/ma.pyi
Labels: 41 - Static typing

#28867 TYP: Type ``MaskedArray.{__setmask__,mask,harden_mask,soften_mask,hardmask,unshare_mask,sharedmask,shrink_mask}``
  numpy/ma/core.py
  numpy/ma/core.pyi
  numpy/typing/tests/data/fail/ma.pyi
  numpy/typing/tests/data/pass/ma.py
  numpy/typing/tests/data/reveal/ma.pyi
Labels: component: numpy.ma, 41 - Static typing

#28893 TYP: remove non-existent extended-precision scalar types
  numpy/__init__.pyi
  numpy/_core/numerictypes.pyi
  numpy/_typing/__init__.py
  numpy/_typing/_extended_precision.py
  numpy/_typing/_nbit_base.py
  numpy/typing/mypy_plugin.py
  numpy/typing/tests/data/misc/extended_precision.pyi
  numpy/typing/tests/test_typing.py
Labels: 41 - Static typing, numtype

#28905 TYP: Test ``MaskedArray.transpose`` and ``MaskedArray.T``, remove unnecessary annotations
  numpy/ma/core.pyi
  numpy/typing/tests/data/reveal/ma.pyi
Labels: component: numpy.ma, 41 - Static typing

#28908 TYP: Fix non-existent ``CanIndex`` annotation in ``ndarray.setfield``
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/array_like.pyi
Labels: 41 - Static typing

#28912 TYP: add ``float64`` overloads to ``{lin,log,geom}space``
  numpy/_core/function_base.pyi
  numpy/typing/tests/data/reveal/array_constructors.pyi
Labels: 41 - Static typing

#28913 TYP: Fix non-existent ``CanIndex`` annotation in ``ndarray.setfield``
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/array_like.pyi
Labels: 08 - Backport, 41 - Static typing

#28892 MAINT: Avoid dereferencing/strict aliasing warnings during complex casts in `npy_math.h` for C++ runs
  numpy/_core/include/numpy/npy_math.h
Labels: 03 - Maintenance, 09 - Backport-Candidate

#28898 BUG: Fix missing check for PyErr_Occurred() in _pyarray_correlate.
  numpy/_core/src/multiarray/multiarraymodule.c
Labels: 00 - Bug, 09 - Backport-Candidate

#28916 BUG: Fix missing check for PyErr_Occurred() in _pyarray_correlate.
  numpy/_core/src/multiarray/multiarraymodule.c
Labels: 00 - Bug, 08 - Backport

#28915 MAINT: Avoid dereferencing/strict aliasing warnings
  numpy/_core/include/numpy/npy_math.h
Labels: 03 - Maintenance, 08 - Backport

#28836 ENH: Provide Windows 11 ARM64 wheels (#22530)
  .github/workflows/wheels.yml
  .github/workflows/windows.yml
  numpy/_core/tests/test_array_interface.py
  numpy/_core/tests/test_cython.py
  numpy/_core/tests/test_limited_api.py
  numpy/_core/tests/test_mem_policy.py
  numpy/distutils/mingw32ccompiler.py
  numpy/distutils/tests/test_mingw32ccompiler.py
  numpy/random/tests/test_extending.py
  pyproject.toml
  tools/wheels/cibw_before_build.sh
Labels: 01 - Enhancement

#28821 BUG: Use unrotated companion matrix in polynomial.polyroots.
  numpy/lib/tests/test_polynomial.py
  numpy/polynomial/polynomial.py
  numpy/polynomial/tests/test_polynomial.py
Labels: 00 - Bug, component: numpy.polynomial

#28931 MAINT: remove py2 ``__div__`` methods from ``lib.user_array.container``
  numpy/lib/_user_array_impl.py
  numpy/lib/_user_array_impl.pyi
  numpy/lib/mixins.py
Labels: 03 - Maintenance

#28929 MAINT: remove py2 ``__div__`` methods from ``poly1d`` and ``ABCPolyBase``
  numpy/__init__.pyi
  numpy/lib/_polynomial_impl.py
  numpy/polynomial/_polybase.py
Labels: 03 - Maintenance

#28928 MNT: add support for 3.14.0b1
  numpy/_core/src/multiarray/temp_elide.c
  pytest.ini
Labels: 03 - Maintenance

#28927 MAINT: Remove outdated ``MaskedArray.__div__`` and ``MaskedArray.__idiv__``
  doc/source/reference/maskedarray.baseclass.rst
  numpy/ma/core.py
  numpy/ma/core.pyi
Labels: component: numpy.ma, 03 - Maintenance

#28935 MAINT: Enable ruff E251
  numpy/lib/tests/test_polynomial.py
  numpy/polynomial/tests/test_polynomial.py
  ruff.toml
  tools/refguide_check.py
  tools/swig/test/setup.py
Labels: 03 - Maintenance

#28938 MNT: clean up free-threaded CI configuration
  .github/workflows/compiler_sanitizers.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/wheels.yml
  .github/workflows/windows.yml
  numpy/random/src/mt19937/mt19937-jump.c
  numpy/random/src/mt19937/mt19937.c
  numpy/random/src/mt19937/mt19937.h
  tools/ci/cirrus_wheels.yml
  tools/wheels/cibw_before_build.sh
  tools/wheels/cibw_test_command.sh
Labels: 03 - Maintenance

#28936 TST: Prevent import error when tests are not included in the wheel
  numpy/_core/tests/_natype.py
  numpy/_core/tests/test_stringdtype.py
  numpy/conftest.py
  numpy/testing/_private/utils.py
Labels: 05 - Testing

#28934 TYP, TST: improved type-testing
  numpy/typing/tests/data/fail/arithmetic.pyi
  numpy/typing/tests/data/fail/array_constructors.pyi
  numpy/typing/tests/data/fail/array_like.pyi
  numpy/typing/tests/data/fail/array_pad.pyi
  numpy/typing/tests/data/fail/arrayprint.pyi
  numpy/typing/tests/data/fail/arrayterator.pyi
  numpy/typing/tests/data/fail/bitwise_ops.pyi
  numpy/typing/tests/data/fail/char.pyi
  numpy/typing/tests/data/fail/chararray.pyi
  numpy/typing/tests/data/fail/comparisons.pyi
  numpy/typing/tests/data/fail/constants.pyi
  numpy/typing/tests/data/fail/datasource.pyi
  numpy/typing/tests/data/fail/dtype.pyi
  numpy/typing/tests/data/fail/einsumfunc.pyi
  numpy/typing/tests/data/fail/flatiter.pyi
  numpy/typing/tests/data/fail/fromnumeric.pyi
  numpy/typing/tests/data/fail/histograms.pyi
  numpy/typing/tests/data/fail/index_tricks.pyi
  numpy/typing/tests/data/fail/lib_function_base.pyi
  numpy/typing/tests/data/fail/lib_polynomial.pyi
  numpy/typing/tests/data/fail/lib_utils.pyi
  numpy/typing/tests/data/fail/lib_version.pyi
  numpy/typing/tests/data/fail/linalg.pyi
  numpy/typing/tests/data/fail/ma.pyi
  numpy/typing/tests/data/fail/memmap.pyi
  numpy/typing/tests/data/fail/modules.pyi
  numpy/typing/tests/data/fail/multiarray.pyi
  numpy/typing/tests/data/fail/ndarray.pyi
  numpy/typing/tests/data/fail/ndarray_misc.pyi
  numpy/typing/tests/data/fail/nditer.pyi
  numpy/typing/tests/data/fail/nested_sequence.pyi
  numpy/typing/tests/data/fail/npyio.pyi
  numpy/typing/tests/data/fail/numerictypes.pyi
  numpy/typing/tests/data/fail/random.pyi
  numpy/typing/tests/data/fail/rec.pyi
  numpy/typing/tests/data/fail/scalars.pyi
  numpy/typing/tests/data/fail/shape.pyi
  numpy/typing/tests/data/fail/shape_base.pyi
  numpy/typing/tests/data/fail/stride_tricks.pyi
  numpy/typing/tests/data/fail/strings.pyi
  numpy/typing/tests/data/fail/testing.pyi
  numpy/typing/tests/data/fail/twodim_base.pyi
  numpy/typing/tests/data/fail/type_check.pyi
  numpy/typing/tests/data/fail/ufunc_config.pyi
  numpy/typing/tests/data/fail/ufunclike.pyi
  numpy/typing/tests/data/fail/ufuncs.pyi
  numpy/typing/tests/data/fail/warnings_and_errors.pyi
  numpy/typing/tests/data/mypy.ini
  numpy/typing/tests/data/pass/ndarray_misc.py
  numpy/typing/tests/data/reveal/nbit_base_example.pyi
  numpy/typing/tests/test_typing.py
Labels: 05 - Testing, 41 - Static typing

#28923 BUG: Use string conversion defined on dtype for .str
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/tests/test_custom_dtypes.py
  numpy/_core/tests/test_dtype.py
Labels: 00 - Bug

#28888 DOC: math mode x to \times in docstring for numpy.linalg.multi_dot
  numpy/linalg/_linalg.py
Labels: 04 - Documentation

#28615 ENH: Upgrade Array API version to 2024.12
  .github/workflows/linux.yml
  doc/release/upcoming_changes/28615.change.rst
  numpy/__init__.py
  numpy/__init__.pyi
  numpy/_core/numeric.pyi
  numpy/_core/src/multiarray/array_api_standard.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/tests/test_regression.py
  numpy/lib/_shape_base_impl.py
  numpy/lib/_shape_base_impl.pyi
  numpy/typing/tests/data/reveal/numeric.pyi
  tools/ci/array-api-xfails.txt
Labels: 01 - Enhancement, 40 - array API standard

#27404 DOC: document type promotion with Python types
  doc/source/reference/arrays.dtypes.rst
  doc/source/reference/arrays.promotion.rst
Labels: 04 - Documentation

#22718 DOC: Add docs on using GitHub Codespaces for NumPy development
  doc/source/dev/development_ghcodespaces.rst
  doc/source/dev/ghcodespaces-imgs/codespaces-codebutton.png
Labels: 04 - Documentation

#28626 DOC: update array API standard version in compatibility page
  doc/source/reference/array_api.rst
Labels: 04 - Documentation

#28941 DOC: Fix titles in ``development_ghcodespaces.rst``
  doc/source/dev/development_ghcodespaces.rst
  doc/source/dev/index.rst
Labels: 04 - Documentation

#28945 MAINT: Enable linting with ruff E501
  .spin/cmds.py
  doc/source/conf.py
  doc/source/reference/random/performance.py
  numpy/ctypeslib/_ctypeslib.py
  numpy/exceptions.py
  numpy/fft/_pocketfft.py
  numpy/fft/tests/test_helper.py
  numpy/testing/_private/extbuild.py
  ruff.toml
Labels: 03 - Maintenance

#28933 MAINT: Use consistent naming for ``numpy/typing/tests/data/fail/ma.pyi``
  numpy/typing/tests/data/fail/ma.pyi
Labels: 03 - Maintenance

#28961 DEP: finalize removal of ``numpy.compat``
  doc/release/upcoming_changes/28961.expired.rst
  numpy/__init__.py
  numpy/_expired_attrs_2_0.py
  numpy/_expired_attrs_2_0.pyi
  numpy/compat/__init__.py
  numpy/compat/py3k.py
  numpy/compat/tests/__init__.py
  numpy/conftest.py
  numpy/lib/_iotools.py
  numpy/meson.build
  numpy/tests/test_public_api.py
Labels: 03 - Maintenance

#28105 ENH: support no-copy pickling for any array that can be transposed to a C-contiguous array
  doc/release/upcoming_changes/28105.improvement.rst
  numpy/_core/numeric.py
  numpy/_core/src/multiarray/methods.c
  numpy/_core/tests/test_multiarray.py
Labels: 01 - Enhancement

#28960 TYP: fix mypy & pyright errors in ``np.matrix``
  numpy/__init__.pyi
Labels: 41 - Static typing

#28959 TYP: remove redundant ``ndarray`` inplace operator overloads
  numpy/__init__.pyi
Labels: 41 - Static typing

#28963 MAINT: Update ruff to 0.11.9 in linting requirements
  numpy/_core/numeric.py
  numpy/_core/tests/test_multiarray.py
  numpy/polynomial/tests/test_polynomial.py
  numpy/random/tests/test_extending.py
  requirements/linter_requirements.txt
  ruff.toml
Labels: 03 - Maintenance

#28755 MNT: Apply assorted ruff/Pylint Refactor rules (PLR)
  numpy/_build_utils/tempita/_tempita.py
  numpy/_core/function_base.py
  numpy/_core/memmap.py
  numpy/_core/numeric.py
  numpy/_core/records.py
  numpy/_core/tests/test_array_coercion.py
  numpy/_core/tests/test_casting_unittests.py
  numpy/_core/tests/test_cpu_features.py
  numpy/_core/tests/test_dtype.py
  numpy/_core/tests/test_indexing.py
  numpy/_core/tests/test_mem_overlap.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_nep50_promotions.py
  numpy/_core/tests/test_stringdtype.py
  numpy/_core/tests/test_ufunc.py
  numpy/f2py/auxfuncs.py
  numpy/f2py/capi_maps.py
  numpy/f2py/cb_rules.py
  numpy/f2py/crackfortran.py
  numpy/f2py/f2py2e.py
  numpy/f2py/f90mod_rules.py
  numpy/f2py/func2subr.py
  numpy/f2py/symbolic.py
  numpy/lib/_format_impl.py
  numpy/lib/_function_base_impl.py
  numpy/lib/_nanfunctions_impl.py
  numpy/lib/_npyio_impl.py
  numpy/lib/_polynomial_impl.py
  numpy/lib/_shape_base_impl.py
  numpy/lib/_twodim_base_impl.py
  numpy/linalg/_linalg.py
  numpy/ma/core.py
  numpy/ma/mrecords.py
  numpy/ma/tests/test_subclassing.py
  numpy/ma/testutils.py
  numpy/matrixlib/tests/test_masked_matrix.py
  numpy/random/tests/test_smoke.py
  numpy/testing/_private/utils.py
  numpy/tests/test_public_api.py
  tools/functions_missing_types.py
Labels: 03 - Maintenance

#28962 TYP: type-testing without the mypy plugin
  numpy/typing/tests/data/mypy.ini
  numpy/typing/tests/data/reveal/ctypeslib.pyi
  numpy/typing/tests/test_typing.py
Labels: 05 - Testing, 07 - Deprecation, 41 - Static typing

#28940 TYP: optional type parameters for ``ndarray`` and ``flatiter``
  doc/release/upcoming_changes/28940.new_feature.rst
  numpy/__init__.pyi
  numpy/_core/defchararray.pyi
  numpy/ma/core.pyi
  numpy/typing/tests/data/pass/literal.py
Labels: 41 - Static typing

#28971 MAINT: Enable linting with ruff E501
  numpy/_build_utils/tempita/_tempita.py
  numpy/lib/_function_base_impl.py
  numpy/lib/_histograms_impl.py
  numpy/lib/_npyio_impl.py
  numpy/lib/recfunctions.py
  numpy/ma/core.py
  numpy/ma/mrecords.py
  ruff.toml
Labels: 03 - Maintenance

#28974 MNT: Get rid of `version: $Id` CVS tags
  numpy/ma/extras.py
  numpy/ma/tests/test_extras.py
  numpy/ma/tests/test_subclassing.py
  numpy/ma/testutils.py
Labels: 03 - Maintenance

#28975 MNT: import numpy as np
  numpy/linalg/_linalg.py
Labels: 03 - Maintenance

#28977 MNT: Enforce ruff/flake8-implicit-str-concat rules (ISC)
  numpy/_core/tests/test_arrayprint.py
  ruff.toml
Labels: 03 - Maintenance

#26958 BUG: index overlap copy
  numpy/_core/src/multiarray/mapping.c
  numpy/_core/tests/test_indexing.py
Labels: 00 - Bug, component: numpy._core

#28765 MNT: Enforce ruff/flake8-bugbear rules (B)
  doc/neps/nep-0016-benchmark.py
  numpy/__init__.py
  numpy/_build_utils/tempita/_looper.py
  numpy/_core/printoptions.py
  numpy/_core/tests/test_array_coercion.py
  numpy/_core/tests/test_deprecations.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_numeric.py
  numpy/f2py/crackfortran.py
  numpy/f2py/f2py2e.py
  numpy/f2py/tests/test_character.py
  numpy/lib/_npyio_impl.py
  numpy/lib/tests/test_function_base.py
  numpy/ma/core.py
  numpy/testing/_private/utils.py
  ruff.toml
  tools/refguide_check.py
Labels: 03 - Maintenance

#28976 MNT: Get rid of Pyflakes / flake8
  doc/source/dev/index.rst
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_nditer.py
  numpy/_core/tests/test_regression.py
  numpy/lib/recfunctions.py
  numpy/lib/tests/test_io.py
  numpy/lib/tests/test_recfunctions.py
  numpy/testing/_private/utils.py
Labels: 03 - Maintenance

#28978 MNT: Enforce ruff/pandas-vet rules (PD)
  doc/source/reference/random/performance.py
  ruff.toml
Labels: 03 - Maintenance

#28987 MNT: Align ruff pin between ``requirements/linter_requirements.txt`` and ``environment.yml``
  environment.yml
  requirements/linter_requirements.txt
Labels: 03 - Maintenance

#28984 MNT: Use isinstance() instead of comparing type()
  numpy/_core/shape_base.py
  numpy/_core/tests/test_nditer.py
  numpy/lib/tests/test_io.py
  numpy/polynomial/_polybase.py
Labels: 03 - Maintenance

#28906 TYP: np.argmin and np.argmax overload changes
  numpy/__init__.pyi
  numpy/_core/fromnumeric.pyi
  numpy/typing/tests/data/fail/fromnumeric.pyi
  numpy/typing/tests/data/pass/ndarray_misc.py
  numpy/typing/tests/data/reveal/fromnumeric.pyi
  numpy/typing/tests/data/reveal/matrix.pyi
  numpy/typing/tests/data/reveal/ndarray_misc.pyi
Labels: 41 - Static typing

#28988 TYP: add missing ``ndarray.__{add,mul}__`` ``character`` type overloads
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/arithmetic.pyi
Labels: 41 - Static typing

#28678 DEP: Deprecate `.T` property for non-2dim arrays and scalars
  doc/release/upcoming_changes/28678.deprecation.rst
  numpy/_core/_add_newdocs.py
  numpy/_core/src/multiarray/getset.c
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/tests/test_deprecations.py
  numpy/_core/tests/test_einsum.py
  numpy/_core/tests/test_indexing.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_nditer.py
  numpy/_core/tests/test_regression.py
  numpy/_core/tests/test_shape_base.py
  numpy/_core/tests/test_ufunc.py
  numpy/fft/tests/test_pocketfft.py
  numpy/lib/_function_base_impl.py
  numpy/lib/_polynomial_impl.py
  numpy/lib/tests/test_stride_tricks.py
  numpy/polynomial/polyutils.py
Labels: 03 - Maintenance, 40 - array API standard

#28995 TYP: remove ``from __future__ import annotations``
  numpy/_core/tests/test_arraymethod.py
  numpy/_core/tests/test_multiarray.py
  numpy/_typing/__init__.py
  numpy/_typing/_array_like.py
  numpy/_typing/_nbit_base.py
  numpy/_typing/_nested_sequence.py
  numpy/f2py/_backends/_backend.py
  numpy/f2py/_backends/_meson.py
  numpy/typing/tests/test_runtime.py
  numpy/typing/tests/test_typing.py
Labels: 41 - Static typing

#28997 MAINT: Prepare 2.2.x for further development
  doc/source/release.rst
  doc/source/release/2.2.7-notes.rst
  pavement.py
  pyproject.toml
Labels: 03 - Maintenance

#29002 MAINT: Update download-wheels for multiple pages
  tools/download-wheels.py
Labels: 03 - Maintenance

#28998 MAINT: Update main after 2.2.6 release.
  doc/changelog/2.2.6-changelog.rst
  doc/source/release.rst
  doc/source/release/2.2.6-notes.rst
Labels: 03 - Maintenance

#28994 TYP: allow inplace division of ``NDArray[timedelta64]`` by floats
  numpy/__init__.pyi
  numpy/typing/tests/data/pass/arithmetic.py
Labels: 41 - Static typing

#29006 ENH: Disable the alloc cache under address and memory sanitizers
  numpy/_core/src/multiarray/alloc.c
Labels: 01 - Enhancement

#28986 TYP: Type ``MaskedArray.__{iadd,isub,imul,itruediv,ifloordiv,ipow}__``
  numpy/ma/core.pyi
  numpy/typing/tests/data/fail/ma.pyi
  numpy/typing/tests/data/pass/ma.py
Labels: component: numpy.ma, 41 - Static typing

#29008 MNT: fix CI issues on main
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  numpy/_core/numeric.py
  numpy/_core/tests/test_numeric.py
Labels: 03 - Maintenance

#28918 DOC: Fixes absent line numbers on link to classes decorated with set_module
  doc/source/conf.py
  numpy/_utils/__init__.py
Labels: 04 - Documentation

#29019 BEG, MAINT: Begin NumPy 2.4.0 development.
  doc/release/upcoming_changes/26018.change.rst
  doc/release/upcoming_changes/26018.performance.rst
  doc/release/upcoming_changes/26745.highlight.rst
  doc/release/upcoming_changes/27288.improvement.rst
  doc/release/upcoming_changes/27789.new_function.rst
  doc/release/upcoming_changes/27883.c_api.rst
  doc/release/upcoming_changes/27883.change.rst
  doc/release/upcoming_changes/27998.c_api.rst
  doc/release/upcoming_changes/28080.c_api.rst
  doc/release/upcoming_changes/28080.improvement.rst
  doc/release/upcoming_changes/28102.change.rst
  doc/release/upcoming_changes/28105.improvement.rst
  doc/release/upcoming_changes/28129.deprecation.rst
  doc/release/upcoming_changes/28205.improvement.rst
  doc/release/upcoming_changes/28214.new_feature.rst
  doc/release/upcoming_changes/28250.improvement.rst
  doc/release/upcoming_changes/28254.expired.rst
  doc/release/upcoming_changes/28343.change.rst
  doc/release/upcoming_changes/28426.change.rst
  doc/release/upcoming_changes/28436.change.rst
  doc/release/upcoming_changes/28442.improvement.rst
  doc/release/upcoming_changes/28569.change.rst
  doc/release/upcoming_changes/28576.new_feature.rst
  doc/release/upcoming_changes/28615.change.rst
  doc/release/upcoming_changes/28619.highlight.rst
  doc/release/upcoming_changes/28619.performance.rst
  doc/release/upcoming_changes/28669.new_feature.rst
  doc/release/upcoming_changes/28703.change.rst
  doc/release/upcoming_changes/28713.change.rst
  doc/release/upcoming_changes/28741.change.rst
  doc/release/upcoming_changes/28769.performance.rst
  doc/release/upcoming_changes/28856.improvement.rst
  doc/release/upcoming_changes/28884.deprecation.rst
  doc/release/upcoming_changes/28940.new_feature.rst
  doc/release/upcoming_changes/28961.expired.rst
  doc/source/release.rst
  doc/source/release/2.4.0-notes.rst
  numpy/_core/code_generators/cversions.txt
  numpy/_core/include/numpy/numpyconfig.h
  pavement.py
  pyproject.toml
Labels: 03 - Maintenance

#29032 BUG: Fix workflow bug
  .github/workflows/windows.yml
Labels: 00 - Bug, 09 - Backport-Candidate, component: CI

#28985 MNT: constant string arrays instead of pointers in C
  numpy/_core/src/common/npy_cpu_features.c
  numpy/_core/src/multiarray/compiled_base.c
  numpy/_core/src/multiarray/stringdtype/casts.cpp
  numpy/_core/src/multiarray/stringdtype/static_string.c
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/f2py/rules.py
Labels: 03 - Maintenance, 09 - Backport-Candidate

#29034 BUG: Avoid compile errors in f2py modules
  numpy/f2py/cfuncs.py
Labels: 00 - Bug, component: numpy.f2py, 09 - Backport-Candidate

#29040 BUG: Fix f2py derived types in modules
  numpy/f2py/auxfuncs.py
  numpy/f2py/auxfuncs.pyi
  numpy/f2py/f90mod_rules.py
  numpy/f2py/tests/src/regression/mod_derived_types.f90
  numpy/f2py/tests/test_regression.py
Labels: component: numpy.f2py, 09 - Backport-Candidate

#28996 ENH: add __array_function__ protocol in polynomial
  numpy/polynomial/polynomial.py
  numpy/polynomial/tests/test_polynomial.py
Labels: 01 - Enhancement

#29043 BUG: Avoid compile errors in f2py modules
  numpy/f2py/cfuncs.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#29044 BUG: Fix f2py derived types in modules
  numpy/f2py/auxfuncs.py
  numpy/f2py/auxfuncs.pyi
  numpy/f2py/f90mod_rules.py
  numpy/f2py/tests/src/regression/mod_derived_types.f90
  numpy/f2py/tests/test_regression.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport

#29046 BUG: Fix cache use regression
  numpy/_core/src/multiarray/alloc.c
Labels: 00 - Bug, 08 - Backport

#29007 CI: update cibuildwheel to 3.0.0b1 and enable cp314 and cp314t nightlies
  .github/workflows/wheels.yml
  tools/wheels/cibw_test_command.sh
Labels: component: CI, 39 - free-threading

#29061 BLD: use sonoma image on Cirrus for wheel build
  tools/ci/cirrus_wheels.yml
Labels: 36 - Build

#29057 TYP: fix invalid overload definition in ``_core.defchararray.add``
  numpy/_core/defchararray.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#29072 MAINT: use pypy 3.11 nightly which has a fix for ctypeslib
  .github/workflows/linux.yml
Labels: 03 - Maintenance, 08 - Backport

#29074 BUG: add bounds-checking to in-place string multiply
  doc/release/upcoming_changes/29060.change.rst
  numpy/_core/src/umath/string_buffer.h
  numpy/_core/src/umath/string_ufuncs.cpp
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/strings.py
  numpy/_core/tests/test_stringdtype.py
  numpy/_core/tests/test_strings.py
  numpy/typing/tests/data/pass/ma.py
Labels: 00 - Bug, 08 - Backport

#29070 TYP: Various typing fixes.
  numpy/_core/defchararray.pyi
  numpy/_core/strings.pyi
  numpy/lib/_user_array_impl.pyi
  numpy/ma/core.pyi
  numpy/strings/__init__.pyi
  numpy/typing/tests/data/reveal/strings.pyi
Labels: 08 - Backport, 41 - Static typing

#29030 MAINT: Convert umath_linalg to multi-phase init (PEP 489)
  doc/release/upcoming_changes/29030.compatibility.rst
  numpy/linalg/umath_linalg.cpp
  numpy/tests/test_lazyloading.py
  numpy/tests/test_reloading.py
Labels: 56 - Needs Release Note.

#29039 BLD: bump OpenBLAS version, use OpenBLAS for win-arm64
  .github/workflows/wheels.yml
  pyproject.toml
  requirements/ci32_requirements.txt
  requirements/ci_requirements.txt
  tools/wheels/cibw_before_build.sh
  tools/wheels/repair_windows.sh
Labels: 09 - Backport-Candidate, 36 - Build

#29082 BLD: bump OpenBLAS version, use OpenBLAS for win-arm64 [wheel build]
  .github/workflows/wheels.yml
  pyproject.toml
  requirements/ci32_requirements.txt
  requirements/ci_requirements.txt
  tools/wheels/cibw_before_build.sh
  tools/wheels/repair_windows.sh
Labels: 08 - Backport, 36 - Build

#29089 MNT: Avoid use of deprecated _PyDict_GetItemStringWithError in f2py
  numpy/f2py/src/fortranobject.c
Labels: component: numpy.f2py, 03 - Maintenance, 08 - Backport, 39 - free-threading

#29095 MAINT: bump `mypy` to `1.16.0`
  environment.yml
  requirements/test_requirements.txt
Labels: 03 - Maintenance

#29092 TYP: fix `NDArray[integer]` inplace operator mypy issue
  numpy/__init__.pyi
  numpy/ma/core.pyi
  numpy/typing/tests/data/fail/arithmetic.pyi
  numpy/typing/tests/data/pass/arithmetic.py
Labels: 09 - Backport-Candidate, 41 - Static typing

#29084 BENCH: Increase array sizes for ufunc and sort benchmarks
  benchmarks/benchmarks/bench_function_base.py
  benchmarks/benchmarks/bench_ufunc_strides.py
Labels: 28 - Benchmark

#29097 TYP: run mypy in strict mode
  numpy/typing/tests/data/mypy.ini
  numpy/typing/tests/data/pass/ma.py
  numpy/typing/tests/data/reveal/nbit_base_example.pyi
Labels: 41 - Static typing

#29101 PERF: Make NpzFile member existence constant time
  numpy/lib/_npyio_impl.py
Labels: 03 - Maintenance, 08 - Backport

#29099 BUG: f2py: thread-safe forcomb (#29091)
  numpy/f2py/cfuncs.py
  numpy/f2py/rules.py
Labels: 00 - Bug, component: numpy.f2py, 08 - Backport, 39 - free-threading
