Repository numpy/numpy, pull requests merged in 2025-06, with the labels that each got.

#29106 DOC: Fix some incorrect reST markups
  doc/changelog/1.21.5-changelog.rst
  doc/neps/nep-0021-advanced-indexing.rst
  doc/neps/nep-0030-duck-array-protocol.rst
  doc/source/dev/internals.code-explanations.rst
  doc/source/reference/c-api/types-and-structures.rst
  doc/source/reference/maskedarray.generic.rst
  doc/source/reference/simd/build-options.rst
  doc/source/release/1.11.0-notes.rst
  doc/source/release/1.13.0-notes.rst
  doc/source/release/1.14.0-notes.rst
  doc/source/release/1.15.0-notes.rst
  doc/source/release/1.18.0-notes.rst
  doc/source/release/1.21.5-notes.rst
  doc/source/user/c-info.ufunc-tutorial.rst
  doc/source/user/how-to-io.rst
  numpy/lib/_polynomial_impl.py
  numpy/lib/_version.py
Labels: 04 - Documentation

#29111 MAINT: fix SPDX license expressions for LAPACK, GCC runtime libs
  tools/wheels/LICENSE_linux.txt
  tools/wheels/LICENSE_osx.txt
  tools/wheels/LICENSE_win32.txt
Labels: 14 - Release, 03 - Maintenance, 09 - Backport-Candidate

#29116 MAINT: Update to vs2022 in NumPy 2.3.x [wheel build]
  .github/workflows/wheels.yml
  .github/workflows/windows.yml
  .github/workflows/windows_arm64.yml
  azure-pipelines.yml
  meson_cpu/x86/meson.build
  numpy/_core/tests/test_umath.py
Labels: 03 - Maintenance

#29118 MAINT: fix SPDX license expressions for LAPACK, GCC runtime libs
  tools/wheels/LICENSE_linux.txt
  tools/wheels/LICENSE_osx.txt
  tools/wheels/LICENSE_win32.txt
Labels: 14 - Release, 03 - Maintenance, 08 - Backport

#29053 BLD: allow targeting webassembly without emscripten
  numpy/_core/include/numpy/npy_cpu.h
Labels: 36 - Build

#29115 MAINT: cleanup from finalized concatenate deprecation
  numpy/_core/src/multiarray/multiarraymodule.c
Labels: 03 - Maintenance

#29122 DOC: fix typo in Numpy's module structure
  doc/source/reference/module_structure.rst
Labels: 04 - Documentation

#29085 MAINT: Bump ``scipy-doctest`` to 1.8
  .github/workflows/linux.yml
  .spin/cmds.py
  numpy/_core/_add_newdocs.py
  numpy/lib/introspect.py
  requirements/doc_requirements.txt
Labels: 03 - Maintenance

#29136 REL: Prepare for the NumPy 2.3.0 release [wheel build]
  .mailmap
  doc/changelog/2.3.0-changelog.rst
  doc/release/upcoming_changes/29060.change.rst
  doc/source/release/2.3.0-notes.rst
  pyproject.toml
Labels: 14 - Release

#29140 MAINT: Prepare 2.3.x for further development
  doc/source/release.rst
  doc/source/release/2.3.1-notes.rst
  pavement.py
  pyproject.toml
Labels: 03 - Maintenance

#29141 MAINT: Update main after 2.3.0 release.
  .mailmap
  doc/changelog/2.3.0-changelog.rst
  doc/source/release/2.3.0-notes.rst
Labels: 03 - Maintenance

#29145 TYP: add missing ``numpy.lib`` exports
  numpy/lib/__init__.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#29146 TYP: fix minor ``f2py`` stub inconsistencies
  numpy/f2py/auxfuncs.pyi
  numpy/f2py/diagnose.pyi
Labels: component: numpy.f2py, 09 - Backport-Candidate, 41 - Static typing

#29094 BUG: remove `NPY_ALIGNMENT_REQUIRED`
  doc/release/upcoming_changes/29094.compatibility.rst
  numpy/_core/include/numpy/npy_cpu.h
  numpy/_core/src/multiarray/common.h
  numpy/_core/src/multiarray/compiled_base.c
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/src/multiarray/lowlevel_strided_loops.c.src
Labels: 00 - Bug

#29147 BUG: Missing array-api ``capabilities()`` key
  numpy/_array_api_info.py
Labels: 00 - Bug, 09 - Backport-Candidate, 40 - array API standard

#29154 DOC: Remove version switcher colors
  doc/source/_static/numpy.css
Labels: 04 - Documentation

#29158 DOC: tweak release walkthrough for numpy.org news blurb
  doc/RELEASE_WALKTHROUGH.rst
Labels: 04 - Documentation

#29148 TST: migrating from pytz to zoneinfo + tzdata (where needed)
  .github/workflows/linux.yml
  environment.yml
  numpy/_core/multiarray.py
  numpy/_core/src/multiarray/_datetime.h
  numpy/_core/src/multiarray/datetime.c
  numpy/_core/tests/test_datetime.py
  numpy/_core/tests/test_deprecations.py
  requirements/doc_requirements.txt
  requirements/emscripten_test_requirements.txt
  requirements/test_requirements.txt
Labels: 05 - Testing

#29177 TYP: ``lib._iotools`` annotation improvements
  numpy/lib/_iotools.pyi
Labels: 41 - Static typing

#29176 TYP: ``any(None)`` and ``all(None)``
  numpy/_core/fromnumeric.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#29175 TYP: Fix invalid inline annotations in ``lib._function_base_impl``
  numpy/lib/_function_base_impl.py
Labels: 41 - Static typing

#29169 TYP: ``out=...`` in ufuncs
  numpy/_typing/_ufunc.pyi
Labels: 41 - Static typing

#29181 TYP: fix and improve ``numpy.lib._utils_impl``
  numpy/lib/_utils_impl.pyi
Labels: 41 - Static typing, numtype

#29155 TYP: ``double = float64`` and ``cdouble = complex128``
  numpy/__init__.pyi
Labels: 41 - Static typing

#29149 CI: Bump `array-api-tests` to `v2025.05.23`
  .github/workflows/linux.yml
  tools/ci/array-api-xfails.txt
Labels: 05 - Testing, component: CI, 40 - array API standard

#29186 MAINT: bump ``ruff`` to ``0.11.13``
  environment.yml
  requirements/linter_requirements.txt
Labels: 03 - Maintenance, Dependencies

#29179 BUG: fix matmul with transposed out arg
  doc/release/upcoming_changes/29179.change.rst
  doc/source/release/2.3.0-notes.rst
  numpy/_core/src/umath/matmul.c.src
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug

#29160 DOC: Suppress distutils doc build warnings for python 3.12+
  doc/source/conf.py
Labels: 04 - Documentation

#29208 ENH: improve Timsort with powersort merge-policy
  numpy/_core/src/npysort/timsort.cpp
Labels: 01 - Enhancement

#29222 TYP: Backport typing fixes
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/ndarray_misc.pyi
Labels: 08 - Backport, 41 - Static typing

#29223 BUG: Address interaction between SME and FPSR
  numpy/_core/meson.build
  numpy/_core/src/common/blas_utils.c
  numpy/_core/src/common/blas_utils.h
  numpy/_core/src/common/cblasfuncs.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/umath/matmul.c.src
  numpy/_core/tests/test_multiarray.py
  numpy/testing/_private/utils.py
Labels: 00 - Bug, 09 - Backport-Candidate

#29230 BUG: avoid negating unsigned integers in resize implementation
  numpy/_core/fromnumeric.py
  numpy/_core/tests/test_numeric.py
Labels: 00 - Bug, 09 - Backport-Candidate

#29234 TST: Fix test that uses unininitialized memory (#29232)
  numpy/_core/tests/test_ufunc.py
Labels: 05 - Testing, 08 - Backport

#29235 BUG: Address interaction between SME and FPSR (#29223)
  numpy/_core/meson.build
  numpy/_core/src/common/blas_utils.c
  numpy/_core/src/common/blas_utils.h
  numpy/_core/src/common/cblasfuncs.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/umath/matmul.c.src
  numpy/_core/tests/test_multiarray.py
  numpy/testing/_private/utils.py
Labels: 00 - Bug, 08 - Backport

#29233 BUG: avoid negating unsigned integers in resize implementation (#29230)
  numpy/_core/fromnumeric.py
  numpy/_core/tests/test_numeric.py
Labels: 00 - Bug, 08 - Backport

#29227 TYP: Support iteration of ``StringDType`` arrays
  numpy/__init__.pyi
Labels: 41 - Static typing

#29237 BUG: Enforce integer limitation in concatenate (#29231)
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/tests/test_shape_base.py
Labels: 00 - Bug, 08 - Backport

#29238 CI: Add support for building NumPy with LLVM for Win-ARM64
  .github/windows_arm64_steps/action.yml
  .github/workflows/wheels.yml
  .github/workflows/windows.yml
Labels: 08 - Backport, component: CI

#29224 ENH: Detect CPU features on FreeBSD / OpenBSD RISC-V64.
  numpy/_core/src/common/npy_cpu_features.c
Labels: 01 - Enhancement, 09 - Backport-Candidate

#29242 ENH: Detect CPU features on FreeBSD / OpenBSD RISC-V64.
  numpy/_core/src/common/npy_cpu_features.c
Labels: 01 - Enhancement, 08 - Backport

#28925 DEP: Deprecate setting the strides attribute of a numpy array
  doc/release/upcoming_changes/28925.deprecation.rst
  numpy/__init__.pyi
  numpy/_core/src/multiarray/getset.c
  numpy/_core/tests/test_api.py
  numpy/_core/tests/test_deprecations.py
  numpy/_core/tests/test_half.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_nditer.py
  numpy/_core/tests/test_regression.py
  numpy/lib/_npyio_impl.py
Labels: 07 - Deprecation

#29252 DOC: Fix some markup errors
  doc/source/f2py/buildtools/distutils-to-meson.rst
  doc/source/reference/random/multithreading.rst
Labels: 04 - Documentation

#29254 DOC: Clarify dtype argument for __array__ in custom container guide
  doc/source/user/basics.dispatch.rst
Labels: 04 - Documentation

#29272 MAINT: Fix ``I001`` ruff error on main
  numpy/_core/__init__.pyi
Labels: 03 - Maintenance

#29248 TYP: Work around a mypy issue with bool arrays
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/array_constructors.pyi
  numpy/typing/tests/data/reveal/ma.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#29271 TYP: Add overloads for `MaskedArray.__{div,rdiv,floordiv,rfloordiv}__`
  numpy/__init__.pyi
  numpy/ma/core.pyi
  numpy/typing/tests/data/reveal/ma.pyi
Labels: component: numpy.ma, 41 - Static typing

#29283 TYP: Work around a mypy issue with bool arrays (#29248)
  environment.yml
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/array_constructors.pyi
  numpy/typing/tests/data/reveal/ma.pyi
  requirements/test_requirements.txt
Labels: 08 - Backport, 41 - Static typing

#29286 BUG: handle case in mapiter where descriptors might get replaced
  numpy/_core/src/multiarray/mapping.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 09 - Backport-Candidate

#29289 BUG: Fix macro redefinition
  .clang-format
  numpy/_core/src/multiarray/alloc.c
Labels: 00 - Bug

#29275 DOC: avoid searching some directories for doxygen-commented source code
  doc/preprocess.py
Labels: 04 - Documentation

#29250 MAINT: Enable linting with ruff E501
  numpy/_core/tests/test_api.py
  numpy/_core/tests/test_shape_base.py
  numpy/lib/tests/test_function_base.py
  numpy/lib/tests/test_io.py
  numpy/lib/tests/test_polynomial.py
  ruff.toml
Labels: 03 - Maintenance

#29143 DOC: Document assertion comparison behavior between scalar and empty array
  numpy/testing/_private/utils.py
Labels: 04 - Documentation

#29290 BUG: Fix version check in blas_utils.c
  numpy/_core/src/common/blas_utils.c
Labels: 00 - Bug

#29291 MAINT: Enable linting with ruff E501
  numpy/_core/tests/test_datetime.py
  numpy/_core/tests/test_multithreading.py
  numpy/_core/tests/test_simd_module.py
  numpy/_core/tests/test_strings.py
  ruff.toml
Labels: 03 - Maintenance
