Repository numpy/numpy, pull requests merged in 2025-02, with the labels that each got.

#28259 TYP: Fix ``timedelta64.__divmod__`` and ``timedelta64.__mod__`` overloads
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/mod.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing, 41 - Static typing

#28258 DOC: Change the scientific page link in NumPy/MATLAB
  doc/source/user/numpy-for-matlab-users.rst
Labels: 04 - Documentation

#28254 MAINT: expire deprecations
  benchmarks/benchmarks/bench_records.py
  doc/release/upcoming_changes/28254.expired.rst
  doc/source/reference/arrays.ndarray.rst
  doc/source/reference/c-api/ufunc.rst
  doc/source/reference/maskedarray.baseclass.rst
  numpy/__init__.cython-30.pxd
  numpy/__init__.pxd
  numpy/__init__.pyi
  numpy/_core/_add_newdocs.py
  numpy/_core/include/meson.build
  numpy/_core/include/numpy/ndarraytypes.h
  numpy/_core/include/numpy/npy_1_7_deprecated_api.h
  numpy/_core/include/numpy/ufuncobject.h
  numpy/_core/src/multiarray/calculation.c
  numpy/_core/src/multiarray/compiled_base.c
  numpy/_core/src/multiarray/conversion_utils.c
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/src/multiarray/datetime.c
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/src/multiarray/mapping.c
  numpy/_core/src/multiarray/methods.c
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/src/multiarray/scalarapi.c
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/src/multiarray/textreading/parser_config.h
  numpy/_core/src/multiarray/textreading/readtext.c
  numpy/_core/src/multiarray/textreading/str_to_int.c
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_conversion_utils.py
  numpy/_core/tests/test_deprecations.py
  numpy/_core/tests/test_indexing.py
  numpy/_core/tests/test_longdouble.py
  numpy/_core/tests/test_multiarray.py
  numpy/_core/tests/test_numeric.py
  numpy/_core/tests/test_records.py
  numpy/_core/tests/test_regression.py
  numpy/_core/tests/test_scalarmath.py
  numpy/_core/tests/test_ufunc.py
  numpy/lib/_user_array_impl.py
  numpy/ma/core.py
  numpy/ma/core.pyi
  numpy/matrixlib/tests/test_defmatrix.py
  numpy/matrixlib/tests/test_masked_matrix.py
  numpy/random/_bounded_integers.pyx.in
  numpy/random/_common.pyx
  numpy/random/_generator.pyx
  numpy/random/mtrand.pyx
  numpy/typing/tests/data/reveal/ndarray_conversion.pyi
Labels: 03 - Maintenance

#28262 TYP: expire deprecations
  numpy/__init__.pyi
Labels: 41 - Static typing

#28266 TYP: Fix ``timedelta64.__divmod__`` and ``timedelta64.__mod__`` overloads
  numpy/__init__.pyi
  numpy/typing/tests/data/reveal/mod.pyi
Labels: 08 - Backport, 41 - Static typing, static typing

#28264 DOC: Remove an invalid link in f2py-examples.rst
  doc/source/f2py/f2py-examples.rst
Labels: 04 - Documentation

#28270 TYP: Fixed missing typing information of set_printoptions
  numpy/_core/arrayprint.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#28274 TYP: Fixed missing typing information of set_printoptions
  numpy/_core/arrayprint.pyi
Labels: 08 - Backport, 41 - Static typing

#28214 ENH: add pkg_config entrypoint
  doc/release/upcoming_changes/28214.new_feature.rst
  numpy/testing/_private/utils.py
  numpy/tests/test_configtool.py
  numpy/tests/test_public_api.py
  pyproject.toml
Labels: 01 - Enhancement

#28273 CI: update sanitizer CI to use python compiled with ASAN and TSAN
  .github/workflows/compiler_sanitizers.yml
  .github/workflows/linux_compiler_sanitizers.yml
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_indexing.py
  numpy/_core/tests/test_multithreading.py
  numpy/_core/tests/test_nep50_promotions.py
  numpy/_core/tests/test_numeric.py
  numpy/_core/tests/test_stringdtype.py
  numpy/conftest.py
  numpy/testing/_private/utils.py
Labels: component: CI, 39 - free-threading

#28276 BUG: fix incorrect bytes to StringDType coercion
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 09 - Backport-Candidate, component: numpy.strings

#28278 BUG: backport resource cleanup bugfix from gh-28273
  numpy/_core/src/umath/ufunc_object.c
Labels: 00 - Bug, 08 - Backport

#28282 BUG: fix incorrect bytes to stringdtype coercion
  numpy/_core/src/multiarray/stringdtype/dtype.c
  numpy/_core/tests/test_stringdtype.py
Labels: 00 - Bug, 08 - Backport, component: numpy.strings

#28279 TYP: Fix scalar constructors
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/scalars.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#28280 TYP: stub ``numpy.matlib``
  numpy/matlib.pyi
  numpy/meson.build
Labels: 09 - Backport-Candidate, 41 - Static typing

#28281 TYP: stub the missing ``numpy.testing`` modules
  numpy/testing/_private/__init__.pyi
  numpy/testing/_private/extbuild.pyi
  numpy/testing/overrides.pyi
  numpy/testing/print_coercion_tables.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#28286 CI: Fix the github label for `TYP:` PR's and issues
  .github/ISSUE_TEMPLATE/typing.yml
  .github/pr-prefix-labeler.yml
Labels: 03 - Maintenance, 08 - Backport, component: CI

#28285 TYP: stub the missing ``numpy.testing`` modules
  numpy/testing/_private/__init__.pyi
  numpy/testing/_private/extbuild.pyi
  numpy/testing/overrides.pyi
  numpy/testing/print_coercion_tables.pyi
Labels: 08 - Backport, 41 - Static typing

#28284 TYP: stub ``numpy.matlib``
  numpy/matlib.pyi
  numpy/meson.build
Labels: 08 - Backport, 41 - Static typing

#28283 TYP: Fix scalar constructors
  numpy/__init__.pyi
  numpy/typing/tests/data/fail/scalars.pyi
Labels: 08 - Backport, 41 - Static typing

#28288 DOC: Correct a typo in Intel License URL
  doc/source/f2py/windows/intel.rst
Labels: 04 - Documentation

#28295 TYP: stub ``numpy._globals``
  numpy/__init__.pyi
  numpy/_globals.pyi
  numpy/meson.build
Labels: 09 - Backport-Candidate, 41 - Static typing

#28296 TYP: stub ``numpy._expired_attrs_2_0``
  numpy/__init__.pyi
  numpy/_expired_attrs_2_0.pyi
  numpy/meson.build
Labels: 09 - Backport-Candidate, 41 - Static typing

#28297 TYP: stub ``numpy._configtool`` and ``numpy._distributor_init``
  numpy/_configtool.pyi
  numpy/_distributor_init.pyi
  numpy/meson.build
Labels: 09 - Backport-Candidate, 41 - Static typing

#28298 TYP: stub ``numpy.lib._iotools``
  numpy/lib/_iotools.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#28299 TYP: stub ``lib.user_array`` and ``lib._user_array_impl``
  numpy/lib/_user_array_impl.pyi
  numpy/lib/user_array.pyi
  numpy/typing/tests/data/pass/lib_user_array.py
Labels: 09 - Backport-Candidate, 41 - Static typing

#28300 TYP: stub ``lib.introspect``
  numpy/lib/introspect.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#28301 TYP: stub ``lib.recfunctions``
  numpy/lib/recfunctions.pyi
  numpy/typing/tests/data/pass/recfunctions.py
Labels: 09 - Backport-Candidate, 41 - Static typing

#28302 TYP: fix and improve ``numpy._core.arrayprint``
  numpy/_core/arrayprint.pyi
  numpy/typing/tests/data/fail/arrayprint.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#28303 TYP: stub ``lib._datasource`` and fix ``lib._npyio_impl``
  numpy/lib/_datasource.pyi
  numpy/lib/_npyio_impl.pyi
  numpy/lib/npyio.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#28305 TYP: Backport typing updates from main
  numpy/__init__.pyi
  numpy/_configtool.pyi
  numpy/_core/arrayprint.pyi
  numpy/_distributor_init.pyi
  numpy/_expired_attrs_2_0.pyi
  numpy/_globals.pyi
  numpy/lib/_datasource.pyi
  numpy/lib/_iotools.pyi
  numpy/lib/_npyio_impl.pyi
  numpy/lib/_user_array_impl.pyi
  numpy/lib/introspect.pyi
  numpy/lib/npyio.pyi
  numpy/lib/recfunctions.pyi
  numpy/lib/user_array.pyi
  numpy/meson.build
  numpy/typing/tests/data/fail/arrayprint.pyi
  numpy/typing/tests/data/pass/lib_user_array.py
  numpy/typing/tests/data/pass/recfunctions.py
Labels: 08 - Backport, 41 - Static typing

#28307 MAINT: bump ``mypy`` to ``1.15.0``
  environment.yml
  numpy/typing/tests/data/mypy.ini
  requirements/test_requirements.txt
Labels: 03 - Maintenance

#28312 DOC: remove references to Python 2
  numpy/_core/tests/test_scalarprint.py
  numpy/testing/tests/test_utils.py
Labels: 04 - Documentation

#28320 MAINT: Update actions/cache and use hash.
  .github/workflows/linux_qemu.yml
Labels: 03 - Maintenance, 09 - Backport-Candidate, component: CI

#28321 BUG: fix race initializing legacy dtype casts
  .github/workflows/compiler_sanitizers.yml
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/dtypemeta.c
  numpy/_core/tests/test_multithreading.py
  numpy/conftest.py
  numpy/testing/_private/utils.py
  requirements/test_requirements.txt
Labels: 00 - Bug, 08 - Backport, 39 - free-threading

#28291 BUG: Prevent class-bound attr mutation in ``lib._iotools.NameValidator``
  numpy/lib/_iotools.py
Labels: 00 - Bug

#28324 CI: update test_moderately_small_alpha [wheel build]
  numpy/random/tests/test_generator_mt19937.py
Labels: 03 - Maintenance, component: CI

#28323 DOC: Correct a typo in Exception TooHardError
  numpy/exceptions.py
Labels: 04 - Documentation

#28333 MAINT: Prepare 2.2.x for further development.
  doc/source/release.rst
  doc/source/release/2.2.4-notes.rst
  pavement.py
  pyproject.toml
Labels: 03 - Maintenance

#28294 MAINT: Enable building tanh on vector length agnostic architectures
  numpy/_core/src/umath/loops_hyperbolic.dispatch.cpp.src
Labels: 03 - Maintenance, 36 - Build

#28335 MAINT: Update main after 2.2.3 release.
  doc/changelog/2.2.3-changelog.rst
  doc/source/release.rst
  doc/source/release/2.2.3-notes.rst
Labels: 03 - Maintenance

#28336 DOC: Update link to Anaconda Eclipse/PyDev documentation
  doc/source/user/troubleshooting-importerror.rst
Labels: 04 - Documentation

#28332 BUG: avoid segfault in np._core.multiarray.scalar
  numpy/_core/src/multiarray/multiarraymodule.c
  numpy/_core/tests/test_dtype.py
Labels: 00 - Bug

#28327 TYP: fix positional- and keyword-only params in ``astype``, ``cross`` and ``linalg``
  numpy/_core/numeric.pyi
  numpy/linalg/_linalg.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#28350 DOC: fix typo
  doc/source/user/how-to-partition.rst
  numpy/lib/_function_base_impl.py
Labels: 04 - Documentation

#28319 BUG: numpy.loadtxt reads only 50000 lines when skip_rows >= max_rows
  numpy/lib/_npyio_impl.py
  numpy/lib/tests/test_loadtxt.py
Labels: 00 - Bug, 09 - Backport-Candidate

#28353 DOC: Make numpy.fft a clickable link to module
  numpy/fft/__init__.py
Labels: 04 - Documentation

#28370 DOC: Revise bullet point formatting in `arrays.promotions.rst`
  doc/source/reference/arrays.promotion.rst
Labels: 04 - Documentation

#28358 MAINT: No need to check for check for FPEs in casts to/from object
  numpy/_core/src/multiarray/convert_datatype.c
  numpy/_core/src/multiarray/dtype_transfer.c
Labels: 03 - Maintenance, 09 - Backport-Candidate

#28379 BUG: numpy.loadtxt reads only 50000 lines when skip_rows >= max_rows
  numpy/lib/_npyio_impl.py
  numpy/lib/tests/test_loadtxt.py
Labels: 00 - Bug, 08 - Backport

#28361 BUG: Make np.nonzero threading safe
  .github/workflows/compiler_sanitizers.yml
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/tests/test_multithreading.py
  tools/ci/tsan_suppressions.txt
Labels: 00 - Bug, 09 - Backport-Candidate, 39 - free-threading

#28385 BUG: Make np.nonzero threading safe
  .github/workflows/compiler_sanitizers.yml
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/tests/test_multithreading.py
  tools/ci/tsan_suppressions.txt
Labels: 00 - Bug, 08 - Backport, 39 - free-threading

#28387 DOC: fix expected exception from StringDType without string coercion
  numpy/_core/_add_newdocs.py
Labels: 04 - Documentation

#28386 MAINT: Extend the default ruff exclude files
  ruff.toml
Labels: 03 - Maintenance

#28390 MAINT: speed up slow test under TSAN
  numpy/_core/tests/test_multithreading.py
Labels: 03 - Maintenance

#28206 BUG: Remove unnecessary copying and casting from out array in choose
  numpy/_core/src/multiarray/item_selection.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug

#28383 DOC: Added links to CTypes and CFFI in Numba
  doc/source/reference/random/extending.rst
Labels: 04 - Documentation

#28404 MAINT: remove legacy ucsnarrow module
  numpy/_core/meson.build
  numpy/_core/src/common/ucsnarrow.c
  numpy/_core/src/common/ucsnarrow.h
  numpy/_core/src/multiarray/arraytypes.c.src
  numpy/_core/src/multiarray/common.h
Labels: 03 - Maintenance
