Repository numpy/numpy, pull requests merged in 2025-07, with the labels that each got.

#29307 TYP: Type ``MaskedArray.{trace,round,cumsum,cumprod}``
  numpy/__init__.pyi
  numpy/ma/core.pyi
  numpy/typing/tests/data/reveal/ma.pyi
Labels: component: numpy.ma, 41 - Static typing

#29305 TYP: add explicit types for np.quantile
  numpy/lib/_function_base_impl.pyi
Labels: 41 - Static typing

#29312 BLD: remove unused github workflow
  .github/workflows/windows_arm64.yml
Labels: 36 - Build

#29309 TYP: Type ``MaskedArray.dot`` and ``MaskedArray.anom``
  numpy/ma/core.pyi
  numpy/typing/tests/data/reveal/ma.pyi
Labels: 41 - Static typing

#29320 DOC: Fix spelling
  doc/source/reference/arrays.classes.rst
Labels: 04 - Documentation

#29327 MAINT: Rename nep-0049.rst.
  doc/neps/nep-0049-data-allocation-strategies.rst
Labels: 03 - Maintenance

#29325 DOC: Clarify assert_allclose differences vs. allclose
  numpy/testing/_private/utils.py
Labels: 04 - Documentation

#29112 ENH: Improve error message in numpy.testing.assert_array_compare
  doc/release/upcoming_changes/29112.improvement.rst
  numpy/testing/_private/utils.py
  numpy/testing/tests/test_utils.py
Labels: 01 - Enhancement, 03 - Maintenance

#29350 BUG: Fix shape error path in array-interface
  numpy/_core/src/multiarray/ctors.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug, 08 - Backport

#29351 BLD: print long double format used
  numpy/_core/meson.build
Labels: 36 - Build

#29240 ENH: Let numpy.size accept multiple axes.
  doc/release/upcoming_changes/29240.new_feature.rst
  numpy/_core/fromnumeric.py
  numpy/_core/fromnumeric.pyi
  numpy/_core/tests/test_numeric.py
Labels: 01 - Enhancement, 56 - Needs Release Note.

#29356 BUG: fix test_npy_uintp_type_enum
  numpy/_core/tests/test_cython.py
Labels: 00 - Bug

#29358 BUG: Fix reference leakage for output arrays in reduction functions
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_ufunc.py
Labels: 00 - Bug, 09 - Backport-Candidate

#29362 DOC: specify that `numpy.nan_to_num` supports array like arguments
  numpy/lib/_type_check_impl.py
Labels: 04 - Documentation

#29369 BUG: fix casting issue in center, ljust, rjust, and zfill
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/tests/test_strings.py
Labels: 00 - Bug

#28983 MAINT: Options to catch more issues reported by pytest
  pytest.ini
Labels: 03 - Maintenance

#29377 TYP: Fix overloads in ``np.char.array`` and ``np.char.asarray`` for ``unicode`` argument
  numpy/_core/defchararray.pyi
  numpy/typing/tests/data/reveal/char.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#29374 DEV: remove "packages" from `.gitignore`
  .gitignore
Labels: 16 - Development

#29386 DOC: Fix `PyArrayMapIterObject` document
  doc/source/reference/c-api/types-and-structures.rst
Labels: 04 - Documentation

#29385 BLD: Add sw_64 support
  numpy/_core/include/numpy/npy_cpu.h
  numpy/_core/include/numpy/npy_endian.h
Labels: 36 - Build

#29381 TYP: Type `MaskedArray.{sum,std,var,mean,prod}`
  numpy/ma/core.pyi
  numpy/typing/tests/data/pass/ndarray_misc.py
  numpy/typing/tests/data/reveal/ma.pyi
Labels: component: numpy.ma, 41 - Static typing

#29321 MNT: Cleanup infs handling in np.testing assertion utilities
  numpy/testing/_private/utils.py
  numpy/testing/tests/test_utils.py
Labels: 03 - Maintenance

#28970 MNT: Enforce ruff/Perflint rules (PERF)
  benchmarks/benchmarks/bench_ufunc.py
  numpy/_core/code_generators/genapi.py
  numpy/f2py/func2subr.py
  numpy/lib/introspect.py
  numpy/ma/testutils.py
  numpy/testing/_private/utils.py
  ruff.toml
Labels: 03 - Maintenance

#29396 ENH: Show unit information in repr for datetime64("NaT")
  doc/release/upcoming_changes/29396.improvement.rst
  numpy/_core/src/multiarray/scalartypes.c.src
  numpy/_core/tests/test_datetime.py
Labels: 01 - Enhancement

#29407 use a stable pypy release in CI
  .github/workflows/linux.yml
Labels: component: CI

#29392 BUG: Any dtype should call `square` on `arr ** 2`
  numpy/_core/src/multiarray/number.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug

#29413 TST: Avoid uninitialized values in test (#29341)
  numpy/_core/tests/test_ufunc.py
Labels: 05 - Testing, 08 - Backport

#29414 BUG: Fix reference leakage for output arrays in reduction functions
  numpy/_core/src/umath/ufunc_object.c
  numpy/_core/tests/test_ufunc.py
Labels: 00 - Bug, 08 - Backport

#29415 BUG: fix casting issue in center, ljust, rjust, and zfill (#29369)
  numpy/_core/src/umath/stringdtype_ufuncs.cpp
  numpy/_core/tests/test_strings.py
Labels: 00 - Bug, 08 - Backport

#29416 TYP: Fix overloads in ``np.char.array`` and ``np.char.asarray`` for ``unicode`` argument.
  numpy/_core/defchararray.pyi
  numpy/typing/tests/data/reveal/char.pyi
Labels: 08 - Backport, 41 - Static typing

#29419 DOC: Fix index name in notes for np.take
  numpy/_core/fromnumeric.py
Labels: 04 - Documentation

#29424 MAINT: use a stable pypy release in CI
  .github/workflows/linux.yml
Labels: 03 - Maintenance, 08 - Backport, component: CI

#29404 TYP: Type ``MaskedArray.reshape``
  numpy/__init__.pyi
  numpy/ma/core.pyi
  numpy/typing/tests/data/reveal/ma.pyi
Labels: component: numpy.ma, 41 - Static typing

#29427 DOC: Remove outdated `numpy.exceptions` compatibility note.
  numpy/exceptions.py
Labels: 04 - Documentation

#29429 MAINT: Update highway to match main.
  numpy/_core/src/_simd/_simd.c
  numpy/_core/src/umath/loops_hyperbolic.dispatch.cpp.src
  numpy/_core/src/umath/loops_trigonometric.dispatch.cpp
Labels: 03 - Maintenance, component: SIMD

#29437 BUG: fix datetime/timedelta hash memory leak (#29411)
  numpy/_core/src/multiarray/scalartypes.c.src
Labels: 00 - Bug, 08 - Backport

#29435 BUG: Fix test_configtool_pkgconfigdir to resolve PKG_CONFIG_DIR symli…
  numpy/tests/test_configtool.py
Labels: 00 - Bug, 09 - Backport-Candidate

#29440 MAINT: Prepare 2.3.x for further development.
  doc/source/release.rst
  doc/source/release/2.3.3-notes.rst
  pavement.py
  pyproject.toml
Labels: 03 - Maintenance

#29441 MAINT: Update main after 2.3.2 release.
  doc/changelog/2.3.2-changelog.rst
  doc/source/release.rst
  doc/source/release/2.3.2-notes.rst
Labels: 03 - Maintenance

#29436 BLD: allow targeting webassembly without emscripten
  numpy/_core/src/multiarray/lowlevel_strided_loops.c.src
Labels: 09 - Backport-Candidate, 36 - Build

#29445 DOC: Update RELEASE_WALKTHROUGH.rst
  doc/RELEASE_WALKTHROUGH.rst
Labels: 04 - Documentation, 03 - Maintenance

#29456 MAINT: Replace pavement.py
  doc/RELEASE_WALKTHROUGH.rst
  pavement.py
  requirements/release_requirements.txt
  tools/write_release.py
Labels: 03 - Maintenance

#29428 TYP: Add test which hits `np.array` constructor overload with `object: _SupportsArray[_ArrayT]`
  numpy/typing/tests/data/reveal/array_constructors.pyi
Labels: 41 - Static typing

#29467 TYP: Type ``MaskedArray.recordmask``
  numpy/ma/core.pyi
  numpy/typing/tests/data/fail/ma.pyi
  numpy/typing/tests/data/reveal/ma.pyi
Labels: component: numpy.ma, 41 - Static typing

#29470 TYP: Remove ``MaskedArray.__reduce__``, and punt on ``MaskedArray.__{eq,ne}__``
  numpy/ma/core.pyi
Labels: component: numpy.ma, 41 - Static typing

#29468 TYP: Type ``MaskedArray.fill_value``
  numpy/ma/core.pyi
  numpy/typing/tests/data/pass/ma.py
  numpy/typing/tests/data/reveal/ma.pyi
Labels: component: numpy.ma, 41 - Static typing

#29450 DOC: Clarify that `numpy.printoptions` applies only to `ndarray`, not…
  numpy/_core/arrayprint.py
Labels: 04 - Documentation

#29403 MAINT: remove unnecessary `kwargs` update in `MaskedArray.reshape`
  numpy/ma/core.py
Labels: component: numpy.ma, 03 - Maintenance

#29489 DOC: Add 'See Also' refs for sign, copysign and signbit.
  numpy/_core/code_generators/ufunc_docstrings.py
Labels: 04 - Documentation

#29493 MAINT: bump `mypy` to `1.17.1`
  environment.yml
  requirements/test_requirements.txt
Labels: 03 - Maintenance, 41 - Static typing, Dependencies
