Repository numpy/numpy, pull requests merged in 2025-08, with the labels that each got.

#29500 BUG: Always return a real dtype from linalg.cond (gh-18304) (#29333)
  numpy/linalg/_linalg.py
  numpy/linalg/tests/test_linalg.py
Labels: 00 - Bug, 08 - Backport

#29459 BLD: provide explicit control over cpu-baseline detection
  doc/source/reference/simd/build-options.rst
  meson.options
  meson_cpu/meson.build
Labels: 36 - Build

#29504 ENH: Use extern C in arraytypes.h.src file for cpp files
  numpy/_core/src/multiarray/arraytypes.h.src
Labels: 01 - Enhancement

#29505 BUG: Casting from one timedelta64 to another didn't handle NAT.
  numpy/_core/src/multiarray/datetime.c
  numpy/_core/tests/test_datetime.py
Labels: 00 - Bug, component: numpy._core, component: numpy.datetime64

#29513 MAINT: Bump hypothesis to 6.137.1
  requirements/test_requirements.txt
Labels: 03 - Maintenance

#29487 CI: Add UBSAN CI jobs for macOS arm64 and Linux x86-64
  .github/workflows/compiler_sanitizers.yml
  tools/ci/ubsan_suppressions_arm64.txt
  tools/ci/ubsan_suppressions_x86_64.txt
Labels: component: CI

#29532 DOC:Clarify build compatibility to dev depending page
  doc/source/dev/depending_on_numpy.rst
Labels: 04 - Documentation

#29514 DOC: Add 'today' string to datetime64 documentation
  doc/source/reference/arrays.datetime.rst
Labels: 04 - Documentation, component: numpy.datetime64

#29535 BLD: update licensing metadata to use PEP 639
  LICENSES_bundled.txt
  meson.build
  numpy/_core/src/multiarray/dragon4_LICENSE.txt
  pyproject.toml
  tools/wheels/check_license.py
  tools/wheels/cibw_before_build.sh
Labels: 01 - Enhancement, 14 - Release, 36 - Build, Meson

#29556 BUG: Casting from one timedelta64 to another didn't handle NAT.
  numpy/_core/src/multiarray/datetime.c
  numpy/_core/tests/test_datetime.py
Labels: 00 - Bug, component: numpy._core, 08 - Backport, component: numpy.datetime64

#29563 BUG: Fix metadata not roundtripping when pickling datetime (#29555)
  numpy/_core/src/multiarray/descriptor.c
  numpy/_core/tests/test_datetime.py
Labels: 00 - Bug, 08 - Backport

#29586 TYP: add ``sorted`` kwarg to ``unique``
  numpy/lib/_arraysetops_impl.pyi
Labels: 09 - Backport-Candidate, 41 - Static typing

#29593 TYP: add ``sorted`` kwarg to ``unique``
  numpy/lib/_arraysetops_impl.pyi
Labels: 41 - Static typing

#29601 DOC: fix for f2py migrating-to-meson page
  doc/source/f2py/buildtools/distutils-to-meson.rst
Labels: 04 - Documentation

#29579 BLD: wire up `ASIMDDP` feature to `ARM_FEATURES`
  meson_cpu/arm/meson.build
Labels: 36 - Build

#29603 TYP: Add defaults to stubs in ``numpy/lib``
  numpy/lib/_array_utils_impl.pyi
  numpy/lib/_arraypad_impl.pyi
  numpy/lib/_function_base_impl.pyi
  numpy/lib/_histograms_impl.pyi
  numpy/lib/_index_tricks_impl.pyi
  numpy/lib/_npyio_impl.pyi
  numpy/lib/_polynomial_impl.pyi
  numpy/lib/_shape_base_impl.pyi
  numpy/lib/_stride_tricks_impl.pyi
  numpy/lib/_twodim_base_impl.pyi
  numpy/lib/_ufunclike_impl.pyi
Labels: 41 - Static typing

#29137 BUG: make round consistently return a copy
  doc/release/upcoming_changes/29137.compatibility.rst
  numpy/_core/src/multiarray/calculation.c
  numpy/_core/tests/test_multiarray.py
Labels: 00 - Bug

#29605 TST: Replace xunit setup with methods
  numpy/_core/tests/test_half.py
  numpy/_core/tests/test_indexing.py
  numpy/_core/tests/test_numerictypes.py
  numpy/_core/tests/test_records.py
Labels: 05 - Testing

#29613 CI: only test pyodide
  .github/workflows/emscripten.yml
Labels: component: CI

#29630 TYP: fix slightly incorrect ``memoryview`` type argument in ``ScalarType``
  numpy/_core/numerictypes.pyi
  numpy/typing/tests/data/reveal/numerictypes.pyi
Labels: 41 - Static typing, numtype

#29372 BUG: Fix np.unique with axis=0 and 1D input not collapsing NaNs with equal_nan=True #29336
  numpy/lib/_arraysetops_impl.py
  numpy/lib/tests/test_arraysetops.py
Labels: 00 - Bug
